### ISSUE TITLE
Problem with accented characters

### ISSUE THREAD

**Issue by mlaloux** [gboeing/osmnx#1]
Hello,

With Python 2.7.x, if they are accented characters in the name of the edge, there is an unicode error when saving to shapefiles

lines 1998-1999

          for col in [c for c in gdf_edges.columns if not c == 'geometry']: `
          `     gdf_edges[col] = gdf_edges[col].fillna('').astype(str)`

The solution is to replace with `unicode`

 `     gdf_edges[col] = gdf_edges[col].fillna('').astype('unicode')` 

Because, if I break down the script

    place = 'Louvain-la-Neuve, Belgium'
    G = ox.graph_from_place(place, network_type='drive')
    G_projected = ox.project_graph(G)

    import networkx as nx
    G_save = G_projected.copy()
    G_save = G_save.to_undirected()

    edges = []
    for u, v, key, data in G_save.edges(keys=True, data=True):
          # for each edge, add key and all attributes in data dict to the edge_details
          edge_details = {'key':key}
          for attr_key in data:
              #print attr_key, 
               edge_details[attr_key] = data[attr_key]
         edges.append(edge_details)

    print edges[0]
    {'name': u'Avenue Ath\xe9na', 'geometry': <shapely.geometry.linestring.LineString object at 0x11b02e050>, 'length': 26.273919709432, 'key': 0, 'oneway': True, 'highway':   
     edges[0]['name']
     u'Avenue Ath\xe9na'
     print edges[0]['name']
     Avenue Athéna

But 

    str(edges[0]['name']) 

gives an UnicodeEncodeError

**Comment by gboeing** [comment]
Good catch. We can't replace astype(str) with astype(unicode) though, because python 3 has no unicode type. I fixed it by mapping a function that abstracts strings and unicode types for python 2 and 3 gracefully. Should be working now -- just pushed the fix. Please check and confirm.

**Comment by mlaloux** [comment]
It works now, thanks
I have attempted another solution with

     from __future__ import unicode_literals. 

creating other  problems/
