### ISSUE TITLE
Making a map of anything that intersects the Gulf of Maine is very slow

### ISSUE THREAD

**Issue by llimllib** [gboeing/osmnx#1050]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Python 3.10.12, OS X Ventura 13.4

### What OSMnx version are you using?

1.6.0

### Environment packages and versions

```shell
$ pip list
Package            Version
------------------ -----------
attrs              23.1.0
certifi            2023.7.22
charset-normalizer 3.2.0
click              8.1.7
click-plugins      1.1.1
cligj              0.7.2
Fiona              1.9.4.post1
geopandas          0.13.2
idna               3.4
networkx           3.1
numpy              1.25.2
osmnx              1.6.0
packaging          23.1
pandas             2.0.3
pip                23.0.1
pyproj             3.6.0
python-dateutil    2.8.2
pytz               2023.3
requests           2.31.0
setuptools         65.5.0
shapely            2.0.1
six                1.16.0
tzdata             2023.3
urllib3            2.0.4
```

### How did you install OSMnx?

Pip

### Problem description

The Gulf of Maine has a [very intricate OSM representation](https://polygons.openstreetmap.fr/?id=13663366), and using `osmnx` with anything that intersects it is very slow.

See [this issue](https://github.com/chrieke/prettymapp/issues/26) for how I discovered this issue.

The script below takes ~5 minutes to run `features_from_polygon` on a small area. I've removed all the tags but `natural`, since that is enough to reproduce.

<img width="514" alt="image" src="https://github.com/gboeing/osmnx/assets/7150/463d5235-11ce-478a-ae3b-7195e7c78b17">

```
$ time python test.py
python test.py  321.67s user 22.32s system 100% cpu 5:41.56 total
```

Is there anything that could be done to make this faster, or is it an irreducible slowdown?

### Complete minimal reproducible example

```python
from shapely.geometry import Point
from osmnx.features import features_from_polygon

p = Point(-70.24, 43.65).buffer(0.01)
tags = {
    "natural": ["water", "bay", "island", "wood"],
}
df = features_from_polygon(polygon=p, tags=tags)
```

A profile of that script shows that `_subtract_inner_polygons_from_outer_polygons` takes up pretty much all the time:

```
         3037162 function calls (3017718 primitive calls) in 339.025 seconds

   Ordered by: cumulative time
   List reduced from 4654 to 15 due to restriction <15>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    975/1    0.003    0.000  339.025  339.025 {built-in method builtins.exec}
        1    0.000    0.000  339.025  339.025 test.py:1(<module>)
        1    0.034    0.034  338.485  338.485 .venv/lib/python3.10/site-packages/osmnx/features.py:286(features_from_polygon)
        1    0.154    0.154  338.451  338.451 .venv/lib/python3.10/site-packages/osmnx/features.py:380(_create_gdf)
        1    0.000    0.000  337.257  337.257 .venv/lib/python3.10/site-packages/osmnx/features.py:719(_parse_relation_to_multipolygon)
        1    0.636    0.636  337.008  337.008 .venv/lib/python3.10/site-packages/osmnx/features.py:860(_subtract_inner_polygons_from_outer_polygons)
    48412    0.091    0.000  336.684    0.007 .venv/lib/python3.10/site-packages/shapely/decorators.py:62(wrapped)
     3241    0.005    0.000  262.813    0.081 .venv/lib/python3.10/site-packages/shapely/geometry/base.py:568(difference)
     3241  262.786    0.081  262.786    0.081 .venv/lib/python3.10/site-packages/shapely/set_operations.py:21(difference)
     3241    0.008    0.000   73.559    0.023 .venv/lib/python3.10/site-packages/shapely/geometry/base.py:712(within)
     3241   73.514    0.023   73.514    0.023 .venv/lib/python3.10/site-packages/shapely/predicates.py:897(within)
```

**Comment by gboeing** [comment]
An interesting problem, but no simple answer. A couple thoughts.

First, if you know the OSM ID of the element of interest (in this case, the Gulf of Maine), you can try retrieving it from the Nominatim API instead of the Overpass API, like this:
```python
ox.geocode_to_gdf("R13663366", by_osmid=True)
```
It will be much faster.

Second, regarding your specific inquiry about `_subtract_inner_polygons_from_outer_polygons`, there's no real workaround for that slow performance right now. But if you are curious and interested, I'd welcome a performance enhancing PR if you can find a way to make it more efficient.

**Comment by gboeing** [comment]
I'll close this for now, but if someone is interested in proposing a PR for relevant performance enhancements, I'm happy to review it in the future.

**Comment by llimllib** [comment]
I considered (but didn't go as far as implementing) a keyword option that would allow you to specify that you don't want multipolygons with parts outside the AOI to have their inner nodes subtracted. Would you be interested in that?

Basically, the idea is this: In the script above, I _do_ want to get the Gulf of Maine in the response, but I also don't want `osmnx` to spend 5 minutes subtracting all the tiny Islands that are very far away from my AOI, so I would be happy to accept the GoM polygon, with any inner areas that overlap my AOI subtracted but not others, in exchange for speed.

Alternatively, I considered simply adding the ability to limit "monster polygons" (using the term from [this discussion](https://community.openstreetmap.org/t/gulf-of-mexico-object-rendering-of-large-seas/7466/24)) - other examples include the Labrador Sea and the Chesapeake Bay. In this scenario, you'd just return a simplified object (or something?) if you found a multipolygon with many (> 500 maybe?) references.
