### ISSUE TITLE
Simplified edges have the same reversed attributes despite being reversed

### ISSUE THREAD

**Issue by pmlpm1986** [gboeing/osmnx#1056]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Debian Bookworm

### What OSMnx version are you using?

1.5.0

### Environment packages and versions

```shell
Fiona                         1.9.4.post1
geopandas                     0.13.2
geopy                         2.3.0
matplotlib                    3.7.1
networkx                      3.1
numpy                         1.24.3
osmnx                         1.5.0
pandas                        2.0.2
pyogrio                       0.6.0
pyproj                        3.5.0
pyproject_hooks               1.0.0
rasterio                      1.3.6
requests                      2.29.0
scikit-learn                  1.2.2
shapely                       2.0.1
```

### How did you install OSMnx?

Pip

### Problem description

While using osmnx, I realised that the MultiDiGraph object I get contains simplified edges for the forward and reverse directions. That is, the simplified edges are made of the same simpler edges. However, the reversed attributes in these are identical even though the geometry is not (it is reversed) and the osmids appear in the same order. Is this a bug? It strikes me as wrong to have the geometry reversed and not the reversed attribute too, since that is what happens in the standard case (see below).

### Complete minimal reproducible example

```python
import osmnx as ox
G = ox.graph_from_bbox(north=55.68070,south=55.67957,west=12.25981,east=12.26271)
#************************************************************************************************
# the standard case (unsimplified)
#************************************************************************************************
arc_key_forward=(3411585490,1495987314,0)
arc_key_reverse=(1495987314,3411585490,0)
# it is unsimplified
assert type(G.edges[arc_key_forward]['osmid']) != list
assert type(G.edges[arc_key_reverse]['osmid']) != list
# the osmids are the same
assert G.edges[arc_key_forward]['osmid'] == G.edges[arc_key_reverse]['osmid']
# the reversed attributes are logical opposites
assert G.edges[arc_key_forward]['reversed'] == (not G.edges[arc_key_reverse]['reversed'])
# the geometry is equivalent...
assert G.edges[arc_key_forward]['geometry'].equals(G.edges[arc_key_reverse]['geometry'])
assert G.edges[arc_key_forward]['geometry'].equals(G.edges[arc_key_reverse]['geometry'].reverse())
# ... and is reversed
assert not tuple(G.edges[arc_key_forward]['geometry'].coords) == tuple(G.edges[arc_key_reverse]['geometry'].coords)
assert tuple(G.edges[arc_key_forward]['geometry'].coords) == tuple(G.edges[arc_key_reverse]['geometry'].reverse().coords)
#************************************************************************************************
# the unexpected case
#************************************************************************************************
arc_key_forward=(3411585488,3411585486,0)
arc_key_reverse=(3411585486,3411585488,0)
# it is simplified
assert type(G.edges[arc_key_forward]['osmid']) == list
assert type(G.edges[arc_key_reverse]['osmid']) == list
# the osmids are the same
assert G.edges[arc_key_forward]['osmid'] == G.edges[arc_key_reverse]['osmid']
# the reversed attributes are the same
assert G.edges[arc_key_forward]['reversed'] == G.edges[arc_key_reverse]['reversed']
# the geometry is equivalent...
assert G.edges[arc_key_forward]['geometry'].equals(G.edges[arc_key_reverse]['geometry'])
assert G.edges[arc_key_forward]['geometry'].equals(G.edges[arc_key_reverse]['geometry'].reverse())
# ... but is reversed
assert not tuple(G.edges[arc_key_forward]['geometry'].coords) == tuple(G.edges[arc_key_reverse]['geometry'].coords)
assert tuple(G.edges[arc_key_forward]['geometry'].coords) == tuple(G.edges[arc_key_reverse]['geometry'].reverse().coords)
```

**Comment by gboeing** [comment]
The `reversed` tag denotes whether the node order in an edge is the same or the reverse of the node order as digitized on OpenStreetMap, to account for reciprocal edges between linked nodes in a MultiDiGraph. From the [docs](https://osmnx.readthedocs.io/en/latest/getting-started.html#topology-clean-up):

> By default, OSMnx simplifies this topology by discarding non-intersection/dead-end nodes while retaining the complete true edge geometry as an edge attribute. When multiple OpenStreetMap ways are merged into a single graph edge, the ways’ attribute values are collapsed into a single edge attribute value if they are all the same, or a list of unique values if any of them differ.

Thus, in your example code, you are just seeing that the observed edges simplified into a single new edge contained multiple unique values in their `reversed` attributes: that is, the values `True` and `False` were observed at least once each. As the docs suggest, these are unique values, so you should think of this attribute as a `set` though it's represented as a list for data structure consistency.

**Comment by pmlpm1986** [comment]
I see. I went through the code for the simplify_graph method and realised that that was what was being done but I wondered if that was really intended. In my mind, information is being lost if only the unique values are being preserved and not their order (as the type suggests). I suppose somebody might be interested in that information but it's not critical for me. I have been writing a method to test whether or not two edges are reversed by osmnx standards and all I wanted to know was if this was really intended. Might such a method be of interest to the project?

**Comment by gboeing** [comment]
> information is being lost if only the unique values are being preserved and not their order

Precisely. This is a model *simplification* algorithm rather than lossless compression. Its purpose is to discard some information to return a simpler, more parsimonious model that retains its usefulness in representing the phenomenon of interest. If full information is ever required, setting `simplify=False` provides it.
