### ISSUE TITLE
Adding type hints to the function signatures

### ISSUE THREAD

**Issue by Vuizur** [gboeing/osmnx#1062]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My proposal is not addressed by the documentation or examples

### Existing issues

- [X] Nothing similar appears in an existing issue

### What problem does your feature proposal solve?

The types of the parameters and the returned data of the functions is already very well documented. Currently the data is in docstrings, which unfortunately IDEs like VS Code cannot use. Putting them additionally directly in the function signatures would have several advantages:
* Make it easier for users to see what they need to input without having to scroll through the docstrings
* Enable type checkers to find quickly find errors if the user uses something wrong
* Enable autocomplete on returned values

### What is your proposed solution?

One could simply copy the info out of the docstrings and put it in the function signatures. I think using `from __future__ import annotations` would be the best choice, as we could use modern constructs from Python 3.10+ and still have a runnable program on Python 3.8.

### What alternatives have you considered?

One could also create type stubs, but they would be harder to maintain and get out of date.

### Additional context

-

**Comment by gboeing** [comment]
@Vuizur thanks for the suggestion. Yes this has been on my radar and I hope to incorporate type annotations into OSMnx v2.0 (aiming for a 2024 release). The current plan is for v2.0 to support Python 3.9+ and drop support for Python 3.8. Reading the [3.9 release notes](https://docs.python.org/3.9/whatsnew/3.9.html) it looks like we should be able to avoid using `from __future__ import annotations`, if so.

**Comment by gboeing** [comment]
Work in progress in the [typing](https://github.com/gboeing/osmnx/tree/typing) branch.

**Comment by gboeing** [comment]
Proposed resolution in #1107. Comments, feedback, and improvements welcome.

**Comment by gboeing** [comment]
Merged into the v2 branch and targeted for release in 2.0.0.

**Comment by gboeing** [comment]
The first pre-release OSMnx v2 beta has been released. Testers needed! See #1123 for details.
