### ISSUE TITLE
Detect API changes on a regular basis

### ISSUE THREAD

**Issue by gboeing** [gboeing/osmnx#107]
Per conversations with @migurski, Nominatim and Overpass API changes need to be detected more regularly, and as a separate process from code changes. We want to start using cached server responses in the code tests, so we need some other process checking the API now and then to make sure it's returning what we expect.

CI is triggered only when commits and PRs happen, while API changes can happen at any time and affect users regardless of changes to the codebase. We might want to use a daily scheduled task to check for them to let us know that something's up even if no one is actively committing code changes for a lengthy period of time.

**Comment by migurski** [comment]
Here are some [sample calls from the tests](https://github.com/gboeing/osmnx/blob/5008ad755/tests/test_osmnx.py) that a preliminary version should look for:

- `ox.gdf_from_place('Manhattan, New York City, New York, USA', buffer_dist=100)`
- `ox.graph_from_place('Piedmont, California, USA')`
- `ox.graph_from_bbox(37.79, 37.78, -122.41, -122.43, network_type='drive_service')`
- `ox.graph_from_point(ox.bbox_from_point((37.791427, -122.410018), project_utm=True), distance=750, distance_type='bbox', network_type='drive')`
- `ox.graph_from_address(address='350 5th Ave, New York, NY', distance=1000, distance_type='network', network_type='bike')`
- `ox.graph_from_place(['Los Altos, California, USA', {'city':'Los Altos Hills', 'state':'California'}, 'Loyola, California'], network_type='all', clean_periphery=False)`
- `ox.graph_from_place('Piedmont, California, USA', network_type='drive', simplify=False)`
- `ox.graph_from_address('398 N. Sicily Pl., Chandler, Arizona', distance=800, network_type='drive')`
- `ox.buildings_from_place(place='Piedmont, California, USA')`
- `ox.buildings_from_address(address='260 Stockton Street, San Francisco, California, USA', distance=300)`

**Comment by migurski** [comment]
☝️ I’ll use that to make a shortlist of request types and some basic tests.

**Comment by mmd-osm** [comment]
I’m a bit curious if you’ve encountered such an API change in the past. New Overpass releases should always be downward compatible unless there’s some regression which hasn’t been caught by the test suite. Do you plan to report any findings upstream, or what kind of process did you have in mind?

**Comment by migurski** [comment]
Hi @mmd-osm, here’s some background context for this issue: https://github.com/gboeing/osmnx/commit/4794435e7916b3cf0367ee86cb2d6d8ea65e701b#commitcomment-25700819

> API parameters/format didn't change, but response content did. For example, some city name queries started returning lat-long points as the first query result, rather than polygons like they used to. I had to update several tests, examples, and documentation accordingly, because this change in response changed the queries we have to use to get data through OSMnx.
