### ISSUE TITLE
Feature Request: Adding Buffer Zone Function to OSMnx

### ISSUE THREAD

**Issue by timverlaan** [gboeing/osmnx#1072]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My proposal is not addressed by the documentation or examples

### Existing issues

- [X] Nothing similar appears in an existing issue

### What problem does your feature proposal solve?

The current problem is that when using OSMnx's graph_from_polygon (and potentially other graph functions) function, there is no straightforward way to specify a buffer zone in meters around the polygon. This limitation makes it challenging to include the street network data within a specified buffer, which is essential in cases where users need a more comprehensive representation of the network, especially in areas near the polygon boundary. This feature was essential in my research, and I have implemented it myself (as shown in the code snippet below).
 
```
gdf_area = gpd.read_file(area).to_crs(epsg=4326)
boundary = gdf_area.dissolve().loc[0, 'geometry'].buffer(0.05)   
``` 

### What is your proposed solution?

I propose adding a buffer zone parameter to the osmnx.graph.graph_from_polygon function, allowing users to specify a buffer distance in meters when retrieving street networks. This enhancement will extend the retrieved network beyond the polygon's boundary by the specified buffer distance, providing a more complete and accurate representation of the street network in the desired area.

### What alternatives have you considered?

As an alternative, users currently need to manually create a larger polygon that includes the desired buffer zone and then use this larger polygon as input. This is how I have now done it, but in my current operationalization the buffer is not specified in meters - and my non-technical self could not get it to work that way.

### Additional context

Here's a code example demonstrating how the proposed feature could be used:

```
import osmnx as ox

# Define your polygon and buffer zone
polygon = ox.gdf_from_place("Your City, Your Country")
buffer_meters = 1000  # Adjust as needed

# Retrieve the street network with the buffer zone
G = ox.graph.graph_from_polygon(polygon, buffer=buffer_meters)
```

**Comment by gboeing** [comment]
Thanks for using OSMnx. 

> The current problem is that when using OSMnx's graph_from_polygon (and potentially other graph functions) function, there is no straightforward way to specify a buffer zone in meters around the polygon. This limitation makes it challenging to include the street network data within a specified buffer, which is essential in cases where users need a more comprehensive representation of the network, especially in areas near the polygon boundary.

Users can currently do this with 2 lines of code, so we're probably not going to add this to the API. In fact some piecemeal buffering functionality used to exist, but was deprecated and will be fully removed from the codebase when v2.0 comes out. But the consistent, simple expectation is that users just request the study site that they actually want, since study site definitions are infinitely and easily adjustable. But as you rightly mention, the artificial periphery problem is essential to keep in mind in all spatial network analysis.

Sample code to do this now and in the future:

```python
import osmnx as ox
geom = ox.geocode_to_gdf("Piedmont, CA, USA")["geometry"].iloc[0]

# buffer the geometry by 100 meters
geom_proj, crs = ox.projection.project_geometry(geom)
geom_buff, _ = ox.projection.project_geometry(geom_proj.buffer(100), crs=crs, to_latlong=True)

# model the driving network within the buffered geometry
G = ox.graph_from_polygon(geom_buff, network_type="drive")
```

**Comment by gboeing** [comment]
See also the new `buffer_geometry` helper function added in #1214.
