### ISSUE TITLE
PermissionError [ErrNo 13] when connecting to localhost using the latest docker image

### ISSUE THREAD

**Issue by primetimber** [gboeing/osmnx#1074]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Windows 10 / Docker

### What OSMnx version are you using?

latest

### Environment packages and versions

```shell
latest docker image
```

### How did you install OSMnx?

OSMnx Docker image

### Problem description

While following the instructions here https://hub.docker.com/r/gboeing/osmnx#! I was unable to run Jupyter Notebook, while localhost:8888 is working. The log displays the following error message:

> [E 2023-10-18 14:32:47.530 ServerApp] Uncaught exception
>     Traceback (most recent call last):
>       File "/opt/conda/lib/python3.11/site-packages/tornado/http1connection.py", line 276, in _read_message
>         delegate.finish()
>       File "/opt/conda/lib/python3.11/site-packages/tornado/routing.py", line 268, in finish
>         self.delegate.finish()
>       File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 2395, in finish
>         self.execute()
>       File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 2417, in execute
>         self.handler = self.handler_class(
>                        ^^^^^^^^^^^^^^^^^^^
>       File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 238, in __init__
>         self.initialize(**kwargs)  # type: ignore
>         ^^^^^^^^^^^^^^^^^^^^^^^^^
>       File "/opt/conda/lib/python3.11/site-packages/jupyterlab_server/settings_handler.py", line 22, in initialize
>         SchemaHandler.initialize(
>       File "/opt/conda/lib/python3.11/site-packages/jupyterlab_server/settings_utils.py", line 439, in initialize
>         self.overrides, error = _get_overrides(app_settings_dir)
>                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>       File "/opt/conda/lib/python3.11/site-packages/jupyterlab_server/settings_utils.py", line 302, in _get_overrides
>         with open(overrides_path, encoding="utf-8") as fid:
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     PermissionError: [Errno 13] Permission denied: '/opt/conda/share/jupyter/lab/settings/overrides.json'
> time="2023-10-18T16:36:54+02:00" level=error msg="error waiting for container: "

### Complete minimal reproducible example

```python
n/a
```

**Comment by gboeing** [comment]
Should be fixed by #1074. You can test.

**Comment by primetimber** [comment]
Switching to a random port finally did the trick for me. Working now. Thank you very much. I very much appreachiate your effort!!
