### ISSUE TITLE
Contributing guidelines link nowhere

### ISSUE THREAD

**Issue by matkoniecz** [gboeing/osmnx#1078]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Irrelevant 

### What OSMnx version are you using?

Currently published in default branch

### Environment packages and versions

```shell
Irrelevant
```

### How did you install OSMnx?

Other (describe below)

### Problem description

On creating issue in this repository you get "Before you proceed, read the [contributing guidelines](https://github.com/gboeing/osmnx/CONTRIBUTING.md) regarding where to ask usage questions and how to file a bug report." 

That link goes to nonexistent file 

### Complete minimal reproducible example

```python
Irrelevant
```

**Comment by gboeing** [comment]
I can inspect the link when I get to an actual computer later, but possibly related to or introduced in #1051?

**Comment by gboeing** [comment]
Fixed in 7086e65bd94ad3b44c005015b1f85e9b258fbc96
