### ISSUE TITLE
Document usage limitations

### ISSUE THREAD

**Issue by matkoniecz** [gboeing/osmnx#1079]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My proposal is not addressed by the documentation or examples

### Existing issues

- [X] Nothing similar appears in an existing issue

### What problem does your feature proposal solve?

Several users use this library without understanding usage limits of called services.

### What is your proposed solution?

Document usage limitations and policy of underlying services and mention it clearly in quick start

### What alternatives have you considered?

Errors related to usage limits may also fail with error messages mentioning over use of services and suggesting alternatives for workloads requiring heavy use.

### Additional context

I can track down support requests appearing at OpenStreetMap forums.

Users of this library are among most common cases assisting there unaware of what is going wrong and that their scale of usage is exceeding underlying services, and that they violated their usage policies

**Comment by matkoniecz** [comment]
Note: maybe it is documented somewhere? In such case just linking it from quick start and putting it into faq would be useful.

**Comment by gboeing** [comment]
Thanks for flagging this @matkoniecz.

> Document usage limitations and policy of underlying services and mention it clearly in quick start

Good idea. We have some mention of this already but it's probably too buried. Adding it to the "getting started" guide and FAQ sounds like a good idea to me.

> I can track down support requests appearing at OpenStreetMap forums.

Yes please. If you can share any more information about what they are doing wrong and what policies they are violating, we can 1) specifically highlight this in our guide and 2) implement programmatic restraints if feasible. Our goal is to always be a good neighbor.

I'm readying a patch release today (can delay slightly), but we could potentially update the docs in time to make this go live ASAP.

**Comment by matkoniecz** [comment]
https://community.openstreetmap.org/t/road-types-and-speed-limits-in-nigeria/105309 is the latest one

**Comment by matkoniecz** [comment]
https://community.openstreetmap.org/t/how-can-i-efficiently-query-the-highway-tag-and-the-max-speed-tag-for-the-nearest-road-to-20-million-lat-long-points/103972

**Comment by matkoniecz** [comment]
I remember other cases, but maybe it was on IRC/Discord/elsewhere or for some other reason I failed to track them down

**Comment by matkoniecz** [comment]
And it is definitely great to see OpenStreetMap data being used and being more accessible!

Though it would help everyone if people would be aware that making millions of overpass requests require having own server and that OSM editing API is for editing, not bulk downloads :)

**Comment by gboeing** [comment]
I'm sorry for laughing, but this guy trying to make 20 million API requests 😂

Thanks again for the links. We shall update the docs.

**Comment by gboeing** [comment]
@matkoniecz do you have any specific links to usage limits? I'd like to link to the best source to point users to an authoritative policy/reference.

**Comment by matkoniecz** [comment]
For Overpass: https://dev.overpass-api.de/overpass-doc/en/preface/commons.html

> As a broad guideline to stay within safety margins, users are expected to send a maximum of about 10000 requests per day and keep their download volume below about 1 GB per day.

For Nominatim: https://operations.osmfoundation.org/policies/nominatim/

For OSM Editing API: use it for editing, not for read-only use

https://operations.osmfoundation.org/policies/tiles/ may be applicable, but likely not

Are there any other relevant services?

**Comment by gboeing** [comment]
Perfect. No we just use Overpass and Nominatim. (And Google Maps API, but users provide their own API key for that.)
