### ISSUE TITLE
code for elevation

### ISSUE THREAD

**Issue by Mehdi2566** [gboeing/osmnx#108]
#### i want to use osmnx to analysis the data related to elevation like 

- new peaks with an elevation
- new peaks without elevation
- peaks that incorporated elevation
- peaks that removed elevation
- peaks that changed elevation
- peaks that changed the name
- peaks with elevation with an incorrect format
my problem is the following error
- 

#### i used`pip list`

####from .core import save_to_cache

```python
# Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import math
>>> import time
>>> import requests
>>> import pandas as pd
>>> import networkx as nx
>>> from .core import save_to_cache
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '__main__.core'; '__main__' is not a package
>>>

**Comment by gboeing** [comment]
Hi @Mehdi2566 -- it's not clear to me what you're doing in this code snippet. It looks like you launched a python interpreter then imported some dependencies. But why? For instance, why are you trying to import `save_to_cache` from `.core`? Are you trying to run the elevation.py module? If so, this isn't how OSMnx is used.

I'd suggest getting started by reading the [OSMnx documentation](https://osmnx.readthedocs.io/) to understand how to run and use this tool, and then peruse the usage [examples](https://github.com/gboeing/osmnx-examples). If you're interested in working with elevation data, here's the [relevant demonstration](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/12-node-elevations-edge-grades.ipynb) that you can re-create.

**Comment by Mehdi2566** [comment]
yes ,actually i want to analysis the elevation for a specific period .but i am beginner ,could you plz tell me how should i do it ?

**Comment by gboeing** [comment]
@Mehdi2566 if you're a beginner, I'd suggest getting started by reading the [OSMnx documentation](https://osmnx.readthedocs.io/) to understand how to run and use this tool, and then peruse the usage [examples](https://github.com/gboeing/osmnx-examples). If you're interested in working with elevation data, here's the [relevant demonstration](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/12-node-elevations-edge-grades.ipynb) that you can re-create.

This issue tracker is for flagging bugs, problems, and new feature requests. If you have general question or a "how to" question, please see the [contributing guidelines](https://github.com/gboeing/osmnx/blob/master/CONTRIBUTING.md) -- these are better suited for asking on StackOverflow.
