### ISSUE TITLE
Animate OSMNX Graphs

### ISSUE THREAD

**Issue by hocherie** [gboeing/osmnx#109]
Hi, I am hoping to animate the plotted OSMNX graphs (ex. node changes color based on time). What is the best way to do so?

Right now, I have plot_graph in a for loop, however this requires me to manually close the graph screen before it advances one step.

**Comment by gboeing** [comment]
Hi @hocherie thanks for using OSMnx. The issue tracker is for bugs and feature requests. As this is a general question, it's best suited for asking on [StackOverflow](https://stackoverflow.com/search?q=osmnx). See the [contributing guidelines](https://github.com/gboeing/osmnx/blob/master/CONTRIBUTING.md) for details. That said, here's one workflow for [animated Python plots](http://geoffboeing.com/2015/04/animated-3d-plots-python/). You might also check out the matplotlib animation module.
