### ISSUE TITLE
Vasu

### ISSUE THREAD

**Issue by VasuPadsumbia** [gboeing/osmnx#1091]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Ubuntu20.04/Python 3.8

### What OSMnx version are you using?

1.8.0

### Environment packages and versions

```shell
pip3 install osmnx==1.8.0
```

### How did you install OSMnx?

Pip

### Problem description

Hello! I am using jetson for my autonomous rover and while installing osmnx it shows gdal requirement of 3.1 however Ubuntu 20.04 only supports GDAL version of 3.0.4. Is there any older version of osmnx that supports the provided GDAL version?

### Complete minimal reproducible example

```python
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpz51sc8ae get_requires_for_build_wheel /tmp/tmpe4pmxwkk
       cwd: /tmp/pip-install-bzwwo1w2/fiona
  Complete output (1 lines):
  ERROR: GDAL >= 3.1 is required for fiona. Please upgrade GDAL.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpz51sc8ae get_requires_for_build_wheel /tmp/tmpe4pmxwkk Check the logs for full command output.
```

**Comment by gboeing** [comment]
Not a bug. Just follow the installation instructions: https://osmnx.readthedocs.io/

Side note: GDAL is not a requirement of OSMnx, but rather of its dependencies. So if you want to use a 4+ year old version of GDAL you'll probably need a 4+ year old version of the dependencies.
