### ISSUE TITLE
street networks graphs not working

### ISSUE THREAD

**Issue by MihirT-10** [gboeing/osmnx#1096]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Windows 11, 3.11.5

### What OSMnx version are you using?

1.8

### Environment packages and versions

```shell
N/A
```

### How did you install OSMnx?

Conda and conda-forge

### Problem description

street network graphs return a response error: "UnboundLocalError: cannot access local variable 'response' where it is not associated with a value" shows up for graph_from_place and graph_from_bbox and others not sure what the issue is. Checked the 03-graph-place-queries.ipynb example and same issue occurs in that example notebook

### Complete minimal reproducible example

```python
# get the walking network for piedmont
import osmnx as ox
G = ox.graph_from_place("Piedmont, California, USA", network_type="walk")
```

**Comment by gboeing** [comment]
Are you using a proxy or behind some kind of firewall?

**Comment by MihirT-10** [comment]
Sorry, yes this was the issue I was behind a firewall, was able to work through it on that end, the modules do all work
