### ISSUE TITLE
[Feature request] Regarding offline queries

### ISSUE THREAD

**Issue by RLstat** [gboeing/osmnx#112]
First, Thanks for this great package!

It seems to me that currently many queries cannot be offline, such as graph_from_point, graph_from_address etc. Sometimes we make large amount of queries within a city, just to get many local small networks or nearby nodes for analysis, and performance is an issue (as well as internet connectivity). I am wondering whether new feature can be added to support queries on pre-loaded large graphs object (networkx multidigraph) that are in memory or downloaded maps locally. 

I am not familiar with dissecting networkx multidigraph structure, so if you think this feature is not necessary, any recommendations on how to analyse networkx multidigraph will be highly appreciated (like packages, tutorials etc. ) Thanks.

**Comment by gboeing** [comment]
If you want to load a graph from a local .osm file, this functionality has been added to the master branch in #100. If you want to extract a small local network from a larger network (nx multidigraph) in memory, you can induce a subgraph with [ego_graph](https://networkx.github.io/documentation/stable/reference/generated/networkx.generators.ego.ego_graph.html) or [subgraph](https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.MultiDiGraph.subgraph.html).

**Comment by RLstat** [comment]
@gboeing Thanks, that is really helpful.
