### ISSUE TITLE
Support directed bearing/orientation distributions and plots

### ISSUE THREAD

**Issue by dhimmel** [gboeing/osmnx#1137]
### What problem does your feature proposal solve?

Creating orientation/bearing distributions and plots for directed graphs.

### What is your proposed solution?

`_extract_edge_bearings` can support directed graphs and in the case of a directed graph skip adding reverse bearings (`bearings_r`):

https://github.com/gboeing/osmnx/blob/78af8ed55f1dfd2ebc079eded928be4b6af537c1/osmnx/bearing.py#L148-L191

### What alternatives have you considered?

Implementing bearing calculation, distributions, and plotting outside of osmnx and networkx, but would like to avoid such duplication.

### Additional context

Possible use cases are one-way transportation networks or [downhill ski trails](https://github.com/russellporter/openskimap.org/issues/82).

**Comment by gboeing** [comment]
This would be easy enough to implement but I want to make sure that it's theoretically sound first. I think it may be, though users may need a warning to ensure things proceed according to expectations. That is, *should* we allow the calculation of bearings on directed graphs?

If a user is interested in the bearings/orientation of *flows*, then maybe yes. If the user is interested in the bearings/orientation of *physical infrastructure*, then no. Perhaps a UserWarning as such is sufficient if a user passes a MultiDiGraph instead of a MultiGraph.

**Comment by dhimmel** [comment]
Thanks @gboeing for your insights here.

> _should_ we allow the calculation of bearings on directed graphs? If a user is interested in the bearings/orientation of _flows_, then maybe yes. If the user is interested in the bearings/orientation of _physical infrastructure_, then no.

That is a helpful conceptual distinction, although there is certainly a relation between physical infrastructure and flow. Some examples are waterways, separated highways, one ways trails (common in mountain biking, skiing, etc). In all these cases, the physical infrastructure is designed to support directional flow.

> Perhaps a UserWarning as such is sufficient if a user passes a MultiDiGraph instead of a MultiGraph.

Another option would be to keep the "graph must be undirected" error unless the user sets an additional argument like `directed_bearings=True` or `omit_reverse=True`.

The warning proposal also sounds good paired with documentation like: "Supplying a `MultiDiGraph` results in directional bearings. For bidirectional bearings, use `MultiDiGraph.to_undirected()`".

One final note, I initially come to this repository with the hopes of using the bearing calculation and polar histogram plotting without wanting to use a networkx graph. But many of the critical functions required a graph input. Putting the data into the graph was not too hard, but for me was solely for purposes of using the mature and powerful bearing/plotting functionality.

**Comment by gboeing** [comment]
Would you like to open a PR to allow directed graphs, issue a UserWarning and update the docstring?

**Comment by gboeing** [comment]
Closed by #1139
