### ISSUE TITLE
[Meta] Enable Discussions tab on this GitHub repo

### ISSUE THREAD

**Issue by EwoutH** [gboeing/osmnx#1141]
I would find it quite useful if the [Discussions](https://github.com/features/discussions) tab could be enabled on this repository. Then users would have a place to discuss questions, configurations and new ideas, without adding noise here in the issues.

It can be enabled very easily, see [Enabling GitHub Discussions on your repository](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository).

**Comment by gboeing** [comment]
Good suggestion. I've enabled it.

**Comment by EwoutH** [comment]
Weird, for me it doesn't show up:

![image](https://github.com/gboeing/osmnx/assets/15776622/e169380c-b2a5-4384-899f-356e2df0d597)
