### ISSUE TITLE
_bearings_distribution: apply weight during histogram

### ISSUE THREAD

**Issue by dhimmel** [gboeing/osmnx#1143]
Here is how `_bearings_distribution` currently applies the `weight` parameter:

https://github.com/gboeing/osmnx/blob/ea397d3aec77c7fb394712d5af6d490e0b159d4c/osmnx/bearing.py#L276-L277

`_extract_edge_bearings` implements the weight by repeating bearings:

https://github.com/gboeing/osmnx/blob/ea397d3aec77c7fb394712d5af6d490e0b159d4c/osmnx/bearing.py#L214-L220

Instead, the weight could be applied by [`numpy.histogram`](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html). The benefits would be:

1. avoiding a loss of precision when converting a float weight value to an int
2. greater computational efficiency and reduced memory usage

The resulting counts could have decimals (non-integers), but `_bearings_distribution` is already typed to return `npt.NDArray[np.float64]` for `bin_counts`.

**Comment by gboeing** [comment]
Thanks. Sounds like a promising efficiency improvement. Would you like to open a PR for me to review?

**Comment by gboeing** [comment]
closed by #1147
