### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by adnls** [gboeing/osmnx#115]
The issue tracker is for reporting bugs and feature requests. For general questions, see the contributing guidelines in CONTRIBUTING.md.

If you're having trouble with OSMnx, first search the previously opened issues to see if the problem has already been noted. If not, fill in the template below. You can delete any sections that don't apply.

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>
# Paste the output of your Python packages and their versions here, between these two "details" tags

</details>

#### Code that reproduces the issue

```python
# your code goes here
```

**Comment by adnls** [comment]
hi, i'm trying to import osmx with pip and it fail with error : 
UnicodeDecodeError  "utf-8" codec can't decode byte 0xe9 in position 36 : invalid continuation byte.
i don't know what to do, could you help me to fix this issue?
Thanks.

**Comment by adnls** [comment]
0xe9 is the exadecimal code for 'é' in the ascii table if it helps...

**Comment by gboeing** [comment]
Thanks for using OSMnx. If you fill out the issue template completely, we'll have enough information to help you troubleshoot.
