### ISSUE TITLE
Add edge_attrs_differ argument to each graph.graph_from_* method

### ISSUE THREAD

**Issue by rinconraul** [gboeing/osmnx#1151]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My proposal is not addressed by the documentation or examples

### Existing issues

- [X] Nothing similar appears in an existing issue

### What problem does your feature proposal solve?

The creation of any graph with graph.graph_from* function will call the `simplify_graph` function without allowing the user to directly pass the edge_attrs_differ argument. In this way, the graph merges the edges from the initial point, making a more difficult to go backward and retain the nodes with intersections of interest. For example, if you create the same graph by filtering with different conditions, the feature bridge results merged for large links for the lower resolutions:

![image](https://github.com/gboeing/osmnx/assets/61350784/21107641-1306-43f7-ae0e-4db310e33f93)

From right to left, the resolution is varied using 'custom_filter', merging edges with 'bridge' feature 'yes' (blue edges) which defeats later the use of this feature (i.e., bridges).

### What is your proposed solution?

Adding edge_attrs_differ argument to each graph.graph_from_* method to make it accessible from the point of graph creation. The default value is set to None, and the description is the same in simplification.simplify_graph function is added. 

### What alternatives have you considered?

The user could pass 'simplify' as False and later run simplification.simplify_graph; however, if it passes 'True', then the user should have more control over it. I try spatial analysis methods but it is more complicated than the first possible solution.

### Additional context

Adding the attribute and description to the functions graph.grap_from*:
```python
def graph_from_point(
    center_point,
    dist=1000,
    dist_type="bbox",
    network_type="all_private",
    simplify=True,
    edge_attrs_differ=None,
    retain_all=False,
    truncate_by_edge=False,
    clean_periphery=None,
    custom_filter=None,
):
    """
    Download and create a graph within some distance of a (lat, lon) point.

    You can use the `settings` module to retrieve a snapshot of historical OSM
    data as of a certain date, or to configure the Overpass server timeout,
    memory allocation, and other custom settings.

    Parameters
    ----------
    center_point : tuple
        the (lat, lon) center point around which to construct the graph
    dist : int
        retain only those nodes within this many meters of the center of the
        graph, with distance determined according to dist_type argument
    dist_type : string {"network", "bbox"}
        if "bbox", retain only those nodes within a bounding box of the
        distance parameter. if "network", retain only those nodes within some
        network distance from the center-most node.
    network_type : string, {"all_private", "all", "bike", "drive", "drive_service", "walk"}
        what type of street network to get if custom_filter is None
    simplify : bool
        if True, simplify graph topology with the `simplify_graph` function
    edge_attrs_differ : iterable
        An iterable of edge attribute names for relaxing the strictness of
        endpoint determination. If not None, a node is an endpoint if its
        incident edges have different values then each other for any of the
        edge attributes in `edge_attrs_differ`.
    retain_all : bool
        if True, return the entire graph even if it is not connected.
        otherwise, retain only the largest weakly connected component.

```

New result:
![image](https://github.com/gboeing/osmnx/assets/61350784/d0edef8a-7c95-4b70-9075-554f219d6280)
Now the 'bridges' kept using 'edge_attrs_differ ' are indeed over the edges.

**Comment by gboeing** [comment]
The official method for doing this is to pass `simplify=False` when creating the graph, then manually simplify it with your custom parameterization. Otherwise pass `simplify=True` as a shortcut with default parameterization.

**Comment by rinconraul** [comment]
Agree! I thought it was just convenient. Thank you for checking the issue; I'll close it 👍🏽 !
