### ISSUE TITLE
New feature: Retrieving OSM POIs with osmnx?

### ISSUE THREAD

**Issue by HTenkanen** [gboeing/osmnx#116]
Hi, 

first of all, awesome work with the package! Highly useful and needed. 

I was wondering if there would be interest to include separate functionalities to retrieve OpenStreetMap POIs with osmnx? I am currently starting to write such functionalities for my own project, and I think I will be using osmnx as a basis for fetching Points of interest from OpenStreetMap (such as restaurants etc.). I know that it is possible to work with [other infrastructures](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/16-work-with-other-infrastructures.ipynb) than roads, but if I have understood correctly that function works only with graphs, not with point data such as POIs. 

If you think this would be interesting, I would be happy to help implementing these functions. 

Cheers,
Henrikki

P.S. FYI: I introduce osmnx also with the fully open GIS course (Lesson 7) that can be found here [http://autogis.github.io](http://autogis.github.io).

**Comment by gboeing** [comment]
@HTenkanen your course looks really cool. Nice work. Yes I think it might be interesting to work with POIs directly in OSMnx... perhaps with a separate new POI module.

**Comment by HTenkanen** [comment]
@gboeing thanks! 👍 

Nice, I think having POIs included in OSMnx would be a nice addition! And yes, I think a separate module would be good, and it could be written e.g. into `pois.py` in a similar manner as you have now the `buildings.py`. Or what would you suggest?

Basically the idea could be that you can pass a list of amenities to a function `pois_from_poly()` that you want to retrieve from Overpass API, and then it would return a GeoDataFrame out of those amenities. This would follow the style that have, and there would be separate functions for `pois_from_bbox()`, `pois_from_place()`, `pois_from_address()` etc.   

I actually already wrote a first version of module with this style (only `pois_from_poly()` now) for my own purposes, and it works quite nicely. There are, however, still some things needs a bit of thinking:

**Should the module provide information about what amenities are available?**
    - e.g. `ox.pois_available` could return a list of possible amenity values
    - This would mean that the amenity list should be updated every now and then...

**The function searches now amenities from** `nodes`, `ways` and `relation`s: 
```
query_template = ('[out:json][timeout:{timeout}]{maxsize};((node["amenity"~"{amenities}"]({south:.8f},'
                  '{west:.8f},{north:.8f},{east:.8f});(._;>;););(way["amenity"~"{amenities}"]({south:.8f},'
                  '{west:.8f},{north:.8f},{east:.8f});(._;>;););(relation["amenity"~"{amenities}"]'
                  '({south:.8f},{west:.8f},{north:.8f},{east:.8f});(._;>;);));out;')
```

**How should we deal with the amenities that are of type `way`?** E.g.

```
{'type': 'way', 'id': 531711920, 'nodes': [5161070021, 5161088574, 5161088573, 5161088572, 5161070022, 5161070023, 5161070024, 5161070021], 'tags': {'amenity': 'kindergarten', 'operator': 'Boställs Daghem'}}
```
Should the functions return two GeoDataFrames where first one are the points and the second one contains edges? There are for example a lot of `parking area` features and `schools` that seem to be `way`s. I think that might work. 

**And then the last thing, how should the functions deal with relations?**
```
{'type': 'relation', 'id': 7158483, 'members': [{'type': 'way', 'ref': 29875899, 'role': 'outer'}, {'type': 'way', 'ref': 486843935, 'role': 'inner'}], 'tags': {'addr:housenumber': '4', 'addr:street': 'Talvelantie', 'amenity': 'hospital', 'building': 'public', 'name': 'Malmin terveysasema ja hammashoitola', 'type': 'multipolygon'}} 
```
These can be fairly tricky to handle. Any ideas? 

Okey, so these are some of the thoughts that I have now after testing a little bit what kind of amenities are returned by the Overpass. I would really appreciate all the thoughts and ideas from you about this, as you know the best how you want to develop the package.  

I need to be cleaning my code a little bit and implement some of the missing features, but after that I will push my changes to a fork I made where you can take a look [https://github.com/HTenkanen/osmnx](https://github.com/HTenkanen/osmnx). 

Cheers,
Henrikki

**Comment by HTenkanen** [comment]
@gboeing 

I now wrote a `pois.py` which is a first version of the POI module that works in a similar manner as the other modules. At the moment it works only for `node` tags and returns a GeoDataFrame of POIs with points of interests. I wrote it into this branch:
[https://github.com/HTenkanen/osmnx/tree/1-osm-poi-dev](https://github.com/HTenkanen/osmnx/tree/1-osm-poi-dev)

Please take a look, and try it out. E.g. following should work:
```python
>>> import osmnx as ox
>>> place = "Kamppi, Helsinki, Finland"
>>> ox.available_amenities
>>> selected_amenities = ['restaurant', 'bar', 'cafe']
>>> poi_gdf = ox.pois_from_place(place=place, amenities=selected_amenities)
```
Cheers,
Henrikki

**Comment by gboeing** [comment]
@HTenkanen this is looking like a great start! A few ideas regarding your questions:

I'm not sure if the module needs to provide information about which amenities are available, as this would create a maintenance task on the OSMnx side... is it possible to just provide a link in the docstring to an authoritative documentation source from OSM?

Regarding amenities of type "way"... we could return a GeoDataFrame with both node-based and way-based amenities as individual rows. The former would have point geometries, and the latter would have polygon or multipolygon geometries. Would that work? If not, I'd be inclined to take the centroid of the way-based amenity to convert it to a point.

Regarding relations, do you have any examples? What kinds of amenities are these, and must they be handled as relations?

**Comment by HTenkanen** [comment]
@gboeing Thanks for your thoughts!

I now implemented your ideas and now the poi-functions return a single GeoDataFrame consisting of `node`, `way` and `relation` elements. I added a column called `element_type` that tells which kind of element a specified row is. Possible values for that column are:  'node', 'way', and 'relation'.  In this way, it is possible to easily select only such POIs that are points (i.e. nodes), or polygons (ways), or multipolygons (relations). 

Regarding your question about relations, there are quite many cases where for example a school consists of many Polygons and hence those are dealt with a relation. And it is typically the case that the individual 'way' elements do not contain any attribute information about the school (like name, address, etc) as those attributes are assigned to the 'relation' element. Hence, in these cases it is necessary to handle the relation and create a MultiPolygon object having all the attributes. I have now wrote a function called `parse_osm_relations()` which does exactly that. 

I also modularized the code a bit, and I think there are few functions that could be used directly e.g. in `buildings.py` module so that there wouldn't be repetitive code in different modules. But this would maybe need another module for those functions that are shared commonly between different modules (I was thinking to put them in `utils.py` but I'm not sure if that would be the place to put them or to make a separate module for such functions that are related to handling of geometries and parsing osm responses. 

Overall, I think the poi-module is now almost there, but it still needs some tests, documentation and a look from you.  
You can check it out from [https://github.com/HTenkanen/osmnx/tree/1-osm-poi-dev](https://github.com/HTenkanen/osmnx/tree/1-osm-poi-dev). 
If you have any suggestions or ideas, I'm all ears. 👂 😊

**Comment by gboeing** [comment]
Looks good! Yes I think converting relations like schools -> multipolygons is a good solution. For now I think putting shared code in utils.py is a good idea.

**Comment by gboeing** [comment]
@HTenkanen just checking back in on this

**Comment by gboeing** [comment]
Sounds good. I can edit the readme file as needed, but please add documentation via function docstrings so that it appears automatically at https://osmnx.readthedocs.io/en/latest/

**Comment by gboeing** [comment]
@HTenkanen just checking back if this is still an open item.

**Comment by BlackArbsCEO** [comment]
Great project here, has the poi functionality been added yet or that still in testing?

**Comment by HTenkanen** [comment]
@gboeing @BlackArbsCEO:

Sorry for leaving this hanging for quite a long time. Just made a pull request for the added features.

**Comment by gboeing** [comment]
@TRomijn the server started enforcing changed syntax. Should be fixed in 1413217.

**Comment by claytongroth** [comment]
Hello guys,

Amazing stuff! I've been loving these modules. I am getting stuck with a particular part of the OSM POIs module. I was wondering if you had any suggestions.

`ox.pois_from_point(point1, distance = 500)`

For some reason whenever I try to use a distance parameter higher than 500 I get the following error. 

` raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value`

The error occurs at this line.
`POIshapes =  all_pois1['geometry'].representative_point()`

For my current project, I really would like to run it at 1000.

I can post more code if necessary. 

Thanks!

**Comment by gboeing** [comment]
@claytongroth can you provide a complete minimal working example so I can reproduce it?

**Comment by HTenkanen** [comment]
Hi @claytongroth! Can you still share us the error you receive? 

Could you also check what version of Pandas you are using? I at least cannot reproduce the error. 
Newest version of pandas is required (0.23.1).

```
import pandas as pd
pd.__version__
```

**Comment by gboeing** [comment]
@claytongroth I don't see any OSMnx error. I had to change your code snippet to turn it into a working example that reproduces the error you mentioned (this took some guesswork as your snippet works fine out of the box). 

MWE:

```python
import osmnx as ox
point = (43.073051, -89.401230)
dist = 1000
G = ox.graph_from_point(point, distance=dist, network_type='walk')
pois = ox.pois_from_point(point, distance=dist)
POIshapes = pois['geometry'].representative_point()
```

This throws a *geopandas* ValueError as you're calling `geopandas.GeoSeries.representative_point()` on a DataFrame of mixed types (Point, Polygon, MultiPolygon). The "[within](http://toblerity.org/shapely/manual.html#object.representative_point)" logic of `representative_point` doesn't make sense on a Point. If you call `.centroid` instead, this snippet works fine.

**Comment by gboeing** [comment]
@claytongroth please see the geopandas documentation. `centroid` is an attribute, not a method (it should not have parentheses), and `representative_point` doesn't make sense to call on a GDF that contains Point type geometries.

**Comment by claytongroth** [comment]
@gboeing I just read it and was about to delete my post haha...

Thank you for your help and patience! I'm all set!

**Comment by TheodoreGalanos** [comment]
Hello,

I was wondering if it is possible to extract pois from a bbox. I have been looking but can't seem to find this functionality. I'm guessing there is an indirect way of getting the polygon from the bbox? Or could there be a direct way to ask amenities within a bbox?

Thanks in advance!
Theodore.

**Comment by chesterharvey** [comment]
@gboeing What do you think about generalizing the `amenities` parameter so you can retrieve features with other tags, too? I wrote a generalization in this branch that switches out `amenities` for `tags`, which takes a dictionary to query specific key:value pairs.

https://github.com/chesterharvey/osmnx/blob/master/osmnx/pois.py

For example, let's say you want to get all features with an `amenity` tag (specified with a 'None' value in the dictionary), but only `park` within the `leisure` tag, a couple different types of `landuse`, and `bus_stop` within the `highway` tag.

```
tags = {
    'amenity':None,
    'leisure':'park',
    'landuse':['retail','commercial'],
    'highway':'bus_stop'
}

gdf = ox.pois_from_place(place='Santa Clara, Santa Clara County, California, USA', tags=tags)
```
Since there are a lot of POIs without consistent amenity tags (e.g., parks), this generalization was necessary for me to retrieve a broad array of POI types and seemed like low hanging fruit.

A **kwargs parameter in the `pois_from*` functions continues to accept the `amenities` parameter and automatically converts it to a tag dictionary to handle any existing uses.

Happy Friday,
Chester

**Comment by HTenkanen** [comment]
@chesterharvey There is actually an open issue for this feature, see #190. So definitely this is something that would be good and important to include.  Great that you worked on it! 👍 And the way you solved this issue follows more or less the discussion that we had with @gboeing.

**Comment by gboeing** [comment]
@chesterharvey thanks! Following up on @HTenkanen's comment, would you take a quick look at #190 to see how your fork corresponds to the discussion there, and I'd be happy to review a pull request if you'll open one.

**Comment by chesterharvey** [comment]
Thanks @HTenkanen and @gboeing for pointing out #190! Yes, my implementation is surprisingly similar, dictionaries and all. The biggest difference seems to be @HTenkanen's use of booleans to specify all or no values for a given tag key. I really like this; `True` is more intuitive than my use of `None` to specify all values, and `False` also intuitivly facilitates a NOT query.

Switching `None` to `True` is easy, but adding the `False` option will take a little more work to translate into an appropriate Overpass QL query string. I can work on that, hopefully within the next week. Will open a pull request once this is done.

**Comment by chesterharvey** [comment]
@gboeing Status update: I'm having trouble implementing a reliable `NOT` query, I think related to this known issue with Overpass that keeps popping up: https://github.com/drolbr/Overpass-API/issues/192

What this means in practice is that a tag dictionary like the one below, which is supposed to exclude any element with a `leisure` tag, ends up excluding *most* of them, but not all.

```
tags = {
    'amenity':True,
    'leisure':False,
    'landuse':['retail','commercial'],
    'highway':'bus_stop',
}
```
For example, if I use this dictionary to query Piedmont, CA, I end up with a couple of stray elements with `leisure` tags:

```
gdf = ox.pois_from_place(place='Piedmont, Alameda County, California, 94611, USA', tags=tags)
gdf['leisure'].value_counts()

park              1
fitness_centre    1
Name: leisure, dtype: int64
```

One the one hand, the API is supposed to facilitate this sort of query, so maybe it makes sense to assume it will someday and include the functionality. On the other hand, I don't want to lead people into thinking it will work perfectly.

Thoughts?

I still think `TRUE` is the most intuitive way to ask for all values.

**Comment by gboeing** [comment]
> I'm having trouble implementing a reliable NOT query, I think related to this known issue with Overpass that keeps popping up: drolbr/Overpass-API#192 What this means in practice is that a tag dictionary like the one below, which is supposed to exclude any element with a leisure tag, ends up excluding most of them, but not all.

@mmd-osm do you have any insights on this?

**Comment by mmd-osm** [comment]
drolbr/Overpass-API#192 was resolved in release 0.7.55.5, so this shouldn't happen anymore, if you're using overpass-api.de as a backend.

**Comment by gboeing** [comment]
> drolbr/Overpass-API#192 was resolved in release 0.7.55.5, so this shouldn't happen anymore, if you're using overpass-api.de as a backend. In any case, we'd need a query in Overpass QL format, if this still needs further research.

@chesterharvey if you're still experiencing this issue, could you produce an MWE in Overpass QL?

**Comment by gboeing** [comment]
@chesterharvey also, feel free to open a PR in the meantime. We can always add more commits there, and it'll make discussion a little easier.

**Comment by gboeing** [comment]
@chesterharvey just checking to see if this is still active and if you're interested in opening a PR?

**Comment by chesterharvey** [comment]
Sorry, I let this slide for a while. I'm opening a PR now. My modified `osm_poi_download` and `pois_from_place` functions have optional parameters to return the Overpass queries constructed from the input tag dictionaries so they can the troubleshooting, if necessary.

**Comment by corneliailin** [comment]
Hi!

I am trying to retrieve name and geometry data for all the schools in Nairobi, Kenya. I am using the pois_from_place() function available in the osmnx package for this. When I plot the data on a map I see schools outside the boundaries of Nairobi and I don't understand why (please see graph attached).

Am I missing something here? Any help appreciated.


![Screen Shot 2019-08-08 at 6 59 24 PM](https://user-images.githubusercontent.com/52328238/62745069-f12bd180-ba0e-11e9-9f31-e302afa8ddcd.png)

**Comment by elharchaoui** [comment]
Hi all,

I'm really impressed with the work done since the begining of this module project that was started from a needs ! I would like to thank you for this amazing job done and that collaborative work. it's really good to see that!

**Comment by xxC3llxx** [comment]
Hi,
I tried the below code but got an error.

import osmnx as ox
place = "Manhattan Island, Manhattan, New York City, New York, United States of America"

all_pois = ox.pois_from_place(place=place)


AttributeError: module 'osmnx' has no attribute 'pois_from_place'


Why this could be?

**Comment by gboeing** [comment]
@xxC3llxx per the contributing guidelines, the issue tracker is for tracking bugs or proposing pull requests: please read the package [documentation](https://osmnx.readthedocs.io/) for usage details, review the [examples](https://github.com/gboeing/osmnx-examples) for usage demonstrations, and ask any remaining "how-to" usage questions on [StackOverflow](https://stackoverflow.com/).
