### ISSUE TITLE
Publish v2 pre-releases

### ISSUE THREAD

**Issue by EwoutH** [gboeing/osmnx#1162]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My proposal is not addressed by the documentation or examples

### Existing issues

- [X] Nothing similar appears in an existing issue

### What problem does your feature proposal solve?

Currently you have to do a git checkoout of the v2 branch to test the new features on there. Now that (I think) v2 is moving closer to release, it might be nice to have a few pre-released tagged and deployed that users can easily test.

### What is your proposed solution?

Tag and deploy a few pre-releases to PyPI, so that they can be installed with `pip install --pre osmnx`. Not only will this make it easier for users to test the upcoming v2 release, it will also draw some attention to it and thus speedup migration effords.

### What alternatives have you considered?

Not doing pre-releases.

### Additional context

It's quite easy to do this, just give the dev version a number (like `2.0.0-dev1`) and tag it and deploy it as usual. PyPI will automatically recoginize it as a pre-release, based on the `-dev` version suffix (`-b` and `-rc` also work, see https://pythonpackaging.info/07-Package-Release.html).

https://github.com/gboeing/osmnx/blob/1b10a07c5fa559f604e5e66e638bfd1d0eb7b1c1/osmnx/_version.py#L3

**Comment by gboeing** [comment]
Yes, the first beta release is planned within the next few weeks.
