### ISSUE TITLE
AttributeError: module 'osmnx' has no attribute 'convert'

### ISSUE THREAD

**Issue by SmarthBakshi** [gboeing/osmnx#1167]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Windows 10.0.19045

### What OSMnx version are you using?

1.9.2

### Environment packages and versions

```shell
asttokens==2.4.1
attrs==23.1.0
bng_latlon==1.1
branca==0.7.0
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
colorama==0.4.6
comm==0.2.0
contourpy==1.2.0
cycler==0.12.1
debugpy==1.8.0
decorator==5.1.1
et-xmlfile==1.1.0
executing==2.0.1
fastjsonschema==2.19.1
fiona==1.9.5
folium==0.15.1
fonttools==4.46.0
geographiclib==2.0
geopandas==0.14.1
geopy==2.4.1
idna==3.6
ipykernel==6.27.1
ipython==8.18.1
jedi==0.19.1
Jinja2==3.1.2
joblib==1.3.2
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter_client==8.6.0
jupyter_core==5.5.0
kiwisolver==1.4.5
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
nbformat==5.10.2
nest-asyncio==1.5.8
networkx==3.2.1
numpy==1.26.2
openpyxl==3.1.2
osmnx==1.9.2
packaging==23.2
pandas==2.1.3
parso==0.8.3
patsy==0.5.6
Pillow==10.1.0
platformdirs==4.1.0
plotly==5.18.0
prompt-toolkit==3.0.41
psutil==5.9.6
pure-eval==0.2.2
Pygments==2.17.2
pyparsing==3.1.1
pyproj==3.6.1
python-dateutil==2.8.2
pytz==2023.3.post1
pywin32==306
pyzmq==25.1.2
referencing==0.33.0
requests==2.31.0
rpds-py==0.18.0
scikit-learn==1.3.2
scipy==1.11.4
seaborn==0.13.2
shapely==2.0.2
six==1.16.0
stack-data==0.6.3
statsmodels==0.14.1
style==1.1.0
tenacity==8.2.3
threadpoolctl==3.2.0
tornado==6.4
traitlets==5.14.0
tripy==1.0.0
tzdata==2023.3
update==0.0.1
urllib3==2.1.0
wcwidth==0.2.12
xyzservices==2023.10.1
```

### How did you install OSMnx?

Pip

### Problem description

Hi.

Problem description (what did you do, what did you expect to happen, and what actually happened)
I ran the following lines of code:

`ox.convert.to_undirected(g) `
I expected the outcome:

`<networkx.classes.multigraph.MultiGraph at 0x1ae3da07490>`

But instead got the error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[418], [line 1](vscode-notebook-cell:?execution_count=418&line=1)
----> [1](vscode-notebook-cell:?execution_count=418&line=1) ox.convert.to_undirected(g) 

AttributeError: module 'osmnx' has no attribute 'convert'`

### Complete minimal reproducible example

```python
import osmnx as ox
import networkx as nx

g = ox.graph_from_place('London, United Kingdom', network_type='all')
g_undirected = ox.convert.to_undirected(g)
```

**Comment by gboeing** [comment]
Not a bug. You may have OSMnx v1.9.2 installed somewhere on your system, but you are not using it here in your code if you are getting that error. You can print the version from within your code to demonstrate this:

```python
import osmnx as ox
print(ox.__version__)  # prints '1.9.2'
G = ox.graph_from_place('London, United Kingdom', network_type='all')
Gu = ox.convert.to_undirected(G)  # works fine
```
You didn't post your full traceback so it's impossible to guess what precisely is happening. However, this is almost certainly just an installation path issue, and more likely if you're using Jupyter or similar.

> How did you install OSMnx?
>
> Pip

Refer to the [installation instructions](https://osmnx.readthedocs.io/en/stable/installation.html) for the supported method of installation and the importance of using a virtual environment (to avoid this exact kind of problem).
