### ISSUE TITLE
Update secret key in Travis configuration

### ISSUE THREAD

**Issue by migurski** [gboeing/osmnx#117]
Followup to #111: replace the `secret` value in the Travis config with this value to deploy to Lambda:

    secure: "vPcCcTBj+LXDfq+JjwgNmK6YTdvQB/yPeGN5KOac4ome/lv7L7U4bW4p47iyS1iA23mtRS3qiNKBJmn50JXGUzs8PVttv28O9pT0NXbleu2GfraU95yHZwJnCCBnnwIZz1cPJojY8ueD5EU8YCuUtOxsUIHzSNImhR5WaLdHkXzSYBNHWWnuOkA5AgZ/dEOvTVrNtaMOVzY8g5YhvTZeYe9m7xHZdscHP8ZClUoCqueuclGS7GtYhoXxVFfebjXWHbSQCfqrGNgnZHYX/dqi+Q6DRZOGsn46hgIudWtoLGXnN+Yx7/gS77WSMwihS78Z/lNl8Cunj2bpXCggiSEf7MV7g8/kKIoyKVfYnKl3hmp3ORDXLyjgNP3MR09Gr0ybpWpiXDgW67Il+4cdhZSMeCFCkGI1H31nMArJP1NpWausjc6TpHsJOX5rbyWwKjfc4KcyS7Kl81evp6G06Z00kfxwnEToHO8gE2qznE3PWZ3nwlKlHQ9GWRsR2EeK0rotYmIKM7YhoHN5v6tV58pGfsshkOukb4u408RLnlbwASy3k5Kpbp3ZFnY0VahxDEOJR32GptPCPOXC8WXdWs1XmMu0/l8M0fzQy8VGu4tAeRM8giNR6ukpRjfEQi07oqdAuB8aUm8dh3AJVek6wrrtp5BFrZcDUgXR7rCYC/ulEUo="

~~I followed these steps to generate it:~~ ([actual steps below](https://github.com/gboeing/osmnx/issues/117#issuecomment-362757168))

**Comment by gboeing** [comment]
@migurski updated with that new secure key, but still failing to deploy: https://travis-ci.org/gboeing/osmnx/jobs/319856294

**Comment by migurski** [comment]
Frustrating, and hard to debug. I wonder if it makes a difference if you do it instead of me? I don't recall authenticating with Travis in any way.

**Comment by gboeing** [comment]
@migurski I can try it on my machine, but when I follow those steps, what is the value of `{secret key}`?

**Comment by migurski** [comment]
I will send you an email with the value!

**Comment by gboeing** [comment]
👍 will try it tomorrow

**Comment by gboeing** [comment]
@migurski ok, I ran `travis encrypt` in a ruby container on my computer and it produced a different secure key than what you had posted earlier:

```
  secure: "PGpUTsCuB+N/ydZXbPo1ZkgSQPweIVBk3RHOPocYBTtdHjraw0pNFOON9aCWI9vm/vcjbWS30ERW3aPyIRuLkOmtrLMuu7C4z8XMmE0JoH2/Q/TOTZddDyVqGf5FxKcgP7KeFMtrtW/NttsVCPPpuoXVH6iM4HxLwqW+G+JidqDuXfGDFP4V5lT7LHlm80R/1HLQwlCc18rRMT3qOwjTRcnrZ6iIK66rEqZ9bIC/dzoyZWL385x9+c/zQr4w7/aiozkPQI3h+LrO3FndNsSx2lldnxi8mfvRs6r+W9rTlkMwdUtkR8/VbXs3HYPCR52LolRY9ylPcFQ64FZpG3NNClBIxvQWvDkD6cj3GDXiQhwNgFruwnjiE6fqxUAUpBUzSM7iS/XiS6Uyfq2Ddzlx6IcMdwdl5nKHBK929VzCrR5hJExaMMbZP+h5i7/BSZ0XidsOd5/GlTQXbhlAUohFTASWD0bY0grrOkdIuCM+JkMMraha6HtjqBhtu0oY8OqdRlHlOYzrMa4eL4reUTub01MF128pGDw01c2CUTmwypIPrgUDP6SH1+ortdsFwcdphhNSj7Vax5Qal/WGO2Nl7Y1d2o+zygn/rkEtOkBlFaNLpPwu985zrVmjcTDsr3lsJxYbrefp7f8tuKvJCO5qqDc0vPeIg29WdondM4FB4E0="
```

I updated the `.travis.yml` file. However, CI is still failing to deploy: https://travis-ci.org/gboeing/osmnx/jobs/322242215

**Comment by migurski** [comment]
Weird. Sorry for the churn on this, I’ll try again to figure out what’s going on.

**Comment by gboeing** [comment]
Hi @migurski just noticed that all CI tests were still erroring, so wanted to check back in on this

**Comment by migurski** [comment]
Would you be willing to give me temporary write access to this repository? I’ve been able to make this work on my fork, and I'd like to be able to try here directly.

**Comment by gboeing** [comment]
Just added you.

**Comment by migurski** [comment]
Thanks! (Github emails are taking multiple days to reach me for some reason; I'll look at this ASAP)

**Comment by migurski** [comment]
Did you remove it? I wasn't able to write to the repo when I just tried to push a commit.

**Comment by gboeing** [comment]
@migurski I added you as a collaborator with push access on Jan 16, but it says it's still awaiting your response. I think you need to accept the invite?

**Comment by migurski** [comment]
Small update: the configuration that was working before doesn't seem to be working anymore either, so I’ll keep digging.

**Comment by gboeing** [comment]
@migurski I've got some bug fixes and feature updates that have been on hold for a while... I need to clean up the master branch and get it working. I've moved all the cached tests and api tests to a new branch: https://github.com/gboeing/osmnx/tree/cached_tests. The master branch now does tests the old way. When we get things working completely, we can re-merge.

**Comment by migurski** [comment]
Sounds good, I'll work there! I’ll let you know when I’ve been able to figure out the situation on that branch.

**Comment by migurski** [comment]
Thanks for that nudge; I looked at this again and realized the mistake I had been making. The update to Lambda now works correctly. Here are the actual steps:

1. `docker pull ruby`
2. `docker run -it --rm ruby /bin/bash`
3. Inside the ruby container:
    1. `gem install travis`
    2. `travis encrypt -r gboeing/osmnx {secret key}`

The older `AWS_SECRET_ACCESS_KEY=` part was a holdover from when these were being set as environment variables. You also don’t need to make any changes to incorporate this directly, it’ll just continue using the very cheap Lambda function under my AWS account. Here is a current result for the `cached_tests` branch: https://travis-ci.org/gboeing/osmnx/builds/336796356.

If you’re interested in moving forward with this on `master`, a next step would be to add your email to the notification service so you also receive notice when Lambda fails.
