### ISSUE TITLE
aspect ratio in plot

### ISSUE THREAD

**Issue by kkdd** [gboeing/osmnx#120]
Hello,
An aspect ratio in plot_graph() would be preferable to be set as:
```
latitude_center = (min(node_Ys)+max(node_Ys))/2
ax.set_aspect(1/cos(latitude_center))
```

**Comment by gboeing** [comment]
Hi @kkdd thanks for using OSMnx and thanks for this suggestion. Would you mind providing a full, minimal working example to demonstrate your thinking and why this would be preferable? You could also provide this info as a pull request instead if you'd like.

**Comment by kkdd** [comment]
I have send PR (https://github.com/gboeing/osmnx/pull/121).

 > conformal projection preserves shapes
