### ISSUE TITLE
Consider oneway:bus for bidirectionality

### ISSUE THREAD

**Issue by stertingen** [gboeing/osmnx#1216]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My proposal is not addressed by the documentation or examples

### Existing issues

- [X] Nothing similar appears in an existing issue

### What problem does your feature proposal solve?

Consider https://www.openstreetmap.org/way/6878440
This street is only bidirectional for buses.
When searching for a path for city buses, edges along this way are not considered.

### What is your proposed solution?

Expose oneway exception types to graph API, similar to network_type.

https://wiki.openstreetmap.org/wiki/Key:oneway:bus
https://wiki.openstreetmap.org/wiki/Key:oneway:psv
https://wiki.openstreetmap.org/wiki/Key:oneway:bicycle

`graph = ox.graph_from_polygon(bounds, network_type="drive_service", oneway_type="bus")`
should consider `oneway:bus` if it exists, `oneway` otherwise.

### What alternatives have you considered?

Workaround considered: Download graph, change oneway attribute, rebuild graph
```python
ox.settings.useful_tags_way = list(
    dict.fromkeys(ox.settings.useful_tags_way + ["oneway:bus"])
)
graph = ox.graph_from_polygon(bounds, network_type="drive_service", simplify=False)
nodes, edges = ox.graph_to_gdfs(graph, nodes=True, edges=True)
edges["oneway"] = edges["oneway"] & ~edges["oneway:bus"].eq("no")
graph = ox.graph_from_gdfs(nodes, edges)
```

However, it seems to me that `graph_from_gdfs` does not consider `oneway`.

### Additional context

Example: https://www.openstreetmap.org/way/6878440

**Comment by stertingen** [comment]
Functional workaround:

```python
nodes, edges = ox.graph_to_gdfs(graph, nodes=True, edges=True)
bidirectionalEdges = edges[edges["oneway:bus"].eq("no")]
bidirectionalEdges.index.rename(["v", "u", "key"], inplace=True)
bidirectionalEdges = bidirectionalEdges.reorder_levels(["u", "v", "key"])
graph = ox.graph_from_gdfs(nodes, pd.concat([edges, bidirectionalEdges]))
```

**Comment by gboeing** [comment]
@stertingen thanks for using OSMnx and for suggesting this. It's a good question. There's a faster and easier way to do this, which probably precludes adding another parameter to the function signature:

```python
for u, v, k, d in G.edges(keys=True, data=True):
    if d.get("oneway:bus"):
        G.add_edge(v, u, k, **d)
```

This just adds another edge in the reverse direction whenever it finds a "oneway:bus" tagged edge. Note that the "oneway" attribute is irrelevant to routing: it's just a MultiDiGraph, so you need to add an actual edge if you want it considered as a possible path.
