### ISSUE TITLE
Large datasets

### ISSUE THREAD

**Issue by bkj** [gboeing/osmnx#122]
Hi all --

I'm looking to download the road network for the entire United States.  That seems like a bit of an undertaking though so I'm wondering -- has anyone ever uploaded large OSMNX graphs somewhere  that I can just go and download?

Thanks!

**Comment by gboeing** [comment]
@bkj depending on what you need... I have every US city and town, urbanized area, and Zillow neighborhoods' street networks uploaded as shapefiles and graphml files on the Harvard dataverse: https://dataverse.harvard.edu/dataverse.xhtml?alias=osmnx-street-networks

Not sure of anyone who's done this for the US as a single unified graph though.

**Comment by bkj** [comment]
Ah interesting.  I'm trying to find a unified network of the entire US. (I suspect that this may stress NetworkX a little...)

**Comment by gboeing** [comment]
And your system's memory, presumably...
