### ISSUE TITLE
Include cc (or other parameter) in osmnx.save_load.save_graph_shapefile

### ISSUE THREAD

**Issue by johlund** [gboeing/osmnx#123]
I've been using OSMnx for the first time today, and I'm very impressed by the tool. I'm trying to calculate closness, betweenness, etc for the city of Stockholm and have been successful in doing so inside OSMnx. 

To make any use of the results I need to export the results (values/colours/segments) shown in the picture below to a shapefile (these results are just a small sample of the total network):
![skarmklipp 1](https://user-images.githubusercontent.com/6193868/35158432-54219fb8-fd37-11e7-8baa-423fca9981c5.PNG)

Following the documentation I've successfully managed to export the nodes and edges using the save_graph_shapefile:
`ox.save_load.save_graph_shapefile(G_projected,filename='Stockholm_OSMNX',folder='C:/GIS/')`

But when looking in the attributes for 'edges.shp' I can't find anything that refers to the closeness_centrality at all, which I need for further processing and visualisation with QGIS:
![skarmklipp_ii](https://user-images.githubusercontent.com/6193868/35159104-76149b82-fd39-11e7-9efa-121c769507f9.PNG)

It feels like I'm missing something really obvious, or is this impossible with OSMnx? 

Regards,
Jonas

**Comment by gboeing** [comment]
@johlund you're calculating closeness centrality and saving it as a new variable but you're not [setting it](https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.set_edge_attributes.html) as a graph edge attribute at any point.

```python
import osmnx as ox, networkx as nx
G = ox.graph_from_place('Piedmont, California', network_type='drive')
L = nx.line_graph(G)
cc = nx.closeness_centrality(L)
nx.set_edge_attributes(G, cc, 'closeness')
ox.save_graph_shapefile(G)
```

Open in QGIS, color edges according to the closeness column, and voilà:

![qgis osmnx](https://user-images.githubusercontent.com/4977197/35175290-cd16147c-fd27-11e7-8767-7a37ff9a691c.png)

**Comment by gboeing** [comment]
@johlund also, I've updated the [example here](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/08-example-line-graph.ipynb) and wrote a short [blog post](http://geoffboeing.com/2018/01/urban-street-network-centrality/) about this centrality analysis.

**Comment by johlund** [comment]
Can't thank you enough Geoff, what a potent program you have created! Very helpful with the blog post and the examples as well! I'm not that familiar with Github but should I mark this as resolved/answered similar to the way Stackexchange works? 

And since you seem to be very up to date in this field of research I'm taking my changes and trowing in two smaller questions to help me and my colleges get a better understanding in this subject:
- Could you point us in any direction where to find understandable definitions and example of usage for the different types of analysis (betweenness, centrality, closeness centrality etc)? We're struggling to explain what each type of analysis really does to a rather big crew of city planners over here. 
- Open source is the way forward and lies perfect in time but as a government organisation we have a more accurate street network over Stockholm compared to the current state of the equivalent OSM street network. The name of the program gives me a hint of what the answer to this question will be, but I'm asking anyway: is there a way to run the same analysis based on a .shp we have on a local disk?

Thanks again!

Kind regards,
Jonas

**Comment by gboeing** [comment]
@johlund wikipedia has a straightforward [overview](https://en.wikipedia.org/wiki/Centrality) of different centrality measures. Alternatively Newman's [book](https://global.oup.com/academic/product/networks-9780199206650?cc=us&lang=en&) provides a very good introduction.

Regarding shapefiles, you can try networkx's [functions](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.readwrite.nx_shp.read_shp.html) (OSMnx is built on top of networkx). But be aware that shapefiles do not necessarily provide full graph topology and your results may vary. Also, you might need to write some extra code to add in the attributes OSMnx expects once your shapefile is loaded.
