### ISSUE TITLE
module documentation is broken

### ISSUE THREAD

**Issue by xieliy** [gboeing/osmnx#125]
Hi:
I try to access to osmnx document "https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx-buildings-module" but find the document is empty.
I use ubuntu and firefox by the way.

**Comment by gboeing** [comment]
It looks like the module documentation has broken so none of the module info is being rendered. I'll take a look. Would appreciate any help tracking this down if anyone can assist.

**Comment by gboeing** [comment]
@xieliy should be fixed now.
