### ISSUE TITLE
plot_route_folium

### ISSUE THREAD

**Issue by falcaozane** [gboeing/osmnx#1252]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Windows 11 / Python 3.12

### What OSMnx version are you using?

v2

### Environment packages and versions

```shell
no env
```

### How did you install OSMnx?

Other (describe below)

### Problem description

AttributeError: module 'osmnx' has no attribute 'plot_route_folium'

is this function removed

### Complete minimal reproducible example

```python
AttributeError: module 'osmnx' has no attribute 'plot_route_folium'
```

**Comment by gboeing** [comment]
Thanks for using OSMnx! If you've recently upgraded to v2 and are wondering how to ensure code compatibility, see #1123:

> If you want to ensure your code is fully compatible with OSMnx v2 before upgrading to it, you can install the latest v1 release (currently 1.9.4), then run your code. The latest v1 release will remain compatible with the v1 API, but any deprecated functionality you're using will issue a FutureWarning with simple guidance to make it v2 compatible. 

Yes, the `folium` module [was deprecated](https://github.com/gboeing/osmnx/blob/main/CHANGELOG.md#140-2023-06-11) with a warning for removal back in 2023, and finally removed in v2.0.0. The good news: interactive web mapping with folium remains easy to do with OSMnx in ~2 lines of code! See [this example](https://github.com/gboeing/osmnx-examples/blob/main/notebooks/11-interactive-web-mapping.ipynb) in the Examples Gallery for a demonstration.

**Comment by gboeing** [comment]
See also #957 for more details.
