### ISSUE TITLE
Max retries exceeded with url: /api/interpreter

### ISSUE THREAD

**Issue by iwatkot** [gboeing/osmnx#1266]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Windows 11 + Python 3.12.8. Same on MacOS, Ubuntu, Docker.

### What OSMnx version are you using?

osmnx 2.0.0

### Environment packages and versions

```shell
Packages:


affine==2.4.0
altair==5.5.0
annotated-types==0.7.0
astroid==3.3.8
attrs==24.3.0
black==23.12.1
blinker==1.9.0
branca==0.8.1
cachetools==5.5.0
certifi==2024.12.14
charset-normalizer==3.4.1
click==8.1.8
click-plugins==1.1.1
cligj==0.7.2
colorama==0.4.6
coverage==7.6.10
databind==4.5.2
databind.core==4.5.2
databind.json==4.5.2
Deprecated==1.2.15
dill==0.3.9
docspec==2.2.1
docspec-python==2.2.1
docstring_parser==0.11
fast_simplification==0.1.9
folium==0.19.3
geographiclib==2.0
geopandas==1.0.1
geopy==2.4.1
gitdb==4.0.11
GitPython==3.1.43
idna==3.10
iniconfig==2.0.0
isort==5.13.2
Jinja2==3.1.5
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
markdown-it-py==3.0.0
MarkupSafe==3.0.2
mccabe==0.7.0
mdurl==0.1.2
mypy==1.14.1
mypy-extensions==1.0.0
narwhals==1.20.1
networkx==3.4.2
nr-date==2.1.0
nr-stream==1.1.5
nr.util==0.8.12
numpy==2.2.1
opencv-python==4.10.0.84
osmnx==2.0.0
packaging==24.2
pandas==2.2.3
pandas-stubs==2.2.3.241126
pathspec==0.12.1
pillow==11.0.0
platformdirs==4.3.6
pluggy==1.5.0
protobuf==5.29.2
pyarrow==18.1.0
pydantic==2.10.4
pydantic_core==2.27.2
pydeck==0.9.1
pydoc-markdown==4.8.2
Pygments==2.18.0
pylint==3.3.3
Pympler==1.1
pyogrio==0.10.0
pyparsing==3.2.0
pyproj==3.7.0
pytest==8.3.4
pytest-cov==6.0.0
python-dateutil==2.9.0.post0
pytz==2024.2
pywin32==308
PyYAML==6.0.2
rasterio==1.4.3
referencing==0.35.1
requests==2.32.3
rich==13.9.4
rpds-py==0.22.3
shapely==2.0.6
six==1.17.0
smmap==5.0.1
streamlit==1.41.1
streamlit_stl==0.0.5
tenacity==9.0.0
toml==0.10.2
tomli==2.2.1
tomli_w==1.1.0
tomlkit==0.13.2
tornado==6.4.2
trimesh==4.5.3
typeapi==2.2.3
types-pytz==2024.2.0.20241221
types-requests==2.32.0.20241016
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.3.0
watchdog==6.0.0
wrapt==1.17.0
xyzservices==2024.9.0
yapf==0.43.0
```

### How did you install OSMnx?

Other (describe below)

### Problem description

Hello!

First of all, I want to thank you very much for this awesome library. Works as a charm and provides everything you want to and beyond.

But starting from yesterday the:

```python
objects = ox.features_from_bbox(bbox=self.new_bbox, tags=tags)
```

method stopped working. Any requests will fail with:

```python
Error: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022D17946EA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')).
```

Just in case, when working with local files there's no issue.
Works fine:

```python
objects = ox.features_from_xml(self.map.custom_osm, tags=tags)
```

This issue appears everywhere: on my Windows laptop, on my MacOS laptop, locally inside of the Docker, and on the VPS in a different country (DE) with Ubuntu 24.04.
I've tried recreating venv, rebuilding docker images, and so on. It's exactly the same and the fact it appears on different OS, Python versions, machines, and even on machines from different countries, make me think that I can't do anything with it on my own.

I found a similar issue from 2022, but it was closed without any useful comments.

I would appreciate it if you could point me to any workarounds.

Best Regards

### Complete minimal reproducible example

Try to get features from a bounding box (I guess for any other request to OSM API):

```python
import osmnx as ox

bbox = (20.224344458948824, 45.27650505266082, 20.250522423471406, 45.29492313313172)
tags = {"building": True}

objects = ox.features_from_bbox(bbox, tags=tags)
```

But on any other tags or coordinates that I'm using the error is the same.

No additional steps are needed.

**Comment by iwatkot** [comment]
So, the error appears here: https://github.com/gboeing/osmnx/blob/main/osmnx/_overpass.py#L475

URL of the request:
https://overpass-api.de/api/interpreter

DATA (payload) of the request:
```python
OrderedDict({'data': "[out:json][timeout:180];((node['building'](poly:'45.276505 20.224344 45.276505 20.250522 45.294923 20.250522 45.294923 20.224344 45.276505 20.224344');(._;>;););(way['building'](poly:'45.276505 20.224344 45.276505 20.250522 45.294923 20.250522 45.294923 20.224344 45.276505 20.224344');(._;>;););(relation['building'](poly:'45.276505 20.224344 45.276505 20.250522 45.294923 20.250522 45.294923 20.224344 45.276505 20.224344');(._;>;);););out;"})
```

HEADERS of the request:
```json
{'User-Agent': 'OSMnx Python package (https://github.com/gboeing/osmnx)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'referer': 'OSMnx Python package (https://github.com/gboeing/osmnx)', 'Accept-Language': 'en'}
```

**Comment by iwatkot** [comment]
It's functioning again.

**Comment by gboeing** [comment]
Looks like the Overpass server was overloaded or down. If others find this issue in the future, it should just self-resolve.

**Comment by jGaboardi** [comment]
Also, as an FYI for future folks -- this resolved for me about 30 minutes after @iwatkot reported it functioning again. So in case your queries don't work immediately when other's do, take a break and try again after some time.
