### ISSUE TITLE
Problem installing on Ubuntu 

### ISSUE THREAD

**Issue by GordanBuckingham** [gboeing/osmnx#13]
Using Ubuntu 16.04.

I installed Anaconda and ran 'conda install -c ioos rtree=0.8.2'

Then used 

`pip install osmnx`

Output: 

`Collecting osmnx
  Using cached osmnx-0.1b2-py2.py3-none-any.whl
Requirement already satisfied: networkx>=1.11 in ./anaconda2/lib/python2.7/site-packages (from osmnx)
Collecting shapely>=1.5 (from osmnx)
  Using cached Shapely-1.5.17.tar.gz
    Complete output from command python setup.py egg_info:
    Failed ``CDLL(libgeos_c.so.1)``
    Failed ``CDLL(libgeos_c.so)`
    `Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zH46Y2/shapely/setup.py", line 38, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']`
    
    ----------------------------------------
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zH46Y2/shapely/`

Any suggestions?

**Comment by jmz-b** [comment]
`sudo apt-get install libgeos-dev` i think

**Comment by gboeing** [comment]
As @jmz-b points out, the [shapely install instructions](https://pypi.python.org/pypi/Shapely) tell you to install GEOS via `sudo apt-get install libgeos-dev` on Debian/Ubuntu if you don't already have it.

**Comment by GordanBuckingham** [comment]
I tried this on a fresh install of Ubuntu:

1. Installed Anaconda using the Python 2.7 64-bit install from Continuum.
2.  Ran `conda install -c ioos rtree=0.8.2 `
3.  Ran `sudo apt-get install libgeos-dev` 
3.  Tried to run `pip install osmnx` and got the same error as before.

`sudo dpkg -S libgeos-dev` shows it is installed.
`dpkg -S | grep Status` returns 

> Status: install ok installed

**Comment by lizhili** [comment]
find / | grep -E libgeos_c.so.1,add the path to /etc/ld.so.conf,  and ldconfig

**Comment by gboeing** [comment]
@GordanBuckingham you might want to check with the [GEOS](https://trac.osgeo.org/geos) folks directly regarding getting libgeos-dev installed and working properly on your system. Alternatively, the [shapely](https://github.com/Toblerity/Shapely) folks might have some insight as it's their package that uses GEOS directly. For now I'm going to close this issue as it's a matter of installing shapely/libgeos, not with OSMnx.

**Comment by ocefpaf** [comment]
@GordanBuckingham if using conda try this:

`conda install -c conda-forge osmnx`

The `ioos` channel is deprecated and you should always use `conda-forge` instead. (I am a maintainer in both BTW :wink:)

**Comment by gboeing** [comment]
@ocefpaf great point. I've pointed people toward the `ioos` channel in the past and I should probably update those instructions to point to `conda-forge` instead.

**Comment by GordanBuckingham** [comment]
@ocefpaf Thanks for the tip! That worked.

Note to anyone with similar issues: 
Once I ran that and installed osmnx, I tried importing osmnx in the Python interpreter and got a `libstdc++.so.6: version GLIBCXX_3.4.20 not found ` error. `conda install libgcc` fixed that issue.

Thanks again for the help. I'm looking forward to playing around with OSMnx...
