### ISSUE TITLE
Extracting regional road network (Bay Area) using OSMnx

### ISSUE THREAD

**Issue by jesuslovesyiyi** [gboeing/osmnx#138]
#### I'm running it on my mac, Python 3.6.4
appnope                   0.1.0                     <pip>
ca-certificates           2018.1.18                     0    conda-forge
certifi                   2018.1.18                py36_0    conda-forge
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
click-plugins             1.0.3                     <pip>
cligj                     0.4.0                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.2.1                     <pip>
descartes                 1.1.0                     <pip>
Fiona                     1.7.11.post1              <pip>
geopandas                 0.3.0                     <pip>
idna                      2.6                       <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.2.1                     <pip>
ipython-genutils          0.2.0                     <pip>
jedi                      0.11.1                    <pip>
jupyter-client            5.2.2                     <pip>
jupyter-core              4.4.0                     <pip>
kiwisolver                1.0.1                     <pip>
matplotlib                2.2.0                     <pip>
munch                     2.2.0                     <pip>
ncurses                   5.9                          10    conda-forge
networkx                  2.1                       <pip>
numpy                     1.14.1                    <pip>
openssl                   1.0.2n                        0    conda-forge
osmnx                     0.7.2                     <pip>
pandas                    0.22.0                    <pip>
parso                     0.1.1                     <pip>
pexpect                   4.4.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py36_1    conda-forge
prompt-toolkit            1.0.15                    <pip>
ptyprocess                0.5.2                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
pyproj                    1.9.5.1                   <pip>
python                    3.6.4                         0    conda-forge
python-dateutil           2.6.1                     <pip>
pytz                      2018.3                    <pip>
pyzmq                     17.0.0                    <pip>
readline                  7.0                           0    conda-forge
requests                  2.18.4                    <pip>
Rtree                     0.8.3                     <pip>
setuptools                38.5.1                   py36_0    conda-forge
Shapely                   1.6.4.post1               <pip>
simplegeneric             0.8.1                     <pip>
six                       1.11.0                    <pip>
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0                       <pip>
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                     <pip>
wheel                     0.30.0                   py36_2    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forgeand OSMnx version are you using?

#### Code that reproduces the issue

```python
north, south, east, west = 38.902, 36.855, -121.051, -123.711
G_roads_bb = ox.graph_from_bbox(north, south, east, west,network_type='drive')
```

**Comment by gboeing** [comment]
@jesuslovesyiyi make sure you're using the latest versions of the packages. For OSMnx, that's v 0.7.3 (you're using 0.7.2).

**Comment by gboeing** [comment]
OSMnx 0.7.3 added significant performance improvements for networkx 2.1.

**Comment by gboeing** [comment]
@jesuslovesyiyi did that resolve this for you?

**Comment by jesuslovesyiyi** [comment]
Thank you so much for asking. Yes, it did! You are awesome Geoff!
