### ISSUE TITLE
[Feature Suggestion] Smopy integration

### ISSUE THREAD

**Issue by sfwatergit** [gboeing/osmnx#14]
Hi,

Kudos on great library! I've found it very useful. 

For some recent routing work, I integrated [smopy](https://github.com/rossant/smopy) into a sort-of mangled version of your visualization code. The results are quite nice and permit use of other map tiles besides.

A sample:
![image](https://cloud.githubusercontent.com/assets/1607349/20997759/6075237c-bcbd-11e6-8a8a-52016d35f32b.png)
[A georeferenced network w/ red one ways for (most of) Pittsburg, CA is rendered on top of the map. Also showing two routes in red and blue (alpha < 1 so purple where they match) + origin/destination points.]

I can refactor my implementation and submit a pull request from a fork if you'd like. However, I used an object-oriented approach with an earlier version of the master branch and suspect you would have your own way of implementing it. The general idea though is to initialize a `smopy.Map` instance w/ the coordinates of the network bounding box and call the show_mpl method on any existing matplotlib artist. The .to_map_pixels method on the `smopy.Map` instance must be used to plot any lines, points or other georeferenced data. 

Figured this might be useful for you or other users, but not sure if this is the best place to provide this info. Feel free to close if not relevant. 

Looking forward to future updates!

**Comment by gboeing** [comment]
@sfwatergit yes this is a great idea. I'll integrate this into the next major version. Do you have your code on GitHub?

**Comment by sfwatergit** [comment]
I refactored some code from a much earlier version of osmnx, as I was initially planning to only use the visualization functionality and didn’t feel that this justified the additional dependencies. In particular, I subsumed all of the viz code into a single class, as it reduced some redundancy in my implementation. I’m happy to share that as a gist; however, I can’t yet open source the rest of the project. Would that work for you?

**Comment by gboeing** [comment]
Yes of course. The gist would be useful just so I don't reinvent the wheel when I work to integrate this in a few weeks.

**Comment by sfwatergit** [comment]
Fairly inelegant, but did the job for me: https://gist.github.com/sfwatergit/0267cf5b9ed0b0f3e294592b52e422fc <https://gist.github.com/sfwatergit/0267cf5b9ed0b0f3e294592b52e422fc>. Lines 72-80 set up the smopy.Map object. Anytime you need a coordinate pair plotted, run it through smopy.Map.to_pixels(coord) so that the correct translation from geographic to pixel coordinates is achieved. I’ve updated the map and route plotting code to do just that.

**Comment by gboeing** [comment]
I added a variation of this functionality in d9ee28c305568ddaaf164fb9d8d5a92befcd08ac. It uses [folium](https://github.com/python-visualization/folium) and interactive web maps instead of smopy and static map tiles.
