### ISSUE TITLE
load_graphml of large network graphml file returns error (perhaps related to ast.py)

### ISSUE THREAD

**Issue by cgthigpen** [gboeing/osmnx#142]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
I am using a large polygon (essentially the Phoenix Urbanized Area) as the boundary for use in osmnx to return the bike network within the polygon. Though it takes some time (no complaints, just being honest!), I can use ox.graph_from_polygon and then ox.project_graph without a hitch. Ideally, I would be able to save and load the resulting network, to avoid the time-intensive step of generating it every time. I can save it to a folder ('Output') using ox.save_graphml, but then I have run into the same issue every time when I try to load it back in using ox.load_graphml. Before opening this issue, I tried using a toy example but couldn't replicate the issue. It seems it might be related to the size or complexity of the network I'm trying to load, or perhaps due to me using a jupyter notebook? 

The error message seems to be pointing to "ast.py", which is used on line 243 of save_load.py.

Thanks in advance for the assistance, and let me know if you need further details.

#### What operating system, architecture, Python version, and OSMnx version are you using?
Mac OS 10.13.3 and Windows 7
Python 3.6.3
OSMnx 0.7.3

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>
​altair 1.2.1 py_0 conda-forge
appnope 0.1.0 py36_0 conda-forge
asn1crypto 0.22.0 py36_0 conda-forge
backports 1.0 py36_1 conda-forge
backports.functools_lru_cache 1.4 py36_1 conda-forge
bleach 2.0.0 py36_0 conda-forge
boost 1.66.0 py36_1 conda-forge
boost-cpp 1.66.0 1 conda-forge
branca 0.2.0 py_1 conda-forge
bzip2 1.0.6 1 conda-forge
ca-certificates 2017.7.27.1 0 conda-forge
cairo 1.14.10 0 conda-forge
certifi 2017.7.27.1 py36_0 conda-forge
cffi 1.10.0 py36_0 conda-forge
chardet 3.0.4 py36_0 conda-forge
clangdev 4.0.0 default_0 conda-forge
click 6.7 py36_0 conda-forge
click-plugins 1.0.3 py36_0 conda-forge
cligj 0.4.0 py36_0 conda-forge
conda 4.3.34 py36_0 conda-forge
conda-env 2.6.0 0 conda-forge
cryptography 2.0.3 py36_0 conda-forge
curl 7.55.1 0 conda-forge
cycler 0.10.0 py36_0 conda-forge
decorator 4.1.2 py36_0 conda-forge
descartes 1.1.0 py36_0 conda-forge
entrypoints 0.2.3 py36_1 conda-forge
expat 2.2.5 0 conda-forge
fastcache 1.0.2 py36_0 conda-forge
fiona 1.7.11 py36_3 conda-forge
folium 0.5.0 py_0 conda-forge
fontconfig 2.12.6 0 conda-forge
freetype 2.8.1 0 conda-forge
freexl 1.0.2 2 conda-forge
gdal 2.2.3 py36_0 conda-forge
geopandas 0.3.0 py36_0 conda-forge
geopy 1.11.0 py36_0 conda-forge
geos 3.6.2 1 conda-forge
geotiff 1.4.2 1 conda-forge
gettext 0.19.8.1 0 conda-forge
giflib 5.1.4 0 conda-forge
glib 2.55.0 0 conda-forge
gmp 6.1.2 0 conda-forge
gmpy2 2.0.8 py36_1 conda-forge
hdf4 4.2.13 0 conda-forge
hdf5 1.10.1 1 conda-forge
html5lib 0.999999999 py36_0 conda-forge
icu 58.1 1 conda-forge
idna 2.6 py36_1 conda-forge
intel-openmp 2018.0.0 h68bdfb3_7
ipykernel 4.6.1 py36_0 conda-forge
ipython 6.2.1 py36_0 conda-forge
ipython_genutils 0.2.0 py36_0 conda-forge
jedi 0.10.2 py36_0 conda-forge
jinja2 2.9.6 py36_0 conda-forge
jpeg 9b 2 conda-forge
json-c 0.12.1 0 conda-forge
jsonschema 2.6.0 py36_0 conda-forge
jupyter_client 5.1.0 py36_0 conda-forge
jupyter_core 4.4.0 py_0 conda-forge
kealib 1.4.7 4 conda-forge
kiwisolver 1.0.1 py36_1 conda-forge
krb5 1.14.2 0 conda-forge
libcxx 4.0.0 1 conda-forge
libcxxabi 4.0.1 hebd6815_0
libdap4 3.18.3 2 conda-forge
libedit 3.1.20170329 0 conda-forge
libffi 3.2.1 3 conda-forge
libgdal 2.2.3 3 conda-forge
libgfortran 3.0.0 0 conda-forge
libiconv 1.15 0 conda-forge
libkml 1.3.0 6 conda-forge
libnetcdf 4.4.1.1 10 conda-forge
libpng 1.6.34 0 conda-forge
libpq 9.6.3 0 conda-forge
libsodium 1.0.15 0 conda-forge
libspatialindex 1.8.5 1 conda-forge
libspatialite 4.3.0a 19 conda-forge
libssh2 1.8.0 2 conda-forge
libtiff 4.0.9 0 conda-forge
libxml2 2.9.5 1 conda-forge
llvmdev 4.0.0 default_0 conda-forge
markupsafe 1.0 py36_0 conda-forge
matplotlib 2.2.0 py36_0 conda-forge
mistune 0.8 py36_0 conda-forge
mkl 2017.0.4 h1fae6ae_0
mpc 1.0.3 4 conda-forge
mpfr 3.1.5 0 conda-forge
mpmath 1.0.0 py_0 conda-forge
munch 2.2.0 py36_0 conda-forge
nbconvert 5.3.1 py_1 conda-forge
nbformat 4.4.0 py36_0 conda-forge
ncurses 5.9 10 conda-forge
networkx 2.1 py36_0 conda-forge
notebook 5.2.1 py36_2 conda-forge
numpy 1.13.1 py36_0
openjpeg 2.3.0 2 conda-forge
openssl 1.0.2l 0 conda-forge
osmnx 0.7.2 py36_1 conda-forge
pandas 0.21.0 py36_0 conda-forge
pandoc 2.0.0.1 1 conda-forge
pandocfilters 1.4.1 py36_0 conda-forge
pcre 8.39 0 conda-forge
pexpect 4.2.1 py36_0 conda-forge
pickleshare 0.7.4 py36_0 conda-forge
pip 9.0.1 py36_0 conda-forge
pixman 0.34.0 1 conda-forge
poppler 0.61.1 3 conda-forge
poppler-data 0.4.8 0 conda-forge
proj4 4.9.3 5 conda-forge
prompt_toolkit 1.0.15 py36_0 conda-forge
psycopg2 2.7.3.2 py36_0 conda-forge
ptyprocess 0.5.2 py36_0 conda-forge
pycosat 0.6.2 py36_0 conda-forge
pycparser 2.18 py36_0 conda-forge
pygments 2.2.0 py36_0 conda-forge
pyopenssl 17.2.0 py36_0 conda-forge
pyparsing 2.2.0 py36_0 conda-forge
pyproj 1.9.5.1 py36_0 conda-forge
pysal 1.14.3 py36_0 conda-forge
pysocks 1.6.7 py36_0 conda-forge
python 3.6.4 0 conda-forge
python-dateutil 2.6.1 py36_0 conda-forge
python.app 1.2 py36_0 conda-forge
pytz 2017.3 py_2 conda-forge
pyzmq 16.0.2 py36_2 conda-forge
readline 7.0 0 conda-forge
requests 2.18.4 py36_1 conda-forge
rtree 0.8.3 py36_0 conda-forge
ruamel_yaml 0.11.14 py36_0 conda-forge
scipy 0.19.1 np113py36_0
setuptools 36.6.0 py36_1 conda-forge
shapely 1.6.2 py36_1 conda-forge
simplegeneric 0.8.1 py36_0 conda-forge
six 1.11.0 py36_1 conda-forge
sqlalchemy 1.1.13 py36_0 conda-forge
sqlite 3.20.1 2 conda-forge
sympy 1.1.1 py36_0 conda-forge
terminado 0.6 py36_0 conda-forge
testpath 0.3.1 py36_0 conda-forge
tk 8.6.7 0 conda-forge
tornado 4.5.2 py36_0 conda-forge
traitlets 4.3.2 py36_0 conda-forge
urllib3 1.22 py36_0 conda-forge
vega 0.4.4 py36_1 conda-forge
vincent 0.4.4 py36_0 conda-forge
wcwidth 0.1.7 py36_0 conda-forge
webencodings 0.5 py36_0 conda-forge
wheel 0.30.0 py_1 conda-forge
xerces-c 3.2.0 0 conda-forge
xz 5.2.3 0 conda-forge
yaml 0.1.6 0 conda-forge
zeromq 4.2.1 1 conda-forge
zlib 1.2.11 0 conda-forge
</details>

#### Code that reproduces the issue

```python
# As mentioned earlier in the issue, reproducing the issue is very time consuming, 
# and it doesn't appear in toy examples that I've run.
# So I've shared the python code immediately preceding the error message.

# load street network from GraphML file
b_phx_ua_touching_proj2 = ox.load_graphml(filename = 'b_phx_ua_touching_proj2.graphml', folder = 'Output')
```

Output:
Traceback (most recent call last):

  File "C:\Users\USERNAME\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-15-4d3e897ef555>", line 2, in <module>
    b_phx_ua_touching_proj2 = ox.load_graphml(filename = 'b_phx_ua_touching_proj2.graphml', folder = 'Output')

  File "C:\Users\USERNAME\AppData\Local\Continuum\anaconda3\lib\site-packages\osmnx\save_load.py", line 243, in load_graphml
    data[attr] = ast.literal_eval(data[attr])

  File "C:\Users\USERNAME\AppData\Local\Continuum\anaconda3\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')

  File "C:\Users\USERNAME\AppData\Local\Continuum\anaconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)

  File "<unknown>", line 1
    [FSR 13]
          ^
SyntaxError: invalid syntax

**Comment by cgthigpen** [comment]
Something seems to be fundamentally wrong with the network that was generated in the first place. When I try to use nx.shortest_path it returns a single link, and it's the same link for the various origin-destination pairs I've tested. I'll do some more testing to see if I can figure out the underlying issue.

**Comment by gboeing** [comment]
@cgthigpen any update? Did you track this to a bug with OSMnx? Or is it a problem with something else? Given the nature of your description, sounds like there might be a spatial projection problem somewhere in your workflow?

**Comment by cgthigpen** [comment]
Thanks for checking in, @gboeing. I'm under deadline pressure, so I've switched over to ArcMap for the meantime, but I will likely come back to this after mid-April. I'll check my projections to make everything line up - I think you're probably on the right track.

**Comment by gboeing** [comment]
Ok -- I'll close this for now but please feel free to re-open if you find a bug there...
