### ISSUE TITLE
Issue with loading Manhattan graph

### ISSUE THREAD

**Issue by ppawakapan** [gboeing/osmnx#145]
Hi, I just installed your package, and it's incredibly awesome, but I'm having some trouble trying to load the Manhattan graph, as well as others. Literally all I am doing is:

import osmnx as ox
G = ox.graph_from_place('Manhattan Island, New York City, New York, USA')

But I am getting this error message:

TypeError                                 Traceback (most recent call last)
<ipython-input-46-00aa7c0c7493> in <module>()
----> 1 G = ox.graph_from_place('Hong Kong Island')

/Users/admin/anaconda/lib/python2.7/site-packages/osmnx/core.pyc in graph_from_place(query, network_type, simplify, retain_all, truncate_by_edge, name, which_result, buffer_dist, timeout, memory, max_query_area_size, clean_periphery, infrastructure)
   1809                            name=name, timeout=timeout, memory=memory,
   1810                            max_query_area_size=max_query_area_size,
-> 1811                            clean_periphery=clean_periphery, infrastructure=infrastructure)
   1812 
   1813     log('graph_from_place() returning graph with {:,} nodes and {:,} edges'.format(len(list(G.nodes())), len(list(G.edges()))))

/Users/admin/anaconda/lib/python2.7/site-packages/osmnx/core.pyc in graph_from_polygon(polygon, network_type, simplify, retain_all, truncate_by_edge, name, timeout, memory, max_query_area_size, clean_periphery, infrastructure)
   1688                                           max_query_area_size=max_query_area_size,
   1689                                           infrastructure=infrastructure)
-> 1690         G_buffered = create_graph(response_jsons, name=name, retain_all=True, network_type=network_type)
   1691         G_buffered = truncate_graph_polygon(G_buffered, polygon_buffered, retain_all=True, truncate_by_edge=truncate_by_edge)
   1692 

/Users/admin/anaconda/lib/python2.7/site-packages/osmnx/core.pyc in create_graph(response_jsons, name, retain_all, network_type)
   1326     # add length (great circle distance between nodes) attribute to each edge to
   1327     # use as weight
-> 1328     G = add_edge_lengths(G)
   1329 
   1330     return G

/Users/admin/anaconda/lib/python2.7/site-packages/osmnx/core.pyc in add_edge_lengths(G)
   1161     # first load all the edges' origin and destination coordinates as a
   1162     # dataframe indexed by u, v, key
-> 1163     coords = np.array([[u, v, k, G.nodes[u]['y'], G.nodes[u]['x'], G.nodes[v]['y'], G.nodes[v]['x']] for u, v, k in G.edges(keys=True)])
   1164     df_coords = pd.DataFrame(coords, columns=['u', 'v', 'k', 'u_y', 'u_x', 'v_y', 'v_x'])
   1165     df_coords[['u', 'v', 'k']] = df_coords[['u', 'v', 'k']].astype(np.int64)

TypeError: 'instancemethod' object has no attribute '__getitem__'

Would you know what the issue might be?
By the way I really love this package, and thanks so much for creating something like this!

**Comment by gboeing** [comment]
@ppawakapan can you post your full environment info and package info, as well as how you installed OSMnx?

**Comment by ppawakapan** [comment]
Hi,

Really sorry for the late reply. Somehow it seemed to have fixed itself. Everything's working fine now!
