### ISSUE TITLE
Disappearing node on road/path change

### ISSUE THREAD

**Issue by scottishbee** [gboeing/osmnx#147]
#### Problem description

It looks like OSMnx drops a node on a road->path transition.  Previously this node was being picked up, but now it blends the road/path into a single edge.

#### What operating system, architecture, Python version, and OSMnx version are you using?
I upgraded to 0.7.3 and am running python 3.6.

<details>
Comparing the map from OpenStreetMap (https://www.openstreetmap.org/history#map=19/37.79103/-122.43143) with the osmnx plot, there is no longer a node between the road/path transition along Clay Street.

</details>

#### Code that reproduces the issue

```
import osmnx as ox
%matplotlib inline
sg = ox.graph_from_point((37.791015, -122.43158), distance=200, network_type='walk')
ox.plot_graph(sg, node_size=30)
```

**Comment by gboeing** [comment]
Looks like you are running `graph_from_point` with the default argument `simplify=True`, which simplifies the graph in `strict` mode. Hence it merges together edges that that don't have a 3+ way intersection between them. If you want to retain more "transition" nodes (ie, 2-way intersections where the OSM way IDs change between the two edge), you can simplify the graph with `strict=False`.
