### ISSUE TITLE
Proposal: overpass_json_from_file(filename) to iterparse

### ISSUE THREAD

**Issue by jimr1603** [gboeing/osmnx#149]
Love the library, and I'll send you my blog post of what I've done with it so far if you like.

Loading a graph from a large OSM file fails due to memory, which I believe is because it is not using iterparse. Basically it keeps the whole XML in memory, even the bits it doesn't actually want. 

I can probably have a fork ready to commit in a week or two, just kinda busy with a house move at the moment.

**Comment by gboeing** [comment]
@jimr1603 this is interesting. If you'd like to open a PR when you have time, I'd be glad to review.

**Comment by gboeing** [comment]
Closed for inactivity. Can reopen at later date.

**Comment by jimr1603** [comment]
Sure thing, I've worked out what I need to do, I just need to do it. Moving house this weekend, so don't hold your breath.
