### ISSUE TITLE
graph_from_place AttributeError

### ISSUE THREAD

**Issue by abjer** [gboeing/osmnx#15]
Hey!

I'm using Python 3.5.2 on Ubuntu. When using the graph_from_place I get the following error message. I use Anaconda with all packages installed from the 'conda-forge' channel. The issue remains even when changing to Python 2 or using the newest version from github installed through pip and across machines.

```
>>> import osmnx as ox
>>> G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andreasbn/anaconda3/envs/python2/lib/python2.7/site-packages/osmnx/osmnx.py", line 1824, in graph_from_place
    truncate_by_edge=truncate_by_edge, name=name, timeout=timeout, memory=memory, max_query_area_size=max_query_area_size, clean_periphery=clean_periphery)
  File "/home/andreasbn/anaconda3/envs/python2/lib/python2.7/site-packages/osmnx/osmnx.py", line 1751, in graph_from_polygon
    G_buffered = truncate_graph_polygon(G_buffered, polygon_buffered, retain_all=True, truncate_by_edge=truncate_by_edge)
  File "/home/andreasbn/anaconda3/envs/python2/lib/python2.7/site-packages/osmnx/osmnx.py", line 1306, in truncate_graph_polygon
    points_within_geometry = intersect_index_quadrats(gdf_nodes, polygon)
  File "/home/andreasbn/anaconda3/envs/python2/lib/python2.7/site-packages/osmnx/osmnx.py", line 1268, in intersect_index_quadrats
    possible_matches_index = list(sindex.intersection(poly.bounds))
AttributeError: 'NoneType' object has no attribute 'intersection'

```

**Comment by gboeing** [comment]
Do you have libspatialindex installed, per the rtree install [instructions](http://toblerity.org/rtree/install.html#nix)?

**Comment by abjer** [comment]
Yes, I have installed 1.8.5 also from conda-forge channel

**Comment by gboeing** [comment]
It appears to be an rtree bug that affects the combination of rtree 0.8.2 + libspatialindex 1.8.5 + Linux. This bug was not reproducible for me on Mac or Windows. The bug is documented in [an issue](https://github.com/Toblerity/rtree/issues/68) in rtree's GitHub repo, and it was recently [fixed](https://github.com/Toblerity/rtree/pull/77) but hasn't been released yet. But you can fix it in the meantime by installing the GitHub version of rtree:

```
pip install --upgrade https://github.com/Toblerity/rtree/tarball/master
```

See #8

**Comment by abjer** [comment]
Cheers, I'll wait for the update to arrive through conda

**Comment by gboeing** [comment]
rtree 0.8.3 is now released and available via pip: https://github.com/Toblerity/rtree/issues/79#issuecomment-267150896

Closing this issue, accordingly.
