### ISSUE TITLE
replace Json caching with some alternative?

### ISSUE THREAD

**Issue by Casyfill** [gboeing/osmnx#155]
just wondering if it makes sense to replace (optionally?) JSON dumps with ZODB or tinyMongo.

**Comment by Casyfill** [comment]
yes, I understand the dependency con, that is why I am asking. (although it can be an optional dependency, like rtree for geopandas)

I am not sure to which extent there will be less space - but might be significantly faster to read / write cache

**Comment by gboeing** [comment]
@Casyfill has cache read/write speed been a bottleneck in an application of yours? Do you have an example or benchmark? Just trying to see if this is a significant issue to solve.

**Comment by gboeing** [comment]
Closing this for now, pending benchmarks to demonstrate significance. Happy to re-open if someone wants to pursue that, and PRs always welcome.
