### ISSUE TITLE
ox.add_edge_grades() fails when network has zero length edges

### ISSUE THREAD

**Issue by anastasiaclark** [gboeing/osmnx#156]
I was using the `add_edge_grades()` function and got the division by zero error.

```python

ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-165-f0944a5b715b> in <module>()
      4 # Get the directed grade (ie, rise over run)--slope for each edge in the network and add it to the edge as an attribute.
      5 # keeps downhil change negative
----> 6 bx_streets = ox.add_edge_grades(bx_streets, add_absolute=False)

~/anaconda/envs/gep662/lib/python3.6/site-packages/osmnx/elevation.py in add_edge_grades(G, add_absolute)
    114     for u, v, data in G.edges(keys=False, data=True):
    115         elevation_change = G.nodes[v]['elevation'] - G.nodes[u]['elevation']
--> 116         grade = elevation_change / data['length']
    117         data['grade'] = grade
    118         if add_absolute:

ZeroDivisionError: float division by zero
```
It turned out that the network had few edges with zero length attribute; I identified and removed them. It would be helpful to incorporate the workaround for such situations into the `add_edge_grades()` function, maybe as an additional parameter like `drop_zero_len=True`

The network I used was for the Bronx using this line of code:`bx_streets = ox.graph_from_place('Bronx, New York, USA', network_type='bike')`. Not sure how common zero length edges in other networks.

**Comment by gboeing** [comment]
@anastasiaclark that's interesting. Do you have a sense of why those edges had length zero? What kind of edges were they (ie, what was the highway type)? How many were there?

**Comment by anastasiaclark** [comment]
The network type is 'bike'. There were four edges with zero length; all in the same location. I mapped them over the OSM and they appear to be very tiny. Attached is the code that reproduces the error and examines the zero length edges.
[Archive.zip](https://github.com/gboeing/osmnx/files/1969534/Archive.zip)

**Comment by gboeing** [comment]
I just ran the code you uploaded and I'm not getting any errors.

```python
import geopandas as gpd
import osmnx as ox
ox.config(use_cache=True, log_console=True)
bx = ox.graph_from_place('Bronx, New York, USA', network_type='bike')
bx = ox.add_node_elevations(bx, api_key='YOUR-KEY-HERE')
bx = ox.add_edge_grades(bx, add_absolute=False)
```

That all runs fine. What version of OSMnx are you using? Make sure you're upgraded to the latest. If you keep getting the error, please post your full python environment info, all package versions, and the full code to reproduce the error.

**Comment by anastasiaclark** [comment]
You are right! Updating to the latest version (from 0.6 to 0.8) of osmnx fixed the error!

**Comment by jchaykow** [comment]
```
G = ox.graph_from_bbox(40.68, 40.19, -79.68, -80.37, network_type='drive', simplify=False)
G = ox.elevation.add_node_elevations(G, elevAPIkey, max_locations_per_batch=512, pause_duration=0.02)
G = ox.elevation.add_edge_grades(G, add_absolute=True)

ZeroDivisionError: float division by zero
```

`Rtree-0.9.3 geopandas-0.6.2 networkx-2.4 osmnx-0.11`
