### ISSUE TITLE
Wrong with "not implemented for multigraph type"

### ISSUE THREAD

**Issue by chaoshengt** [gboeing/osmnx#157]
@gboeing , when i run **OSMnx features demo**, there is something wrong ,
when I run the code `
G = ox.graph_from_place('Piedmont, California, USA', network_type='drive')  

fig, ax = ox.plot_graph(G)  

........

edge_centrality = nx.closeness_centrality(nx.line_graph(G))
`
it appeared
`
NetworkXNotImplemented                    Traceback (most recent call last)
<ipython-input-9-ac73c088a7b1> in <module>()
      2 # edge_centrality = nx.closeness_centrality(nx.line_graph(G))
      3 
----> 4 edge_centrality = nx.closeness_centrality(nx.line_graph(G))

<decorator-gen-503> in line_graph(G, create_using)

D:\Anaconda3\lib\site-packages\networkx\utils\decorators.py in _not_implemented_for(not_implement_for_func, *args, **kwargs)
     69         if match:
     70             msg = 'not implemented for %s type' % ' '.join(graph_types)
---> 71             raise nx.NetworkXNotImplemented(msg)
     72         else:
     73             return not_implement_for_func(*args, **kwargs)

NetworkXNotImplemented: not implemented for multigraph type
`
How to deal with it？ thank you. ：）

**Comment by chaoshengt** [comment]
networkx 2.2rc done

**Comment by gboeing** [comment]
See also https://github.com/gboeing/osmnx-examples/issues/8

**Comment by studentextra** [comment]
I'm having the same problem

**Comment by studentextra** [comment]
How can this be resolved?
