### ISSUE TITLE
ValueError: Geometry must be a shapely Polygon or MultiPolygon

### ISSUE THREAD

**Issue by gboeing** [gboeing/osmnx#16]
If we run this code:
```
import osmnx as ox
ox.config(log_console=True)
G = ox.graph_from_place('Baltimore, Maryland, USA', network_type='drive')
```
We get this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-afb511cf7347> in <module>()
      1 import osmnx as ox
      2 ox.config(log_console=True)
----> 3 G = ox.graph_from_place('Baltimore, Maryland, USA', network_type='drive')

C:\Anaconda\lib\site-packages\osmnx\osmnx.py in graph_from_place(query, network_type, simplify, retain_all, truncate_by_edge, name, which_result, buffer_dist, timeout, memory, max_query_area_size, clean_periphery)
   1815     # create graph using this polygon(s) geometry
   1816     G = graph_from_polygon(polygon, network_type=network_type, simplify=simplify, retain_all=retain_all, 
-> 1817                            truncate_by_edge=truncate_by_edge, name=name, timeout=timeout, memory=memory, max_query_area_size=max_query_area_size, clean_periphery=clean_periphery)
   1818 
   1819     log('graph_from_place() returning graph with {:,} nodes and {:,} edges'.format(len(G.nodes()), len(G.edges())))

C:\Anaconda\lib\site-packages\osmnx\osmnx.py in graph_from_polygon(polygon, network_type, simplify, retain_all, truncate_by_edge, name, timeout, memory, max_query_area_size, clean_periphery)
   1730         raise ValueError('Shape does not have a valid geometry')
   1731     if not isinstance(polygon, (Polygon, MultiPolygon)):
-> 1732         raise ValueError('Geometry must be a shapely Polygon or MultiPolygon')
   1733 
   1734     if clean_periphery and simplify:

ValueError: Geometry must be a shapely Polygon or MultiPolygon
```

**Comment by gboeing** [comment]
This is behaving correctly. The API returns a _point_ for the query 'Baltimore, Maryland, USA' but `graph_from_place` and `graph_from_polygon` require a geometry that is a Polygon or MultiPolygon to proceed -- as the error message explains.

OSMnx passes the query string 'Baltimore, Maryland, USA' to OSM's nominatim API to get a polygon representing the boundaries of the place. It then collects the street network within these boundaries. But if you pass 'Baltimore, Maryland, USA' to nominatim directly yourself, you can see [the result](https://nominatim.openstreetmap.org/search?format=json&limit=10&dedupe=0&polygon_geojson=1&q=Baltimore%2C+Maryland%2C+USA).

Nominatim successfullly geocodes it and returns 2 results. The first's geometry is simply a point representing the center of the city. The 2nd result's geometry is the city's administrative boundary. The API usually prioritizes the latter result with a higher importance score, but for whatever reason, in Baltimore's case it doesn't. By default OSMnx uses the first result and tries to create a street network from it. But with a point, it (obviously) can't find any network data within the geometry. 

Rather, we must point OSMnx at the 2nd result that correctly includes the boundary data by using the `which_result` function argument, as demonstrated in [the tutorial](https://github.com/gboeing/osmnx/blob/master/examples/02-example-osm-to-shapefile.ipynb):
```
G = ox.graph_from_place('Baltimore, Maryland, USA', network_type='drive', which_result=2)
```

If none of the geocoding results contain polygon geometry, you can still get the local street network using `graph_from_address(place_name, distance)` or `graph_from_point`.

**Comment by gboeing** [comment]
The `graph_from_place` docstring has been updated to reflect this: https://github.com/gboeing/osmnx/blob/673ddf2a223cb6301cd9b51fafa74fba08bb10e7/osmnx/core.py#L1487

**Comment by gboeing** [comment]
Another example:

```python
G = ox.graph_from_place('Beijing, China', network_type='drive')
G_proj = ox.project_graph(G)
fig, ax = ox.plot_graph(G_proj)
```
...throws the error described above because the first geocode result for "Beijing, China" returns a point as the geometry. The second geocode result returns a polygon so this error is fixed by passing `which_result=2`:

```python
G = ox.graph_from_place('Beijing, China', which_result=2, network_type='drive')
G_proj = ox.project_graph(G)
fig, ax = ox.plot_graph(G_proj)
```

...produces:

![](https://i.imgur.com/thEtwBr.jpg)

If OSM had no polygon for this place query in *any* of the geocoding results, we could have used `graph_from_address` instead, like:

```python
G = ox.graph_from_address('Beijing, China', distance=10000, network_type='drive')
```

**Comment by d3netxer** [comment]
@gboeing I get this error when trying to run 
```
G = ox.graph_from_place('Beijing, China', which_result=2, network_type='drive')
```

```
G = ox.graph_from_place('Beijing, China', which_result=2, network_type='drive')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myusername/anaconda/envs/osmnx/lib/python3.6/site-packages/osmnx/core.py", line 1800, in graph_from_place
    clean_periphery=clean_periphery, infrastructure=infrastructure)
  File "/Users/myusername/anaconda/envs/osmnx/lib/python3.6/site-packages/osmnx/core.py", line 1679, in graph_from_polygon
    G_buffered = create_graph(response_jsons, name=name, retain_all=True, network_type=network_type)
  File "/Users/myusername/anaconda/envs/osmnx/lib/python3.6/site-packages/osmnx/core.py", line 1290, in create_graph
    raise ValueError('There are no data elements in the response JSON objects')
ValueError: There are no data elements in the response JSON objects
```

any idea what it could be?

**Comment by gboeing** [comment]
@d3netxer I just re-ran that code line, and it succeeded without error on my machine.

**Comment by scottishbee** [comment]
I am seeing the same error running a line that previously worked (~last worked in August 2017):

`G = ox.graph_from_place('San Francisco, California, USA', network_type='all_private')`

Adding the `which_result=2` parameter did not change the error.

**Comment by gboeing** [comment]
@scottishbee the Nominatim geocoder that resolves place names has changed since then. Try to provide an explicit query, and it should work, as seen in [this example](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/12-node-elevations-edge-grades.ipynb):

```python
place_query = {'city':'San Francisco', 'state':'California', 'country':'USA'}
G = ox.graph_from_place(place_query, network_type='drive')
```

**Comment by shreyatpandey** [comment]
Hey,
I have question regarding the one-square mile image of Irvine,Portland.
Which function did you use to obtain the desired image? If you could please share that code or function with us.
Thanx,

**Comment by gboeing** [comment]
@shreyatpandey https://github.com/gboeing/osmnx-examples

**Comment by gboeing** [comment]
For more on geocoding/polygon logic, see also this [thread](https://www.reddit.com/r/gis/comments/8swxc3/nominatim_logic_for_downloading_administrative/).

**Comment by gboeing** [comment]
@puntofisso regarding your first question, you can run:

```python
import requests
url = 'https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City of London, UK'
requests.get(url).text
```

...to see exactly what nominatim is returning when we make that GET request. If you see something unexpected or inconsistent, please open a new issue.

Regarding your second question, gdf_from_place is for geocoding query strings/dicts, not for looking up IDs. Other discussion about that would be best suited to a new issue or a PR if new functionality is proposed.

**Comment by puntofisso** [comment]
Hi @gboeing, thanks for responding so quickly! :) So... let me clarify a little after doing a couple of tests.

What seems to be happening here is that calling that url via requests returns two different results than when I use a browser, which are different from the results returned by gdf_from_place.

**Using a browser**, I pass 'City of London, UK' as its (urlencoded) counterpart 'City%20of%20London,%20UK', so the url I enter in the browser is:
[https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City%20of%20London,%20UK](https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City%20of%20London,%20UK)

The query returns the two results as stated above:
1. a POINT for osm_id 27365030
2. and a POLYGON for osm_id 51800.

If I **use requests**, regardless of using urlencoding or not, i.e. whether i call

`import requests
url = 'https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City of London, UK'
requests.get(url).text`

or

`url = 'https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City%20of%20London,%20UK'`

I get two result which are different from the in-browser ones: 

1. a POINT for osm_id 27365030 which is the same as above 
2. a different POLYGON in the second result, for osm_id 4001857 (instead of osm_id 51800 - although this is an acceptable result).

If I use **gdf_from_place**, I get something else entirely
1. ox.gdf_from_place('City of London, UK',which_result=0) -> returns POINT as above
2. ox.gdf_from_place('City of London, UK',which_result=1) -> returns the same POINT 
3. ox.gdf_from_place('City of London, UK',which_result=2) -> returns the POLYGON for osm_id 4001857

So even if we discount the browser behaviour, which is probably caused by the way the urlencoding engages with the http library, if you say that gdf_from_place should work exactly as the result of requests then there is a discrepancy for the first two results. What would be a good place to understand where the discrepancy stems from?

If I'm not understanding how this is supposed to work, please feel free to say :) I'm just trying to make sure I get 100% how the queries are parsed.

**Comment by gboeing** [comment]
@puntofisso could you open a new issue for this and I'll explore it? I think this is requests vs browser inconsistency is unrelated to the original issue here.

**Comment by puntofisso** [comment]
Sure @gboeing and thanks!

**Comment by tiwaris436** [comment]
I am getting error while running these codes.

G = ox.graph_from_place('Pune, Maharashtra', which_result=2, network_type='drive')
G_proj = ox.project_graph(G)
fig, ax = ox.plot_graph(G_proj)

"TypeError: Geometry must be a shapely Polygon or MultiPolygon. If you requested graph from place name or address, make sure your query resolves to a Polygon or MultiPolygon, and not some other geometry, like a Point. See OSMnx documentation for details."

Please help.
Thanks

**Comment by gboeing** [comment]
@tiwaris436 I'm not really sure what else to say that hasn't already been said in this thread and the many other related issue threads. The error message is pretty straightforward the documentation here provides comprehensive info on why you're seeing this and how to resolve it.

**Comment by etrnote** [comment]
I've also run into the same problem a few times, and adding `which_result=2 ` solved it.
How about adding it to the code?
Maybe adding a parameter that allows iteration over the results till a polygon is found,
or an exception that tries to execute `gdf_from_place` with `which_result=2` as a parameter in case it fails on the first result.
I'd be happy to try and add it if this sounds like a good idea.

**Comment by gboeing** [comment]
@etrnote see #320

**Comment by vamatya** [comment]
> @scottishbee the Nominatim geocoder that resolves place names has changed since then. Try to provide an explicit query, and it should work, as seen in [this example](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/12-node-elevations-edge-grades.ipynb):
> 
> ```python
> place_query = {'city':'San Francisco', 'state':'California', 'country':'USA'}
> G = ox.graph_from_place(place_query, network_type='drive')
> ```

The above works. However, if I changed place_query as follows: 
`place_query = {'county':'Los Angeles', 'state':'California', 'country':'USA'}`
`G = ox.graph_from_place(place_query,which_result=2, network_type='drive')`
`ox.save_graph_shapefile(G, filename='la_county')` 

, I get the following error: 

File "/Users/username/test_runs/scripts/vto_scripts/osmnx/osmnx_place_by_name.py", line 6, in <module>
    G = ox.graph_from_place(place_query,which_result=2, network_type='drive')
  File "/Users/username/miniconda3/envs/ox3.6/lib/python3.6/site-packages/osmnx/graph.py", line 610, in graph_from_place
    polygon = gdf_place["geometry"].unary_union
  File "/Users/username/miniconda3/envs/ox3.6/lib/python3.6/site-packages/geopandas/geodataframe.py", line 576, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "/Users/username/miniconda3/envs/ox3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/username/miniconda3/envs/ox3.6/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'geometry'


 I also tried: 
`place = 'Los Angeles County, California, USA'` 
in place of "place_query", which gives following error: 


File "/Users/username/test_runs/scripts/vto_scripts/osmnx/osmnx_place_by_name.py", line 6, in <module>
    G = ox.graph_from_place(place,which_result=2, network_type='drive')
  File "/Users/username/miniconda3/envs/ox3.6/lib/python3.6/site-packages/osmnx/graph.py", line 626, in graph_from_place
    custom_settings=custom_settings,
  File "/Users/username/miniconda3/envs/ox3.6/lib/python3.6/site-packages/osmnx/graph.py", line 482, in graph_from_polygon
    G_buffered, polygon, retain_all=retain_all, truncate_by_edge=truncate_by_edge
  File "/Users/username/miniconda3/envs/ox3.6/lib/python3.6/site-packages/osmnx/truncate.py", line 166, in truncate_graph_polygon
    gdf_nodes, polygon, quadrat_width=quadrat_width, min_num=min_num
  File "/Users/username/miniconda3/envs/ox3.6/lib/python3.6/site-packages/osmnx/utils_geo.py", line 427, in _intersect_index_quadrats
    raise Exception("There are no nodes within the requested geometry")
Exception: There are no nodes within the requested geometry

Any insight what I might be doing incorrectly?

**Comment by gboeing** [comment]
> Any insight what I might be doing incorrectly?

@vamatya per the contributing guidelines, please ask general "how-to" usage questions on https://stackoverflow.com/ for community troubleshooting. One quick thought: why are you using `which_result=2`? It'll probably work fine if you don't.

**Comment by vamatya** [comment]
@gboeing Thank you for the prompt reply. Another tool that used OSMNX to generate the shapefile suggested the use of `which_result=2`. You are probably correct, that ignoring this value could work. Also, thanks for reminding me about the contributing guidelines.

**Comment by gboeing** [comment]
No worries. It's just easier for everyone to respond usage questions on StackOverflow than here in the issue tracker. Good luck.

**Comment by kenomaerz** [comment]
Would you accept a pull request that automatically selects the first polygon from the results if which_result is not specified?

Just started playing around with osmnsx. I intend to use it for a printing project. Thank you for your efforts!

**Comment by korasami96** [comment]
Hello @gboeing . Iam trying to execute :
`import osmnx as ox
place_query = {'state':'Illinois', 'country':'USA'}
G = ox.graph_from_place(place_query,  network_type='drive',which_result=2)`

But iam getting this error : 
`OSM returned fewer than `which_result=2` results for query "{'state': 'Illinois', 'country': 'USA'}"`

Please, can you help me?
Thanks

**Comment by korasami96** [comment]
Hello @gboeing . Iam trying to execute this :
`import osmnx as ox
 place_query = {'state':'Illinois', 'country':'USA'} 
G = ox.graph_from_place(place_query, network_type='drive',which_result=2)
`

But iam getting this error :
`OSM returned fewer than 'which_result=2' results for query "{'state': 'Illinois', 'country': 'USA'}"`


Please, can you help me?
Thanks

**Comment by gboeing** [comment]
@korasami96 per the contributing guidelines please as "how to" questions on StackOverflow.

**Comment by mejl** [comment]
I get this error when adding dist=1

`G = ox.graph_from_point((lat, lng), dist=1, network_type="bike")`

`G = ox.graph_from_point((lat, lng), dist=100, network_type="bike")`

Works. But How can I get rid of this error if I have dist=1?
