### ISSUE TITLE
Allow plot_graph to receive existing fig and ax objects

### ISSUE THREAD

**Issue by temetski** [gboeing/osmnx#163]
Currently `plot_graph` creates it's own axes. It would be nice to allow it to have fig and ax objects as parameters. Use cases would be to plot two graph subnetworks that don't exist as one graph object within the same figure.

**Comment by gboeing** [comment]
In the meantime, you can compose subgraphs into a supergraph using `nx.compose`. If this is insufficient for your use case, please document it and feel free to open a PR!

**Comment by temetski** [comment]
`nx.compose` would indeed work to create a supergraph. However my use case would be trying to generate this plot: 
![image](https://user-images.githubusercontent.com/6328105/39731479-5f448082-529a-11e8-918a-d2454974d5e4.png)

I do it by using my version of plot_graph twice: one to draw the streets in thin gray, and another (taking in the previous figure) to generate the colored edges.

```python
fig, ax = plot_graph(streets, node_size=0, edge_linewidth=0.1)
fig, ax = plot_graph(Gprime, fig=fig, ax=ax, color=color, edge_linewidth=1, show=False,
            node_size=0)
```
Yes, this could also be done based on your examples by creating a list comprehension that runs over edges and sets the edge widths and colors accordingly, but it seems simpler to have control over the figure and axis objects `plot_graph` draws on.

**Comment by gboeing** [comment]
@temetski @guenteru this would be useful. PR welcome.

**Comment by guenteru** [comment]
Hi, 
I'm currently working on it. It just needs a bit more testing.
Will do the PR the following days.

**Comment by gboeing** [comment]
Closing this issue here as the discussion has moved to the PR in code review.
