### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by truls-r** [gboeing/osmnx#164]
#### Problem description:
With 'osmnx.graph_from_place' applied to rural areas, e.g. 'lyngen, norway' with network_type='drive', osmnx is not able to correctly simplify the network topology, casting a RecursionError, because there are too many nodes between "endpoints".
This can be fixed by adjusting the recursion limit, e.g. in the case above, with Windows 10:
`sys.setrecursionlimit(10**5)`
Would it be an idea to add a note about this in the documentation?

**Comment by gboeing** [comment]
@truls-r yes, thanks, would you like to open a PR to include this note in the relevant docstring?
