### ISSUE TITLE
Something wrong in 0.8.1 when I run poi code

### ISSUE THREAD

**Issue by chaoshengt** [gboeing/osmnx#167]
when I update osmnx from 0.8 to 0.8.1, and  run the code bellow,there is something wrong , how to solve it ?  :)   there is nothing wrong in version:0.8.0

`import networkx as nx
import osmnx as ox
import requests
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.cm as cm
import matplotlib.colors as colors
ox.config(use_cache=True, log_console=True)
print('OSMNX版本：',ox.__version__)  
print('--------         \n NetworkX版本：',nx.__version__)

place = "Kamppi, Helsinki, Finland"

all_pois = ox.pois_from_place(place=place)`

![qq 20180524180835](https://user-images.githubusercontent.com/7035642/40479184-9acf8b5c-5f7d-11e8-89bf-133aa55da2f4.png)

**Comment by gboeing** [comment]
@chaoshengt update pandas to >= 0.23

**Comment by chaoshengt** [comment]
@gboeing Thanks :+1:
