### ISSUE TITLE
Simplifying Topography - Exclude nodes from being removed from the graph

### ISSUE THREAD

**Issue by ogjetaj** [gboeing/osmnx#168]
Hi, Thank you for such an awesome package. 
I have a question regarding the graph simplification. 
I have a set of nodes ( as lat-lon pairs), that need to be part of the final graph and should not be removed during the simplify process. 
Is there a way I can perform this using the functionality that already exists as part of the package?

Thank you

**Comment by gboeing** [comment]
No there isn't. But if you want to add that ability on your installation, edit the `is_endpoint` function here: https://github.com/gboeing/osmnx/blob/33059780fb99f83845ad320d2f71d182a19a9d19/osmnx/simplify.py#L49

Add a new `if` statement like:

```python
if node in my_nodes:
    return True
```

where `my_nodes` is a list of OSM node IDs corresponding to the lat-lng pairs you wish you retain.

**Comment by ogjetaj** [comment]
Thank you, that works just right
