### ISSUE TITLE
Bike path not pulled in "walk" graph

### ISSUE THREAD

**Issue by scottishbee** [gboeing/osmnx#169]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

A bike path is not getting pulled as a network for walk paths.  Even after openstreetmap has been updated to explicitly label this edge as "Allowed Access > Foot : Yes".

#### What operating system, architecture, Python version, and OSMnx version are you using?
python 3.6.0, osmnx 0.7.3

<details>
Comparing the map to openstreetmap
https://www.openstreetmap.org/edit#map=17/37.75685/-122.38933 (The bike path connects Tennessee St, between Tubbs & 22nd).

</details>

#### Code that reproduces the issue

```python
import osmnx as ox
%matplotlib inline

#checkout individual issue
sg = ox.graph_from_point((37.756681, -122.389197), distance=200, network_type='walk')
ox.plot_graph(sg, node_size=30)
```

**Comment by gboeing** [comment]
@scottishbee see https://github.com/gboeing/osmnx/issues/151#issuecomment-379491607 for a similar question/answer.

**Comment by gboeing** [comment]
To clarify further, you might just want to pass a custom filter that does not discard cycleways:

```python
cf = """
     ["area"!~"yes"]
     ["highway"!~"motor|proposed|construction|abandoned|platform|raceway"]
     ["foot"!~"no"]
     ["service"!~"private"]
     ["access"!~"private"]
     """
sg = ox.graph_from_point((37.756681, -122.389197), distance=200, custom_filter=cf)
fig, ax = ox.plot_graph(sg, node_size=50)
```

**Comment by scottishbee** [comment]
Thanks, I didn't know about the advanced query features.

It looks like if I pull down cycleways, they inherit the one-wayness of the cycleway.  Even edges I was previously getting via "walk", if they allow cycling then they inherit the one-way direction of the cycleway, whereas "walk" is always both directions.

I have a hack built that detects one-way and creates a flipped edge to complement.  But I suspect there's a better way for me to build the custom filter.

**Comment by gboeing** [comment]
@scottishbee ah, yes, you should also specify `network_type='walk'` to get edges in both directions when the graph is constructed:

```python
cf = """
     ["area"!~"yes"]
     ["highway"!~"motor|proposed|construction|abandoned|platform|raceway"]
     ["foot"!~"no"]
     ["service"!~"private"]
     ["access"!~"private"]
     """
sg = ox.graph_from_point((37.756681, -122.389197), distance=200, custom_filter=cf, network_type='walk')
fig, ax = ox.plot_graph(sg, node_size=50)
```

**Comment by rohanaras** [comment]
In case anyone runs into the issue I just ran into, for this code to not pull in non `"highway"` features (like the nearby Muni line), you'll need to add a generic `["highway"]` filter:

```python
cf = """
     ["area"!~"yes"]
     ["highway"]
     ["highway"!~"motor|proposed|construction|abandoned|platform|raceway"]
     ["foot"!~"no"]
     ["service"!~"private"]
     ["access"!~"private"]
     """
sg = ox.graph_from_point((37.756681, -122.389197), dist=200, custom_filter=cf, network_type='walk')
fig, ax = ox.plot_graph(sg, node_size=50)

```
