### ISSUE TITLE
graph_from_place return exception for street network from place name example in documentation

### ISSUE THREAD

**Issue by khorshidisamira** [gboeing/osmnx#170]
#### Problem:
I need to get the nodes of Los Angeles, California. According to http://geoffboeing.com/2016/11/osmnx-python-street-networks/, "2e) street network from place name" I want to get the nodes but I got " Exception: There are no nodes within the requested geometry"

####  Ubuntu 16.4
Python 2.7
OSMnx latest version
#### Environment's packages 
Package                            Version     
---------------------------------- ------------
adium-theme-ubuntu                 0.3.4       
backports.functools-lru-cache      1.5         
backports.shutil-get-terminal-size 1.0.0       
bleach                             2.1.3       
certifi                            2018.4.16   
chardet                            3.0.4       
click                              6.7         
click-plugins                      1.0.3       
cligj                              0.4.0       
configparser                       3.5.0       
cycler                             0.10.0      
decorator                          4.3.0       
descartes                          1.1.0       
entrypoints                        0.2.3       
enum34                             1.1.6       
Fiona                              1.7.11.post2
functools32                        3.2.3.post2 
future                             0.16.0      
geopandas                          0.3.0       
html5lib                           1.0.1       
idna                               2.6         
ipykernel                          4.8.2       
ipython                            5.7.0       
ipython-genutils                   0.2.0       
ipywidgets                         7.2.1       
Jinja2                             2.8         
jsonschema                         2.6.0       
jupyter                            1.0.0       
jupyter-client                     5.2.3       
jupyter-console                    5.2.0       
jupyter-core                       4.4.0       
kiwisolver                         1.0.1       
MarkupSafe                         0.23        
matplotlib                         2.2.2       
mistune                            0.8.3       
munch                              2.3.2       
nbconvert                          5.3.1       
nbformat                           4.4.0       
networkx                           2.1         
notebook                           5.5.0       
numpy                              1.14.3      
osmnx                              0.8.1       
pandas                             0.23.0      
pandocfilters                      1.4.2       
pathlib2                           2.3.2       
pexpect                            4.0.1       
pickleshare                        0.7.4       
pip                                10.0.1      
prompt-toolkit                     1.0.15      
protobuf                           3.5.2.post1 
ptyprocess                         0.5         
pycurl                             7.43.0      
Pygments                           2.2.0       
PyMySQL                            0.7.2       
pyparsing                          2.2.0       
pyproj                             1.9.5.1     
python-dateutil                    2.7.3       
pytz                               2018.4      
pyzmq                              17.0.0      
qtconsole                          4.3.1       
requests                           2.18.4      
Rtree                              0.8.3       
scandir                            1.7         
Send2Trash                         1.5.0       
setuptools                         39.2.0      
Shapely                            1.6.4.post1 
simplegeneric                      0.8.1       
six                                1.11.0      
subprocess32                       3.5.1       
terminado                          0.8.1       
testpath                           0.3.1       
tornado                            4.2.1       
traitlets                          4.3.2       
unity-lens-photos                  1.0         
urllib3                            1.22        
wcwidth                            0.1.7       
webencodings                       0.5.1       
widgetsnbextension                 3.2.1  
<details>
# Paste the output of your Python packages and their versions here, between these two "details" tags
Traceback (most recent call last):
  File "getNodes.py", line 3, in <module>
    G = ox.graph_from_place('Los Angeles, California', network_type='drive')
  File "/usr/local/lib/python2.7/dist-packages/osmnx/core.py", line 1862, in graph_from_place
    custom_filter=custom_filter)
  File "/usr/local/lib/python2.7/dist-packages/osmnx/core.py", line 1749, in graph_from_polygon
    G = truncate_graph_polygon(G_buffered, polygon, retain_all=retain_all, truncate_by_edge=truncate_by_edge)
  File "/usr/local/lib/python2.7/dist-packages/osmnx/core.py", line 1155, in truncate_graph_polygon
    points_within_geometry = intersect_index_quadrats(gdf_nodes, polygon, quadrat_width=quadrat_width, min_num=min_num, buffer_amount=buffer_amount)
  File "/usr/local/lib/python2.7/dist-packages/osmnx/core.py", line 1107, in intersect_index_quadrats
    raise Exception('There are no nodes within the requested geometry')
Exception: There are no nodes within the requested geometry

</details>

#### Code that reproduces the issue

```python
# your code goes here
import osmnx as ox
G = ox.graph_from_place('Los Angeles, California', network_type='drive')
ox.plot_graph(G)
```

**Comment by gboeing** [comment]
Hi @khorshidisamira, see the documentation (that blog post isn't an official doc, as it's not revised with every update of OSMnx): https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_place

OSMnx geocodes your query to a polygon (if OSM has one) then gets the network with those bounds. The geocoder changes sometimes, and no longer resolves "Los Angeles, California" to the city polygon. Try a more explicit query string for disambiguation. For example, `G = ox.graph_from_place('Los Angeles, Los Angeles County, California, USA', network_type='drive')` should work for you.

For a related issue, see https://github.com/gboeing/osmnx/issues/16
