### ISSUE TITLE
pois from place error

### ISSUE THREAD

**Issue by TRomijn** [gboeing/osmnx#171]
#### Problem
POIs from place function contains small bugs.
#### Versions:
osmnx: 0.8.1
pandas 0.22.0
geopandas 0.3.0
3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:20:50) [MSC v.1900 64 bit (AMD64)]

Error message:
```python
append() got an unexpected keyword argument 'sort'
``` 

#### Code 

```python
ox.pois_from_place(place="Amsterdam, The Netherlands")
```

#### Solution
commenting the sort=False argument on three places in pois.py solved the issue.
#### Solution 2:
I just found that the pandas package has released version 0.23.0. Updating to the latest version of pandas solved the issue.

**Comment by TRomijn** [comment]
Even after fixing that error, the function is very fickle. 
When I try:
 `ox.pois_from_place(place='Amsterdam, The Netherlands', amenities='hospital')`,
I receive a GeoDataFrame with shape (12323, 447), containing all amenities and not only hospitals.
When I try:
`ox.pois_from_place(place='The Netherlands', amenities='hospital')`
I receive an empty GeoDataFrame.

**Comment by gboeing** [comment]
@TRomijn the `amenities` argument is of type `list`, per the docstring.

```python
POIs = ox.pois_from_place(place='Amsterdam, The Netherlands', amenities=['hospital'])
```

**Comment by TRomijn** [comment]
Thanks for the quick reply! Stupid mistake from my side..

Follow up:
This line works:
`POIs = ox.pois_from_place(place='Nepal', amenities=['hospital'])`
While this line results in an error:
`POIs = ox.pois_from_place(place='The Netherlands', amenities=['hospital'])`
Error message:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-91f274581b3e> in <module>()
----> 1 POIs = ox.pois_from_place(place='The Netherlands', amenities=['hospital'])

~\Anaconda3\lib\site-packages\osmnx\pois.py in pois_from_place(place, amenities)
    445     city = gdf_from_place(place)
    446     polygon = city['geometry'].iloc[0]
--> 447     return create_poi_gdf(polygon=polygon, amenities=amenities)

~\Anaconda3\lib\site-packages\osmnx\pois.py in create_poi_gdf(polygon, amenities, north, south, east, west)
    346 
    347     # Parse relations (MultiPolygons) from 'ways'
--> 348     gdf_ways = parse_osm_relations(relations=relations, osm_way_df=gdf_ways)
    349 
    350     # Combine GeoDataFrames

~\Anaconda3\lib\site-packages\osmnx\pois.py in parse_osm_relations(relations, osm_way_df)
    241     # Iterate over relations and extract the items
    242     for relation in relations:
--> 243         if relation['tags']['type'] == 'multipolygon':
    244             try:
    245                 # Parse member 'way' ids

KeyError: 'type'
```

With %debug, I find:
```python
> c:\users\xxx\anaconda3\lib\site-packages\osmnx\pois.py(243)parse_osm_relations()
    241     # Iterate over relations and extract the items
    242     for relation in relations:
--> 243         if relation['tags']['type'] == 'multipolygon':
    244             try:
    245                 # Parse member 'way' ids

ipdb> relation
{'type': 'relation', 'id': 1154069, 'members': [{'type': 'way', 'ref': 75171162, 'role': 'outer'}, {'type': 'way', 'ref': 75188210, 'role': 'inner'}], 'tags': {'amenity': 'hospital', 'building': 'yes', 'name': 'Hopital de jour agricole Bellevue'}}
ipdb> q
```

**Comment by gboeing** [comment]
@TRomijn The Netherlands includes oversees territories, so your query area ends up covering about 30 million square kilometers:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
%matplotlib inline

gdf = ox.gdf_from_place('The Netherlands')
geom = gdf['geometry'].iloc[0]
geom_proj, crs = ox.project_geometry(geom)
area = geom_proj.envelope.area / 1e6

print('{:,.0f} sq km'.format(area))
gdf.plot()
```

Due to the sheer geographic scale, something unsurprisingly chokes along the way. You might want to just query for hospitals in the mainland:

```python
mainland = max(geom, key=lambda x: x.area)
pois = ox.pois_from_polygon(mainland, amenities=['hospital'])
pois.shape
# returns (1155, 156)
```

**Comment by TRomijn** [comment]
Thanks a lot for taking time to figure it out! Great work.
