### ISSUE TITLE
Edges spanning location boundaries are not included (purposefully?)

### ISSUE THREAD

**Issue by scottishbee** [gboeing/osmnx#175]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Along the edge of a city, some blocks seem to get left off.  I'm pulling all roads in "San Francisco, CA".  The southern boundary of the city is fairly arbitrary, often splitting blocks, so I'd expect this split blocks to mainly be excluded.  But other blocks that go right up to the edge seem to also be lost.

Is pulling from a location defined as all edges that are exclusively within the location (ie the nodes are entirely within) or is there a broader definition where edges may split locations?

#### Code that reproduces the issue
An example block is Pope Street, between Polaris Way and Bellevue Avenue.  The southern intersection (Pope & Bellevue) is at the boundary between San Francisco and Daly City.  Clicking on that section of Pope Street in OpenStreetMap it is tagged "tiger:county" : "San Francisco, CA".

**Comment by gboeing** [comment]
You can currently do this when getting graph by point, address, and bounding box, using the truncate_by_edge argument. However this functionality is not currently implemented for place and polygon. See https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_place and https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.truncate_graph_polygon

**Comment by gboeing** [comment]
Also, you can buffer your query by say 100 meters to get peripheral edges.
