### ISSUE TITLE
How to use gdf_from_place like places as: Beijing,China or Shanghai, China?

### ISSUE THREAD

**Issue by Zhuifeng414** [gboeing/osmnx#176]
When I use the function : city = ox.gdf_from_place('Shanghai, China')
the error : ValueError: All geometries in GeoDataFrame must be shapely Polygons or MultiPolygons

I have check the website of Open Street Map
![image](https://user-images.githubusercontent.com/25602402/42140951-db99512c-7dd7-11e8-841f-1e47c8db42ec.png)
the first one is a point
the second one is the shapeloy polygons
the problem is that the demo will chose the first one, so the error happend.

How can i fixed this?
 
```python
city = ox.gdf_from_place('Shanghai, China')
city = ox.project_gdf(city)
fig, ax = ox.plot_shape(city, figsize=(3,3))
```

**Comment by Zhuifeng414** [comment]
I have solved it just now, use the demo as follow:
```python
place = { 'state' : 'Shanghai',
          'country' : 'China'}
city = ox.gdf_from_place(place)
city = ox.project_gdf(city)
fig, ax = ox.plot_shape(city, figsize=(3,3))
```

**Comment by gboeing** [comment]
This issue and its solution are discussed in several places elsewhere, but most notably the thread in #16
