### ISSUE TITLE
(Very) minor optimization 

### ISSUE THREAD

**Issue by subwayHareArmy** [gboeing/osmnx#177]
https://github.com/gboeing/osmnx/blob/0c62d727b0dc468c04b13ec5dcd390417cf28734/osmnx/core.py#L980

Should there be a break statement after this? Adding a break after it would still ensure that the variable 'any_neighbors_in_bbox' is set to True. There is no need of iterating through the rest of the 'neighbor's in 'neighbors'.

Please correct me if I haven't understood this completely. Also, should I have asked this on StackOverflow and not here?

**Comment by gboeing** [comment]
Would you like to open a PR and test it out?

**Comment by gboeing** [comment]
Closed for inactivity; can re-open with PR to test it out.
