### ISSUE TITLE
Bounding box limitation

### ISSUE THREAD

**Issue by zifeo** [gboeing/osmnx#179]
#### Problem description

When querying bounding boxes, the queries can be very slow depending on the size of the boxes.
Is there any limits involved? The difference of time between a 9x9km^2 box and 10x10km^2 seems to be exponential. Same is happening with a polygon approximately of the same size.

Is there other alternative for loading those data into OSMnx? I tried `graph_from_file` but it is again taking a very long time (for full Switzerland).

#### What operating system, architecture, Python version, and OSMnx version are you using?

Reproduced on latest macOS and Ubuntu 16.04 with python 3.5/3.6 (and latest OSMnx).  

#### Complete list of your environment's packages and their versions

Not relevant.

#### Code that reproduces the issue

```python
import osmnx as ox
g = ox.graph_from_bbox(5.920258, 46.089424, 6.346664, 46.339343)
```

**Comment by gboeing** [comment]
Can you supply both an example 9x9km^2 box and a 10x10km^2 box and I'll check the execution times? What are the execution times you're seeing?

**Comment by zifeo** [comment]
Thanks for getting back. It seems it was a local issue over the previous week. We are now able to retrieve 10x10km^2 with a correct and consistent time. Could you still give a bit of background on the fetching/downloading process in case it happens again (and we can try debugging)?

**Comment by baygaliyev** [comment]
Greetings, I have the same problem while trying to get a box from Pisa, Italy:
```
bbox = 10.3659, 43.7019, 10.4224, 43.7357
G = ox.graph_from_bbox(bbox=bbox, simplify=False, network_type="drive_service")
```

**Comment by gboeing** [comment]
@baygaliyev see the docs. You're providing the coordinates in the wrong order.  https://osmnx.readthedocs.io/en/stable/user-reference.html#osmnx.graph.graph_from_bbox

**Comment by baygaliyev** [comment]
Solved, thank you @gboeing !
