### ISSUE TITLE
Unable to import osmnx after having it installed with pip.

### ISSUE THREAD

**Issue by goggle** [gboeing/osmnx#180]
#### Problem description 
I've installed `osmnx` with pip in a fresh virtual environment as described in the README:
```
pip install geopandas
pip install rtree
pip install osmnx
```
All three commands ran successfully.
After this, I've opened a python console, and tried to import the `osmnx` module:
```
import osmnx as ox
```
I get the following error message:
```
>>> import osmnx as ox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/osmnx/osmnx/lib/python3.6/site-packages/osmnx/__init__.py", line 9, in <module>
    from .buildings import *
  File "/home/alex/osmnx/osmnx/lib/python3.6/site-packages/osmnx/buildings.py", line 9, in <module>
    import geopandas as gpd
  File "/home/alex/osmnx/osmnx/lib/python3.6/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/home/alex/osmnx/osmnx/lib/python3.6/site-packages/geopandas/geoseries.py", line 12, in <module>
    from geopandas.base import GeoPandasBase, _series_unary_op, _CoordinateIndexer
  File "/home/alex/osmnx/osmnx/lib/python3.6/site-packages/geopandas/base.py", line 14, in <module>
    from rtree.core import RTreeError
  File "/home/alex/osmnx/osmnx/lib/python3.6/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/alex/osmnx/osmnx/lib/python3.6/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/home/alex/osmnx/osmnx/lib/python3.6/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file
```

#### What operating system, architecture, Python version, and OSMnx version are you using?
Operating System: Arch Linux
Architecture: x86_64
Python version: 3.6.6
OSMnx version: 0.8.1

#### Output of `pip list`:
```
Package         Version    
--------------- -----------
certifi         2018.4.16  
chardet         3.0.4      
click           6.7        
click-plugins   1.0.3      
cligj           0.4.0      
cycler          0.10.0     
decorator       4.3.0      
descartes       1.1.0      
Fiona           1.7.12     
geopandas       0.3.0      
idna            2.7        
kiwisolver      1.0.1      
matplotlib      2.2.2      
munch           2.3.2      
networkx        2.1        
numpy           1.14.5     
osmnx           0.8.1      
pandas          0.23.3     
pip             10.0.1     
pyparsing       2.2.0      
pyproj          1.9.5.1    
python-dateutil 2.7.3      
pytz            2018.5     
requests        2.19.1     
Rtree           0.8.3      
setuptools      40.0.0     
Shapely         1.6.4.post1
six             1.11.0     
urllib3         1.23       
wheel           0.31.1     
```

#### Code that reproduces the issue

```
import osmnx as ox
```
after having it installed as I have...

**Comment by gboeing** [comment]
This is an rtree installation issue. The OSMnx readme suggests using conda and conda-forge to install the dependencies as rtree is more complicated than that. If you want to install everything with pip, read the additional instructions to get rtree's dependencies installed here: http://toblerity.org/rtree/install.html

**Comment by goggle** [comment]
Ok, after installing `spatialindex` (version 1.8.5, I hope this is not a problem, because in your linked document it is suggested to install version 1.7.0) through the package manager of my distribution, it seems to work, at least I don't get this error message anymore after importing `osmnx`.

This is my solution:
```
sudo pacman -S spatialindex
pip install geopandas
pip install rtree
pip install osmnx
```
The last three commands have been executed in a virtual environment using `virtualenv`.

Although I think it's enough to do
```
pip install osmnx
```
after having installed `spatialindex` on my system, since it seems that the dependencies are retrieved by default, right?

Maybe this should be mentioned in the `REDME.md`. Something like this:

## Installation with pip
Make sure to have geospatial installed on your system. Then run
```
pip install osmnx
```

**Comment by sssaha** [comment]
I am trying to install OSMNX through using conda, and executing the single command
`conda create -n syn --strict-channel-priority osmnx`
But while trying to run any code like `import osmnx` 
The error I get is `could not find or load rtree`
