### ISSUE TITLE
gdf_from_place() returns different list of results from requests.get() and browsr

### ISSUE THREAD

**Issue by puntofisso** [gboeing/osmnx#184]
Following up the discussion on #16 I seem to have found an example for which I get slightly different result when calling gdf_from_place(which_result=X) compared to calling the equivalent url via requests and via browser.

Using a **browser**, I pass 'City of London, UK' as its (urlencoded) counterpart 'City%20of%20London,%20UK', so the url I enter in the browser is:
[https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City%20of%20London,%20UK](https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City%20of%20London,%20UK)

The query returns the two results as stated above:

1. a POINT for osm_id 27365030
2. and a POLYGON for osm_id 51800.

If I use **requests**, regardless of using urlencoding or not, i.e. whether i call

`import requests url = 'https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City of London, UK' requests.get(url).text`

or

`url = 'https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City%20of%20London,%20UK'`

I get two result which are different from the in-browser ones:

1. a POINT for osm_id 27365030 which is the same as above
2. a different POLYGON in the second result, for osm_id 4001857 (instead of osm_id 51800 - although this is an acceptable result).

If I use **gdf_from_place**, I get something else entirely

1. `ox.gdf_from_place('City of London, UK',which_result=0)` -> returns POINT as above
2. `ox.gdf_from_place('City of London, UK',which_result=1)` -> returns the same POINT
3. `ox.gdf_from_place('City of London, UK',which_result=2)` -> returns the POLYGON for osm_id 4001857

So even if we discount browser behaviour, which is probably caused by the way the urlencoding engages with the http library, if we say that gdf_from_place() should work exactly as requests.get() then there is a discrepancy for the first two results. What would be a good place to understand where the discrepancy stems from?

If I'm not understanding how this is supposed to work, please feel free to say :) I'm just trying to make sure I get 100% how the queries are parsed.

**Comment by gboeing** [comment]
@puntofisso I just opened an issue in Nominatim's repo as it seems to be giving inconsistent results even when the request's user agent string is set to chrome. https://github.com/openstreetmap/Nominatim/issues/1104

**Comment by puntofisso** [comment]
That's grand. Thanks :)

**Comment by gboeing** [comment]
@puntofisso this should fix it:

```python
import requests
url = 'https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City%20of%20London,%20UK'
headers = {'Accept-Language':'en'}
r = requests.get(url, headers=headers)
```

I'll add to OSMnx master later today.

**Comment by gboeing** [comment]
@puntofisso could you test the latest commits to master for me? It should be working as expected now. 

```python
import osmnx as ox
gdf = ox.gdf_from_place('City of London, UK', which_result=2)
gdf.iloc[0]['place_name']
```

Returns: 'City of London, Greater London, England, United Kingdom'. Also, you can now configure your default language like this:

```python
import osmnx as ox
ox.config(default_accept_language='es')
gdf = ox.gdf_from_place('City of London, UK', which_result=2)
gdf.iloc[0]['place_name']
```

Returns: 'City de Londres, London, Greater London, Inglaterra, EC2V 5AE, Reino Unido'

**Comment by puntofisso** [comment]
Mmm. I'm not a massive python environment experts but let me try. The working version I have - bar this issue - was the one I installed via conda's pip. 

When I try installing the new master version after creating a virtualenv, if I import osmnx I get     

`raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file`

which I think points to #180? 

I've seen this error before while using a non-conda pip install, but I haven't managed to get Rtree functioning if not via conda, so I'm not entirely sure how to get to testing without waiting for the master version to go into pip. Any idea to workaround this are welcome, I'd be happy to help testing.

**Comment by puntofisso** [comment]
Thanks :)

It looks like it works and that I can reliably change its behaviour. Just to make sure it's what you expect: it looks like I need to select the language explicitly to to 'en' to get the same results I was getting from requests(). 

If I don't select the language, or I select different languages, I get different results for the same call. Some examples:

`ox.config(default_accept_language='en')
gdf = ox.gdf_from_place('City of London, UK', which_result=2)
gdf.iloc[0]['place_name']

'City of London, Greater London, England, United Kingdom'`

`ox.config(default_accept_language='es')
gdf = ox.gdf_from_place('City of London, UK', which_result=2)
gdf.iloc[0]['place_name']

'City de Londres, London, Greater London, Inglaterra, EC2V 5AE, Reino Unido'`

`import osmnx as ox
ox.config(default_accept_language='')
gdf = ox.gdf_from_place('City of London, UK', which_result=2)
gdf.iloc[0]['place_name']

'City of London, Gresham Street, Temple, London, Greater London, England, SE15, UK'`
(Note that this previous example returns the odd result which I originally reported.)

`ox.config(default_accept_language='fr')
gdf = ox.gdf_from_place('City of London, UK', which_result=2)
gdf.iloc[0]['place_name']

'City of London, Saint Botolph Street, London, Grand Londres, Angleterre, SE15, Royaume-Uni'`

So I think it works (I'm assuming nominatim is supposed to work this way?) 

I hope this helps and thanks once again for helping with this issue.

**Comment by gboeing** [comment]
Nominatim's default language is 'en', and it sorts importance scores slightly differently if different languages (or none) are provided.

OSMnx now by default provides 'en' as the accept-language. So if you just run

```python
import osmnx as ox
gdf = ox.gdf_from_place('City of London, UK', which_result=2)
gdf.iloc[0]['place_name']
```

It explicitly sends 'en' by default and receives the same results you see in your browser (as long as your browser's default language is set to 'en'). If you use `ox.config` to set a different accept_language, you'll see different results.
