### ISSUE TITLE
plot_buildings ignores bgcolor parameter for existing Figure, Axes

### ISSUE THREAD

**Issue by coolum001** [gboeing/osmnx#187]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Hi

I called `buildings.plot_buildings` with an existing `fig` and `ax`; I expected the background to be set to specified color via `bgcolor`, but the parameter was ignored.  It seems from reading the code that it is only used if a `fig` or `ax` paramers are not provided.

happy to run more tests or answer questions

Don

#### What operating system, architecture, Python version, and OSMnx version are you using?

Environment 9s 👍 
```
python version : 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:10:42) [MSC v.1900 64 bit (AMD64)]
python environment : root36
pandas version : 0.22.0
osmnx version: 0.8.1
current wkg dir: C:\Users\donrc\Documents\JupyterNotebooks\OSMNXNotebookProject\develop
Notebook name: osmnx issues
Notebook run at: 2018-07-24 12:23:35.576539 local time
Notebook run at: 2018-07-24 02:23:35.576539 UTC
Notebook run on: Windows-10-10.0.17134-SP0
```

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>

(root36) C:\Users\donrc>conda list
# packages in environment at D:\Anaconda3\envs\root36:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1
_nb_ext_conf              0.4.0                    py36_1
alabaster                 0.7.10                   py36_1    conda-forge
altair                    2.1.0                      py_0    conda-forge
altgraph                  0.14                       py_0    conda-forge
anaconda                  custom           py36h363777c_0
anaconda-clean            1.1.0                    py36_0
anaconda-client           1.6.14                     py_0    conda-forge
anaconda-navigator        1.8.7                    py36_0
anaconda-project          0.8.2                    py36_0    conda-forge
anyqt                     0.0.8                    py36_1    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
argcomplete               1.8.2                    py36_0    conda-forge
arrow                     0.10.0                     py_1    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
astroid                   1.4.8                    py36_0    conda-forge
astropy                   3.0                      py36_1    conda-forge
attrs                     18.1.0                     py_1    conda-forge
autopep8                  1.3.3                      py_0    conda-forge
babel                     2.5.1                    py36_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.4                      py36_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
basemap                   1.1.0                    py36_4    conda-forge
basemap-data-hires        1.0.8.dev0                    2    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
binaryornot               0.4.4                    py36_0    conda-forge
bitarray                  0.8.1                    py36_0    conda-forge
black                     18.6b2                     py_0    conda-forge
blas                      1.0                         mkl
blaze                     0.10.1                   py35_0
bleach                    2.0.0                    py36_0    conda-forge
blinker                   1.4                      py36_0    conda-forge
bokeh                     0.12.10                  py36_0    conda-forge
boost                     1.66.0              py36_vc14_1  [vc14]  conda-forge
boost-cpp                 1.66.0                   vc14_1  [vc14]  conda-forge
boto                      2.48.0           py36h1a776d2_1
bottlechest               0.7.1                    py36_0
bottleneck                1.2.1                    py36_1    conda-forge
branca                    0.2.0                      py_1    conda-forge
brewer2mpl                1.4.1                    py36_2    conda-forge
bz2file                   0.98                     py36_0
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cartopy                   0.16.0                   py36_0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
chest                     0.2.3                    py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cloudpickle               0.4.0                    py36_0    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
commonmark                0.7.3                    py36_0    conda-forge
comtypes                  1.1.3                    py36_0    conda-forge
configobj                 5.0.6                    py36_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5                    py36_0    conda-forge
cookiecutter              1.5.1                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
curl                      7.60.0                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.27.3                   py36_0    conda-forge
cytoolz                   0.8.2                    py36_0    conda-forge
dask                      0.15.4                     py_0    conda-forge
dask-core                 0.15.4                     py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
descartes                 1.1.0                    py36_0    conda-forge
dill                      0.2.6                    py36_0    conda-forge
distributed               1.19.3                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
dynd-python               removed                       0
entrypoints               0.2.3                    py36_1    conda-forge
et_xmlfile                1.0.1                    py36_0    conda-forge
expat                     2.2.5                    vc14_0  [vc14]  conda-forge
fastcache                 1.0.2                    py36_0    conda-forge
filelock                  2.0.6                    py36_0    conda-forge
fiona                     1.7.12                   py36_0    conda-forge
flask                     0.12.2                   py36_0    conda-forge
flask-cors                3.0.3                    py36_0    conda-forge
folium                    0.5.0                      py_0    conda-forge
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
freexl                    1.0.2                    vc14_1  [vc14]  conda-forge
future                    0.16.0                   py36_0    conda-forge
gdal                      2.2.3                    py36_0    conda-forge
gensim                    3.1.0               py36_vc14_0  [vc14]  conda-forge
geopandas                 0.4.0                      py_0    conda-forge
geopy                     1.11.0                   py36_0    conda-forge
geos                      3.6.2                he025d50_2    conda-forge
geotiff                   1.4.2                    vc14_1  [vc14]  conda-forge
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2                    py36_0    conda-forge
graphviz                  2.38.0                        7    conda-forge
greenlet                  0.4.12                   py36_0    conda-forge
h5py                      2.6.0               np111py35_2
hdf4                      4.2.12                   vc14_0  [vc14]  conda-forge
hdf5                      1.10.1                   vc14_2  [vc14]  conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
humanize                  0.5.1                    py36_0    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.5                      py36_0    conda-forge
imageio                   2.2.0                    py36_0    conda-forge
imagesize                 0.7.1                    py36_0    conda-forge
inflection                0.3.1                    py36_0
inkscape                  0.91                          0    conda-forge
intel-openmp              2018.0.0             hcd89f80_7
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.0.5                    py36_0    conda-forge
isort                     4.2.15                   py36_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jdcal                     1.3                      py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jinja2-time               0.2.0                    py36_1    conda-forge
joblib                    0.11                     py36_0    conda-forge
jpeg                      9b                       vc14_0  [vc14]  conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter                   1.0.0                    py35_3
jupyter_client            5.2.2                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_contrib_core      0.3.3                    py36_1    conda-forge
jupyter_contrib_nbextensions 0.4.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.1.0                    py36_0    conda-forge
jupyter_latex_envs        1.4.4                    py36_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py36_0    conda-forge
jupyterlab                0.32.1                   py36_0    conda-forge
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
kealib                    1.4.7                    vc14_4  [vc14]  conda-forge
keyring                   9.0                      py36_0    conda-forge
keyrings.alt              1.2                      py36_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.14.6                   vc14_0  [vc14]  conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libcurl                   7.60.0               hc4dcbb0_0
libdynd                   0.7.2                         0
libflang                  5.0.0             vc14_20180208  [vc14]  conda-forge
libgdal                   2.2.3                    vc14_3  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libnetcdf                 4.4.1.1                 vc14_10  [vc14]  conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libpq                     9.5.4                    vc14_3  [vc14]  conda-forge
libspatialindex           1.8.5                    vc14_1  [vc14]  conda-forge
libspatialite             4.3.0a                  vc14_19  [vc14]  conda-forge
libssh2                   1.8.0                    vc14_2  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.3                    vc14_9  [vc14]  conda-forge
libxslt                   1.1.29                   vc14_5  [vc14]  conda-forge
llvm-meta                 5.0.0                         0    conda-forge
llvmlite                  0.21.0                   py36_0    conda-forge
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.1.1                    py36_0    conda-forge
macholib                  1.8                        py_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
menuinst                  1.4.10           py36h42196fb_0
mistune                   0.8                      py36_0    conda-forge
mkl                       2018.0.0             h36b65af_4
mkl-service               1.1.2            py36h57e144c_4
more-itertools            3.2.0                    py36_0    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.4.8                    py36_0    conda-forge
multipledispatch          0.4.9                    py36_0    conda-forge
munch                     2.2.0                    py36_0    conda-forge
nb_anacondacloud          1.4.0                    py36_0    conda-forge
nb_conda                  2.2.1                    py36_0    conda-forge
nb_conda_kernels          2.1.0                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
nbpresent                 3.0.2                    py36_0
networkx                  2.1                        py_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.4.0                    py36_0    conda-forge
numba                     0.36.2          np114py36h12cb543_0
numexpr                   2.6.4                    py36_0    conda-forge
numpy                     1.14.2           py36h5c71026_0
oauthlib                  2.0.6                      py_0    conda-forge
odo                       0.5.1                    py36_0    conda-forge
olefile                   0.44                     py36_0    conda-forge
openblas                  0.2.20                   vc14_7  [vc14]  conda-forge
openjpeg                  2.3.0                    vc14_2  [vc14]  conda-forge
openmp                    5.0.0                    vc14_1  [vc14]  conda-forge
openpyxl                  2.5.0b1                  py36_0    conda-forge
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
orange3                   3.7.0                    py36_0    conda-forge
osmnx                     0.8.1                      py_0    conda-forge
owslib                    0.16.0                     py_0    conda-forge
pandas                    0.22.0                   py36_0    conda-forge
pandoc                    2.0.0.1                       1    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
path.py                   10.3.1                   py36_0    conda-forge
pathlib2                  2.3.0                    py36_0    conda-forge
patsy                     0.4.1                    py36_0    conda-forge
pcre                      8.39                     vc14_0  [vc14]  conda-forge
pefile                    2017.9.3                   py_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    5.2.0                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pkginfo                   1.4.1                    py36_0    conda-forge
ply                       3.10                     py36_0    conda-forge
poyo                      0.4.1                    py36_0    conda-forge
proj4                     4.9.3                    vc14_2  [vc14]  conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.0                    py36_0    conda-forge
psycopg2                  2.7.3.2                  py36_0    conda-forge
py                        1.5.2                      py_0    conda-forge
pyasn1                    0.3.7                      py_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pycurl                    7.43.0.2         py36h74b6da3_0
pyepsg                    0.3.2                    py36_0    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyinstaller               3.3                 py36_vc14_1  [vc14]  conda-forge
pyjwt                     1.5.3                      py_0    conda-forge
pylint                    1.6.5                    py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pyqtgraph                 0.10.0                   py36_2    conda-forge
pyreadline                2.1              py36h094d952_1
pysal                     1.14.3                   py36_0    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pytables                  3.2.2               np111py35_4
pytest                    3.2.5                    py36_0    conda-forge
pytest-arraydiff          0.2                        py_0    conda-forge
pytest-astropy            0.2.1                      py_0    conda-forge
pytest-doctestplus        0.1.2                      py_0    conda-forge
pytest-openfiles          0.2.0                      py_0    conda-forge
pytest-remotedata         0.2.0                      py_0    conda-forge
python                    3.6.3                         1    conda-forge
python-crfsuite           0.9.2               py36_vc14_0  [vc14]  conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
python-docx               0.8.6                    py36_1    conda-forge
python-graphviz           0.8.2                    py36_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
pywavelets                0.5.2                    py36_1    conda-forge
pywin32                   220                      py36_1    conda-forge
pywinpty                  0.5                      py36_1    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtpy                      1.4.2            py36h8a2030e_0    conda-forge
quandl                    3.2.0            py36h30f7a5e_0
requests                  2.17.3                   py36_0    conda-forge
requests-oauthlib         0.8.0                    py36_1    conda-forge
rope                      0.10.7                   py36_0    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
scikit-image              0.13.0                   py36_1    conda-forge
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.0.0            py36h1260518_0
seaborn                   0.8.1                    py36_0    conda-forge
selenium                  3.12.0                   py36_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
serverfiles               0.2.1                      py_0    conda-forge
setuptools                36.6.0                   py36_1    conda-forge
shapely                   1.6.4            py36hc90234e_1    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
singledispatch            3.4.0.3                  py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
smart_open                1.5.3                    py36_0    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sockjs-tornado            1.0.3                    py36_0
sortedcontainers          1.5.7                    py36_0    conda-forge
sphinx                    1.6.5                    py36_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.20.1                   vc14_2  [vc14]  conda-forge
statsmodels               0.8.0                    py36_0    conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
textblob                  0.15.0                     py_0    conda-forge
tk                        8.6.6                    vc14_5  [vc14]  conda-forge
toml                      0.9.4                      py_0    conda-forge
toolz                     0.8.2                      py_2    conda-forge
tornado                   4.5.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
tweepy                    3.5.0                    py36_0    conda-forge
twython                   3.6.0                    py36_0    conda-forge
typing                    3.6.2                    py36_0    conda-forge
unicodecsv                0.14.1                   py36_0    conda-forge
urllib3                   1.21.1                   py36_1    conda-forge
vc                        14                            0    conda-forge
vega                      0.4.4                    py36_1    conda-forge
vega_datasets             0.5.0                      py_0    conda-forge
vincent                   0.4.4                    py36_0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.12.2                     py_1    conda-forge
wheel                     0.30.0                     py_1    conda-forge
whichcraft                0.4.1                    py36_0    conda-forge
widgetsnbextension        3.0.8                    py36_0    conda-forge
win_inet_pton             1.0.1                    py36_1    conda-forge
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2                      py36_0    conda-forge
winpty                    0.4.3                    vc14_2  [vc14]  conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
wxpython                  4.0.3            py36h6538335_1    conda-forge
wxPython                  4.0.0b1                   <pip>
xerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge
xlrd                      1.0.0                    py36_1    conda-forge
xlsxwriter                1.0.2                      py_0    conda-forge
xlwings                   0.11.4                   py36_0    conda-forge
xlwt                      1.3.0                    py36_0    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                    vc14_0  [vc14]  conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

</details>

#### Code that reproduces the issue

```python
fig, ax = plt.subplots(1, 1, figsize=(10,10) )
bb=ox.buildings.create_buildings_gdf(north=-26.526, south=-26.538, west=153.085, east=153.095)
ox.buildings.plot_buildings(bb, fig=fig, ax=ax, bgcolor='black', color='red', )
plt.show()
```

this gives me:

![bug1](https://user-images.githubusercontent.com/23631696/43115218-509e998a-8f46-11e8-9c9f-a1c64e6f9324.png)

```
ox.buildings.plot_buildings(bb,  bgcolor='red', color='black', )
```
give me as expected:

![bug2](https://user-images.githubusercontent.com/23631696/43115237-669c194c-8f46-11e8-8c9c-f21777e4520d.png)

**Comment by gboeing** [comment]
If you're creating your own figure and axes, just set the background color when you do so.

```python
fig, ax = plt.subplots(1, 1, figsize=(10,10), facecolor='r')
ox.plot_buildings(bb, fig=fig, ax=ax, color='k')
plt.show()
```
