### ISSUE TITLE
PolarAxesSubplot' object has no attribute 'flat

### ISSUE THREAD

**Issue by rs06085** [gboeing/osmnx#192]
I am trying to run an example I found on this repo: osmnx-examples

The issue is with matplotlib

# create figure and axes
n = len(places)
ncols = int(np.ceil(np.sqrt(n)))
nrows = int(np.ceil(n / ncols))
figsize = (ncols * 5, nrows * 5)
fig, axes = plt.subplots(nrows, ncols, figsize=figsize, subplot_kw={'projection':'polar'})

# plot each city's polar histogram
for ax, place in zip(axes.flat, sorted(places.keys())):
    polar_plot(ax, bearings[place].dropna(), title=place)

when I run this code, I receive the following error:
AttributeError: 'PolarAxesSubplot' object has no attribute 'flat'

I use Python 3.6

Thanks in advance!

**Comment by gboeing** [comment]
Can you provide a complete minimal working example for me to run? It would appear that you are not creating multiple subplots, but you are trying to flatten as though you were.
