### ISSUE TITLE
Detect turns in a road

### ISSUE THREAD

**Issue by tarikd** [gboeing/osmnx#193]
I'm really sorry to post this request as an issue but it's not meeting the requirement to be posted on stackoverflow.

I would like to be able to locate where are the turns in a specific road and I was wondering if OSMNX is able to help me with this task.

Thank you for your answers!

**Comment by gboeing** [comment]
Like where a road curves, mid-block? Here's a general gist. Construct the graph (with simplify=False), then add edge bearings. Then you can do something like find all the edges where osmid=12345 and compare their bearings. If adjacent edges have bearings that differ by say more than 5 degrees, then you  can say the road curves there.

Alternatively, simplify the graph when you construct it. Then pull an edge for the road of interest. Its geometry is a LineString, with the points of the line string constituting vertices (essentially directional changes).
