### ISSUE TITLE
osmnx tries to show images even when show = False

### ISSUE THREAD

**Issue by Robinlovelace** [gboeing/osmnx#194]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

Reproducible example from the README:

```python
ox.plot_graph(ox.project_graph(G), filename = "plot.png", show = False, save = True, close = True)
```

I expected it to create `plot.png` and do nothing else. Instead it tried to show an image and crashed the terminal (I'm running in an environment where it cannot show images).

#### What operating system, architecture, Python version, and OSMnx version are you using?

```bash
conda --version
# conda 4.5.9
conda list osm
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
# osmnx                     0.8.1                      py_0    conda-forge
python --version
# Python 3.6.5 :: Anaconda, Inc.
```

<details>
conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0
blas                      1.0                         mkl
branca                    0.3.0                      py_0    conda-forge
bzip2                     1.0.6                h14c3975_5
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.12              h8948797_3
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36h9745a5d_0
chardet                   3.0.4            py36h0f667ec_1
click                     6.7              py36h5253387_0

</details>

#### Code that reproduces the issue

```python
ox.plot_graph(ox.project_graph(G), filename = "plot.png", show = False, save = True, close = True)
```

**Comment by gboeing** [comment]
I just tested this now in both a Jupyter notebook and a terminal window, and it worked properly. The image file was saved to disk and nothing was displayed.

For reference, here's a complete minimal working example:

```python
import osmnx as ox
ox.config(use_cache=True)
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
fig, ax = ox.plot_graph(ox.project_graph(G), filename = "plot.png", show=False, save=True, close=True)
```

If your environment cannot show images, you should configure matplotlib as usual to use a different back-end (this should be the first two lines in your script):

```python
import matplotlib as mpl
mpl.use('Agg')
```

**Comment by Robinlovelace** [comment]
The second solution solved it. Many thanks!

**Comment by Robinlovelace** [comment]
More context, in case it's of use/interest to others:

I'm running osmnx in a docker container I'm developing to help teach an MSc module in Transport Data Science next year: https://hub.docker.com/r/robinlovelace/tds/

I'm building on code (mostly in Python) and writing by @charles-fox linked his book Transport Data Science. As you'll see I cited your osmnx in the module catalogue: https://github.com/Robinlovelace/TDS/blob/master/catalogue.md - any suggestions of further (perhaps even more up-to-date) reading material linked to this, especially linked to the use of osmnx/similar for building an evidence-base for sustainable transport policies?

Any suggestions either on the teaching or the tech (do you know of osmnx used in minimal containers? mine is a little large at 8 GB!) very welcome.

Below is a gratuitous gif of it working in RStudio server (that was causing the crash):

![peek 2018-08-02 09-06](https://user-images.githubusercontent.com/1825120/43570979-a41791c2-9633-11e8-9edd-f3e11bc884c1.gif)

Final question: any suggestions about IDEs that work well with Python workflows involving osmnx? As you may have guessed I'm quite new to the language.

Sorry for all the questions, don't feel obliged to answer them.

**Comment by gboeing** [comment]
Some more OSMnx literature is listed in the middle of this page: https://geoffboeing.com/2018/03/osmnx-features-roundup/

Regarding IDEs, I recommend using a Jupyter notebook.

**Comment by bluelancer** [comment]
I can confirm the case when using matplotlib 3.3.4 and osmnx 1.0.1

fig_drive_STH, ax_drive_STH = ox.plot_graph(ox.project_graph(G_drive_STH), filepath = "plot.png", save=False, show=False, close=False,node_size=4) still plot the figure in notebook in my case.

**Comment by gboeing** [comment]
@bluelancer use a parameterization like `show=False, save=True, close=True` if you don't want to see the figure inline in your Jupyter notebook. You have to close it. In your example you set `close=False` so the notebook will try to show it even if you don't call `plt.show()` under the hood.
