### ISSUE TITLE
Issues with numpy.histogram?

### ISSUE THREAD

**Issue by puntofisso** [gboeing/osmnx#196]
This isn't quite an osmnx issue, but I thought I'd add it here, as it may help shed some light in case others have the same problems. 

I've just re-run the sample notebook that creates the street network polar visualizations, and got the following error (the same happens if I provide different locations):

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-c59ecd43a7f0> in <module>()
      9 # plot each city's polar histogram
     10 for ax, place in zip(axes, sorted(places.keys())):
---> 11     polar_plot(ax, bearings[place], title=place)
     12 
     13 # add super title and save full image

<ipython-input-5-3f02bf8f385b> in polar_plot(ax, bearings, n, title)
      3 
      4     bins = [ang * 360 / n for ang in range(0, n + 1)]
----> 5     count = count_and_merge(n, bearings)
      6     _, division = np.histogram(bearings, bins=bins)
      7     frequency = count / count.sum()

<ipython-input-6-c7da03125f04> in count_and_merge(n, bearings)
      4     n = n * 2
      5     bins = [ang * 360 / n for ang in range(0, n + 1)]
----> 6     count, _ = np.histogram(bearings, bins=bins)
      7 
      8     # move the last bin to the front, so eg 0.01° and 359.99° will be binned together

~/anaconda3/envs/OSMNX/lib/python3.6/site-packages/numpy/lib/function_base.py in histogram(a, bins, range, normed, weights, density)
    668     if not np.all(np.isfinite([first_edge, last_edge])):
    669         raise ValueError(
--> 670             'range parameter must be finite.')
    671     if first_edge == last_edge:
    672         first_edge -= 0.5

ValueError: range parameter must be finite.
```

Error "range parameter must be finite" is triggered any time am invalid range is passed to np.histogram(), say a range that contains NaN (or other errors). If range is omitted, as it is in the notebook, the [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html) suggests it should default to the range of the passed array, in this case to (bearings.min(), bearings.max()). I've amended the the code to pass range=(bearings.min(), bearings.max()) explicitly, and it works. 

Have there been undocumented changes in numpy that may create this issue?

NOTE: I run this notebook in a conda environment I created specifically for this, which worked perfectly the last time I run it (e.g. https://twitter.com/puntofisso/status/1020028000530845696), so I feel this is definitely related to some changes in the underlying library.

Running `pip list` in the notebook I get:
appnope (0.1.0)
asn1crypto (0.24.0)
backcall (0.1.0)
beautifulsoup4 (4.6.1)
boto (2.49.0)
boto3 (1.7.59)
botocore (1.10.59)
branca (0.3.0)
bz2file (0.98)
certifi (2018.4.16)
cffi (1.11.5)
chardet (3.0.4)
click (6.7)
click-plugins (1.0.3)
cligj (0.4.0)
cryptography (2.2.1)
cycler (0.10.0)
decorator (4.3.0)
descartes (1.1.0)
docutils (0.14)
Fiona (1.7.13)
folium (0.3.0)
GDAL (2.2.4)
gensim (3.5.0)
geographiclib (1.49)
geopandas (0.4.0)
geopy (1.15.0)
idna (2.7)
ipykernel (4.8.2)
ipython (6.4.0)
ipython-genutils (0.2.0)
jedi (0.12.0)
Jinja2 (2.10)
jmespath (0.9.3)
jupyter-client (5.2.3)
jupyter-core (4.4.0)
kiwisolver (1.0.1)
lxml (4.2.4)
MarkupSafe (1.0)
matplotlib (2.2.2)
munch (2.3.2)
networkx (2.1)
numpy (1.14.5)
osmnx (0.8.1)
pandas (0.23.3)
parso (0.2.1)
pexpect (4.6.0)
pickleshare (0.7.4)
pip (9.0.3)
prompt-toolkit (1.0.15)
psycopg2 (2.7.5)
ptyprocess (0.6.0)
pycparser (2.18)
Pygments (2.2.0)
pyOpenSSL (18.0.0)
pyparsing (2.2.0)
pyproj (1.9.5.1)
PySAL (1.14.3)
PySocks (1.6.8)
python-dateutil (2.7.3)
pytz (2018.5)
pyzmq (17.0.0)
requests (2.19.1)
Rtree (0.8.3)
s3transfer (0.1.13)
scipy (0.19.1)
setuptools (40.0.0)
Shapely (1.6.4.post2)
simplegeneric (0.8.1)
six (1.11.0)
smart-open (1.6.0)
SQLAlchemy (1.2.10)
tornado (5.1)
traitlets (4.3.2)
urllib3 (1.23)
vincent (0.4.4)
wcwidth (0.1.7)
wheel (0.31.1)
wikipedia (1.4.0)
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

While `conda list` returns
(OSMNX) bash-3.2$ conda list
# packages in environment at /Users/puntofisso/anaconda3/envs/OSMNX:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0            py36hf537a9a_0
asn1crypto                0.24.0                     py_1    conda-forge
backcall                  0.1.0                    py36_0
beautifulsoup4            4.6.1                     <pip>
blas                      1.0                         mkl
boost                     1.67.0           py36h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
boto                      2.49.0                    <pip>
boto3                     1.7.59                    <pip>
botocore                  1.10.59                   <pip>
branca                    0.3.0                      py_0    conda-forge
bz2file                   0.98                      <pip>
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.03.07                    0
cairo                     1.14.12              he56eebe_1    conda-forge
certifi                   2018.4.16                py36_0
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_2    conda-forge
click                     6.7                        py_1    conda-forge
click-plugins             1.0.3                      py_1    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cryptography              2.2.1            py36hdffb7b8_1    conda-forge
curl                      7.60.0               h93b3f91_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_1    conda-forge
docutils                  0.14                      <pip>
expat                     2.2.5                hfc679d8_1    conda-forge
Fiona                     1.7.13                    <pip>
fiona                     1.7.12                   py36_0    conda-forge
folium                    0.3.0                    py36_0    conda-forge
fontconfig                2.13.0               h074f895_2    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.5                hf837533_1    conda-forge
gdal                      2.2.4                    py36_0    conda-forge
gensim                    3.5.0                     <pip>
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.4.0                      py_0    conda-forge
geopy                     1.15.0                     py_0    conda-forge
geos                      3.6.2                hfc679d8_2    conda-forge
geotiff                   1.4.2                hb54a4aa_2    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.55.0                        0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.2               hc401514_1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py36_2    conda-forge
intel-openmp              2018.0.3                      0
ipykernel                 4.8.2                    py36_0
ipython                   6.4.0                    py36_1
ipython_genutils          0.2.0            py36h241746c_0
jedi                      0.12.0                   py36_1
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                     <pip>
jpeg                      9c                   h470a237_0    conda-forge
json-c                    0.12.1                        0    conda-forge
jupyter_client            5.2.3                    py36_0
jupyter_core              4.4.0                    py36_0
kealib                    1.4.9                h0bee7d0_2    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.14.6                        0    conda-forge
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libdap4                   3.19.1                        0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.2.4                ha6e4b24_6    conda-forge
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.15                 h470a237_1    conda-forge
libkml                    1.3.0                hfce3912_7    conda-forge
libnetcdf                 4.6.1                h5e45101_3    conda-forge
libpng                    1.6.34               ha92aebf_1    conda-forge
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.16               h3efe00b_0
libspatialindex           1.8.5                hfc679d8_2    conda-forge
libspatialite             4.3.0a                       19    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
lxml                      4.2.4                     <pip>
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mkl                       2017.0.4             h1fae6ae_0
munch                     2.3.2                      py_0    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  2.1                        py_1    conda-forge
numpy                     1.14.5                    <pip>
numpy                     1.13.1                   py36_0
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                h316dc23_3    conda-forge
openssl                   1.0.2o               h26aff7b_0
osmnx                     0.8.1                     <pip>
osmnx                     0.8.1                      py_0    conda-forge
pandas                    0.23.3                   py36_0    conda-forge
parso                     0.2.1                    py36_0
pcre                      8.41                          1    conda-forge
pexpect                   4.6.0                    py36_0
pickleshare               0.7.4            py36hf512f8e_0
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
poppler                   0.61.1                        3    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15           py36haeda067_0
psycopg2                  2.7.5                    py36_0    conda-forge
ptyprocess                0.6.0                    py36_0
pycparser                 2.18                       py_1    conda-forge
pygments                  2.2.0            py36h240cd3f_0
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pysal                     1.14.3                   py36_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pyzmq                     17.0.0           py36h1de35cc_3
readline                  7.0                           0    conda-forge
requests                  2.19.1                   py36_1    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
s3transfer                0.1.13                    <pip>
scipy                     0.19.1              np113py36_0
setuptools                40.0.0                   py36_0    conda-forge
Shapely                   1.6.4.post2               <pip>
shapely                   1.6.4            py36h164cb2d_1    conda-forge
simplegeneric             0.8.1                    py36_2
six                       1.11.0                   py36_1    conda-forge
smart-open                1.6.0                     <pip>
sqlalchemy                1.2.10                   py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.1                      py36_0    conda-forge
traitlets                 4.3.2            py36h65bd3ce_0
urllib3                   1.23                     py36_0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.7            py36h8c6ec74_0
wheel                     0.31.1                   py36_0    conda-forge
wikipedia                 1.4.0                     <pip>
xerces-c                  3.2.0                         0    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.2.5                h0a44026_0
zlib                      1.2.11               h470a237_3    conda-forge

**Comment by gboeing** [comment]
Might be related to #183. Try to drop NaNs or use the latest master branch of OSMnx and see if that fixes it.

**Comment by puntofisso** [comment]
Thanks @gboeing. The numpy versions are different, but that said it doesn't look to me it's a real probelm with -infs or NaNs because if it so were, it would manifest itself even when I do

`np.histogram(bearings, bins=bins, range=(bearings.min(), bearings.max()))`.

Note that calling
`np.histogram(bearings, bins=bins)` 
is, per documentation, equivalent to calling
`np.histogram(bearings, bins=bins, range=(bearings.min(), bearings.max()))`

but the former fails and the latter doesn't. Doesn't that suggest an issue with numpy (or a potential version-related difference in behaviour) rather than OSMnx itself?

**Comment by gboeing** [comment]
Ah I see. Sorry I should have read that line you wrote more carefully. Indeed it looks like something may have changed in numpy if calling `histogram` without a range argument no longer corresponds to what their documentation says should be the default behavior. Perhaps best to open an issue at numpy to see why this inconsistency exists? (Closing this here now, accordingly, but can reopen if we need to change something on the OSMnx side in the end.)

**Comment by puntofisso** [comment]
Indeed :) Just wanted to leave it here for the record, in case anyone else has similar issues.

**Comment by gboeing** [comment]
@puntofisso thank you!
