### ISSUE TITLE
Error when running pip install osmnx

### ISSUE THREAD

**Issue by jafetmorales** [gboeing/osmnx#197]
This is the output when running <code>pip install osmnx</code>
```
Collecting osmnx
  Using cached https://files.pythonhosted.org/packages/c7/ab/29f315dbbbca2e66dd60486ac130af19826a175ddb15e823695a4e9cb68a/osmnx-0.8.1-py2.py3-none-any.whl
Collecting descartes>=1.1 (from osmnx)
  Downloading https://files.pythonhosted.org/packages/e5/b6/1ed2eb03989ae574584664985367ba70cd9cf8b32ee8cad0e8aaeac819f3/descartes-1.1.0-py3-none-any.whl
Collecting Rtree>=0.8.3 (from osmnx)
  Downloading https://files.pythonhosted.org/packages/33/0d/0bcb0fdd759570e85697189f675fa462131e5636482f2832288bbe4bb6f7/Rtree-0.8.3-py3-none-any.whl
Collecting Shapely>=1.6 (from osmnx)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-2cf8et3b\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-2cf8et3b\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\ctypes\__init__.py", line 347, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jmorales\AppData\Local\Temp\pip-install-2cf8et3b\Shapely\
```
This is my setup:
>Python version: 3.5
>OS: Windows 10 Home
>System Type: 64-bit Operating System, x64-based processor
>Processor: AMD A10-8700P Radeon R6

**Comment by gboeing** [comment]
You should either install rtree according to its [installation instructions](http://toblerity.org/rtree/install.html) or install OSMnx with conda per the documentation: https://osmnx.readthedocs.io/en/stable/#installation

**Comment by jafetmorales** [comment]
Thank you for your suggestion, but I was only trying to verify whether the pip installation as suggested by the docs worked, as this would make it easier and faster to deploy for users who have not installed conda.

**Comment by gboeing** [comment]
pip works, but with the caveat that pip installation is always going to be entirely dependent on the individual system on which the installation occurs, plus whether upstream package developers have their build recipes fully supported for your individual system's configuration. Bottom line: if you have the dependencies installed, it's easy to pip install OSMnx as it is pure python.
