### ISSUE TITLE
Feature Enhancement: List street names for intersections

### ISSUE THREAD

**Issue by jpark11** [gboeing/osmnx#199]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

I am looking for street information for the clean intersections that are produced by osmnx. I see that I can print lat/lon information, but is there a way to include street/road names as well? I don't see how to do this in the documentation. Thanks!

#### What operating system, architecture, Python version, and OSMnx version are you using?

I am using osmnx version 0.8.1.

**Comment by gboeing** [comment]
Currently, OSMnx does intersection cleaning by merging "geometries" (ie, multiple intersection points) into one, but it ignores topology (ie, the actual connections between intersections and streets). So the cleaned intersection objects do not retain data about what street segments they connect to.

**Comment by gboeing** [comment]
One workaround is to find the network node nearest to each cleaned intersection point and find the streets at this intersection.

```python
import networkx as nx
import osmnx as ox
import geopandas as gpd
ox.config(log_console=True, use_cache=True)

G = ox.graph_from_place('Piedmont, California', network_type='drive')
G = ox.project_graph(G)
ints = ox.clean_intersections(G)

gdf = gpd.GeoDataFrame(ints, columns=['geometry'], crs=G.graph['crs'])
X = gdf['geometry'].map(lambda pt: pt.coords[0][0])
Y = gdf['geometry'].map(lambda pt: pt.coords[0][1])

nodes = ox.get_nearest_nodes(G, X, Y, method='kdtree')
connections = {}

for n in nodes:
    connections[n] = set([])
    for nbr in nx.neighbors(G, n):
        for d in G.get_edge_data(n, nbr).values():
            if 'name' in d:
                if type(d['name']) == str:
                    connections[n].add(d['name'])
                elif type(d['name']) == list:
                    for name in d['name']:
                        connections[n].add(name)
                else:
                    connections[n].add(None)
            else:
                connections[n].add(None)
                
print(connections)
```

**Comment by jpark11** [comment]
awesome -- this is great. thanks!
