### ISSUE TITLE
Import Error: Can't get past "import osmnx" line although everything is installed.

### ISSUE THREAD

**Issue by MikeDM16** [gboeing/osmnx#201]
I'm having difficulties regarding the installation of OSMnx package. 

In order to install OSMnx I follow the steps for installing using Anaconda. 
Although every package dependency seems to installed and solved, I can't use the OSMnx package nor find a traceback to an error or fault.  

I'm simpling trying to follow the code example provided in the git README and the program simply stops and exit after the "import osmnx as ox" line. 
When I compile my file, it just "returns" after trying to make the import, but no errors are displayed. 

I tried to create an environment for OSMnx following the instruction below. 
But again, when trying to print the osmnx version. my bash simply do nothing. 
```
conda create --yes -c conda-forge -n OSMNX python=3.6 osmnx
source activate OSMNX
python -c 'import osmnx; print(osmnx.__version__)'
0.2.1
```

Also, i tried to run python directly from the bash environment and using the python debugger (pdb) and i always can't get past the "import osmnx" line. 

#### What operating system, architecture, Python version, and OSMnx version are you using?
Windows 10 x64 
Python 3.6.5
OSMnx 0.8.1

#### Complete list of my environment's packages and their versions running `conda list`
[conda_list.txt](https://github.com/gboeing/osmnx/files/2386647/conda_list.txt)

Any help or suggestion would be thankful.

**Comment by gboeing** [comment]
@MikeDM16 if you installed via conda, best to open an installation issue at https://github.com/conda-forge/osmnx-feedstock as this doesn't appear to be related to the OSMnx codebase itself.
