### ISSUE TITLE
Getting only street level

### ISSUE THREAD

**Issue by bcoghe** [gboeing/osmnx#202]
I'm trying to use osmnx to find the shortest route matrix between points all over the netherlands. The problem is that the graph for the netherlands is too big to load in (it seems). Is there a way to reduce size by only getting streets f.e.? How?

When using graph_from_place or graph_from_file, the error was "segmentation failed (core dumped)

Might there be another solution? I would need the shortest routes from 2000 points to each other point but would like to have the highway tags. Which other tools don't provide.

**Comment by gboeing** [comment]
You can do something like this to get only certain levels of the road network hierarchy: https://stackoverflow.com/questions/52231122/python-osmnx-extract-only-big-freeways-of-a-country/52412274

**Comment by bcoghe** [comment]
But then you can't search the shortest route? It returns a geopandas object instead of the multidigraph?

**Comment by gboeing** [comment]
@bcoghe is this issue ready to be closed?
