### ISSUE TITLE
RunTime Error - Cannot run the code at all

### ISSUE THREAD

**Issue by KayleeZhu** [gboeing/osmnx#203]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
I am totally new to python, osm and coding stuff. I got Runtime Error after I ran the code, and I even did not know which step has an issue. Here was what I did:
I saw your paper online and want to use your code to get a graph (includes edges and nodes) like this.
![image](https://user-images.githubusercontent.com/43792717/46499801-4f2fcd00-c7de-11e8-9c16-38aa9bdedc6f.png)
As I am a very beginner, I followed the instruction step by step from this link. https://geoffboeing.com/2017/02/python-getting-started/
I think I did not have any problem with installation.
After I opened the jupyter notebook, I tried to run some code to see what would happen. The code I used was all from your example or from your paper. 
** This was my code and the corresponding error:
![image](https://user-images.githubusercontent.com/43792717/46500216-894d9e80-c7df-11e8-9250-c8949aa816e3.png)
![image](https://user-images.githubusercontent.com/43792717/46500224-8ce12580-c7df-11e8-942b-7d664118a588.png)

#### What operating system, architecture, Python version, and OSMnx version are you using?
I'm running on Windows10, python version is 3.6
OSMnx version is "0.8.2" if I understand the code correctly.
![image](https://user-images.githubusercontent.com/43792717/46500615-7a1b2080-c7e0-11e8-96dd-34851ae08e8f.png)

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
C:\Users\Kaylee>conda list
# packages in environment at C:\Users\Kaylee\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0
alabaster                 0.7.11                     py_3    conda-forge
altair                    2.2.2                    py36_1    conda-forge
anaconda                  custom           py36h363777c_0
anaconda-client           1.7.1                      py_0    conda-forge
anaconda-navigator        1.9.2                    py36_0
anaconda-project          0.8.2                      py_1    conda-forge
asn1crypto                0.24.0                   py36_3    conda-forge
astroid                   2.0.3                    py36_0    conda-forge
astropy                   3.0.4                    py36_0    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.6.3                    py36_0    conda-forge
bitarray                  0.8.3            py36hfa6e2cd_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blas                      1.0                         mkl
blaze                     0.11.3                   py36_0    conda-forge
bleach                    2.1.4                      py_1    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.14.4            h6538335_1000    conda-forge
bokeh                     0.13.0                   py36_0    conda-forge
boost                     1.66.0              py36_vc14_1  [vc14]  conda-forge
boost-cpp                 1.66.0                   vc14_1  [vc14]  conda-forge
boto                      2.49.0                   py36_0
boto3                     1.9.14                     py_0    conda-forge
botocore                  1.12.14                    py_0    conda-forge
bottleneck                1.2.1            py36hc8d92b1_1    conda-forge
branca                    0.3.0                      py_0    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24             py36_1001    conda-forge
cffi                      1.11.5           py36hfa6e2cd_1    conda-forge
chardet                   3.0.4                    py36_3    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.5.6                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.3.9                      py_1    conda-forge
comtypes                  1.1.7                 py36_1000    conda-forge
conda                     4.5.11                   py36_0    conda-forge
conda-build               3.15.1                   py36_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-verify              3.1.1                    py36_0    conda-forge
console_shortcut          0.1.1                         3
contextlib2               0.5.5                      py_2    conda-forge
cryptography              2.3.1            py36h74b6da3_0    conda-forge
cryptography-vectors      2.3.1                    py36_0    conda-forge
curl                      7.60.0                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.28.5           py36h6538335_0    conda-forge
cytoolz                   0.9.0.1          py36hfa6e2cd_0    conda-forge
dask                      0.19.2                     py_0    conda-forge
dask-core                 0.19.2                     py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
distributed               1.23.2                   py36_0    conda-forge
docutils                  0.14                     py36_1    conda-forge
entrypoints               0.2.3                    py36_2    conda-forge
et_xmlfile                1.0.1                 py36_1000    conda-forge
expat                     2.2.5                    vc14_0  [vc14]  conda-forge
fastcache                 1.0.2            py36hfa6e2cd_1    conda-forge
filelock                  3.0.4                      py_1    conda-forge
fiona                     1.7.13           py36h01e27f7_3    conda-forge
flask                     1.0.2                      py_2    conda-forge
flask-cors                3.0.6                      py_0    conda-forge
folium                    0.6.0                      py_0    conda-forge
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
freexl                    1.0.2                    vc14_2  [vc14]  conda-forge
future                    0.16.0                   py36_2    conda-forge
gdal                      2.2.4            py36h2fc6367_1    conda-forge
gensim                    3.5.0               py36_vc14_0  [vc14]  conda-forge
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geopy                     1.17.0                     py_0    conda-forge
geos                      3.6.2                he025d50_3    conda-forge
geotiff                   1.4.2                    vc14_1  [vc14]  conda-forge
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.3.6            py36hfa6e2cd_0    conda-forge
glob2                     0.6                        py_0    conda-forge
greenlet                  0.4.13                   py36_0    conda-forge
h5py                      2.8.0            py36hfa6e2cd_0    conda-forge
hdf4                      4.2.13                   vc14_0  [vc14]  conda-forge
hdf5                      1.10.1                   vc14_2  [vc14]  conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.7                      py36_2    conda-forge
imageio                   2.3.0                      py_1    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
intel-openmp              2019.0                      118
ipykernel                 5.0.0              pyh24bf2e0_1    conda-forge
ipython                   7.0.1            py36h39e3cac_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                    py36_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jdcal                     1.4                        py_1    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.6.0                    py36_2    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.34.12                  py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
kealib                    1.4.7                    vc14_4  [vc14]  conda-forge
keyring                   13.2.1                   py36_0    conda-forge
kiwisolver                1.0.1            py36he980bc4_2    conda-forge
krb5                      1.14.6                   vc14_0  [vc14]  conda-forge
lazy-object-proxy         1.3.1            py36hfa6e2cd_0    conda-forge
libcurl                   7.61.1               h7602738_0
libgdal                   2.2.4                    vc14_5  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libnetcdf                 4.6.1                    vc14_2  [vc14]  conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libpq                     9.6.3                    vc14_0  [vc14]  conda-forge
libsodium                 1.0.16                   vc14_0  [vc14]  conda-forge
libspatialindex           1.8.5                    vc14_1  [vc14]  conda-forge
libspatialite             4.3.0a                  vc14_19  [vc14]  conda-forge
libssh2                   1.8.0             hc4dcbb0_1002    conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
libxslt                   1.1.32                   vc14_0  [vc14]  conda-forge
llvmlite                  0.24.0                   py36_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.3            py36heafd4d3_0    conda-forge
lzo                       2.10                     vc14_0  [vc14]  conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.0              py36hfa6e2cd_1    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.14                   py36_0    conda-forge
mistune                   0.8.3            py36hfa6e2cd_2    conda-forge
mkl                       2019.0                      118
mkl-service               1.1.2            py36hb217b18_5
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
more-itertools            4.3.0                    py36_0    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.5.6            py36he980bc4_2    conda-forge
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
navigator-updater         0.2.1                    py36_0
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
networkx                  2.2                        py_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.7.0                    py36_0    conda-forge
numba                     0.39.0           py36h830ac7b_0
numexpr                   2.6.6                    py36_0    conda-forge
numpy                     1.15.2           py36ha559c80_0
numpy-base                1.15.2           py36h8128ebf_0
numpydoc                  0.8.0                      py_1    conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
odo                       0.5.1                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.0                    vc14_2  [vc14]  conda-forge
openpyxl                  2.5.8                      py_0    conda-forge
openssl                   1.0.2p            hfa6e2cd_1000    conda-forge
osmnx                     0.8.2                      py_0    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py36h830ac7b_0    conda-forge
pandoc                    2.3.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.8                      py_1    conda-forge
path.py                   11.0.1                     py_0    conda-forge
pathlib2                  2.3.2                    py36_0    conda-forge
patsy                     0.5.0                      py_1    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pickleshare               0.7.5                    py36_0    conda-forge
pillow                    5.2.0                    py36_0    conda-forge
pip                       18.0                     py36_1    conda-forge
pkginfo                   1.4.2                      py_1    conda-forge
pluggy                    0.7.1                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
proj4                     4.9.3                    vc14_5  [vc14]  conda-forge
prometheus_client         0.3.1                      py_1    conda-forge
prompt_toolkit            2.0.5                      py_0    conda-forge
psutil                    5.4.7            py36hfa6e2cd_1    conda-forge
psycopg2                  2.7.5            py36h74b6da3_1    conda-forge
py                        1.6.0                      py_0    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycosat                   0.6.3            py36hfa6e2cd_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pycurl                    7.43.0.2         py36h74b6da3_0
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pylint                    2.1.1                    py36_0    conda-forge
pyodbc                    4.0.24           py36h6538335_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.2                      py_0    conda-forge
pyproj                    1.9.5.1          py36haf3c679_5    conda-forge
pyqt                      5.6.0            py36h764d66f_7    conda-forge
pyreadline                2.1                   py36_1000    conda-forge
pysal                     1.14.4.post2             py36_0    conda-forge
pysocks                   1.6.8                    py36_2    conda-forge
pytables                  3.4.4                    py36_8    conda-forge
pytest                    3.8.1                    py36_0    conda-forge
pytest-arraydiff          0.2                        py_0    conda-forge
pytest-astropy            0.4.0                      py_0    conda-forge
pytest-doctestplus        0.1.3                      py_0    conda-forge
pytest-openfiles          0.3.0                      py_0    conda-forge
pytest-remotedata         0.3.0                      py_0    conda-forge
python                    3.6.6                he025d50_0    conda-forge
python-crfsuite           0.9.2               py36_vc14_0  [vc14]  conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywavelets                1.0.1            py36h452e1ab_0    conda-forge
pywin32                   223             py36hfa6e2cd_1000    conda-forge
pywin32-ctypes            0.2.0                    py36_0    conda-forge
pywinpty                  0.5.4                    py36_2    conda-forge
pyyaml                    3.13             py36hfa6e2cd_1    conda-forge
pyzmq                     17.1.2           py36hf576995_0    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.5.1              pyh8a2030e_0    conda-forge
qtconsole                 4.4.1                    py36_1    conda-forge
qtpy                      1.5.1              pyh8a2030e_0    conda-forge
requests                  2.19.1                   py36_1    conda-forge
requests-oauthlib         1.0.0                      py_1    conda-forge
rope                      0.10.7                     py_1    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
ruamel_yaml               0.15.71          py36hfa6e2cd_0    conda-forge
s3transfer                0.1.13                   py36_1    conda-forge
scikit-image              0.14.0           py36h6538335_1    conda-forge
scikit-learn              0.20.0           py36heebcf9a_1
scipy                     1.1.0            py36h4f6bf74_1
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.4.0                py36_1000    conda-forge
shapely                   1.6.4            py36hc90234e_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3                  py36_0    conda-forge
sip                       4.18.1           py36h6538335_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
smart_open                1.7.1                      py_0    conda-forge
snappy                    1.1.7                    vc14_1  [vc14]  conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcollections         1.0.1                      py_1    conda-forge
sortedcontainers          2.0.5                      py_0    conda-forge
sphinx                    1.8.1                    py36_0    conda-forge
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.1                    py36_2    conda-forge
spyder-kernels            0.2.6                      py_1    conda-forge
sqlalchemy                1.2.12           py36hfa6e2cd_0    conda-forge
sqlite                    3.20.1                   vc14_2  [vc14]  conda-forge
statsmodels               0.9.0                    py36_0    conda-forge
sympy                     1.3                      py36_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                    py36_1    conda-forge
testpath                  0.4.1                    py36_0    conda-forge
tk                        8.6.8                    vc14_0  [vc14]  conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.1.1            py36hfa6e2cd_0    conda-forge
tqdm                      4.26.0                     py_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
twython                   3.7.0                      py_0    conda-forge
typed-ast                 1.1.0                    py36_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
urllib3                   1.23                     py36_1    conda-forge
vc                        14                            0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.31.1                py36_1001    conda-forge
widgetsnbextension        3.4.2                    py36_0    conda-forge
win_inet_pton             1.0.1                    py36_2    conda-forge
win_unicode_console       0.5                      py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.10.11          py36hfa6e2cd_1    conda-forge
xerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xlsxwriter                1.1.1                      py_0    conda-forge
xlwings                   0.11.8                   py36_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
zeromq                    4.2.5                    vc14_2  [vc14]  conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
</details>

#### Code snippet that independently and completely reproduces the issue
I run "jupyter notebook" in the command promt as you can see below:
C:\Users\Kaylee>jupyter notebook
[I 14:18:14.257 NotebookApp] JupyterLab extension loaded from C:\Users\Kaylee\Anaconda3\lib\site-packages\jupyterlab
[I 14:18:14.257 NotebookApp] JupyterLab application directory is C:\Users\Kaylee\Anaconda3\share\jupyter\lab
[I 14:18:14.261 NotebookApp] Serving notebooks from local directory: C:\Users\Kaylee
[I 14:18:14.264 NotebookApp] The Jupyter Notebook is running at:
[I 14:18:14.264 NotebookApp] http://localhost:8888/?token=0181fb8d966133f1204bc9d2ec7953144dbc2710bbf8e155
[I 14:18:14.265 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:18:14.270 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=0181fb8d966133f1204bc9d2ec7953144dbc2710bbf8e155
[I 14:18:14.503 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 14:18:36.981 NotebookApp] Creating new notebook in
[I 14:18:37.747 NotebookApp] Kernel started: d75b8d15-d664-4db1-a742-f76a31edfee7
[I 14:18:38.421 NotebookApp] Adapting to protocol v5.1 for kernel d75b8d15-d664-4db1-a742-f76a31edfee7
Configured osmnx
[I 14:20:37.734 NotebookApp] Saving file at /Untitled1.ipynb

After I opened the jupyter notebook, I run the code as following:
![image](https://user-images.githubusercontent.com/43792717/46500797-f7df2c00-c7e0-11e8-8e45-d2273477c32c.png)

This code is exactly the same as what I described for the code causing errors above.
I think there are some problems dealing with the function "ox.graph_from_point", or the packages which one exactly I do not know.
Besides, this is not the only case I got RunTime Error. I got RunTime Error every single time when I run different code. I tried many codes from different examples you provide, but I still got the same results (same error "RuntimeError: b'No such file or directory'"). 
Therefore, I am not sure if I have issues in installation.

Thanks very much for helping me. I really don't know what is going on.

**Comment by gboeing** [comment]
This isn't an OSMnx issue... it is an issue with one of its dependencies, pyproj. In general, I'd recommend installing OSMnx in a conda virtual environment (which should solve this) per the instructions here: https://osmnx.readthedocs.io/en/stable/#installation

Alternatively, see this issue and my reply: https://github.com/geopandas/geopandas/issues/830#issuecomment-426116505

**Comment by KayleeZhu** [comment]
Hi Boeing,
Thanks very much for your speedy reply.
I tried to install it in a new, clean virtual environment using conda and conda-forge, but it failed.
This is what I got:

C:\Users\Kaylee>conda create --override-channels -c conda-forge -n OSMNX python=3 osmnx
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - osmnx
  - geopandas[version='>=0.2.1']
  - gdal=2.1
  - osmnx
  - geopandas[version='>=0.2.1']
  - pysal
  - scipy[version='>=0.11']

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by gboeing** [comment]
Ah, because you're on Windows right? I think conda-forge might not have a scipy build for windows so you can't override channels like that on windows. So, try the solution here to set up the environment variable: https://github.com/geopandas/geopandas/issues/830#issuecomment-426116505

**Comment by KayleeZhu** [comment]
Yes, I am on windows!
Do you mean running 
"import os
os.environ["PROJ_LIB"] = "C:\Anaconda\envs\env_name\Library\share" #windows"
on jupyter notebook?

**Comment by gboeing** [comment]
Yes.

**Comment by KayleeZhu** [comment]
I am not sure if I got you right. It still doesn't work.
![image](https://user-images.githubusercontent.com/43792717/46545032-750ead80-c882-11e8-802f-e4863e0e8ceb.png)
![image](https://user-images.githubusercontent.com/43792717/46545038-78099e00-c882-11e8-98ee-6c55f26f40f1.png)

**Comment by gboeing** [comment]
Please post code as text rather than screenshots, so I can work with it. You need to update the line `os.environ["PROJ_LIB"] = "C:\Anaconda\envs\env_name\Library\share"` to reflect the reality of your computer's path. If you installed in a virtual environment, browse your `c:\Anaconda` to find the environment name and make sure it contains `Library\share` subfolders.

If this doesn't resolve it, you'll need to open an issue with pyproj, as this is a problem with their installation and location of their data directory.

**Comment by KayleeZhu** [comment]
Thank you very much! I think it works now!

**Comment by qwer345345** [comment]
Hi all
I have a question here with osmnx, when i apply ox.graph_from_place function, it always returns the error 
![image](https://user-images.githubusercontent.com/39678864/52178114-a6649f00-27ca-11e9-97a4-8c17b36f0740.png). 
I tried the codes mentioned previously, as shown following, but it still doesnt work and returns the same error. Can someone give me some advice? 
![image](https://user-images.githubusercontent.com/39678864/52178122-c4320400-27ca-11e9-9234-75ed5a39857f.png)

**Comment by custom-directive-hurt** [comment]
Glance this way for the answer https://pythondev.space/questions/error-the-init-function-requires-4-arguments-to-be-passed-but-only-3-were-provided-this-pertains
