### ISSUE TITLE
Download Isochrone as a shapefile or geojson?

### ISSUE THREAD

**Issue by kzhanar** [gboeing/osmnx#204]
The issue tracker is for reporting bugs and feature requests. Before you proceed, please read the contributing guidelines in this repo's CONTRIBUTING.md.

If you installed OSMnx via conda and are experiencing installation problems, please open an issue at https://github.com/conda-forge/osmnx-feedstock/issues

If you're having trouble with OSMnx, first search the previously opened issues to see if the problem has already been noted. If not, fill in the template below:

**Comment by gboeing** [comment]
Is this a "how-to" question or a new feature request? If it is a how-to question, per the contributing guidelines please ask it at [StackOverflow](https://stackoverflow.com/search?q=osmnx). If it's a feature request, please sketch it out in detail.
