### ISSUE TITLE
TypeError: Geometry must be a shapely Polygon or MultiPolygon.

### ISSUE THREAD

**Issue by fanyangxyz** [gboeing/osmnx#207]
I'm using osmnx 0.8.2 on Ubuntu 16.04 and Python 3.6.

When trying this example:
https://github.com/gboeing/osmnx-examples/blob/master/notebooks/15-calculate-visualize-edge-bearings.ipynb

When I run the code 
```
G = ox.graph_from_place('Moraga, California')
```
It returns the following TypeError
```
TypeError: Geometry must be a shapely Polygon or MultiPolygon. If you requested graph from place name or address, make sure your query resolves to a Polygon or MultiPolygon, and not some other geometry, like a Point. See OSMnx documentation for details.
```

I'm very confused, since this is different from the example output in the notebook.

**Comment by gboeing** [comment]
Geocoder results can change from time to time. Feel free to issue a PR to update the example!

For a full explanation of this issue and how to fix see #16.

See also #11 and #118
