### ISSUE TITLE
Error when extracting POIs

### ISSUE THREAD

**Issue by bpstewar** [gboeing/osmnx#208]
The issue tracker is for reporting bugs and feature requests. Before you proceed, please read the contributing guidelines in this repo's CONTRIBUTING.md.

If you installed OSMnx via conda and are experiencing installation problems, please open an issue at https://github.com/conda-forge/osmnx-feedstock/issues

If you're having trouble with OSMnx, first search the previously opened issues to see if the problem has already been noted. If not, fill in the template below:

#### Problem description (what did you do, what did you expect to happen, and what actually happened)
I was running a simple extract POIs for Bamako and encountered the following error - for which I am proposing a solution

#### What operating system, architecture, Python version, and OSMnx version are you using?
Windows, Python 3.7, OSMNX 0.8.2
</details>

#### Code snippet that independently and completely reproduces the issue
```python
>>> df = ox.pois_from_polygon(polygon = self.bbox, amenities = self.current_amenity)
```
I have identified the error, and I updated a solution in my local OSMNX install, if you want to incorporate it into the code. At line 255(ish) of pois.py there is a check of relation tags that causes the error below

```python
if  relation['tags']['type'] == 'multipolygon':
    try:
        # Parse member 'way' ids
        member_way_ids = [member['ref'] for member in relation['members'] if member['type'] == 'way']        

### PROPOSED CHANGE

try:
  relType = relation['tags']['type']
except:
  relType = ''
if relType == 'multipolygon':
  try:
    # Parse member 'way' ids
    member_way_ids = [member['ref'] for member in relation['members'] if member['type'] == 'way']        
```

```python
###Error Encountered
>>> df = ox.pois_from_polygon(polygon = self.bbox, amenities = self.current_amenity)
        
  File "testing_pois.py", line 15, in <module>
    temp = current.GenerateOSMPOIs()
  File "C:\Users\WB411133\OneDrive - WBG\AAA_BPS\Code\Code\Github\GOST_PublicGoods\Market_Access\OSMNX_POIs.py", line 67, in GenerateOSMPOIs
    df = ox.pois_from_polygon(polygon = self.bbox, amenities = self.current_amenity)
  File "C:\WBG\Anaconda\envs\gbdxtools\lib\site-packages\osmnx\pois.py", line 434, in pois_from_polygon
    return create_poi_gdf(polygon=polygon, amenities=amenities)
  File "C:\WBG\Anaconda\envs\gbdxtools\lib\site-packages\osmnx\pois.py", line 357, in create_poi_gdf
    gdf_ways = parse_osm_relations(relations=relations, osm_way_df=gdf_ways)
  File "C:\WBG\Anaconda\envs\gbdxtools\lib\site-packages\osmnx\pois.py", line 252, in parse_osm_relations
    if relation['tags']['type'] == 'multipolygon':
KeyError: 'type'
```

**Comment by gboeing** [comment]
Can you provide a complete code snippet to independently reproduce the issue?

Secondly, if you've found a solution, would you like to open a PR?

**Comment by rbhatia46** [comment]
Hi @gboeing first of all thanks for such an amazing package! However, this issue still persists, and even after trying the changes suggested by @bpstewar, there's no improvement, can you please suggest a fix around the same?

Thanks

**Comment by gboeing** [comment]
If someone provides a complete code snippet to independently reproduce the issue, I can take a look.

**Comment by lnicoletti** [comment]
Hi @gboeing! Yes, thank you for this really great package! I would like point that this issue still persists. My code is:

`import osmnx as ox
NYC_pois = ox.pois_from_place('New York City')`

I get the same error described by @bpstewar. And as mentioned @rbhatia46, @bpstewar's fix does not solve the problem. I have used this function (and "pois_from_polygon" as well) for several cities around the world, with no problems. The error happens only with NYC. Any idea of what may be causing the problem?

Thank you!

**Comment by gboeing** [comment]
Should be fixed in #431

**Comment by gboeing** [comment]
@lnicoletti the fix has been merged into master and tested using your MWE. Thanks!

**Comment by lnicoletti** [comment]
Thanks @gboeing !
