### ISSUE TITLE
Duplicate columns

### ISSUE THREAD

**Issue by SqySimmon** [gboeing/osmnx#209]
#### An example is here.
<img width="724" alt="screen shot 2018-10-21 at 10 28 11" src="https://user-images.githubusercontent.com/15140733/47262467-0f761e80-d51c-11e8-95e5-aa50ec916199.png">

#### list of my environment's packages and their versions

<details>
_license                  1.1                      py36_1  
_nb_ext_conf              0.4.0                    py36_1  
absl-py                   0.1.7                     <pip>
alabaster                 0.7.10                   py36_0  
altair                    2.2.2                    py36_1    conda-forge
anaconda                  custom                   py36_0  
anaconda-client           1.6.3                    py36_0  
anaconda-navigator        1.6.2                    py36_0  
anaconda-project          0.6.0                    py36_0  
asn1crypto                0.22.0                   py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3.2               np112py36_0  
babel                     2.4.0                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.6.0                    py36_0  
bitarray                  0.8.1                    py36_0  
blas                      1.0                         mkl  
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                     <pip>
bleach                    1.5.0                    py36_0  
bokeh                     0.12.5                   py36_1  
boto                      2.46.1                   py36_0  
bottleneck                1.2.1               np112py36_0  
branca                    0.3.0                      py_0    conda-forge
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              h77bcde2_0  
certifi                   2018.8.24                 <pip>
cffi                      1.10.0                   py36_0  
chardet                   3.0.3                    py36_0  
click                     6.7                      py36_0  
click-plugins             1.0.3                    py36_1  
cligj                     0.4.0                    py36_1  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.9                    py36_0  
conda                     4.4.6                    py36_0  
conda-env                 2.6.0                h36134e3_1  
contextlib2               0.5.5                    py36_0  
cryptography              1.8.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.14.3                   py36_1  
datashape                 0.5.4                    py36_0  
dbus                      1.10.10                       0  
decorator                 4.3.0                    py36_0  
descartes                 1.1.0                    py36_0  
distributed               1.16.3                   py36_0  
dm-control                0.0.0                     <pip>
docutils                  0.13.1                   py36_0  
easydict                  1.7                       <pip>
entrypoints               0.2.2                    py36_1  
enum34                    1.1.6                     <pip>
et_xmlfile                1.0.1                    py36_0  
expat                     2.2.5                he0dffb1_0  
fastcache                 1.0.2                    py36_1  
fiona                     1.7.10           py36h48a52f0_0  
flask                     0.12.2                   py36_0  
flask-cors                3.0.2                    py36_0  
folium                    0.6.0                      py_0    conda-forge
fontconfig                2.12.4               h88586e7_1  
freetype                  2.8.1                hfa320df_1    conda-forge
freexl                    1.0.5                h14c3975_0  
future                    0.16.0                    <pip>
gdal                      2.2.2            py36hc209d97_1  
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.3.0                    py36_0  
geopy                     1.17.0                     py_0    conda-forge
geos                      3.6.2                heeff764_2  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
giflib                    5.1.4                h14c3975_1  
glfw                      1.4.0                     <pip>
glib                      2.53.6               h5d9569c_2  
graphite2                 1.3.11               h16798f4_2  
greenlet                  0.4.12                   py36_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
gym                       0.9.3                     <pip>
h5py                      2.7.0               np112py36_0  
harfbuzz                  1.7.6                hc5b324e_0  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.1               h9caa474_1  
heapdict                  1.0.0                    py36_1  
html5lib                  0.999                    py36_0  
html5lib                  0.9999999                 <pip>
icu                       58.2                 h9c2bf20_1  
idna                      2.5                      py36_0  
imagesize                 0.7.1                    py36_0  
intel-openmp              2018.0.0             hc7b2577_8  
ipykernel                 4.6.1                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.10.2                   py36_2  
jinja2                    2.9.6                    py36_0  
jpeg                      9b                            0  
json-c                    0.12.1               ha6a3662_2  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_contrib_core      0.3.3                    py36_0    conda-forge
jupyter_contrib_nbextensions 0.3.3                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0  
jupyter_highlight_selected_word 0.1.0                    py36_0    conda-forge
jupyter_latex_envs        1.4.0                    py36_1    conda-forge
jupyter_nbextensions_configurator 0.2.8                    py36_0    conda-forge
kealib                    1.4.7                h79811e5_5  
Keras                     2.1.2                     <pip>
keras-rl                  0.4.0                     <pip>
kiwisolver                1.0.1            py36hf484d3e_0  
krb5                      1.16.1               hc83ff2d_6  
lazy-object-proxy         1.2.2                    py36_0  
libboost                  1.67.0               h46d08c1_4  
libdap4                   3.19.0               h8c95237_1  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                         1  
libgcc                    4.8.5                         2  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgdal                   2.2.2                h804cdde_1  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                h9f7466a_2  
libiconv                  1.14                          0  
libkml                    1.3.0                h590aaf7_4  
libnetcdf                 4.4.1.1              h816af47_8  
libpng                    1.6.34               hb9fc6fc_0  
libpq                     10.5                 h1ad7b7a_0  
libsodium                 1.0.10                        0  
libspatialindex           1.8.5                h20b78c2_2  
libspatialite             4.3.0a              h72746d6_18  
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.9                he85c1e1_1  
libtool                   2.4.2                         0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.18.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      4.1.1                    py36_0    conda-forge
Markdown                  2.6.9                     <pip>
markupsafe                0.23                     py36_2  
matplotlib                2.2.2            py36h0e671d2_0  
mistune                   0.7.4                    py36_0  
mkl                       2018.0.1             h19d6760_4  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
msgpack-python            0.4.8                    py36_0  
multipledispatch          0.4.9                    py36_0  
munch                     2.3.2                    py36_0  
navigator-updater         0.1.0                    py36_0  
nb_anacondacloud          1.4.0                    py36_0  
nb_conda                  2.2.1            py36h8118bb2_0  
nb_conda_kernels          2.1.0                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
nbpresent                 3.0.2            py36h5f95a39_1  
ncurses                   6.1                  hf484d3e_0  
networkx                  2.1                      py36_0  
nltk                      3.2.3                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  5.0.0                    py36_0  
numba                     0.33.0              np112py36_0  
numexpr                   2.6.4            py36hc4a3f9a_0  
numpy                     1.13.1                    <pip>
numpy                     1.14.2           py36hdbf6ddf_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
olefile                   0.44                     py36_0  
openjpeg                  2.3.0                h05c96fa_1  
openpyxl                  2.4.7                    py36_0  
openssl                   1.0.2p               h14c3975_0  
osmnx                     0.8.1                      py_0    conda-forge
packaging                 16.8                     py36_0  
pandas                    0.23.4           py36h04863e7_0  
pandocfilters             1.4.1                    py36_0  
pango                     1.41.0               hd475d92_0  
partd                     0.3.8                    py36_0  
path.py                   10.3.1                   py36_0  
pathlib2                  2.2.1                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    5.1.0            py36h3deb7b8_0  
pip                       9.0.1            py36h6c6f9ce_4  
pipenv                    2018.7.1                  <pip>
pixman                    0.34.0                        0  
ply                       3.10                     py36_0  
poppler                   0.60.1               hc909a00_0  
poppler-data              0.4.9                         0  
proj4                     4.9.3                hc8507d1_7  
prompt_toolkit            1.0.14                   py36_0  
protobuf                  3.4.0                     <pip>
psutil                    5.2.2                    py36_0  
psycopg2                  2.7.5            py36hb7f436b_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.33                   py36_0  
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_6  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pyglet                    1.3.0                     <pip>
pygments                  2.2.0                    py36_0  
pylint                    1.6.4                    py36_1  
pyodbc                    4.0.16                   py36_0  
pyopenssl                 17.0.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyproj                    1.9.5.1                  py36_0  
pyqt                      5.6.0                    py36_2  
pysal                     1.14.4.post1             py36_1  
pytables                  3.3.0               np112py36_0  
pytest                    3.0.7                    py36_0  
python                    3.6.4                hc3d631a_1  
python-dateutil           2.6.0                    py36_0  
pytz                      2017.2                   py36_0  
pywavelets                0.5.2               np112py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         7    conda-forge
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.0                    py36_0  
qtpy                      1.2.1                    py36_0  
readline                  7.0                  ha6073c6_4  
requests                  2.14.2                   py36_0  
rope                      0.9.4                    py36_1  
rtree                     0.8.3                    py36_0  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.13.0              np112py36_0  
scikit-learn              0.19.1           py36h7aa7ec6_0  
scipy                     1.0.0            py36hbf646e7_0  
seaborn                   0.7.1                    py36_0  
setuptools                36.4.0                    <pip>
setuptools                27.2.0                   py36_0  
shapely                   1.6.4            py36h7ef4460_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                    <pip>
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sortedcollections         0.5.3                    py36_0  
sortedcontainers          1.5.7                    py36_0  
sphinx                    1.5.6                    py36_0  
spyder                    3.1.4                    py36_0  
sqlalchemy                1.1.9                    py36_0  
sqlite                    3.20.1               hb898158_2  
statsmodels               0.8.0               np112py36_0  
sympy                     1.0                      py36_0  
tblib                     1.3.2                    py36_0  
tensorflow-gpu            1.3.0                     <pip>
tensorflow-tensorboard    0.1.6                     <pip>
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
tk                        8.6.7                hc745277_3  
toolz                     0.8.2                    py36_0  
torch-0.2.0               3                         <pip>
torchvision               0.1.9                     <pip>
tornado                   4.5.1                    py36_0  
tqdm                      4.19.5                    <pip>
traitlets                 4.3.2                    py36_0  
unicodecsv                0.14.1                   py36_0  
unixodbc                  2.3.4                         0  
util-linux                2.21                          0  
uvloop                    0.10.2                    <pip>
vincent                   0.4.4                      py_1    conda-forge
virtualenv                16.0.0                    <pip>
virtualenv-clone          0.3.0                     <pip>
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.12.2                   py36_0  
Werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                   py36_0  
wheel                     0.30.0                    <pip>
widgetsnbextension        2.0.0                    py36_0  
wrapt                     1.10.10                  py36_0  
xerces-c                  3.2.1                hac72e42_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zict                      0.1.2                    py36_0  
zlib                      1.2.11               ha838bed_2
</details>

**Comment by gboeing** [comment]
@SqySimmon can you provide a complete code snippet to reproduce your issue from scratch?

**Comment by SqySimmon** [comment]
#### get data
```
import osmnx as ox
graph = ox.graph_from_place("beijing, china", which_result=2, network_type='drive')
```
#### transform nodes edges
`nodes, edges = ox.graph_to_gdfs(graph)`
#### length from 125845 to 36516
```
import pandas as pd
print(len(edges['osmid']))
print(len(pd.unique(edges['osmid'])))
```
#### almost same rows
```
from shapely.geometry import Point, shape
print('------------------------------ Same Edges ------------------------------')
print(edges[(edges['u']=='5227945378') & (edges['v']=='5227945383')])

print('------------------------------ Same Edges geometry column ------------------------------')

print(shape(edges[(edges['u']=='5227945378') & (edges['v']=='5227945383')].loc[5814]['geometry']))
print(shape(edges[(edges['u']=='5227945378') & (edges['v']=='5227945383')].loc[5815]['geometry']))
print(shape(edges.loc[5815]['geometry']) == shape(edges.loc[5814]['geometry']))
```
#### result
<img width="724" alt="screen shot 2018-10-21 at 10 28 11" src="https://user-images.githubusercontent.com/15140733/47268060-7d533200-d57e-11e8-8244-7319e05d6ad5.png">

**Comment by gboeing** [comment]
> But you can see that there are rows with same node u and node v, is that the combination of osmid, u and v the unique id?

No, like I said in my response:

> because it is built on top of networkx, the unique id is the combination of u, v, key

See the networkx documentation, for example [here](https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.MultiDiGraph.edges.html) and [here](https://networkx.github.io/documentation/stable/reference/introduction.html#data-structure).

**Comment by SqySimmon** [comment]
I got it, thanks.
