### ISSUE TITLE
IOError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by yyan162** [gboeing/osmnx#211]
Hi Sir,

I am started to use your library to do traffic network. 

I have python 2.7 and have installed osmnx with conda. My computer is 64-bit. I use Spyder for analysis instead of jupyter.

The code I am running is a very basic one:

The code can be run without problem on a ipython kernel for the first time, but when I run it for a second time, the following message shows up:

```
runfile('C:/Users/B***/Desktop/testing.py', wdir='C:/Users/B***/Desktop')
Traceback (most recent call last):

  File "C:\Anaconda_27\lib\site-packages\IPython\core\interactiveshell.py", line 2895, in run_code
    self.showtraceback()

  File "C:\Anaconda_27\lib\site-packages\IPython\core\interactiveshell.py", line 1828, in showtraceback
    self._showtraceback(etype, value, stb)

  File "C:\Anaconda_27\lib\site-packages\ipykernel\zmqshell.py", line 541, in _showtraceback
    sys.stdout.flush()

IOError: [Errno 9] Bad file descriptor
```

The code is this one:

```
import osmnx as ox

ox.config(log_file=True, log_console=True, use_cache=True)
# define a bounding box in San Francisco
north, south, east, west = 37.79, 37.78, -122.41, -122.43

# create network from that bounding box
G1 = ox.graph_from_bbox(north, south, east, west, network_type='drive_service')
G1 = ox.project_graph(G1)
fig, ax = ox.plot_graph(G1)
```

Thank you very much for your kind assistance.

Regards,
yyan162

**Comment by gboeing** [comment]
This doesn't look like an OSMnx issue, but something with your environment. I'd strongly suggest installing OSMnx in a virtual environment (a python 3 one, to be specific) and then running the code again.

```
conda create --override-channels -c conda-forge -n OSMNX python=3 osmnx
```
