### ISSUE TITLE
graph_from_file silently ignores network_type

### ISSUE THREAD

**Issue by RunOrVeith** [gboeing/osmnx#212]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

0. Download an osm file (I used [California](https://download.geofabrik.de/north-america/us/california.html)), and extracted a smaller bounding box from it using [osmconvert](https://wiki.openstreetmap.org/wiki/Osmconvert)
```
osmconvert /home/veith/Downloads/california-latest.osm.pbf -b=-122.426758,37.468958,-122.32628133333333,37.54542633333333 --drop-broken-refs -o=/tmp/17959953994637619024173.osm
```
1. Load that file: 
```
import osmnx as ox
G1 = ox.graph_from_file("/tmp/17959953994637619024173.osm", simplify=True, network_type="drive")
G2 = ox.graph_from_file("/tmp/17959953994637619024173.osm", simplify=True, network_type="all_private")
bbox = [-122.426758,37.468958,-122.32628133333333,37.54542633333333]
G3 =  ox.graph_from_bbox(north=bbox[3], south=bbox[1],
                                   east=bbox[2], west=bbox[0],
                                   simplify=True, network_type="drive")
```

3. Result: G1 and G2 are the same, G3 contains a lot less nodes (all smaller ways removed)
4. Expected behavior: G1 == G3, and G2 is a lot larger
5. Problem: `network_type` is passed along like `graph_from_file` calls `create_graph` calls `add_path`, where it is only used to check one way streets for walkways. In all other `graph_from_X` functions, an `osm_filter` is used to query the overpass API with appropriate filters.
There is no mention at all in the doc-strings or documentation that `network_type` is more or less ignored for `graph_from_file`.

#### What operating system, architecture, Python version, and OSMnx version are you using?
Ubuntu 18.04, python 3.6, OSMnx 0.8.2

**Comment by RunOrVeith** [comment]
It would definitely be more clear and meaningful. 
I am assuming to support the full functionality more or less all functionality of the overpass API would need to be implemented?

**Comment by gboeing** [comment]
Correct.

**Comment by gboeing** [comment]
@RunOrVeith as this would be a quick patch, would you like to create a pull request along the lines of https://github.com/gboeing/osmnx/issues/212#issuecomment-434047009?

**Comment by RunOrVeith** [comment]
Yes, I can do it. Do you have a procedure for API deprecation?

**Comment by gboeing** [comment]
Normally it would be nice to do a deprecation warning but in this case I think we can skip it and directly update the code.
