### ISSUE TITLE
osmx_divisionerror_float division by zero

### ISSUE THREAD

**Issue by YATPKU** [gboeing/osmnx#215]
Hello!
I had an error with shapely polygon or multipolygon, but it worked when I changed from place to address. In 3rd next step, I added 'which_result=2' to avoid geometry error. In 4th step, it failed several times, but when removed 'area=area,' it worked but the results showed some missing value 'None'.

#1 get the network for Piedmont, calculate its basic stats, then show the average circuity
In[1 ] : stats = ox.basic_stats(ox.graph_from_address('phnompenh,Cambodia'))
           stats['circuity_avg']
Out[2 ] :1.0405251692295552

#2 get the street network for a place and its area in square meters
In [3]: address = 'phnompenh,Cambodia'
          gdf = ox.gdf_from_place(address)
          area = ox.project_gdf(gdf).unary_union.area
          G = ox.graph_from_address(address, network_type='drive_service')

#3 get the street network for a place and its area in square meters
In[4]:   place = 'Phnom Penh, Cambodia'
           gdf = ox.gdf_from_place(place)
           area = ox.project_gdf(gdf).unary_union.area
           G = ox.graph_from_place(place, which_result=2, network_type='drive_service')
#4 calculate basic and extended network stats, merge them together, and display
In[5]:    stats = ox.basic_stats(G,)
            extended_stats = ox.extended_stats(G, ecc=True, bc=True, cc=True)
            for key, value in extended_stats.items():
                      stats[key] = value
            pd.Series(stats)

Here are the outputs with "None"

node_density_km                                                                  
None
intersection_density_km                                                     
None
edge_density_km                                                                
None
street_density_km                                                                
None
circuity_avg                                                                            
1.01897
self_loop_proportion                                                                
  0
clean_intersection_count                                                           
None
clean_intersection_density_km                                                      
None

I don't know why 4 important density outputs were "None"
I am a beginner at python and osmnx. Any advice to fix them, please? I really appreciate!

**Comment by gboeing** [comment]
You are creating the graph of Phnom Penh using `which_result=2`. But you are created the GeoDataFrame (to get its area) using the default argument, ie `which_result=1`, which returns a point and thus has area=0. Hence you get a divide by zero error when you calculate densities. You need to consistently download the same result number for both operations, like:

```python
place = 'Phnom Penh, Cambodia'
gdf = ox.gdf_from_place(place, which_result=2)
area = ox.project_gdf(gdf).unary_union.area
G = ox.graph_from_place(place, which_result=2, network_type='drive_service')
stats = ox.basic_stats(G, area=area)
```
