### ISSUE TITLE
ram fills to whole capacity 

### ISSUE THREAD

**Issue by isfando** [gboeing/osmnx#218]
I am trying to make graph from file(whole of finland) and my whole ram (8 gb ) gets filled up and the program is stuck at snail pace . How can i solve this issue.

```python
# your code goes here
import osmnx as ox
import matplotlib.pyplot as plt

ox.config(log_console=True)
G = ox.graph_from_file('../resources/finland-latest.osm.bz2',  network_type='drive')
fig, ax = ox.plot_graph(G)
```

**Comment by gboeing** [comment]
In general, your options are:

1. Acquire more RAM (either install more RAM in your machine, or use a cloud service like AWS with flexible memory). 8gb isn't much to work with, especially if you're trying to model an entire nation.

2. Create the graph model using a coarser-grained representation of the street network (such as primary roads and up). You can do this by using a custom filter when downloading from OSM (similar to here: https://github.com/gboeing/osmnx/issues/151)

3. Create the graph model using a small geography unit of analysis, such as a single county.

**Comment by isfando** [comment]
Thanks alot for the guidance.
