### ISSUE TITLE
graph_from_place returns exception for the requested place

### ISSUE THREAD

**Issue by MustafaIsmaill** [gboeing/osmnx#219]
The following code return an exception.

`import osmnx as ox`
`place_name = 'Universidad Carlos III de Madrid, Leganes, Spain'`
`graph = ox.graph_from_place(place_name, network_type='drive')`

>Exception: There are no nodes within the requested geometry

Even though I used the nominatim API to make sure that my search string includes a closed area and not a point but still it returns an exception. 
I also tried adding `which_result` argument but still I get the same exception.

**Comment by gboeing** [comment]
The query you're using seems to geocode to the auditorio rather than to the campus polygon. This query appears to work instead:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
place_name = 'Universidad Carlos III de Madrid, 30, Avenida de la Universidad'
G = ox.graph_from_place(place_name, network_type='all')
```

Sometimes it takes a little bit of fudging around with the query string to get the Nominatim geocoder's magic to work properly.

**Comment by MustafaIsmaill** [comment]
well thanks for the reply!
