### ISSUE TITLE
Docs unclear: difference between edge length and street length

### ISSUE THREAD

**Issue by cbeddow** [gboeing/osmnx#220]
I'm trying to see the difference between total street length and total edge length, from the basic stats.

When I sum the total edge length in the geometry, with 3857 projection, I get a higher number that the street length total. Can anybody help me explain the difference in how these are calculated?

I'm pulling the graph from a bbox, then trying to calculate total road length inside smaller grids. Right now I am using Shapely's intersection function to get the small grid geometry and then sum the length in meters on web mercator

![image](https://user-images.githubusercontent.com/10554922/49028005-b7c57580-f1a1-11e8-9688-1367883d0579.png)

I want to make sure this is reasonably accurate

**Comment by gboeing** [comment]
OSMnx uses networkx MultiDiGraphs as the underlying network model. As these are directed graphs, all bidirectional streets are represented by two reciprocal directed edges. Total street length instead uses (essentially) an undirected version of this model to quantify how many linear meters of physical street exist in the study area. If every street in your network is bidirectional, total edge length will thus equal approximately 2x the total street length.

**Comment by cbeddow** [comment]
@gboeing perfect, that makes sense. So I guess what I need is a way to get to total street length of a subsection. If I pulled the entire grey road network because I want to only make one large API call, then how can I calculate total street length for the bbox of just one smaller grid?

Right now I'm doing:

1. turn road into a gdf
2. get road_gdf.unitary_union.intersection(small_grid)
3. calculate length of the intersection, based on 3857 projection meters (good enough)

But this means I'm getting double edges for all streets, if I understand correctly?

So I need to either heuristically just divide that edge length by 2 and assume it's closer, or is there a better way to make sure I get the total street length for the intersection?

**Comment by gboeing** [comment]
A decent option would be to produce an undirected version of the graph, then sum the edge lengths (since they'll no longer have bidirectional duplicates): https://osmnx.readthedocs.io/en/latest/osmnx.html#osmnx.save_load.get_undirected

**Comment by gboeing** [comment]
@cbeddow is this issue ready to be closed?

**Comment by cbeddow** [comment]
Yes, thank you. I will reference it in the future and re-open if I have question!
