### ISSUE TITLE
Is there a way of visualizing or representing two way or multiple lane roads?

### ISSUE THREAD

**Issue by MustafaIsmaill** [gboeing/osmnx#225]
I am working on an autonomous vehicle project where I use OSMnx to extract the road information to use for path planning and navigation control, and when it comes to navigation in oneway roads it works perfectly. However, when it comes to multiple lane roads it is not very accurate due to the fact that multiple lane roads are represented as a single edge.

For example the edge (in red) shown here is supposed to be a two-way road yet both ways are represented as a single edge in the middle of both ways. 
![issue](https://user-images.githubusercontent.com/24419212/49439358-18b40580-f7c1-11e8-92ac-84613de0eabc.png)

I know there is a key (lanes) that tells how many lanes are on each edge yet still is there a way that I can get maybe the geometry of the other lanes or a different way of representation other than just the middle line of the road?

**Comment by gboeing** [comment]
@MustafaIsmaill the edges represent the node-to-node centerlines, so bidirectional streets have reciprocal directed edges laid atop one another, and multiple-lane roads are represented by a single line. This conforms to the OSM/OSMnx theoretical model of a street network, where nodes represent intersections/dead-ends and edges represent the street segments that link them.

OSM/OSMnx do not represent the street network with polygons or with multiple edges for each lane. You could however do this yourself by looping through the edges and adding parallel edges for each lane. You could evenly alter each parallel edge's geometry as you see fit if you'd like them to appear side-by-side when plotting.

See related: https://github.com/gboeing/osmnx/issues/162

**Comment by MustafaIsmaill** [comment]
@gboeing the parallel_point_shift here #162 seems to do it, but I think I am gonna need to know as well the width of each lane, so I wonder if there is a way to find out?
Also one more thing, the solution in #162 assumes only one lane for each direction although there might be more. I know I can use the `edges.lanes` column to know how many lanes are in each edge but usually the output is NaN as in the screenshot. 
![nan_issue](https://user-images.githubusercontent.com/24419212/49447463-eca37f00-f7d6-11e8-8397-32b70b2f8afd.png)

I was thinking maybe I can use the info from `edges.highway` to know how many lanes are in each road depending on whether it's a residential, secondary or a primary road. What do you think?

**Comment by gboeing** [comment]
Regarding number of lanes, yes you might want to impute/infer this from the highway tag as this metadata is spotty on OSM. Regarding lane widths, that data is not present but you could could impute/infer it as well based on standard urban design in your study area.
