### ISSUE TITLE
ways ids for shortest path

### ISSUE THREAD

**Issue by isfando** [gboeing/osmnx#227]
In a route we get a list of all the nodes from source to destination.

route = nx.shortest_path(G,origin_node,desitination_node, weight='length')

Is it possible to get all the osm way ids from source to destination

**Comment by gboeing** [comment]
Yes it is. As the issue tracker is for reporting bugs or proposing new features, it's best to ask how-to questions at the user community on StackOverflow: https://stackoverflow.com/search?q=osmnx
