### ISSUE TITLE
Footpaths on water

### ISSUE THREAD

**Issue by ylzhouchris** [gboeing/osmnx#228]
#### Problem description

Hi, we are trying to use OSMNX to extract footpath in Boston. 
We found that the Massachusetts Bridge is not included in the graph while it is walk-able. Is this a problem with OSM data? or did you do any filtering to footpaths on water. 

Here's my code (Python 3): 
```python
location_point = (42.352367, -71.090240)
G = ox.graph_from_point(location_point, distance=500, network_type='walk',simplify=False)
fig, ax = ox.plot_graph(G, node_color='b', `node_zorder=3)
```

Thanks!

**Comment by gboeing** [comment]
@ylzhouchris it looks like it's working correctly. I believe you just made your bounding box too small to include the nodes on the north side of the bridge, so it wasn't capturing it. Update your `distance` argument to say 700 meters and it should work.

**Comment by gboeing** [comment]
@ylzhouchris just checking back -- is this issue resolved?
