### ISSUE TITLE
Raise TypeError with networkx latest version ''2.0.dev_20170110215719'

### ISSUE THREAD

**Issue by philippschw** [gboeing/osmnx#23]
Hello Geoff !
I am currently testing osmnx to figure out how useful it is for my purposes. First of all, I would like to compliment you, it is a terrific library with great features, thank you for this work.
However, I would like to bring to your attention that it currently does not work together with networkx 2 and their changes to work to an iterator reporting API.
https://networkx.github.io/documentation/development/reference/release_2.0.html.

Example:
```
G5 = ox.graph_from_place('Manhattan, New York City, New York, USA')
G5_projected = ox.project_graph(G5)
fig, ax = ox.plot_graph(G5_projected)
```

> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-2-d90194f01ee8> in <module>()
>       1 # # create the street network within the region of Chittagong
> ----> 2 G5 = ox.graph_from_place('Chittagong, Chittagong, Bangladesh')
>       3 G5_projected = ox.project_graph(G5)
>       4 fig, ax = ox.plot_graph(G5_projected)
> 
> /home/philipp/anaconda3/envs/env_geotiff/lib/python2.7/site-packages/osmnx/osmnx.pyc in graph_from_place(query, network_type, simplify, retain_all, truncate_by_edge, name, which_result, buffer_dist, timeout, memory, max_query_area_size, clean_periphery)
>    1814     # create graph using this polygon(s) geometry
>    1815     G = graph_from_polygon(polygon, network_type=network_type, simplify=simplify, retain_all=retain_all, 
> -> 1816                            truncate_by_edge=truncate_by_edge, name=name, timeout=timeout, memory=memory, max_query_area_size=max_query_area_size, clean_periphery=clean_periphery)
>    1817 
>    1818     log('graph_from_place() returning graph with {:,} nodes and {:,} edges'.format(len(G.nodes()), len(G.edges())))
> 
> /home/philipp/anaconda3/envs/env_geotiff/lib/python2.7/site-packages/osmnx/osmnx.pyc in graph_from_polygon(polygon, network_type, simplify, retain_all, truncate_by_edge, name, timeout, memory, max_query_area_size, clean_periphery)
>    1740         # get the network data from OSM,  create the buffered graph, then truncate it to the buffered polygon
>    1741         response_jsons = osm_net_download(polygon=polygon_buffered, network_type=network_type, timeout=timeout, memory=memory, max_query_area_size=max_query_area_size)
> -> 1742         G_buffered = create_graph(response_jsons, name=name, retain_all=True, network_type=network_type)
>    1743         G_buffered = truncate_graph_polygon(G_buffered, polygon_buffered, retain_all=True, truncate_by_edge=truncate_by_edge)
>    1744 
> 
> /home/philipp/anaconda3/envs/env_geotiff/lib/python2.7/site-packages/osmnx/osmnx.pyc in create_graph(response_jsons, name, retain_all, network_type)
>    1499         G = get_largest_component(G)
>    1500 
> -> 1501     log('Created graph with {:,} nodes and {:,} edges in {:,.2f} seconds'.format(len(G.nodes()), len(G.edges()), time.time()-start_time))
>    1502 
>    1503     # add length (great circle distance between nodes) attribute to each edge to use as weight
> 
> TypeError: object of type 'generator' has no len()

**Comment by gboeing** [comment]
Right... they're moving to generators instead of lists. This should be a relatively easy fix and I'll aim to release it in the next minor release of fixes.

**Comment by gboeing** [comment]
Resolved by https://github.com/gboeing/osmnx/commit/53b51f705752a523110ce2b29a9a6dc01a00fc59

**Comment by gboeing** [comment]
OSMnx 0.2.2 is now available via pip and conda-forge, and works with networkx 2.0

**Comment by gboeing** [comment]
See also PR #84
