### ISSUE TITLE
save_graph_shapefile option to not include subdirectories

### ISSUE THREAD

**Issue by CordThomas** [gboeing/osmnx#230]
The save_graph_shapefile creates possibly unnecessary layers of organizational structure.   Other save methods I have seen use folder and file to specify a containing folder and then name the shapefile the name passed, e.g., save_shape ('/data', 'my_shape') would create a shapefile my_shape.shp in the /data directory.  

The current OSMnx implementation creates a folder my_shape, subfolders edges and nodes and then files within these subfolders named edges.shp and nodes.shp.

I propose a model where one could opt for a 'simple' save that would either create the files as /data/my_shape_edges.shp or /data/my_shape/edges.shp.   One could flag this request with an additional parameter to the save method.

**Comment by gboeing** [comment]
Thanks @CordThomas. The original reasoning behind the folder structure was to consolidate the collection of files (.shx, .dbf, .prj, etc, etc) that compose a "shapefile" into a single folder. As the nodes and edges each make up their own individual shapefile, I put them in separate subfolders. Thus, the path to the shapefile is the path to the subfolder containing its constituent parts.

For reference, the [ESRI spec](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf), and this snippet from [wikipedia](https://en.wikipedia.org/wiki/Shapefile#Overview):

> The term "shapefile" is quite common, but is misleading since the format consists of a collection of files with a common filename prefix, stored in the same directory. The three mandatory files have filename extensions .shp, .shx, and .dbf. The actual shapefile relates specifically to the .shp file, but alone is incomplete for distribution as the other supporting files are required. Legacy GIS software may expect that the filename prefix be limited to eight characters to conform to the DOS 8.3 filename convention, though modern software applications accept files with longer names.

Now, all that said, this is possibly unnecessary as OSMnx could save all shapefiles for a graph into a single folder, with consistent "node" and "edge" filenames. I can see an argument for both sides and am open to soliciting ideas on how this could make for easier, better, more intuitive, or more efficient workflows.

**Comment by gboeing** [comment]
If there's any other interest in this proposal, I'm open to someone opening a PR. Otherwise if not we can close this.

**Comment by CordThomas** [comment]
I have no objection to closing.   If i revisit, I'll create a PR.
