### ISSUE TITLE
Why the .prj is empty? saved from osmnx

### ISSUE THREAD

**Issue by littlestar565** [gboeing/osmnx#233]
I tried to use the following statement to get the street information of the latitude and longitude range. However, the saved file does not get the latitude and longitude information of each node. Why?

In fact, I successfully acquired the Manhattan area, and the street information of the entire Beijing area was successful.
<details>

![image](https://user-images.githubusercontent.com/28550249/50141043-68c2ba00-02e1-11e9-8741-0901797481a5.png)
![image](https://user-images.githubusercontent.com/28550249/50141065-7710d600-02e1-11e9-934d-de881b1eb2bb.png)

```python
# your code goes here
BJ_3 = ox.graph_from_bbox(40.03, 39.83, 116.46, 116.26, network_type='drive')
ox.save_graph_shapefile(BJ_3, folder='F:\enjoy\Beijing', filename='BJ3_drive_network')
```

**Comment by littlestar565** [comment]
I have read your guidance document, modified the code, and now I have solved this problem, but I still don’t understand what their differences are.

north, south, east, west = 40.03, 39.83, 116.46, 116.26
G3 = ox.graph_from_bbox(north, south, east, west, network_type='drive_service')

**Comment by gboeing** [comment]
I ran your original code:

```python
BJ_3 = ox.graph_from_bbox(40.03, 39.83, 116.46, 116.26, network_type='drive')
ox.save_graph_shapefile(BJ_3, folder='beijing', filename='BJ3_drive_network')
```

And the contents of the nodes.prj file look right:

```
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]
```
