### ISSUE TITLE
TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by yuvrajbokhre4** [gboeing/osmnx#237]
from tkinter import *
from tkinter.font import *
from Database import *
from tkinter import messagebox

class Insert_user:
    def call(self,event=None):
        self.top = Tk()
        self.top.title('Insert New User')
        self.width = self.top.winfo_screenwidth()
        self.height = self.top.winfo_screenheight()
        self.xposition = (self.width / 2) - 150
        self.yposition = (self.height / 2) - 100
        self.font = Font(self.top, size=12, weight='bold')
        self.top.geometry("%dx%d+%d+%d" % (self.width / 4, self.height / 5, self.xposition, self.yposition))

        ####Name
        self.name_label = Label(self.top, text='Username', font=self.font)
        self.name_entry = Entry(self.top)
        self.name_label.grid(row=0, column=0, sticky=W, padx=self.width / 32, pady=10)
        self.name_entry.grid(row=0, column=1, padx=self.width / 70, pady=10)

        ####Password
        self.password_label = Label(self.top, text='Password', font=self.font)
        self.password_entry = Entry(self.top)
        self.password_label.grid(row=1, column=0, sticky=W, padx=self.width / 32, pady=10)
        self.password_entry.grid(row=1, column=1, padx=self.width /70, pady=10)
        self.password_entry.configure(show='*')

        ###Summbit Button
        self.sumbit = Button(self.top, text='Submit')
        self.sumbit.bind("<Button-1>", self.sumbit_user)
        self.sumbit.grid(row=2, columnspan=2, padx=self.width / 32, pady=10)

        self.top.mainloop()

    def sumbit_user(self,event=None):
        try:
            self.db = User_info()
            self.name =self.name_entry.get()
            self.password=self.password_entry.get()
            if self.name=="" or self.password=="":
                self.message=messagebox.showwarning('Warning','Name and Password field would not be empty')
            else:
                self.db.insert_user(self.name,self.password)
                self.message=messagebox.showinfo('Message','Successfull')
                self.top.destroy()
        except sqlite3.IntegrityError:
            self.message = messagebox.showerror('Warning', 'Username Already Taken')
            self.top.destroy()

iu=Insert_user()
iu.call()

**Comment by gboeing** [comment]
This doesn't appear to be related to OSMnx. To open an issue, please completely fill out the new issue template.
