### ISSUE TITLE
Unable to control edge_alpha in ox.plot_graph

### ISSUE THREAD

**Issue by PFerrix** [gboeing/osmnx#239]
(what did I do, what did I expect to happen, and what actually happened)

Hello @gboeing, 

thanks for the amazing repo!

I am using osmnx and networkx to visualize bicycle displacements in a given city. Instead of using the plot_routes command, I created a dataframe with the edges hit by cyclists, so that I can change the node_color, node_size, edge_color and edge_linewidth in the Graph according to the number of hits.
Everything works fine with the above arguments (and with edge_alpha, let's say, equal to 0.6), but returns an "TypeError: alpha must be a float or None" when I try to control the edge_alpha.

The thing I don't understand is that both edge_linewidth and edge_alpha require a Float, and the 2 functions ev and ea are basically identical.

What am I missing here?

I am using MacOS 10.14, Python 3.7, and OSMnx 0.8.2

#### Code snippet that independently and completely reproduces the issue

```python

#creates 3 lists from the dataframe containing the hit edges and the number of hits
hu=list(df_counted["u_node"])
hv=list(df_counted["v_node"])
hc=list(df_counted["count"])

#for each edge, assign values to functions that control edge_color, edge_linewidth, and edge_alpha

for u,v,k in G.edges(keys=True, data=False):
    i = 0
    while i < n_unique_edges:
        if (u==hu[i] and v==hv[i]):
            ev[u,v] = 5 * (hc[i] / (hc[i] + 1))
            ec[u,v] = 'b'
            ea[u,v] = 0.5 * (hc[i] / (hc[i] + 1))
            i = n_unique_edges

        else:
            ev[u,v] = 0.5
            ec[u,v] = 'gray'
            ea[u,v] = 0.5 * (hc[i] / (hc[i] + 1))

        i = i + 1

fig, ax = ox.plot_graph(G, fig_height=7, node_color=nc, node_size=8, node_alpha=0.8, node_zorder=2,
edge_color=[ec[u,v] for u, v in G.edges(keys=False, data=False)], edge_linewidth=[ev[u,v] for u, v in G.edges(keys=False, data=False)],
edge_alpha=[ea[u,v] for u, v in G.edges(keys=False, data=False)])
```

**Comment by gboeing** [comment]
You are passing `plot_graph()` an `edge_alpha` value of type `list` when as you can see in the docstring, it requires type `float`: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.plot.plot_graph

You didn't post your full error traceback, so some of this is guesswork, but this error is probably being thrown in matplotlib as I believe matplotlib requires a scalar for the alpha argument (hence, `float` rather than `list`).

If you want varying opacities, you can presumably leave the `edge_alpha` argument alone and instead pass a list of `node_color` values specified as RGBA, where A is the alpha value: https://matplotlib.org/api/colors_api.html

**Comment by PFerrix** [comment]
Thanks,

I am surely going to try with RGBA! Still, I don't get why my code works fine with `edge_linewidth`: I am passing a `list`, while it should accept only a `float` (as `edge_alpha`).

Here goes my full error traceback, sorry!```

> 
> Traceback (most recent call last):
>   File "route4.py", line 118, in <module>
>     edge_alpha=[ea[u,v] for u, v in G.edges(keys=False, data=False)])
> 
>   File "/miniconda3/lib/python3.7/site-packages/osmnx/plot.py", line 392, in plot_graph
>     lc = LineCollection(lines, colors=edge_color, linewidths=edge_linewidth, alpha=edge_alpha, zorder=2)
>   File "/miniconda3/lib/python3.7/site-packages/matplotlib/collections.py", line 1252, in __init__
>     **kwargs)
>   File "/miniconda3/lib/python3.7/site-packages/matplotlib/collections.py", line 170, in __init__
>     self.update(kwargs)
>   File "/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 888, in update
>     for k, v in props.items()]
>   File "/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 888, in <listcomp>
>     for k, v in props.items()]
>   File "/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 882, in _update_property
>     return func(v)
>   File "/miniconda3/lib/python3.7/site-packages/matplotlib/collections.py", line 782, in set_alpha
>     raise TypeError('alpha must be a float or None')
> TypeError: alpha must be a float or None

```

**Comment by gboeing** [comment]
Downstream, matplotlib allows a list on linewidths but it does not allow a list of alphas.

**Comment by dcorreab** [comment]
> I was able to achieve my goal by passing the RGBA values to the `edge_color` and setting the `edge_alpha=None`, thanks again!

Hello PFerrix, I ave facing this same issue, could you share your fixed code, please? Thanks!

**Comment by gboeing** [comment]
See also #429 for details.
