### ISSUE TITLE
Include colourbar for elevation plots

### ISSUE THREAD

**Issue by shriv** [gboeing/osmnx#243]
I've been following the excellent tutorial [here](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/12-node-elevations-edge-grades.ipynb) on plotting the street gradients. However, there seems to be no option to set a colourbar with the grade values. Am I missing something? Or is this a new feature request? :-)

Thanks! 
Shrividya

**Comment by gboeing** [comment]
OSMnx has no built-in colorbar functionality. However, the plotting functions return a matplotlib figure, axis (as a tuple), which you can then use matplotlib directly to add a colorbar to them: https://matplotlib.org/api/colorbar_api.html
