### ISSUE TITLE
Gtk-Message: 22:26:30.504: Failed to load module "atk-bridge" Gtk-Message: 22:26:30.507: Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by bsnyh** [gboeing/osmnx#244]
If you're having trouble with OSMnx, first search the previously opened issues to see if the problem has already been noted. If not, fill in the template below:

#### Problem description (what did you do, what did you expect to happen, and what actually happened)
I installed the package under the OSMNX environment. I'm running a simple example with only two lines of code as the following: 

import osmnx as ox
ox.plot_graph(ox.graph_from_place('my city, my country'))

The matplotlib gives me a very nice picture. However, I got two error messages as the following. 

(OSMNX) devel@cc:~/Desktop$ python test.py
Gtk-Message: 21:56:37.278: Failed to load module "atk-bridge"
Gtk-Message: 21:56:37.281: Failed to load module "canberra-gtk-module"

I'm not sure why. Does it have something to do with my installation of the module osmnx? 

#### What operating system, architecture, Python version, and OSMnx version are you using?
I'm using Ubuntu. Python 3, the latest OSMnx. 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
# Paste the output of your Python packages and their versions here, between these two "details" tags
# output when I run conda list
# Name                    Version                   Build  Channel
altair                    2.3.0                 py37_1001    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
atk                       2.25.90           hf2eb9ee_1001    conda-forge
attrs                     18.2.0                     py_0    conda-forge
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12           h80bd089_1005    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.11.5          py37h9745a5d_1001    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.3.1           py37hb7f436b_1000    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fiona                     1.8.4           py37heb36068_1001    conda-forge
folium                    0.7.0                      py_0    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h3cfcefd_1004    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.3.2           py37heb36068_1002    conda-forge
gdk-pixbuf                2.36.12           h4f1c04b_1001    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geopy                     1.18.1                     py_0    conda-forge
geos                      3.7.0             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gobject-introspection     1.56.1          py37h9e29830_1001    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
gtk2                      2.24.31           h5baeb44_1000    conda-forge
harfbuzz                  1.9.0             he243708_1001    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.0.0a3               py37_1000    conda-forge
kealib                    1.4.10            he7154bc_1002    conda-forge
kiwisolver                1.0.1           py37h6bb024c_1002    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.3.2             h2a0c6be_1002    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libspatialindex           1.8.5             hf484d3e_1003    conda-forge
libspatialite             4.3.0a            h06a27ec_1025    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
markupsafe                1.1.0           py37h14c3975_1000    conda-forge
matplotlib                3.0.2           py37h8a2030e_1001    conda-forge
matplotlib-base           3.0.2           py37h167e16e_1001    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
numpy                     1.16.0          py37_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
osmnx                     0.8.2                      py_0    conda-forge
pandas                    0.23.4          py37h637b7d7_1000    conda-forge
pango                     1.40.14           hf0c64fd_1003    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       18.1                  py37_1000    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0            h2fc8fa2_1002    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
psycopg2                  2.7.6.1         py37hb7f436b_1000    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py37_1000    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.6           py37hc0953d3_1000    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pyrsistent                0.14.9          py37h14c3975_1000    conda-forge
pysal                     1.14.4.post2          py37_1001    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1             hd21baee_1000    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
qt                        5.6.2             hf516382_1011    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
rtree                     0.8.3                 py37_1000    conda-forge
scipy                     1.2.0           py37_blas_openblash1522bff_1200  [blas_openblas]  conda-forge
setuptools                40.6.3                   py37_0    conda-forge
shapely                   1.6.4           py37he696f1c_1001    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlalchemy                1.2.16          py37h14c3975_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py37h14c3975_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wheel                     0.32.3                   py37_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

output when I run pip list

Package         Version     
--------------- ------------
altair          2.3.0       
asn1crypto      0.24.0      
attrs           18.2.0      
branca          0.3.1       
certifi         2018.11.29  
cffi            1.11.5      
chardet         3.0.4       
Click           7.0         
click-plugins   1.0.4       
cligj           0.5.0       
cryptography    2.3.1       
cycler          0.10.0      
decorator       4.3.0       
descartes       1.1.0       
entrypoints     0.3         
Fiona           1.8.4       
folium          0.7.0       
GDAL            2.3.2       
geographiclib   1.49        
geopandas       0.4.0       
geopy           1.18.1      
idna            2.8         
Jinja2          2.10        
jsonschema      3.0.0a3     
kiwisolver      1.0.1       
MarkupSafe      1.1.0       
matplotlib      3.0.2       
munch           2.3.2       
networkx        2.2         
numpy           1.16.0      
osmnx           0.8.2       
pandas          0.23.4      
pip             18.1        
psycopg2        2.7.6.1     
pycparser       2.19        
pyOpenSSL       18.0.0      
pyparsing       2.3.1       
pyproj          1.9.6       
pyrsistent      0.14.9      
PySAL           1.14.4.post2
PySocks         1.6.8       
python-dateutil 2.7.5       
pytz            2018.9      
requests        2.21.0      
Rtree           0.8.3       
scipy           1.2.0       
setuptools      40.6.3      
Shapely         1.6.4.post2 
six             1.12.0      
SQLAlchemy      1.2.16      
toolz           0.9.0       
tornado         5.1.1       
urllib3         1.24.1      
vincent         0.4.4       
wheel           0.32.3      

</details>

#### Code snippet that independently and completely reproduces the issue

```python
# your code goes here
import osmnx as ox
ox.plot_graph(ox.graph_from_place('my city, my country'))
```

**Comment by gboeing** [comment]
This doesn't appear to be an issue with OSMnx, but rather with your installation of GTK. Did you try googling it and following the suggested steps, such as [this](https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed)?
