### ISSUE TITLE
Getting inconsistent fields in shapefiles returned from graph_from_bbox

### ISSUE THREAD

**Issue by CordThomas** [gboeing/osmnx#248]
I am doing analysis on street networks in Los Angeles County.   I am using the method graph_from_bbox and saving to a Shapefile.  Because of the extent of the data, I have to make 16 requests to cover all of LA County.   When i tried to merge the 16 Shapefiles together as one I noticed that they had inconsistent fields.  I loaded into QGIS and verified this.

Following is the relevant code I am using - am i doing something wrong?

    base_long = -117.4
    base_lat = 33.4
    step = .5

    for long in frange(0.0, 1.5, step):
      for lat in frange(0.0, 1.5, step):
        latmin = round(decimal.Decimal(base_lat) + decimal.Decimal(lat), 1)
        latmax = round(decimal.Decimal(latmin) + decimal.Decimal(step), 1)

        longmin = round(decimal.Decimal(base_long) - decimal.Decimal(long), 1)
        longmax = round(decimal.Decimal(longmin) - decimal.Decimal(step), 1)

        longlatkey = str(long) + '.' + str(lat)

        print("Processing {} with min and max lat and long {} {} {} {}".format(longlatkey,
                                                                               str(latmax), str(latmin),
                                                                               str(longmin), str(longmax)))

        try:

          # Pull only drivable highways, primary and residential streets based on
          # https://wiki.openstreetmap.org/wiki/Key:highway
          greater_la_streets_box = ox.graph_from_bbox(latmax, latmin, longmin, longmax,
                                    network_type='drive', simplify=True,
                                    timeout=3600,
                                    infrastructure='way["highway"~"motorway|trunk|primary|secondary|' \
                                    'residential|motorway_link|trunk_link|primary_link"]')

          G_projected = ox.project_graph(greater_la_streets_box)

          print ("   Saving to {}".format(config['SPATIAL']['CA_Street_Centerlines_OSM'] + longlatkey))

          ox.save_graph_shapefile(G_projected, filename=config['SPATIAL']['CA_Street_Centerlines_OSM'] + longlatkey,
                             folder=config['SPATIAL']['BASE_STREET_PATH'])

        except ox.core.EmptyOverpassResponse:
          print("    No features found in request")

        except Exception as ex:
          print("    Exception happened of type {} with args {}".format(type(ex), ex.args))

**Comment by gboeing** [comment]
Specifically which fields are inconsistent?

**Comment by CordThomas** [comment]
Sorry, thought i included the error - i am using Fiona to merge the 16 tiles.  On attempting to merge the first two, i get the error below.  As I mentioned, i loaded the Shapefiles in QGIS and confirmed these inconsistencies from the downloaded OSM data.  

ValueError: Record does not match collection schema: odict_keys(['access', 'bridge', 'from', 'highway', 'junction', 'key', 'lanes', 'length', 'maxspeed', 'name', 'oneway', 'osmid', 'ref', 'service', 'to', 'tunnel', 'width']) != ['bridge', 'access', 'tunnel', 'length', 'from', 'maxspeed', 'lanes', 'osmid', 'key', 'junction', 'landuse', 'highway', 'name', 'to', 'ref', 'oneway', 'width']

From there you can see that the first schema has **service** that the second does not and the second has **landuse** that the first does not.

'access' | 'access'
'bridge' | 'bridge'
'from' | 'from'
'highway' | 'highway'
'junction' | 'junction'
'key' | 'key'
'lanes' | '**landuse**'
'length' | 'lanes'
'maxspeed' | 'length'
'name' | 'maxspeed'
'oneway' | 'name'
'osmid' | 'oneway'
'ref' | 'osmid'
'**service**' | 'ref'
'to' | 'to'
'tunnel' | 'tunnel'
'width' | 'width'

**Comment by gboeing** [comment]
Hi @CordThomas:

> Because of the extent of the data, I have to make 16 requests to cover all of LA County.

Note that OSMnx does this automatically for you. If you just query using the bounding box of LA county, or the polygon of LA county's borders, OSMnx will subdivide it into multiple queries if it has to in order to stay within the API's memory limits:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
G = ox.graph_from_place('Los Angeles County', network_type='drive')
```

Regarding your code snippet, I can't reproduce it because it's not a standalone MWE and I can't guess what is happening elsewhere in your script. If you can provide one, I can check it out further. But in general, it's easiest to let OSMnx handle the requests subdivision and everything should be consistent.

**Comment by CordThomas** [comment]
Thanks for the tip; I noticed that a while ago and forgot about it.

If you want, here is the full script - you would just need to replace the config[] sections with local file paths...   But only if you were curious.  I am going to shift to using the caching method.

https://github.com/CordThomas/commute-justice-analysis/blob/master/network/get_osm_data.py

**Comment by CordThomas** [comment]
I have updated my code to use your suggested approach.   It broke the request into 20.   It makes good progress but then the process is killed - think something is hitting the limits of my docker container...

...
Creating networkx graph from downloaded OSM data...
Graph was not connected, retained only the largest weakly connected component (1,252,986 of 1,465,714 total nodes) in 126.12 seconds
Created graph with 1,252,986 nodes and 2,423,357 edges in 248.20 seconds
Added edge lengths to graph in 35.50 seconds
Truncated graph by bounding box in 42.08 seconds
Begin topologically simplifying the graph...
Killed

**Comment by gboeing** [comment]
Probably need to provision more memory for your container.

**Comment by gboeing** [comment]
@CordThomas ready to close this issue?

**Comment by CordThomas** [comment]
Yes, please close.  As feedback or for future users, I am now exactly 48 hours into running my script that has spent most of this time processing the simplification "Begin topologically simplifying the graph...".  I am on a 2016 MBP (2.7 GHz Intel Core i7) in docker with 4 CPU and 10 GB memory provisioned.   This is for a 2 degree x 2 degree bounding box in LA County.

**Comment by CordThomas** [comment]
Definitely something different then.  I restarted the process and it's now
been running for over 2 hours.

Is it possible because I am pulling a lot more infrastructure?

Again, my code is
https://github.com/CordThomas/commute-justice-analysis/blob/master/network/get_osm_data.py
- updated

**Comment by CordThomas** [comment]
So, i did not know that python/docker would not throw an out of memory error.  I had provisioned my docker container with 6 GB which I had thought would be enough.   On adding some additional logging, I noticed that the networkx graph copy happens 3 times and doesn't seem to return memory.   So, in the 3rd copy, it froze at using 5.99 GB of memory.  Increasing to 8 GB resolved the problem.

**Comment by gboeing** [comment]
Good catch on copying/memory issue. Want to open a new issue to document it?
