### ISSUE TITLE
Using graph_from_bbox with the simplify option seems to consume a lot of memory

### ISSUE THREAD

**Issue by CordThomas** [gboeing/osmnx#250]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

I was running the graph_from_bbox method to download a superset of Los Angeles County streets. I wanted the network simplified.    The network downloads over 2,000,000 edges.  The process was freezing midway through in a docker container with 6 GB RAM.   After digging into the code, I noticed that the networkx graph is copied 3 times and somewhere along the way it seems memory is not freed.   After increasing my container's memory to 8 GB the process succeeded.

#### What operating system, architecture, Python version, and OSMnx version are you using?

I am on Mac OSX 10.13.6, Docker engine 18.09, Python 3.6.7, OSMnx 0.8.2 and Networkx 2.2

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
attrs               18.2.0
certifi             2018.11.29
chardet             3.0.4
Click               7.0
click-plugins       1.0.4
cligj               0.5.0
cryptography        2.1.4
cycler              0.10.0
decorator           4.3.0
descartes           1.1.0
Fiona               1.8.3
GDAL                2.2.2
geopandas           0.4.0
idna                2.6
keyring             10.6.0
keyrings.alt        3.0
kiwisolver          1.0.1
matplotlib          3.0.2
munch               2.3.2
networkx            2.2
numpy               1.15.4
olefile             0.45.1
osmnx               0.8.2
pandas              0.23.4
Pillow              5.1.0
pip                 18.1
psycopg2            2.7.6.1
pycairo             1.16.2
pycrypto            2.6.1
pygobject           3.26.1
pyparsing           2.3.0
pyproj              1.9.5.1
python-apt          1.6.3
python-dateutil     2.7.5
pytz                2018.7
pyxdg               0.25
requests            2.20.1
Rtree               0.8.3
scipy               1.1.0
SecretStorage       2.3.1
setuptools          39.0.1
Shapely             1.6.4.post2
six                 1.11.0
SQLAlchemy          1.2.14
unattended-upgrades 0.1
urllib3             1.24.1
virtualenv          15.1.0
wheel               0.30.0
</details>

#### Code snippet that independently and completely reproduces the issue

Code is here:
https://github.com/CordThomas/commute-justice-analysis/blob/master/network/get_osm_data.py

**Comment by CordThomas** [comment]
I will track those call sources down again and report here.

**Comment by CordThomas** [comment]
Finally got around to it.   I used traceback to find all calls to G.copy() in multigraph.py.   

G.copy() is called the following times for the method graph_from_bbox() with simplify=True:
	core.py line 965 in truncate_graph_bbox()
	simplify.py line 232 in simplify_graph()
	core.py line 965 in truncate_graph_bbox()

It seems the last one is the one that caused me the problem (did not have time to garbage clean memory before carrying on to next step thus adding to the memory footprint more than i would have expected).

**Comment by gboeing** [comment]
I'm going to close this for now because from my perusal of the codebase it looks like these are necessary at this point. Garbage collection should free up locally-used memory after each function exits.
