### ISSUE TITLE
ImportError: libkea.so.1.4.7: cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by bsnyh** [gboeing/osmnx#252]
You probably have already saw this from stackoverflow. But I would really appreciate it if you can take a look of this again. I know how to run it using coda virtual environment. But as I plan to call this osmnx module from julia. The virtual environment created by conda can not be used. 

I am installing package OSMnx following this link: https://geoffboeing.com/2016/11/osmnx-python-street-networks/ on Linux using conda install -c conda-forge osmnx.
It works, but with a warning like this:

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.5.12

Please update conda by running

    $ conda update -n base -c defaults conda

So I update the conda, and re-install the OSMnx package again in my computer. After that, I start my Python shell and entered import osmnx to test it. Then I got the following error.

Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:33:04) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import osmnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/devel/anaconda3/lib/python3.7/site-packages/osmnx/__init__.py", line 9, in <module>
    from .buildings import *
  File "/home/devel/anaconda3/lib/python3.7/site-packages/osmnx/buildings.py", line 9, in <module>
    import geopandas as gpd
  File "/home/devel/anaconda3/lib/python3.7/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/home/devel/anaconda3/lib/python3.7/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/home/devel/anaconda3/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/devel/anaconda3/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory

After searching, I found this link: https://github.com/darribas/contextily/issues/42 But it's not easy for me to understand what's going on. Could anyone help me out please?

**Comment by gboeing** [comment]
Did you install OSMnx in a virtual environment? Per [the documentation](https://osmnx.readthedocs.io/en/stable/#installation):

> If you have any trouble with the installation, try installing OSMnx in a new, clean virtual environment using conda and conda-forge:
> 
> ```
> conda create --override-channels -c conda-forge -n OSMNX python=3 osmnx
> source activate OSMNX
> ```

**Comment by gboeing** [comment]
@bsnyh this appears to be an issue with the conda-forge installation of fiona. Would you mind opening an issue in that feedstock: https://github.com/conda-forge/fiona-feedstock/issues

**Comment by saveriogzz** [comment]
Good morning,
I have the exact same error! Did you maybe solve it?

Thank you

**Comment by gboeing** [comment]
@saveriogzz can you provide the specific steps you tried in installation? Also can you provide the output of `conda info` and `conda list`?

**Comment by saveriogzz** [comment]
Good evening @gboeing, actually on Mac High Sierra the errors I receive are quite different.
I'm attaching the standard outputs as reference. I'm not much familiar with the usage of different environments and installing packages.. I do apologize!

Thank you very much!

[conda_info.txt](https://github.com/gboeing/osmnx/files/2980867/conda_info.txt)
[conda_list.txt](https://github.com/gboeing/osmnx/files/2980868/conda_list.txt)

**Comment by gboeing** [comment]
@saveriogzz per the [OSMnx docs](https://osmnx.readthedocs.io/en/latest/#installation) try
```
conda create -n ox -c conda-forge --strict-channel-priority --yes python=3 osmnx
conda activate ox
```

**Comment by saveriogzz** [comment]
hi @gboeing, i tried but now the error is:

In [1]: import osmnx                                                            
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-771da528bb5b> in <module>
----> 1 import osmnx

/anaconda3/lib/python3.7/site-packages/osmnx/__init__.py in <module>
      7 ################################################################################
      8 
----> 9 from .buildings import *
     10 from .core import *
     11 from .elevation import *

/anaconda3/lib/python3.7/site-packages/osmnx/buildings.py in <module>
      6 ################################################################################
      7 
----> 8 import geopandas as gpd
      9 import matplotlib.pyplot as plt
     10 import time

/anaconda3/lib/python3.7/site-packages/geopandas/__init__.py in <module>
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

/anaconda3/lib/python3.7/site-packages/geopandas/io/file.py in <module>
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 import six

/anaconda3/lib/python3.7/site-packages/fiona/__init__.py in <module>
     81     os.environ["PATH"] = os.environ["PATH"] + ";" + libdir
     82 
---> 83 from fiona.collection import BytesCollection, Collection
     84 from fiona.drvsupport import supported_drivers
     85 from fiona.env import ensure_env_with_credentials, Env

/anaconda3/lib/python3.7/site-packages/fiona/collection.py in <module>
      7 
      8 from fiona import compat, vfs
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libkea.1.4.7.dylib
  Referenced from: /anaconda3/lib/libgdal.20.dylib
  Reason: image not found

**Comment by gboeing** [comment]
@saveriogzz it does not look like you're working in the virtual environment here. For example, the traceback shows that the path to OSMnx is `/anaconda3/lib/python3.7/site-packages/osmnx/init.py` which is the root/base environment, rather than the new environment named `ox` which was created when you ran `conda create -n ox -c conda-forge --strict-channel-priority --yes python=3 osmnx`.

Try to run:
```
conda activate ox
python -c "import osmnx; print(osmnx.__version__)"
```

If that runs successfully, then OSMnx is installed ok and can be imported/run ok.

If you are working in a certain interpreter/IDE such as IPython or Jupyter Lab, make sure to [install it](https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments) in your virtual environment as well (including any kernels as needed).

**Comment by annamuji** [comment]
Dear @gboeing 
I am facing the same problem when trying to use geopandas in spyder.

[condainfo.txt](https://github.com/gboeing/osmnx/files/3402339/condainfo.txt)
[condalist.txt](https://github.com/gboeing/osmnx/files/3402340/condalist.txt)

**Comment by gboeing** [comment]
@annamuji your environment has a jumble of packages from defaults and conda-forge. You should avoid this: https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels

See the installation instructions for how to install OSMnx in a new, clean, conda env: https://osmnx.readthedocs.io/en/stable/#installation
