### ISSUE TITLE
KeyError: 'geometry',  ox.footprints_from_point

### ISSUE THREAD

**Issue by Hartry** [gboeing/osmnx#256]
Hi :-) 
 I m trying to get the node of this coordinate 

add_kard  : (2.379921, 48.9141959)

d = ox.footprints_from_point(add_kard ,distance=10)

I get this error.. 
KeyError: 'geometry', I do not understand  why

**Comment by gboeing** [comment]
You are querying for a point in the middle of the Indian Ocean because you have represented your point as (longitude, latitude) rather than (latitude, longitude).

**Comment by YoungDev-R** [comment]
If you flip the coordinates, the problem persists.

**Comment by gboeing** [comment]
@YoungDev-R it seems to work fine:
```python
import osmnx as ox
ox.config(log_console=True, use_cache=True)
point = (48.9141959, 2.379921)
fp = ox.footprints_from_point(point, distance=1000)
fp.shape #returns (5701, 57)
```
