### ISSUE TITLE
export to osm xml or .pbf?

### ISSUE THREAD

**Issue by mxndrwgrdnr** [gboeing/osmnx#257]
Hey @gboeing, any plans to add support for exporting an osmnx network back out to an OSM-based format? Many network modeling platforms expect an OSM-formatted network, so it would be great to be able to load a network with osmnx, use osmnx's geometry simplification capabilities, for example, and export back out to an OSM-supported format to use with a different platform. Do you have any suggestions for accomplishing this kind of workflow in the meantime?

**Comment by gboeing** [comment]
No current plans to add functionality to export back to OSM XML. However, if you end up putting this sort of workflow together for your own purposes, a PR would certainly be welcome. Regarding suggestions, you might want to check out the class here: https://github.com/gboeing/osmnx/blob/master/osmnx/utils.py#L1165

**Comment by mxndrwgrdnr** [comment]
OK cool. I'm gonna take a stab at something in the couple days for my own use and I'll submit a PR if it seems to work reasonably well.

**Comment by gboeing** [comment]
closed by #259
