### ISSUE TITLE
Install OSMnx in a new clean virtual env or run it in the Docker container

### ISSUE THREAD

**Issue by gboeing** [gboeing/osmnx#258]
It can be tricky to install OSMnx sometimes. Although OSMnx itself is pure python, several of its dependencies have C extensions that require compilation. You can usually avoid any issues by installing OSMnx into a new clean environment with conda-forge:

```bash
conda create --override-channels -c conda-forge -n OSMNX python=3 osmnx
source activate OSMNX
```

If you don't want to install OSMnx locally, you can instead now run it directly from this [docker container](https://hub.docker.com/r/gboeing/osmnx).

**Comment by gboeing** [comment]
cc #251 #203 #197 #191 #180 #118 #110 #92 #45 #32 #28 #27 #25 #13 #7

**Comment by mwinkenb** [comment]
Hi Geoff, I hope all is well. I'm just trying to get ready for this year's iteration of my class and would like to create a clean new virtual environment using conda. When trying to install OSMnx in that environment, it keeps failing:
`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
`
Interestingly, installing OSMNx in the base environment works. 
Any recommendations?

Thank you!
Matthias

**Comment by gboeing** [comment]
Hi @mwinkenb  Did you use the conda-forge channel to install this, per the instructions? If so, please open an issue at its feedstock https://github.com/conda-forge/osmnx-feedstock with the detailed steps you ran and the output they produced, including the error you're getting.
