### ISSUE TITLE
Feature Request - RTree Implementation of Nearest Edge

### ISSUE THREAD

**Issue by juliamgomes** [gboeing/osmnx#261]
I would like to create a more efficient implementation of the function `osmnx.utils.get_nearest_edge`, which currently uses the following algorithm:

def get_nearest_edge(G, point):
    """
    Return the nearest edge to a pair of coordinates. Pass in a graph and a tuple
    with the coordinates. We first get all the edges in the graph. Secondly we compute
    the euclidean distance from the coordinates to the segments determined by each edge.
    The last step is to sort the edge segments in ascending order based on the distance
    from the coordinates to the edge. In the end, the first element in the list of edges
    will be the closest edge that we will return as a tuple containing the shapely
    geometry and the u, v nodes.
    Parameters
    ----------
    G : networkx multidigraph
    point : tuple
        The (lat, lng) or (y, x) point for which we will find the nearest edge
        in the graph
    Returns
    -------
    closest_edge_to_point : tuple (shapely.geometry, u, v)
        A geometry object representing the segment and the coordinates of the two
        nodes that determine the edge section, u and v, the OSM ids of the nodes.
    """

When a user has a large graph and must repeatedly query this graph for the nearest edge, it is time-consuming to calculate the distance between the point and every edge of the graph. A faster method would be to generate and cache a rtree corresponding to the graph, then optionally pass it in as an argument to the `get_nearest_edge()` function at query time. 

My feature proposal is the following:
1) Create a GraphRTree class that can convert a graph into an rtree data structure and store the relevant information
2) Either add an rtree as an optional argument in the get_nearest_edge() function, or have an addition get_nearest_edge() method under the GraphRTree class

I implemented this for a different project and found that this implementation allows the query to be completed in just a few milliseconds, even for very large graphs.

**Comment by gboeing** [comment]
@juliamgomes thanks, this might be a good idea. Note that the `get_nearest_edges()` function already [uses trees](https://github.com/gboeing/osmnx/blob/master/osmnx/utils.py#L621) (optionally either a balltree or a kdtree) for faster search. One of those index data structures might work better than an rtree. But more broadly, when you say:

> When a user has a large graph and must repeatedly query this graph for the nearest edge

The `get_nearest_edges()` function already exists to allow for multiple such queries using a single tree data structure to accelerate.

**Comment by juliamgomes** [comment]
Thanks for the quick response! Does `get_nearest_edges()` work for real-time systems? It seemed limited in the sense that I would have to provide a list of coordinates in advance, and if I were to give the function one point at a time, then it would reconstruct the kdtree every time I call it. I was hoping for a system that would instead store the tree once and later be able to quickly find the nearest edge from a graph as a human or robot dynamically moves through the space. If you're open to the idea and it would be helpful to others, I'll send in a PR. And thanks so much for providing this resource!

**Comment by gboeing** [comment]
@juliamgomes good point. `get_nearest_edges` constructs a new tree each time it's called. It might be useful to generalize this existing function to construct a tree if one doesn't already exist, then cache it somewhere for future calls to reuse?

**Comment by adwayish** [comment]
@gboeing yes, I think separating index creation from `get_nearest_edge` is a good idea, I also agree with @juliamgomes idea of having a class for spatial graphs. I think  the approach that makes more sense to me is having a `SpatialGraph (nx.MultiDiGraph)` class for nearest neighbour queries, and it would be responsible for creating and caching the index. Regarding which type of index to use, the implementation could be flexible to support different kind of structures but I would like to point out that the current implementation with kdtree/balltree is brilliant and extremely fast. I was able to query 30M points in under ~5 seconds (thanks @samuelduchesne ).

**Comment by juliamgomes** [comment]
@gboeing @adwayish I totally agree, it’s better to use the tree structures that are already provided. Based on the feedback above, I would propose the following modifications:

- Add a `construct_spatial_index` function that can convert a graph to a tree structure of the user’s choice (eg kdtree, balltree, rtree). Developers can choose how to cache or store this tree independently
- Add optional `method` / `spatial_index` parameters to the singular `get_nearest_edge` function, so that developers have the option to pass in a stored tree for queries regarding a single GPS coordinate. 
- Move the tree search implemented in `get_nearest_edges` to the `get_nearest_edge` function. Developers can still call `get_nearest_edges` with the  `method` set to `kdtree` or `balltree`, in which case the `get_nearest_edges` function would either construct a tree internally or use an optional tree argument to call the `get_nearest_edge` function on each coordinate with the specified `method`

Lmk your thoughts!

**Comment by gboeing** [comment]
@juliamgomes I think this is a good idea.

**Comment by PedrosWits** [comment]
> I think the approach that makes more sense to me (based on my use case) is having a `SpatialGraph (nx.MultiDiGraph)` class for edge/nodes nearest neighbour queries, and it would be responsible for creating and caching the index.

I think that `SpatialGraph (nx.MultiDiGraph)` is a great idea! It will require considerable refactoring, but I think it's worth it in the long run.

> @gboeing @adwayish I totally agree, it’s better to use the tree structures that are already provided. Based on the feedback above, I would propose the following modifications:

In the meantime, I agree with @juliamgomes . It's worth pointing out that it's up to the user to build the index (using `construct_spatial_index` or the sklearn API), store in a variable and pass it to `get_nearest_edges`. Naturally, advanced users will be more comfortable with this than beginners. But, I think that it would be straightforward to come up with a PR that offers this functionality.

Alternatively, we could also think about doing this in the background, effectively moving towards `SpatialGraph (nx.MultiDiGraph)` . The index could be automatically created when the graph is retrieved from address, place, etc; and stored internally. However, the index can become obsolete if new nodes/edges are added to the graph (though not very common) or a projection occurs. We would have to detect those changes and update the index accordingly.

So, it boils down to whether we want to manage the index internally or offload that responsibility to the user. Maybe in a first instance, we're okay with passing that responsibility to the user? And later we can think about how to do it ourselves?

**Comment by gboeing** [comment]
Closing this for now (as #284 was closed) but I'm open to this being re-opened and developed in the future.
