### ISSUE TITLE
Connectivity error (graph from polygon)

### ISSUE THREAD

**Issue by JulienTh** [gboeing/osmnx#262]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Hi,
I would like to use OSMnx to automatically get the graph associated with satellite maps that I download from USGs (https://earthexplorer.usgs.gov/). I’ve downloaded orthoimages with a shapefile from which I extract the coordinate of a polygon.  After that, I’m projecting it on WGS 84 (espg:4326) and round the coordinate with a 6-digit precision.
In the end I try to get the graph from the polygon but I get this error: 
NetworkXPointlessConcept: Connectivity is undefined for the null graph.

#### What operating system, architecture, Python version, and OSMnx version are you using?
I'm on Windows 7 Pro. I'm using python 3.7.1 and conda 4.6.7. I'm using OSMnx 0.9.
#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
# packages in environment at C:\Users\j.theron\AppData\Local\Continuum\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
altair                    2.4.1                    py37_0    conda-forge
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.6                    py37_0  
anaconda-project          0.8.2                    py37_0  
asn1crypto                0.24.0                   py37_0  
astroid                   2.1.0                    py37_0  
astropy                   3.1              py37he774522_0  
atomicwrites              1.2.1                    py37_0  
attrs                     18.2.0           py37h28b3542_0  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                      py37_1  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.6.3                    py37_0  
bitarray                  0.8.3            py37hfa6e2cd_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
blaze                     0.11.3                   py37_0  
bleach                    3.0.2                    py37_0  
blosc                     1.14.4               he51fdeb_0  
bokeh                     1.0.2                    py37_0  
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h452e1ab_1  
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.6                hfa6e2cd_5  
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py37_0  
cffi                      1.11.5           py37h74b6da3_1  
chardet                   3.0.4                    py37_1  
click                     7.0                      py37_0  
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.6.1                    py37_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.1                    py37_0  
comtypes                  1.1.7                    py37_0  
conda                     4.6.7                    py37_0  
conda-build               3.17.6                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
console_shortcut          0.1.1                         3  
contextlib2               0.5.5                    py37_0  
cryptography              2.5              py37h74b6da3_1    conda-forge
curl                      7.63.0            h2a8f88b_1000  
cycler                    0.10.0                   py37_0  
cython                    0.29.2           py37ha925a31_0  
cytoolz                   0.9.0.1          py37hfa6e2cd_1  
dask                      1.0.0                    py37_0  
dask-core                 1.0.0                    py37_0  
datashape                 0.5.4                    py37_1  
decorator                 4.3.0                    py37_0  
defusedxml                0.5.0                    py37_1  
descartes                 1.1.0                      py_2    conda-forge
distributed               1.25.1                   py37_0  
docutils                  0.14                     py37_0  
entrypoints               0.2.3                    py37_2  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.5             he025d50_1002    conda-forge
fastcache                 1.0.2            py37hfa6e2cd_2  
filelock                  3.0.10                   py37_0  
fiona                     1.8.4           py37h0d92105_1001    conda-forge
flask                     1.0.2                    py37_1  
flask-cors                3.0.7                    py37_0  
folium                    0.8.0                      py_0    conda-forge
freetype                  2.9.1                ha9979f8_1  
freexl                    1.0.5             hd288d7e_1002    conda-forge
future                    0.17.1                   py37_0  
gdal                      2.3.2            py37h16ee443_0  
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geopy                     1.18.1                     py_0    conda-forge
geos                      3.6.2             he025d50_1004    conda-forge
get_terminal_size         1.0.0                h38e98db_0  
gevent                    1.3.7            py37he774522_1  
glob2                     0.6                      py37_1  
greenlet                  0.4.15           py37hfa6e2cd_0  
h5py                      2.8.0            py37h3bdd7fb_2  
hdf4                      4.2.13               h712560f_2  
hdf5                      1.10.2               hac2f561_1  
heapdict                  1.0.0                    py37_2  
html5lib                  1.0.1                    py37_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
idna                      2.8                      py37_0  
imageio                   2.4.1                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        0.6                      py37_0  
intel-openmp              2019.1                      144  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.2.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
isort                     4.3.4                    py37_0  
itsdangerous              1.1.0                    py37_0  
jdcal                     1.4                      py37_0  
jedi                      0.13.2                   py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   hb83a4c4_2  
jsonschema                2.6.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.3                   py37_0  
jupyterlab_server         0.2.0                    py37_0  
kealib                    1.4.9                h4380d0d_2    conda-forge
keyring                   17.0.0                   py37_0  
kiwisolver                1.0.1            py37h6538335_0  
krb5                      1.16.2            h038dc86_1000    conda-forge
lazy-object-proxy         1.3.1            py37hfa6e2cd_2  
libarchive                3.3.3                h798a506_0  
libcurl                   7.63.0            h2a8f88b_1000  
libgdal                   2.3.2                hcd84ac5_0  
libiconv                  1.15                 h1df5818_7  
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
libnetcdf                 4.6.1                h183b1a9_3    conda-forge
libopencv                 3.4.1                h875b8b8_3  
libpng                    1.6.35               h2a8f88b_0  
libpq                     10.6              h4c6b53d_1000    conda-forge
libsodium                 1.0.16               h9d3ae62_0  
libspatialindex           1.8.5             he025d50_1003    conda-forge
libspatialite             4.3.0a              hefca060_19  
libssh2                   1.8.0             hc4dcbb0_1003    conda-forge
libtiff                   4.0.9                h36446d0_2  
libxml2                   2.9.8                hadb2253_1  
libxslt                   1.1.32               hf6f1972_0  
llvmlite                  0.26.0           py37ha925a31_0  
locket                    0.2.0                    py37_1  
lxml                      4.2.5            py37hef2cd61_0  
lz4-c                     1.8.1.2              h2fa13f4_0  
lzo                       2.10                 h6df0209_2  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markupsafe                1.1.0            py37he774522_0  
matplotlib                3.0.2            py37hc8f65d3_0  
mccabe                    0.6.1                    py37_1  
menuinst                  1.4.14           py37hfa6e2cd_0  
mistune                   0.8.4            py37he774522_0  
mkl                       2019.1                      144  
mkl-service               1.1.2            py37hb782905_5  
mkl_fft                   1.0.6            py37h6288b17_0  
mkl_random                1.0.2            py37h343c172_0  
more-itertools            4.3.0                    py37_0  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.5.6            py37he980bc4_1  
msys2-conda-epoch         20160418                      1  
multipledispatch          0.6.0                    py37_0  
munch                     2.3.2                      py_0    conda-forge
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.4.0                    py37_1  
nbformat                  4.4.0                    py37_0  
networkx                  2.2                      py37_1  
nltk                      3.4                      py37_1  
nose                      1.3.7                    py37_2  
notebook                  5.7.4                    py37_0  
numba                     0.41.0           py37hf9181ef_0  
numexpr                   2.6.8            py37hdce8814_0  
numpy                     1.15.4           py37h19fb1c0_0  
numpy-base                1.15.4           py37hc3f5095_0  
numpydoc                  0.8.0                    py37_0  
odo                       0.5.1                    py37_0  
olefile                   0.46                     py37_0  
opencv                    3.4.1            py37h6fd60c2_3  
openpyxl                  2.5.12                   py37_0  
openssl                   1.0.2p               hfa6e2cd_0  
osmnx                     0.9                        py_0    conda-forge
packaging                 18.0                     py37_0  
palettable                3.1.1                      py_0    conda-forge
pandas                    0.23.4           py37h830ac7b_0  
pandoc                    1.19.2.1             hb2460c7_1  
pandocfilters             1.4.2                    py37_1  
parso                     0.3.1                    py37_0  
partd                     0.3.9                    py37_0  
path.py                   11.5.0                   py37_0  
pathlib2                  2.3.3                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.42                 hd6b2f15_0  
pep8                      1.7.1                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.3.0            py37hdc69c19_0  
pip                       18.1                     py37_0  
pkginfo                   1.4.2                    py37_1  
pluggy                    0.8.0                    py37_0  
ply                       3.11                     py37_0  
proj4                     5.1.0             hfa6e2cd_1002    conda-forge
prometheus_client         0.5.0                    py37_0  
prompt_toolkit            2.0.7                    py37_0  
psutil                    5.4.8            py37he774522_0  
psycopg2                  2.7.7            py37h74b6da3_0    conda-forge
py                        1.7.0                    py37_0  
py-opencv                 3.4.1            py37h1b0d24d_3  
pycodestyle               2.4.0                    py37_0  
pycosat                   0.6.3            py37hfa6e2cd_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37hfa6e2cd_9  
pycurl                    7.43.0.2         py37h74b6da3_0  
pyflakes                  2.0.0                    py37_0  
pygments                  2.3.1                    py37_0  
pylint                    2.2.2                    py37_0  
pyodbc                    4.0.25           py37ha925a31_0  
pyopenssl                 18.0.0                   py37_0  
pyparsing                 2.3.0                    py37_0  
pyproj                    1.9.5.1          py37hb98d9bb_1  
pyqt                      5.9.2            py37h6538335_2  
pysal                     2.0.0                      py_0    conda-forge
pysocks                   1.6.8                    py37_0  
pytables                  3.4.4            py37he6f6034_0  
pytest                    4.0.2                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.2.0                    py37_0  
pytest-openfiles          0.3.1                    py37_0  
pytest-remotedata         0.3.1                    py37_0  
python                    3.7.1             h9460c21_1002    conda-forge
python-dateutil           2.7.5                    py37_0  
python-libarchive-c       2.8                      py37_6  
pytz                      2018.7                   py37_0  
pywavelets                1.0.1            py37h8c2d366_0  
pywin32                   223              py37hfa6e2cd_1  
pywinpty                  0.5.5                 py37_1000  
pyyaml                    3.13             py37hfa6e2cd_0  
pyzmq                     17.1.2           py37hfa6e2cd_0  
qt                        5.9.6            vc14h1e9a669_2  
qtawesome                 0.5.3                    py37_0  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.5.2                    py37_0  
requests                  2.21.0                   py37_0  
rope                      0.11.0                   py37_0  
rtree                     0.8.3                 py37_1000    conda-forge
ruamel_yaml               0.15.46          py37hfa6e2cd_0  
scikit-image              0.14.1           py37ha925a31_0  
scikit-learn              0.20.1           py37h343c172_0  
scipy                     1.1.0            py37h29ff71c_2  
seaborn                   0.9.0                    py37_0  
send2trash                1.5.0                    py37_0  
setuptools                40.6.3                   py37_0  
shapely                   1.6.4           py37hc90234e_1000    conda-forge
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37h6538335_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                h777316e_3  
snowballstemmer           1.2.1                    py37_0  
sortedcollections         1.0.1                    py37_0  
sortedcontainers          2.1.0                    py37_0  
sphinx                    1.8.2                    py37_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-websupport  1.1.0                    py37_1  
spyder                    3.3.2                    py37_0  
spyder-kernels            0.3.0                    py37_0  
sqlalchemy                1.2.15           py37he774522_0  
sqlite                    3.26.0               he774522_0  
statsmodels               0.9.0            py37h452e1ab_0  
sympy                     1.3                      py37_0  
tblib                     1.3.2                    py37_0  
terminado                 0.8.1                    py37_1  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.9.0                    py37_0  
tornado                   5.1.1            py37hfa6e2cd_0  
tqdm                      4.28.1           py37h28b3542_0  
traitlets                 4.3.2                    py37_0  
unicodecsv                0.14.1                   py37_0  
urllib3                   1.24.1                   py37_0  
vc                        14.1                 h0510ff6_4  
vincent                   0.4.4                      py_1    conda-forge
vs2015_runtime            14.15.26706          h3a45250_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.14.1                   py37_0  
wheel                     0.32.3                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
win_inet_pton             1.0.1                    py37_1  
win_unicode_console       0.5                      py37_0  
wincertstore              0.2                      py37_0  
winpty                    0.4.3                         4  
wrapt                     1.10.11          py37hfa6e2cd_2  
xerces-c                  3.2.2             h6538335_1001    conda-forge
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.1.2                    py37_0  
xlwings                   0.15.1                   py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zeromq                    4.2.5                he025d50_1  
zict                      0.1.3                    py37_0  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  

</details>

#### Code snippet that independently and completely reproduces the issue

```python
import osmnx as ox, geopandas as gpd
import shapely.wkt as wkt
import pathlib

from functools import partial
import pyproj
from shapely.ops import transform

ox.config(log_file=True, log_console=True, use_cache=True)

mapsZone = gpd.read_file(pathlib.Path('shapefiles','coloradospringsco.dbf'))
polygonTrue = mapsZone.geometry.iloc[0]
project = partial(
    pyproj.transform,
    pyproj.Proj(init='epsg:32613'), # source coordinate system : NAD_1983_UTM_Zone_13N_EPSG.prj
    pyproj.Proj(init='epsg:4326')) # destination coordinate system : WGS 84

g2 = transform(project, polygonTrue)
shape2 = ox.round_shape_coords(g2, 6)


# graph from polygon
#polygon = wkt.loads('POLYGON ((-122.418083 37.754154, -122.418082 37.766028, -122.410909 37.766028, -122.410908 37.754154, -122.418083 37.754154))') # This is the exemple that works
#polygon = wkt.loads('POLYGON ((-105.005754727028 38.75870150033518, -104.9884905460249 38.75870107534883, -104.9884927164047 38.74518346395622, -105.0057536418381 38.74518388873852, -105.005754727028 38.75870150033518))')
#polygon = shape2
#This is the hardcoded version of the polygon associated with shape2. I'm getting the same error with it
polygon = wkt.loads('POLYGON ((-105.005755 38.758702, -104.988491 38.758701, -104.988493 38.745183, -105.005754 38.745184, -105.005755 38.758702))')
G6 = ox.graph_from_polygon(polygon, network_type='walk')
G6_projected = ox.project_graph(G6)
fig, ax = ox.plot_graph(G6_projected)
```

**Comment by gboeing** [comment]
Your bounding box:

```python
polygon = wkt.loads('POLYGON ((-105.005755 38.758702, -104.988491 38.758701, -104.988493 38.745183, -105.005754 38.745184, -105.005755 38.758702))')
```

is in the middle of the Rocky Mountains: https://www.google.com/maps/search/38.745183,-104.988493

There are no streets within it, so you get a null graph. You should use try/except in you code to handle geometries in your shapefile that cover regions with no street network data.

**Comment by JulienTh** [comment]
It was supposed to be in the city Colorado Spring. I think I might have misread the dbf file (mapsZone.geometry.iloc[0]). I'm going to further that.
Thank you very much for your fast and precise answer.
