### ISSUE TITLE
AttributeError: module 'osmnx' has no attribute 'footprints_from_place'

### ISSUE THREAD

**Issue by Renton2017** [gboeing/osmnx#263]
**#### Problem description (what did you do, what did you expect to happen, and what actually ####happened)**

Hello everybody,
I am trying to run the code as per Github example:

> gdf = ox.footprints_from_place(place='Emeryville, California, USA')

Unfortunately I got the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-12-8896bb10f9f1> in <module>()
----> 1 gdf = ox.footprints_from_place(place='Emeryville, California, USA')

AttributeError: module 'osmnx' has no attribute 'footprints_from_place'

I also checked **similar issues** with module footprints_from_place, but I was pretty much unable to find a viable solution.
Should I upgrade OSMNX to version 0.9?
Please provide a valid path solution. Thanks in advance. Andrea

**#### What operating system, architecture, Python version, and OSMnx version are you using?**
I am using a machine of 64 bits, running Windows 10PRO version 1803, Python 3.6.3, OSMNX 0.8.2

**#### Complete list of your environment's packages and their versions (for example, run `conda list` or ##`pip list` then paste the output below, between the two "details" tags)**
<details>
adal                               1.1.0
affine                             2.2.0
alabaster                          0.7.10
altair                             2.3.0
anaconda-client                    1.6.14
anaconda-navigator                 1.8.2
anaconda-project                   0.8.0
apipkg                             1.4
applicationinsights                0.11.7
asn1crypto                         0.22.0
astroid                            1.5.3
astropy                            2.0.2
azure-cli-command-modules-nspkg    2.0.2
azure-cli-nspkg                    3.0.3
azure-common                       1.1.16
azure-mgmt-nspkg                   3.0.2
azure-mgmt-resource                2.0.0
azure-nspkg                        3.0.2
azure-storage-blob                 1.3.1
azure-storage-common               1.3.0
azure-storage-nspkg                3.0.0
azureml-model-management-sdk       1.0.1b6.post1
babel                              2.5.0
backports.functools-lru-cache      1.5
backports.shutil-get-terminal-size 1.0.0
basemap                            1.1.0
beautifulsoup4                     4.6.0
bitarray                           0.8.1
bkcharts                           0.2
blaze                              0.11.3
bleach                             2.0.0
bokeh                              0.12.10
boto                               2.48.0
boto3                              1.5.32
botocore                           1.8.46
Bottleneck                         1.2.1
branca                             0.3.1
CacheControl                       0.12.3
certifi                            2018.11.29
cffi                               1.10.0
chardet                            3.0.4
click                              6.7
click-plugins                      1.0.3
cligj                              0.4.0
cloudpickle                        0.4.0
clyent                             1.2.2
colorama                           0.3.9
comtypes                           1.1.2
conda                              4.6.7
conda-build                        3.0.27
conda-verify                       2.0.0
contextlib2                        0.5.5
coverage                           4.5.1
cryptography                       2.3.1
cycler                             0.10.0
Cython                             0.26.1
cytoolz                            0.8.2
dask                               0.15.3
datashape                          0.5.4
decorator                          4.1.2
descartes                          1.1.0
dill                               0.2.8.2
distlib                            0.2.5
distributed                        1.19.1
docutils                           0.14
entrypoints                        0.2.3
et-xmlfile                         1.0.1
execnet                            1.5.0
fastcache                          1.0.2
fastparquet                        0.1.4
feather-format                     0.4.0
filelock                           2.0.12
Fiona                              1.7.11.post1
flake8                             3.5.0
Flask                              0.12.2
Flask-Cors                         3.0.3
folium                             0.7.0
GDAL                               2.2.4
geographiclib                      1.49
geopandas                          0.4.0
geopy                              1.18.1
georaster                          1.25
gevent                             1.2.2
glob2                              0.5
greenlet                           0.4.12
h5py                               2.7.0
heapdict                           1.0.0
html5lib                           1.0.1
idna                               2.6
imageio                            2.2.0
imagesize                          0.7.1
ipykernel                          4.8.2
ipython                            6.2.1
ipython-genutils                   0.2.0
ipywidgets                         7.0.0
isodate                            0.6.0
isort                              4.2.15
itsdangerous                       0.24
jdcal                              1.3
jedi                               0.10.2
Jinja2                             2.10
jmespath                           0.9.3
jsonschema                         2.6.0
jupyter-client                     5.2.3
jupyter-console                    5.2.0
jupyter-core                       4.4.0
jupyterlab                         0.27.0
jupyterlab-launcher                0.4.0
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
liac-arff                          2.3.1
llvmlite                           0.20.0
locket                             0.2.0
lockfile                           0.12.2
lxml                               4.1.1
MarkupSafe                         1.0
matplotlib                         2.1.1
mccabe                             0.6.1
menuinst                           1.4.14
mistune                            0.7.4
mpmath                             0.19
msgpack-python                     0.4.8
msrest                             0.5.5
msrestazure                        0.5.0
multipledispatch                   0.4.9
munch                              2.3.2
navigator-updater                  0.1.0
nbconvert                          5.3.1
nbformat                           4.4.0
nbsphinx                           0.3.1
ndg-httpsclient                    0.5.1
networkx                           2.2
nltk                               3.2.4
nose                               1.3.7
notebook                           5.5.0
numba                              0.35.0+10.g143f70e
numexpr                            2.6.4
numpy                              1.14.2
numpydoc                           0.7.0
oauthlib                           2.1.0
odo                                0.5.1
olefile                            0.44
openpyxl                           2.5.0
osmnx                              0.8.2
packaging                          16.8
pandas                             0.23.4
pandocfilters                      1.4.2
partd                              0.3.8
path.py                            10.3.1
pathlib2                           2.3.0
patsy                              0.4.1
pep8                               1.7.0
pickleshare                        0.7.4
Pillow                             4.2.1
pip                                18.1
pkginfo                            1.4.1
plotly                             3.3.0
ply                                3.10
progress                           1.3
prompt-toolkit                     1.0.15
psutil                             5.4.0
psycopg2                           2.7.4
py                                 1.4.34
pyarrow                            0.8.0
pyasn1                             0.4.4
pycodestyle                        2.3.1
pycosat                            0.6.3
pycparser                          2.18
pycrypto                           2.6.1
pycurl                             7.43.0
pyflakes                           1.6.0
Pygments                           2.2.0
PyJWT                              1.6.4
pylint                             1.7.4
PyMySQL                            0.8.0
pyodbc                             4.0.17
pyOpenSSL                          17.2.0
pyparsing                          2.2.0
pyproj                             1.9.5.1
pyreadline                         2.1
PySAL                              1.14.4.post2
pyshp                              1.2.12
PySocks                            1.6.7
pytest                             3.2.1
pytest-cov                         2.5.1
pytest-forked                      0.2
pytest-xdist                       1.22.1
python-dateutil                    2.7.3
pytz                               2017.2
PyWavelets                         0.5.2
pywin32                            221
pywinpty                           0.5.1
PyYAML                             3.12
pyzmq                              17.0.0
QtAwesome                          0.4.4
qtconsole                          4.3.1
QtPy                               1.3.1
requests                           2.19.1
requests-oauthlib                  1.0.0
retrying                           1.3.3
rope                               0.10.5
Rtree                              0.8.3
ruamel-yaml                        0.11.14
s3fs                               0.1.3
s3transfer                         0.1.13
scikit-image                       0.13.0
scikit-learn                       0.19.1
scipy                              1.0.0
seaborn                            0.8.1
Send2Trash                         1.5.0
setuptools                         36.5.0.post20170921
Shapely                            1.6.4.post2
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.11.0
snowballstemmer                    1.2.1
snuggs                             1.4.1
sortedcollections                  0.5.3
sortedcontainers                   1.5.7
Sphinx                             1.6.3
sphinxcontrib-websupport           1.0.1
spyder                             3.2.4
SQLAlchemy                         1.2.4
statsmodels                        0.8.0
sympy                              1.1.1
tables                             3.4.2
tblib                              1.3.2
terminado                          0.8.1
testpath                           0.3.1
thrift                             0.11.0
toolz                              0.8.2
tornado                            4.5.2
traitlets                          4.3.2
typing                             3.6.2
unicodecsv                         0.14.1
urllib3                            1.23
vincent                            0.4.4
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.12.2
wheel                              0.29.0
widgetsnbextension                 3.0.2
win-inet-pton                      1.0.1
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.10.11
xarray                             0.10.1
xgboost                            0.7
xlrd                               1.1.0
XlsxWriter                         1.0.2
xlwings                            0.11.4
xlwt                               1.3.0
zict                               0.1.3

</details>

#### Code snippet that independently and completely reproduces the issue

```python
# your code goes here
`import numpy as np
import osmnx as ox
import networkx as nx
import pandas
import geopandas
from sklearn.neighbors import KDTree
import folium
import matplotlib.pyplot as plt
import collections
%matplotlib

gdf = ox.footprints_from_place(place='Emeryville, California, USA')`

**Comment by gboeing** [comment]
@Renton2017 yes, per [the change log](https://github.com/gboeing/osmnx/blob/master/CHANGELOG.md), the `buildings` module was deprecated in favor of a new `footprints` module in v0.9. The `buildings` module will be fully removed in v0.10.

If you're using OSMnx<0.9, then use `ox.buildings_from_place`. If you're using OSMnx>=0.9, then use `ox.footprints_from_place`. See [the documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.footprints) for more usage details.

**Comment by Renton2017** [comment]
Hi @gboeing , many thanks for the clarifications,
I will use the code suggestions, you sent me. Sorry if I do not have read carefully. Regards.
Andrea

**Comment by unifireseeker** [comment]
It is really helpful for me! Thanks a lot.

**Comment by Mehrdadbabazadeh17** [comment]
Hi,
I am trying to run this code on Jupyter on mac which I did it before, but I don't know why it does an error like this:

AttributeError: module 'osmnx' has no attribute 'distance'

and the code itself is:

incr = 0
same_count = 0
for ind, row in nearestNodes_under2000.iterrows():
    u, v, key = ox.get_nearest_edge(Graph, (row['Point_X'],row['Point_Y']))
    nn = min((u, v), key=lambda n: ox.distance.great_circle_vec(row['Point_X'],row['Point_Y'], Graph.nodes[n]['y'], Graph.nodes[n]['x']))
    
    if row['NN_ID'] == nn and ['NN_Distance'] < 2000:
        print(int(row['NN_ID']), " -> ", nn, " - X:", Graph.nodes[nn]['x'], " - Y:", Graph.nodes[nn]['y'])
        same_count += 1
        print ("They are same:", same_count)
    else:
        nid = int(row['NN_ID'])
        print("Diff: ", nid, " -> ", nn, " - X:", Graph.nodes[nid]['x'], " - Y:", Graph.nodes[nid]['y'])
    incr += 1



could you please help me what can I do to solve it.

**Comment by gboeing** [comment]
@Mehrdadbabazadeh17 this isn't related to this issue (deprecation of buildings module). Please open a new issue and completely fill out the new issue template and we can take a look.

**Comment by arilwan** [comment]
> ox.footprints_from_place

@gboeing As far this, I do not seem to solve the problem.

```
ox.footprints_from_place(place)

AttributeError: module 'osmnx' has no attribute 'footprints_from_place'
```

Version:
```
print(ox.__version__)
1.1.2
```

**Comment by gboeing** [comment]
@arilwan this is an old thread referring to now-deprecated modules from before v1.0. Use the [geometries](https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.geometries) module and see the usage examples repo for demonstrations of functionality.

**Comment by Alouette-29** [comment]
but now I can't find either of them! ***module 'osmnx' has no attribute 'footprints_from_place'*** and ***module 'osmnx' has no attribute 'footprints_from_place'***

**Comment by gboeing** [comment]
@Alouette-29 see the comment previous to yours.
