### ISSUE TITLE
Docker launch failure when using Git Bash (source path doesnt exist)

### ISSUE THREAD

**Issue by trakru** [gboeing/osmnx#264]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Used the docker installation instructions at https://hub.docker.com/r/gboeing/osmnx to launch osmnx. However when used the following command to run the Docker container 

> docker run --rm -it --name osmnx -p 8888:8888 -v "$PWD":/_mydirectory_/ gboeing/osmnx

Git Bash threw up an error  

> C:/Program Files/Docker/Docker/Resources/bin/docker.exe: Error response from daemon: Mount denied:
The source path "C:/_mydirectory_;C"
doesn't exist and is not known to Docker.

#### Attribution

Further research on stackoverflow: https://stackoverflow.com/questions/50608301/docker-mounted-volume-adds-c-to-end-of-windows-path-when-translating-from-linux lead me to understand that git-bash is automatically adding the

>  ;C

 to directory path which needs to be  removed

#### Suggested change

The command to run docker container (for linux) should be modified to include the escape character "/" before "$PWD" for git-bash users. the correct command would look like:

> $ winpty docker run --rm -it --name osmnx -p 8888:8888 -v /"$PWD":/_mydirectory_/ gboeing/osmnx

Please note the addition of "winpty" at the beginning of the docker run command - this is particular to users of Windows 10 & Git-Bash. the relevant error thread from Git says:

> the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

**Comment by gboeing** [comment]
@trakru thanks for figuring this out!

I'm a little hesitant to change the documentation to cover every individual command-line shell like Git Bash, as there may be many alternatives out there (such as Powershell, etc). My goal is to have the documentation on Docker Hub reflect how to run the container using the platform default terminals of Windows command prompt, Max terminal, and Linux terminal. In my testing it works across those (and of course may require some command tweaks for Git Bash or Powershell or other alternatives).
