### ISSUE TITLE
Edge grades are negative

### ISSUE THREAD

**Issue by schoeller** [gboeing/osmnx#265]
Hello,

thanks for this superduperuseful package. When fetching and equipping a road network like below

```
G = ox.graph_from_address('yourlocation', distance=300, network_type='drive', infrastructure='way["highway"~"motorway|trunk|primary|secondary|tertiary|unclassified|residential"]')
G = ox.add_node_elevations(G, your_map_key, max_locations_per_batch=350, pause_duration=0.02)
G = ox.add_edge_grades(G)
```

Some edges have a negative grade. Not knowing about neither osmnx, networkx I reversed the order through the following function

```
def correct_edge_grade(gdf_edges):
    edges = gdf_edges
    for idx in edges.index:
        # reversing LineString, u, v and copy grade_abs to grade
        if edges.grade[idx] < 0:
            u, v = edges.u[idx], edges.v[idx]
            geom = LineString(reversed(edges.geometry[idx].coords))
            edges.geometry[idx] = geom
            edges.u[idx], edges.v[idx] = v, u
            edges.grade[idx] = edges.grade_abs[idx]
    return edges
```

If there are more gentle ways of doing whatever I have, please correct. Otherwise I suggest that edge direction should be adjustable when calling ox.add_edge_grades.

Best

Sebastian

**Comment by gboeing** [comment]
As this is a directed graph, edge grades can be negative for directed edges that point downhill. For the absolute value of the edge grade (to always get a positive value), see the `add_absolute` argument: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.elevation.add_edge_grades
