### ISSUE TITLE
Plot direction of edges

### ISSUE THREAD

**Issue by schoeller** [gboeing/osmnx#266]
Dear all,

thanks for this wonderful toolbox.

I am using OSMNX in order to generate a first sketch for a drainage network layout based on a road network and a custom elevation model. I am missing the possibility to draw edge directions for verifying results. Any suggestions on how to do this are highly welcome. 

Best regards

Sebastian

**Comment by gboeing** [comment]
Best to ask how-to questions on [StackOverflow](https://stackoverflow.com/search?q=osmnx) as the issue tracker is for bugs, per the contributing guidelines.
