### ISSUE TITLE
Calculate complete Distance of shortest path

### ISSUE THREAD

**Issue by svenfpunkt** [gboeing/osmnx#267]
Hello,
I am trying toi calculate the distance of the calculated shortest path.
But I get an Error in the distance calculation.

My Code:
place_name = "Köln, Germany"
graph = ox.graph_from_place(place_name, network_type='drive', simplify=True)
edges = ox.graph_to_gdfs(graph, nodes=False, edges=True)

orig_xy = (50.838373, 7.072758)
target_xy = (50.898464, 7.042262)

orig_node = ox.get_nearest_node(graph, orig_xy)
target_node = ox.get_nearest_node(graph, target_xy)

route = nx.shortest_path(G=graph, source=orig_node, target=target_node,  weight='length')
route_length_km = sum([graph.edges[u][v][0]['length'] for u, v in zip(route, route[1:])]) / 1000.

Errro:
Traceback (most recent call last):
  File "/home/s.fanghaenel/anaconda3/envs/route_planer/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-104-a0dfd81a99ea>", line 1, in <module>
    route_length_km = sum([graph.edges[u][v][0]['length'] for u, v in zip(route, route[1:])]) / 1000.
  File "<ipython-input-104-a0dfd81a99ea>", line 1, in <listcomp>
    route_length_km = sum([graph.edges[u][v][0]['length'] for u, v in zip(route, route[1:])]) / 1000.
  File "/home/s.fanghaenel/anaconda3/envs/route_planer/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 1106, in __getitem__
    u, v, k = e
TypeError: 'numpy.int64' object is not iterable

Is there something wrong in my code?
How can i fix this?

Thanx alot Sven

**Comment by gboeing** [comment]
Use [this function](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.shortest_path_length.html#networkx.algorithms.shortest_paths.generic.shortest_path_length) to calculate shortest path lengths.

**Comment by svenfpunkt** [comment]
Hello Geoff,

this function gives me only the number of segments not the distance in km.

Greatings Sven

Von: Geoff Boeing [mailto:notifications@github.com]
Gesendet: Freitag, 29. März 2019 14:03
An: gboeing/osmnx
Cc: Fanghänel Sven (Post Direkt); Author
Betreff: Re: [gboeing/osmnx] Calculate complete Distance of shortest path (#267)


Use this function<https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.shortest_path_length.html#networkx.algorithms.shortest_paths.generic.shortest_path_length> to calculate shortest path lengths.

**Comment by gboeing** [comment]
Use the `weight` argument to get the geometric distance, the same as you did in your code snippet.

**Comment by svenfpunkt** [comment]
This is what  I am doing but, nothing changed.

Greatings

Von: Geoff Boeing [mailto:notifications@github.com]
Gesendet: Freitag, 29. März 2019 15:09
An: gboeing/osmnx
Cc: Fanghänel Sven (Post Direkt); Author
Betreff: Re: [gboeing/osmnx] Calculate complete Distance of shortest path (#267)


Use the weight argument to get the geometric distance, the same as you did in your code snippet.

**Comment by gboeing** [comment]
```python
import networkx as nx
import osmnx as ox
graph = ox.graph_from_place('Köln, Germany', network_type='drive', simplify=True)
edges = ox.graph_to_gdfs(graph, nodes=False, edges=True)
orig_node = ox.get_nearest_node(graph, (50.838373, 7.072758))
target_node = ox.get_nearest_node(graph, (50.898464, 7.042262))
length = nx.shortest_path_length(G=graph, source=orig_node, target=target_node, weight='length')
print(length) # prints 9201.784
```

**Comment by svenfpunkt** [comment]
Herre is my script:


import osmnx as ox
import networkx as nx
import numpy as np

#ox.config(log_console=True, use_cache=True)
np.random.seed(12)
graph = ox.graph_from_point((50.932253, 6.951256), distance=1000, network_type='drive')
fig, ax = ox.plot_graph(graph)
nodes, edges = ox.graph_to_gdfs(graph, nodes=True, edges=True)

test_arr = np.c_[nodes.y.values, nodes.x.values][np.random.choice(nodes.shape[0], 10)]

orig_xy = (50.932253, 6.951256)
orig_node = ox.get_nearest_node(graph, orig_xy)

Y = test_arr[:, 0]
X = test_arr[:, 1]
target_nodes = ox.get_nearest_nodes(graph, X, Y, method='balltree')

for j in range(Y.shape[0]):
    target_node = target_nodes[j]
    length = nx.shortest_path_length(G=graph, source=orig_node, target=target_node, weight='lenght')
    print(length)

output:

12
15
15
18
24
24
20
7
21
13

What iam doing wrong?


Von: Geoff Boeing [mailto:notifications@github.com]
Gesendet: Freitag, 29. März 2019 15:18
An: gboeing/osmnx
Cc: Fanghänel Sven (Post Direkt); Author
Betreff: Re: [gboeing/osmnx] Calculate complete Distance of shortest path (#267)


import networkx as nx



import osmnx as ox



graph = ox.graph_from_place('Köln, Germany', network_type='drive', simplify=True)



edges = ox.graph_to_gdfs(graph, nodes=False, edges=True)



orig_node = ox.get_nearest_node(graph, (50.838373, 7.072758))



target_node = ox.get_nearest_node(graph, (50.898464, 7.042262))



length = nx.shortest_path_length(G=graph, source=orig_node, target=target_node, weight='length')



print(length) # prints 9201.784

**Comment by svenfpunkt** [comment]
Sorry i found the bug in my code:
I wrote 'lenght' instead of 'length'
☺

Sorry


Von: Geoff Boeing [mailto:notifications@github.com]
Gesendet: Freitag, 29. März 2019 15:18
An: gboeing/osmnx
Cc: Fanghänel Sven (Post Direkt); Author
Betreff: Re: [gboeing/osmnx] Calculate complete Distance of shortest path (#267)


import networkx as nx



import osmnx as ox



graph = ox.graph_from_place('Köln, Germany', network_type='drive', simplify=True)



edges = ox.graph_to_gdfs(graph, nodes=False, edges=True)



orig_node = ox.get_nearest_node(graph, (50.838373, 7.072758))



target_node = ox.get_nearest_node(graph, (50.898464, 7.042262))



length = nx.shortest_path_length(G=graph, source=orig_node, target=target_node, weight='length')



print(length) # prints 9201.784

**Comment by vikaskumar99** [comment]
Does the shortest_path_length return in meters ??

**Comment by mengluchu** [comment]
if I use the weight = "length", then the route is different from if I use weight = "travel_time". In anther word, how can I get the distance of the shortest travel time route?

**Comment by gboeing** [comment]
@mengluchu if this is a "how-to" usage question, best to ask it on StackOverflow per the contributing guidelines, as the issue tracker is reserved for tracking bugs and proposing PRs.

**Comment by bernarducs** [comment]
Sorry but I'm tryn' run that snippet and one method has changed ('get_nearest_node'):

Then, I imagine the follow code is updated

```
import networkx as nx
import osmnx as ox

graph = ox.graph_from_place('Köln, Germany', network_type='drive', simplify=True)
edges = ox.graph_to_gdfs(graph, nodes=False, edges=True)

orig_node = ox.distance.nearest_nodes(graph, 50.838373, 7.072758)
target_node = ox.distance.nearest_nodes(graph, 50.898464, 7.042262)

length = nx.shortest_path_length(G=graph, source=orig_node, target=target_node, weight='length')
```
length variable outputs 0. 

What's wrong?

**Comment by gboeing** [comment]
@bernarducs for the same reason I mentioned on StackOverflow: you swapped the positions of your X and Y coordinates: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.distance.nearest_nodes You're searching for the nearest node to a point off the coast of Somalia, rather than in Germany.

**Comment by bernarducs** [comment]
Oh, thanks!

**Comment by pROGRAMMERDATASCIENCE22** [comment]
Hi,
I need to retrieve lat, long for my nodeId. Kindly mention which method to use.
for example:--- Graph= G, Source_node
**I need to know which method to use to retrieve the lat, long.**

I used osmnx.distance.get_nearest_nodes(G, lat, long) to get this source node ID.

**source_node_id = ox.distance.nearest_nodes(graph, 77.60181745749799, 12.991965832026759)**
