### ISSUE TITLE
TopologicalError：footprint_type='landuse'

### ISSUE THREAD

**Issue by melove93** [gboeing/osmnx#270]
Hallo, gboeing . Thank you for osmnx . I used 'footprints_from_place' function
I typed 
point = (48, 10)
dist =2000
gdf = ox.footprints.footprints_from_point(point=point, distance=dist,footprint_type='landuse')
gdf_proj = ox.project_gdf(gdf)

and it works well. But wenn i dist=10000 change,occurs TopologyException.
Error is:
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 10.060335240950593 48.128294710088241 at 10.060335240950593 48.128294710088241
TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x00000155BF9DD978>

But wenn i change footprint_type='building', dist=10000, it works well. 
In different latitude and longitude,wenn i type footprint_type='landuse'    ,dist have different upper limits.But footprint_type='building' works well.
Whats the Problem?
![image](https://user-images.githubusercontent.com/49486333/55954462-0bbb8d00-5c5f-11e9-9127-983fe1a86fbe.png)
Thanks

**Comment by melove93** [comment]
I think perhaps the problem is outer_polys and  inner_polys, because the lag-long point nearby is always a large forest belt, in this polygon there are some small polygons such as park,lake. I think may be this causes TopologicalError.

**Comment by gboeing** [comment]
@AtelierLibre recently did some nice work on adapting the footprints module to handle multipolygons... he might have some quick insight into what's going on here?

**Comment by AtelierLibre** [comment]
Hello both, I'm happy to have a look and see what I can find.

**Comment by AtelierLibre** [comment]
@melove93 I haven't been able to resolve this but it does seem to be Relation: Kirchberger Holz (14650) that is causing the problem. I exported it to GQIS and couldn't find a problem with its geometry there. @gboeing it is a multipolygon about 20km long with several ways as outer members and inner polys. I'm speculating at the moment but it would be subdivided by osm_footprints_download wouldn't it? Could this affect it?

**Comment by AtelierLibre** [comment]
Having another look, I think what is happening is that in 'create_footprints_gdf' the part 'try ...' 'exception ...' takes the vertices of every way received from the request and tries to turn them into a polygon.
In this case, it attempts to do that individually to the fragments of the outer way when they need to be joined together first before forming the large external polygon. This creates some smaller self-intersecting invalid geometries which generate the error.
As far as I can see [this page](https://wiki.openstreetmap.org/wiki/Relation:multipolygon/Algorithm) suggests an algorithm for dealing with multipolygon relations though I have seen others suggesting it is not that straightforward.
I'm going to have a look to see if 'gdf_from_place' in 'core' resolve long fragmented place boundaries into well-formed polygons.

**Comment by melove93** [comment]
@AtelierLibre  OK，Thanks for your help, i'm going to look at the algorithm with mutipolygon.

**Comment by AtelierLibre** [comment]
@melove93 that sounds great, if I can help at all please let me know.

**Comment by AtelierLibre** [comment]
@melove93 I potentially have a bit of time to work on this at the moment. I was just wondering if you are making some progress with the multipolygon algorithm?

**Comment by rubenl92** [comment]
Hi all,

I also got the same issue and made a workaround using the sourcecode and customized it.
Here is what i changed:

after this line in the function create_footprints_gdf:
`for inner_poly in inner_polys:`
i added:
`if footprints[inner_poly]['geometry'].within(temp_poly):`

maybe this helps you or others to fix this issue.

Good luck!

**Comment by AtelierLibre** [comment]
@rubenl92 thanks for suggesting that check. It sounds like a good idea and could well help resolve some of the issues.

**Comment by gboeing** [comment]
resolved in #289
