### ISSUE TITLE
Option to get info by "out geom;"

### ISSUE THREAD

**Issue by lyshuga** [gboeing/osmnx#272]
Dear Geoff Boeing,

I was wondering if there any way to get map data using graph_from_point function with output configuration as "out geom;". 

Having looked though the code, I haven`t find any way to do it :(

**Comment by gboeing** [comment]
No, that's not built into OSMnx as the purpose of the library is to construct networkx graphs (or geopandas GeoDataFrames) from OSM data. You could always use OSMnx to save its geometry to disk as a shapefile or graphml or somesuch for ingestion elsewhere.
