### ISSUE TITLE
Minor refactor to plot.py

### ISSUE THREAD

**Issue by dHannasch** [gboeing/osmnx#273]
I happened to have a use-case for getting a shortest path (normally a list of nodes) as a sequence of coordinate points *without* (immediately) plotting, so I extracted that code from plot_graph_route into a separate function node_list_to_coordinate_lines: https://github.com/dHannasch/osmnx/blob/master/osmnx/plot.py#L447

This can then be called by both plot_graph_route and plot_graph_routes.

I figured I'd drop you a line just in case you might want something like this in OSMnx proper.

**Comment by gboeing** [comment]
@dHannasch yes it sounds like this might be a useful PR. Would you like to open one?

**Comment by dHannasch** [comment]
Sure: https://github.com/gboeing/osmnx/pull/274
