### ISSUE TITLE
Allow specifying custom elevation URL and/or proxies

### ISSUE THREAD

**Issue by dHannasch** [gboeing/osmnx#277]
Not sure how many people might have this problem, but allowing a call to `add_node_elevations` to specify a custom URL and/or proxies enables working within restrictive networks, at the cost of adding a couple more parameters to the function: https://github.com/dHannasch/osmnx/commit/211a618456a8062bc701429dded7f191f5576344

Not sure how you'd feel about having those extra parameters in OSMnx proper.

Another option that might be more palatable would be to extract the critical request code into a separate function: https://github.com/gboeing/osmnx/commit/937af8c4b58a1faabe76769bf90f602c1b9d0a42
`add_node_elevations` could then call that function.
`add_node_elevations` could leave the URL and proxies out of its own parameters, keeping a short simple signature, and anyone who needed to do something more complicated could call the more powerful low-level function and then assign elevations to nodes manually.

**Comment by dHannasch** [comment]
Another option that might be more palatable would be to extract the critical request code into a separate function: https://github.com/gboeing/osmnx/commit/937af8c4b58a1faabe76769bf90f602c1b9d0a42
`add_node_elevations` could then call that function.
`add_node_elevations` could leave the URL and proxies out of its own parameters, keeping a short simple signature, and anyone who needed to do something more complicated could call the more powerful low-level function and then assign elevations to nodes manually.

**Comment by gboeing** [comment]
I'll leave this open for a bit to see if anyone else weighs in on this being useful functionality for their workflow...

**Comment by gboeing** [comment]
I'm going to close this one for now. But I'm willing to reopen it and solicit a PR if any other folks end up needing this sort of functionality at some point.
