### ISSUE TITLE
Input geom 0 is invalid: Self-intersection at or near point 

### ISSUE THREAD

**Issue by PierreAttard** [gboeing/osmnx#278]
Hello gboing. 

I have seen the issue #270 but I'm not sure it is the same issue. 

# Request

For some location, the method *create_footprints_gdf* has an issue. 

You can find below an example of request. 

results = osmnx.footprints.create_footprints_gdf(polygon=None, north=51.26658135394529, south=51.152831680560726, east=4.55191769225323, west=4.4076010491502684, footprint_type='building', retain_invalid=False)

# The issue
I got these errors when I do this request :
- TopologyException: Input geom 0 is invalid: Self-intersection at or near point 
- shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at >

If I add .buffer(0) for temp_poly=footprints[outer_poly]['geometry'] and temp_poly=temp_poly.difference(footprints[inner_poly]['geometry'].buffer(0)), the issue disappear but it is not satisfactory. 

I use Python 3.7 on windows. 

Thank you a lot.

**Comment by AtelierLibre** [comment]
I think this is the same as issue #270.

Your code generates this error:
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 4.4621621060636354 51.214826758346931 at 4.4621621060636354 51.214826758346931

If you look at OpenStreetMap at that point
(https://www.openstreetmap.org/#map=19/51.21486/4.46238) the castle's outer boundary is made up of two lines.

As in #270 OSMnx currently tries to turn them both into individual polygons but the shorter one creates a self-intersection. buffer(0) may 'fix' the self-intersection but it still won't return the correct geometry for the outer edge of the castle.
![Screenshot from 2019-04-30 09-46-34](https://user-images.githubusercontent.com/36126654/56951907-e240a380-6b30-11e9-912f-621f8d23aedf.png)

**Comment by gboeing** [comment]
Thanks @AtelierLibre, did that `geom.buffer(0)` suggestion resolve it? (That fix has often worked for me in other, previous, but similar circumstances). If so, would you like to create a PR?

**Comment by AtelierLibre** [comment]
@gboeing The exisiting `create_footprints_gdf` only correctly handles polygons formed from single closed ways. The `geom.buffer(0)` may 'fix' the invalid polygons created from chained open ways and avoid the error but it won't create the correct shape for the building.

I potentially have a bit of time to look at this now and I was thinking it could be done in two steps:
1. Amend the existing `create_footprints_gdf` to fail gracefully i.e. not try to polygonise chains of open ways and warn that this is what it is doing.
2. Implement [this algorithm](https://wiki.openstreetmap.org/wiki/Relation:multipolygon/Algorithm) to deal with multipolygons properly.

I'm suggesting two steps as I think the second one might take some time. Does that sound okay?

**Comment by gboeing** [comment]
@AtelierLibre that sounds good, and thanks again for you help with this functionality! It's much appreciated.

**Comment by gboeing** [comment]
resolved in #289

**Comment by PierreAttard** [comment]
Thanks a lot !
