### ISSUE TITLE
Return distances to nearest edges

### ISSUE THREAD

**Issue by dHannasch** [gboeing/osmnx#280]
It would be convenient to have the capability to keep the distances to nearest edges found by `get_nearest_edges`.
One possible way to do this would be to have `get_nearest_edges` internally call a function that does return the distances returned by the tree query, as shown in https://github.com/dHannasch/osmnx/commit/8f0cc95ca80cb3b0bf0e0322ec0771033fb127b1.

This would, obviously, affect Issue #261. But from reading https://github.com/juliamgomes/osmnx/commit/72b887a53d045ce8468cb1e5766f85abda036d4d, it *looks* like it would be reasonably straightforward to return distances in @juliamgomes' new scheme the same way we can in the current scheme.

**Comment by juliamgomes** [comment]
@dHannasch that makes sense to me! @gboeing @PedrosWits it sounds like we're all on the same page about the implementation so I'll try to get a PR together over the weekend :)

**Comment by gboeing** [comment]
Thanks!

**Comment by gboeing** [comment]
closing this issue here in favor of discussion in #261 and #284
