### ISSUE TITLE
Bug in osmnx\core.py

### ISSUE THREAD

**Issue by reymnia** [gboeing/osmnx#282]
### Issue

Hello,
 
I think there's a bug in the core.py. I tried to correct it and it's running now. I am attaching the edited code.
[core-edited.txt](https://github.com/gboeing/osmnx/files/3146674/core-edited.txt)

Thanks,

### Error

```python
----> 5 graph=ox.core.create_graph(osm_data,name='unnamed',retain_all=True, bidirectional=False)

D:\Program Files\Anaconda3\lib\site-packages\osmnx\core.py in create_graph(response_jsons, name, retain_all, bidirectional)
   1333     elements = []
   1334     for response_json in response_jsons:
-> 1335         elements.extend(response_json['elements'])
   1336     if len(elements) < 1:
   1337         raise EmptyOverpassResponse('There are no data elements in the response JSON objects')
```

**Comment by gboeing** [comment]
Can you please provide a complete example to reproduce the error you were getting?

**Comment by reymnia** [comment]
Please find it below:

`import osmnx as ox
osm_data = ox.utils.overpass_json_from_file('D:\\osm\\data.osm')
graph=ox.core.create_graph(osm_data,name='unnamed',retain_all=True, bidirectional=False)
` 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-8ffa660b80ea> in <module>
      4 osm_data = ox.utils.overpass_json_from_file('D:\\osm\\data.osm')
----> 5 graph=ox.core.create_graph(osm_data,name='unnamed',retain_all=True, bidirectional=False)

D:\Program Files\Anaconda3\lib\site-packages\osmnx\core.py in create_graph(response_jsons, name, retain_all, bidirectional)
   1333     elements = []
   1334     for response_json in response_jsons:
-> 1335         elements.extend(response_json['elements'])
   1336     if len(elements) < 1:
   1337         raise EmptyOverpassResponse('There are no data elements in the response JSON objects')

TypeError: string indices must be integers

**Comment by gboeing** [comment]
Can you share a reproducible example? I can't debug it if I can't reproduce it, and I can't reproduce it if the code snippet relies on that `data.osm` file that I don't have.

**Comment by gboeing** [comment]
For reference, @reymnia emailed me `data.osm` and I'm uploading it here for replication: [data.zip](https://github.com/gboeing/osmnx/files/3154361/data.zip)

Make sure you read [the docs](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_file) and the OSMnx examples. You should use the `graph_from_file` function.

Testing this with your file, everything works fine:

```python
import osmnx as ox
G = ox.graph_from_file('data.osm')
```

Completes successfully.

Testing this with the [DC extract file](http://download.geofabrik.de/north-america/us/district-of-columbia-latest.osm.bz2), everything works fine too:

```python
import osmnx as ox
G = ox.graph_from_file('district-of-columbia-latest.osm')
```
Completes successfully.

**Comment by reymnia** [comment]
Ah I see, I should use graph_from_file() directly! I have first converted xml to json in order to use create_graph(). But this is more straightforward. Thank you for your help.

**Comment by reymnia** [comment]
Just am wondering if you checked create_graph() function as well? Does it work properly?

**Comment by gboeing** [comment]
`create_graph` isn't meant to be used that way... per [the docstring](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.create_graph) its `response_jsons` argument must be a list of Overpass API JSON-formatted HTTP responses.

**Comment by reymnia** [comment]
Thank you very much for your help. I will need to read the documentation carefully!

**Comment by ZAHRAZ-GH** [comment]
Hello,
Really Thanks for your resources.
I download  data with overpass API  in GeoJSON format. now i want to use ox.graph_from_file('/content/export (1).geojson'), to create Rose orientation, but"ox.graph_from_file" does not work 


figsize = ( 5,  5)
fig, axes = plt.subplots(figsize=figsize, subplot_kw={"projection": "polar"})
G = ox.graph_from_file("Isfahan, Iran", network_type="drive")
Gu = ox.add_edge_bearings(ox.get_undirected(neis['geometry']))
fig, ax =ox.bearing.plot_orientation(Gu, ax=axes, title="Isfahan, Iran", area=True)


really thanks for your guide in advance

**Comment by gboeing** [comment]
@ZAHRAZ-GH if you have a usage question, please ask on StackOverflow, per the OSMnx contributing guidelines. Thanks.
