### ISSUE TITLE
DeprecationWarning: Flags not at the start of the expression '//(?s)(.*?)/'

### ISSUE THREAD

**Issue by dHannasch** [gboeing/osmnx#285]
As of Python 3.6, OSMnx gets the following DeprecationWarning:
```
osmnx/core.py:344: DeprecationWarning: Flags not at the start of the expression '//(?s)(.*?)/'
    domain = re.findall(r'//(?s)(.*?)/', url)[0]
```
Many other projects, such as [bottle](https://github.com/bottlepy/bottle/issues/949) and [babel](https://github.com/python-babel/babel/issues/467), have been getting the same DeprecationWarning. This is the change to Python that causes this DeprecationWarning:
https://github.com/python/cpython/commit/db99e6ee57c5070e6ef82fd2eaa528f09f3948dc

We can put the (?s) (dot matches all) flag at the start of each such regular expression:
https://github.com/dHannasch/osmnx/commit/675c2db02092cabce13e0631a7b837cbb3bb0c55

There's also the babel solution of passing re.DOTALL seperately: https://github.com/python-babel/babel/commit/f89f48795fdbed07c51aa897eca590a05eb4b746

**Comment by gboeing** [comment]
@dHannasch can you provide a working example to reproduce this warning with OSMnx? Somehow I haven't seen it (on python 3.7).

**Comment by gboeing** [comment]
Ah yes, I see. Do you want to open a quick PR to fix?
