### ISSUE TITLE
ox.add_edge_grades() fails 

### ISSUE THREAD

**Issue by tarwcz111111111** [gboeing/osmnx#287]
I already  upgraded to the latest version of osm, but I still got the division by zero error when I used add_edge_grades() function .
![image](https://user-images.githubusercontent.com/49775390/58072521-7d79e580-7bd2-11e9-9b4a-159173f82263.png)
![image](https://user-images.githubusercontent.com/49775390/58072536-89fe3e00-7bd2-11e9-84c3-a33bc29ee7b4.png)
![image](https://user-images.githubusercontent.com/49775390/58072543-908cb580-7bd2-11e9-894b-d936536dd290.png)

**Comment by gboeing** [comment]
@tarwcz111111111 can you post your working example to reproduce this as plain text here, so I can run it?

**Comment by tarwcz111111111** [comment]
my_google_elevation_api_key = " "
import networkx as nx
import numpy as np
import osmnx as ox
import geopandas as gpd
import pandas as pd
ox.config(log_console=True, use_cache=True)
ox.__version__

G = ox.graph_from_place('Hsinchu, Taiwan', network_type='walk')
ox.plot_graph(G)

G = ox.graph_from_place('Hsinchu, Taiwan', network_type='walk')
G = ox.add_node_elevations(G, api_key=my_google_elevation_api_key)

G = ox.add_edge_grades(G,add_absolute = False)

**Comment by gboeing** [comment]
Thanks. Fixed in fde6927cba8b26612d9e3d4844ae6c5165cc8089.
