### ISSUE TITLE
Add parameter which_result for footprints_from_place 

### ISSUE THREAD

**Issue by enriqueav** [gboeing/osmnx#290]
The function footprints_from_place

`osmnx.footprints.footprints_from_place(place, footprint_type='building', retain_invalid=False)`

could also receive the argument which_result, to choose the result number of Nominatim

`osmnx.core.gdf_from_place(query, gdf_name=None, which_result=1, buffer_dist=None)`.

If this is accepted, I could work on it and send the PR.

**Comment by enriqueav** [comment]
Seems like the same could be done for 
`osmnx.pois.pois_from_place(place, amenities=None)`

**Comment by gboeing** [comment]
I think this is a good idea. Would you like to open a PR?

**Comment by gboeing** [comment]
closed in #292
