### ISSUE TITLE
Feature Request - which_result in gdf_from_places

### ISSUE THREAD

**Issue by rafaeelaudibert** [gboeing/osmnx#295]
Hey Guys!

I need to query a lot of cities, so I'm using the `gdf_from_places` function, but as you could expect I don't always want the first returned result, so it would be needed to add the `which_result` (available in `gdf_from_place`) to the gdf_from_places function as well.

I have implemented this feature locally, just checking to see if this is something it would be wanted to be implemented upstream.

If so, there is a project decision to be made:
Do we restrict the same which_result for all places (this way we just need to add an optional parameter in the function), or we use a specific parameter for each of the places (which is what I used in my case) that must be passed together in the dictionary, or maybe another idea?

**Comment by gboeing** [comment]
A good option would be to add `which_results` as an optional argument as a list with the same length as the `queries` argument, then zip them in `gdf_from_places`'s for loop to pass them both into the `gdf_from_place` call one at a time.

**Comment by rafaeelaudibert** [comment]
That’s a great idea. I can make a PR today for it. Is that good for you?

**Comment by gboeing** [comment]
Sure, thanks.

**Comment by rafaeelaudibert** [comment]
Pull Request addressing this feature opened at #301
