### ISSUE TITLE
graph_from_file fails on XML dump

### ISSUE THREAD

**Issue by ricsonc** [gboeing/osmnx#296]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

I attempted to load a graph from the OSM planet dump (https://wiki.openstreetmap.org/wiki/Planet.osm) with 
`G = ox.graph_from_file('planet.osm.bz2')`.

I expected the function to return the road graph of the entire world.

This resulted in the error:

```
Traceback (most recent call last):
  File "parseplanet.py", line 3, in <module>
    G = ox.graph_from_file('planet.osm.bz2')
  File "/home/ricsonc/anaconda3/envs/ox/lib/python3.7/site-packages/osmnx/core.py", line 1907, in graph_from_file
    response_jsons = [overpass_json_from_file(filename)]
  File "/home/ricsonc/anaconda3/envs/ox/lib/python3.7/site-packages/osmnx/utils.py", line 1242, in overpass_json_from_file
    xml.sax.parse(file, handler)
  File "/home/ricsonc/anaconda3/envs/ox/lib/python3.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/home/ricsonc/anaconda3/envs/ox/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/ricsonc/anaconda3/envs/ox/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/home/ricsonc/anaconda3/envs/ox/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/home/conda/feedstock_root/build_artifacts/python_1553725065783/work/Modules/pyexpat.c", line 417, in StartElement
  File "/home/ricsonc/anaconda3/envs/ox/lib/python3.7/xml/sax/expatreader.py", line 333, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/home/ricsonc/anaconda3/envs/ox/lib/python3.7/site-packages/osmnx/utils.py", line 1201, in startElement
    self._element['tags'].update({attrs['k']: attrs['v']})
TypeError: 'NoneType' object is not subscriptable
```

I am reasonably sure that this is not a problem with `planet.osm.bz2` because
1. I checked that the md5sum matches the value provided by the site
2. I unzipped it to `planet.osm` and as far as I can tell with my eyes -- it's valid XML.

### What operating system, architecture, Python version, and OSMnx version are you using?

Ubuntu 14.04, python 3.7, osmnx version 0.10

Note that while this function gave an error, other parts of OSMn

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
altair                    3.1.0                    py37_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
cfitsio                   3.430             h0bd2449_1002    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
descartes                 1.1.0                      py_3    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fiona                     1.8.6            py37hf242f0b_3    conda-forge
folium                    0.9.1                      py_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.4.1            py37hf242f0b_3    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.5.0                      py_2    conda-forge
geopy                     1.20.0                     py_0    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.5.1                h560c3f3_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1
libgdal                   2.4.1                h02bbc0b_3    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.3                 h4e4e079_0    conda-forge
libspatialindex           1.9.0                he1b5a44_1    conda-forge
libspatialite             4.3.0a            h4c5cd43_1028    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
mapclassify               2.0.1                      py_0    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
matplotlib                3.1.0                    py37_1    conda-forge
matplotlib-base           3.1.0            py37hfd891ef_1    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
osmnx                     0.10                       py_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hbeee2d4_0    conda-forge
proj4                     6.1.0                he751ad9_2    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    2.2.0            py37hc44880f_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_0    conda-forge
pyrsistent                0.15.2           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py37_0    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
scipy                     1.3.0            py37h921218d_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
shapely                   1.6.4           py37h2afed24_1004    conda-forge
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py37h516909a_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.24.3                   py37_0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
</details>

#### Code snippet that independently and completely reproduces the issue

```python
import osmnx as ox
G = ox.graph_from_file('planet.osm.bz2')
```

**Comment by gboeing** [comment]
Isn't the planet dump hundreds of GB? I don't think you'd be able to load it period (unless you're on some sort of supercomputer). Can you try your code with a small extract (such as for a single city) to see if it works?

**Comment by gboeing** [comment]
I only have 32 GB of RAM on my computer, so I obviously can't load/test the entire planet graph. But to test a manageable use case, I just downloaded the [Delaware extract](https://download.geofabrik.de/north-america/us/delaware-latest.osm.bz2) and loaded it just fine:

```python
import osmnx as ox
ox.config(log_console=True)
G = ox.graph_from_file('delaware-latest.osm.bz2')
```

**Comment by ricsonc** [comment]
I was also able to load the delaware extract. It seems the problem with the planet dump is the xml parsing -- specifically in `OSMContentHandler`:

```
    def startElement(self, name, attrs):
        if name == 'osm':
            self.object.update({k: attrs[k] for k in attrs.keys()
                if k in ('version', 'generator')})

        elif name in ('node', 'way'):
            self._element = dict(type=name, tags={}, nodes=[], **attrs)
            self._element.update({k: float(attrs[k]) for k in attrs.keys()
                if k in ('lat', 'lon')})
            self._element.update({k: int(attrs[k]) for k in attrs.keys()
                if k in ('id', 'uid', 'version', 'changeset')})

        elif name == 'tag':
            self._element['tags'].update({attrs['k']: attrs['v']})

        elif name == 'nd':
            self._element['nodes'].append(int(attrs['ref']))

        elif name == 'relation':
            # Placeholder for future relation support.
            # Look for nested members and tags.
            pass
```

In planet.osm, there are some other tags such as "comment" and "created_by" which appear before any node or way, so in

```        elif name == 'tag':
            self._element['tags'].update({attrs['k']: attrs['v']})```
`self._element` is still None and this causes an error. 

I fixed the issue by adding an if statement to skip the update if it's None.
