### ISSUE TITLE
Unable to use the "buildings_from_place" attribute since it says that it does not exist

### ISSUE THREAD

**Issue by rampallishyam** [gboeing/osmnx#298]
Buildings_from_place attribute does not work anymore. 

OSMNX version: 0.10
Python: 3.7.3, 64-bit
Using Anaconda 64 bit
OS: Windows

```python
>>> import osmnx as ox
>>> graph=ox.graph_from_bbox(1.364,1.339,103.718,103.676)
>>> buildings = ox.buildings_from_place(place_name)

AttributeError                            Traceback (most recent call last)
<ipython-input-50-34f1457532bf> in <module>
      6 """
      7 
----> 8 buildings=ox.buildings_from_place(place_name)

AttributeError: module 'osmnx' has no attribute 'buildings_from_place'
```

**Comment by gboeing** [comment]
The `buildings` module was [deprecated](https://github.com/gboeing/osmnx/blob/master/CHANGELOG.md) in a previous release and officially removed in the current release. It has been replaced by the `footprints` module, as detailed in the [documentation](https://osmnx.readthedocs.io/).

**Comment by rampallishyam** [comment]
Thanks Professor Boeing!
