### ISSUE TITLE
`add_node_elevations` api issue (400 bad request)

### ISSUE THREAD

**Issue by sitthinutk** [gboeing/osmnx#303]
I think there is some update in Google API which affects `add_node_elevations( )` function.
Google api needs **(lat, lon)**, not **(x, y)** from osmnx.

correct url format:
https://maps.googleapis.com/maps/api/elevation/json?locations=39.7391536,-104.9847034&key=[API_KEY]

current osmnx url format:
https://maps.googleapis.com/maps/api/elevation/json?locations=6200023.54218,488066.31946&key=[API_KEY]

which makes Google returns
```
{
error_message: "Invalid request. Invalid 'locations' parameter.",
results: [ ],
status: "INVALID_REQUEST"
}
```

I manually changed the code (line 49 **elevation.py**) from 
`node_points = pd.Series({node:'{:.5f},{:.5f}'.format(data['y'], data['x']) for node, data in G.nodes(data=True)})`
to
`node_points = pd.Series({node:'{:.5f},{:.5f}'.format(float(data['lat']), float(data['lon'])) for node, data in G.nodes(data=True)})`
and it seems to work as expected

The reason I added `float( )` because sometimes we may read graph from `.graphml` and every `float` will become `str`.

**Comment by gboeing** [comment]
@sitthinutk the URL you provided (as "current osmnx url format") suggests you are working in projected units, but Google needs lat-lng units.

**Comment by sitthinutk** [comment]
yes so that makes `add_node_elevations( )` can't be used right now, right?

**Comment by gboeing** [comment]
You can use that function at any point in your workflow. Just project your coordinates to lat-lng first.
