### ISSUE TITLE
Create virtual nodes on a edge

### ISSUE THREAD

**Issue by lovetuliper** [gboeing/osmnx#304]
The package is great. I like it so much!  Currently, I am simulating a vehicle traversal environment. Some edge is very long so that the vehicle can not finish traveling within a certain time slot.  I want to create virtual nodes or just markers on the long edge. In this way, I can see where the vehicle stop on the edge after a certain time slot. How to make this visualization? Thank you very much!

**Comment by gboeing** [comment]
Yes, see this function: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils.redistribute_vertices

You'd use it via something like the following:

```python
# transform graph into DataFrame
edges = ox.graph_to_gdfs(G, nodes=False, fill_edge_geometry=True)

# transform edges into evenly spaced points
edges['points'] = edges.apply(lambda x: redistribute_vertices(x.geometry, dist), axis=1)

# develop edges data for each created points
extended = edges['points'].apply([pd.Series]).stack().reset_index(level=1, drop=True).join(edges).reset_index()
```

**Comment by lovetuliper** [comment]
Thanks, Prof. Boeing! I applied these functions but couldn't make it work. Could you help me check the code? I want to create some virtual nodes on the edge from node_1 to node_2. Thank you. 

import networkx as nx
import osmnx as ox
import requests
import matplotlib.cm as cm
import matplotlib.colors as colors
import csv, sys
import numpy
import numpy as np
from shapely import wkt
from shapely.geometry import LineString
import pandas as pd

def redistribute_vertices(geom, distance):
    if geom.geom_type == 'LineString':
        num_vert = int(round(geom.length / distance))
        if num_vert == 0:
            num_vert = 1
        return LineString(
            [geom.interpolate(float(n) / num_vert, normalized=True)
             for n in range(num_vert + 1)])
    elif geom.geom_type == 'MultiLineString':
        parts = [redistribute_vertices(part, distance)
                 for part in geom]
        return type(geom)([p for p in parts if not p.is_empty])
    else:
        raise ValueError('unhandled geometry %s', (geom.geom_type,))

ox.config(use_cache=True, log_console=True)
ox.__version__

G = ox.graph_from_place('Blacksburg, Virginia, USA', network_type='drive')
edges = ox.graph_to_gdfs(G, nodes=False, fill_edge_geometry=True)

node_1 = ox.get_nearest_node(G, (37.2238, -80.4402)); #276308465
node_2 = ox.get_nearest_node(G, (37.2109, -80.43)); #5288322283
# # route = nx.shortest_path(G, node_1, node_2, weight='length')
# # route_length = nx.shortest_path_length(G, node_1, node_2, weight='length')
# # print(route_length)
# # ox.plot_graph_route(G, route, node_size=0)

u = list(edges.u)
v = list(edges.v)

#find index of node_1
node_1_inx = [] 
for i in range(0, len(u)) : 
    if u[i] == node_1 : 
        node_1_inx.append(i) 

#find index of node_2
node_2_inx = [] 
for i in range(0, len(v)) : 
    if v[i] == node_2 : 
        node_2_inx.append(i) 

# find the row index of node_1 & node 2
inx = list(set(node_1_inx) & set(node_2_inx))

edge_string = edges.geometry[inx[0]]
print(edge_string)

# transform edges into evenly spaced points
edges['points'] = edges.apply(lambda edge_string: redistribute_vertices(edge_string.geometry, 0.004), axis=1)

# # develop edges data for each created points
extended = edges['points'].apply([pd.Series]).stack().reset_index(level=1, drop=True).join(edges).reset_index()

ox.plot_graph(G)

**Comment by lovetuliper** [comment]
Thanks, Prof. Boeing! I was trying to create some virtual nodes on the edge from node_1 to node_2. I applied these functions but couldn't make it work. Could you help me check the code?  Thank you. 

[test_add_nodes.py.zip](https://github.com/gboeing/osmnx/files/3323258/test_add_nodes.py.zip)

**Comment by gboeing** [comment]
The issue tracker is for documenting bugs or proposing new features. Best to ask how-to questions at the user community on StackOverflow, per the contributing guidelines.

**Comment by lfzhou917** [comment]
OK. Thanks, Prof. Boeing.
