### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by bonakdarf92** [gboeing/osmnx#308]
Hi,

I succesfully used the osmnx framework in order to access the Network of Darmstadt in Germany on my Windows PC.
Unfortunetaley the Problem which occurs is an IllegalArgumentException when running my code or other sample code.  
```python
import osmnx as ox
G = ox.graph_from_place('Manhattan Island, New York City, New York, USA', network_type='drive')
-->Shell is not a LinearRing
IllegalArgumentException: geometries must not contain null elements
[1]    22260 segmentation fault  python
```
This error is only at my MacBookPro (10.14.1) whereas no error occur on WinPC (10).
In both environments I use an Anaconda with Python 3.7.3 and osmnx 0.10

#### List Mac Environment

<details>

| Name | Version |  Build | Channel |
| ------ | ------- | ------ | -------- |
| altair | 3.1.0 | py37_0 | conda-forge |
| asn1crypto | 0.24.0 | py37_1003 | conda-forge |
 | attrs |  19.1.0 |  py_0 | conda-forge |  
 | boost-cpp |  1.70.0 |  hd59e818_0 | conda-forge |  
 | branca | 0.3.1 | py_0 | conda-forge |  
 | bzip2 |  1.0.6 |  h1de35cc_1002 | conda-forge |  
 | ca-certificates |  2019.6.16 | hecc5488_0 | conda-forge |  
 | cairo |  1.16.0 | h0ab9d94_1001 | conda-forge |  
 | certifi |  2019.6.16 | py37_0 | conda-forge |  
 | cffi | 1.12.3 |  py37hccf1714_0 | conda-forge |  
 | cfitsio |  3.430 |  h50cca31_1002 | conda-forge |  
 | chardet |  3.0.4 | pypi_0 | pypi |  
 | click |  7.0 | pypi_0 | pypi |  
 | click-plugins |  1.1.1 | py_0 | conda-forge |  
 | cligj |  0.5.0 | pypi_0 | pypi |  
 | cryptography | 2.7 | py37h212c5bf_0 | conda-forge |  
 | curl | 7.64.1 |  h22ea746_0 | conda-forge |  
 | cycler | 0.10.0 |  pypi_0 | pypi |  
 | decorator |  4.4.0 | py_0 | conda-forge |  
 | descartes |  1.1.0 | py_3 | conda-forge |  
 | entrypoints |  0.3 |  py37_1000 | conda-forge |  
 | expat |  2.2.5 |  h6de7cb9_1003 | conda-forge |  
 | fiona |  1.8.6 | pypi_0 | pypi |  
 | folium | 0.9.1 | py_0 | conda-forge |  
 | fontconfig | 2.13.1 | h1027ab8_1000 | conda-forge |  
 | freetype | 2.10.0 |  h24853df_0 | conda-forge |  
 | freexl | 1.0.5 |  h1de35cc_1002 | conda-forge |  
 | gdal | 2.4.1 | py37h39889d8_4 | conda-forge |  
 | geographiclib |  1.49 |  py_0 | conda-forge |  
 | geopandas |  0.5.0 | py_2 | conda-forge |  
 | geopy |  1.20.0 |  py_0 | conda-forge |  
 | geos | 3.7.1 |  h0a44026_1000 | conda-forge |  
 | geotiff |  1.5.1 | h83de174_2 | conda-forge |  
 | gettext |  0.19.8.1 | h46ab8bc_1002 | conda-forge |  
 | giflib | 5.1.7 | h01d97ff_1 | conda-forge |  
 | glib | 2.58.3 | h9d45998_1001 | conda-forge |  
 | hdf4 | 4.2.13 | hf3c6af0_1002 | conda-forge |  
 | hdf5 | 1.10.5 | nompi_h0cbb7df_1100 | conda-forge |  
 | icu |  58.2 | h0a44026_1000 | conda-forge |  
 | idna | 2.8 | pypi_0 | pypi |  
 | jinja2 | 2.10.1 |  py_0 | conda-forge |  
 | jpeg | 9c | h1de35cc_1001 | conda-forge |  
 | json-c | 0.13.1 | h1de35cc_1001 | conda-forge |  
 | jsonschema | 3.0.1 | py37_0 | conda-forge |  
 | kealib | 1.4.10 | h6659575_1005 | conda-forge |  
 | kiwisolver | 1.1.0 | py37h770b8ee_0 | conda-forge |  
 | krb5 | 1.16.3 | hcfa6398_1001 | conda-forge |  
 | libblas |  3.8.0 | 7_openblas | conda-forge |  
 | libcblas | 3.8.0 | 7_openblas | conda-forge |  
 | libcurl |  7.64.1 |  h16faf7d_0 | conda-forge |  
 | libcxx | 8.0.0 |  2 | conda-forge |  
 | libcxxabi |  8.0.0 |  2 | conda-forge |  
 | libdap4 |  3.19.1 | hae55d67_1000 | conda-forge |  
 | libedit |  3.1.20170329 | hcfe32e1_1001 | conda-forge |  
 | libffi | 3.2.1 |  h6de7cb9_1006 | conda-forge |  
 | libgdal |  2.4.1 | hbed8f18_4 | conda-forge |  
 | libgfortran |  3.0.1 |  0 | conda-forge |  
 | libiconv | 1.15 | h01d97ff_1005 | conda-forge |  
 | libkml | 1.3.0 |  hed7d534_1010 | conda-forge |  
 | liblapack |  3.8.0 | 7_openblas | conda-forge |  
 | libnetcdf |  4.6.2 |  h1a02027_1002 | conda-forge |  
 | libpng | 1.6.37 |  h2573ce8_0 | conda-forge |  
 | libpq |  11.3 |  h56406e1_0 | conda-forge |  
 | libspatialindex |  1.9.0 | h6de7cb9_1 | conda-forge |  
 | libspatialite |  4.3.0a | he900ada_1028 | conda-forge |  
 | libssh2 |  1.8.2 | hcdc9a53_2 | conda-forge |  
 | libtiff |  4.0.10 | hd08fb8f_1003 | conda-forge |  
 | libxml2 |  2.9.9 | hd80cff7_0 | conda-forge |  
 | lz4-c |  1.8.3 |  h6de7cb9_1001 | conda-forge |  
 | mapclassify |  2.0.1 | py_0 | conda-forge |  
 | markupsafe | 1.1.1 | py37h1de35cc_0 | conda-forge |  
 | matplotlib | 3.1.0 | py37_1 | conda-forge |  
 | matplotlib-base |  3.1.0 | py37h3a684a6_1 | conda-forge |  
 | munch |  2.3.2 | py_0 | conda-forge |  
 | ncurses |  6.1 |  h0a44026_1002 | conda-forge |  
 | networkx | 2.3 | py_0 | conda-forge |  
 | numpy |  1.16.4 |  py37h6b0580a_0 | conda-forge |  
 | openblas | 0.3.5 |  h436c29b_1001 | conda-forge |  
 | openjpeg | 2.3.1 | hc1feee7_0 | conda-forge |  
 | openssl |  1.1.1b |  h01d97ff_2 | conda-forge |  
 | osmnx |  0.10 |  py_1 | conda-forge |  
 | pandas | 0.24.2 |  py37h86efe34_0 | conda-forge |  
 | pcre | 8.41 | h0a44026_1003 | conda-forge |  
 | pip |  19.1.1 |  py37_0 | conda-forge |  
 | pixman | 0.38.0 | h01d97ff_1003 | conda-forge |  
 | poppler |  0.67.0 |  hb974355_6 | conda-forge |  
 | poppler-data | 0.4.9 |  1 | conda-forge |  
 | postgresql | 11.3 |  hf10c77c_0 | conda-forge |  
 | proj4 |  6.1.0 | h2cc77ee_2 | conda-forge |  
 | pycparser |  2.19 |  py37_1 | conda-forge |  
 | pygsp |  0.5.1 | pypi_0 | pypi |  
 | pyopenssl |  19.0.0 |  py37_0 | conda-forge |  
 | pyparsing |  2.4.0 | py_0 | conda-forge |  
 | pyproj | 2.2.0 | pypi_0 | pypi |  
 | pyrsistent | 0.15.2 |  py37h01d97ff_0 | conda-forge |  
 | pysocks |  1.7.0 | py37_0 | conda-forge |  
 | python | 3.7.3 | h0d93f26_0 | conda-forge |  
 | python-dateutil |  2.8.0 | py_0 | conda-forge |  
 | pytz | 2019.1 |  py_0 | conda-forge |  
 | pyunlocbox | 0.5.2 | py_0 | conda-forge |  
 | readline | 7.0 |  hcfe32e1_1001 | conda-forge |  
 | requests | 2.22.0 |  py37_0 | conda-forge |  
 | rtree |  0.8.3 |  py37h666c49c_1002 | conda-forge |  
 | scipy |  1.3.0 | py37hab3da7d_0 | conda-forge |  
 | setuptools | 41.0.1 |  py37_0 | conda-forge |  
 | shapely |  1.6.4 |  py37h79c6f3e_1005 | conda-forge |  
 | six |  1.12.0 |  pypi_0 | pypi |  
 | sqlite | 3.28.0 |  h9721f7c_0 | conda-forge |  
 | tk | 8.6.9 |  h2573ce8_1002 | conda-forge |  
 | toolz |  0.9.0 | py_1 | conda-forge |  
 | tornado |  6.0.3 | py37h01d97ff_0 | conda-forge |  
 | tzcode | 2019a |  h01d97ff_1002 | conda-forge |  
 | urllib3 |  1.25.3 |  pypi_0 | pypi |  
 | vincent |  0.4.4 | py_1 | conda-forge |  
 | wheel |  0.33.4 |  py37_0 | conda-forge |  
 | xerces-c | 3.2.2 |  h44e365a_1001 | conda-forge |  
 | xz | 5.2.4 |  h1de35cc_1001 | conda-forge |  
 | zlib | 1.2.11 | h1de35cc_1004 | conda-forge |  
 | zstd | 1.4.0 | ha9f0a20_0 | conda-forge |  
</details>

#### List Win Environment
<details>  

| Name | Version |  Build | Channel |
| ------ | ------- | ------ | -------- |
| altair | 3.1.0 | py37_0 | conda-forge | 
| asn1crypto | 0.24.0 | py37_1003 | conda-forge | 
| astroid | 2.2.5 | pypi_0 | pypi | 
| atomicwrites | 1.3.0 | py_0 | conda-forge | 
| attrs | 19.1.0 | py_0 | conda-forge | 
| awscli | 1.16.172 | pypi_0 | pypi | 
| backcall | 0.1.0 | py_0 | conda-forge | 
| beautifulsoup4 | 4.7.1 | py37_1 | anaconda | 
| blas | 1.0 | mkl | 
| bleach | 3.1.0 | py_0 | conda-forge | 
| bokeh | 1.2.0 | py37_0 | conda-forge | 
| boost-cpp | 1.68.0 | h6a4c333_1000 | conda-forge | 
| botocore | 1.12.162 | pypi_0 | pypi | 
| branca | 0.3.1 | py_0 | conda-forge | 
| bzip2 | 1.0.6 | hfa6e2cd_1002 | conda-forge | 
| ca-certificates | 2019.5.15 | 0 | anaconda | 
| cartopy | 0.17.0 | py37h814cdbc_1004 | conda-forge | 
| certifi | 2019.3.9 | py37_0 | anaconda | 
| cffi | 1.12.3 | py37hb32ad35_0 | conda-forge | 
| cftime | 1.0.3.4 | py37h452e1ab_1001 | conda-forge | 
| chardet | 3.0.4 | py37_1003 | conda-forge | 
| click | 7.0 | py_0 | conda-forge | 
| click-plugins | 1.1.1 | py_0 | conda-forge | 
| cligj | 0.5.0 | py_0 | conda-forge | 
| cloudpickle | 1.0.0 | py_0 | conda-forge | 
| colorama | 0.3.9 | pypi_0 | pypi | 
| colorcet | 2.0.1 | py_0 | pyviz/label/dev | 
| cryptography | 2.6.1 | py37hb32ad35_0 | conda-forge | 
| cudatoolkit | 10.0.130 | 0 | 
| curl | 7.64.0 | h4496350_2 | conda-forge | 
| cvxopt | 1.2.3 | pypi_0 | pypi | 
| cvxpy | 1.0.23 | pypi_0 | pypi | 
| cycler | 0.10.0 | py_1 | conda-forge | 
| cytoolz | 0.9.0.1 | py37hfa6e2cd_1001 | conda-forge | 
| dask | 1.2.2 | py_0 | conda-forge | 
| dask-core | 1.2.2 | py_0 | conda-forge | 
| datashader | 0.7.0 | py_0 | pyviz/label/dev | 
| datashape | 0.5.4 | py_1 | conda-forge | 
| decorator | 4.4.0 | py_0 | conda-forge | 
| defusedxml | 0.5.0 | py_1 | conda-forge | 
| descartes | 1.1.0 | py_3 | conda-forge | 
| dill | 0.2.9 | pypi_0 | pypi | 
| distributed | 1.28.1 | py37_0 | conda-forge | 
| docutils | 0.14 | pypi_0 | pypi | 
| ecos | 2.0.7.post1 | pypi_0 | pypi | 
| entrypoints | 0.3 | py37_1000 | conda-forge | 
| expat | 2.2.5 | he025d50_1002 | conda-forge | 
| fastparquet | 0.3.1 | py37hfa6e2cd_0 | conda-forge | 
| fiona | 1.8.6 | py37hce0be61_3 | conda-forge | 
| folium | 0.9.1 | py_0 | conda-forge | 
| freetype | 2.10.0 | h5db478b_0 | conda-forge | 
| freexl | 1.0.5 | hd288d7e_1002 | conda-forge | 
| future | 0.17.1 | pypi_0 | pypi | 
| gdal | 2.4.1 | py37hdf5ee75_0 | conda-forge | 
| geographiclib | 1.49 | py_0 | conda-forge | 
| geopandas | 0.5.0 | py_2 | conda-forge | 
| geopy | 1.20.0 | py_0 | conda-forge | 
| geos | 3.7.1 | he025d50_1000 | conda-forge | 
| geotiff | 1.4.3 | h8408f58_1000 | conda-forge | 
| geoviews | 1.6.2 | pypi_0 | pypi | 
| gettext | 0.19.8.1 | hb01d8f6_1002 | conda-forge | 
| glib | 2.58.3 | hc0c2ac7_1001 | conda-forge | 
| gurobi | 8.1.1 | py37_0 | gurobi | 
| hdf4 | 4.2.13 | hf8e6fe8_1002 | conda-forge | 
| hdf5 | 1.10.4 | nompi_hcc15c50_1106 | conda-forge | 
| heapdict | 1.0.0 | py37_1000 | conda-forge | 
| holoviews | 1.12.3 | pypi_0 | pypi | 
| hvplot | 0.4.0 | pypi_0 | pypi | 
| icc_rt | 2019.0.0 | h0cc432a_1 | 
| icu | 58.1 | vc14_0 | conda-forge | 
| idna | 2.8 | py37_1000 | conda-forge | 
| imageio | 2.5.0 | py37_0 | conda-forge | 
| intel-openmp | 2019.0 | pypi_0 | pypi | 
| ipykernel | 5.1.1 | pypi_0 | pypi | 
| ipython | 7.5.0 | py37h39e3cac_0 | conda-forge | 
| ipython_genutils | 0.2.0 | py_1 | conda-forge | 
| ipywidgets | 7.4.2 | pypi_0 | pypi | 
| isort | 4.3.20 | pypi_0 | pypi | 
| jedi | 0.13.3 | py37_0 | conda-forge | 
| jinja2 | 2.10.1 | py_0 | conda-forge | 
| jmespath | 0.9.4 | pypi_0 | pypi | 
| jpeg | 9c | hfa6e2cd_1001 | conda-forge | 
| jsonschema | 3.0.1 | py37_0 | conda-forge | 
| jupyter | 1.0.0 | pypi_0 | pypi | 
| jupyter-client | 5.2.4 | pypi_0 | pypi | 
| jupyter-console | 6.0.0 | pypi_0 | pypi | 
| jupyter-core | 4.4.0 | pypi_0 | pypi | 
| kealib | 1.4.10 | heacb130_1003 | conda-forge | 
| kiwisolver | 1.1.0 | py37he980bc4_0 | conda-forge | 
| krb5 | 1.16.3 | hdd46e55_1001 | conda-forge | 
| lapack | 3.6.1 | h8933c1f_2 | conda-forge | 
| lazy-object-proxy | 1.4.1 | pypi_0 | pypi | 
| libblas | 3.8.0 | 10_mkl | conda-forge | 
| libcblas | 3.8.0 | 10_mkl | conda-forge | 
| libcurl | 7.64.0 | h4496350_2 | conda-forge | 
| libffi | 3.2.1 | h6538335_1006 | conda-forge | 
| libgdal | 2.4.1 | he26aab1_0 | conda-forge | 
| libiconv | 1.15 | hfa6e2cd_1005 | conda-forge | 
| libkml | 1.3.0 | h4fd0f3b_1009 | conda-forge | 
| liblapack | 3.8.0 | 10_mkl | conda-forge | 
| libnetcdf | 4.6.2 | h396784b_1001 | conda-forge | 
| libpng | 1.6.37 | h7602738_0 | conda-forge | 
| libpq | 11.3 | hb0bdaea_0 | conda-forge | 
| libsodium | 1.0.16 | h2fa13f4_1001 | conda-forge | 
| libspatialindex | 1.8.5 | he025d50_4 | conda-forge | 
| libspatialite | 4.3.0a | h6a0152f_1026 | conda-forge | 
| libssh2 | 1.8.2 | h642c060_2 | conda-forge | 
| libtiff | 4.0.10 | h36446d0_1001 | conda-forge | 
| libxml2 | 2.9.9 | h9ce36c8_0 | conda-forge | 
| libxslt | 1.1.32 | heafd4d3_1002 | conda-forge | 
| llvmlite | 0.28.0 | py37_0 | conda-forge | 
| locket | 0.2.0 | py_2 | conda-forge | 
| lxml | 4.3.3 | py37heafd4d3_0 | conda-forge | 
| m2w64-expat | 2.1.1 | 2 | 
| m2w64-gcc-libgfortran | 5.3.0 | 6 | 
| m2w64-gcc-libs | 5.3.0 | 7 | 
| m2w64-gcc-libs-core | 5.3.0 | 7 | 
| m2w64-gettext | 0.19.7 | 2 | 
| m2w64-gmp | 6.1.0 | 2 | 
| m2w64-libiconv | 1.14 | 6 | 
| m2w64-libwinpthread-git5.0.0.4634.697f757 | 2 | 
| m2w64-xz | 5.2.2 | 2 | 
| mapclassify | 2.0.1 | py_0 | conda-forge | 
| markdown | 2.6.11 | py_0 | conda-forge | 
| markupsafe | 1.1.1 | py37hfa6e2cd_0 | conda-forge | 
| matplotlib | 3.1.0 | py37_1 | conda-forge | 
| matplotlib-base | 3.1.0 | py37h2852a4a_1 | conda-forge | 
| mccabe | 0.6.1 | pypi_0 | pypi | 
| miktex | 2.9.6753 | h2fa13f4_1000 | conda-forge | 
| mistune | 0.8.4 | py37hfa6e2cd_1000 | conda-forge | 
| mkl | 2019.0 | pypi_0 | pypi | 
| more-itertools | 4.3.0 | py37_1000 | conda-forge | 
| msgpack-python | 0.6.1 | py37he980bc4_0 | conda-forge | 
| msys2-conda-epoch | 20160418 | 1 | 
| multipledispatch | 0.6.0 | py_0 | conda-forge | 
| multiprocess | 0.70.7 | pypi_0 | pypi | 
| munch | 2.3.2 | py_0 | conda-forge | 
| nbconvert | 5.5.0 | pypi_0 | pypi | 
| nbformat | 4.4.0 | pypi_0 | pypi | 
| netcdf4 | 1.5.1.2 | py37h2b7c3b1_0 | conda-forge | 
| networkx | 2.3 | py_0 | conda-forge | 
| notebook | 5.7.8 | pypi_0 | pypi | 
| numba | 0.43.1 | py37hf9181ef_0 | 
| numpy | 1.16.3 | py37h873a0b8_0 | conda-forge | 
| olefile | 0.46 | py_0 | conda-forge | 
| openjpeg | 2.3.1 | ha922770_0 | conda-forge | 
| openssl | 1.1.1 | he774522_0 | anaconda | 
| osmium | 2.15.2 | pypi_0 | pypi | 
| osmnx | 0.10 | py_0 | conda-forge | 
| osqp | 0.5.0 | pypi_0 | pypi | 
| owslib | 0.17.1 | py_0 | conda-forge | 
| packaging | 19.0 | py_0 | conda-forge | 
| pandas | 0.24.2 | py37he350917_0 | conda-forge | 
| pandoc | 2.7.2 | 0 | conda-forge | 
| pandocfilters | 1.4.2 | py_1 | conda-forge | 
| panel | 0.6.0a1 | py_0 | pyviz/label/dev | 
| param | 1.9.1a2 | py_0 | pyviz/label/dev | 
| parso | 0.4.0 | py_0 | conda-forge | 
| partd | 0.3.9 | py_0 | conda-forge | 
| pcre | 8.41 | h6538335_1003 | conda-forge | 
| phantomjs | 2.1.1 | 0 | pyviz/label/dev | 
| pickleshare | 0.7.5 | py37_1000 | conda-forge | 
| pillow | 6.0.0 | py37h9a613e6_0 | conda-forge | 
| pip | 19.1.1 | py37_0 | conda-forge | 
| pluggy | 0.11.0 | py_0 | conda-forge | 
| poppler | 0.67.0 | heddaa77_6 | conda-forge | 
| poppler-data | 0.4.9 | 1 | conda-forge | 
| postgresql | 11.3 | h06f7779_0 | conda-forge | 
| proj4 | 5.2.0 | h6538335_1002 | conda-forge | 
| prometheus_client | 0.6.0 | py_0 | conda-forge | 
| prompt_toolkit | 2.0.9 | py_0 | conda-forge | 
| psutil | 5.6.2 | py37hfa6e2cd_0 | conda-forge | 
| py | 1.8.0 | py_0 | conda-forge | 
| pyasn1 | 0.4.5 | pypi_0 | pypi | 
| pycparser | 2.19 | py37_1 | conda-forge | 
| pyct | 0.4.6 | py_0 | pyviz/label/dev | 
| pyct-core | 0.4.6 | py_0 | pyviz/label/dev | 
| pyepsg | 0.4.0 | py_0 | conda-forge | 
| pygments | 2.4.1 | py_0 | conda-forge | 
| pykdtree | 1.3.1 | py37h452e1ab_1002 | conda-forge | 
| pylint | 2.3.1 | pypi_0 | pypi | 
| pyopenssl | 19.0.0 | py37_0 | conda-forge | 
| pyparsing | 2.4.0 | py_0 | conda-forge | 
| pyproj | 1.9.6 | py37hfa6e2cd_1002 | conda-forge | 
| pyqt | 5.9.2 | py37h6538335_0 | conda-forge | 
| pyrsistent | 0.15.2 | py37hfa6e2cd_0 | conda-forge | 
| pyshp | 2.1.0 | py_0 | conda-forge | 
| pysocks | 1.7.0 | py37_0 | conda-forge | 
| pytest | 4.5.0 | py37_0 | conda-forge | 
| python | 3.7.3 | hb12ca83_0 | conda-forge | 
| python-dateutil | 2.8.0 | py_0 | conda-forge | 
| python-snappy | 0.5.4 | py37hd25c944_0 | conda-forge | 
| pytz | 2019.1 | py_0 | conda-forge | 
| pyviz | 0.10.0 | pypi_0 | pypi | 
| pyviz_comms | 0.7.2 | py_0 | pyviz/label/dev | 
| pywavelets | 1.0.3 | py37h452e1ab_1 | conda-forge | 
| pywinpty | 0.5.5 | py37_1000 | conda-forge | 
| pyyaml | 3.13 | pypi_0 | pypi | 
| pyzmq | 18.0.1 | py37he7828b0_1 | conda-forge | 
| qt | 5.9.7 | hc6833c9_1 | conda-forge | 
| qtconsole | 4.5.1 | pypi_0 | pypi | 
| requests | 2.22.0 | py37_0 | conda-forge | 
| rsa | 3.4.2 | pypi_0 | pypi | 
| rtree | 0.8.3 | py37h21ff451_1002 | conda-forge | 
| s3transfer | 0.2.1 | pypi_0 | pypi | 
| scikit-image | 0.15.0 | py37h6538335_0 | conda-forge | 
| scipy | 1.2.1 | py37h29ff71c_0 | 
| scs | 2.1.0 | pypi_0 | pypi | 
| selenium | 3.141.0 | py37hfa6e2cd_1000 | conda-forge | 
| send2trash | 1.5.0 | py_0 | conda-forge | 
| setuptools | 41.0.1 | py37_0 | conda-forge | 
| shapely | 1.6.4 | py37h8921fb9_1004 | conda-forge | 
| sip | 4.19.8 | py37h6538335_1000 | conda-forge | 
| six | 1.12.0 | py37_1000 | conda-forge | 
| snappy | 1.1.7 | h6538335_1002 | conda-forge | 
| sortedcontainers | 2.1.0 | py_0 | conda-forge | 
| soupsieve | 1.8 | py37_0 | anaconda | 
| sqlite | 3.28.0 | hfa6e2cd_0 | conda-forge | 
| streamz | 0.5.1 | py_0 | conda-forge | 
| tblib | 1.4.0 | py_0 | conda-forge | 
| terminado | 0.8.2 | py37_0 | conda-forge | 
| testpath | 0.3.1 | py37_1 | conda-forge | 
| thrift | 0.11.0 | py37h6538335_1001 | conda-forge | 
| tk | 8.6.9 | hfa6e2cd_1001 | conda-forge | 
| toolz | 0.9.0 | py_1 | conda-forge | 
| tornado | 6.0.2 | py37hfa6e2cd_0 | conda-forge | 
| tqdm | 4.32.1 | py_0 | conda-forge | 
| traitlets | 4.3.2 | py37_1000 | conda-forge | 
| typed-ast | 1.4.0 | pypi_0 | pypi | 
| urllib3 | 1.24.3 | py37_0 | conda-forge | 
| vc | 14.1 | h21ff451_3 | anaconda | 
| vincent | 0.4.4 | py_1 | conda-forge | 
| vs2015_runtime | 15.5.2 | 3 | anaconda | 
| wcwidth | 0.1.7 | py_1 | conda-forge | 
| webencodings | 0.5.1 | py_1 | conda-forge | 
| wheel | 0.33.4 | py37_0 | conda-forge | 
| widgetsnbextension | 3.4.2 | pypi_0 | pypi | 
| win_inet_pton | 1.1.0 | py37_0 | conda-forge | 
| wincertstore | 0.2 | py37_1002 | conda-forge | 
| winpty | 0.4.3 | 4 | conda-forge | 
| wrapt | 1.11.1 | pypi_0 | pypi | 
| xarray | 0.12.1 | py_0 | conda-forge | 
| xerces-c | 3.2.2 | h6538335_1001 | conda-forge | 
| xz | 5.2.4 | h2fa13f4_1001 | conda-forge | 
| yaml | 0.1.7 | hfa6e2cd_1001 | conda-forge | 
| zeromq | 4.3.1 | he025d50_1000 | conda-forge | 
| zict | 0.1.4 | py_0 | conda-forge | 
| zlib | 1.2.11 | h2fa13f4_1004 | conda-forge
</details>

Any idea how to tackle this problem ?

**Comment by bonakdarf92** [comment]
Solved the Problem. Probably the error occured because of mismatches from conda environments between MacOS and Win10. Once you got an running environment (Win10) you have to export it via

```terminal
(working env) $ conda env export --no-builds | grep -v "^prefix: " > env.yml
```
Then you need do delete all OS dependent lines e.g. 
msys...,
vs_2015, 
winpy... 
etc. 
which causes error when starting to recreate a copy of the environment with
```terminal
conda env create -f env.yml
```
If you find any other plausible answer for the error let me know because its more a workaround and not a solution to the IllegalArgumentException

**Comment by obinnam** [comment]
Hi guys,
I'm new to geospatial analytics and I try to import data into pycharm or jupyter and I have this error

Shell is not a LinearRing
IllegalArgumentException: geometries must not contain null elements

My lines:

`import pandas as pd
import geopandas as gpd
import gdal
import shapely
import fiona
from geopandas import GeoDataFrame
from pandas import DataFrame`

**Comment by gboeing** [comment]
@obinnam I'm not clear what you're asking, but you don't appear to be using OSMnx in your code snippet.
