### ISSUE TITLE
Enhancement: Arrows and edge annotations in plot_graph

### ISSUE THREAD

**Issue by ppintosilva** [gboeing/osmnx#309]
Hi @gboeing . If we have a graph and wish to zoom in on a particular junction (by passing a value to bbox) to understand what's going on, it could be useful to have additional arguments to plot the direction of traffic flow and annotate edges, with street names for instance.

I was wondering if you've thought about this enhancement before and if it's worth drafting a pull request.

Cheers.

**Comment by gboeing** [comment]
That's an interesting idea. But I wonder if OSMnx is the right place for that functionality, given that GIS tools can do it relatively easily? Typically when I'm trying to better understand some section of the graph, I'll just dump it to shapefile > open in QGIS > click/explore interactively (to see street names, directionality, etc). Thoughts?

**Comment by ppintosilva** [comment]
Yes, that is probably the sound thing to do. I'm still very much a rookie at GIS and hence not very familiar with the whole spatial analysis ecosystem, tools and workflow.

But what got me thinking about this, is the fact that I have 200+ traffic cameras, which I'm trying to merge with the road graph, based on location, address and camera orientation. Validating this at scale is a bit tricky and for that I'm generating a close up figure of the surrounding road network for each camera (~200 meter bbox). So far, I generate a pair of figures for every camera (example below):

Unmerged |  Merged
:-------------------------:|:-------------------------:
![24](https://user-images.githubusercontent.com/11331882/60976526-be19f380-a325-11e9-8ff1-8cb1c00aa340.png)|![24](https://user-images.githubusercontent.com/11331882/60977317-24534600-a327-11e9-8f4a-5cf2633e857b.png)

At first it seems that camera 25 is being projected to the wrong edge, but after I've looked at the direction of traffic flow in Google Maps, it's actually fine. This would be straightforward to see by annotating the graph with arrows and street names.

But like you've suggested, I'm probably better off using other GIS tools? Do you think I can do this at scale with QGIS instead?

**Comment by gboeing** [comment]
I think this workflow would be best-suited to something like QGIS. One other option would be to save the OSMnx graph to Folium/Leaflet and add your annotations there as an interactive web map: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.plot.plot_graph_folium
