### ISSUE TITLE
Error loading building outlines

### ISSUE THREAD

**Issue by ldodds** [gboeing/osmnx#31]
I'm trying to follow [the building outline example](https://github.com/gboeing/osmnx/blob/master/examples/10-building-footprints.ipynb) for my city, but am having problems retrieving the data.

I've tried:

```
gdf = ox.buildings_from_place(place='Bath, United Kingdom')
```

But this generates:

```
Retrieved response from cache file "cache/4dd9e9bd0481bfc73438754979de4014.json" for URL "https://nominatim.openstreetmap.org/search?format=json&limit=1&dedupe=0&polygon_geojson=1&q=Bath%2C+United+Kingdom"
OSM returned a Point as the geometry.
Created GeoDataFrame with 1 row for query "Bath, United Kingdom"
Projected the GeoDataFrame "geometry to project" to UTM-30 in 0.00 seconds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ldodds/tools/anaconda2/envs/OSMNX/lib/python2.7/site-packages/osmnx/buildings.py", line 225, in buildings_from_place
    return create_buildings_gdf(polygon)
  File "/home/ldodds/tools/anaconda2/envs/OSMNX/lib/python2.7/site-packages/osmnx/buildings.py", line 120, in create_buildings_gdf
    results = osm_bldg_download(polygon, north, south, east, west)
  File "/home/ldodds/tools/anaconda2/envs/OSMNX/lib/python2.7/site-packages/osmnx/buildings.py", line 85, in osm_bldg_download
    geometry_proj_consolidated_subdivided = consolidate_subdivide_geometry(geometry_proj, max_query_area_size=max_query_area_size)
  File "/home/ldodds/tools/anaconda2/envs/OSMNX/lib/python2.7/site-packages/osmnx/core.py", line 550, in consolidate_subdivide_geometry
    raise ValueError('Geometry must be a shapely Polygon or MultiPolygon')
ValueError: Geometry must be a shapely Polygon or MultiPolygon
```

The cache file contains:

```
[{"display_name": "Bath, South West England, England, BA1, UK", "importance": 0.70803439318359, "place_id": "104804", "lon": "-2.3596962", "geojson": {"type": "Point", "coordinates": [-2.3596962, 51.3813864]}, "lat": "51.3813864", "osm_type": "node", "licence": "Data \u00a9 OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright", "osm_id": "1947201", "boundingbox": ["51.2213864", "51.5413864", "-2.5196962", "-2.1996962"], "type": "city", "class": "place", "icon": "https://nominatim.openstreetmap.org/images/mapicons/poi_place_city.p.20.png"}]
```

I notice with the Piedmont example the node that is returned is of type boundary. So I thought it might be having problems resolving the right location.

I've also tried specifying the point as a lat, long and instead called `buildings_from_point` but this also fails (`KeyError: 'geometry') which I suspect is also data related. 

However OSM does seem to have building outlines for the city:

http://www.openstreetmap.org/node/1947201#map=17/51.38146/-2.35869

Any ideas?

**Comment by gboeing** [comment]
> I notice with the Piedmont example the node that is returned is of type boundary. So I thought it might be having problems resolving the right location.

You're on the right track. To use the `graph_from_place` or `buildings_from_place` functions, you need to provide a place name query string that the Nominatim API can geocode to an entity that has polygon geojson data. "Bath, United Kingdom" does not, as you can see directly from [the API](https://nominatim.openstreetmap.org/search?polygon_geojson=1&format=json&q=Bath,UK&limit=10). As you saw, the geojson type was Point and the error message you got was that the geometry must instead be a Polygon or MultiPolygon to query for elements within the geometry.

So you have three options: you could get buildings by polygon, address, or point. First off, if you have a shapefile of Bath's boundaries, you could pass that polygon in to `buildings_from_polygon`. Second, with a city name as address, you could do:

```python
gdf = ox.buildings_from_address('Bath, England', distance=500)
fig, ax = ox.plot_buildings(ox.project_gdf(gdf))
```

Third, you could pass a (lat, lng) point to `buildings_from_point`. I'm guessing from the error you received that you instead passed it a (lng, lat) point -- this is the format in which Nominatim returns the point `[-2.3596962, 51.3813864]` -- but OSMnx uses the standard geographic (lat, lng) format instead:

```python
gdf = ox.buildings_from_point((51.3813864, -2.3596962), distance=500)
fig, ax = ox.plot_buildings(ox.project_gdf(gdf))
```

See the [documentation for more](https://osmnx.readthedocs.io/en/latest/osmnx.html#module-osmnx.buildings).

**Comment by gboeing** [comment]
@ldodds did that resolve the issue?

**Comment by ldodds** [comment]
@gboeing I've not had chance to try this yet, but your answer confirms that my main issue is how I'm looking up the data for bath. I'll try again and will reopen this if I still have issues.

Thanks for the detailed response. In case you're interested, I had success elsewhere: https://twitter.com/ldodds/status/830435740987301888 thanks for creating such a useful tool!
