### ISSUE TITLE
Get all country data 

### ISSUE THREAD

**Issue by JiweiZh** [gboeing/osmnx#310]
Hi, I want to get the graph for whole country to calculte the distance between some points, my code is like this: 

```
ox.config(use_cache=True, log_console=True)
G = ox.graph_from_place('France', network_type='drive', which_rresult=2)
```

But I think that is too large, so I got python request's time out errors each time, I try to change these two parameters: max_query_area_size, timeout, but I seem also take so much time. 

Is this the right way to get all the graph for the whole country ? or some other way?  

Thx a lot!

**Comment by gboeing** [comment]
Your `which_result` argument is misspelled. But the main issue here will be RAM on your computer. OSMnx automatically handles large queries, subdividing them so the API can handle it. But your computer needs enough memory to construct a massive country-wide graph. You might want to filter to only retain freeways or something like that if memory is an issue.

In general, the issue tracker is for documenting bugs or proposing new features. Best to ask how-to questions at the user community on StackOverflow, per the contributing guidelines.
