### ISSUE TITLE
slightly shifted nodes

### ISSUE THREAD

**Issue by jermaine1ronquillo** [gboeing/osmnx#312]
I'm using osmnx to extract lines and nodes and the coordinate system is changed to UTM then I convert it into a hydraulic model. To check if the hydraulic model coincides with the map from which it was extracted I would open it in QGIS, however based on the image below, the nodes are slightly shifted. Is there a way to check why this happen?

![image](https://user-images.githubusercontent.com/15191328/61166713-e93e5600-a564-11e9-8400-c63708dd5d8d.png)

**Comment by gboeing** [comment]
Before you project it to UTM, check a node in the graph's x and y coordinates. Then look up that node on OSM and double check the x and y match what you've got in your graph. Assuming everything came in correctly, double-check the projection process. It looks like the projections don't perfectly line up, so make sure they're precisely identical.

**Comment by jermaine1ronquillo** [comment]
Below is the image if the xy coordinates are in lat long, and it shows the there is something in the process of converting to UTM, however, i am only using this "P_projected=ox.project_graph(P)" to convert to UTM.  
am i missing some pre-pocessing before converting to UTM or is there a way to increase the precision of the lat long coordinates before converting to UTM?

![image](https://user-images.githubusercontent.com/15191328/61178815-9af28b00-a628-11e9-9c60-97b2ac8beedc.png)
  
and one more thing, some of the roads seen on the image don't have lines.

**Comment by gboeing** [comment]
You shouldn't need to increase the precision. You can pass a `to_crs` argument to define a precise projection you want, and then verify that you are using precisely the same projection in QGIS: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.projection.project_graph

**Comment by jermaine1ronquillo** [comment]
Thank you for the response, i'm closing this for now
