### ISSUE TITLE
Connectivity error (graph from polygon) 

### ISSUE THREAD

**Issue by BrunoEduardoCSantos** [gboeing/osmnx#313]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
I would expect to convert a random polygon from shapely to a direct acyclic graph in osmnx .

#### What operating system, architecture, Python version, and OSMnx version are you using?
0.10
#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
IllegalArgumentException: RobustDeterminant encountered non-finite numbers 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-761168cb7b7e> in <module>
      3 import networkx as nx
      4 
----> 5 G6 = ox.graph_from_polygon(poly, network_type='walk')

/usr/local/lib/python3.5/dist-packages/osmnx/core.py in graph_from_polygon(polygon, network_type, simplify, retain_all, truncate_by_edge, name, timeout, memory, max_query_area_size, clean_periphery, infrastructure, custom_filter)
   1741         buffer_dist = 500
   1742         polygon_utm, crs_utm = project_geometry(geometry=polygon)
-> 1743         polygon_proj_buff = polygon_utm.buffer(buffer_dist)
   1744         polygon_buffered, _ = project_geometry(geometry=polygon_proj_buff, crs=crs_utm, to_latlong=True)
   1745 

~/.local/lib/python3.5/site-packages/shapely/geometry/base.py in buffer(self, distance, resolution, quadsegs, cap_style, join_style, mitre_limit)
    582                 'Cannot compute offset from zero-length line segment')
    583         if cap_style == CAP_STYLE.round and join_style == JOIN_STYLE.round:
--> 584             return geom_factory(self.impl['buffer'](self, distance, res))
    585 
    586         if 'buffer_with_style' not in self.impl:

~/.local/lib/python3.5/site-packages/shapely/geometry/base.py in geom_factory(g, parent)
     74     # Abstract geometry factory for use with topological methods below
     75     if not g:
---> 76         raise ValueError("No Shapely geometry can be created from null value")
     77     ob = BaseGeometry()
     78     geom_type = geometry_type_name(g)

ValueError: No Shapely geometry can be created from null value

</details>

#### Code snippet that independently and completely reproduces the issue

```python
 from shapely.geometry import Point,Polygon
import geopandas as gpd
from fiona.crs import from_epsg
import matplotlib.pyplot as plt
#Create an empty GeoDataFrame

data= gpd.GeoDataFrame()

data['geometry']= None

coordinates= [(24.0555,60.000),(14.54545,100.123123),(24.53434,60.123132)]

poly= Polygon(coordinates)
#Insert the polygon into GeodataFrame
data.loc[0,'geometry'] = poly
data.loc[0,'Location']= 'SanSinati'
data.crs = from_epsg(3035)


data.plot(facecolor='blue');
# Convert polygon to graph network 
import osmnx as ox
import networkx as nx

G6 = ox.graph_from_polygon(poly, network_type='walk')
```

**Comment by gboeing** [comment]
A few thoughts.

1. Why do you expect a directed acyclic graph? Nearly all real world street networks include cycles.

2. There's no reason to believe that every random polygon will yield a street network: you'll only successfully get a graph back if you pass in a polygon within which OSM network infrastructure appears.

3. Building on point 2, your polygon is very strange. As you plot it in your code snippet, you can see that it is an extremely long triangle that spans over 40 degrees of latitude and 10 degrees of longitude. I'm not sure what you are aiming for, given that site boundary.

**Comment by BrunoEduardoCSantos** [comment]
Thanks for your feedback.
