### ISSUE TITLE
Feature Request - add orginal way direction

### ISSUE THREAD

**Issue by torbenf86** [gboeing/osmnx#314]
Hi,

thank you for the great package! 
I would suggest just one thing to add. As we are using the keys lane:backward and lane:forward in OSM, we need to know which direction backward and forward is. This information is present in OSM by the order of nodes in the way. But it is somehow dropped when using OSMNX. I would propose to add "original" direction of the edge. Right now, I see no possibilty how I can extract this information from the edge dataframe. 

Kind regards,
Torben

**Comment by gboeing** [comment]
@torbenf86 every edge contains `u` and `v` attributes denoting the direction the edge points (from node `u` to node `v`).

**Comment by torbenf86** [comment]
@gboeing 
Thanks Geoff. I think, I may have been unclear. An OSM way always points in a certain direction, right ? In OSMNX, an edge as part of this OSM way is created from node u to node v. Next, another edge with the opposite direction is created (except one-ways). Node u from the opposite edge is the original node v and node v from the opposite edge is the original node u. The consequence is that I cannot tell anymore which edge points in the original direction of the OSM way. Or am I mistaken here ?

Identifying the original direction is relevant in order to use the information in the keys lane:backward and lane:forward.

**Comment by torbenf86** [comment]
Any new thoughts on this ?

**Comment by gboeing** [comment]
@torbenf86 thanks for the ping. Been a busy summer. Yes you are right: an OSM way has a "direction" that corresponds to the way it was drawn and this would impact the interpretation of lanes:forward and lanes:backward. It could be useful to include edge attributes like `osm_way_u` and `osm_way_v` to denote the origin and destination nodes of the original OSM way.

**Comment by gboeing** [comment]
This has been dormant for a while, so I'm going to close it for now. If someone wants to pick it up and run with it in the future it can be revisited or reopened as needed!
