### ISSUE TITLE
Map matching GPS trajectory to OSM road network?

### ISSUE THREAD

**Issue by willgeary** [gboeing/osmnx#315]
Thank you so much for this wonderful library. The feature list in the OSMNX documentation  includes: "Fast map-matching of points, routes, or trajectories to nearest graph edges or nodes". I am hoping to match a GPS trajectory to OSM road network and return a list of node id's represented that path travelled. Is there map-matching functionality within OSMNX? Are there any examples available towards this end? Thank you!

**Comment by torbenf86** [comment]
@willgeary 
I am interested in this feature as well. You might look into OSRM online API for now. There are several Python packages which provide a wrapper around this API. But I still don't have any experience with it.

example: https://github.com/ustroetz/python-osrm

**Comment by philMarius** [comment]
I have used a variation of this with my application: https://github.com/valhalla/valhalla/blob/master/docs/meili/algorithms.md

The Viterbi algorithm for solving the HMM ran into a few issues but Dijkstra's works _almost_ perfectly for what I am trying to do.

**Comment by gboeing** [comment]
@willgeary OSMnx provides basic functionality for matching GPS points to graph nodes and/or edges. Probably the most relevant to your inquiry would be `ox.get_nearest_edges` which was released in v0.9 and is documented here: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils.get_nearest_edges

See also #234 for more details.

There's also some discussion/development of a better spatial index for these operations in #284

**Comment by nreinicke** [comment]
@willgeary - This question was asked a while ago but we've recently open sourced a python package [mappymatch](https://github.com/NREL/mappymatch) that matches GPS traces to the OSM road network (and uses osmnx under the hood!)

**Comment by gboeing** [comment]
This looks great.
