### ISSUE TITLE
Getting Nearest Node on a Multidigraph

### ISSUE THREAD

**Issue by joshuageoghegan** [gboeing/osmnx#316]
I am writing a Python script which will loop through a set of points and using a multigraph find the shortest path to another set of points. The multidigraph is created from a shp I output from QGIS. I have a function to create the multidigraph

>     def read_multi_shp(path):
>         try:
>             from osgeo import ogr
>     except ImportError:
>          raise ImportError("read_shp requires OGR: http://www.gdal.org/")
>     net = nx.MultiDiGraph() 
>     def getfieldinfo(lyr, feature, flds):
>             f = feature
>             return [f.GetField(f.GetFieldIndex(x)) for x in flds]
> 
>     def addlyr(lyr, fields):
>         for findex in range(lyr.GetFeatureCount()):
>             f = lyr.GetFeature(findex)
>             flddata = getfieldinfo(lyr, f, fields)
>             g = f.geometry()
>             attributes = dict(zip(fields, flddata))
>             attributes["ShpName"] = lyr.GetName()
>             if g.GetGeometryType() == 1:  # point
>                 net.add_node((g.GetPoint_2D(0)), attributes)
>             if g.GetGeometryType() == 2:  # linestring
>                 attributes["Wkb"] = g.ExportToWkb()
>                 attributes["Wkt"] = g.ExportToWkt()
>                 attributes["Json"] = g.ExportToJson()
>                 last = g.GetPointCount() - 1
>                 net.add_edge(g.GetPoint_2D(0), g.GetPoint_2D(last), attr_dict=attributes)
> 
>     if isinstance(path, str):
>         shp = ogr.Open(path)
>         lyrcount = shp.GetLayerCount()  # multiple layers indicate a directory
>         for lyrindex in range(lyrcount):
>             lyr = shp.GetLayerByIndex(lyrindex)
>             flds = [x.GetName() for x in lyr.schema]
>             addlyr(lyr, flds)
> 	
>     return net

When I try to get the nearest node to a point with 

>     H=read_multi_shp(path)
> 
>     PTV_Playground_Shortest_Path_300_400 = []
>     while i < len(PTV_Playground_Joined_initial):
> 		
>            orig_xy = (df.loc[i,"PTV_N"], df.loc[i,"PTV_E"])
> 
>            target_xy = (df.loc[i,"Playgroun1"], df.loc[i,"Playground"])
>            orig_node = ox.get_nearest_node(H, orig_xy, method='euclidean')
>     ......

I get the error

>      Traceback (most recent call last):
>      File "C:\Users\geogjo\Desktop\PythonTraining\Network_Analysis_Test.py", line 99, in <module>
>          orig_node = ox.get_nearest_node(H, orig_xy, method='euclidean') ####################getting key error x
>        File "C:\Users\geogjo\AppData\Local\Continuum\anaconda3\lib\site-packages\osmnx\utils.py", line 461, in get_nearest_node
>          coords = [[node, data['x'], data['y']] for node, data in G.nodes(data=True)]
>        File "C:\Users\geogjo\AppData\Local\Continuum\anaconda3\lib\site-packages\osmnx\utils.py", line 461, in <listcomp>
>          coords = [[node, data['x'], data['y']] for node, data in G.nodes(data=True)]
>      KeyError: 'x'
> 

How do get the nearest point of a multidigraph? is this error easily explainable?

**Comment by gboeing** [comment]
OSMnx is designed to construct graphs of street networks from OSM data. Accordingly, all of its functions expect all of its "expected machinery" to be present in the graph. If you want to use OSMnx on non-OSMnx created graphs, you'll need to make sure your graph exactly matches the format and contains all the same attributes as an OSMnx created graph (but this isn't really the use case OSMnx was designed for). For example, in your snippet it looks like your graph is missing attributes, such as the `x` coordinate.

**Comment by joshuageoghegan** [comment]
Thanks for that. I'll read more into it in that case.
