### ISSUE TITLE
Saving to .graphml destroys graph crs data

### ISSUE THREAD

**Issue by HughKelley** [gboeing/osmnx#317]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

Loading a multidigraph from OSM, the object has a crs value specified along with a few other values in a dict. 

Saving to a .graphml and reloading from that file results in a multidigraph missing all values that were previously stored in the  'graph.graph' dict. 

Is this expected behavior for the .graphml file type?

#### What operating system, architecture, Python version, and OSMnx version are you using?

Windows 10, Python 3.7.4  OSMNX 0.10

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>

Package         Version
--------------- -----------
attrs           19.1.0
certifi         2019.6.16
chardet         3.0.4
Click           7.0
click-plugins   1.1.1
cligj           0.5.0
cycler          0.10.0
decorator       4.4.0
descartes       1.1.0
Fiona           1.8.6
GDAL            2.4.1
GeoAlchemy2     0.6.3
geopandas       0.5.1
idna            2.8
kiwisolver      1.1.0
matplotlib      3.1.1
munch           2.3.2
networkx        2.3
numpy           1.16.4
osmnx           0.10
pandas          0.24.2
pip             19.1.1
psycopg2        2.8.3
pyparsing       2.4.0
pyproj          2.2.1
python-dateutil 2.8.0
pytz            2019.1
requests        2.22.0
Rtree           0.8.3
setuptools      41.0.1
Shapely         1.6.4.post2
six             1.12.0
SQLAlchemy      1.3.5
urllib3         1.25.3

</details>

#### Code snippet that independently and completely reproduces the issue

```
import osmnx as ox

# big bbox
north = 51.55975924
south = 51.45975924
east = -0.010389357
west = -0.2106266

# small bbox 
# half size
north = north - (north - south) / 4
south = south + (north - south) / 4
east = east + (west - east) / 4
west = west - (west - east) / 4

test_net = ox.graph_from_bbox(north, south, east, west, network_type = 'all_private', name = 'London_box')

print(test_net.graph['crs'])
# returns: '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'

# save to graphml
test_file = ox.save_graphml(test_net, filename = 'test.graphml', gephi = True)

new_net = ox.load_graphml('test.graphml')
new_net.graph['crs']

# returns: "Keyerror: 'crs'

```

**Comment by gboeing** [comment]
Interesting. Inside your `test.graphml` file, do you see the graph.graph dict keys and values anywhere? Is the issue that they're not being saved to the file, or is the issue that they're not being read from the file upon re-loading?

**Comment by HughKelley** [comment]
A control-f for "crs" came up blank so most likely it is a write problem not a read problem. 

There are plenty of other keys though. 

for instance:
```
  <key attr.name="maxspeed" attr.type="string" for="edge" id="d11" />
  <key attr.name="length" attr.type="string" for="edge" id="d10" />
  <key attr.name="highway" attr.type="string" for="edge" id="d9" />
  <key attr.name="geometry" attr.type="string" for="edge" id="d8" />
  <key attr.name="ref" attr.type="string" for="node" id="d7" />
  <key attr.name="highway" attr.type="string" for="node" id="d6" />
  <key attr.name="ycoord" attr.type="double" for="node" id="d5" />
  <key attr.name="xcoord" attr.type="double" for="node" id="d4" />
  <key attr.name="geometry" attr.type="string" for="node" id="d3" />
  <key attr.name="y" attr.type="string" for="node" id="d2" />
  <key attr.name="x" attr.type="string" for="node" id="d1" />
  <key attr.name="osmid" attr.type="string" for="node" id="d0" />
```

I've switched all of my network storage needs to using pickles, which has worked great since I don't need to access the data from any other software and don't need to collaborate with anyone.

**Comment by gboeing** [comment]
@HughKelley ah I see what's happening here. You set the argument `gephi=True`, which strips out the non-node/edge graph attributes to make the GraphML file comply with Gephi's specific format requirements:

https://github.com/gboeing/osmnx/blob/eb39dff4aaf726d33b6b7aa9f71c50f3e9b9f012/osmnx/save_load.py#L278

If you set `gephi=False`, your code works.
