### ISSUE TITLE
how to add node to the road network

### ISSUE THREAD

**Issue by ICDI0906** [gboeing/osmnx#318]
Hello~, I want to add some node to the road network. What do I need to do?

**Comment by gboeing** [comment]
You should begin by reading the documentation for OSMnx: https://osmnx.readthedocs.io/en/stable/

and for NetworkX: https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.MultiDiGraph.add_node.html

The issue tracker is for documenting bugs or proposing new features. Best to ask how-to questions at the user community on StackOverflow, per the contributing guidelines.

**Comment by ICDI0906** [comment]
> You should begin by reading the documentation for OSMnx: https://osmnx.readthedocs.io/en/stable/
> 
> and for NetworkX: https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.MultiDiGraph.add_node.html
> 
> The issue tracker is for documenting bugs or proposing new features. Best to ask how-to questions at the user community on StackOverflow, per the contributing guidelines.

OK, Thanks a lot!
