### ISSUE TITLE
How to get road network in Haiti's islands?

### ISSUE THREAD

**Issue by emanuelemassaro** [gboeing/osmnx#319]
I am trying to get the road network from Haiti. However even if I use coordinates or place I get the same road network. The road network does not include the islands of Haiti and this is the output. This is what I am doing:

```
place = 'Haiti'
G = ox.graph_from_place('Haiti', network_type='drive')
ox.plot_graph(G)
```
<img width="356" alt="Screen Shot 2019-07-30 at 12 54 06" src="https://user-images.githubusercontent.com/1876526/62123859-2296f580-b2c9-11e9-8ca7-08d6ff76c018.png">

**Comment by gboeing** [comment]
Read through the OSMnx documentation and try the `retain_all=True` argument: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_place

In general, the issue tracker is for documenting bugs or proposing new features. Best to ask how-to questions at the user community on StackOverflow, per the contributing guidelines and new issue template.
