### ISSUE TITLE
Incompatible library version 

### ISSUE THREAD

**Issue by rcagle4** [gboeing/osmnx#32]
#### Ran installation instructions 

```python
import osmnx as ox
%matplotlib inline
ox.config(log_file=True, log_console=True, use_cache=True)
```

Received error 
```
ImportError: dlopen(/Applications/anaconda/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Applications/anaconda/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 45.0.0 or later, but libpng16.16.dylib provides version 44.0.0
```

#### Last successful Terminal entry was...
[I 21:52:18.347 NotebookApp] Saving file at /Untitled1.ipynb
conda create --yes -c conda-forge -n OSMNX python=3.6 osmnx
source activate OSMNX
python -c 'import osmnx; print(osmnx.__version__)'
0.2.1

**Comment by gboeing** [comment]
See #25 for suggestions.

As this is an issue with conda installation (of dependencies) rather than with the OSMnx codebase, I'm going to close this here. Please feel free to open an issue at https://github.com/conda-forge/osmnx-feedstock/issues and we can assist there in the relevant repository.

**Comment by gboeing** [comment]
For future reference, see https://github.com/conda-forge/osmnx-feedstock/issues/14
