### ISSUE TITLE
using a postcode in osmnx 

### ISSUE THREAD

**Issue by sabrinadraude** [gboeing/osmnx#321]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Hiya, 
i've been trying to code using a user_input postcode to find the distance between two points in osmnx. However it seems you have to enter a node value not an address. Because this is user input I wouldn't expect the user to know the node that they are starting or ending at. 

Any feedback would be great. 

Cheers 

Here is my code: 
import networkx as nx
import osmnx as ox
graph = ox.graph_from_address('Cardiff, UK', 10000, network_type = 'drive', simplify = 'True')
#ox.plot_graph(graph)plots a graph of the area above in green.
#print (graph)
edges = ox.graph_to_gdfs(graph, nodes = False, edges = True)
user_input_start_postcode = input("What is your starting postcode?")
user_input_end_postcode = input("What is your end postcode?")
start_postcode = ox.graph_from_address() #not sure how to allow this to be a postcode input
end_postcode = ox.graph_from_address() #not sure how to allow this to be a postcode input
length = nx.shortest_path_length(G=graph, source=orig_node, target=target_node, weight='length')
print(length)#prints distance

**Comment by gboeing** [comment]
The issue tracker is for documenting bugs or proposing new features. Best to ask how-to questions at the user community on StackOverflow to get a useful answer, per the contributing guidelines and issue template.
