### ISSUE TITLE
Querying local osm data

### ISSUE THREAD

**Issue by DmitriyG228** [gboeing/osmnx#322]
Hi, this is the enchantment idea, rather than an issue. It has previously been discussed #51.

Just to make sure my understanding of how osmnx works is currect:

- If you want to query a big dataset (say, country) through overpass, that takes waaay long time to get it, since it does it in tiny chunks. 

- the resulting Graph object is not full does not fully correspond the initial dataset, and if you want to get extra features with footprints etc you have to query overpass again.

At the same time,  full dataset  for any part of the  world is available for a quick (few seconds) download [here](https://download.geofabrik.de/) and can possibly be queried locally with ease, right? 

If that is correct, that is at least not quite  sustainable to load overpass servers with heavy and time consuming requests.

If the community likes the idea I may try to implement this in future, though I have close to zero experience in working with python modules, so my code definitely will not be neat.

Thank you!

**Comment by DmitriyG228** [comment]
or, maybe the better idea  is just to set up one's own overpass server? :)

**Comment by HughKelley** [comment]
hi, if you need a solution in the short term, you might take a look at the [save_load module](https://osmnx.readthedocs.io/en/stable/osmnx.html?highlight=shapefile#module-osmnx.save_load) where there are functions for loading graphs from different file types. It isn't always super easy, but it may be possible to download the shapefile for a reagon from that Geofabrik website and then read the shapefile in as a graph.

**Comment by gboeing** [comment]
@DmitriyG228 yes you can download a `.osm` file and then load it with OSMnx using `ox.graph_from_file`. See [the OSMnx documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_file) for details.
