### ISSUE TITLE
Retrieving amenities data with osmnx

### ISSUE THREAD

**Issue by corneliailin** [gboeing/osmnx#324]
Hi!

I am trying to retrieve name and geometry data for all the schools in Nairobi, Kenya. I am using the pois_from_place() function available in the osmnx package for this. When I plot the data on a map I see schools outside the boundaries of Nairobi and I don't understand why (please see graph attached). Doing the same thing with QGIS tells me that there are also more schools inside the boundaries of Nairobi that I don't see in my osmnx data.

Am I missing something here? Any help appreciated.
![Screen Shot 2019-08-08 at 6 59 24 PM](https://user-images.githubusercontent.com/52328238/62827814-747b2d80-bb9d-11e9-9578-50656fb19f35.png)

**Comment by gboeing** [comment]
If you fill out all the information requested in the new issue template I can take a look.
