### ISSUE TITLE
Feature Request - overpass endpoint

### ISSUE THREAD

**Issue by SebMilardo** [gboeing/osmnx#328]
Hi

Thank you for the awesome work!
I would like to point osmnx to a local instance of Overpass Turbo. This is also related to #302 
However there is a typo in #302 that I have fixed in my fork and I have also added a test for this new setting. If you are ok with it I can submit a PR.

Kind regards,
Sebastiano

**Comment by gboeing** [comment]
@SebMilardo sounds good, thanks!

**Comment by SebMilardo** [comment]
Pull Request addressing this feature opened at #329

**Comment by gboeing** [comment]
Closed by #329.
