### ISSUE TITLE
plot_figure_ground: 'this isn't a TK application' (matplotlib)

### ISSUE THREAD

**Issue by 42loop** [gboeing/osmnx#33]
for me, plot_figure_ground runs fine when using the ipython notebook in a browser, 
but trying to run plot_figure_ground in a script on ubuntu 16.04 keeps throwing:

'this isn't a TK application':
...
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/tkagg.py", line 30, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError: this isn't a Tk application

of course this seems to be an environment error, but i couldn't figure out how to solve this.
python-tk is installed via apt

any idea whats going wrong ?

#### What operating system, architecture, Python version, and OSMnx version are you using?
ubuntu 16.04, 64bit, python 2.7, osmnx 0.3.1
#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>
# Paste the output of your Python packages and their versions here
actionlib (1.11.7)
adium-theme-ubuntu (0.3.4)
appdirs (1.4.0)
argcomplete (1.7.0)
attrs (15.2.0)
autobahn (0.10.3)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.4.1)
bleach (1.5.0)
bondpy (1.7.18)
buildozer (0.33.dev0)
bzr (2.7.0)
camera-calibration (1.12.19)
camera-calibration-parsers (1.11.11)
catkin (0.7.4)
catkin-pkg (0.2.10)
ccsm (0.9.12.2)
certifi (2016.9.26)
chardet (2.3.0)
Cheetah (2.4.4)
click (6.7)
click-plugins (1.0.3)
cligj (0.4.0)
coloredlogs (5.2)
compizconfig-python (0.9.12.2)
configobj (5.0.6)
configparser (3.5.0)
cryptography (1.2.3)
cv-bridge (1.12.3)
cycler (0.9.0)
Cython (0.21)
decorator (4.0.6)
defusedxml (0.4.1)
descartes (1.1.0)
diagnostic-analysis (1.8.10)
diagnostic-common-diagnostics (1.8.10)
diagnostic-updater (1.8.10)
docutils (0.12)
dynamic-reconfigure (1.5.46)
ecdsa (0.13)
empy (3.3.2)
entrypoints (0.2.2)
enum34 (1.1.2)
executor (14.1)
fasteners (0.14.1)
Fiona (1.7.4)
funcsigs (0.4)
functools32 (3.2.3.post2)
futures (3.0.5)
gazebo-plugins (2.5.8)
gazebo-ros (2.5.8)
gencpp (0.5.4)
geneus (2.2.5)
genlisp (0.4.16)
genmsg (0.5.8)
gennodejs (1.0.3)
genpy (0.6.3)
geopandas (0.2.1)
geopy (1.11.0)
gyp (0.1)
html5lib (0.999)
httplib2 (0.9.1)
humanfriendly (2.1)
idna (2.0)
image-geometry (1.12.3)
interactive-markers (1.11.3)
ipaddress (1.0.16)
ipykernel (4.5.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.9.4)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.1)
keyring (7.3)
Kivy (1.9.1)
laser-geometry (1.6.4)
launchpadlib (1.10.3)
lazr.restfulclient (0.13.4)
lazr.uri (1.0.3)
lxml (3.5.0)
lz4 (0.7.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
meld (3.14.2)
mercurial (3.7.3)
message-filters (1.12.6)
mistune (0.7.3)
mock (1.3.0)
monotonic (1.2)
mpi4py (1.3.1)
msgpack-python (0.4.6)
MultipartPostHandler (0.1.0)
munch (2.1.0)
nbconvert (5.0.0)
nbformat (4.2.0)
ndg-httpsclient (0.4.0)
netifaces (0.10.4)
networkx (1.11)
nose (1.3.7)
notebook (4.3.1)
numpy (1.11.0)
oauth (1.0.1)
oauthlib (2.0.1)
osmnx (0.3.1)
PAM (0.4.2)
pandas (0.19.2)
pandocfilters (1.4.1)
paramiko (1.16.0)
pathlib2 (2.2.0)
pbr (1.8.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (3.1.2)
pip (8.1.1)
Pivy (0.5.0)
pluginlib (1.10.4)
proc (0.10.1)
prompt-toolkit (1.0.9)
property-manager (2.1)
psutil (3.4.2)
ptyprocess (0.5.1)
py-notify (0.3.1)
pyasn1 (0.1.9)
pyasn1-modules (0.0.7)
pycollada (0.4)
pycrypto (2.6.1)
pycurl (7.43.0)
pydot (1.0.29)
pyfreenect2 (0.0.0)
Pygments (2.1)
pygobject (3.20.0)
pygpgme (0.3)
PyOpenGL (3.0.2)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyproj (1.9.5.1)
pyserial (3.0.1)
Pyste (0.9.10)
python-apt (1.1.0b1)
python-dateutil (2.4.2)
python-escpos (2.2.0)
python-networkmanager (1.2.1)
python-qt-binding (0.3.1)
python-snappy (0.5)
pytz (2014.10)
pyusb (1.0.0)
PyYAML (3.11)
pyzmq (15.2.0)
qrcode (5.3)
qt-dotgraph (0.3.3)
qt-gui (0.3.3)
qt-gui-cpp (0.3.3)
qt-gui-py-common (0.3.3)
qtconsole (4.2.1)
requests (2.9.1)
requests-oauthlib (0.7.0)
resource-retriever (1.12.2)
roman (2.0.0)
rosbag (1.12.6)
rosboost-cfg (1.13.4)
rosclean (1.13.4)
roscreate (1.13.4)
rosdep (0.11.5)
rosdistro (0.5.0)
rosgraph (1.12.6)
rosinstall (0.7.8)
roslaunch (1.12.6)
roslib (1.13.4)
roslint (0.11.0)
roslz4 (1.12.6)
rosmake (1.13.4)
rosmaster (1.12.6)
rosmsg (1.12.6)
rosnode (1.12.6)
rosparam (1.12.6)
rospkg (1.0.41)
rospy (1.12.6)
rosservice (1.12.6)
rostest (1.12.6)
rostopic (1.12.6)
rosunit (1.13.4)
roswtf (1.12.6)
rqt-action (0.4.3)
rqt-bag (0.4.3)
rqt-bag-plugins (0.4.3)
rqt-console (0.4.3)
rqt-dep (0.4.3)
rqt-graph (0.4.3)
rqt-gui (0.3.1)
rqt-gui-py (0.3.1)
rqt-image-view (0.4.3)
rqt-launch (0.4.3)
rqt-logger-level (0.4.3)
rqt-moveit (0.5.5)
rqt-msg (0.4.3)
rqt-nav-view (0.5.5)
rqt-plot (0.4.3)
rqt-pose-view (0.5.5)
rqt-publisher (0.4.3)
rqt-py-common (0.4.3)
rqt-py-console (0.4.3)
rqt-reconfigure (0.4.3)
rqt-robot-dashboard (0.5.5)
rqt-robot-monitor (0.5.5)
rqt-robot-steering (0.5.5)
rqt-runtime-monitor (0.5.5)
rqt-rviz (0.5.5)
rqt-service-caller (0.4.3)
rqt-shell (0.4.3)
rqt-srv (0.4.3)
rqt-tf-tree (0.5.5)
rqt-top (0.4.3)
rqt-topic (0.4.3)
rqt-web (0.4.3)
Rtree (0.8.3)
rviz (1.12.4)
scandir (1.4)
scipy (0.17.0)
seaborn (0.7.1)
SecretStorage (2.1.3)
selenium (3.0.2)
sensor-msgs (1.12.5)
service-identity (16.0.0)
setuptools (20.7.0)
Shapely (1.5.17)
simplegeneric (0.8.1)
simplejson (3.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
smach (2.0.0)
smach-ros (2.0.0)
smclib (1.7.18)
specto (0.3.1)
stevedore (1.19.1)
subprocess32 (3.2.7)
terminado (0.6)
testpath (0.3)
tf (1.11.8)
tf-conversions (1.11.8)
tf2-geometry-msgs (0.5.13)
tf2-kdl (0.5.13)
tf2-py (0.5.13)
tf2-ros (0.5.13)
topic-tools (1.12.6)
tornado (4.4.2)
traitlets (4.3.1)
trollius (2.0.1)
tweepy (3.5.0)
Twisted (16.0.0)
txaio (1.0.0)
Unidecode (0.4.19)
unity-lens-photos (1.0)
urlgrabber (3.9.1)
urllib3 (1.13.1)
vboxapi (1.0)
vcstools (0.1.39)
verboselogs (1.5)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wadllib (1.3.2)
Wand (0.4.4)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (1.2.6)
wstool (0.1.13)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
xacro (1.11.1)
youtube-dl (2016.2.22)
zope.interface (4.1.3)

</details>

#### Code that reproduces the issue

```python
place = 'portland'
point = (45.517309, -122.682138)
fig, ax = ox.plot_figure_ground(point=point, filename=place)

```

**Comment by 42loop** [comment]
just noticed that output files are generated anyway, so this is of not so big importance for me

**Comment by gboeing** [comment]
This probably has to do with the matplotlib backend you are using when you execute your script. You might have success if you change the backend you're using when you run the script. For more info see:

  - http://matplotlib.org/users/shell.html
  - http://matplotlib.org/faq/usage_faq.html#what-is-a-backend
  - http://matplotlib.org/api/backend_gtkagg_api.html

Note that the last link contains minimal info, but does indicate that the gtk backend requires an active x-session and isn't compatible with cron jobs -- could explain your trouble running in the script.

**Comment by gboeing** [comment]
@42loop did that work?

**Comment by 42loop** [comment]
i modified ~/.config/matplotlib/matplotlibrc ,
changed 
backend    :GTKCairo
interactive :False

tried different backends but this seemed to work best on ubuntu

still had to use close=True and show=False to get rid of the window and the error message:
 
ox.plot_figure_ground(address=place, dist=1000, close=True, show=False, save=True, filename=fname ,file_format='svg')
