### ISSUE TITLE
Large data taking too long

### ISSUE THREAD

**Issue by mohdalattar** [gboeing/osmnx#334]
Hi, I am trying to calculate centrality indices for large network 

ox.graph_from_place('Glasgow City')
 
 degree centrality and egivenvector centrality have been calculated instantly, however, betweenness centrality is still processing.

![Uploading Screen Shot 2019-09-30 at 6.52.28 PM.png…]()

is there anyway to speed it up ? is it normal ? or there is a bug ?

**Comment by gboeing** [comment]
OSMnx just uses NetworkX to calculate betweenness centrality. It can be a very slow operation, as noted in the [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.stats.extended_stats) "Many of these algorithms have an inherently high time complexity. Global topological analysis of large complex networks is extremely time consuming and may exhaust computer memory." Any issues with NetworkX as such should to directed to the NetworkX GitHub repo.

In the meantime, you could try calling NetworkX's centrality function directly and trying different parameterizations. Or you could try dumping the OSMnx graph to igraph and trying some of its fast C routines for centrality calculation.
