### ISSUE TITLE
Projected graph crash due to UTM zone

### ISSUE THREAD

**Issue by nemecsek69** [gboeing/osmnx#336]
**Linux 19.04, Python 3.7.3, OSMnx 0.10, JupyterLab 1.0.4**

`plot_figure_ground` returns an error when used with `GProjected` (projected graph):
`CRSError: Invalid projection: +proj=utm +zone=51562 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs: (Internal Proj Error: proj_create: Error -35: invalid UTM zone number)`

`plot_figure_ground` works with the standard graph `G`.
`plot_graph` works with both with the graph `G` and the projected graph `GProjected`.

I tried with other locations (even South California, where Geoff is based) but it looks like there is an issue with `geopandas` and any location produces an error.

```python
import osmnx as ox
import os
from IPython.display import Image

%matplotlib inline
ox.config(log_file=False, log_console=False, use_cache=True)

location_point = (50.6233696,12.3007474)

G = ox.graph_from_point(
    location_point, 
    distance=802, 
    distance_type='bbox', 
    network_type="drive", 
    clean_periphery=False, 
)
GProjected = ox.project_graph(G)

fig, ax = ox.plot_graph(G, show=True, node_size=0, edge_linewidth=0.3, edge_color="#000000")
fig, ax = ox.plot_figure_ground(GProjected, show=True, smooth_joints=True, bgcolor="b", edge_color="w")
```

**Comment by gboeing** [comment]
The `plot_figure_ground` function requires an *unprojected* graph. I will update the docstring accordingly.
