### ISSUE TITLE
Degree Centrality inconsistency with OSMnx

### ISSUE THREAD

**Issue by mohdalattar** [gboeing/osmnx#337]
There is an inconsistency with degree centrality with OSMnx. 
I've used nx.degree_centrality as well as nx.degree. for some reason, degree centrality is not accurate with OSMnx. 

<img width="746" alt="Screen Shot 2019-10-04 at 11 07 59 AM" src="https://user-images.githubusercontent.com/50058721/66201866-42b5ad00-e69c-11e9-8f84-e540fbce5f69.png">

As seen in the picture for some nodes (which are connected to 4 streets) is returning 6 [ and some is returning 7 ] while the correct value should be 4. Beside that some wrong values elsewhere.

**Comment by gboeing** [comment]
> I've used nx.degree_centrality as well as nx.degree

If this is an issue with networkx, please open the issue at their repo. Regarding OSMnx, all of its graphs are directed, so a node at an intersection of two bidirectional streets will have degree = 8. Intersections of two one-way streets will have degree = 4. Intersections of bidirectional and one-way streets will vary accordingly. If you're interested in in-degree or out-degree exclusively, consult the networkx documentation. Examine your graph structure itself, look at the adjacency matrix, and the results should make sense.

**Comment by mohdalattar** [comment]
I've examined your interpretation by inserting a basemap, it makes sense. 
Thank you !
