### ISSUE TITLE
Add to plot_figure_ground the possibility to get a multidigraph parameter

### ISSUE THREAD

**Issue by sephib** [gboeing/osmnx#34]
Similar to the other plot functions I thought to add a multidigraph parameter.

```python
def plot_figure_ground(G, address=None, point=None, dist=805, network_type='drive_service',
                       street_widths=None, default_width=4, fig_length=8, edge_color='w', bgcolor='#333333',
                       filename=None, file_format='png', show=False, save=True, close=True, dpi=300):
```

Sending a PR

**Comment by gboeing** [comment]
Thanks. Yes please do issue a PR - this is a useful addition.

**Comment by sephib** [comment]
Hi,
I'm having a problem finding the center point for the graph. 
When running 
``` nx.center(G) ``` I'm getting the following error
``` NetworkXError: Graph not connected: infinite path length```

Apparently the graph is `is_weakly_connected` - 
Do you have any suggestions?

**Comment by gboeing** [comment]
You can get the largest strongly connected component with `ox.get_largest_component(G, strongly=True)`

https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils.get_largest_component

**Comment by sephib** [comment]
Thx
Sent a PR . 
(To connect the PR to this issue I guess I needed to use #34  as the title and note 34 - correct?)

**Comment by gboeing** [comment]
Your method of calculating the network center was a bit slow, so I changed it to instead use the geographic centroid (this is faster) in 9786048
