### ISSUE TITLE
Node Coordinates

### ISSUE THREAD

**Issue by ozgurgundogan** [gboeing/osmnx#340]
Hello,
Great job first of all. thanks for your effort.
I tried many things to obtain node coordinates but I couldnt be successful. 
How can I get node coordinates ? 
I saw a couple example related to this problem ( https://stackoverflow.com/questions/46238813/osmnx-get-coordinates-of-nodes-using-osm-id ). However, as I understand G[node_id] does not give us latitude and longitude anymore.
Is there any possible way to get the coordinates ?

**Comment by gboeing** [comment]
The `x` and `y` attributes are your node coordinates. If your graph is unprojected, then they are in lat-lon (degree units).

*If you've projected your graph*, then `x` and `y` are your projected node coordinates (in meters or whatever units your projected coordinate system uses) and the nodes will also have additional `lat` and `lon` attributes that contain the original unprojected coordinates.

```python
import osmnx as ox
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
node_id = list(G.nodes())[0]
G.node[node_id]['x'] #lon
G.node[node_id]['y'] #lat
```

**Comment by gboeing** [comment]
Note that the NetworkX API has changed slightly over time:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
node_id = list(G.nodes())[0]
G.nodes[node_id]['x'] #lon
G.nodes[node_id]['y'] #lat
```

**Comment by tisttsf** [comment]
> Note that the NetworkX API has changed slightly over time:
> 
> ```python
> import osmnx as ox
> G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
> node_id = list(G.nodes())[0]
> G.nodes[node_id]['x'] #lon
> G.nodes[node_id]['y'] #lat
> ```
Please tell us how to change this piece of code to be work again,Thanks.

**Comment by gboeing** [comment]
@tisttsf I'm not sure what you're asking. That code snippet works fine with the latest version of NetworkX (2.5). If you have a NetworkX usage question, you can consult their [documentation here](https://networkx.org/).

**Comment by tisttsf** [comment]
> @tisttsf I'm not sure what you're asking. That code snippet works fine with the latest version of NetworkX (2.5). If you have a NetworkX usage question, you can consult their [documentation here](https://networkx.org/).

I try your code.I was wrong.Some simple code syntax mistakes in my code. Sorry.
