### ISSUE TITLE
Feature Request: New elevation provider

### ISSUE THREAD

**Issue by kylebarron** [gboeing/osmnx#341]
Hello! This is an amazing project, and I'm happy to finally have a project to test out osmnx.

I'm working with OSM data of trails, and adding elevation data to trails is important. Currently, the only elevation provider supported is Google Maps, and this has a couple drawbacks. For one they're currently restricting API usage: 
> Notice: New customers will need to contact sales for access to the Elevation API.

This might mean they only care about large-scale, large-budge projects, and in any case restricts small developers from using it. There are a couple other elevation APIs, but they all have the drawbacks of being web services.

I wrote code for myself to import elevations from a local DEM using `rasterio`. Would you accept a PR for this? 

Using local DEMs are more scalable than APIs. They can be more accurate since most APIs use at most 30m SRTM data, and there exists 10m data for the contiguous US and 1m for some cities from new LIDAR data.

Maybe there could also be a helper function to download predefined types of elevation DEMs, like SRTM, 3DEP for the US, etc. for the area covered by the current Graph.

Drawbacks:

Using `rasterio` would add a dependency on GDAL, which is not insignificant. I'd propose that it not be included in `requirements.txt`, but that a user who's interested in using this function could self install, and it would be imported conditionally.

**Comment by gboeing** [comment]
I'd be interested in reviewing a PR for this. Changes to the Google Maps Elevation API over the past couple of years have raised some concerns in my mind about scalability and ongoing feasibility. While it (historically) was quicker and easier to attach elevations via the API, it may be that DEMs become a better option moving forward.

> Using local DEMs are more scalable than APIs. They can be more accurate since most APIs use at most 30m SRTM data, and there exists 10m data for the contiguous US and 1m for some cities from new LIDAR data.

This is a good point. If you're already familiar with these data, could you briefly list out say ~3 top DEM sources and their resolutions? My impression of the Google API was that they had pretty fine resolution. From their docs: "The response includes the elevation at that point, in meters, along with the resolution value (the maximum distance between data points from which the elevation was interpolated, in meters)." ...and the example they give returns a 4.77 meter resolution (suggesting they interpolated the point's elevation from data points only 4.77 meters apart).

> Using rasterio would add a dependency on GDAL, which is not insignificant.

OSMnx already depends on GDAL, via OSMnx -> geopandas -> Fiona -> libgdal.

**Comment by kylebarron** [comment]
I'm not intricately familiar with DEM sources.

I believe the standard for worldwide coverage is [SRTM][srtm], which looks to be available at 30m horizontal resolution worldwide. Apparently [ASTER][aster] is newer, but it's questionable whether it has higher accuracy. OSM apparently [uses][osm_srtm] SRTM already; SRTM version 3 apparently combines ASTER data.

[srtm]: https://en.wikipedia.org/wiki/Shuttle_Radar_Topography_Mission
[aster]: https://en.wikipedia.org/wiki/Advanced_Spaceborne_Thermal_Emission_and_Reflection_Radiometer#ASTER_Global_Digital_Elevation_Model
[osm_srtm]: https://wiki.openstreetmap.org/wiki/SRTM

For my purposes I only care about US OSM data, so I'm using USGS elevation data. There's [complete](https://prd-wret.s3-us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/styles/full_width/public/thumbnails/image/Seamless_Resolution_092019.jpg?itok=cUCla7Nj) 1/3 arc second and 1 arc second data for the continental US. This is roughly 10m and 30m spacing, respectively. USGS is currently working to use LiDAR to create a 1 meter DEM for the continental US, but currently available data is a [patchwork](https://prd-wret.s3-us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/styles/full_width/public/thumbnails/image/1meter_Availability_092019.jpg?itok=rf5DVT-b).

So I'm using 1/3 arc second data in my project, but with `rasterio` it looks super easy to work with data from any source.

**Comment by gboeing** [comment]
Regarding an API alternative, there is also this: https://open-elevation.com/ which appears to use SRTM data.

**Comment by kylebarron** [comment]
Yes, I've seen that. It wouldn't be difficult to support that, I assume. It looks like it uses roughly the same API as Google does. Still, I think having local DEM support would be helpful to users who have a lot of data they want to get elevations for.

**Comment by kylebarron** [comment]
By the way USGS also has [an API](https://nationalmap.gov/epqs/), but you can only get one point at a time.

**Comment by gboeing** [comment]
> but you can only get one point at a time

I think that makes USGS a nonstarter. A useful PR might swap the Google Maps API for the OpenElevation API, and add a new function to attach elevation via local DEM file rather than via remote API calls.
