### ISSUE TITLE
Would it be feasible to complete network on areas such as places or plaza?

### ISSUE THREAD

**Issue by swiss-knight** [gboeing/osmnx#346]
#### Problem description

As described here: https://gis.stackexchange.com/questions/341204 I'm wondering if it would be possible to complete a network on some areas where incoming edges are not directly connected to each other, but only through that particular area, such a pedestrian plaza?

**Comment by gboeing** [comment]
It's conceivably possible, but would be nontrivial and probably beyond the scope of the OSMnx project at this point.
