### ISSUE TITLE
test_stats: stats4 failed

### ISSUE THREAD

**Issue by jgmbenoit** [gboeing/osmnx#347]
In debian Sid environment, the stats4 in test_stats in tests/test_osmnx.py fails with the message:
E           networkx.exception.NetworkXNotImplemented: not implemented for multigraph type

**Comment by gboeing** [comment]
This test failure is resulting from networkx no longer implementing the betweenness_centrality algorithm on Multi(Di)Graph types as of v2.4: https://github.com/networkx/networkx/pull/3454

I need to change the OSMnx stats module to accommodate that.

**Comment by gboeing** [comment]
See also: https://github.com/networkx/networkx/issues/3432
