### ISSUE TITLE
libspatialindex_c.so: cannot open shared object file

### ISSUE THREAD

**Issue by Georgepop** [gboeing/osmnx#349]
Hello i can't pull docker image of your library !!
gives error: libspatialindex
PLease help !

**Comment by gboeing** [comment]
It's not clear to me how `docker pull` could produce any such error. From your terminal, run

```
docker pull gboeing/osmnx
```

and docker will pull the image.

**Comment by Georgepop** [comment]
thank you !

**Comment by Georgepop** [comment]
when trying to install in docker i get this error:
OSError: libspatialindex_c.so: cannot open shared object file: No such file or directory

what to do ?!
