### ISSUE TITLE
Error when loading street network from poligon

### ISSUE THREAD

**Issue by AlbertoMCS** [gboeing/osmnx#355]
Hi , 
I am following this post: https://geoffboeing.com/2016/11/osmnx-python-street-networks/#comment-42748 and replicating it. 

I want to get street network from a polygon I created. 
I loaded the polygon with geopandas and I wrote the code provided in the post but I get an error, here my code: 

`df1 = gdp.read_file('C:/Users/ATELLO/Desktop/shapefile/prueba.shp')
K = ox.graph_from_polygon(df1, network_type='all')
`

ValueError                                Traceback (most recent call last)
<ipython-input-117-841b96eb89e7> in <module>()
      1 df1 = gdp.read_file('C:/Users/ATELLO/Desktop/shapefile/prueba.shp')
----> 2 K = ox.graph_from_polygon(df1, network_type='all')

C:\Program Files\Anaconda3\lib\site-packages\osmnx\core.py in graph_from_polygon(polygon, network_type, simplify, retain_all, truncate_by_edge, name, timeout, memory, max_query_area_size, clean_periphery, infrastructure, custom_filter)
   1296     # verify that the geometry is valid and is a shapely Polygon/MultiPolygon
   1297     # before proceeding
-> 1298     if not polygon.is_valid:
   1299         raise TypeError('Shape does not have a valid geometry')
   1300     if not isinstance(polygon, (Polygon, MultiPolygon)):

C:\Program Files\Anaconda3\lib\site-packages\pandas\core\generic.py in __nonzero__(self)
   1553             "The truth value of a {0} is ambiguous. "
   1554             "Use a.empty, a.bool(), a.item(), a.any() or a.all().".format(
-> 1555                 self.__class__.__name__
   1556             )
   1557         )

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Many thanks!,
Alberto.

**Comment by gboeing** [comment]
You need to provide a [minimal, complete, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for me to be able to troubleshoot this.

Read the documentation for `graph_from_polygon`: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_polygon

It calls for a shapely Polygon or MultiPolygon with coordinates in units of lat-long degrees. You appear to be passing in a geopandas GeoDataFrame instead (though you do not define `gdp` in your code snippet, so I'm making some assumptions).
