### ISSUE TITLE
Fix duplicate edges in save_graph_osm()

### ISSUE THREAD

**Issue by mxndrwgrdnr** [gboeing/osmnx#356]
When I originally wrote this function, I didn't realize that the edges dataframe generated by `ox.graph_to_gdfs()` will contain multiple rows with the same `osmid` for any way that is associate with more than two nodes. As such, save_graph_osm() will generate XML like
```
<way id="123456789"/>
  <nd ref="1"/>
  <nd ref="2"/>
  <tag k="highway" v="residential"/>
</way>
<way id="123456789"/>
  <nd ref="2"/>
  <nd ref="3"/>
 <tag k="highway" v="residential"/>
</way>
<way id="123456789"/>
  <nd ref="3"/>
  <nd ref="4"/>
  <tag k="highway" v="residential"/> 
</way>
```
instead of 
```
<way id="123456789"/>
  <nd ref="1"/>
  <nd ref="2"/>
  <nd ref="3"/>
  <nd ref="4"/>
  <tag k="highway" v="residential"/>
</way>
```
The XML will still validate, as was documented in the original PR, but it doesn't technically conform to the OSM XML design schema, nor is it the most efficient way of storing the data. Furthermore I'm just not sure what this might do for any downstream processes (e.g. routers) that make use of this re-formatted file. 

In practice, this should be a straightforward fix, edit [this](https://github.com/gboeing/osmnx/blob/master/osmnx/save_load.py#L217-L224) chunk of code to check whether or not the tree already contains an edge with that id and if so just add the new nodes to it rather than creating a whole new way. However, according to the OSM wiki, OSM XML requires that the `<nd/>` tags be listed "in the correct order" (see the last sentence [here](https://wiki.openstreetmap.org/wiki/Way#Street_as_a_vector), and I'm unsure if its possible to infer that order from the order in which the duplicate `osmid` ways appear in the edges table.. 

So, my questions are two-fold:
1. Is this a big enough problem to worry about fixing?
2. If so, is it possible to recover the correct node order from either the edges table or the original NetworkX graph object?

**Comment by mxndrwgrdnr** [comment]
By the same token, I believe we ought to first convert the graph object to an _undirected_ graph with before converting to gdfs. That will at least get rid of the duplicate edges that are only duplicate because they were two-way ways. Whatever processes use the OSM XML output of `ox.save_graph_osm()` will rely solely on the `oneway` tag to interpret directionality.

**Comment by gboeing** [comment]
> 1. Is this a big enough problem to worry about fixing?

Probably worth fixing if we can figure out a fix. 

> 2. If so, is it possible to recover the correct node order from either the edges table or the original NetworkX graph object?

Yes. You'd basically want to find all graph edges that match a certain way ID. Then you can recover their order by look at the `u` and `v` keys (meaning "to" and "from" nodes).

**Comment by mxndrwgrdnr** [comment]
I guess I was hoping that somewhere OSMnx might have preserved the original order of the nodes in sequence. Reconstructing the node order by matching the `v` key from one edge to the `u` key of another will definitely work, but will also probably be quite slow to run on the entire graph. If that's all we got then I can work with it but if you had any other bright ideas I'd love to hear them.

**Comment by mxndrwgrdnr** [comment]
@gboeing I documented my proposed fix in PR #359. Let me know what you think. It's not particularly elegant but it works.

**Comment by mxndrwgrdnr** [comment]
I've found another complicating issue that will cause my algorithm to break. I noticed that after converting my network from a multi-digraph to an undirected multigraph, the remaining edges were often preserved in a weird order. For example, if I had edges ((1, 2), (2, 1), (2, 3), (3, 2)) in my multi-digraph, after conversion using the `ox.get_undirected()` method I might be left with something like ((1, 2), (3, 2)) or ((2, 1) (2, 3)) instead of the expected ((1, 2), (2, 3)) or even ((2, 1), (3, 2)). It seems like the origin of this behavior goes back to NetworkX and the docs [here](https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.DiGraph.to_undirected.html#networkx-digraph-to-undirected) which state: 

> If edges in both directions (u, v) and (v, u) exist in the graph, attributes for the new undirected edge will be a combination of the attributes of the directed edges. The edge data is updated in the (arbitrary) order that the edges are encountered. For more customized control of the edge attributes use add_edge()

So that makes sense, and I can and will adjust the algorithm so that it knows how to reconstruct the full list of ordered nodes even if it encounters something like ((2, 1), (2, 3)). The problem is that this means we cannot know which was the correct original order: [1, 2, 3] or [3, 2, 1]. This has major implications for one-way streets and other ways with direction-dependent tags like `cycleway:left`. 

You might be thinking that one-way streets won't actually be affected by this issue because they'll only have their edges in their original order since they never had (u, v) and (v, u) edges in the graph. However, in my own testing, I've noticed the following behavior:
```
 G = ox.graph_from_place('Beverly Hills, California, United States', simplify=True, retain_all=False)
nodes, edges = ox.graph_to_gdfs(G)
edges.loc[edges['osmid'] == 397466539, ['u', 'v', 'osmid', 'oneway']]
```
|	u |	v |	osmid |	oneway|
|---|---|---|---|
|4273	|1715604581	| 1497909289	| 397466539	| True |
|16606	|4808196169	|1497909362	|397466539	|True
18731	|1497909227	|1497909319|	397466539	|True
18825	|1497909289	|1715604537	|397466539	|True
18863	|1497909316	|1497909306|	397466539	|True
18866	|1497909319	|1497909388|	397466539	|True
18921	|1497909362	|1497909227|	397466539	|True
18963	|1497909388	|1497909316|	397466539	|True
20288	|1715604537	|4808196169|	397466539	|True

```
H = ox.get_undirected(G)
nodes, edges = ox.graph_to_gdfs(H)
edges.loc[edges['osmid'] == 397466539, ['u', 'v', 'osmid', 'oneway']]
```

|	u|	v|	osmid|	oneway|
|---|---|---|---|
3029	|1715604581|	1497909289|	397466539|	True
10699	|4808196169|	1497909362|	397466539|	True
10702	|4808196169	|1715604537|	397466539|	True
11733	|1497909227	|1497909319|	397466539|	True
11734	|1497909227	|1497909362|	397466539|	True
11814	|1497909289	|1715604537	|397466539|	True
11832	|1497909306	|1497909316	|397466539|	True
11847	|1497909316	|1497909388	|397466539|	True
11848	|1497909319	|1497909388	|397466539|	True

so edges 10699 and 10702 are both one-way edges on the same way that originate at the same node, which shouldn't be possible.

Clearly the `get_undirected()` method just shouldn't be used here, which, as far as I can tell only  leaves us with one option: reconstruct the node order from the full multi-digraph. We still wouldn't be able to differentiate between [1, 2, 3] and [3, 2, 1], but one-way ways wouldn't be effected. I believe the major casualty would be directional tags like `cycleway:left`, where we couldn't know which direction was left and which direction was right. 

The only other thing I can think of would be to add a new high-level setting to prevent the creation of bi-directional edges from the beginning. You already have a high-level parameter (`ox.settings.bidirectional_network_types`) that can override one-way tags, so we could just define something like `ox.settings.oneway_only` or `ox.settings.all_oneway`which could trigger an extra `if` clause in the `ox.add_paths()` method definition [here](https://github.com/gboeing/osmnx/blob/master/osmnx/core.py#L847-L870) like 
```
for data in paths.values():
    if ox.settings.all_oneway:
        add_path(G, data, one_way=True)
```
This last option would be super rad for my use case but I would understand if you had reservations about tweaking such a critical piece of infrastructure. Let me know what you think.

**Comment by mxndrwgrdnr** [comment]
What say you @gboeing?

**Comment by gboeing** [comment]
Step me through your logic a bit more on creating a high-level setting like `ox.settings.all_oneway` and how that solves your use case. I'm potentially open to it but want to think through its operation and implications in some detail first...

**Comment by mxndrwgrdnr** [comment]
In short, my use case is one in which I want to use OSMnx to download a network, programmatically edit network attributes (e.g. custom tags), and save the results back to OSM XML in a format that preserves the original network topology so that the results can be used by something that reads OSM XML.

OSM XML really only reflects directionality in two ways: directional tags and the implicit order of the node tags associated with each way. The order of the nodes is arbitrary according to how the way was drawn by the editor, but crucially they are consistent with directional tags like "oneway", "cycleway:left", "cycleway:opposite", etc. 

As shown above, the way OSMnx creates its graphs only preserves the node order when the "oneway" tag evaluates to `True`, which makes it impossible to interpret other directional tags like "cycleway:left" because we can't know the original direction of flow. 

Something like `ox.settings.all_oneway` would force OSMnx to construct a graph where all edges are constructed according to the order in which nodes are read from the way object. No reverse edges would be constructed. The result would be similar to what you get when you call `ox.get_undirected()`, except it would reflect the original node order. It also would not overwrite the "oneway" tag as is currently done in `ox.add_path()`.

So `ox.add_path()` becomes
```python
def add_path(G, data, one_way):
    """
    Add a path to the graph.

    Parameters
    ----------
    G : networkx multidigraph
    data : dict
        the attributes of the path
    one_way : bool
        if this path is one-way or if it is bi-directional

    Returns
    -------
    None
    """

    # extract the ordered list of nodes from this path element, then delete it
    # so we don't add it as an attribute to the edge later
    path_nodes = data['nodes']
    del data['nodes']

    # set the oneway attribute to the passed-in value, to make it consistent
    # True/False values, but only do this if you aren't forcing all edges to
    # oneway with the all_oneway setting. With the all_oneway setting, you
    # likely still want to preserve the original OSM oneway attribute.
    if not settings.all_oneway:
        data['oneway'] = one_way

    # zip together the path nodes so you get tuples like (0,1), (1,2), (2,3)
    # and so on
    path_edges = list(zip(path_nodes[:-1], path_nodes[1:]))
    G.add_edges_from(path_edges, **data)

    # if the path is NOT one-way
    if not one_way:
        # reverse the direction of each edge and add this path going the
        # opposite direction
        path_edges_opposite_direction = [(v, u) for u, v in path_edges]
        G.add_edges_from(path_edges_opposite_direction, **data)
```

and `ox.add_paths()` becomes
```python
def add_paths(G, paths, bidirectional=False):
    """
    Add a collection of paths to the graph.

    Parameters
    ----------
    G : networkx multidigraph
    paths : dict
        the paths from OSM
    bidirectional : bool
        if True, create bidirectional edges for one-way streets


    Returns
    -------
    None
    """

    # the list of values OSM uses in its 'oneway' tag to denote True
    osm_oneway_values = ['yes', 'true', '1', '-1']

    for data in paths.values():

        if settings.all_oneway is True:
            add_path(G, data, one_way=True)
        # if this path is tagged as one-way and if it is not a walking network,
        # then we'll add the path in one direction only
        elif ('oneway' in data and data['oneway'] in osm_oneway_values) and not bidirectional:
            if data['oneway'] == '-1':
                # paths with a one-way value of -1 are one-way, but in the
                # reverse direction of the nodes' order, see osm documentation
                data['nodes'] = list(reversed(data['nodes']))
            # add this path (in only one direction) to the graph
            add_path(G, data, one_way=True)

        elif ('junction' in data and data['junction'] == 'roundabout') and not bidirectional:
            # roundabout are also oneway but not tagged as is
            add_path(G, data, one_way=True)

        # else, this path is not tagged as one-way or it is a walking network
        # (you can walk both directions on a one-way street)
        else:
            # add this path (in both directions) to the graph and set its
            # 'oneway' attribute to False. if this is a walking network, this
            # may very well be a one-way street (as cars/bikes go), but in a
            # walking-only network it is a bi-directional edge
            add_path(G, data, one_way=False)

    return G
```

**Comment by gboeing** [comment]
Ok I think this makes sense. Want to make PR?

**Comment by mxndrwgrdnr** [comment]
Probably makes most sense to merge the changes into the existing PR for this issue, #359. Sound good?

**Comment by gboeing** [comment]
Yep.

**Comment by mxndrwgrdnr** [comment]
Done.
