### ISSUE TITLE
Inconsistencies in get_nearest_edge(s)

### ISSUE THREAD

**Issue by TMorville** [gboeing/osmnx#360]
First off, thanks for making this package and maintaining it. It's really great work.

#### Problem description (what did you do, what did you expect to happen, and what actually happened)

I have two issues with the `get_nearest_edges` method. One may be a bug and the other one seems like a performance issue.

First, in [the documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html) under `get_nearest_edges` is states that input should be X,Y or longitude latitude. However. the default method `None`, calls `get_nearest_edge` which is Y,X (latitude longitude). This results in errornous output without any warning when setting a new method.

Second, the performance of both `kdtree` and `balltree` seem identical, and both seem slower than `None`?

The following code reproduces both the bugs and the performance issue.

```
    graph = ox.graph_from_place('Copenhagen Municipality, Denmark')

    lat = [55.67271538, 55.67333957, 55.67134307, 55.67340924, 55.67390186]
    lng = [12.5893237, 12.59032014, 12.58719633, 12.59043931, 12.59126821]
    
    methods = [None, 'kdtree', 'balltree']
    
    for m in methods:
        t0 = time.time()

        ne = ox.get_nearest_edges(graph, lng, lat, method=m)
        
        t1 = time.time()
        
        print(m, t1-t0)
        print(ne)
```
```
None 22.455718994140625
[[282416810 282416811]
 [282416810 282416811]
 [282416810 282416811]
 [282416810 282416811]
 [282416810 282416811]]
kdtree 42.809242725372314
[[ 257790076    8891513]
 [   8891513    8891514]
 [1236259018 1236557323]
 [   8891513    8891514]
 [   8891513    8891514]]
balltree 41.82496619224548
[[ 257790076    8891513]
 [   8891513    8891514]
 [1236557323 1236259018]
 [   8891513    8891514]
 [   8891513    8891514]]
```

It's seems clear that the output when using `None` is wrong. Also, it seems that `kdtree` and `balltree` have similar performance. I've reproduced the performance issue on much larger sets of data as well.

When changing the order of `lat, lng` coordinates, results from `None` are correct, but performance of the other two methods deteriorate even more.

```
None 21.603910207748413
[[ 257790076    8891513]
 [   8891513    8891514]
 [1236557323 1236259018]
 [   8891513    8891514]
 [   8891513    8891514]]
kdtree 58.87358808517456
[[282416811 282416810]
 [282416811 282416810]
 [282416811 282416810]
 [282416811 282416810]
 [282416811 282416810]]
balltree 72.93773794174194
[[282416811 282416810]
 [282416811 282416810]
 [282416811 282416810]
 [282416811 282416810]
 [282416811 282416810]]
```

#### What operating system, architecture, Python version, and OSMnx version are you using?

`osmnx==0.10`

`Python 3.7.3`

**Comment by TMorville** [comment]
After updating to `osmnx==0.11` performance is much better for `kdtree` and `balltree` for a longer list of coordinates. However, the "swapping" of orders from `None` to the two other methods still persist. 

For N = 100 lat, lng pairs: 

`lat, lng` order (correct result for `None`):

```
ox.get_nearest_edges(graph, lat, lng, method=m)

None 415.25596714019775
kdtree 41.519052028656006
balltree 44.4577419757843
```

`lng, lat` order (correct result for `kdtree` & `balltree`):

```
ox.get_nearest_edges(graph, lng, lat, method=m)

None 475.5944209098816
kdtree 50.76128697395325
balltree 47.974807024002075
```

**Comment by gboeing** [comment]
Thanks for catching this: `get_nearest_edges` was incorrectly passing the coordinates to `get_nearest_edge` as (x, y) instead of (y, x).

#361 fixes this, so that everything is passed as (y, x) and (lat, lng), and improves the docstring with more detail.

**Comment by gboeing** [comment]
Also, regarding the runtimes: the kdtree and balltree methods need to build an index upfront, so there's a substantial fixed cost. Thus for small networks, the manual-search `None` method will often be faster because it avoids the time cost of index construction. For large graphs, it is worth it to build the index for the substantial speed-up it offers, and thus the kdtree and balltree methods are preferred.
