### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Monduiz** [gboeing/osmnx#37]
I apologize but this is going to be  a basic use question.

To get started after installing do I:

Launch the environment with source activate osmnx or go to python
Then, do I just run 

    `import osmnx as ox
    from IPython.display import Image
    %matplotlib inline
    ox.config(log_console=True, use_cache=True)`

or do I save into a .py file and run the script?

**Comment by philippschw** [comment]
It is easier and nicer to play with the Jupyter/Python Notebooks. If you have never heard this term, have a look here: http://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#

1. To get started, install osmnx as described in command line via: 
`pip install osmnx`
or if you are using anaconda
`conda install -c conda-forge osmnx`

2. Download the complete osmnx repository

3. Type in command line:
`jupyter notebook`

4. Navigate to examples in repository and check it out:
https://github.com/gboeing/osmnx/tree/master/examples

Cheers,

**Comment by gboeing** [comment]
Thanks @philippschw -- yep, the notebooks are the easiest way to play around. @Monduiz if you're new to all of this, I also have a getting started guide that might be useful: http://geoffboeing.com/2017/02/python-getting-started/

**Comment by Monduiz** [comment]
Thank you for this! I will take the time to read the guide. I have anaconda
but I have not touched jupyter.

Bjenk
