### ISSUE TITLE
ZeroDivisionError in basic_stats

### ISSUE THREAD

**Issue by janinaaa** [gboeing/osmnx#370]
I'm trying to calculate basic and extended network stats of a walking network, merge them together, and display them as done in the example (https://github.com/gboeing/osmnx-examples/blob/master/notebooks/06-example-osmnx-networkx.ipynb). Unfortunately, when I try to run the basic_stats, it throws a ZeroDivisionError. Apparently, when it tries to calculate node density as nodes per sq km (node_density_km = n / area_km), area_km is 0. I suspect that that's happening because we're guarding against null, but not zero here: https://github.com/gboeing/osmnx/blob/master/osmnx/stats.py#L153?

#### What operating system, architecture, Python version, and OSMnx version are you using?
I'm using OSMnx 0.11.3, Python 3.7, macOS Catalina

#### Code snippet that independently and completely reproduces the issue

```python
# your code goes here
import networkx as nx
import osmnx as ox
import requests
import geopandas as gpd
%matplotlib inline
ox.config(use_cache=True, log_console=True)
ox.__version__

G = ox.graph_from_place('Leipzig, Saxony, Germany', network_type='walk', which_result=2)
fig, ax = ox.plot_graph(G)

# get the street network for a place, and its area in square meters
place = 'Leipzig, Saxony, Germany'
gdf = ox.gdf_from_place(place)
area = ox.project_gdf(gdf).unary_union.area
G = ox.graph_from_place(place, network_type='walk', which_result=2)

# calculate basic and extended network stats, merge them together, and display
stats = ox.basic_stats(G, area=area)
extended_stats = ox.extended_stats(G, ecc=True, bc=True, cc=True)
for key, value in extended_stats.items():
    stats[key] = value
pd.Series(stats)
```

<img width="1121" alt="Screenshot 2020-01-28 at 13 47 37" src="https://user-images.githubusercontent.com/48382145/73265230-cb6cd180-41d4-11ea-8229-82dd3bce9e77.png">

**Comment by gboeing** [comment]
@janinaaa you're getting a `ZeroDivisionError` because you're passing `area=0` into the `basic_stats` function, so when it calculates densities, you're asking it to divide by zero. This is because you specify `which_result=2` when you get the graph, but not when you get the gdf (geometry) of the place itself. If you consistently use `which_result=2` in both queries, it all works fine.

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
place = 'Leipzig, Saxony, Germany'
gdf = ox.gdf_from_place(place, which_result=2)
area = ox.project_gdf(gdf).unary_union.area
G = ox.graph_from_place(place, network_type='walk', which_result=2)
stats = ox.basic_stats(G, area=area)
```
