### ISSUE TITLE
Allow use of existing axes without reassigning

### ISSUE THREAD

**Issue by asongtoruin** [gboeing/osmnx#377]
As things stand with the module, it's very easy to create single plots but difficult to use `matplotlib`'s subplotting to create multiple plots on the same figure. This is in part because the calling of the `save_and_show` function is called at the end of most (all?) of these functions, which reassigns `fig` and `ax`.

I'd like to propose adding in a parameter in each function to optionally prevent this from happening. As an initial try, here is what `plot_footprints` might look like if, for example, there was a new parameter called `use_active_ax` for this purpose (and reducing the function down to just the modified parts):

```python
def plot_footprints(gdf, use_active_ax=False, fig=None, ax=None, figsize=None, color='#333333', bgcolor='w',
                    set_bounds=True, bbox=None, save=False, show=True, close=False,
                    filename='image', file_format='png', dpi=600):
    
    if use_active_ax:
        ax = plt.gca()
        fig = ax.figure
    elif fig is None or ax is None:
        fig, ax = plt.subplots(figsize=figsize, facecolor=bgcolor)
    
    ax.set_facecolor(bgcolor)

   # ...

    # make everything square
    ax.set_aspect('equal')
    
    if not use_active_ax:
        fig.canvas.draw()

        fig, ax = ox.plot.save_and_show(fig=fig, ax=ax, save=save, show=show, close=close,
                                filename=filename, file_format=file_format, dpi=dpi, axis_off=True)

        return fig, ax
```

This should allow us to quickly produce multiple plots on the same figure. Using the locations from the footprints example:

```python
import matplotlib.pyplot as plt
import osmnx as ox


places = [
    ('Arc de Triomphe', (48.873446, 2.294255)),
    ('Portland', (45.517309, -122.682138)),
    ('NYC', (40.757920, -73.983393)),
    ('Richmond', (37.781999, -122.472501))
]

distance_m = 612
size = 7

fig, axes = plt.subplots(figsize=(len(places)*size, size), ncols=len(places), facecolor='#333333')

for place, ax in zip(places, axes):
    plt.sca(ax)
    
    fpr = ox.footprints_from_point(place[1], distance=distance_m)
    os.plot_footprints(fpr, use_active_ax=True, bgcolor='#333333', color='orange')
    ax.set_title(place[0], color='orange', fontsize='xx-large', weight='bold')
```

![Single figure multiple axes](https://user-images.githubusercontent.com/20771863/73645355-09ec0b80-466f-11ea-9067-88f6bd6f560f.png)

I think this would also allow for easy use of `FacetGrid` in `seaborn` too. I'd be happy to work up a PR for this functionality later if this is something you think would be helpful.

Any thoughts?

**Comment by asongtoruin** [comment]
@gboeing - not sure if this slipped through your net, here's a little bump in case it did.

**Comment by gboeing** [comment]
This should be currently doable:

```python
fig, axes = plt.subplots(figsize=(len(places)*size, size), ncols=len(places), facecolor='#333333')
for place, ax in zip(places, axes):
    fpr = ox.footprints_from_point(place[1], distance=distance_m)
    fig, ax = ox.plot_footprints(fpr, fig=fig, ax=ax, bgcolor='#333333', color='orange', save=False, show=False, close=False)
    ax.set_title(place[0], color='w', fontsize='xx-large', weight='bold')
plt.show()
```
