### ISSUE TITLE
osmnx/examples/11-plot-routes-folium-web-map.ipynb

### ISSUE THREAD

**Issue by ABC0408** [gboeing/osmnx#38]
graph_map = ox.plot_graph_folium(G, popup_attribute='name', edge_width=2)
AttributeError: 'module' object has no attribute 'plot_graph_folium'
graph_from_place() returning graph with 348 nodes and 944 edges

**Comment by gboeing** [comment]
What operating system, architecture, Python version, and OSMnx version are you using?

Note that this functionality is new to v0.4: https://github.com/gboeing/osmnx/blob/master/CHANGELOG.md

**Comment by ABC0408** [comment]
Thank you. I used sudo pip install -U osmnx, and then ImportError: The folium package must be installed to use this optional feature. so I  install folium , now is ok.
