### ISSUE TITLE
Save as OSM XML does not work

### ISSUE THREAD

**Issue by mschroen** [gboeing/osmnx#381]
Saving the osm graph to xml does not seem to work. The error is complaining about some str to integer conversion and some keyerror concerning highway. However, the graph contains highway keys. If I am doing something fundamentally wrong, it would be great if the documentation for this function could be improved.

<details>
Windows 10, python 3.7.6, osmnx 0.11.4
</details>

#### Code snippet that independently and completely reproduces the issue

```python
import osmnx
osmnx.utils.config(all_oneway=True)
G = osmnx.graph_from_bbox(50.01, 50.000, 12.01, 12.000)
#osmnx.plot_graph(G)
osmnx.save_as_osm(G, filename='osm.xml')
```

Outputs a beautiful graph and the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
c:\users\XXX\appdata\local\programs\python\python37\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4410             try:
-> 4411                 return libindex.get_value_at(s, key)
   4412             except IndexError:

pandas\_libs\index.pyx in pandas._libs.index.get_value_at()

pandas\_libs\index.pyx in pandas._libs.index.get_value_at()

pandas\_libs\util.pxd in pandas._libs.util.get_value_at()

pandas\_libs\util.pxd in pandas._libs.util.validate_indexer()

TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-118-0256ba19ccc6> in <module>
      3 G = osmnx.graph_from_bbox(50.01, 50.000, 12.01, 12.000)
      4 osmnx.plot_graph(G)
----> 5 osmnx.save_as_osm(G, filename='osm.xml')

c:\users\XXX\appdata\local\programs\python\python37\lib\site-packages\osmnx\save_load.py in save_as_osm(data, node_tags, node_attrs, edge_tags, edge_attrs, oneway, merge_edges, edge_tag_aggs, filename, folder)
    248         for tag in node_tags:
    249             etree.SubElement(
--> 250                 node, 'tag', attrib={'k': tag, 'v': row[tag]})
    251 
    252     # append edges to the XML tree

c:\users\XXX\appdata\local\programs\python\python37\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    869         key = com.apply_if_callable(key, self)
    870         try:
--> 871             result = self.index.get_value(self, key)
    872 
    873             if not is_scalar(result):

c:\users\XXX\appdata\local\programs\python\python37\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4417                     raise InvalidIndexError(key)
   4418                 else:
-> 4419                     raise e1
   4420             except Exception:
   4421                 raise e1

c:\users\XXX\appdata\local\programs\python\python37\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4403         k = self._convert_scalar_indexer(k, kind="getitem")
   4404         try:
-> 4405             return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
   4406         except KeyError as e1:
   4407             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'highway'
```

**Comment by gboeing** [comment]
@mxndrwgrdnr any thoughts?

**Comment by mxndrwgrdnr** [comment]
@mschroen can you confirm that your edges have a `highway` tag?

**Comment by mxndrwgrdnr** [comment]
What's happening here is that osmnx is attempting to create an XML tag for every attribute specified in the `node_tags` argument of `ox.save_as_osm()`. If no argument is passed in, it defaults to `ox.settings.osm_xml_node_tags`, which includes `highway`. If the edges don't have a `highway` tag, as the error above would seem to suggest, then the user simply needs to pass in their own list of tags to use into the `ox.save_as_osm()` method.

**Comment by mxndrwgrdnr** [comment]
Sorry @mschroen, just read your post more carefully and see your graph does include `highway` tags. Since the error occurs at line 250, though, this would mean the nodes would  need to have the `highway` tag, not just the edges. Still, a good test would be to try and pass in your own `node_tags` argument to the `ox.save_as_osm()` that excludes "highway" and see what that does. Would also be interested to know if you get the same error if you create the nodes and edges tables first, outside of `ox.save_as_osm()` and pass those in as a tuple.

**Comment by gboeing** [comment]
@mschroen just checking back if this issue is still open or is @mxndrwgrdnr's advice resolved it?

**Comment by mschroen** [comment]
Hi, sorry for the quiet period, I submitted the issue right before family holidays. Thanks for the quick response. Unfortunately I think I cannot answer your questions. I just started with OSMnx a few days ago, and I am not yet familiar enough to know how to pass own node tags, exclude stuff, or create node and edge tables. Sorry that I cannot help you here. But since I provided a MWE, I am sure you guys could investigate better and more efficiently.

What I can tell is, that changing the network limit from 50.01 to 50.1 and 12.01 to 12.1, solves the issue. It seems that your hypothesis is right, that for a network of too small size, the cutted nodes lose the highway tag and happen to crash `save_as_osm()`. I am using the procedure in an automatic mode that should be user friendly, so it would be great if osmnx could still save the network without errors in any case. Either this, or provide a generic solution which function arguments to pass such that the error does not happen. Thanks!

**Comment by gboeing** [comment]
@mschroen thanks for the additional info.

@mxndrwgrdnr I think I see what's happening here. `highway` is an expected tag for the nodes, but it probably shouldn't be. Nodes will often have a `highway` tag if they are a `turning_circle` or somesuch, but it is not a ubiquitous tag, so it shouldn't be required. 

The only tags we should ever "expect" nodes to have would be `osmid`, `x`, and `y`. Everything else is inconsistent and on a per-case basis.

**Comment by gboeing** [comment]
@mxndrwgrdnr lemme know your thoughts.

**Comment by mxndrwgrdnr** [comment]
Hey all sorry for the delay I've been hosting guests over the long weekend. This all makes sense to me and I should be able to push a fix today.

**Comment by gboeing** [comment]
Thanks Max.
