### ISSUE TITLE
`get_nearest_node()` returning same output irrespective of input after projecting

### ISSUE THREAD

**Issue by agdhruv** [gboeing/osmnx#382]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Firstly, amazing library -- I would love to be able to contribute to it one day! 
I downloaded a `graph_from_bbox` and projected the downloaded graph as stated in point 2a [here](https://geoffboeing.com/2016/11/osmnx-python-street-networks/). After doing these, every call to `get_nearest_node` always returns the same output. If I don't project, the outputs for different inputs are different, i.e. expected behavior.

For my use case, I need the latitude and longitude for each node. Hence, I cannot do without projecting the graph.

#### What operating system, architecture, Python version, and OSMnx version are you using?
MacOS Mojave 10.14, Python 3.7.6, OSMnx==0.11.4

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
# Paste the output of your Python packages and their versions here, between these two "details" tags
attrs              19.3.0     
azure-core         1.2.1      
azure-storage-blob 12.1.0     
certifi            2019.9.11  
cffi               1.13.2     
chardet            3.0.4      
Click              7.0        
click-plugins      1.1.1      
cligj              0.5.0      
cryptography       2.8        
cycler             0.10.0     
decorator          4.4.1      
descartes          1.1.0      
Fiona              1.8.13     
Flask              1.1.1      
geographiclib      1.50       
geopandas          0.6.3      
geopy              1.20.0     
gunicorn           20.0.4     
idna               2.8        
isodate            0.6.0      
itsdangerous       1.1.0      
Jinja2             2.10.3     
kiwisolver         1.1.0      
MarkupSafe         1.1.1      
matplotlib         3.1.3      
msrest             0.6.10     
munch              2.5.0      
networkx           2.4        
numpy              1.17.3     
oauthlib           3.1.0      
osmnx              0.11.4     
pandas             1.0.1      
pip                20.0.2     
polyline           1.4.0      
progressbar2       3.47.0     
pycparser          2.19       
pymongo            3.9.0      
pyparsing          2.4.5      
pyproj             2.4.2.post1
python-dateutil    2.8.1      
python-utils       2.3.0      
pytz               2019.3     
requests           2.22.0     
requests-oauthlib  1.3.0      
Rtree              0.9.3      
setuptools         45.1.0     
Shapely            1.7.0      
six                1.12.0     
urllib3            1.25.7     
Werkzeug           0.16.0     
wheel              0.33.6 
</details>

#### Code snippet that independently and completely reproduces the issue

```python
bbox = (13.1105752581959, 12.8227927418041, 77.7679309759084, 77.4726182240916)
G = ox.graph_from_bbox(*bbox, network_type='drive_service')
G_projected = ox.project_graph(G)

# lat-longs of two points: source and destination
s = (12.9581809, 77.6022779)
d = (12.961213, 77.690655)

# using the unprojected graph
ox.get_nearest_node(G, s) # returns 60952298
ox.get_nearest_node(G, d) # returns 320630059

# using the projected graph
ox.get_nearest_node(G_projected, s) # returns 1513928872
ox.get_nearest_node(G_projected, d) # returns 1513928872

```

**Comment by agdhruv** [comment]
Surprisingly, I get different outputs if I project to `EPSG:4326`, but again incorrect (i.e. same) outputs if I project to `EPSG:3857`. `EPSG:3857` is preferred because OSM an Google Maps both use it, and my service interacts with both of them.

**Comment by gboeing** [comment]
@agdhruv are you using an appropriate `method` argument when you call `get_nearest_node`? See the docs: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.geo_utils.get_nearest_node

> Which method to use for calculating distances to find nearest node. If ‘haversine’, graph nodes’ coordinates must be in units of decimal degrees. If ‘euclidean’, graph nodes’ coordinates must be projected.

So, if you're using a projected coordinate system, you need to make sure you're using `method='euclidian'` to calculate distances because using the law of haversines wouldn't make sense. Conversely if you're using a geographic coordinate system, you need to make sure you're using `method='haversine'` to calculate distances along the curved surface of the Earth.

But, secondly, there's another problem with your code. In this snippet:
```
# using the projected graph
ox.get_nearest_node(G_projected, s) # returns 1513928872
ox.get_nearest_node(G_projected, d) # returns 1513928872
```

You are looking for nodes in a projected graph, but you never projected `s` and `d`. So you're essentially searching in a metric space for the nodes nearest to two points represented by coordinates in decimal degrees. Make sure you're working consistently in the same units and in the same projections.

**Comment by gboeing** [comment]
Is this issue ready to be closed?

**Comment by agdhruv** [comment]
Yes, thank you for the help and sorry for the delayed response.
