### ISSUE TITLE
Feature Request: Retrieve OSM Data for Specific Date

### ISSUE THREAD

**Issue by kanaad** [gboeing/osmnx#384]
First off, osmnx is incredibe and has made a lot my work a lot easier, so thank you to all who have contributed!

Recently, San Francisco closed Market Street, and now retrieving the the 'drive' network type does not include those edges - since the data I'm using in conjunction with the map is from last year, this presents a problem.

I'm curious as to how possible it is to specify a date when retrieving OSM data, as just another argument in, for example, the graph_from methods.

**Comment by gboeing** [comment]
Thanks for the suggestion! I'm not sure how trivial or complicated this would be. If you know more about it, please share what would be involved or some sample code snippets and we can discuss how it fits with the OSMnx project here.

**Comment by kanaad** [comment]
I should mention that I have very little experience using the Overpass API. However, it seems that there is a data parameter that can be passed into the API, seen [here](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#OSM_data_at_a_certain_date).

Is it possible that a date can be added to the query string passed to `overpass_request`?

**Comment by pmartincalvo** [comment]
Dropping by to add this feature would be very useful. I'm not sure if any work has been done on this, would be willing the lend a helping hand.

**Comment by gboeing** [comment]
If someone wants to create a simple PR for this, I'm open to reviewing it.

**Comment by pmartincalvo** [comment]
Will look into it.

**Comment by gboeing** [comment]
closed in #405

**Comment by sunayana** [comment]
@gboeing : Could you say, when the date is given in the config, is the data extracted from OSM till that date or only on that date. 
Thanks!

**Comment by gboeing** [comment]
Hi @sunayana, per the contributing guidelines, best to ask "how-to" usage questions on StackOverflow as the issue tracker is reserved for fixing bugs and proposing new features.
