### ISSUE TITLE
Clipping OSMnx graphs

### ISSUE THREAD

**Issue by mannbenji** [gboeing/osmnx#388]
Hi, thanks a lot for this great package. I am currently running into two problems. Firstly, I am running a loop that computes a graph for each neighbourhood (polygon) of a list of cities (GeoDataFrames). It then computes some network statistics for the graph and writes the file out to disk. The problem is that the loop is extremely long to compute because the graph is computed for each row. If there is a good way to bypass this problem, could you suggest it? 

Secondly, the solution I am trying is that, instead of computing the graph for each neighbourhood, I compute it for the city as a whole, and then clip the graph to the neighbourhood boundaries. However, I am not aware of a function in OSMnx or in Networkx that does that. Could you confirm no such function does not exist? Thanks.

**Comment by gboeing** [comment]
Yes you can create subgraphs of your original graph. Per the new issue template, the issue tracker is for bug reporting. Please ask your how-to question on https://stackoverflow.com/
