### ISSUE TITLE
Feature request - adding bike-able walking segments in bike network type

### ISSUE THREAD

**Issue by niteshshah12** [gboeing/osmnx#389]
I used the following code to import the bike network from osmnx.

```python
#import network data 
place = "Nashville, USA"
G0 = ox.graph_from_address(place, distance=1000, simplify=True, network_type='bike')

#plot network graph
fig, ax = ox.plot_graph(G0);
plt.tight_layout()
plt.show()
```
I am working with GPS trace data of bicycling, which has points on the Pedestrian bridge (pointed by a red circle in the image below). But osmnx doesn't download such segments if I pass "bike" as network type.
![Image](https://user-images.githubusercontent.com/51802001/74767150-49604d80-5254-11ea-8e3c-88fbd7f7dd17.png)
Is there any way to download such bike-able walking segments? Also, is there any quick way to clean up such a network?

Nitesh

**Comment by gboeing** [comment]
What is the OSM ID of the way you circled? And how exactly is it tagged on OSM?

**Comment by gboeing** [comment]
Ah I found it. For reference it is [this way](https://www.openstreetmap.org/way/89757744) on OSM. The following code seems to work for me.

```python
import osmnx as ox
p = (36.16238, -86.77257)
G = ox.graph_from_point(p, network_type='bike', retain_all=True)
```

**Comment by gboeing** [comment]
The problem is that the bridge (as currently digitized) doesn't connect to any other bikeable infrastructure on either end, so the graph is disconnected. Using `retain_all=True` keeps all components of the disconnected graph.

**Comment by niteshshah12** [comment]
Thanks. 
Also, can I make a query for a bike-able footpath (for example this [foothpath](https://www.openstreetmap.org/way/591997448))?

I see a lot of cycling/scooter activity on those paths too. So, I want to merge these footpaths with the "bike" network.

**Comment by gboeing** [comment]
It is not currently tagged on OSM to allow bicycle traffic. Your best bet is to use the `custom_filter` argument to query for precisely what you would like. OSMnx's built-in network types usually work reasonably well but for individual precision, a custom filter is more powerful. You can see an example of what the filters look like here: https://github.com/gboeing/osmnx/blob/master/osmnx/downloader.py#L63-L65

**Comment by niteshshah12** [comment]
Thanks.
