### ISSUE TITLE
Numerical summaries of edge bearing distributions

### ISSUE THREAD

**Issue by mannbenji** [gboeing/osmnx#391]
Hello, thanks again for this great package. I'm really interested in OSMnx's ability to derive street edge bearings. I'd like to use that property of street networks in a regression and so need a numerical summary of bearing distribution for a graph. I see from [this article](https://appliednetsci.springeropen.com/articles/10.1007/s41109-019-0189-1) that a normalised measure of orientation order (φ in the article) can be calculated. However, I was wondering whether osmnx already had this feature.

**Comment by gboeing** [comment]
It's not built in, but you can adapt the code from here: https://github.com/gboeing/osmnx-examples/blob/master/notebooks/17-street-network-orientations.ipynb

Once you get the distribution of bearings using that code, you can just apply the formulas to calculate the entropy then convert it to orientation order as described in the article.
