### ISSUE TITLE
Not able to get route

### ISSUE THREAD

**Issue by Dartartmirus** [gboeing/osmnx#392]
Hello! I have been trying to get routes for Moscow, Russia, but for two destination graph shows the same node. What i do:
```
import networkx as nx
import osmnx as ox
import requests
import matplotlib.cm as cm
import matplotlib.colors as colors
ox.config(use_cache=True, log_console=True)
ox.config(overpass_endpoint='https://lz4.overpass-api.de/api/interpreter')
print(ox.__version__)
place = {'city' : 'Moscow',
         'country' : 'Russia'}
G = ox.graph_from_place(place, network_type='drive')
G_projected = ox.project_graph(G)
ox.save_graphml(G_projected, filename='NewnetworkDrive.graphml')
G = ox.load_graphml('NewnetworkDrive.graphml')
# get the nearest network node to each point
orig_node = ox.get_nearest_node(G, (55.754715, 37.583251))
dest_node = ox.get_nearest_node(G, (55.753994, 37.656282))
route = nx.shortest_path(G, orig_node, dest_node, weight='time')
fig, ax = ox.plot_graph_route(G, route, node_size=0)
```
This is what i get as a result:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/60848256/74972326-8a15bd80-5432-11ea-8cb5-a79f64b6233e.png">

And when i try to calculate distance i get zero:
`nx.shortest_path_length(G, orig_node, dest_node, weight='length')`

I use osmnx 0.11.4 on MacOS. My conda packages:

<details>
# Name                    Version                   Build  Channel
attrs                     19.3.0                     py_0    conda-forge
boost-cpp                 1.70.0               h75728bb_2    conda-forge
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            he1c11cd_1002    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
cffi                      1.13.2           py38h33e799b_0    conda-forge
cfitsio                   3.470                h84d2f63_2    conda-forge
chardet                   3.0.4                 py38_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.8              py38hafa8578_1    conda-forge
curl                      7.68.0               h8754def_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.1                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
fiona                     1.8.13           py38he71f6a4_0    conda-forge
folium                    0.10.1                     py_0    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      3.0.4            py38h97c3584_0    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.6.3                      py_0    conda-forge
geopy                     1.21.0                     py_0    conda-forge
geos                      3.8.0                h4a8c4bd_0    conda-forge
geotiff                   1.5.1                hc9fff18_8    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                h0b31af3_1    conda-forge
glib                      2.58.3          py38h577aef8_1002    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.8                   py38_1000    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            h6659575_1005    conda-forge
kiwisolver                1.1.0            py38ha1b3eb9_0    conda-forge
krb5                      1.16.4               h1752a42_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.68.0               h709d2b2_0    conda-forge
libcxx                    9.0.1                         1    conda-forge
libdap4                   3.20.4               habf5908_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   3.0.4                hf96e369_0    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.7.3           nompi_hda4e5f1_101    conda-forge
libopenblas               0.3.7                h3d69b6c_7    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     12.1                 h31a01ba_0    conda-forge
libspatialindex           1.9.3                h4a8c4bd_1    conda-forge
libspatialite             4.3.0a            h9c28a66_1034    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.1.0                ha78913b_3    conda-forge
libwebp                   1.0.2                hd3bf737_5    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
llvm-openmp               9.0.1                h28b9765_2    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py38h0b31af3_0    conda-forge
matplotlib                3.1.3                    py38_0    conda-forge
matplotlib-base           3.1.3            py38h11da6c2_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
numpy                     1.18.1           py38hde6bac1_0    conda-forge
openjpeg                  2.3.1                hcdae239_3    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
osmnx                     0.11.4                     py_0    conda-forge
pandas                    1.0.1            py38h4f17bb1_0    conda-forge
pcre                      8.43                 h4a8c4bd_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
poppler                   0.67.0               h16886b5_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.1                 h26bc10f_0    conda-forge
proj                      6.3.0                h773a61f_0    conda-forge
pycparser                 2.19                     py38_1    conda-forge
pyopenssl                 19.1.0                   py38_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.4.2.post1      py38hf8af742_1    conda-forge
pysocks                   1.7.1                    py38_0    conda-forge
python                    3.8.1                hf2284b6_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py38_1    conda-forge
rtree                     0.9.3            py38h7b0cdae_0    conda-forge
scikit-learn              0.22.1           py38h3dc85bc_1    conda-forge
scipy                     1.4.1            py38h82752d6_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
shapely                   1.7.0            py38h999ffa5_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.7.0                hd5e958f_2    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
tornado                   6.0.3            py38h0b31af3_2    conda-forge
tzcode                    2019a             h01d97ff_1002    conda-forge
urllib3                   1.25.7                   py38_0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                he7fca8b_1    conda-forge

</details>
What should i do to calculate routes? I do everything like in example notebooks.

**Comment by gboeing** [comment]
Per the contributing guidelines, please ask how-to questions on StackOverflow to reserve the issue tracker for bugs and feature development. But in short, you're projecting your graph and then searching for its nearest node to an unprojected (lat-lng) coordinate pair.
