### ISSUE TITLE
Feature Request: Edge length taking into account the geometry of the street

### ISSUE THREAD

**Issue by pareyesv** [gboeing/osmnx#394]
AFAIK the edge attribute `length` (by using [`add_edge_length`](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.add_edge_lengths)) computes the `great_circle_vec` between the origin node and the destination node. So it doesn't take into account the full geometry of the edge, only the first and the last nodes of the edge.

On the other hand, the length of a (shapely) LineString (`edge["geometry"].length`) takes into account the full geometry of the street, but the distance function is the Euclidean Distance or Linear distance between two points on a plane (And the result is not measured in meters).

I think It'd be nice to have a sort-of _street_length_ (a function to compute `great_circle_vec` with the full geometry of the LineString). Maybe the running time is to long? I know that this new _street_length_ attribute would take longer compared to the current `length`...

My first approach is the following (Based on answers from [StackExchange](https://gis.stackexchange.com/a/115285) and [StackOverflow](https://stackoverflow.com/questions/1257413/1257446#1257446)):

```
def street_length(line):
    """Calculate length of a line in meters, given in geographic coordinates.
    Args:
        line: a shapely LineString object
    Returns:
        Length of line in meters
        
    Source:
        https://gis.stackexchange.com/a/115285
    """
    # Swap shapely (lonlat) to geopy (latlon) points
    latlon = lambda lonlat: (lonlat[1], lonlat[0])
    total_length = sum(
        great_circle_vec(*latlon(a), *latlon(b)) for (a, b) in pairs(line.coords)
    )
    return round(total_length, 0)


def pairs(lst):
    """Iterate over a list in overlapping pairs without wrap-around.

    Args:
        lst: an iterable/list

    Returns:
        Yields a pair of consecutive elements (lst[k], lst[k+1]) of lst. Last 
        call yields the last two elements.

    Example:
        lst = [4, 7, 11, 2]
        pairs(lst) yields (4, 7), (7, 11), (11, 2)

    Source:
        https://stackoverflow.com/questions/1257413/1257446#1257446
    """
    i = iter(lst)
    prev = next(i)
    for item in i:
        yield prev, item
        prev = item
```

PS: I started using osmnx a couple of months ago. So please correct me if I am wrong.

**Comment by gboeing** [comment]
> AFAIK the edge attribute length (by using add_edge_length) computes the great_circle_vec between the origin node and the destination node. So it doesn't take into account the full geometry of the edge, only the first and the last nodes of the edge.

Yes, but: in the OSMnx workflow when you call, for example, `ox.graph_from_place`, OSMnx constructs the graph, then calls `add_edge_lengths`, and then simplifies the graph. Prior to simplification, the graph edges are all straight-line approximations of curves, so `add_edge_lengths` estimates the true length of each segment. When simplification occurs, we sum those length attributes of the segments as we aggregate them into a single (curving) edge in the final graph.

**Comment by pareyesv** [comment]
(Sorry for my late reply...)

OK. I understand the workflow now. Thanks.

However, I still think it'd be nice to have a sort of _street_length_ as explained above.

For example: I just started a project where I have to split streets constructed with `ox.graph_from_place`. I also have to add new streets.
So my first approach of re-computing the lengths again with `add_edge_lengths` didn't work because of what you explained above. I think I'll run the version of `street_length` (proposed [above](https://github.com/gboeing/osmnx/issues/394#issue-571592006)) to get the length of the new/modified streets. Please let me know If there is a better _OSMnx-ic_ way to do it.

**Comment by gboeing** [comment]
Yes this might be a useful addition for the use case you describe. But I also wonder if it would be more sensible for the function to expect a projected graph and then just calculate euclidean distances of the sub-segments?

**Comment by pareyesv** [comment]
OK. I understand the idea, but I have no experience in spatial graph projections...
(If you have time) Could you please elaborate on this?
Do you have any specific reference to start reading about it? Or link to a piece of code?

I'll look into it.

**Comment by pareyesv** [comment]
I think what you suggest is the [`euclidean_dist_vec`](https://github.com/gboeing/osmnx/blob/019228a8a17943abfc9e3665987baac16085f0f4/osmnx/utils.py#L213) instead of `great_circle_vec` but over a _projected graph_? If this is the case, I still don't know how to _project_ the graph...

I'll look into it.

**Comment by gboeing** [comment]
> I still don't know how to project the graph...

I'd suggest reading through the OSMnx documentation and examples repo to get started.
