### ISSUE TITLE
Allow folium plotting functions to accept FeatureGroup in place of Map, and **kwargs

### ISSUE THREAD

**Issue by eecharlie** [gboeing/osmnx#396]
#### Problem description 
I expected the following to work:

```
fg = folium.FeatureGroup(name='legend name', show=False)
ox.plot_route_folium(G, route, route_color='green', route_map=fg, tooltip='some tooltip')
```
However the extra argument (meant to be passed to folium) is not accepted, and `plot_route_folium` makes a member function call that a FeatureGroup does not have, 
`route_map.fit_bounds(bounds)`

#### What operating system, architecture, Python version, and OSMnx version are you using?

Ubuntu 4.15.0, x86_64, Python 3.8.1

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bokeh                     1.4.0                    py38_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cachetools                4.0.0                    pypi_0    pypi
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
cffi                      1.13.2           py38h8022711_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4                 py38_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
cryptography              2.8              py38h72c5cf5_1    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py38h516909a_0    conda-forge
dask                      2.11.0                     py_0    conda-forge
dask-core                 2.11.0                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
distributed               2.11.0                   py38_0    conda-forge
entrypoints               0.3                   py38_1000    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fiona                     1.8.13           py38h900e953_0    conda-forge
folium                    0.10.1                     py_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
gdal                      3.0.4            py38hbb6b9fb_0    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.6.3                      py_0    conda-forge
geopy                     1.21.0                     py_0    conda-forge
geos                      3.8.0                he1b5a44_0    conda-forge
geotiff                   1.5.1                h38872f0_8    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.2.1                h516909a_1    conda-forge
glib                      2.58.3          py38h6f030ca_1002    conda-forge
google-api-core           1.16.0                   pypi_0    pypi
google-auth               1.11.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-cloud-bigquery     1.24.0                   pypi_0    pypi
google-cloud-core         1.3.0                    pypi_0    pypi
google-resumable-media    0.5.0                    pypi_0    pypi
googleapis-common-protos  1.51.0                   pypi_0    pypi
gst-plugins-base          1.14.5               h0935bb2_1    conda-forge
gstreamer                 1.14.5               h36ae1b5_1    conda-forge
haversine                 2.2.0                      py_0    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py38_1000    conda-forge
ipykernel                 5.1.4            py38h5ca1d4c_0    conda-forge
ipython                   7.12.0           py38h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.16.0                   py38_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jupyter_client            5.3.4                    py38_1    conda-forge
jupyter_core              4.6.1                    py38_0    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
kiwisolver                1.1.0            py38hc9558a2_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   3.0.4                h20022a4_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     12.1                 hd9ab2ff_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             4.3.0a            ha48a99a_1034    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py38h516909a_0    conda-forge
matplotlib                3.1.3                    py38_0    conda-forge
matplotlib-base           3.1.3            py38h250f245_0    conda-forge
msgpack-python            1.0.0            py38hc9558a2_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.18.1           py38h95a1406_0    conda-forge
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
osmnx                     0.11.4                     py_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.1            py38hb3f55d8_0    conda-forge
pandas-gbq                0.13.0                   pypi_0    pypi
parso                     0.6.1                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.8.0                    py38_0    conda-forge
pickleshare               0.7.5                 py38_1000    conda-forge
pillow                    7.0.0            py38hefe7db6_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.1                 hc63931a_0    conda-forge
proj                      6.3.0                hc80f0dc_0    conda-forge
prompt_toolkit            3.0.3                      py_0    conda-forge
protobuf                  3.11.3                   pypi_0    pypi
psutil                    5.7.0            py38h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.19                     py38_1    conda-forge
pydata-google-auth        0.3.0                    pypi_0    pypi
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                   py38_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.4.2.post1      py38h8ff28aa_1    conda-forge
pyqt                      5.12.3           py38hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1                    py38_0    conda-forge
python                    3.8.1                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py38h516909a_0    conda-forge
pyzmq                     18.1.1           py38h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py38_1    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
rtree                     0.9.3            py38h7b0cdae_0    conda-forge
scikit-learn              0.22.1           py38hcdab131_1    conda-forge
scipy                     1.4.1            py38h921218d_0    conda-forge
seaborn                   0.10.0                     py_1    conda-forge
setuptools                45.2.0                   py38_0    conda-forge
shapely                   1.7.0            py38h5d51c17_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
statsmodels               0.11.1           py38h516909a_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py38h516909a_3    conda-forge
tqdm                      4.42.1                     py_0    conda-forge
traitlets                 4.3.3                    py38_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.7                   py38_0    conda-forge
utm                       0.5.0                      py_0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge

</details>

#### Code snippet that independently and completely reproduces the issue

```python
# Minimal test case for osmnx feature request

import numpy as np
import osmnx as ox
import networkx as nx
import folium

# creating a graph by using a point in downtown Omaha
old_market = (41.255676, -95.931338)
G = ox.graph_from_point(old_market, distance=500)

# using NetworkX to calculate the shortest path between two random nodes
route = nx.shortest_path(G, np.random.choice(G.nodes), 
                         np.random.choice(G.nodes))

# This works, as expected
ox.plot_graph_route(G, route, fig_height=10, fig_width=10)

# Now I want to plot the route as part of a FeatureGroup so
# it can be toggled etc., and I want to tweak aspects of the mapped
# shape in addition color. 
# But I can't attach the route to a non-map Folium object, or pass-through
# additional arguments that would go to e.g. Folium.PolyLine

m = folium.Map()
fg = folium.FeatureGroup(name='legend name', show=True)

# Expect this function to accept other folium objects for route_map, 
# and pass on **kwargs to Folium primitive shape plotting functions
ox.plot_route_folium(G, route, route_color='green', 
                    route_map=fg, tooltip='some tooltip')
m.add_child(fg)
display(m)
```

**Comment by gboeing** [comment]
I'm open to this enhancement. It might be a useful opportunity to rethink how the OSMnx folium functionality works. Originally, I just quickly through it together for simple mapping but it may be better to make it more general. I'm open to a PR.

**Comment by eecharlie** [comment]
Great, I will see if I can do that. It's a straightforward change, I anticipate most of the work being setting up good unit tests.

**Comment by eecharlie** [comment]
Submitted #472

**Comment by lilly-yang-th** [comment]
I am receiving the following error:
 **warn("`route_color` has been deprecated and will be removed: use kwargs instead")**

when I wanted to change the route color by running the following code:
`TSP_map = ox.plot_route_folium(Gs, routes[i],route_map=TSP_map, route_color=colors[group%len(colors)])`

 Could you please let me know how to solve this issue with kwargs**?

**Comment by eecharlie** [comment]
The typical folium color argument is ‘color=‘ but I don’t have the source code in front of me to check or test. I’d try replacing route _color with color.

>

**Comment by gboeing** [comment]
@lilly-yang-th per the contributing guidelines, please ask how-to usage questions on StackOverflow.
