### ISSUE TITLE
save_gdf_shapefile() cannot be used directly on a Geodataframe created from pois_from_polygon()

### ISSUE THREAD

**Issue by tyk122** [gboeing/osmnx#397]
I am pretty new to all of this so I apologize if something here is not in line with the expectations and standards.

#### Problem description (what did you do, what did you expect to happen, and what actually happened)

I discovered that <code>save_gdf_shapefile()</code> will not work on a GDF created with `pois_from_place()`.  While I could not explicitly find the root cause, I eventually got this to work by separating the GDF by <code>element_type</code> (e.g. <code>gdf[gdf['element_type'] == 'way']</code>), otherwise the following error is produced:

```python
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-73-04a804becda8>", line 1, in <module>
    ox.save_gdf_shapefile(pois.loc[: ,cols[0]:cols[10]],"test",os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop'))
  File "C:\Miniconda3\lib\site-packages\osmnx\save_load.py", line 62, in save_gdf_shapefile
    gdf.to_file(folder_path)
  File "C:\Miniconda3\lib\site-packages\geopandas\geodataframe.py", line 533, in to_file
    to_file(self, filename, driver, schema, index, **kwargs)
  File "C:\Miniconda3\lib\site-packages\geopandas\io\file.py", line 193, in to_file
    colxn.writerecords(df.iterfeatures())
  File "C:\Miniconda3\lib\site-packages\fiona\collection.py", line 342, in writerecords
    self.session.writerecs(records, self)
  File "fiona/ogrext.pyx", line 1198, in fiona.ogrext.WritingSession.writerecs
RuntimeError: Failed to write record: {'id': '44580739', ....
```
As such, it appears that this will not work if there are mixed geometries in the GDF.  This is not surprising, but may not be immediately obvious.  OSM has POIs as both polygons and points, which means that if pulled into a single GDF, they cannot be immediately processed as a shape file.

I'm not really sure how this should be addressed.  That said, if anyone else is trying to do this, I spent a considerable amount of time tracking this issue down.  It would be helpful to note this somewhere.

#### What operating system, architecture, Python version, and OSMnx version are you using?

* **Operating System:** Windows 10
* **Architecture:** 64-bit
* **Python version:** 3.7.4
* **OSMnx version:** 0.11.4

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
Not relevant
</details>

#### Code snippet that independently and completely reproduces the issue

```python
import osmnx as ox
import os

# Get city boundaries
city = ox.gdf_from_place('San Francisco, California')

# Get all POIs in boundary
pois = ox.pois_from_polygon(city['geometry'].values[0])

# Save as .shp
ox.save_gdf_shapefile(pois, 'tests', os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop'))

```

**Comment by gboeing** [comment]
To save your `pois` shapefile to disk, just use:

```python
pois.to_file('pois')
```
Per [the docs](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.save_load.save_gdf_shapefile), `save_gdf_shapefile` is for saving "a GeoDataFrame of place shapes or footprints as an ESRI shapefile" but you're passing it a GeoDataFrame of POIs instead.

**Comment by tyk122** [comment]
Thanks @gboeing . I was trying to get some points of interest for a map I was working on and was kind of flying blind as I couldn't find a tutorial on the POIs feature.  The main reason I wrote this up is that it took me a long time to determine why this didn't appear to be working.  Unfortunately, I can't test this because I don't have the same set up at the moment (being stuck at home and all), but I am going to try to describe what the issue was.

Looking at the traceback, it doesn't seem clear that `to_file` would have made a difference, since `save_gdf_shapefile` basically appears to be a fancy wrapper for `to_file`.  As such, I'm not entirely sure what the distinction is, but even if its intended use was meant for polygons, it appears to work with points as well.  Honestly, I think I probably just copied the code from an example and changed things, not knowing what is proper and what is not.

Furthermore, after some experimenting and research, I came to realize that the underlying problem is that POIs in OSM appear to be represented as both points and polygons (i.e. some places are represented as just a point, while other places are represented as though they are a building footprint, such as the boundaries of a school or shopping center which may include buildings), but points and polygons cannot be saved in the same shapefile (I forget how exactly I came to this realization, but this [post](https://gis.stackexchange.com/questions/74627/merging-shapefiles-with-different-geometries-point-and-polygon-to-get-single-l) seems to confirm this).  In hindsight, this should be obvious since I believe the nodes and links of the street network are separate shape files in `save_graph_shapefile` function.  And of course, this all caused problems when trying to write to file.

I do have some other work to do, but if I get some time, I might try to see if I can get a tutorial going.  Hopefully I've better explained the issue, please let me know!

**Comment by gboeing** [comment]
> the underlying problem is that POIs in OSM appear to be represented as both points and polygons (i.e. some places are represented as just a point, while other places are represented as though they are a building footprint, such as the boundaries of a school or shopping center which may include buildings), but points and polygons cannot be saved in the same shapefile

Correct. You'll need to use a compatible file format like [GeoJSON](https://geopandas.org/io.html#writing-spatial-data) if you want to save mixed geometry types in a single file, like:

```python
pois.to_file('pois.geojson', driver='GeoJSON')
```

**Comment by tyk122** [comment]
Good to know.  I haven't really worked with GeoJSON files (and my cursory search seems to indicate you eventually need to convert them to shapefiles anyway, so my preference would be to keep things as shape files.  In the case of my project, my solution was simply to separate them out as separate GeoDataFrames and save the as shapefiles separately.  In the case anyone wants to get POIs as shapefiles, you can use the following snippets to get any of the corresponding geometries:

```
gdf[gdf['element_type'] == 'node']     # corresponds to points
gdf[gdf['element_type'] == 'way']      # corresponds to polygons
gdf[gdf['element_type'] == 'relation'] # corresponds to relations
```

I'm not entirely clear about "relations" here, but the [OSM wiki seems to provide some guidance](https://wiki.openstreetmap.org/wiki/Elements).  Anyway...thanks for the guidance!
