### ISSUE TITLE
'walk' filter doesn't include shared cycleways

### ISSUE THREAD

**Issue by swiss-knight** [gboeing/osmnx#398]
Hello,

I installed `osmnx` using `pip3` on Ubuntu 18.04.

#### Problem description (what did you do, what did you expect to happen, and what actually happened)

I recently saw that the 'walk' filter doesn't take into account the shared cycleways.
In some cases where these are the only way to cross a river for pedestrians without having to make a detour of several kilometers, it would be nice if it could be added to the walk filter.

#### What operating system, architecture, Python version, and OSMnx version are you using?
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
Ubuntu 18.04 LTS 64-bits (`5.3.0-40-generic x86_64 GNU/Linux`)
`osmnx.__version__`  '0.11.4'

#### Code snippet that independently and completely reproduces the issue

```python
import osmnx as ox
ox.core.get_osm_filter('walk')

'["area"!~"yes"]["highway"!~"cycleway|motor|proposed|construction|abandoned|platform|raceway"]["foot"!~"no"]["service"!~"private"]["access"!~"private"]'
```
This exclude the cycle-ways. Simply.    
But in fact, cycle-ways, when not explicitly forbidden for pedestrian may allow them to use them. In some other cases, they are explicitly shared or segregated :  https://wiki.openstreetmap.org/wiki/Key:segregated    
Concretely, it's really rare that they're not allowed for pedestrians.

I tried to modify the filter, but didn't succeed because I cannot figure out how I can tell a specific tag-based filter string to apply only on `cycleway` and not also to all others highways.

**Comment by gboeing** [comment]
See also #389

**Comment by gboeing** [comment]
You didn't provide a complete code example for me to test against, but a custom filter like this should work:

```
'["area"!~"yes"]["highway"!~"motor|proposed|construction|abandoned|platform|raceway"]["foot"!~"no"]["service"!~"private"]["access"!~"private"]'
```

That filter mimics the one provided by `ox.core.get_osm_filter('walk')`, but it no longer filters out cycleways. It does however filter out everything tagged foot=no. You may need to tweak this custom filter to pull in precisely what you're looking for.

**Comment by gboeing** [comment]
By "custom filter" I mean the `custom_filter` parameter in functions like `graph_from_polygon`: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_polygon
