### ISSUE TITLE
Catch MultiPolygons with Topological Errors

### ISSUE THREAD

**Issue by AtelierLibre** [gboeing/osmnx#399]
#### Problem description
As described in recent comments on the closed issue #330, MultiPolygon Relations with invalid inner or outer rings currently cause a TopologicalError that prevents creation of a GeoDataFrame of Footprints.

#### What operating system, architecture, Python version, and OSMnx version are you using?
Ubuntu 18.04, Python 3.7.6, OSMnx 0.11.4

#### Code snippet that independently and completely reproduces the issue
The error can be reproduced by processing the attached zipped json as follows:
```
with open('invalid_multipolygons.json', 'r', encoding='utf-8') as f:
    response_jsons = json.load(f)
test_gdf = ox.create_footprints_gdf(retain_invalid=False, responses=response_jsons)
```

I have started a branch [in my repository](/AtelierLibre/osmnx/tree/iss330b) which includes a fix as suggested by @martibosch. It also logs in greater detail invalid geometries found during the creation of the footprints GDF and their removal.

If it's easier I can make this a pull request.

[invalid_multipolygons.zip](https://github.com/gboeing/osmnx/files/4299172/invalid_multipolygons.zip)

**Comment by gboeing** [comment]
Is it possible to fix the invalid geometries with something as simple as `geometry.buffer(0)`? OSMnx uses this workflow elsewhere to prevent topological errors breaking code.

**Comment by AtelierLibre** [comment]
I'm not sure, I'll have a look into it. I suspect it may help with some cases but not others.
One of the things I'm working on is being much more explicit in the logging about what gets rejected. This helps identify the kinds of footprint geometry and tagging that currently might cause problems.

**Comment by gboeing** [comment]
see proposed fix in #406

**Comment by gboeing** [comment]
FYI @AtelierLibre the merged fix in #406 fixes the reproducible error you provided in https://github.com/gboeing/osmnx/issues/399#issue-577039870

**Comment by AtelierLibre** [comment]
@gboeing Thanks. Sorry, there's a lot going on at the moment and I haven't really been able to follow this up.

I think there is a larger issue around what 'fix' means in this context. geometry.buffer(0) may create a 'valid' geometry that can be processed by the following steps but as far as I understand it is uncertain what geometry actually gets returned (see [Shapely issue 599](https://github.com/Toblerity/Shapely/issues/599)). I think the proposed change may allow OSMnx to process some additional multipolygons with minor invalidities but a more robust solution would be more explicit handling/rejection of invalid geometry that comes directly from OSM.

I can't promise to look at that at the moment so I can understand if you would rather leave this closed.

**Comment by gboeing** [comment]
To clarify, the specific invalid geometries we are handling are "improperly" digitized geometries on OSM right? If so, I'm inclined to use #406 as at least a temporary fix because it allows OSMnx to receive the geometries from OSM as close to "as-is" as possible. Subsequent work after that could be more of feature enhancements rather than fixing an exception-causing bug (which this was).

**Comment by AtelierLibre** [comment]
Yes, that's right. I can understand your preference to keep as much geometry as possible. I was hesitant because I think geometry.buffer(0) will fix specific invalid geometries (like the one I provided) but not others - so hypothetically the exception could still occur. I don't have an example right now though, so may be overcomplicating this.
I'll keep working on my branch and will raise other things separately. Thanks again.
