### ISSUE TITLE
Some trouble with graph serialization

### ISSUE THREAD

**Issue by manuelep** [gboeing/osmnx#4]
Hi!
It seams graph created with **osmnx** (v. 1.11) are not supported by some **NetworkX** serializers (at least *graphml* and *gml*), for example I tried:

```python
import osmnx as ox
from networkx.readwrite import write_graphml
bbox_nsew = (44.5154836411, 44.4930257589, 11.3460649038, 11.3240450721,)
G = ox.graph_from_bbox(*bbox_nsew, simplify=False)
write_graphml(G, "mygraph.xml")
```
obtaining to raise this exception:

> Traceback (most recent call last):
>   File "iNetworkX_unittest.py", line 45, in setUp
>     write_graphml(G, "mygraph.xml")
>   File "<decorator-gen-202>", line 2, in write_graphml
>   File "/usr/local/lib/python2.7/dist-packages/networkx/utils/decorators.py", line 220, in _open_file
>     result = func(*new_args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 82, in write_graphml
>     writer.add_graph_element(G)
>   File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 349, in add_graph_element
>     self.add_attributes("graph", graph_element, data, default)
>   File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 300, in add_attributes
>     scope=scope, default=default_value)
>   File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 288, in add_data
>     '%s as data values.'%element_type)
> NetworkXError: GraphML writer does not support <type 'dict'> as data values.

I would like to save raw data for successive elaborations without downloading data again... how is it possible?

Thank you very mutch
Cheers
    Manuele

**Comment by gboeing** [comment]
You can save and load GraphML using OSMnx's built-in functions that automatically handle dict attribute serialization, as demonstrated in this [example notebook](https://github.com/gboeing/osmnx/blob/master/examples/05-example-save-load-networks-shapes.ipynb).

**Comment by manuelep** [comment]
Ok thank you very mutch!
