### ISSUE TITLE
Trouble with all_oneway, save_as_osm(), and nx.shortest_path()

### ISSUE THREAD

**Issue by mschroen** [gboeing/osmnx#403]
**Intended workflow:**
1. download a graph,
2. save it to disk,
3. load it from disk later,
4. calculate shortest paths.

This workflow will never work because of some strange behaviour of OSMnx:

1. `save_as_osm()` only works for graphs generated with `all_oneway=True`,
2. `nx.shortest_path()` only works for graphs generated with `all_oneway=False`.

Of course I am keen to learn how the workflow could be realized despite those restrictions, but since this is not stackoverflow, I would like to start trying to understand what is going on here. Is this behaviour intended? If yes, why? If not, is it a bug or a missing feature?

Minimal example:
```
import osmnx as ox
import networkx as nx
# some coordinates
c1 = [33.3147, -111.90112]
c2 = [33.3053, -111.89607]
```

Deijkstra works, save doesn't:
```
# Read with oneway=False
ox.utils.config(all_oneway=False)
G = ox.graph_from_address('N. Sicily Pl., Chandler, Arizona', distance=800, network_type='drive')
ox.save_as_osm(G, filename='test')
# Error: does not work with oneway=False
route = nx.shortest_path(G, ox.get_nearest_node(G, c1), ox.get_nearest_node(G, c2))
# works!
```

Save works, deijkstra doesn't:
```
# Read with oneway=True
ox.utils.config(all_oneway=True)
G = ox.graph_from_address('N. Sicily Pl., Chandler, Arizona', distance=800, network_type='drive')
ox.save_as_osm(G, filename='test')
# works!
route = nx.shortest_path(G, ox.get_nearest_node(G, c1), ox.get_nearest_node(G, c2))
# Error: No path between c1 and c2
```

I thought that saving the graph with `all_oneway=True` and reading it using the bidirectional flag could be a clever hack to get the workflow running. But no, it doesn't. Even on a saved osm file no shortest paths can be found:
```
G = ox.graph_from_file('data/test', simplify=False, bidirectional=True)
route = nx.shortest_path(G, ox.get_nearest_node(G, c1), ox.get_nearest_node(G, c2))
# Error: No path between c1 and c2
```

**Comment by gboeing** [comment]
To save/load graphs to/from disk, use the https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.save_load.save_graphml and https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.save_load.load_graphml functions.

This preserves the complete graph faithfully. The `save_as_osm` function is only for serializing as an OSM XML file and cannot preserve all the networkx multidigraph details.

**Comment by mschroen** [comment]
Thank you! Can you update the documentation to make this absolutelly clear for non-experts?

It is still unclear to me why networkx cannot find paths in graphs generated with all_oneway=True.

**Comment by gboeing** [comment]
> It is still unclear to me why networkx cannot find paths in graphs generated with all_oneway=True

@mxndrwgrdnr any thoughts on this?

**Comment by mxndrwgrdnr** [comment]
@mschroen I can't say I know enough about how networkX's shortest path functions work to tell you why it doesn't work. But just thinking this through, is it not possible that in your toy example `c1` to `c2` are both simply located "upstream" of any common nodes on the one-way network and thus are essentially disconnected?

**Comment by mschroen** [comment]
This is theoretically possible, yes. But I tried it with immensly large graphs and "trivial" nodes inside it which are definitelly connected. It still does not work. Maybe it is only in some special cases, maybe "all_oneway" sometimes disconnects (initially connected) nodes. I do not know.

**Comment by mxndrwgrdnr** [comment]
If you look here (https://github.com/gboeing/osmnx/issues/356#issuecomment-571291350) the only difference between `all_oneway` and other networks is that links in the reverse direction are never created. It shouldn't be the case that links that should exist get dropped. If you can create a reproducible example showing that a path between two nodes that should be connected is not traversable then that would give us a better starting place to debug. 

As it is, I would recommend avoiding the use of "all_oneway" unless you are planning to do your analysis outside of OSMnx. The intended use case is one in which you want to leverage OSMNx as a Python pandas-based OSM editor, and then export the resulting network back to an official OSM-supported format.
