### ISSUE TITLE
AttributeError GeoDataFrame object has no attribute 'gdf_name'

### ISSUE THREAD

**Issue by cstutts** [gboeing/osmnx#407]
I'm trying to remove link type highways from an osmnx graph by converting the graph to a pandas dataframe, generating new nodes and edges dataframes that are a subset of the original and then converting the result back to a graph.  ox.gdfs_to_graph generates the following error

File <removed> line 776, in gdfs_to_graph
G.graph['name'] = gdf_nodes.gdf_name.rstrip('_nodes')
File <removed>, line 5274, in __getattr__
return object.__getattribute__(self, name)

AttributeError: 'GeoDataFrame' object has no attribute 'gdf_name

#### What operating system, architecture, Python version, and OSMnx version are you using?
Windows 10 x64
Python 3.8 osmnx version 0.11.4

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below, between the two "details" tags)

<details>
# Name                    Version                   Build  Channel
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                    py38_0    anaconda
boost-cpp                 1.70.0               h6a4c333_2    conda-forge
branca                    0.4.0                      py_0    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py38h32f6830_1    conda-forge
cffi                      1.14.0           py38ha419a9e_0    conda-forge
cfitsio                   3.470                hfa6e2cd_2    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    anaconda
cryptography              2.8              py38hb32ad35_1    conda-forge
curl                      7.68.0               h4496350_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py38hfa6e2cd_0    conda-forge
dask-core                 2.10.1                     py_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
expat                     2.2.9                he025d50_2    conda-forge
fiona                     1.8.13           py38hb7fdc2d_0    conda-forge
folium                    0.10.1                     py_0    conda-forge
freetype                  2.10.0               h563cfd7_1    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.0.4            py38h2fee047_0    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geopy                     1.21.0                     py_0    conda-forge
geos                      3.8.0                he025d50_0    conda-forge
geotiff                   1.5.1                h9633a31_8    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3          py38hc0c2ac7_1002    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.9                        py_1    conda-forge
imageio                   2.6.1                    py38_0    conda-forge
intel-openmp              2019.4                      245
ipython                   7.12.0           py38h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py38_0    anaconda
jedi                      0.16.0                   py38_0    anaconda
jinja2                    2.11.1                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            hf7dc31f_1005    conda-forge
kiwisolver                1.1.0            py38he980bc4_0    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   3.0.4                h90de84b_0    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4ece8bf_1010    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
liblapacke                3.8.0                    14_mkl    conda-forge
libnetcdf                 4.7.3           nompi_hc957ea6_101    conda-forge
libopencv                 4.2.0                    py38_2    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     12.1                 hb0bdaea_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            hd027ac7_1034    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h21b02b4_3    conda-forge
libwebp                   1.0.2                hfa6e2cd_5    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38h9de7a3e_1    conda-forge
matplotlib-base           3.1.3            py38h2981e6d_0    conda-forge
mkl                       2019.4                      245
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
networkx                  2.4                        py_0    conda-forge
numpy                     1.18.1           py38hc71023c_0    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    4.2.0                    py38_2    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1e               hfa6e2cd_0    conda-forge
osmnx                     0.11.4                     py_1    conda-forge
pandas                    1.0.1            py38he350917_0    conda-forge
parso                     0.6.1                      py_0    anaconda
pcre                      8.43                 h6538335_0    conda-forge
pickleshare               0.7.5                 py38_1000    anaconda
pillow                    7.0.0            py38h9ea1dd6_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
poppler                   0.67.0               h1707e21_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.1                 h06f7779_0    conda-forge
proj                      6.3.0                ha7a8c7b_0    conda-forge
prompt_toolkit            3.0.3                      py_0    anaconda
py-opencv                 4.2.0            py38h5ca1d4c_2    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.5.2                      py_0    anaconda
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.5.0            py38hc1560cf_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.1                he1f5543_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py38hc8d92b1_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
rtree                     0.9.4            py38hbf79ddb_0    conda-forge
scikit-image              0.16.2           py38he350917_0    conda-forge
scikit-learn              0.22.2.post1     py38h7208079_0    conda-forge
scipy                     1.3.2            py38h582fac2_0    conda-forge
setuptools                45.2.0                   py38_0    conda-forge
shapely                   1.7.0            py38h2130f3d_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tbb                       2018.0.5             he980bc4_0    conda-forge
tiledb                    1.7.0                hffbbd95_2    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py38hfa6e2cd_3    conda-forge
traitlets                 4.3.3                    py38_0    anaconda
urllib3                   1.25.7           py38h32f6830_1    conda-forge
vc                        14.1                 h0510ff6_4
vincent                   0.4.4                      py_1    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.8                      py_0    anaconda
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                hd8a0e53_1    conda-forge

</details>

#### Code snippet that independently and completely reproduces the issue

```python
import numpy as np
import osmnx_psf as ox

G = ox.graph_from_bbox(32.812469,32.765161,-96.980091,-97.052905,simplify=False)

wgs84_crs = "EPSG:4326" 
print('projecting to %s...' % wgs84_crs)
G = ox.project_graph(G, to_crs=wgs84_crs)

# Remove primary, secondary, and tertiary highway links.
nodes, edges = ox.graph_to_gdfs(G)

#Get the highway category, edge start node (u), and edge end node (v) columns as a numpy object array
highways = edges.highway.to_numpy()
u = edges.u.to_numpy()
v = edges.v.to_numpy()

#Get the rows for highways that are not links
links = ["primary_link","secondary_link","tertiary_link"]
edge_ids =  [row for row, highway in enumerate(highways) if any(link in highway for link in links) is False]

#Store a new edges dataframe not containing links
new_edges = edges.iloc[edge_ids,:]

#Get a list of remaining unique nodes in edges
uv = np.unique(np.concatenate((u[edge_ids],v[edge_ids])))

#Remove nodes that are not in this list
node_values = nodes.index.values
node_ids = [row for row,value in enumerate(node_values) if any(node == value for node in uv)]
new_nodes = nodes.iloc[node_ids,:]

G = ox.gdfs_to_graph(new_nodes,new_edges)```

**Comment by gboeing** [comment]
> I'm trying to remove link type highways from an osmnx graph

You can either do this with a `custom_filter` parameter, or generally how you're doing it by querying for more you need, then manually filtering it down. See the following for working example code, demonstrating various options:

  - https://github.com/gboeing/osmnx/issues/72#issuecomment-313579545
  - https://github.com/gboeing/osmnx/issues/151#issuecomment-379491607
  - https://stackoverflow.com/a/58594752
