### ISSUE TITLE
List street names in network maps

### ISSUE THREAD

**Issue by casemsee** [gboeing/osmnx#408]
I am looking for street information for the clean intersections that are produced by osmnx. 
I see that I can print lat/lon information, but is there a way to **include street/road names**  in network maps as well? I don't see how to do this in the documentation. Thanks!

```
import osmnx as ox
G = ox.graph_from_bbox(37.79, 37.78, -122.41, -122.43, network_type='drive')
G_projected = ox.project_graph(G)
ox.plot_graph(G_projected)
```
@gboeing 

![image](https://user-images.githubusercontent.com/18253918/77755503-89032c00-7081-11ea-8b24-2f9580743f63.png)

**Comment by gboeing** [comment]
Yes you can, but it's not built-in as an OSMnx parameter you can just switch on. Per the new issue template and contributing guidelines, this issue tracker is for reporting bugs in OSMnx. Please ask "how-to" questions on https://stackoverflow.com/ instead.

**Comment by gboeing** [comment]
For reference, here's the link to this question on stackoverflow: https://stackoverflow.com/questions/60886350/street-names-in-osmnx-network-maps

**Comment by gboeing** [comment]
FWIW the reason it's not just built into OSMnx is because

> Automatic text placement is one of the most difficult, complex, and time-consuming problems in mapmaking and GIS

https://en.wikipedia.org/wiki/Automatic_label_placement
