### ISSUE TITLE
Saving graphs to GeoPackages or PostgreSQL (PostGIS) tables?

### ISSUE THREAD

**Issue by swiss-knight** [gboeing/osmnx#411]
hello,

I wonder if it would be possible to export a graph (within the `save_load` module e.g.) directly as:

- two GeoPackages (nodes/edges)
- two PostGIS tables (nodes/edges)

The ESRI Shapefile has some limitations (e.g. field names get truncated to 10 char).

I would suggest to wait for GeoPandas 0.8 to be out for a direct export to PostGIS as it's already [on the track](https://github.com/geopandas/geopandas/pull/822).

Thanks.

**Comment by gboeing** [comment]
I had originally planned on adding functionality to export to GeoJSON, but at this point I think GeoPackage is the right open source standard to export to. As it stands, you can currently save as gpkg easily with OSMnx:

```python
import osmnx as ox
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive', simplify=False)
nodes, edges = ox.graph_to_gdfs(G)
nodes.to_file('nodes.gpkg', driver='GPKG')
edges.to_file('edges.gpkg', driver='GPKG')
```

However, this will not work simply and elegantly with a simplified graph, as you cannot serialize list-like values as gpkg with Fiona.

**Comment by gboeing** [comment]
proposed enhancement in #413
