### ISSUE TITLE
Error geometry

### ISSUE THREAD

**Issue by adrianelizalde** [gboeing/osmnx#416]
Hi, I am trying to retrieve hotels and supermarkets and subways stops. I have tried several things but allways errors:

```
supermarkets = ox.pois_from_place(barceloneta, amenities=['supermarket'])
buildings = ox.footprints_from_place(barceloneta, tourism=['hotel'])
```
KeyError: 'geometry'

**Comment by gboeing** [comment]
Hi @adrianelizalde, you didn't provide a reproducible example or the full error traceback, so I'm unable to diagnose this for you. However, please note from [the documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html):

> The query must be geocodable and OSM must have polygon boundaries for the geocode result. If OSM does not have a polygon for this place, you can instead get its street network using the graph_from_address function, which geocodes the place name to a point and gets the network within some distance of that point. Alternatively, you might try to vary the which_result parameter to use a different geocode result. For example, the first geocode result (ie, the default) might resolve to a point geometry, but the second geocode result for this query might resolve to a polygon, in which case you can use graph_from_place with which_result=2.

See also #268

**Comment by adrianelizalde** [comment]
Hi, I paste the error. If I have to guess I think the error comes because my code is not correct.
Show two examples, **first case** I want to retrieve all the hotels in the area:
```
hotel = ox.footprints_from_place(my_place, tourism=['hotel'])
```
error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-401b171a9712> in <module>
      1 # Retrieve restaurants
----> 2 buildings = ox.footprints_from_place(barceloneta, tourism=['hotel'])
      3 #hotel = ox.pois_from_place(barceloneta, tourism=['hotel'])
      4 
      5 # How many bars do we have?

TypeError: footprints_from_place() got an unexpected keyword argument 'tourism'
---------------------------------------------------------------------------

**Second case**
```
supermarkets = ox.pois_from_place(my_place, amenities=['grocery'])
```
error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/anaconda3/envs/ox/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'geometry'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-5-ceba6f44e83d> in <module>
      1 # Retrieve restaurants
----> 2 supermarkets = ox.pois_from_place(barceloneta, amenities=['grocery'])
      3 
      4 # How many restaurants do we have?
      5 len(supermarkets)

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/osmnx/pois.py in pois_from_place(place, amenities, which_result)
    459     city = gdf_from_place(place, which_result=which_result)
    460     polygon = city['geometry'].iloc[0]
--> 461     return create_poi_gdf(polygon=polygon, amenities=amenities)

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/osmnx/pois.py in create_poi_gdf(polygon, amenities, north, south, east, west)
    361 
    362     if polygon:
--> 363         gdf = gdf.loc[gdf['geometry'].centroid.within(polygon)==True]
    364 
    365     return gdf

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/geopandas/geodataframe.py in __getitem__(self, key)
    574         GeoDataFrame.
    575         """
--> 576         result = super(GeoDataFrame, self).__getitem__(key)
    577         geo_col = self._geometry_column_name
    578         if isinstance(key, str) and key == geo_col:

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2798             if self.columns.nlevels > 1:
   2799                 return self._getitem_multilevel(key)
-> 2800             indexer = self.columns.get_loc(key)
   2801             if is_integer(indexer):
   2802                 indexer = [indexer]

/opt/anaconda3/envs/ox/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2646                 return self._engine.get_loc(key)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2650         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'geometry'

**Comment by adrianelizalde** [comment]
> Hi @adrianelizalde, you didn't provide a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) or the full error traceback, so I'm unable to diagnose this for you. However, please note from [the documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html):
> 
> > The query must be geocodable and OSM must have polygon boundaries for the geocode result. If OSM does not have a polygon for this place, you can instead get its street network using the graph_from_address function, which geocodes the place name to a point and gets the network within some distance of that point. Alternatively, you might try to vary the which_result parameter to use a different geocode result. For example, the first geocode result (ie, the default) might resolve to a point geometry, but the second geocode result for this query might resolve to a polygon, in which case you can use graph_from_place with which_result=2.
> 
> See also #268

How can you pull the hotels and supermarkets of an area?

**Comment by gboeing** [comment]
This is demonstrated in the OSMnx examples. For how-to questions, please ask on StackOverflow to reserve the issue tracker for bug reporting per the contributing guidelines.
