### ISSUE TITLE
truncate_by_edge not implemented in truncate_graph_polygon

### ISSUE THREAD

**Issue by KAI10** [gboeing/osmnx#417]
Hi, I found that `truncate_by_edge` is not implemented for the method [truncate_graph_polygon](https://github.com/gboeing/osmnx/blob/998a764141d89b1adcd5456cc04a31c99a3a705b/osmnx/core.py#L703). I have implemented this part, would like to open a Pull Request.

**Comment by gboeing** [comment]
@KAI10 that'd be great. Thanks.

**Comment by gboeing** [comment]
closed in #419
