### ISSUE TITLE
Next release (0.11.5?) date

### ISSUE THREAD

**Issue by pmartincalvo** [gboeing/osmnx#418]
Just a quick question: some of us are looking forward for some of the new features to be delivered in the next release. I simply wanted to ask if there's any planned date for the next release. Thanks.

**Comment by gboeing** [comment]
I keep hoping to get it wrapped up and released. My release schedule is usually tied to how busy I am during the semester, and this semester has been particularly crazy with covid-19 pushing class delivery suddenly online. I hope to have some time later today to work on the release.

**Comment by gboeing** [comment]
will be finalizing in #420

**Comment by gboeing** [comment]
@pmartincalvo v0.12 has now been released
