### ISSUE TITLE
Find the distance to the nearest edge on a MultiDiGraph using OSMNx

### ISSUE THREAD

**Issue by TheCronus-agario** [gboeing/osmnx#423]
I'm trying to find the distance in a MultiDiGraph from a given location to the closest edge and closest node. For example the specified location with latitude = 51.217220 and longitude = 4.418535. Firstly we compose a MultiDiGraph at that location with a radius of 350m. Here is the code:

```
import osmnx as ox
lat = 51.217220
lon = 4.418535
G = ox.graph_from_point((lat, lon), network_type='drive', distance=350, simplify=True)
```
The OSMNx package has 2 valuable functions for my project: get_nearest_edge() and get_nearest_node(). get_nearest_node() finds the nearest node and returns it's ID. It also has an built-in option to return the distance to this nearest node:

ox.get_nearest_node(G, (lat,lon), method='haversine', return_dist=True) 
get_nearest_edge finds the nearest edge and returns the ID's of the 2 nodes that define the edge (each edge consists of 2 nodes being connected). However there's is no built-in option to get the distance to this edge.

How can I calculate the distance from the given location to the nearest edge? I was thinking that this could be a new feature in OSMNx to be added.

**Comment by gboeing** [comment]
@TheCronus-agario thanks for this suggestion. I'm open to this as a proposed enhancement and it could work the same way that `get_nearest_node` can optionally return distance. Would you like to open a PR?

You can see how `get_nearest_node` does it [here](https://github.com/gboeing/osmnx/blob/3520b244b349cd45ec1ef1baea3d239795d595f3/osmnx/geo_utils.py#L204).

You'd want to implement similar for `get_nearest_edge` [here](https://github.com/gboeing/osmnx/blob/3520b244b349cd45ec1ef1baea3d239795d595f3/osmnx/geo_utils.py#L249).

**Comment by tomshaffner** [comment]
I've actually been looking at this as well recently, and my first impression is that doing this for edges isn't so simple as doing it for nodes. First, the units in the `get_nearest_edge` function are unclear to me, they seem to be [unitless](https://github.com/Toblerity/Shapely/blob/de4838e102dcfd54aadc8af03ed33def918334e6/shapely/geometry/base.py#L432)?

Second, if this change is to be made it would seem to make more sense to include it in the functions that process multiple edges as well, eg. `get_nearest_edges`, and to add it to `get_nearest_nodes` also. I've read conflicting reports however about whether kdtree and balltree keep the nearest node in the edge calculation or simply keep the distance.

If it is in fact the latter, I'm wondering if a separate function to calculate distance to the nearest point of an edge might be the needed approach? And the above functions could be given a flag that would call this function at the end if needed (with a note that this likely adds substantially to runtime). Obviously calculating it in the midst of the existing calculation would be meaningfully better, but it's unclear to me how best to do that.

This is just the result of a preliminary look though so quite possible I'm misunderstanding something at this point; thoughts or correction on the above?

**Comment by gboeing** [comment]
@tomshaffner @TheCronus-agario see #443 which adds an optional parameter to `get_nearest_edge` to return the distance.

> First, the units in the get_nearest_edge function are unclear to me, they seem to be unitless

That's strange. AFAIK shapely geometry `distance` returns the euclidean distance in the geometries' coordinates' units. Testing seems to confirm this.

> Second, if this change is to be made it would seem to make more sense to include it in the functions that process multiple edges as well

Possibly, but this would be much less trivial. For now, I'm inclined to use #443 to close this issue. But in the future I'm open to someone opening a PR to add similar functionality to `get_nearest_edges` and `get_nearest_nodes` if it proves feasible.
