### ISSUE TITLE
Docs github link is broken

### ISSUE THREAD

**Issue by JNatael** [gboeing/osmnx#425]
When one clicks "Edit on Github" in the docs it sends the browser to a github 404 page. The link appears to be broken.

**Comment by gboeing** [comment]
Where is this link specifically?

**Comment by gboeing** [comment]
It looks like the link is broken in the stable version (release) docs https://osmnx.readthedocs.io/en/stable/ but not in the latest version docs https://osmnx.readthedocs.io/en/latest/

see also https://github.com/readthedocs/readthedocs.org/issues/4671 and https://github.com/readthedocs/readthedocs.org/issues/3994 and https://github.com/readthedocs/readthedocs.org/issues/1637

And https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html

**Comment by gboeing** [comment]
I've opened an upstream issue at https://github.com/readthedocs/readthedocs.org/issues/6932

**Comment by gboeing** [comment]
@JNatael thanks for reporting. Closing this here as it's an upstream issue affecting other packages' stable docs hosted on readthedocs too. See link above.
