### ISSUE TITLE
KeyError on Geometry when using simplify=True

### ISSUE THREAD

**Issue by tnoulas** [gboeing/osmnx#427]
Hi, 

it looks like when I load a network setting simplify=False like this:

G = ox.graph_from_point(chicago_center, distance=25000, network_type='drive', simplify=False) #check simplify parameter

and subsequently try to read the geometry at the edge level 

 for u, v, data in G.edges(keys=False, data=True):
       print(data['geometry'].coords)

I'm getting a key error. The error disappears when I am setting simplify=True for some reason. Any ideas whether this is an expected behaviour? I was looking for a more detailed view of the networks geometry actually.

**Comment by gboeing** [comment]
@tnoulas the edges' `geometry` attribute is only created upon simplification. If the graph is not simplified, then the edge geometry is trivial (straight-line from `u` to `v`) so creating a discrete `geometry` attribute is redundant. If you need a `geometry` attribute in your unsimplified graph, you can create it with `shapely.geometry.LineString` and `networkx.set_edge_attributes`.

**Comment by tnoulas** [comment]
@gboeing thanks so much for your response. I see, so basically the 'simplify' method does not have to do anything with the 'resolution' of the street network geometry. For some reason I assumed that and I was hoping that if simplify is False, I would get a more granular view of the network. The fact that the resulting size of the downloaded network gave me a little more hope that this would be the case. For context, I am using the street network from osmxn to use for implementing a map matching algorithm (https://github.com/valhalla/valhalla/blob/master/docs/meili/algorithms.md). 

Anyway thanks so much, probably this issue should be closed then!

**Comment by gboeing** [comment]
You'll get far more nodes and edges with `simplify=False`, so in that sense it is more granular. Simplification takes that original unsimplified graph, retains nodes only at intersections/dead-ends, and stores the original true edge geometry as a multivertex LineString geometry attribute of the new simplified edge.

**Comment by gboeing** [comment]
See also: https://stackoverflow.com/a/64376567/7321942
