### ISSUE TITLE
plot_graph(): edge_colour ignores alpha if colour array is specified as RGBA

### ISSUE THREAD

**Issue by puntofisso** [gboeing/osmnx#428]
I use plot_graph to create street colouring maps this way: 
```
fig, ax = ox.plot_graph(G, bgcolor=background, axis_off=True, node_size=0, node_color='w', node_edgecolor='gray', node_zorder=2, edge_color=ec, filename = place, file_format='svg', edge_linewidth=1, edge_alpha=1, fig_height=50, dpi=1200, save=save)
```   
Where ```ec``` is thus built:

```
ec = [colourcode(str(row['name']).lower()) for index, row in edge_attributes.iterrows()]
```

My colourcode function simply takes the name and assigns colour hex codes based on road suffix (e.g. "road" is red, etc). For example, for a German-language map I do:

```
def colourcode(x):
        if ('straße' in x): 
            return '#f6cf71'
        elif ('weg' in x):
            return '#019868'
        elif ('allee' in x):
            return '#ec0b88'
        else:
            return '#c6c6c6'
```

If instead of a RGB code I pass a RGBA code (as @gboeing suggests in [#239], the alpha channel seems to be ignored. For example, I get a black line whether I do
```            return '#c6c6c6FF'```
or
```            return '#c6c6c600'```

This happens on a Jupyter notebook (6.0.2) run through anaconda on mac os, with matplotlib==3.1.1 and osmnx==0.11

Am I doing something wrong, is this a matplotlib issue, or is there a genuine problem with plot_graph?

**Comment by gboeing** [comment]
Did you try setting `edge_alpha=None` when calling `ox.plot_graph` and passing in your RGBA colors? I see in your code snippet here that `edge_alpha=1` instead. Per [this comment](https://github.com/gboeing/osmnx/issues/239#issuecomment-451196522):

> I was able to achieve my goal by passing the RGBA values to the edge_color and setting the edge_alpha=None

**Comment by puntofisso** [comment]
D'oh. It hadn't occurred to me it was impacting on this. Thanks!

**Comment by gboeing** [comment]
I've made the docstring clearer for future reference on the alpha channel in #429
