### ISSUE TITLE
More informative error message with graph_from_file data import

### ISSUE THREAD

**Issue by anisotropi4** [gboeing/osmnx#436]
#### Importing using `graph_from_file` where edge data contains missing node raises a key error 

As reported by @bradleyswilson in #323 KeyError: 'y' when poorly clipped OSM data (where edges are present without corresponding nodes) is imported using `graph_from_file` this raises a `KeyError 'y'` exception in the `add_edge_lengths`. 

#### Fails with a `KeyError: 'y'` when `G.nodes[{u,v}]` does not exist but the edge `u, v, k` does:
```python
coords = np.array([[u, v, k, G.nodes[u]['y'], G.nodes[u]['x'], G.nodes[v]['y'], G.nodes[v]['x']] for u, v, k in G.edges(keys=True)])
```
The proposed fix places this in a`try/except KeyError`block, identifies the missing node(s) referenced by edges and executes a `raise TypeError` with a more informative error message:

#### Handles the `KeyError` and raises more informative clipping error `TypeError` detailing missing nodes
```python
    try:
        coords = np.array([[u, v, k, G.nodes[u]['y'], G.nodes[u]['x'], G.nodes[v]['y'], G.nodes[v]['x']] for u, v, k in G.edges(keys=True)])
    except KeyError:
        missing_nodes = {str(i) for u, v, _ in G.edges(keys=True) if not(G.nodes[u] or G.nodes[u]) for i in (u, v) if not G.nodes[i]}
        raise TypeError('Edge missing nodes {} likely due to a clipping issue'.format(','.join(missing_nodes)))
```

**Comment by gboeing** [comment]
@anisotropi4 thanks. I'm going to move your comment to the PR (#437) where we can discuss, and close this issue as it duplicates #323.
