### ISSUE TITLE
key values are not saved to shapefile/graphml

### ISSUE THREAD

**Issue by giohappy** [gboeing/osmnx#44]
After saving the graph to shapefile or graphml the "key" field is set to 0 for every element.

**Comment by gboeing** [comment]
Can you provide a minimal working example and your package/python version info? The `key` *should* be 0 for every edge except for parallel edges, which are rare. And there should be no `key` attribute for nodes. So if your graph has no parallel edges, you should see a 0 for every `key` attribute value.

From the networkx [docs](https://networkx.readthedocs.io/en/stable/reference/introduction.html):

> For MultiGraph/MultiDiGraph we use a dict-of-dicts-of-dicts-of-dicts where the third dictionary is keyed by an edge key identifier to the fourth dictionary which contains the edge attributes for that edge between the two nodes.

**Comment by giohappy** [comment]
Thanks @gboeing, I misunderstood the key field.

**Comment by tauhlim** [comment]
Hi @gboeing,

First wanted to thank you for creating this package - it's been extremely helpful for analysis!

Just wanted to point out that this issue actually prevents Gephi from correctly reading the saved graphML properly, as it's unable to detect different edges due to the duplicate id.

**Simple code example:**
```
G = ox.graph_from_place('Berkeley, California', network_type = "drive")
ox.save_load.save_graphml(G, filename="berkeley.graphml", folder=None)
```

**Resulting edges in graphML (excerpt, truncated for conciseness)**
```
<edge id="0" source="53030508" target="53030507">
</edge>
<edge id="0" source="53030510" target="53033490">
</edge>
<edge id="0" source="53030510" target="53030514">
</edge>
```

**When trying to open the graphML file in Gephi:**
![image](https://user-images.githubusercontent.com/7834189/40105672-3f877276-5926-11e8-9717-3c1a2f5040ed.png)

**Comment by tauhlim** [comment]
Thanks @gboeing 

As a quick workaround using `osmnx`, in case anyone is interested in exporting the graphs to work in Gephi:

Using some osmnx graph G:
```
G = ox.graph_from_point(center_point=[37.870288, -122.259479], distance=500, network_type="bike")
```

Split the graph into nodes and edges gdf:
```
G_nodes = ox.graph_to_gdfs(G, nodes = True, edges = False)
G_edges = ox.graph_to_gdfs(G, nodes = False, edges = True)
```

Re-assign key values so each edge gets a unique key:
```
G_edges.key = range(G_edges.shape[0])
```

Convert the gdf's back into a graph, and save it as graphml:
```
H = ox.gdfs_to_graph(gdf_edges=G_edges, gdf_nodes=G_nodes) # WORKAROUND WORKS!!
ox.save_load.save_graphml(H, filename="singapore.graphml", folder=None) 
```

Resulting graph can be opened in Gephi:
![campusbikepaths_gephi](https://user-images.githubusercontent.com/7834189/40171009-b09c81f0-59fc-11e8-8fd5-39d82b786d35.png)

**Comment by gboeing** [comment]
@tauhlim Gephi-compatible graphml saving is now added as a workaround in b5f30c203f504354a25597f70900a713a9f1bc0a including preserving node coordinates so you can run Gephi's GeoLayout.
