### ISSUE TITLE
Can't select Continental Portugal

### ISSUE THREAD

**Issue by Dpm99** [gboeing/osmnx#441]
Good Afternoon,

Firstly I would like to say that this project is amazing and has been extremely helpful, therefore thank you very much for creating it.

The issue I am having is the following: Portugal is a country next to Spain and it also has some islands. I want to select only Continental Portugal, what I mean by this is just the part of Portugal next to Spain and not include the islands.

Can you help me please?

Thank you for the attention.

**Comment by gboeing** [comment]
Per the new issue template and the contributing guidelines: this issue tracker is for reporting bugs or proposing new features. Please ask "how-to" usage questions on https://stackoverflow.com/ instead.
