### ISSUE TITLE
How do i get the bounding boxes of all my buildings in a city?

### ISSUE THREAD

**Issue by Hsengiv2000** [gboeing/osmnx#444]
if i perform a buildings = ox.footprints_from_place(myplace), i get the buildings and I can plot them. however how do i get the bounding box of each building? One strategy I thought of is to iterate through all the nodes of a building and then collect their latitudes and longitudes. However I get a key error when i perform graph.nodes[nodeidfrombuilding]?
Kindly get back to me on this.
Thank you so much

**Comment by gboeing** [comment]
Per the new issue template and the contributing guidelines: this issue tracker is for reporting bugs or proposing new features. Please ask "how-to" usage questions on https://stackoverflow.com/ instead.
