### ISSUE TITLE
Timeout Error from footprints_from_place

### ISSUE THREAD

**Issue by mgaury** [gboeing/osmnx#445]
Hi,

First of all, thank you for this project which appears really helpful.

I have encountered a timeout error when I want to retrieve buildings plan from a place given : 
ReadTimeout: HTTPConnectionPool(host='overpass-api.de', port=80): Read timed out. (read timeout=180)

my code is :

cs = '[out:json][timeout:600]'
buildings2 = ox.footprints_from_place(ville, footprint_type='building', retain_invalid=False, which_result=1, custom_settings=cs)

Are my settings wrong or is it just not possible to fix the timeout ?

Thank you for your answer.

**Comment by gboeing** [comment]
There are two different kinds of "timeout" that are relevant here.

  1. Overpass query timeout: this is what you are manually setting with your `custom_settings` argument
  2. HTTP connection timeout: OSMnx sets this to a default value of 180 seconds

The `graph_from_whatever` function currently expose a `timeout` parameter that is used to set both of the timeout values above. However, the pois and footprints modules do not currently expose this parameter, so all you can do is configure the query timeout through the `custom_settings` parameter. The connection timeout meanwhile remains 180.

This should probably be enhanced to expose the `timeout` parameter for pois and footprints to make query + connection timeouts behave the same as they do in the graph creation functions.

**Comment by gboeing** [comment]
@mgaury see #446 

It allows you to fully control the timeout using a new `timeout` parameter exposed throughout the footprints and pois modules. It does the same for the `memory` parameter.

**Comment by mgaury** [comment]
Thank you for your response and improvement. This will be really helpful in the future.

**Comment by gboeing** [comment]
Note that these params have been deprecated. They are now easily accessible via the ox.config() function and settings module instead. See #492.
