### ISSUE TITLE
Rtree and a missing libspatialindex_c library file

### ISSUE THREAD

**Issue by stevenbeeckman** [gboeing/osmnx#45]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

Importing osmnx on the Python REPL indicates a missing libspatialindex_c library file.

#### What operating system, architecture, Python version, and OSMnx version are you using?

Mac OS X 10.10.5 Yosemite, Python 2.7.12. osmnx 0.4.1

#### Code that reproduces the issue

```python
>> import osmnx as ox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/osmnx/__init__.py", line 8, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/site-packages/osmnx/core.py", line 20, in <module>
    import geopandas as gpd
  File "/usr/local/lib/python2.7/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/usr/local/lib/python2.7/site-packages/geopandas/geoseries.py", line 16, in <module>
    from geopandas.base import GeoPandasBase
  File "/usr/local/lib/python2.7/site-packages/geopandas/base.py", line 15, in <module>
    from rtree.core import RTreeError
  File "/usr/local/lib/python2.7/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/usr/local/lib/python2.7/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/usr/local/lib/python2.7/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file
```
The solution was described in [this blogpost](http://jspeis.com/installing-rtree-on-mac-os-x/): `brew install spatialindex`. 

This issue may be closed as I created this issue purely for documentation purposes.

**Comment by gboeing** [comment]
Thanks.

[libspatialindex](https://libspatialindex.github.io/) is also listed as a dependency of the rtree package in its installation [instructions](http://toblerity.org/rtree/install.html). You can also install everything for OSMnx in one fell swoop with [conda](https://anaconda.org/conda-forge/osmnx).

**Comment by solomonvimal** [comment]
Installing OSMnx solved this issue for me! Thanks @gboeing!

**Comment by 1papaya** [comment]
On Ubuntu 18.04 it worked to install rtree from apt instead of pip, as follows:
`sudo apt install python3-rtree`

**Comment by hanleybrand** [comment]
On MacOS you can `brew install spatialindex` to fix this problem

**Comment by huesmiles49** [comment]
@hanleybrand thank you! installing spatialindex fixed the problem

**Comment by anderl80** [comment]
Unfortunately I have the same issue when using a Google Colab env. I can only use pip install osmnx and so libspatialindex is missing.

**Comment by ratnanil** [comment]
> Unfortunately I have the same issue when using a Google Colab env. I can only use pip install osmnx and so libspatialindex is missing.

Same here when using https://mybinder.org

**Comment by AtelierLibre** [comment]
I'm not familiar with mybinder.org but, incase it's helpful, with Colab using apt instead of pip to install rtree will bring the c library with it:

```
# apt to install c libraries as well
!apt install python3-rtree
```

**Comment by ratnanil** [comment]
@AtelierLibre: Thank you for the tipp! I was just able to use apt in mybinder with [these instructions](https://mybinder.readthedocs.io/en/latest/sample_repos.html#installing-packages-from-apt-repositories): Add a file named `apt.txt` to the repo containing just a single line: 

    libspatialindex-dev

**Comment by AtelierLibre** [comment]
That's great, glad it was helpful!

**Comment by EwoutH** [comment]
> sudo apt install python3-rtree

Unfortunatly this breaks on Ubuntu 20.04 and 22.04. Does anyone have a solution?

**Comment by gboeing** [comment]
OSMnx only officially supports [installation](https://osmnx.readthedocs.io/en/stable/#installation) via conda, as its dependencies can otherwise be themselves a bit complex to install. If you need to install via pip, you can, but you may need to follow the dependencies' maintainers' installation instructions if you run into any snags. For rtree (non-conda) installation problems, you should follow their [instructions](https://rtree.readthedocs.io/en/latest/install.html) or inquire at their repo/forum if you hit any bugs.
