### ISSUE TITLE
Retrieve metadata (user, version, timestamp etc.) along OSM data

### ISSUE THREAD

**Issue by kadirm** [gboeing/osmnx#452]
Hi,

Since this OSMnx is a handy tool to gather information from OSM and use it with geopandas directly, it would be nice to have also metadata (user, version, timestamp, etc.) of the OSM data. It can be queried over the overpass API and perhaps can be integrated into OSMnx.

Thanks,

**Comment by gboeing** [comment]
I'm not sure. Do you have some sample code to demonstrate how querying this metadata would work?  It may require some substantial reworking of OSMnx's Overpass querying.

**Comment by kadirm** [comment]
I'm not an expert but I'll try to explain.

https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#out

In the wiki, it says the default degree of verbosity of the output is _body_. In default, there isn't metadata. When you pass the _meta_ parameter after _out_ statement it gives you metadata of the data. İt is also possible to pass meta with geom parameter. 

```
way({{bbox}});
out geom meta;
```

I hope it helps.

**Comment by gboeing** [comment]
It would probably require a lot of code changes for a potentially edge-case function. But I'll leave this open for now in case anyone else interested wants to weigh in or contribute sample code.

**Comment by gboeing** [comment]
Closing for now due to lack of activity. Can be reopened for discussion in the future as needed.
