### ISSUE TITLE
Getting nodes form ox.get_nearest_node() is giving wrong results

### ISSUE THREAD

**Issue by Dpm99** [gboeing/osmnx#456]
Hello,

I have a big issue when getting a node from geographical coordinates. When I use ox.get_nearest_node(), the node I get is way too far from the coordinates and I don't know why:

```
import networkx as nx
import matplotlib.pyplot as plt
import osmnx as ox
import geopandas as gpd
ox.config(log_console=True, use_cache=True)


place = 'Portugal, Lisbon'
G = ox.graph_from_place(place, network_type='drive')
G = ox.project_graph(G)
hospitals = ox.pois_from_place(place, amenities=['hospital'])

coord_1 = (38.69950, -9.18767)  
target_1 = ox.get_nearest_node(G, coord_1)
print(target_1)

nc = ['r' if node==target_1 else 'gray' for node in G.nodes()]
ns = [50 if node==target_1 else 1 for node in G.nodes()]
fig, ax = ox.plot_graph(G, node_size=ns, node_color=nc, node_zorder=2)
```
From this I get the following node: 4751061000

The plot is:
![image](https://user-images.githubusercontent.com/64794323/82101278-05220380-9704-11ea-9104-47555cc920e3.png)

And the hospital should be near the sea:

![image](https://user-images.githubusercontent.com/64794323/82101320-24209580-9704-11ea-9974-c06ae2d212da.png)

I also tested for another set of coordinates and it gave me the exact same node which is very strange.

Thank you in advance for the help

**Comment by gboeing** [comment]
OSMnx is working correctly. You are searching for the nearest node in a graph with projected coordinates to a pair of unprojected coordinates. This is a usage question rather than a bug report, so please ask on StackOverflow.
