### ISSUE TITLE
Type Error with truncate_graph_polygon function

### ISSUE THREAD

**Issue by kelanstoy** [gboeing/osmnx#46]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
My overall goal was to be able to calculate intersection density for several geometries that fall within a network, without having to make a separate API call to pull down a new network from OSM each time.

The general use case is to get network statistics (like intersection density) for geographies such as census blocks.

I found the `truncate_graph_polygon` function in the code base after a bit of digging. At first glance, it seemed like it would work well with my use case. I could iterate through census block geometries, call `truncate_graph_polygon` with the census block polygon as a parameter, get the stats for the census block, and then continue on to the next block. 

However, the `truncate_graph_polygon` function produces an error, stemming from the `intersect_index_quadrats` function within it. It appears that iteration fails when the `quadrat_cut_geometry` function returns a Polygon, rather than a MultiPolygon. The link below shows where this error occurs in the codebase:

https://github.com/gboeing/osmnx/blob/b25bcabf3ffa2b41ae0ab4c0bac21a3be76c7839/osmnx/core.py#L921

Below is an example that illustrates how this function fails, using city boundaries in Merced County, CA.

#### What operating system, architecture, Python version, and OSMnx version are you using?

- Windows
- Python 3.5
- OSMnx 0.4.1

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>

_license                  1.1                      py35_1
alabaster                 0.7.6                    py35_0
anaconda                  2.4.1               np110py35_0
anaconda-client           1.2.1                    py35_0
appdirs                   1.4.3                     <pip>
argcomplete               1.0.0                    py35_1
astropy                   1.0.6               np110py35_0
babel                     2.1.1                    py35_0
beautifulsoup4            4.4.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze-core                0.8.3                    py35_0
bokeh                     0.10.0                   py35_0
boto                      2.38.0                   py35_0
bottleneck                1.0.0               np110py35_0
branca                    0.2.0                    py35_0    conda-forge
bzip2                     1.0.6                    vc14_2  [vc14]
cffi                      1.9.1                    py35_0
click                     6.7                      py35_0    conda-forge
click-plugins             1.0.3                    py35_0    conda-forge
cligj                     0.4.0                    py35_0    conda-forge
clyent                    1.2.0                    py35_0
colorama                  0.3.3                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.3.16                   py35_0
conda-build               1.18.2                   py35_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
cryptography              1.7.1                    py35_0
curl                      7.45.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cycler                    0.10.0                    <pip>
cython                    0.23.4                   py35_0
cytoolz                   0.7.4                    py35_0
datashape                 0.4.7               np110py35_1
decorator                 4.0.11                    <pip>
decorator                 4.0.6                    py35_0
descartes                 1.1.0                    py35_0    conda-forge
docutils                  0.12                     py35_1
dynd-python               0.7.0                    py35_0
et_xmlfile                1.0.1                    py35_0
expat                     2.1.0                    vc14_2  [vc14]  conda-forge
fastcache                 1.0.2                    py35_0
fiona                     1.7.1               np110py35_1    conda-forge
flask                     0.10.1                   py35_1
folium                    0.3.0                    py35_0    conda-forge
freetype                  2.6.3                    vc14_1  [vc14]  conda-forge
freexl                    1.0.2                    vc14_1  [vc14]  conda-forge
gdal                      2.1.2           np110py35_vc14_6  [vc14]  conda-forge
geopandas                 0.2.1                    py35_3    conda-forge
geopy                     1.11.0                   py35_0    conda-forge
geos                      3.5.1                    vc14_1  [vc14]  conda-forge
greenlet                  0.4.9                    py35_0
h5py                      2.5.0               np110py35_4
hdf4                      4.2.12                   vc14_0  [vc14]  conda-forge
hdf5                      1.8.17                   vc14_9  [vc14]  conda-forge
icu                       57.1                     vc14_0  [vc14]
idna                      2.0                      py35_0
ipykernel                 4.2.2                    py35_0
ipython                   4.0.3                    py35_0
ipython-genutils          0.2.0                     <pip>
ipython-notebook          4.0.4                    py35_3
ipython-qtconsole         4.0.1                    py35_4
ipython_genutils          0.1.0                    py35_0
ipywidgets                4.1.1                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_0
Jinja2                    2.9.6                     <pip>
jinja2                    2.8                      py35_0
jpeg                      9b                       vc14_0  [vc14]  conda-forge
jsonschema                2.4.0                    py35_0
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                    py35_1
jupyter-client            5.0.1                     <pip>
jupyter-core              4.3.0                     <pip>
jupyter_client            4.1.1                    py35_0
jupyter_console           4.1.0                    py35_0
jupyter_core              4.0.6                    py35_0
kealib                    1.4.6                    vc14_3  [vc14]  conda-forge
launcher                  1.0.0                         4
libdynd                   0.7.0                         0
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libnetcdf                 4.4.1.1                  vc14_2  [vc14]  conda-forge
libpng                    1.6.28                   vc14_0  [vc14]  conda-forge
libpq                     9.5.4                    vc14_3  [vc14]  conda-forge
libsodium                 1.0.3                         0
libspatialindex           1.8.5                    vc14_1  [vc14]  conda-forge
libspatialite             4.3.0a                  vc14_14  [vc14]  conda-forge
libtiff                   4.0.6                    vc14_7  [vc14]  conda-forge
libxml2                   2.9.4                    vc14_4  [vc14]  conda-forge
llvmlite                  0.8.0                    py35_0
lxml                      3.4.4                    py35_0
markupsafe                0.23                     py35_0
MarkupSafe                1.0                       <pip>
matplotlib                2.0.0               np112py35_0
matplotlib                1.5.1                     <pip>
menuinst                  1.4.1                    py35_0
mistune                   0.7.1                    py35_0
mkl                       2017.0.1                      0
msvc_runtime              1.0.1                    vc14_0  [vc14]
multipledispatch          0.4.8                    py35_0
munch                     2.1.1                    py35_0    conda-forge
nbconvert                 4.1.0                    py35_0
nbformat                  4.3.0                     <pip>
nbformat                  4.0.1                    py35_0
networkx                  1.10                     py35_0
nltk                      3.1                      py35_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py35_0
notebook                  4.4.1                    py35_0
numba                     0.22.1              np110py35_0
numexpr                   2.6.2               np112py35_0
numpy                     1.12.1                   py35_0
numpy                     1.11.0                    <pip>
odo                       0.3.4                    py35_0
openjpeg                  2.1.2                    vc14_1  [vc14]  conda-forge
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2e                   vc14_1  [vc14]
osmnx                     0.4.1                    py35_0    conda-forge
packaging                 16.8                      <pip>
pandas                    0.18.1                    <pip>
pandas                    0.19.2              np110py35_1    conda-forge
pandocfilters             1.4.1                     <pip>
path.py                   8.1.2                    py35_1
patsy                     0.4.0               np110py35_0
pcre                      8.39                     vc14_0  [vc14]  conda-forge
pep8                      1.6.2                    py35_0
pickleshare               0.5                      py35_0
pillow                    3.0.0                    py35_1
pip                       9.0.1                     <pip>
pip                       8.1.2                    py35_0
pip                       8.1.2                     <pip>
plotly                    1.9.5                     <pip>
ply                       3.8                      py35_0
proj4                     4.9.3                    vc14_3  [vc14]  conda-forge
psutil                    3.3.0                    py35_0
psycopg2                  2.6.1                     <pip>
psycopg2                  2.6.2                    py35_1    conda-forge
py                        1.4.30                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_0
pycrypto                  2.6.1                    py35_3
pycurl                    7.19.5.1                 py35_1
pyflakes                  1.0.0                    py35_0
pygments                  2.0.2                    py35_0
pyopenssl                 16.2.0                   py35_0
pyparsing                 2.0.3                    py35_0
pyparsing                 2.2.0                     <pip>
pyproj                    1.9.5.1                  py35_0    conda-forge
pyqt                      5.6.0                    py35_2
pyreadline                2.1                      py35_0
pysal                     1.13.0                   py35_0    conda-forge
pytables                  3.2.2               np110py35_1
pytest                    2.8.1                    py35_0
python                    3.5.2                         0
python-dateutil           2.6.0                     <pip>
python-dateutil           2.4.2                    py35_0
pytz                      2015.7                   py35_0
pytz                      2016.4                    <pip>
pywin32                   219                      py35_1
pyyaml                    3.11                     py35_4
pyzmq                     15.2.0                   py35_0
pyzmq                     16.0.2                    <pip>
qt                        5.6.2                    vc14_3  [vc14]
qtconsole                 4.1.1                    py35_0
requests                  2.10.0                    <pip>
requests                  2.13.0                   py35_0
rope                      0.9.4                    py35_1
rtree                     0.8.3                    py35_0    conda-forge
ruamel_yaml               0.11.14                  py35_0
scikit-image              0.11.3              np110py35_0
scikit-learn              0.18.1              np112py35_1
scipy                     0.19.0              np112py35_0
setuptools                26.1.1                   py35_0
shapely                   1.5.17              np110py35_2    conda-forge
simplegeneric             0.8.1                    py35_0
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snowballstemmer           1.2.0                    py35_0
sockjs-tornado            1.0.1                    py35_0
sphinx                    1.3.1                    py35_0
sphinx_rtd_theme          0.1.7                    py35_0
spyder                    2.3.8                    py35_0
spyder-app                2.3.8                    py35_0
sqlalchemy                1.0.9                    py35_0
sqlite                    3.13.0                   vc14_0  [vc14]  conda-forge
statsmodels               0.6.1               np110py35_0
sympy                     0.7.6.1                  py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.7.4                    py35_0
tornado                   4.4.3                     <pip>
tornado                   4.4.2                    py35_0
traitlets                 4.3.2                     <pip>
traitlets                 4.1.0                    py35_0
ujson                     1.33                     py35_0
unicodecsv                0.14.1                   py35_0
vc                        14                            0    conda-forge
vincent                   0.4.4                    py35_0    conda-forge
vs2015_runtime            14.0.25123                    0
werkzeug                  0.11.2                   py35_0
wheel                     0.29.0                   py35_0
xerces-c                  3.1.4                    vc14_2  [vc14]  conda-forge
xlrd                      0.9.4                    py35_0
xlsxwriter                0.7.7                    py35_0
xlwings                   0.5.0                    py35_0
xlwt                      1.0.0                    py35_0
zeromq                    4.1.3                    vc14_1  [vc14]
zlib                      1.2.8                    vc14_2  [vc14]
</details>

#### Code that reproduces the issue

```python
import osmnx as ox
# Import Merced County network from OSM
G = ox.graph_from_place('Merced County, California, USA', network_type='drive_service')
G = ox.project_graph(G)

# Import boundary for some cities in Merced County from OSM
place_names = ['Merced, California, USA', 
               'Atwater, California, USA',
               'Livingston, California, USA']
merced_cities = ox.gdf_from_places(place_names)
merced_cities = ox.project_gdf(merced_cities)

# get polygon for city of Merced
merced_polygon = merced_cities['geometry'].iloc[0]

# Truncate graph to the polygon shape
g_sample = ox.truncate_graph_polygon(G, merced_polygon, retain_all=False, truncate_by_edge=False)

# This produces the following error: TypeError: 'Polygon' object is not iterable
```

**Comment by gboeing** [comment]
`truncate_graph_polygon` is an under-the-hood function that I ended up exposing. It uses `intersect_index_quadrats` but doesn't expose some of its arguments. Thus, it works fine when you're using lat-long geometries, but chokes on projected geometries. The fix is to expose those arguments, which I just did in ba1d1b3. Thus your code should work in the latest GitHub version of OSMnx. Here's a small working example:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
G = ox.project_graph(G)
gdf = ox.gdf_from_place('Piedmont, CA, USA')
poly = gdf['geometry'].iloc[0]
poly, crs = ox.project_geometry(poly)
poly = poly.buffer(-500)
G_truncated = ox.truncate_graph_polygon(G, poly, retain_all=False, truncate_by_edge=False, 
                                        quadrat_width=1000, buffer_amount=0.01)
fig, ax = ox.plot_graph(G_truncated)
```

In the meantime (pending these commits getting packaged and released), you can still make this work using OSMnx versions < 5.0. The trick is to work in all lat-long, and only project at the end:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
G = ox.graph_from_place('Merced County, California, USA', network_type='drive_service')
place_names = ['Merced, California, USA', 
               'Atwater, California, USA',
               'Livingston, California, USA']
merced_cities = ox.gdf_from_places(place_names)
merced_polygon = merced_cities['geometry'].iloc[0]
g_sample = ox.truncate_graph_polygon(G, merced_polygon, retain_all=False, truncate_by_edge=False)
g_sample_projected = ox.project_graph(g_sample)
fig, ax = ox.plot_graph(g_sample_projected)
```

**Comment by kuanb** [comment]
Just wanted to chime in and ask a short follow up question/s.

So `osmnx.project_gdf()`'s functionality is to: "Project a GeoDataFrame to the UTM zone appropriate for its geometries' centroid."

Is the purpose of this step purely for rendering purposes? That is, is the intent to prepare the geometries to be rendered in a manner that is less distorted?

In @kelanstoy's example, there is no advantage in that process to re-projecting the data at that step, right? One could simply work in web mercator/latlng until one is ready to plot the results and then use the `project_gdf` function. Otherwise, one would be fine leaving it "as is" during their analysis.

**Comment by gboeing** [comment]
There are various reasons to project spatial data from an (approximately) spheroidal coordinate system like lat-long to a planar coordinate system like UTM. Like you mentioned, you might want to display it in two dimensions, such as on a sheet of paper or on a computer screen. Or you might want to have your geometries in units that are more meaningful than degrees -- typically meters.
