### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by martinfleis** [gboeing/osmnx#480]
Hi,

I just had a couple of issue using my code with the new release and figured out that version 0.13 is not backward compatible with some of the code written for 0.12. Since there was no deprecation warning, I assume it is not intentional?

- Any function downloading the data `...from_points` has `distance` attribute in 0.12.1 but `dist` in 0.13.
- `ox.project_gdf` has to be imported as `ox.projection.project_gdf`
- and some issues related to the refactoring of the core modules, if you import functions from the module itself (like `ox.save_load.graph_to_gdfs` -> `ox.utils_graph.graph_to_gdfs`), which is what documentation actually seems to suggest.

**Comment by gboeing** [comment]
Yeah, I released a couple function parameter changes and refactored a couple functions' access out of the `osmnx.` namespace and into their own modules... not best practice but I was pressed for time to finish the release. I'm hoping it will be a one-time non-backwards-compatible release. Details: https://github.com/gboeing/osmnx/blob/master/CHANGELOG.md#0130-2020-05-25
