### ISSUE TITLE
Check if there are data before accessing

### ISSUE THREAD

**Issue by brenobeirigo** [gboeing/osmnx#484]
In the function `node_list_to_coordinate_lines(G, node_list, use_geom=True)` of file `plot.py` the following excerpt raises an error when there is no edge data (i.e., `G.get_edge_data(u, v)` is None):

`data = min(G.get_edge_data(u, v).values(), key=lambda x: x['length'])
`

In my application, doing

```
 try:
     data = min(G.get_edge_data(u, v).values(), key=lambda x: x['length'])
 except:
     data = {}
```

solved the problem.

**Comment by gboeing** [comment]
Thanks. Can you provide a reproducible standalone code snippet to generate the error?

**Comment by gboeing** [comment]
For reference, this is regarding the internal `_node_list_to_coordinate_lines` function in the `plot` module: https://github.com/gboeing/osmnx/blob/14fb821be83ca60ecf9698cd465926f294a7bb1e/osmnx/plot.py#L515

The function takes an argument representing a list of node IDs in a route, per the [docstring](https://github.com/gboeing/osmnx/blob/14fb821be83ca60ecf9698cd465926f294a7bb1e/osmnx/plot.py#L500): "a valid graph path as a list of node IDs." If the node list is not a valid graph path, the function should throw an error.
