### ISSUE TITLE
module 'osmnx' has no attribute 'get_colors'

### ISSUE THREAD

**Issue by Waywiser** [gboeing/osmnx#485]
Hi,

Running into an issue with the isochrone module for osmnx. I receive the following error when setting the colors. I am using osmnx '0.13.0'
<img width="911" alt="Screen Shot 2020-06-03 at 10 07 18 AM" src="https://user-images.githubusercontent.com/65924806/83646847-344cc780-a582-11ea-8bf1-bf4840a90c4c.png">

**Comment by gboeing** [comment]
See https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.plot.get_colors

The correct syntax as of v0.13.0 is `ox.plot.get_colors()`

**Comment by gboeing** [comment]
see also https://github.com/gboeing/osmnx/issues/511#issuecomment-649669215
