### ISSUE TITLE
Retrieve graph closed edges as multipolygon

### ISSUE THREAD

**Issue by BCNecoder** [gboeing/osmnx#505]
Hi there,

I'm working on a project about available pedestrian urban space. I've realised that some areas in OSM are registered as closed linestrings instead of polygons.

for instance, I run the following snippet to retieve Bilbaos pedestrian areas:

```
G = ox.graph_from_place('Casco Viejo, Bilbao, Spain', network_type='walk', 
                        retain_all=True, buffer_dist = 50, which_result = 2,
                        infrastructure = 'relation["highway" = "pedestrian"]')
```
Which yields this graph:

`fig, ax = ox.plot_graph(G)`

![image](https://user-images.githubusercontent.com/47638539/84758146-5ce2b180-afc5-11ea-903f-e9e0e4713df3.png)

Is it possible to retrive this geometries directly as GeoDataframe made of multipolygon?
If not is it posible to improve thecode to get to it?

**Comment by gboeing** [comment]
Cross-post answered at: https://stackoverflow.com/questions/62405116/convert-closed-linestrings-from-osmnx-graph-into-multipolygon

Per the contributing guidelines, please ask "how-to" usage questions on StackOverflow as the issue tracker is for reporting bugs.
