### ISSUE TITLE
AttributeError: module 'osmnx' has no attribute 'quadrat_cut_geometry'

### ISSUE THREAD

**Issue by KeeratKG** [gboeing/osmnx#507]
Hi. 
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
I ran the following lines of code:
```
geometry_cut = ox.quadrat_cut_geometry(geometry, quadrat_width=750) #width in metres, to introduce gridlines
print(type(geometry_cut))
```
I expected the outcome:
`<class 'shapely.geometry.multipolygon.MultiPolygon'>`
But instead got the error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-e7cf74efad96> in <module>
----> 1 geometry_cut = ox.quadrat_cut_geometry(geometry, quadrat_width=750) #width in metres, to introduce gridlines
      2 print(type(geometry_cut))

AttributeError: module 'osmnx' has no attribute 'quadrat_cut_geometry'

```
#### What operating system, Python version, and OSMnx version are you using?
OS: Linux_x64
osmnx-0.14.1   
Python version: 3.8.3
#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
# packages in environment at /home/keerat/anaconda3/envs/geo_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
branca                    0.4.1                      py_0    conda-forge
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.4.5.2       py38h32f6830_0    conda-forge
cffi                      1.14.0           py38hd463f26_0    conda-forge
cfitsio                   3.470                h3eac812_5    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.9.2            py38h766eaa4_0    conda-forge
curl                      7.69.1               h33f0ec9_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fiona                     1.8.13           py38h033e0f6_1    conda-forge
folium                    0.11.0                     py_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      3.0.4           py38h172510d_10    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.6.0                h05acad5_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.64.3               h6f030ca_0    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_100    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.1            py38h32f6830_0    conda-forge
importlib_metadata        1.6.1                         0    conda-forge
ipykernel                 5.3.0            py38h23f93f0_0    conda-forge
ipython                   7.15.0           py38h32f6830_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.1           py38h32f6830_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.15.1                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
kealib                    1.4.13               h33137a7_1    conda-forge
kiwisolver                1.2.0            py38hbf85e49_0    conda-forge
krb5                      1.17.1               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcurl                   7.69.1               hf7181ac_0    conda-forge
libdap4                   3.20.6               h1d1bd15_0    conda-forge
libedit                   3.1.20191231         h46ee950_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   3.0.4               he6a97d6_10    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libkml                    1.3.0             hb574062_1011    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libnetcdf                 4.7.4           nompi_h84807e1_104    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libpq                     12.2                 h5513abc_1    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             4.3.0a            h2482549_1038    conda-forge
libssh2                   1.9.0                hab1572f_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
matplotlib-base           3.2.2            py38h2af1d28_0    conda-forge
mistune                   0.8.4           py38h1e0a361_1001    conda-forge
munch                     2.5.0                      py_0    conda-forge
nb_conda                  2.2.1                    py38_2    conda-forge
nb_conda_kernels          2.2.3                    py38_0    conda-forge
nbconvert                 5.6.1            py38h32f6830_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
notebook                  6.0.3            py38h32f6830_0    conda-forge
numpy                     1.18.5           py38h8854b6b_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
osmnx                     0.14.1             pyh9f0ad1d_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.0.5            py38hcb8c335_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pip                       20.1.1                     py_1    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.87.0               h4190859_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 h8573dbc_1    conda-forge
proj                      7.0.0                h966b41f_4    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h7521cb9_0    conda-forge
pyrsistent                0.16.0           py38h1e0a361_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.3           cpython_he5300dc_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyzmq                     19.0.1           py38ha71036d_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py38h08f867b_1    conda-forge
scikit-learn              0.23.1           py38h3a94b23_0    conda-forge
scipy                     1.4.1            py38h18bccfc_3    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                47.3.1           py38h32f6830_0    conda-forge
shapely                   1.7.0            py38hd168ffb_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tbb                       2020.1               hc9558a2_0    conda-forge
terminado                 0.8.3            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    1.7.7                h8efa9f0_3    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
tzcode                    2020a                h516909a_0    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wcwidth                   0.2.4              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge

Note: you may need to restart the kernel to use updated packages.
</details>

#### Code snippet that independently and completely reproduces the issue

```import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import geopandas as gpd 
import osmnx as ox 
from descartes import PolygonPatch
from shapely.geometry import Point, LineString, Polygon, MultiPolygon 
#load Delhi from openstreetmap using osmnx api 
state=ox.gdf_from_place("Delhi, India", which_result=2)
print(state.crs)
state=ox.projection.project_gdf(state) #to convert from longlat system to metric system 
print(state)
fig, ax= ox.plot_shape(state)
print(state.crs)
geometry=state['geometry'].iloc[0] #0 indicates first row of table 
print(type(geometry))
geometry_cut = ox.quadrat_cut_geometry(geometry, quadrat_width=750) #width in metres, to introduce gridlines
print(type(geometry_cut))
```

**Comment by gboeing** [comment]
That function was deprecated and made internal/private a few releases ago. It remains available as such via the `utils_geo` module:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
gdf = ox.gdf_from_place('Los Angeles County, California, USA')
geom, crs = ox.projection.project_geometry(gdf.loc[0, 'geometry'])
geom_cut = ox.utils_geo._quadrat_cut_geometry(geom, 20000)
len(geom_cut) #56
```

See also the public OSMnx API reference in the [docs](https://osmnx.readthedocs.io/) for the current release.

**Comment by gboeing** [comment]
Also note that in #508 I added a new page to the docs to provide a [reference guide](https://osmnx.readthedocs.io/en/latest/osmnx-complete.html) to all module functions, including private internal functions (this is linked at the bottom of the docs home page). You can find docs for the `_quadrat_cut_geometry` function [here](https://osmnx.readthedocs.io/en/latest/osmnx-complete.html#osmnx-utils-geo-module).

**Comment by gboeing** [comment]
see also https://github.com/gboeing/osmnx/issues/511#issuecomment-649669215
