### ISSUE TITLE
Adding get_largest_component to core API?

### ISSUE THREAD

**Issue by ChrisStonehenge** [gboeing/osmnx#511]
Hi,

when I upgraded from 0.12.x to 0.14.1 I realised that some functions, including get_largest_component, are still part of the [public documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils_graph.get_largest_component) but are not imported directly as part of the core API.

Are those intentionally missing in the _api.py? Because for me it is a bit confusing to understand which functions are public and therefore part of the core API and which are internal.

Thanks,
Chris

**Comment by gboeing** [comment]
## Short answer

Everything in the [users' reference](https://osmnx.readthedocs.io/en/latest/osmnx.html) is a public function.

Every public function can be accessed via `ox.module_name.function_name()` and ~95% of the them (the most commonly used core functions) can be accessed directly via the `ox.function_name()` shortcut as well. Only a few less-common public functions are accessible only via `ox.module_name.function_name()`.

## Detailed answer

If a function is imported directly in `_api.py` then it is available directly in the `ox.` namespace via `ox.function_name()`.

If a public function is not imported directly in `_api.py`, then it can still be accessed via its module, just like it always could, e.g., `ox.module_name.function_name()`. Only a few public functions are accessed this way, if they're uncommonly used but designed for public consumption anyway. The [docs](https://osmnx.readthedocs.io/en/latest/osmnx.html#osmnx.utils_graph.get_largest_component) show how to use such public functions that aren't imported directly into the `ox.` namespace:

```python
ox.utils_graph.get_largest_component(G)
```

So, in summary, if you can see it in the docs or with code hinting/completion, then it's a public function. Every public function can be accessed via `ox.module_name.function_name()` and most of the them (the most commonly used ones) can be accessed directly via the `ox.function_name()` shortcut.

As of v0.13.0, all internal functions have been made "underscore" [private](https://stackoverflow.com/a/1547163) per standard Python convention. This should have happened years ago and been the case all along, but it fell by the wayside along the way. Finally it's been done properly. Internal functions are not designed for public consumption and could change between minor releases as they are not meant to be part of the public API. However, they can still be accessed via `ox.module_name._function_name()`. Note the underscore preceding the function name, per standard Python convention. If your function's name doesn't begin with a `_` , it's a public function. The private internal functions are documented alongside everything else in the [internals reference](https://osmnx.readthedocs.io/en/latest/osmnx-complete.html) guide.

For more of the reasoning behind this refactor, see [here](https://geoffboeing.com/2020/06/whats-new-with-osmnx/):

> **Streamlined API**
> 
> Over time, the OSMnx API and top-level namespace had become cluttered and increasingly unintuitive. Many of its modules had similarly grown unwieldy and its functional organization needed a rethink. The newly redesigned API:
> 
>  - only imports the primary user functions from the various modules into the ox. namespace (comprising the vast majority of end-user use cases)
>  - allows all other less-common user functions to be accessed via ox.module_name.function_name()
>  - makes all internal functions private/hidden
> 
> This makes package usage, documentation, code hinting, and code completion more simple, streamlined, and straightforward – but note that it is not 100% backwards compatible.

See also the updated [usage examples](https://github.com/gboeing/osmnx-examples).

**Comment by ChrisStonehenge** [comment]
Thank you for your detailed answer, it helped me a lot.

**Comment by gboeing** [comment]
I've updated the docs explain this function access a little more clearly in #510. Cross-ref #480.

**Comment by gboeing** [comment]
See also #526
