### ISSUE TITLE
'module' object has no attribute 'clean_intersections'

### ISSUE THREAD

**Issue by kaseyklimes** [gboeing/osmnx#52]
Loving working with OSMnx Geoff! Great tool. Ran into a problem in the example for 'Unify and clean-up intersections of divided roads'

I'm on Mac OS 10.12.3, using python 2.7.13, OSMnx 0.5

I can run the steps of the example without problem until this section:
```
# clean up the intersections and extract their xy coords
intersections = ox.clean_intersections(G_proj, tolerance=15, dead_ends=False)
points = np.array([point.xy for point in intersections])
```
which returns 
```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-c5c7cf0f7253> in <module>()
      1 # clean up the intersections and extract their xy coords
----> 2 intersections = ox.clean_intersections(G_proj, tolerance=15, dead_ends=False)
      3 points = np.array([point.xy for point in intersections])

AttributeError: 'module' object has no attribute 'clean_intersections'

**Comment by gboeing** [comment]
Thanks Kasey. Those commits haven't been formally released yet. They'll be coming shortly in v0.5.1. In the meantime, you can install the latest GitHub version to use the `clean_intersections` function.

**Comment by kaseyklimes** [comment]
Ah, got it. Thanks!
