### ISSUE TITLE
AttributeError: module 'osmnx' has no attribute 'geocode_to_gdf'

### ISSUE THREAD

**Issue by peanutj12** [gboeing/osmnx#528]
Hi, I know that there are rules for posting questions, but I am really a beginner and I do not know how to explain things very well. I am trying to use OSMNX for the first time and I am testing the examples from the link:

https://geoffboeing.com/2016/11/osmnx-python-street-networks/

I installed the OSMNX via the following command at CONDA:
conda install -c conda-forge/label/gcc7 osmnx

I am using Jupyter to test the examples. I tried the first one:
import osmnx as ox
city = ox.geocode_to_gdf('Berkeley, California')
ax = ox.project_gdf(city).plot()
_ = ax.axis('off')

But I receive the following message back:
AttributeError: module 'osmnx' has no attribute 'geocode_to_gdf'

I believe I am doing something wrong and it might be something very silly. But, as I said, I am really a beginner. My apologies if the question is really silly and thanks in advance.

**Comment by peanutj12** [comment]
I've noticed that the OSMNX hasn't been properly installed. So, I installed it again with the code:

conda config --prepend channels conda-forge
conda create -n ox --strict-channel-priority osmnx

But still, nothing changed.. :(

**Comment by gboeing** [comment]
> I installed the OSMNX via the following command at CONDA:
> conda install -c conda-forge/label/gcc7 osmnx

Why are you using the old `gcc7` tag for installation? Is that deliberate? If not, note that it's an old conda forge tag that hasn't been applied to new releases for months (years?), so you're installing a very old version: 0.8.2. The current release is 0.15.1. The [documentation](https://osmnx.readthedocs.io/en/stable/) and [usage examples](https://github.com/gboeing/osmnx-examples) describe the current release.

I'd recommend removing *all* OSMnx installations on your system and removing any such conda/virtual environments. Then install OSMnx again from the beginning according to the instructions in the [documentation](https://osmnx.readthedocs.io/en/stable/).

If you have further or follow-up usage questions, you can ask on [StackOverflow](https://stackoverflow.com/).
