### ISSUE TITLE
Add an option to the save bidirectional graph

### ISSUE THREAD

**Issue by cyang-kth** [gboeing/osmnx#537]
**Describe the solution you'd like to propose**

Currently, a graph can be created to be bidirectional. However, when saving it to a shapefile or geopackage, the reverse edge are automatically removed to create an undirected graph. 

https://github.com/gboeing/osmnx/blob/fcb51ac4cc17fca28c05694c2f3acbc95ca15a6f/osmnx/io.py#L45-L47 

It would be nice to have a bidirectional option to turn on exporting the original bidirectional graph (the shapefile can be used in an external program, e.g., routing or map matching).

**Comment by gboeing** [comment]
> It would be nice to have a bidirectional option to turn on exporting the original bidirectional graph

An *undirected graph* is bidirectional. Are you interested in saving the *directed graph*?

**Comment by cyang-kth** [comment]
> > It would be nice to have a bidirectional option to turn on exporting the original bidirectional graph
> 
> An _undirected graph_ is bidirectional. Are you interested in saving the _directed graph_?

What I want is actually a bidirectional graph where each edge is directed
- if the original osm edge has one-way=false, two directed edges with reverse geometry are stored 
- If the original osm has one-way=true, just a single directed edge is stored.

**Comment by cyang-kth** [comment]
The current graph object created in Python stores the edges in the way I want, but when I export the data to shapefile or geo package, the reversed edge seems to be deleted.

**Comment by gboeing** [comment]
You can accomplish that directly with just a couple lines of code, so I don't think it will require new feature development in the package itself:

```python
gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)
gdf_nodes = ox.io._stringify_nonnumeric_cols(gdf_nodes)
gdf_edges = ox.io._stringify_nonnumeric_cols(gdf_edges)
gdf_nodes.to_file('graph.gpkg', layer='nodes', driver='GPKG')
gdf_edges.to_file('graph.gpkg', layer='edges', driver='GPKG')
```

Note also that you can recover directedness and directionality from the gpkg saved as-is by `save_graph_geopackage`: the `oneway` attribute on each edge tells you if it's one-way or not, and each one-way edge allows travel only in the direction from the `u` attribute node to the `v` attribute node (allowing you to do routing and map-matching accordingly).

**Comment by cyang-kth** [comment]
@gboeing 
Thanks a lot. I have solved the problem now.
