### ISSUE TITLE
.save_gdf_shapefile returns ValueError

### ISSUE THREAD

**Issue by kaseyklimes** [gboeing/osmnx#54]
Trying to save building gdf's to a shapefile and getting a value error. Seems like it might be an issue with GeoPandas or Fiona? It returns the same error when I designate a specific filename and folder path.

I'm on Mac OS 10.12.3, using python 2.7.13, OSMnx 0.5.1

```python
import osmnx as ox
%matplotlib inline
ox.config(log_console=True, use_cache=True)

G = ox.buildings_from_place(place='Piedmont, California, USA')
G_proj = ox.project_gdf(G)
ox.save_gdf_shapefile(G_proj)
```

error:
```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-820a8cb18c25> in <module>()
      1 G = ox.buildings_from_place(place='Piedmont, California, USA')
      2 G_proj = ox.project_gdf(G)
----> 3 ox.save_gdf_shapefile(G_proj)

/Users/kaseyklimes/anaconda2/lib/python2.7/site-packages/osmnx/save_load.pyc in save_gdf_shapefile(gdf, filename, folder)
     50     if not os.path.exists(folder_path):
     51         os.makedirs(folder_path)
---> 52     gdf.to_file(folder_path)
     53     if not hasattr(gdf, 'gdf_name'):
     54         gdf.gdf_name = 'unnamed'

/Users/kaseyklimes/anaconda2/lib/python2.7/site-packages/geopandas/geodataframe.pyc in to_file(self, filename, driver, schema, **kwargs)
    341         """
    342         from geopandas.io.file import to_file
--> 343         to_file(self, filename, driver, schema, **kwargs)
    344 
    345     def to_crs(self, crs=None, epsg=None, inplace=False):

/Users/kaseyklimes/anaconda2/lib/python2.7/site-packages/geopandas/io/file.pyc in to_file(df, filename, driver, schema, **kwargs)
     61                     schema=schema, **kwargs) as c:
     62         for feature in df.iterfeatures():
---> 63             c.write(feature)
     64 
     65 

/Users/kaseyklimes/anaconda2/lib/python2.7/site-packages/fiona/collection.pyc in write(self, record)
    339     def write(self, record):
    340         """Stages a record for writing to disk."""
--> 341         self.writerecords([record])
    342 
    343     def validate_record(self, record):

/Users/kaseyklimes/anaconda2/lib/python2.7/site-packages/fiona/collection.pyc in writerecords(self, records)
    333         if self.mode not in ('a', 'w'):
    334             raise IOError("collection not open for writing")
--> 335         self.session.writerecs(records, self)
    336         self._len = self.session.get_length()
    337         self._bounds = self.session.get_extent()

fiona/ogrext.pyx in fiona.ogrext.WritingSession.writerecs (fiona/ogrext2.c:17987)()

fiona/ogrext.pyx in fiona.ogrext.OGRFeatureBuilder.build (fiona/ogrext2.c:7030)()

ValueError: Invalid field type <type 'list'>

**Comment by gboeing** [comment]
Right... the use case for which `save_gdf_shapefile` was designed was to save place shape GeoDataFrames. But this should be able to save building footprint GeoDataFrames as well. I changed the function so it converts all non-geometry columns to string type, so Fiona can save it as a shapefile, in 29dc216. Should work now. You can install the latest GitHub version to get this code now and I'll plan to release as a minor version soon.

**Comment by SqySimmon** [comment]
when i use `ox.gdfs_to_graph(nodes, edges)`
i got this error:
**AttributeError: 'GeoDataFrame' object has no attribute 'gdf_name'**
![image](https://user-images.githubusercontent.com/15140733/39085016-c7387c18-45af-11e8-92f9-1f11ce73e08a.png)
the '*.shp' files were downloaded before
![image](https://user-images.githubusercontent.com/15140733/39085067-54afcb64-45b0-11e8-87ae-09ee23208645.png)
(correctly download and save, '****' is only to hide the city)

**Comment by SqySimmon** [comment]
when i use ox.gdfs_to_graph(nodes, edges)
i got this error:
AttributeError: 'GeoDataFrame' object has no attribute 'gdf_name'
![image](https://user-images.githubusercontent.com/15140733/39085124-de9ae016-45b0-11e8-89da-b09a46bc7261.png)

the '.shp' files were downloaded before
![image](https://user-images.githubusercontent.com/15140733/39085110-bfbb81d2-45b0-11e8-81ee-966157ff51f2.png)
(correctly download and save, '***' is only to hide the city)

**Comment by SqySimmon** [comment]
@gboeing thanks
sorry, i haven't described it clearly. i just want to create a graph from the data i have downloaded from these apis:
![image](https://user-images.githubusercontent.com/15140733/39090256-9a184968-460c-11e8-80ee-3b074efd3e44.png)
so i use that function and data read by GeoPandas, is that right?  Or other methods?

**Comment by gboeing** [comment]
@SqySimmon if you want to re-load data you previously downloaded using OSMnx, use the graphml file format via `ox.save_graphml` and `ox.load_graphml`. See the [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.save_load) and example notebooks for demonstration.
