### ISSUE TITLE
Why pd.Series.apply([func]) can add 'func' as outer level column name in result?

### ISSUE THREAD

**Issue by easysam** [gboeing/osmnx#544]
https://github.com/gboeing/osmnx/blob/e1bfad35d8591f8b0e71110476b456c2c62d6e08/osmnx/distance.py#L418

The code use the feature in issue's title, and I can't find the feature in pandas documentation. 

Can you briefly point out how it works? Thanks.

**Comment by easysam** [comment]
Or any reference? Thanks.

**Comment by gboeing** [comment]
Per the contributing guidelines and new issue template, the issue tracker is for reporting bugs or proposing new features.

Please ask general questions on StackOverflow, particularly a pandas usage question such as this, as the user/dev community there will be able to provide a thorough explanation.

As a quick short answer though, just recreate its code then try it with/without the `[ ]` and you'll see what it does.

```python
import osmnx as ox
import pandas as pd
ox.config(use_cache=True, log_console=True)

G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
G = ox.project_graph(G)
edges = ox.utils_graph.graph_to_gdfs(G, nodes=False, fill_edge_geometry=True)
edges["points"] = edges.apply(lambda x: ox.utils_geo.redistribute_vertices(x.geometry, dist=50), axis=1)
edges["points"].apply([pd.Series]).stack().reset_index(level=1, drop=True).join(edges).reset_index()
```
