### ISSUE TITLE
 Add the nearest node to a point GeoDtaframe

### ISSUE THREAD

**Issue by sephib** [gboeing/osmnx#56]
Hi,
I'm suggesting to add the below functionality in order add the nearest node to a point GeoDtaframe, it may be added to the util module  (the code recycles  existing functions)
Unfortunately I have problems sending a PR from my cooperate environment, thus adding the code to this issues:
``` python
def add_nearest_node_to_gdf(gdf, G, radius=1000):
    ''' 
   gdf : GeoDatafram
        Point GeoDataFrame that needs to add the closest node from graph G
    G : networkx graph
   No return
    '''
   # dump graph node coordinates into a pandas datframe indexed by node id with x and y columns
    coords =  np.array([node, data['x'], data['y']] for node, data in G.nodes(data=True)])
    df = pd.DataFrame(coords, columns= ['node', 'x', 'y']).set_index('node')
    df['geometry'] = df.apply(lambda x: Point(x['x'], x['y']), axis=1)

    for _, geom in gdf['geometry'].iteritems():
        dff = df.pip(filter_df_by_radius, geom, radius)
        distances = dff.apply(lambda x: geom.distance(x['geometry']), axis =1)
        gdf.loc[_, 'dif_node'] = int(distances.idxmin())
   gdf['dif_node'] = gdf['dif_node'].astype(int)


def filter_df_by_radius(df, geom, radius=1000):
    ''' Filter DataFrame
    df : dtaframe with point geometry
    geom :  geometry point which will be the centroid for the filter
    radius : distance to set the buffer/MBR on df in dataframe geo units
    Retrun Dataframe
    ''''
   x,y = geom.coords[0]
   dff = df.loc[(df['x'] < x + radius) & (df['x'] > x - radius) & (df['y'] < y + radius) & (df['y'] > y - radius) ]
   return dff
```

Feel free to review and amend.

**Comment by gboeing** [comment]
Thanks. Can you tell me more about this functionality? What is an example use case?

**Comment by sephib** [comment]
Hi,
The idea is that if you need to add a set of GPS coordinates to the network in order (for example) to generate a list of paths to a  destination node.
Does it make sense?

**Comment by gboeing** [comment]
Closing this issue for now. This could be an interesting feature to add in the future if it gets built out, but it needs some further development before a pull request. Keep me posted if you develop it further.

**Comment by SjoerdBraaksma** [comment]
This looks like a fun function to build out more. Mind if I give it a try?

I'd try to build it out to have  a similar functionality as the st_nearest function of the R sf package: https://r-spatial.github.io/sf/reference/st_nearest_feature.html which I think is, to be honest, far better than geopandas.

**Comment by gboeing** [comment]
@SjoerdBraaksma would this offer functionality substantially different than what the `nearest_nodes` function offers?
