### ISSUE TITLE
Improving performance when using get_nearest_edge repeatedly

### ISSUE THREAD

**Issue by McToel** [gboeing/osmnx#563]
For a project, I have to run `get_nearest_edge` about 8000 times on a big network (130k nodes) (to clarify: I cannot use `get_nearest_edges`, as it runs out of memory on my 32GB machine.). What I did was that I got the gdf_edges GeoDataFrame outside the function and this saved me about 5h runtime (from 24h to 19h). For this I changed 3 Lines in distance.py:
```python
def get_nearest_edge(G, point, return_geom=False, return_dist=False, gdf_edges=None):
    if gdf_edges is None:
        # get u, v, key, geom from all the graph edges
        gdf_edges = utils_graph.graph_to_gdfs(G, nodes=False, fill_edge_geometry=True)
```

I wondered whether this might be helpful for more projects.

**Comment by gboeing** [comment]
> I cannot use get_nearest_edges, as it runs out of memory on my 32GB machine

Can you provide a minimal working example of what you're doing? I'm curious how you're parameterizing `get_nearest_edges` and want to test its efficiency using the same code you are.

See also related issue #560

**Comment by McToel** [comment]
Here is a minimal example. I'm using osmnx to generate a routable railway network for Germany.
```python
import osmnx as ox
import networkx as nx
import numpy as np


def get_streckennetz_from_osm():
    ox.config(log_console=True, use_cache=True)
    rail_filter = '["railway"~"rail|tram|narrow_gauge|light_rail"]'
    streckennetz = ox.graph_from_place('Germany',
                                       simplify=True,
                                       network_type='none',
                                       custom_filter=rail_filter
                                       )
    nx.write_gpickle(streckennetz, "original_osm_rail_graph.gpickle")
    return streckennetz


if __name__ == '__main__':
    get_streckennetz_from_osm()
    streckennetz = nx.read_gpickle("original_osm_rail_graph.gpickle")

    # generate coordinates in the bounding box of germany
    x = np.random.uniform(low=5.67, high=15.64, size=(7000,)).tolist()
    y = np.random.uniform(low=47.06, high=55.06, size=(7000,)).tolist()
    ox.get_nearest_edges(streckennetz, x, y, method="kdtree")

```
The script need about an hour to gather the graph. You can speed things up by downloading the graph here: https://1drv.ms/u/s!Ao2sonSYSPrHgZcm8rMoyWqi69RDhw

**Comment by gboeing** [comment]
Given your pickled graph, I'm able to execute `get_nearest_edges` on my machine (32 gb of ram as well) in approximately 3.5 minutes:

```python
import networkx as nx
import osmnx as ox
import numpy as np
ox.config(use_cache=True, log_console=True)

G = nx.read_gpickle("original_osm_rail_graph.gpickle")
Gp = ox.project_graph(G)

x = np.random.uniform(low=5.67, high=15.64, size=(7000,)).tolist()
y = np.random.uniform(low=47.06, high=55.06, size=(7000,)).tolist()

# completes in ~3.5 minutes
ne = ox.get_nearest_edges(Gp, x, y, method="kdtree", dist=50)
```

A couple notes:

  1. It looks like you're using `method="kdtree"`, but you're not passing in a projected graph... see [the docs](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.distance.get_nearest_edges).
  2. Vary the `dist` parameter to balance between the trade-offs of your machine's memory limits vs using a coarser-grained approximation of the line geometries in nearest-edge finding. In my example here, I've set it to 50 meters (as it's a projected graph), which is pretty fine-grained yet never uses even half of my computer's ram.

**Comment by McToel** [comment]
Thank You very much for the advice. Do I understand it correctly, that choosing a higher dist on an unprotected graph should give similar results? And one other thing: is there a buildin method to calculate the length of edges by their full geometry and not only the coords of u and v?
Coming back to the original Question though: I think it might still make sense (even if my problem is probably solved) to add an `gdf_edges` argument as it could also be used for `get_nearest_edges(method=None)`.

**Comment by gboeing** [comment]
> Do I understand it correctly, that choosing a higher dist on an unprotected graph should give similar results?

Yes, but you'll want to use the `balltree` method if you're using an unprojected graph, which is a little slower and less memory efficient.

> is there a buildin method to calculate the length of edges by their full geometry and not only the coords of u and v?

No, but look into the shapely package's geometry `length` attribute.

> I think it might still make sense (even if my problem is probably solved) to add an gdf_edges argument as it could also be used for get_nearest_edges(method=None)

This seems like an edge case, so I don't think it'll be added as a feature to OSMnx. The `get_nearest_edge` function is designed for finding the one edge nearest to a single point. It's not intended to be used in a loop: that's what `get_nearest_edges` (and its massive speed/efficiency improvements) is for.

**Comment by gboeing** [comment]
Note that this functionality has been replaced with the new, faster, streamlined `nearest_edges` function as of OSMnx v1.1.0. See the function's [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.distance.nearest_edges) and #675.
