### ISSUE TITLE
Multiple osmid per edge

### ISSUE THREAD

**Issue by matiasitalia** [gboeing/osmnx#565]
Hi Geoff, great package!

I have a question about some data after loading a map, for example Montevideo (Uruguay).

After generating the geodataframe, I keep the edges, I convert it to a dataframe, and I find that there are observations with multiple osmid, for example: osmid =[176325835, 78108372, 442200095]; name = ['Rambla Edison', 'Coronel Francisco   Tajes']; highway = ['primary', 'residential']; maxspeed = ['45', '60']; and length=163.028.

This is normal? Because I want to get de length of all primary streets, and with these cases I'm in trouble.

My code was:
_import geopandas as gpd
import osmnx as ox
import pandas as pd
useful_tags_way = ['oneway', 'lanes', 'name', 'highway', 'maxspeed', 'width', 'est_width','surface']
ox.utils.config(useful_tags_way=useful_tags_way, timeout=1000)
G = ox.graph_from_place('Montevideo, Uruguay', network_type='drive')
edges = ox.graph_to_gdfs(G, nodes=False, edges=True)
df = pd.DataFrame(edges).apply(tuple)
df.to_csv('Montevideo.csv', index=False)_

Another question is about the length of streets. I understand that this information does not come from osm, and that osmnx generates it, but how does it calculate it?

Thanks!

Matias

**Comment by gboeing** [comment]
> I find that there are observations with multiple osmid

The `graph_from_place` function's default `simplify` argument is `True`, meaning OSMnx automatically topologically simplifies your graph. Some of the resulting edges comprise multiple OSM ways as denoted by the list of OSM ID values. Not a bug.

> Another question is about the length of streets. I understand that this information does not come from osm, and that osmnx generates it, but how does it calculate it?

OSMnx's `graph._create_graph` function assembles the graph model from the raw OpenStreetMap data and as a final step calculates great-circle distances between all straight-line (i.e., unsimplified) edges using the `utils_graph.add_edge_lengths` function, as noted in the [internals reference](https://osmnx.readthedocs.io/en/latest/osmnx-complete.html).
