### ISSUE TITLE
405 Method Not Allowed - HTTP 

### ISSUE THREAD

**Issue by omar-3** [gboeing/osmnx#567]
**Problem description**
  - What did you do?
Trying to get the map data from `osmnx.graph_from_point`
  - What did you expect to happen?
To get the graph back 
  - And what actually happened instead?
It returned to me with reponse code 405 -- please note that I have been using osmnx for the last 3-4 months and it just stopped working for no apparent reason. 

Here is the complete error stack.
<details>

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/osmnx/downloader.py in overpass_request(data, pause, error_pause)
    652         try:
--> 653             response_json = response.json()
    654             if "remark" in response_json:

~/.local/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    897                     pass
--> 898         return complexjson.loads(self.text, **kwargs)
    899 

/usr/lib/python3/dist-packages/simplejson/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    517             and not use_decimal and not kw):
--> 518         return _default_decoder.decode(s)
    519     if cls is None:

/usr/lib/python3/dist-packages/simplejson/decoder.py in decode(self, s, _w, _PY3)
    369             s = s.decode(self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()

/usr/lib/python3/dist-packages/simplejson/decoder.py in raw_decode(self, s, idx, _w, _PY3)
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-2-35a03d102963> in <module>
      1 location_point = (43.661667, -79.395)
----> 2 G = ox.graph_from_point(location_point, dist=300, clean_periphery=True, simplify=True)

~/.local/lib/python3.6/site-packages/osmnx/graph.py in graph_from_point(center_point, dist, dist_type, network_type, simplify, retain_all, truncate_by_edge, clean_periphery, custom_filter)
    165         truncate_by_edge=truncate_by_edge,
    166         clean_periphery=clean_periphery,
--> 167         custom_filter=custom_filter,
    168     )
    169 

~/.local/lib/python3.6/site-packages/osmnx/graph.py in graph_from_bbox(north, south, east, west, network_type, simplify, retain_all, truncate_by_edge, clean_periphery, custom_filter)
     86         truncate_by_edge=truncate_by_edge,
     87         clean_periphery=clean_periphery,
---> 88         custom_filter=custom_filter,
     89     )
     90 

~/.local/lib/python3.6/site-packages/osmnx/graph.py in graph_from_polygon(polygon, network_type, simplify, retain_all, truncate_by_edge, clean_periphery, custom_filter)
    421 
    422         # download the network data from OSM within buffered polygon
--> 423         response_jsons = downloader._osm_net_download(poly_buff, network_type, custom_filter)
    424         bidirectional = network_type in settings.bidirectional_network_types
    425 

~/.local/lib/python3.6/site-packages/osmnx/downloader.py in _osm_net_download(polygon, network_type, custom_filter)
    442     for polygon_coord_str in polygon_coord_strs:
    443         query_str = f"{overpass_settings};(way{osm_filter}(poly:'{polygon_coord_str}');>;);out;"
--> 444         response_json = overpass_request(data={"data": query_str})
    445         response_jsons.append(response_json)
    446     utils.log(

~/.local/lib/python3.6/site-packages/osmnx/downloader.py in overpass_request(data, pause, error_pause)
    669                 # else, this was an unhandled status_code, throw an exception
    670                 utils.log(f"{domain} returned {sc}", level=lg.ERROR)
--> 671                 raise Exception(f"Server returned\n{response} {response.reason}\n{response.text}")
    672 
    673         _save_to_cache(prepared_url, response_json)

Exception: Server returned
<Response [405]> Method Not Allowed
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>405 - HTTP verb used to access this page is not allowed.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>405 - HTTP verb used to access this page is not allowed.</h2>
  <h3>The page you are looking for cannot be displayed because an invalid method (HTTP verb) was used to attempt access.</h3>
 </fieldset></div>
</div>
</body>
</html>
</details>

**Environment information**
  - What operating system are you using?
Ubuntu 18.04
  - What Python version are you using?
3.6.9
  - What OSMnx version are you using?
0.16.0
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
affine                            2.3.0
apturl                            0.5.2
asn1crypto                        0.24.0
attrs                             19.3.0
backcall                          0.1.0
bleach                            3.1.5
bokeh                             2.0.2
branca                            0.4.0
Brlapi                            0.6.6
Brotli                            1.0.7
Cartopy                           0.17.0
celluloid                         0.2.0
certifi                           2020.4.5.1
chardet                           3.0.4
click                             7.1.2
click-plugins                     1.1.1
cligj                             0.5.0
command-not-found                 0.3
contextily                        1.0.0
cryptography                      2.1.4
cupshelpers                       1.0
cycler                            0.10.0
Cython                            0.29.20
dash                              1.11.0
dash-core-components              1.9.1
dash-html-components              1.0.3
dash-renderer                     1.4.0
dash-table                        4.6.2
decorator                         4.4.2
defer                             1.0.6
defusedxml                        0.6.0
Deprecated                        1.2.9
descartes                         1.1.0
distro-info                       0.18ubuntu0.18.04.1
entrypoints                       0.3
Fiona                             1.8.13.post1
Flask                             1.1.2
Flask-Compress                    1.5.0
folium                            0.10.1
future                            0.18.2
geographiclib                     1.50
geopandas                         0.8.1
geoplot                           0.4.0
geopy                             1.21.0
html5lib                          0.999999999
httplib2                          0.9.2
idna                              2.9
imageio                           2.8.0
importlib-metadata                1.6.0
ipykernel                         5.2.1
ipyleaflet                        0.13.3
ipython                           7.14.0
ipython-genutils                  0.2.0
ipythonblocks                     1.9.0
ipywidgets                        7.5.1
iso8601                           0.1.12
itsdangerous                      1.1.0
jedi                              0.17.0
Jinja2                            2.11.2
joblib                            0.14.1
json5                             0.9.4
jsonschema                        3.2.0
jupyter-c-kernel                  1.2.2
jupyter-client                    6.1.3
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.6.3
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        2.1.0
jupyterlab-server                 1.1.0
keplergl                          0.2.1
keyring                           10.6.0
keyrings.alt                      3.0
kiwisolver                        1.2.0
language-selector                 0.1
launchpadlib                      1.10.6
lazr.restfulclient                0.13.5
lazr.uri                          1.0.3
louis                             3.5.0
lxml                              4.5.0
macaroonbakery                    1.1.3
Mako                              1.0.7
mapclassify                       2.2.0
MarkupSafe                        1.1.1
marshmallow                       3.6.1
matplotlib                        3.3.2
mercantile                        1.1.4
mistune                           0.8.4
mpmath                            1.1.0
munch                             2.5.0
mysql                             0.0.2
mysql-connector                   2.2.9
mysqlclient                       1.4.6
nbconvert                         5.6.1
nbformat                          5.0.6
netifaces                         0.10.4
networkx                          2.5
nodejs                            0.1.1
nose                              1.3.7
notebook                          6.0.3
numpy                             1.19.2
oauth                             1.0.1
olefile                           0.45.1
opencv-python                     4.2.0.34
optional-django                   0.1.0
osmiter                           1.0.4
osmnx                             0.16.0
packaging                         20.3
pandas                            1.1.2
pandocfilters                     1.4.2
parso                             0.7.0
patsy                             0.5.1
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            7.1.2
pip                               20.2.2
pip-autoremove                    0.9.1
plotly                            4.6.0
pluggy                            0.6.0
prometheus-client                 0.7.1
prompt-toolkit                    3.0.5
protobuf                          3.12.2
ptyprocess                        0.6.0
py                                1.5.2
pycairo                           1.16.2
pycrypto                          2.6.1
pycups                            1.9.73
Pygments                          2.6.1
pygobject                         3.26.1
pymacaroons                       0.13.0
PyNaCl                            1.1.2
pyparsing                         2.4.7
pyproj                            2.6.1.post1
pyRFC3339                         1.0
pyroutelib3                       1.6.3
pyrsistent                        0.16.0
pyshp                             2.1.0
pytest                            3.3.2
python-apt                        1.6.5+ubuntu0.3
python-dateutil                   2.8.1
python-debian                     0.1.32
pytz                              2020.1
PyWavelets                        1.1.1
pyxdg                             0.25
PyYAML                            5.3.1
pyzmq                             19.0.1
qpsolvers                         1.1
quadprog                          0.1.7
rasterio                          1.1.3
reportlab                         3.4.0
requests                          2.24.0
requests-unixsocket               0.1.5
retrying                          1.3.3
Rtree                             0.9.4
scikit-image                      0.16.2
scikit-learn                      0.22.2.post1
scipy                             1.4.1
seaborn                           0.10.1
SecretStorage                     2.3.1
Send2Trash                        1.5.0
setuptools                        47.1.1
Shapely                           1.7.0
simplegeneric                     0.8.1
simplejson                        3.13.2
six                               1.15.0
snuggs                            1.4.7
sortedcontainers                  2.1.0
SpeechRecognition                 3.8.1
statsmodels                       0.11.1
sympy                             1.6.2
system-service                    0.3
systemd-python                    234
terminado                         0.8.3
testpath                          0.4.4
tk                                0.1.0
tornado                           6.0.4
tqdm                              4.47.0
traitlets                         4.3.3
traittypes                        0.2.1
typing-extensions                 3.7.4.2
ubuntu-drivers-common             0.0.0
ufw                               0.36
unattended-upgrades               0.1
urllib3                           1.25.9
usb-creator                       0.3.3
wadllib                           1.3.2
wcwidth                           0.1.9
webencodings                      0.5.1
Werkzeug                          1.0.1
wget                              3.2
wheel                             0.30.0
widgetsnbextension                3.5.1
wrapt                             1.12.1
xkit                              0.0.0
yapf                              0.29.0
zipp                              3.1.0
zope.interface                    4.3.2
</details>

**Provide a complete minimal reproducible example**

Your example code snippet here must be *minimal* so it doesn't contain extraneous code unrelated to your specific problem and it must be *complete* so we can independently run it from top to bottom by copying/pasting it into a Python interpreter. That means all imports and all variables must be defined. If you're unsure how to create a good reproducible example, read [this guide](https://stackoverflow.com/help/minimal-reproducible-example). Do not post a screenshot of your code or error message: provide it as text.

```python
location_point = (43.661667, -79.395)
G = ox.graph_from_point(location_point, dist=300, clean_periphery=True, simplify=True)
```

**Comment by gboeing** [comment]
This is all working on my end without any problems. I just ran:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
location_point = (43.661667, -79.395)
G = ox.graph_from_point(location_point, dist=300, clean_periphery=True, simplify=True)
len(G) #379
```

**Comment by omar-3** [comment]
Yes the problem was at my OpenSSL config file.

Sorry for the mistake, I will close the issue.
