### ISSUE TITLE
basic_stats returns errors for graphs from polygons containing no roads or roads that do not enclose an area

### ISSUE THREAD

**Issue by capilgram** [gboeing/osmnx#568]
**Problem description**
I discovered this error when running a loop that called basic_stats() for every single census tract in California. Some census tracts contain no roads, or very few roads. When applied to graphs created for those census tracts as polygons, I would expect basic_stats() to return statistics informing the user that there are zero nodes and edges (or very few of them), and potentially give NAs for statistics that do not exist for that geography.

Instead, basic_stats() crashes, alternately with "ValueError: not enough values to unpack (expected 2, got 0)" for zero roads, or with "ZeroDivisionError: float division by zero" for certain census tracts that contain very few roads that do not enclose any area.

**Environment information**
  - OS: both Windows 10 and Ubuntu 20.04 (same error in both environments)
  - Python version: 3.8.5
  - OSMnx version: 0.16.0
  - Packages: See Details.

<details>
(ox) PS C:\Users\Clemens> conda list
# packages in environment at C:\Users\Clemens\Anaconda3\envs\ox:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               20.1.0           py38h1e8a9f7_1    conda-forge
astroid                   2.4.2            py38h32f6830_0    conda-forge
async-generator           1.10                     pypi_0    pypi
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.1.0             pyh9f0ad1d_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py38h1e8a9f7_0    conda-forge
blas                      1.0                         mkl    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
branca                    0.4.1                      py_0    conda-forge
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.1           py38hba49e27_0    conda-forge
cfitsio                   3.470                hbbe6aef_6    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.5.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
console_shortcut          0.1.1                         4
cryptography              3.0              py38hba49e27_0    conda-forge
curl                      7.71.1               h4b64cdc_5    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.16             py38h32f6830_1    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                h33f27b4_2    conda-forge
fiona                     1.8.13           py38h41bf4fa_1    conda-forge
flake8                    3.8.3                      py_1    conda-forge
folium                    0.11.0                     py_0    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gdal                      3.0.4                    pypi_0    pypi
geopandas                 0.8.1                      py_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.5.1               h3d29ae3_10    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3          py38hfa79958_1004    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.7.0            py38h32f6830_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
intel-openmp              2019.4                      245
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 5.3.4            py38h5ca1d4c_0    conda-forge
ipython                   7.17.0           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.5.3                    pypi_0    pypi
jedi                      0.17.1           py38h32f6830_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
jupyterlab-pygments       0.1.2                    pypi_0    pypi
kealib                    1.4.13               h3b59ab9_1    conda-forge
keyring                   21.3.0           py38h32f6830_0    conda-forge
kiwisolver                1.2.0            py38heaebd3c_0    conda-forge
krb5                      1.17.1               hc04afaa_2    conda-forge
lazy-object-proxy         1.5.1                    pypi_0    pypi
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.71.1               h4b64cdc_5    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libgdal                   3.0.4                h6f60a84_9    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_105    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libpq                     12.3                 hd9aa61d_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            h51df0ed_1038    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38h9de7a3e_1    conda-forge
matplotlib-base           3.3.1            py38hfb9ee82_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py38h9de7a3e_1001    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py38hfa6e2cd_0    conda-forge
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
nbclient                  0.5.0                    pypi_0    pypi
nbconvert                 6.0.6                    pypi_0    pypi
nbformat                  5.0.7                      py_0    conda-forge
nest-asyncio              1.4.1                    pypi_0    pypi
networkx                  2.5                      pypi_0    pypi
notebook                  6.1.3            py38h32f6830_0    conda-forge
numpy                     1.19.1           py38h72c728b_0    conda-forge
numpydoc                  1.1.0              pyh9f0ad1d_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
osmnx                     0.16.0                   pypi_0    pypi
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.0            py38h7ae7562_0    conda-forge
pandoc                    2.10.1               he774522_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.1              pyh9f0ad1d_1    conda-forge
parso                     0.8.0                    pypi_0    pypi
pathtools                 0.1.2                      py_1    conda-forge
pcre                      8.44                 h6538335_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.2.0            py38h7011068_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
pixman                    0.38.0            hfa6e2cd_1003    conda-forge
pluggy                    0.13.1           py38h32f6830_2    conda-forge
poppler                   0.87.0               h0cd1227_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.3                 he14cc48_0    conda-forge
powershell_shortcut       0.0.1                         3
proj                      7.0.0                haa36216_5    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.6                      py_0    conda-forge
psutil                    5.7.2            py38h1e8a9f7_0    conda-forge
ptyprocess                0.6.0                    pypi_0    pypi
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                5.1.1                    pypi_0    pypi
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.7.1                    pypi_0    pypi
pylint                    2.5.3            py38h32f6830_0    conda-forge
pynacl                    1.3.0                    pypi_0    pypi
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h1dd9442_0    conda-forge
pyqt5                     5.15.1                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.5           h60c2a47_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.3.4              pyh9f0ad1d_1    conda-forge
python-language-server    0.34.1           py38h32f6830_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywin32                   227              py38hfa6e2cd_0    conda-forge
pywin32-ctypes            0.2.0           py38h32f6830_1001    conda-forge
pywinpty                  0.5.7                    py38_0    conda-forge
pyyaml                    5.3.1            py38h9de7a3e_0    conda-forge
pyzmq                     19.0.2           py38h77b9d75_0    conda-forge
qdarkstyle                2.8.1              pyh9f0ad1d_1    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtawesome                 0.7.2              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.6              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rope                      0.17.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py38h7ad75cc_1    conda-forge
scikit-learn              0.23.2           py38hf00eced_0    conda-forge
scipy                     1.5.0            py38h9439919_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h32f6830_0    conda-forge
shapely                   1.7.1            py38hc96c142_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
sphinx                    3.2.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.1.4            py38h32f6830_0    conda-forge
spyder-kernels            1.9.3            py38h32f6830_0    conda-forge
sqlite                    3.33.0               he774522_0    conda-forge
tbb                       2020.1               he980bc4_0    conda-forge
terminado                 0.8.3            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    1.7.7                h0b90766_3    conda-forge
tk                        8.6.10               he774522_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
tornado                   6.0.4            py38hfa6e2cd_0    conda-forge
traitlets                 5.0.4                    pypi_0    pypi
ujson                     3.2.0                    pypi_0    pypi
urllib3                   1.25.10                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
watchdog                  0.10.3           py38h32f6830_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.2                ha925a31_3    conda-forge
zipp                      3.2.0                    pypi_0    pypi
zlib                      1.2.11            h62dcd97_1007    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge
</details>

**Minimal Reproducible Example**

```python
import osmnx as ox
from shapely import wkt

ox.__version__

### EXAMPLE 1: NO ROADS
# build a polygon containing the California Channel Islands (outline of CA Census tract 06083980100)
# this area contains zero roads - basic stats should return zero edges, zero nodes.
polygon_to_process = wkt.loads('MULTIPOLYGON (((-119.052912 33.47917, -119.051817 33.480711, -119.049558 33.481282, -119.050243 33.482824, -119.050174 33.483167, -119.049969 33.484138, -119.049284 33.485051, -119.047778 33.485394, -119.046135 33.485337, -119.044866 33.484989, -119.043602 33.484537, -119.04148 33.484651, -119.039426 33.484709, -119.037989 33.484709, -119.03703 33.485678, -119.03751 33.486707, -119.037373 33.488078, -119.036414 33.488819, -119.034703 33.488649, -119.033539 33.488191, -119.032923 33.488363, -119.031828 33.489676, -119.029637 33.490133, -119.028131 33.489676, -119.026899 33.488934, -119.026625 33.487564, -119.027241 33.485394, -119.028063 33.483053, -119.026967 33.481682, -119.025872 33.48014, -119.025598 33.477913, -119.02553 33.475687, -119.026009 33.474659, -119.027241 33.474259, -119.027926 33.473174, -119.027994 33.471518, -119.028336 33.468834, -119.029569 33.466779, -119.03217 33.464436, -119.035182 33.463695, -119.038742 33.464038, -119.040659 33.464951, -119.041343 33.464666, -119.045108 33.462268, -119.047162 33.461411, -119.049626 33.461468, -119.051406 33.46221, -119.052365 33.463237, -119.052091 33.465123, -119.050243 33.466208, -119.044287 33.468092, -119.045861 33.469918, -119.046546 33.47226, -119.045724 33.473916, -119.045314 33.476143, -119.04593 33.47797, -119.048394 33.477628, -119.050927 33.477457, -119.052365 33.477913, -119.052912 33.47917)), ((-119.949708 34.065696, -119.947429 34.068219, -119.94471 34.070137, -119.943807 34.07217, -119.940868 34.076494, -119.938528 34.081727, -119.937743 34.084062, -119.93384 34.087776, -119.928852 34.090778, -119.922903 34.092635, -119.914135 34.093764, -119.907234 34.093336, -119.902883 34.092195, -119.90063 34.091272, -119.889011 34.090333, -119.884442 34.09123, -119.879558 34.091086, -119.876618 34.090291, -119.875964 34.089979, -119.867645 34.088954, -119.858095 34.087962, -119.850494 34.08654, -119.846214 34.085293, -119.843026 34.08415, -119.836087 34.081527, -119.828971 34.080272, -119.821315 34.076679, -119.815266 34.074257, -119.813945 34.072885, -119.813067 34.07168, -119.811705 34.070307, -119.809755 34.070802, -119.806698 34.072529, -119.795301 34.07393, -119.785493 34.074434, -119.781649 34.074088, -119.77781 34.073308, -119.772421 34.073491, -119.766696 34.074708, -119.762629 34.076063, -119.757891 34.075981, -119.753968 34.075467, -119.750965 34.074449, -119.74873 34.07392, -119.745124 34.070991, -119.741712 34.068907, -119.73704 34.066271, -119.733047 34.065091, -119.728186 34.064711, -119.725607 34.064992, -119.721812 34.064318, -119.718877 34.063449, -119.716323 34.061641, -119.714784 34.060414, -119.710985 34.060077, -119.706585 34.058791, -119.70142 34.05652, -119.693142 34.051256, -119.690258 34.049748, -119.686908 34.046179, -119.685534 34.044886, -119.682975 34.043481, -119.679813 34.041296, -119.676948 34.038237, -119.675492 34.03701, -119.67101 34.035823, -119.667345 34.03467699999999, -119.661536 34.035128, -119.654779 34.03621, -119.65143 34.035976, -119.648212 34.035069, -119.645 34.033657, -119.639988 34.032498, -119.63407 34.031801, -119.630837 34.03214, -119.629275 34.03290000000001, -119.629106 34.036571, -119.628737 34.03987, -119.62795 34.043872, -119.625959 34.048597, -119.621638 34.052953, -119.618704 34.055143, -119.613245 34.056572, -119.610415 34.059837, -119.60703 34.062526, -119.602369 34.064366, -119.599582 34.064878, -119.59624 34.067299, -119.590809 34.069467, -119.584667 34.070722, -119.581171 34.070222, -119.577168 34.06871, -119.572464 34.070615, -119.568339 34.071653, -119.562092 34.071967, -119.555777 34.071407, -119.551097 34.069486, -119.546467 34.066894, -119.542811 34.063942, -119.540872 34.061877, -119.531732 34.059411, -119.525433 34.057979, -119.517871 34.055023, -119.512778 34.051419, -119.507891 34.047548, -119.505235 34.04514, -119.502757 34.041727, -119.501294 34.037787, -119.501163 34.031376, -119.503507 34.02613, -119.509136 34.01947, -119.513428 34.015618, -119.51661 34.013131, -119.522759 34.011275, -119.524506 34.008036, -119.527001 34.005642, -119.527914 34.000003, -119.543333 34.000173, -119.545191 33.998451, -119.549562 33.99365, -119.559233 33.991339, -119.566225 33.991521, -119.570377 33.992065, -119.575895 33.991023, -119.580539 33.989754, -119.584309 33.987218, -119.587915 33.985723, -119.593269 33.985315, -119.602175 33.984907, -119.607529 33.9845, -119.611463 33.983865, -119.617582 33.984318, -119.622281 33.985224, -119.62441 33.985314, -119.63102 33.983955, -119.636265 33.983729, -119.642383 33.984227, -119.647737 33.984318, -119.655931 33.983729, -119.661777 33.982279, -119.663853 33.979516, -119.666912 33.976753, -119.672484 33.974443, -119.678712 33.973174, -119.682586 33.971951, -119.685208 33.970185, -119.687611 33.969279, -119.69138 33.968509, -119.695039 33.966516, -119.696569 33.964386, -119.698753 33.963662, -119.702467 33.964251, -119.704707 33.964477, -119.707929 33.96339, -119.709786 33.960627, -119.711151 33.958135, -119.715139 33.956731, -119.719126 33.955598, -119.722403 33.955553, -119.724915 33.956323, -119.72852 33.957727, -119.735784 33.958633, -119.741408 33.959267, -119.746651 33.959358, -119.751948 33.957682, -119.755334 33.955779, -119.759867 33.95564299999999, -119.766694 33.957002, -119.773029 33.957274, -119.779528 33.956957, -119.786792 33.956232, -119.790997 33.956187, -119.792308 33.956459, -119.796731 33.958089, -119.800172 33.958225, -119.802794 33.958769, -119.806289 33.958633, -119.811204 33.957591, -119.813771 33.955733, -119.8159 33.952653, -119.817593 33.94989, -119.819942 33.946583, -119.822181 33.945586, -119.825676 33.945813, -119.829663 33.948078, -119.8307 33.950886, -119.82999 33.952744, -119.827915 33.955145, -119.826768 33.958769, -119.82868 33.960218, -119.834742 33.962891, -119.839547 33.964703, -119.842496 33.96425, -119.845172 33.963298, -119.849159 33.963208, -119.85118 33.963661, -119.852709 33.96434, -119.856477 33.967511, -119.858777 33.969414, -119.869211 33.97562, -119.872817 33.975348, -119.87675 33.97648, -119.880793 33.979878, -119.888004 33.985948, -119.899094 33.993377, -119.903822 33.996946, -119.907873 34.000004, -119.90687 34.002105, -119.907339 34.009034, -119.906493 34.013945, -119.90428 34.018408, -119.899521 34.02325, -119.906718 34.031209, -119.918432 34.039573, -119.924735 34.03849, -119.930294 34.039507, -119.937214 34.042109, -119.942034 34.044959, -119.947079 34.050186, -119.94915 34.053782, -119.950642 34.059281, -119.949708 34.065696)), ((-120.271089 34.000018, -120.270728 34.001945, -120.270212 34.005189, -120.268946 34.008288, -120.267431 34.010748, -120.265909 34.013304, -120.263633 34.014775, -120.261604 34.016159, -120.260348 34.017254, -120.257635 34.018057, -120.25523 34.018846, -120.254474 34.01962, -120.252827 34.02088, -120.250962 34.022397, -120.249708 34.02313, -120.24847 34.023512, -120.246156 34.024451, -120.244699 34.024964, -120.241752 34.025676, -120.238727 34.026035, -120.236919 34.026308, -120.235525 34.026095, -120.234257 34.026377, -120.23297 34.026589, -120.230552 34.026795, -120.228737 34.026897, -120.226524 34.027065, -120.223768 34.026988, -120.220875 34.027047, -120.217529 34.0267, -120.214967 34.026312, -120.212413 34.025814, -120.209916 34.025027, -120.20722 34.024509, -120.205356 34.02393, -120.19952 34.022629, -120.194328 34.023033, -120.188815 34.023671, -120.184427 34.024075, -120.179679 34.024076, -120.173844 34.024948, -120.168854 34.027794, -120.165234 34.032178, -120.161935 34.036863, -120.155978 34.039474, -120.149458 34.041382, -120.142091 34.04282, -120.135811 34.042721, -120.130256 34.041983, -120.125963 34.041364, -120.121088 34.039919, -120.118829 34.040128, -120.116973 34.040571, -120.112447 34.038872, -120.108851 34.037707, -120.106389 34.037715, -120.101707 34.037427, -120.096742 34.037342, -120.093634 34.037219, -120.087662 34.038851, -120.085328 34.041347, -120.081215 34.044151, -120.077063 34.047323, -120.073273 34.050059, -120.067545 34.052462, -120.059918 34.054367, -120.051925 34.054659, -120.04292 34.053844, -120.035208 34.051983, -120.029552 34.048502, -120.02543 34.045116, -120.022962 34.040786, -120.022675 34.036786, -120.023195 34.032145, -120.023191 34.028144, -120.023669 34.023267, -120.025316 34.016909, -120.028458 34.011757, -120.027285 34.010045, -120.026961 34.009038, -120.026797 34.006517, -120.025746 34.005007, -120.024411 34.001951, -120.02332 34.00001, -120.000932 33.996263, -119.999109 33.996306, -119.994727 33.997263, -119.987899 33.999197, -119.983371 33.99928, -119.975747 33.998652, -119.968297 33.995306, -119.963403 33.991453, -119.961047 33.985915, -119.959999 33.981737, -119.960117 33.975758, -119.960497 33.970724, -119.959539 33.966178, -119.955885 33.960994, -119.950202 33.95169, -119.948961 33.949657, -119.947933 33.94249, -119.950059 33.93509, -119.954235 33.930166, -119.963435 33.92621, -119.970596 33.925318, -119.982129 33.925786, -119.991817 33.925662, -119.996026 33.925104, -120.000891 33.922543, -120.000887 33.935141, -120.003821 33.935099, -120.008308 33.934972, -120.01269 33.935268, -120.014728 33.933872, -120.016258 33.930404, -120.021915 33.926808, -120.028593 33.923001, -120.035219 33.920168, -120.041438 33.916107, -120.043986 33.913527, -120.046739 33.911708, -120.048191 33.911477, -120.058156 33.909889, -120.061107 33.909424, -120.064572 33.90917, -120.069108 33.908578, -120.073032 33.905955, -120.076548 33.904517, -120.086688 33.904686, -120.090408 33.904728, -120.095861 33.903756, -120.098511 33.902275, -120.101008 33.899864, -120.102282 33.897369, -120.103046 33.894281, -120.105594 33.892166, -120.110945 33.890517, -120.114155 33.889755, -120.115837 33.889586, -120.122105 33.890432, -120.128224 33.892242, -120.128679 33.892377, -120.142183 33.899441, -120.161344 33.910015, -120.168535 33.91416, -120.171084 33.91534499999999, -120.177304 33.918855, -120.181993 33.92042, -120.186021 33.922408, -120.186275 33.924693, -120.185562 33.927442, -120.186785 33.930276, -120.19066 33.93772, -120.193111 33.942373, -120.193111 33.942753, -120.195916 33.94618, -120.198771 33.946687, -120.212387 33.94656, -120.215039 33.946518, -120.216976 33.947871, -120.217537 33.950282, -120.216976 33.952397, -120.214835 33.953201, -120.207389 33.953708, -120.209123 33.956119, -120.211928 33.961364, -120.213356 33.966863, -120.21377 33.968682, -120.233059 33.979351, -120.250969 33.990211, -120.264073 33.996764, -120.270219 33.997607, -120.271082 34.000006, -120.271089 34.000018)), ((-120.397645 34.10515, -120.397232 34.105379, -120.396984 34.105356, -120.396654 34.105195, -120.396654 34.104898, -120.396792 34.104783, -120.397287 34.1046, -120.397562 34.104715, -120.397645 34.10515)), ((-120.469274 34.039217, -120.465489 34.045081, -120.463514 34.047536, -120.458741 34.047808, -120.450018 34.043445, -120.4436 34.042081, -120.438663 34.045354, -120.44146 34.048899, -120.446069 34.052172, -120.446727 34.055172, -120.44666 34.056656, -120.446562 34.058854, -120.443933 34.059462, -120.439485 34.06049, -120.433067 34.057627, -120.429282 34.055036, -120.426155 34.056945, -120.425167 34.059809, -120.42023 34.061854, -120.415622 34.060763, -120.409368 34.058172, -120.405747 34.055172, -120.398506 34.053672, -120.392416 34.054763, -120.385504 34.058036, -120.378427 34.062945, -120.371021 34.070036, -120.372996 34.071127, -120.3753 34.072763, -120.375465 34.075354, -120.37349 34.077945, -120.36773 34.080263, -120.361147 34.07780899999999, -120.353576 34.0714, -120.350778 34.06499, -120.350285 34.061445, -120.347158 34.058581, -120.342056 34.057627, -120.339916 34.059399, -120.338435 34.061581, -120.33251 34.062127, -120.328561 34.060763, -120.327079 34.057218, -120.328396 34.053945, -120.327573 34.052718, -120.325434 34.050672, -120.309305 34.039217, -120.302228 34.032127, -120.299924 34.029263, -120.29367 34.025717, -120.290543 34.023399, -120.290872 34.020263, -120.294987 34.018217, -120.300912 34.016717, -120.317205 34.01549, -120.340245 34.016036, -120.347981 34.015763, -120.350449 34.014263, -120.351272 34.012217, -120.356374 34.010717, -120.363286 34.010445, -120.370363 34.012354, -120.379909 34.016308, -120.386163 34.020808, -120.395873 34.023945, -120.406241 34.026808, -120.411014 34.026808, -120.415293 34.02449, -120.420065 34.022172, -120.427142 34.022036, -120.4357 34.023126, -120.441954 34.02299, -120.450841 34.02299, -120.456766 34.023536, -120.462033 34.026126, -120.465489 34.030627, -120.467464 34.03349, -120.469274 34.039217)))')

G = ox.graph_from_polygon(polygon_to_process, network_type='drive_service',truncate_by_edge=True, simplify=True)
G_proj = ox.project_graph(G)
nodes_proj = ox.graph_to_gdfs(G_proj, edges=False)
graph_area_m = nodes_proj.unary_union.convex_hull.area
stats = ox.basic_stats(G_proj, area=graph_area_m, clean_intersects=True, circuity_dist='euclidean')    

### EXAMPLE 2: VERY FEW ROADS
# this polygon (census tract 06029004601, contains North Kern State Prison) should contain a single, L-shaped road.
polygon_to_process = wkt.loads('POLYGON ((-119.321192 35.79022, -119.320489 35.790219, -119.320424 35.79022, -119.303665 35.79034499999999, -119.303566 35.786846, -119.303578 35.775874, -119.303577 35.775827, -119.306677 35.775829, -119.31196 35.775832, -119.320331 35.7758, -119.320879 35.775798, -119.320967 35.775798, -119.320974 35.775899, -119.321043 35.780536, -119.321139 35.786793, -119.321192 35.79022))')
G = ox.graph_from_polygon(polygon_to_process, network_type='drive_service',truncate_by_edge=True, simplify=True)
G_proj = ox.project_graph(G)
nodes_proj = ox.graph_to_gdfs(G_proj, edges=False)
graph_area_m = nodes_proj.unary_union.convex_hull.area
stats = ox.basic_stats(G_proj, area=graph_area_m, clean_intersects=True, circuity_dist='euclidean')    


```

**Comment by gboeing** [comment]
Resolution in #569.

> basic_stats() crashes, alternately with "ValueError: not enough values to unpack (expected 2, got 0)" for zero roads

This bug was in the `consolidate_intersections` function, which the `basic_stats` function uses. Fixed in b100eec.

> or with "ZeroDivisionError: float division by zero" for certain census tracts that contain very few roads that do not enclose any area

OSMnx is behaving correctly in this second case. You passed it `area=graph_area_m` where `graph_area_m=0` in your code, resulting in division by zero. If you want to pass the `area` argument, it must have a value greater than zero to be meaningful. Otherwise, just don't pass that argument and everything runs fine here. Clarified docstring accordingly in 10eca7b.
