### ISSUE TITLE
Shapely/polygonize does not return any polygon with data coming from OSMnx?

### ISSUE THREAD

**Issue by PatGendre** [gboeing/osmnx#571]
**Problem description**
  - What did you do?
I am working on road network analysis tool.   
I use OSMnx so as to clean the network topology, and them I pass the data as a geodataframe to shapely so as to derive the "blocks" with the polygonize method.   
I have no clue why polygonize returns no polygon although I tested with different data?   
Note that with OSM data read from pyrosm instead of osmnx, polygonize seems to work (polygons are found).   
Below is an extract of my notebook tests.
  - What did you expect to happen?
I expect to get the polygons extracted from the linestring list.   
  - And what actually happened instead?
The result returned by shapely's polygonize is empty. All edges are considered empty (as returned by the polygonize_full method)   
If I load the OSM data via pyrosm instead of OSMnx, polygonize returns some polygons - and also some invalid edges but not all (but to my knowledge pyrosm does NOT clean the graph, which is why I'd prefer to use OSMnx)   
Thanks for your help   

**Environment information**
  - What operating system are you using?
ubuntu 18/04
  - What Python version are you using?
3.8.5
  - What OSMnx version are you using?
0.16.0
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
# paste the output of your Python packages/versions here between these two "details" tags
conda list
# packages in environment at /home/patgendre/miniconda3/envs/omi:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py38h7b6447c_1    anaconda
async_generator           1.10                       py_0    anaconda
attrs                     20.2.0                     py_0    anaconda
backcall                  0.2.0                      py_0    anaconda
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0    anaconda
boost-cpp                 1.74.0               h9359b55_0    conda-forge
branca                    0.4.1                      py_0    conda-forge
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.0           py38h2e261b9_0  
cfitsio                   3.470                hb7c8383_2  
chardet                   3.0.4           py38h32f6830_1007    conda-forge
click                     7.1.2                      py_0  
click-plugins             1.1.1                      py_0  
cligj                     0.5.0                    py38_0  
cryptography              3.1.1            py38h766eaa4_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cykhash                   1.0.2            py38h950e882_1    conda-forge
cython                    0.29.21          py38h950e882_0    conda-forge
decorator                 4.4.2                      py_0    anaconda
defusedxml                0.6.0                      py_0    anaconda
descartes                 1.1.0                      py_4    conda-forge
entrypoints               0.3                      py38_0    anaconda
expat                     2.2.9                he6710b0_2  
fiona                     1.8.17           py38h676c6b2_0    conda-forge
folium                    0.11.0                     py_0    conda-forge
fontconfig                2.13.1            h1056068_1002    conda-forge
freetype                  2.10.2               h5ab3b9f_0  
freexl                    1.0.5                h14c3975_0  
gdal                      3.1.2            py38hb61cb63_1    conda-forge
geopandas                 0.8.1                      py_0  
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.6.0                ha04d9d0_1    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.63.1               h5a9c865_0  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        1.7.0                    py38_0    anaconda
importlib_metadata        1.7.0                         0    anaconda
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py38h5ca1d4c_0    anaconda
ipython                   7.18.1           py38h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py38_0    anaconda
jedi                      0.17.2                   py38_0    anaconda
jinja2                    2.11.2                     py_0    anaconda
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json-c                    0.13.1               h1bed415_0  
jsonschema                3.2.0                    py38_0    anaconda
jupyter_client            6.1.7                      py_0    anaconda
jupyter_core              4.6.3                    py38_0    anaconda
jupyterlab_pygments       0.1.1                      py_0    anaconda
kealib                    1.4.13               h33137a7_1    conda-forge
kiwisolver                1.2.0            py38hbf85e49_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdap4                   3.20.6               h1d1bd15_1    conda-forge
libedit                   3.1.20191231         h14c3975_1    anaconda
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgdal                   3.1.2                hb2a6f5f_1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h74f7ee3_1012    conda-forge
libnetcdf                 4.7.4           nompi_h84807e1_105    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libpng                    1.6.37               hbc83047_0  
libpq                     12.3                 h5513abc_0    conda-forge
libsodium                 1.0.18               h7b6447c_0    anaconda
libspatialindex           1.9.3                he6710b0_0  
libspatialite             4.3.0a            h57f1b35_1039    conda-forge
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               h68273f3_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1            py38h7b6447c_0    anaconda
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py38h91b0d89_0    conda-forge
mistune                   0.8.4           py38h7b6447c_1000    anaconda
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
munch                     2.5.0                      py_0  
nbclient                  0.5.0                      py_0    anaconda
nbconvert                 6.0.6                    py38_0    anaconda
nbformat                  5.0.7                      py_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
nest-asyncio              1.4.0                      py_1    anaconda
networkx                  2.5                        py_0    conda-forge
notebook                  6.1.1                    py38_0    anaconda
numpy                     1.19.1           py38hbc911f0_0  
numpy-base                1.19.1           py38hfa32c7d_0  
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
osmnx                     0.16.0             pyh9f0ad1d_0    conda-forge
packaging                 20.4                       py_0    anaconda
pandas                    1.1.1            py38he6710b0_0  
pandoc                    2.10.1                        0    anaconda
pandocfilters             1.4.2                    py38_1    anaconda
parso                     0.7.0                      py_0    anaconda
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0                    py38_0    anaconda
pickleshare               0.7.5                 py38_1000    anaconda
pillow                    7.2.0            py38h9776b28_1    conda-forge
pip                       20.2.2                   py38_0    anaconda
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.89.0               h4190859_1    conda-forge
poppler-data              0.4.9                         0  
postgresql                12.3                 h8573dbc_0    conda-forge
proj                      7.1.0                h966b41f_1    conda-forge
prometheus_client         0.8.0                      py_0    anaconda
prompt-toolkit            3.0.7                      py_0    anaconda
ptyprocess                0.6.0                    py38_0    anaconda
pycparser                 2.20                       py_2    anaconda
pygeos                    0.8              py38hc7361b7_0    conda-forge
pygments                  2.7.1                      py_0    anaconda
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7                      py_0    anaconda
pyproj                    2.6.1.post1      py38h8e47818_1    conda-forge
pyrobuf                   0.9.3            py38h950e882_0    conda-forge
pyrosm                    0.5.3            py38h950e882_1    conda-forge
pyrsistent                0.17.3           py38h7b6447c_0    anaconda
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.5           h1103e12_9_cpython    conda-forge
python-dateutil           2.8.1                      py_0    anaconda
python-rapidjson          0.9.1            py38he1b5a44_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0  
pyzmq                     19.0.2           py38he6710b0_1    anaconda
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4                    py38_1  
scikit-learn              0.23.2           py38h0573a6f_0  
scipy                     1.5.2            py38h0b6359f_0  
send2trash                1.5.0                    py38_0    anaconda
setuptools                49.6.0                   py38_1    anaconda
shapely                   1.7.1            py38hc7361b7_0    conda-forge
six                       1.15.0                     py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
tbb                       2020.2               hc9558a2_0    conda-forge
terminado                 0.8.3                    py38_0    anaconda
testpath                  0.4.4                      py_0    anaconda
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    2.0.8                h3effe38_1    conda-forge
tk                        8.6.10               hbc83047_0    anaconda
tornado                   6.0.4            py38h7b6447c_1    anaconda
traitlets                 5.0.4                    py38_0    anaconda
tzcode                    2020a                h516909a_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wcwidth                   0.2.5                      py_0    anaconda
webencodings              0.5.1                    py38_1    anaconda
wheel                     0.35.1                     py_0    anaconda
xerces-c                  3.2.3                hfe33f54_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h7b6447c_0    anaconda
zeromq                    4.3.2                he6710b0_3    anaconda
zipp                      3.1.0                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.5                h6597ccf_2    conda-forge

conda info:
     active environment : omi
    active env location : /home/patgendre/miniconda3/envs/omi
            shell level : 2
       user config file : /home/patgendre/.condarc
 populated config files : 
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /home/patgendre/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/patgendre/miniconda3/pkgs
                          /home/patgendre/.conda/pkgs
       envs directories : /home/patgendre/miniconda3/envs
                          /home/patgendre/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.6 Linux/5.4.0-48-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

</details>

**Provide a complete minimal reproducible example**

This is an extract of commands launch in a notebook, the notebook car be viewed here : https://gitlab.com/open-mobility-indicators/omi-scripts/-/blob/master/nb-OMI.ipynb 

```python
import pandas as pd
import geopandas as gpd
from pyrosm import OSM
import shapely
from shapely.ops import polygonize
from shapely.ops import polygonize_full
import osmnx as ox
# I import OSM data for a small location in France
G = ox.graph_from_place('Saint-Antonin-sur-Bayon, France')
# data looks clean
ox.plot_graph(G,figsize=(20,20))
sasb=ox.utils_graph.graph_to_gdfs(G,nodes=False,edges=True,fill_edge_geometry=True)
result, dangles, cuts, invalids = polygonize_full(sasb.geometry)
blocks=list(result)
invalidways=list(invalids)
cutways=list(cuts)
dangleways=list(dangles)
print(len(blocks),len(dangleways),len(cutways),len(invalidways))
# here I see all the 608 edges are invalid. But when I export the geodataframe to a shapefile and open it in QGIS, the edges seem Ok
# if use polygonize instead of polygonize_full the result is empty (no polygons, ie no "blocks" found)


```

**Comment by AtelierLibre** [comment]
@PatGendre I don't know how pyrosm creates the edges that you need but I don't think this is a bug with OSMnx. If you look at this answer on StackOverflow I think it does pretty much what you are trying to do (though with polygonize rather than polygonize_full):

https://stackoverflow.com/a/63919176/12834132

I suspect that the step you are missing is to convert the graph to undirected first. If you don't do this the edges geodataframe contains duplicate edges that cause the polygonization to fail.

**Comment by PatGendre** [comment]
@AtelierLibre Thanks a lot for your answer, I cannot test right now but I will test converting the graph to undirected and tell you.   

I'm pretty sure this will solve the isssue, which was admittedly not a bug, but I could not tag it as a question :-)

**Comment by PatGendre** [comment]
@AtelierLibre thanks again, with an undirected graph, it works fine :-)

**Comment by AtelierLibre** [comment]
@PatGendre great, glad that helped.
