### ISSUE TITLE
graph_from_place: getting city in stead of state

### ISSUE THREAD

**Issue by matiasitalia** [gboeing/osmnx#573]
Hi Geoff,

I have a problem running as "graph_from_place", in a particular state (or department) of Uruguay. When I run:
#graph = ox.graph_from_place("Colonia, Uruguay", network_type='drive', simplify=False)
I get the city Colonia del Sacramento, a city of Colonia, in stead of the entire department of Colonia.
I changed the line with "Colonia (State)", "Colonia (Department)", "State of Colonia", "Department of Colonia", but I get the city, or OSM dont find it.

1-It is a bug or a problem of OSM?
2-There is a way to get all divisions of a country? 

Because I want to get country data of roads' length by type (and surface, lanes, etc) in multiple countries, and when I use "graph_from_place" in countries, I run out of memory.
Im using ox.utils.config(useful_tags_way=useful_tags_way, timeout=1000, use_cache=True, log_console=True),  network_type='drive', simplify=False. 
3-It's Ok or I have to change some part?

4-Or It's possible to get edges in a more aggregated way that don't need too memory?

Thanks and sorry if this is not the place for the issue,

Matias

**Comment by gboeing** [comment]
1. Not a bug.

2. Yes. See [the docs](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples). In particular [this example](https://github.com/gboeing/osmnx-examples/blob/v0.16.0/notebooks/03-graph-place-queries.ipynb) demonstrates how to query specific political boundaries at different levels and how to disambiguate them.

3. If you want to model every street segment in a country as graph edges, you will need enough RAM to do so. No way around it.

4. What do you mean by aggregated? Best to ask "how to" usage questions on StackOverflow, as per the Github issue template. If you want to only get, say, just the highways in a country, that has been asked before and there's example code out there. See for example this [usage example](https://github.com/gboeing/osmnx-examples/blob/v0.16.0/notebooks/08-custom-filters-infrastructure.ipynb) in Belgium.
