### ISSUE TITLE
load graphML - identify attributes to convert to float. 

### ISSUE THREAD

**Issue by d-wasserman** [gboeing/osmnx#575]
## Problem Statement

Around the [private methods for converting the datatypes of a few attributes on load](https://github.com/gboeing/osmnx/blob/8653183bb966cfa826e92f1c95b11efa51f99572/osmnx/io.py#L215), there are only  a small subset of attributes that are converted. If someone adds attributes or custom edge weights, they come in as objects by default. There is also no way to adjust which attributes have conversions attempted. 

### Solution

It would be great to see two possible solutions:
1. Ideally, data types of attributes converted to graphML could be preserved. This might be hard to achieve in practice. At minimum, a dictionary could be passed as an optional attribute to the load function. 
2. Quick fix, perhaps the set being used to determine attributes to attempt float conversions with could be a parameter. 

A clear and concise description of what you want to change in OSMnx and how you plan to implement it.

### Alternatives Considered

I think the easiest approach outside of this is converting the nodes & edges to GDF, and doing .astype() conversions there. 

### Minimum Viable Solution
Example with nodes. Granted, edges could be similar, but is clearly more complicated. These changes would be passed up to the load graphML method (for nodes/edges separately). Notebook examples have graphML as the preferred option, so I want to find ways to address limitations. 

```
def _convert_node_attr_types(G, node_type, num_attr = {"elevation", "elevation_res", "lat", "lon", "x", "y"}):
    """
    Convert graph nodes' attributes' types from string to numeric.
    Parameters
    ----------
    G : networkx.MultiDiGraph
        input graph
    node_type : type
        convert node ID (osmid) to this type
    num_attr : set
        attributes to attempt a cast to float for
    Returns
    -------
    G : networkx.MultiDiGraph
    """
    for _, data in G.nodes(data=True):
        # convert node ID to user-requested type
        data["osmid"] = node_type(data["osmid"])

        # convert numeric node attributes from string to float
        for attr in num_attr:
            if attr in data:
                data[attr] = float(data[attr])

    return G
```

**Comment by gboeing** [comment]
> a dictionary could be passed as an optional attribute to the load function

I think this seems the most straightforward, and could mimic `pandas`'s `dtypes` argument when loading a file as a `DataFrame`. Adding an optional `attr_types` argument to the `load_graphml` function would be a straightforward fix and allow users to specify exactly what they'd like converted and how, upon load.

**Comment by d-wasserman** [comment]
Agreed. I tried this on my end as an "extension" of the library, and I think the dtypes argument would be an ideal solution. If we could store it as a global graph attribute I think similarly to how the CRS (I think) is in the save method that would abstract a lot of this away, but I am not sure this is necessary. 

For now, I think providing the dtypes options to the load method makes sense. Do you have efficiency concerns with converting to GDF if someone uses the dtypes argument (IE converting to GDF theoretically)? Or do you want to keep it pure python?

I have some time to kill, so happy to kick around a PR if this is something you are interested in. I have my own workaround for now though. Just wanted to raise this as an issue as it is the preferred approach for graph loading for the library.

**Comment by gboeing** [comment]
> Do you have efficiency concerns with converting to GDF if someone uses the dtypes argument (IE converting to GDF theoretically)? Or do you want to keep it pure python?

Can you clarify what you mean by that? I didn't understand.

And yes, a PR would be great. Thanks!

**Comment by d-wasserman** [comment]
Sure sorry. If we use the dtypes as a passed parameter, my assumption was we would use the graph_to_gdfs function to convert additional graph attributes to desired dtypes. Currently, the private conversion functions are using pure python to cast to float, but in my head the easy way to implement this is:
1. If there is a passed dtypes parameter that is not None, convert the graph to gdf. 
2. Use astype() methods to convert to the appropriate dtype
3. Convert gdfs back to a graph

Did you have another approach in mind I guess is my question?

**Comment by gboeing** [comment]
I think something like this would be straightforward and efficient:

```python
node_dtypes = None #default argument

if node_dtypes is None:
    # default node_dtypes to mimic current functionality
    node_dtypes = {"elevation": float,
                   "elevation_res": float,
                   "lat": float,
                   "lon": float,
                   "x": float,
                   "y": float}

for attr_name, dtype in node_dtypes.items():
    attrs = nx.get_node_attributes(G, attr_name)
    attrs_converted = {node: dtype(value) for node, value in attrs.items()}
    nx.set_node_attributes(G, attrs_converted, name=attr_name)
```

...and similar for the edges.

**Comment by d-wasserman** [comment]
Something like this makes sense. Let me test something like this out. 

I think we might want to assume node_dtypes will always be included in addition to passed parameters. Easy to accommodate with a dictionary update method.

**Comment by gboeing** [comment]
@d-wasserman just curious, any update on this?

**Comment by d-wasserman** [comment]
I did start working on this on my fork, but other timelines got in the way. I can reprioritize it this week if you want it in an update.

**Comment by d-wasserman** [comment]
@gboeing - point of clarification 
Is there any reason why length is converted to float separately from the rest off the attributes on line 285 of io.py?
```
        # parse length to float: should always have only 1 value
        data["length"] = float(data["length"])
```

**Comment by gboeing** [comment]
Yeah it can be consolidated. Thanks!

**Comment by d-wasserman** [comment]
Excellent. This is my [first draft](https://github.com/d-wasserman/osmnx/blob/master/osmnx/io.py). Going to do some actual tests later.

**Comment by gboeing** [comment]
Great! Could you open a PR for your work in progress?

**Comment by d-wasserman** [comment]
Will do after some minor doc string edits. Thanks.
