### ISSUE TITLE
graph_from_gdfs function is slow

### ISSUE THREAD

**Issue by Labulitiolle** [gboeing/osmnx#576]
https://github.com/gboeing/osmnx/blob/8653183bb966cfa826e92f1c95b11efa51f99572/osmnx/utils_graph.py#L104

Dear @gboeing ,
First of all, thank you for this package. I had a lot of fun playing with it. 
Now I notice that this function is pretty slow when dealing with large networks. I have written down a faster version of it (3x faster) based on the netwrokx `from_pandas_edgelist`. Would you be interested, in seeing the PR?

Best,
Yann

**Comment by gboeing** [comment]
@Labulitiolle yes, thanks!
