### ISSUE TITLE
buildings_from_polygon returning only first API request

### ISSUE THREAD

**Issue by kaseyklimes** [gboeing/osmnx#58]
Trying to run some bulk downloads of building data using `buildings_from_polygon` and only getting data from the first API request. 

Line 104 in buildings.py 
`            response_jsons.append(response_json)`
appears to be appending the list properly but not returning the final iteration of `response_jsons`

I'm on Mac OS 10.12.3, using python 2.7.9, OSMnx 0.5.1

My code:
```python

    cbsa = gpd.read_file('cbsa.shp')
    metro = cbsa[(cbsa['name']=='Atlanta')]
    polygon = metro['geometry'].iloc[0]
    G = ox.buildings_from_polygon(polygon)```

**Comment by gboeing** [comment]
Hmmm... can you provide a working example without that shapefile, so I can re-create it?

**Comment by kaseyklimes** [comment]
Same problem here (the polygon is roughly the same size as the shapefile geometry):

```
shape = Polygon([(-85, 33), (-85, 34.5), (-83.5, 34.5), (-83.5, 33)])
G = ox.buildings_from_polygon(shape)

**Comment by gboeing** [comment]
Awesome, thanks! Yes, found the bug. Will fix it shortly.
