### ISSUE TITLE
Should the use_cache setting = True by default?

### ISSUE THREAD

**Issue by gboeing** [gboeing/osmnx#583]
Currently `use_cache=False` by default. Should it be set to `True`? I think so. Changing this default would be a nudge toward good neighbor behavior with the Overpass server by reducing the number of duplicate calls made by a single user re-running code. And it could be easily turned off with `ox.config(use_cache=False)`.

**Comment by d-wasserman** [comment]
I think so as well. When reviewing the library that was a concern I had about its use in practice. It depends a lot of overpass and it would make sense to have it cache by default. That said, I expect some server based users might experience issues with cache build ups on server machines if it is not flagged. I am not sure how big of a problem that really is though.

**Comment by gboeing** [comment]
Resolved by 7455fae.

**Comment by gboeing** [comment]
A message reporting the current response caching status is now automatically logged (to terminal and/or file) when `ox.config()` is called, as of 5a3188f.
