### ISSUE TITLE
TypeError: object of type 'method' has no len() in the create_graph module

### ISSUE THREAD

**Issue by BenjaminT17** [gboeing/osmnx#585]
**Problem description**
I attempted to run the ox.graph_from_point example included in your Jupiter notebook example and ran into the TypeError TypeError: object of type 'method' has no len() in the create_graph module. 

**Environment information**
I am currently using Python Version 3.7.6 and OSMnx version '0.16.1'
  - The environment's packages are included below

<details>
# packages in environment at /opt/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  2020.02                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.12                   py37_0  
anaconda-project          0.8.4                      py_0  
anytree                   2.8.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
applaunchservices         0.2.1                      py_0  
appnope                   0.1.0                    py37_0  
appscript                 1.1.0            py37h1de35cc_0  
apscheduler               3.6.3                    pypi_0    pypi
argh                      0.26.2                   py37_0  
argparse                  1.4.0                    pypi_0    pypi
asgiref                   3.2.10                   pypi_0    pypi
asn1crypto                1.3.0                    py37_0  
astroid                   2.3.3                    py37_0  
astropy                   4.0              py37h1de35cc_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.3.0                     py_0  
autopep8                  1.4.4                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.8.2                    py37_0  
bitarray                  1.2.1            py37h1de35cc_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
blosc                     1.16.3               hd9629dc_0  
bokeh                     1.4.0                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.3.2            py37h776bbcc_0  
branca                    0.4.1                    pypi_0    pypi
brotli                    1.0.7                    pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2020.1.1                      0  
cached-property           1.5.1                    pypi_0    pypi
cchardet                  2.1.7                    pypi_0    pypi
certifi                   2020.6.20                pypi_0    pypi
cffi                      1.14.0           py37hb5b8e2f_0  
chardet                   3.0.4                 py37_1003  
click                     7.0                      py37_0  
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.5.0                    pypi_0    pypi
cloudpickle               1.3.0                      py_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.3                      py_0  
conda                     4.8.2                    py37_0  
conda-build               3.18.11                  py37_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.6.0            py37h1de35cc_0  
conda-verify              3.4.2                      py_1  
configparser              5.0.1                    pypi_0    pypi
contextlib2               0.6.0.post1                py_0  
coverage                  5.3                      pypi_0    pypi
crayons                   0.4.0                    pypi_0    pypi
cryptography              2.8              py37ha12b0ac_0  
curl                      7.68.0               ha441bb4_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.15          py37h0a44026_0  
cytoolz                   0.10.1           py37h1de35cc_0  
dash                      1.14.0                   pypi_0    pypi
dash-bootstrap-components 0.10.3                   pypi_0    pypi
dash-core-components      1.10.2                   pypi_0    pypi
dash-daq                  0.5.0                    pypi_0    pypi
dash-extensions           0.0.31                   pypi_0    pypi
dash-html-components      1.0.3                    pypi_0    pypi
dash-leaflet              0.1.3                    pypi_0    pypi
dash-renderer             1.6.0                    pypi_0    pypi
dash-table                4.9.0                    pypi_0    pypi
dask                      2.11.0                     py_0  
dask-core                 2.11.0                     py_0  
dbus                      1.13.12              h90a0687_0  
decorator                 4.4.1                      py_0  
defusedxml                0.6.0                      py_0  
deprecated                1.2.10                   pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
diff-match-patch          20181111                   py_0  
distlib                   0.3.1                    pypi_0    pypi
distributed               2.11.0                   py37_0  
dj-database-url           0.5.0                    pypi_0    pypi
django                    3.1.1                    pypi_0    pypi
django-heroku             0.3.1                    pypi_0    pypi
docutils                  0.16                     py37_0  
entities                  1.0.0                    pypi_0    pypi
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                h0a44026_0  
fastcache                 1.1.0            py37h1de35cc_0  
filelock                  3.0.12                     py_0  
fiona                     1.8.13.post1             pypi_0    pypi
flake8                    3.7.9                    py37_0  
flask                     1.1.1                      py_0  
flask-caching             1.9.0                    pypi_0    pypi
flask-compress            1.5.0                    pypi_0    pypi
folium                    0.11.0                   pypi_0    pypi
fontawesome               5.10.1.post1             pypi_0    pypi
freetype                  2.9.1                hb4e5f40_0  
fsspec                    0.6.2                      py_0  
future                    0.18.2                   py37_0  
geobuf                    1.1.1                    pypi_0    pypi
geographiclib             1.50                     pypi_0    pypi
geoindex                  0.0.1                    pypi_0    pypi
geojson                   1.3.5                    pypi_0    pypi
geopandas                 0.8.1                    pypi_0    pypi
geopy                     2.0.0                    pypi_0    pypi
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.4.0            py37h1de35cc_0  
glib                      2.63.1               hd977a24_0  
glob2                     0.7                        py_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py37h6ef4df4_2  
greenlet                  0.4.15           py37h1de35cc_0  
gtfs-realtime-bindings    0.0.6                    pypi_0    pypi
gtfspy                    0.0.4                    pypi_0    pypi
gtfstk                    10.0.7                   pypi_0    pypi
gunicorn                  20.0.4                   pypi_0    pypi
h5py                      2.10.0           py37h3134771_0  
haversine                 2.3.0                    pypi_0    pypi
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.1                      py_0  
helpdev                   0.7.1                    pypi_0    pypi
html5lib                  1.0.1                    py37_0  
hypothesis                5.5.4                      py_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
imageio                   2.6.1                    py37_0  
imagesize                 1.2.0                      py_0  
importlib_metadata        1.5.0                    py37_0  
intel-openmp              2019.4                      233  
intervaltree              3.0.2                      py_0  
ipykernel                 5.1.4            py37h39e3cac_0  
ipython                   7.12.0           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   py37_0  
isoweek                   1.3.3                    pypi_0    pypi
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4.1                      py_0  
jedi                      0.14.1                   py37_0  
jinja2                    2.11.1                     py_0  
joblib                    0.14.1                     py_0  
jpeg                      9b                   he5867d9_2  
json2table                1.1.5                    pypi_0    pypi
json5                     0.9.1                      py_0  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.1                    py37_0  
jupyterlab                1.2.6              pyhf63ae98_0  
jupyterlab_server         1.0.6                      py_0  
keyring                   21.1.0                   py37_0  
kiwisolver                1.1.0            py37h0a44026_0  
krb5                      1.17.1               hddcf347_0  
lazy-object-proxy         1.4.3            py37h1de35cc_0  
libarchive                3.3.3                h786848e_5  
libcurl                   7.68.0               h051b688_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
liblief                   0.9.0                h2a1bed3_2  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libspatialindex           1.9.3                h0a44026_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.1.0                hcb84e12_0  
libxml2                   2.9.9                hf6e021a_1  
libxslt                   1.1.33               h33a18ac_0  
llvm-openmp               4.0.1                hcfea43d_1  
llvmlite                  0.31.0           py37h1341992_0  
locket                    0.2.0                    py37_1  
lxml                      4.5.0            py37hef8c89e_0  
lz4-c                     1.8.1.2              h1de35cc_0  
lzo                       2.10                 h362108e_2  
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.3.2                    pypi_0    pypi
matplotlib-scalebar       0.3.1                    pypi_0    pypi
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.0.15           py37h5e564d8_0  
mkl_random                1.1.0            py37ha771720_0  
mock                      4.0.1                      py_0  
more-itertools            8.2.0                      py_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.1                h3018a27_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.6.1            py37h04f5b5a_1  
multipledispatch          0.6.0                    py37_0  
munch                     2.5.0                    pypi_0    pypi
mysql-connector           2.2.9                    pypi_0    pypi
mysql-connector-python    8.0.21                   pypi_0    pypi
mzgtfs                    0.10.4                   pypi_0    pypi
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.4                      py_0  
ncurses                   6.2                  h0a44026_0  
networkx                  1.11                     pypi_0    pypi
nltk                      3.4.5                    py37_0  
nose                      1.3.7                    py37_2  
notebook                  6.0.3                    py37_0  
numba                     0.48.0           py37h6c726b0_0  
numexpr                   2.7.1            py37hce01a72_0  
numpy                     1.19.2                   pypi_0    pypi
numpydoc                  0.9.2                      py_0  
olefile                   0.46                     py37_0  
openpyxl                  3.0.3                      py_0  
openssl                   1.1.1d               h1de35cc_4  
osmnx                     0.16.1                   pypi_0    pypi
osmread                   0.2                      pypi_0    pypi
packaging                 20.1                       py_0  
pandas                    1.1.3                    pypi_0    pypi
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.5.2                      py_0  
partd                     1.1.0                      py_0  
partridge                 1.1.1                    pypi_0    pypi
path                      13.1.0                   py37_0  
path.py                   12.4.0                        0  
pathlib2                  2.3.5                    py37_0  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 h0a44026_0  
peartree                  0.6.3                    pypi_0    pypi
pep8                      1.7.1                    py37_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    7.0.0            py37h4655f20_0  
pip                       20.0.2                   py37_1  
pkginfo                   1.5.0.1                  py37_0  
plotly                    4.9.0                    pypi_0    pypi
plotly-express            0.4.1                    pypi_0    pypi
pluggy                    0.13.1                   py37_0  
ply                       3.11                     py37_0  
prometheus_client         0.7.1                      py_0  
prompt_toolkit            3.0.3                      py_0  
protobuf                  3.0.0b3                  pypi_0    pypi
psutil                    5.6.7            py37h1de35cc_0  
psycopg2                  2.8.6                    pypi_0    pypi
ptyprocess                0.6.0                    py37_0  
py                        1.8.1                      py_0  
py-lief                   0.9.0            py37h1413db1_2  
pycodestyle               2.5.0                    py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycountry                 18.12.8                  pypi_0    pypi
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37h1de35cc_9  
pycurl                    7.43.0.5         py37ha12b0ac_0  
pydocstyle                4.0.1                      py_0  
pyflakes                  2.1.1                    py37_0  
pygit2                    1.2.1                    pypi_0    pypi
pygithub                  1.52                     pypi_0    pypi
pygments                  2.5.2                      py_0  
pyjwt                     1.7.1                    pypi_0    pypi
pylint                    2.4.4                    py37_0  
pylogit                   0.2.2                    pypi_0    pypi
pyobjc                    6.2.2                    pypi_0    pypi
pyobjc-core               6.2.2                    pypi_0    pypi
pyobjc-framework-accounts 6.2.2                    pypi_0    pypi
pyobjc-framework-addressbook 6.2.2                    pypi_0    pypi
pyobjc-framework-adsupport 6.2.2                    pypi_0    pypi
pyobjc-framework-applescriptkit 6.2.2                    pypi_0    pypi
pyobjc-framework-applescriptobjc 6.2.2                    pypi_0    pypi
pyobjc-framework-applicationservices 6.2.2                    pypi_0    pypi
pyobjc-framework-authenticationservices 6.2.2                    pypi_0    pypi
pyobjc-framework-automaticassessmentconfiguration 6.2.2                    pypi_0    pypi
pyobjc-framework-automator 6.2.2                    pypi_0    pypi
pyobjc-framework-avfoundation 6.2.2                    pypi_0    pypi
pyobjc-framework-avkit    6.2.2                    pypi_0    pypi
pyobjc-framework-businesschat 6.2.2                    pypi_0    pypi
pyobjc-framework-calendarstore 6.2.2                    pypi_0    pypi
pyobjc-framework-cfnetwork 6.2.2                    pypi_0    pypi
pyobjc-framework-cloudkit 6.2.2                    pypi_0    pypi
pyobjc-framework-cocoa    6.2.2                    pypi_0    pypi
pyobjc-framework-collaboration 6.2.2                    pypi_0    pypi
pyobjc-framework-colorsync 6.2.2                    pypi_0    pypi
pyobjc-framework-contacts 6.2.2                    pypi_0    pypi
pyobjc-framework-contactsui 6.2.2                    pypi_0    pypi
pyobjc-framework-coreaudio 6.2.2                    pypi_0    pypi
pyobjc-framework-coreaudiokit 6.2.2                    pypi_0    pypi
pyobjc-framework-corebluetooth 6.2.2                    pypi_0    pypi
pyobjc-framework-coredata 6.2.2                    pypi_0    pypi
pyobjc-framework-corehaptics 6.2.2                    pypi_0    pypi
pyobjc-framework-corelocation 6.2.2                    pypi_0    pypi
pyobjc-framework-coremedia 6.2.2                    pypi_0    pypi
pyobjc-framework-coremediaio 6.2.2                    pypi_0    pypi
pyobjc-framework-coreml   6.2.2                    pypi_0    pypi
pyobjc-framework-coremotion 6.2.2                    pypi_0    pypi
pyobjc-framework-coreservices 6.2.2                    pypi_0    pypi
pyobjc-framework-corespotlight 6.2.2                    pypi_0    pypi
pyobjc-framework-coretext 6.2.2                    pypi_0    pypi
pyobjc-framework-corewlan 6.2.2                    pypi_0    pypi
pyobjc-framework-cryptotokenkit 6.2.2                    pypi_0    pypi
pyobjc-framework-devicecheck 6.2.2                    pypi_0    pypi
pyobjc-framework-dictionaryservices 6.2.2                    pypi_0    pypi
pyobjc-framework-discrecording 6.2.2                    pypi_0    pypi
pyobjc-framework-discrecordingui 6.2.2                    pypi_0    pypi
pyobjc-framework-diskarbitration 6.2.2                    pypi_0    pypi
pyobjc-framework-dvdplayback 6.2.2                    pypi_0    pypi
pyobjc-framework-eventkit 6.2.2                    pypi_0    pypi
pyobjc-framework-exceptionhandling 6.2.2                    pypi_0    pypi
pyobjc-framework-executionpolicy 6.2.2                    pypi_0    pypi
pyobjc-framework-externalaccessory 6.2.2                    pypi_0    pypi
pyobjc-framework-fileprovider 6.2.2                    pypi_0    pypi
pyobjc-framework-fileproviderui 6.2.2                    pypi_0    pypi
pyobjc-framework-findersync 6.2.2                    pypi_0    pypi
pyobjc-framework-fsevents 6.2.2                    pypi_0    pypi
pyobjc-framework-gamecenter 6.2.2                    pypi_0    pypi
pyobjc-framework-gamecontroller 6.2.2                    pypi_0    pypi
pyobjc-framework-gamekit  6.2.2                    pypi_0    pypi
pyobjc-framework-gameplaykit 6.2.2                    pypi_0    pypi
pyobjc-framework-imagecapturecore 6.2.2                    pypi_0    pypi
pyobjc-framework-imserviceplugin 6.2.2                    pypi_0    pypi
pyobjc-framework-inputmethodkit 6.2.2                    pypi_0    pypi
pyobjc-framework-installerplugins 6.2.2                    pypi_0    pypi
pyobjc-framework-instantmessage 6.2.2                    pypi_0    pypi
pyobjc-framework-intents  6.2.2                    pypi_0    pypi
pyobjc-framework-iosurface 6.2.2                    pypi_0    pypi
pyobjc-framework-ituneslibrary 6.2.2                    pypi_0    pypi
pyobjc-framework-latentsemanticmapping 6.2.2                    pypi_0    pypi
pyobjc-framework-launchservices 6.2.2                    pypi_0    pypi
pyobjc-framework-libdispatch 6.2.2                    pypi_0    pypi
pyobjc-framework-linkpresentation 6.2.2                    pypi_0    pypi
pyobjc-framework-localauthentication 6.2.2                    pypi_0    pypi
pyobjc-framework-mapkit   6.2.2                    pypi_0    pypi
pyobjc-framework-mediaaccessibility 6.2.2                    pypi_0    pypi
pyobjc-framework-medialibrary 6.2.2                    pypi_0    pypi
pyobjc-framework-mediaplayer 6.2.2                    pypi_0    pypi
pyobjc-framework-mediatoolbox 6.2.2                    pypi_0    pypi
pyobjc-framework-metal    6.2.2                    pypi_0    pypi
pyobjc-framework-metalkit 6.2.2                    pypi_0    pypi
pyobjc-framework-modelio  6.2.2                    pypi_0    pypi
pyobjc-framework-multipeerconnectivity 6.2.2                    pypi_0    pypi
pyobjc-framework-naturallanguage 6.2.2                    pypi_0    pypi
pyobjc-framework-netfs    6.2.2                    pypi_0    pypi
pyobjc-framework-network  6.2.2                    pypi_0    pypi
pyobjc-framework-networkextension 6.2.2                    pypi_0    pypi
pyobjc-framework-notificationcenter 6.2.2                    pypi_0    pypi
pyobjc-framework-opendirectory 6.2.2                    pypi_0    pypi
pyobjc-framework-osakit   6.2.2                    pypi_0    pypi
pyobjc-framework-oslog    6.2.2                    pypi_0    pypi
pyobjc-framework-pencilkit 6.2.2                    pypi_0    pypi
pyobjc-framework-photos   6.2.2                    pypi_0    pypi
pyobjc-framework-photosui 6.2.2                    pypi_0    pypi
pyobjc-framework-preferencepanes 6.2.2                    pypi_0    pypi
pyobjc-framework-pushkit  6.2.2                    pypi_0    pypi
pyobjc-framework-quartz   6.2.2                    pypi_0    pypi
pyobjc-framework-quicklookthumbnailing 6.2.2                    pypi_0    pypi
pyobjc-framework-safariservices 6.2.2                    pypi_0    pypi
pyobjc-framework-scenekit 6.2.2                    pypi_0    pypi
pyobjc-framework-screensaver 6.2.2                    pypi_0    pypi
pyobjc-framework-scriptingbridge 6.2.2                    pypi_0    pypi
pyobjc-framework-searchkit 6.2.2                    pypi_0    pypi
pyobjc-framework-security 6.2.2                    pypi_0    pypi
pyobjc-framework-securityfoundation 6.2.2                    pypi_0    pypi
pyobjc-framework-securityinterface 6.2.2                    pypi_0    pypi
pyobjc-framework-servicemanagement 6.2.2                    pypi_0    pypi
pyobjc-framework-social   6.2.2                    pypi_0    pypi
pyobjc-framework-soundanalysis 6.2.2                    pypi_0    pypi
pyobjc-framework-speech   6.2.2                    pypi_0    pypi
pyobjc-framework-spritekit 6.2.2                    pypi_0    pypi
pyobjc-framework-storekit 6.2.2                    pypi_0    pypi
pyobjc-framework-syncservices 6.2.2                    pypi_0    pypi
pyobjc-framework-systemconfiguration 6.2.2                    pypi_0    pypi
pyobjc-framework-systemextensions 6.2.2                    pypi_0    pypi
pyobjc-framework-usernotifications 6.2.2                    pypi_0    pypi
pyobjc-framework-videosubscriberaccount 6.2.2                    pypi_0    pypi
pyobjc-framework-videotoolbox 6.2.2                    pypi_0    pypi
pyobjc-framework-vision   6.2.2                    pypi_0    pypi
pyobjc-framework-webkit   6.2.2                    pypi_0    pypi
pyodbc                    4.0.30           py37h0a44026_0  
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.6                      py_0  
pyproj                    2.6.1.post1              pypi_0    pypi
pyqt                      5.9.2            py37h655552a_2  
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h1de35cc_0  
pyshp                     2.1.2                    pypi_0    pypi
pysocks                   1.7.1                    py37_0  
pytables                  3.6.1            py37h5bccee9_0  
pytest                    5.3.5                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.8.0                      py_0  
pytest-astropy-header     0.1.2                      py_0  
pytest-cov                2.10.1                   pypi_0    pypi
pytest-doctestplus        0.5.0                      py_0  
pytest-filter-subpackage  0.1.1                    pypi_0    pypi
pytest-openfiles          0.4.0                      py_0  
pytest-remotedata         0.3.2                    py37_0  
python                    3.7.6                h359304d_2  
python-dateutil           2.8.1                      py_0  
python-geohash            0.8.5                    pypi_0    pypi
python-jsonrpc-server     0.3.4                      py_0  
python-language-server    0.31.7                   py37_0  
python-libarchive-c       2.8                     py37_13  
python.app                2                       py37_10  
pytz                      2019.3                     py_0  
pywavelets                1.1.1            py37h1de35cc_0  
pyyaml                    5.3              py37h1de35cc_0  
pyzmq                     18.1.1           py37h0a44026_0  
qdarkstyle                2.8                        py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.6.1                      py_0  
qtconsole                 4.6.0                      py_1  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.24.0                   pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
ripgrep                   11.0.2               he32d670_0  
rope                      0.16.0                     py_0  
rtree                     0.9.3                    py37_0  
ruamel_yaml               0.15.87          py37h1de35cc_0  
schedule                  0.6.0                    pypi_0    pypi
scikit-image              0.16.2           py37h6c726b0_0  
scikit-learn              0.22.1           py37h27c97d8_0  
scipy                     1.4.1            py37h9fa6033_0  
seaborn                   0.10.0                     py_0  
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.5.0                    py37_0  
setuptools                46.0.0                   py37_0  
shapely                   1.7.0                    pypi_0    pypi
simplegeneric             0.8.1                    py37_2  
simplejson                3.17.2                   pypi_0    pypi
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.14.0                   py37_0  
smopy                     0.0.7                    pypi_0    pypi
snappy                    1.1.7                he62c110_3  
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.1.2                    py37_0  
sortedcontainers          2.1.0                    py37_0  
soupsieve                 1.9.5                    py37_0  
sphinx                    2.4.0                      py_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.1                      py_0  
sphinxcontrib-devhelp     1.0.1                      py_0  
sphinxcontrib-htmlhelp    1.0.2                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.2                      py_0  
sphinxcontrib-serializinghtml 1.1.3                      py_0  
sphinxcontrib-websupport  1.2.0                      py_0  
spyder                    4.0.1                    py37_0  
spyder-kernels            1.8.1                    py37_0  
sqlalchemy                1.3.13           py37h1de35cc_0  
sqlite                    3.31.1               ha441bb4_0  
sqlparse                  0.3.1                    pypi_0    pypi
statsmodels               0.11.0           py37h1de35cc_0  
sympy                     1.5.1                    py37_0  
tableauserverclient       0.12                     pypi_0    pypi
tbb                       2020.0               h04f5b5a_0  
tblib                     1.6.0                      py_0  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.3            py37h1de35cc_3  
tqdm                      4.42.1                     py_0  
traitlets                 4.3.3                    py37_0  
typed-ast                 1.4.1                    pypi_0    pypi
tzlocal                   2.1                      pypi_0    pypi
ujson                     1.35             py37h1de35cc_0  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.25.8                   py37_0  
utm                       0.4.2                    pypi_0    pypi
validation                0.5.0                    pypi_0    pypi
virtualenv                20.0.31                  pypi_0    pypi
waitress                  1.4.4                    pypi_0    pypi
watchdog                  0.10.2           py37h1de35cc_0  
wcwidth                   0.1.8                      py_0  
webdriver-manager         3.2.2                    pypi_0    pypi
webencodings              0.5.1                    py37_1  
werkzeug                  1.0.0                      py_0  
wheel                     0.34.2                   py37_0  
whitenoise                5.2.0                    pypi_0    pypi
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.11.2           py37h1de35cc_0  
wurlitzer                 2.0.0                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.2.7                      py_0  
xlwings                   0.17.1                   py37_0  
xlwt                      1.3.0                    py37_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
yapf                      0.28.0                     py_0  
zeromq                    4.3.1                h0a44026_3  
zict                      1.0.0                      py_0  
zipp                      2.2.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  
</details>

**Provide a complete minimal reproducible example**
```python
>>> import osmnx as ox
>>> wurster_hall = (37.870605, -122.254830)
>>> one_mile = 1609 #meters
>>> G = ox.graph_from_point(wurster_hall, dist=one_mile, network_type='drive')
fig, ax = ox.plot_graph(G, node_size=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/osmnx/graph.py", line 167, in graph_from_point
    custom_filter=custom_filter,
  File "/opt/anaconda3/lib/python3.7/site-packages/osmnx/graph.py", line 88, in graph_from_bbox
    custom_filter=custom_filter,
  File "/opt/anaconda3/lib/python3.7/site-packages/osmnx/graph.py", line 427, in graph_from_polygon
    G_buff = _create_graph(response_jsons, retain_all=True, bidirectional=bidirectional)
  File "/opt/anaconda3/lib/python3.7/site-packages/osmnx/graph.py", line 565, in _create_graph
    if len(G.edges) > 0:

```
Thanks for your help!

**Comment by gboeing** [comment]
You're using the latest release of OSMnx but networkx 1.x. OSMnx has required networkx 2.x for a couple of years. Make sure to follow the documentation's installation instructions.

**Comment by BenjaminT17** [comment]
Whoops. Sorry for the trivial error on my part when I installed a different package it reverted networkx to the lower version. Thanks for such a quick response!
