### ISSUE TITLE
Speed-up plot_route_folium

### ISSUE THREAD

**Issue by Labulitiolle** [gboeing/osmnx#586]
https://github.com/gboeing/osmnx/blob/c1d402601c739108bcdc86523dabd3c0d71dbac4/osmnx/folium.py#L202

Hi @gboeing ,
As I am still using your package with large data sets I have noticed that this function `graph_to_gdfs(G, nodes=False, fill_edge_geometry=True)` builds a gdf wit edges and nodes from the entire graph. As only the nodes and edges from the path are required to plot the route I would suggest using `graph_to_gdfs(G.subgraph(route), nodes=False, fill_edge_geometry=True)`. 

The speed is significantly improved, the computation time for a graph with 90000 edges and a path of 430 nodes is:
- Current version: `23.7146 s`
- Enhanced version: `0.9569 s`

Should I do a PR ?

**Comment by gboeing** [comment]
Good idea. Yes, thanks.

**Comment by gboeing** [comment]
Closed by #587, thanks @Labulitiolle

**Comment by falcaozane** [comment]
AttributeError: module 'osmnx' has no attribute 'plot_route_folium' 

is this function removed or what??

**Comment by gboeing** [comment]
@falcaozane see #1252.
