### ISSUE TITLE
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']

### ISSUE THREAD

**Issue by blairg23** [gboeing/osmnx#59]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Followed the tutorial and installed osmnx, then tried to import it.

#### What operating system, architecture, Python version, and OSMnx version are you using?
Ubuntu 16.04 LTS, Python3, OSMnx 0.5.1
#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>
amqp (2.1.4)

appdirs (1.4.3)

apturl (0.5.2)

asn1crypto (0.22.0)

automaton (1.9.0)

awsebcli (3.10.1)

Babel (2.4.0)

beautifulsoup4 (4.4.1)

billiard (3.5.0.2)

bleach (2.0.0)

blessed (1.14.2)

blinker (1.3)

botocore (1.5.45)

Brlapi (0.6.4)

cachetools (2.0.0)

celery (4.0.2)

cement (2.8.2)

cffi (1.10.0)

chardet (2.3.0)

checkbox-support (0.22)

click (6.7)

click-plugins (1.0.3)

cligj (0.4.0)

colorama (0.3.7)

command-not-found (0.3)

contextlib2 (0.5.5)

coreapi (2.3.0)

coreschema (0.0.4)

cryptography (1.2.3)

cycler (0.10.0)

debtcollector (1.13.0)

decorator (4.0.11)

defer (1.0.6)

defusedxml (0.5.0)

descartes (1.1.0)

Django (1.11.1)

django-admin-tools (0.8.0)

django-admin-tools-stats (0.8.0)

django-allauth (0.32.0)

django-appconf (1.0.2)

django-autoslug (1.9.3)

django-bower (5.2.0)

django-cache-utils (0.7.2)

django-celery-beat (1.0.1)

django-celery-email (1.1.5)

django-celery-results (1.0.1)

django-cors-headers (2.0.2)

django-extensions (1.7.9)

django-jsonfield (1.0.1)

django-nvd3 (0.9.7)

django-qsstats-magic (0.7.2)

django-redis-cache (1.7.1)

django-rest-auth (0.9.1)

django-websocket-redis (0.5.0)

djangorestframework (3.6.3)

docker-py (1.7.2)

dockerpty (0.4.1)

docopt (0.6.2)

docutils (0.13.1)

drf-extensions (0.3.1)

drf-writable-nested (0.1.3)

drfdocs (0.0.11)

entrypoints (0.2.2)

fasteners (0.14.1)

feedparser (5.2.1)

Fiona (1.7.6)

futurist (1.1.0)

geopandas (0.2.1)

gevent (1.2.1)

google-api-python-client (1.6.2)

googleads (5.4.0)

greenlet (0.4.12)

guacamole (0.9.2)

html5lib (0.999999999)

httplib2 (0.10.3)

idna (2.5)

ipykernel (4.6.0)

ipython (5.3.0)

ipython-genutils (0.2.0)

ipywidgets (6.0.0)

iso8601 (0.1.11)

itypes (1.1.0)

Jinja2 (2.9.6)

jmespath (0.9.2)

jsonschema (2.6.0)

jupyter (1.0.0)

jupyter-client (5.0.1)

jupyter-console (5.1.0)

jupyter-core (4.3.0)

kombu (4.0.2)

language-selector (0.1)

louis (2.6.4)

lxml (3.5.0)

mailchimp3 (2.0.6)

Mako (1.0.3)

MarkupSafe (1.0)

matplotlib (2.0.2)

mistune (0.7.4)

monotonic (1.3)

msgpack-python (0.4.8)

munch (2.1.1)

mysqlclient (1.3.10)

nbconvert (5.1.1)

nbformat (4.3.0)

netaddr (0.7.19)

netifaces (0.10.5)

networkx (1.11)

notebook (5.0.0)

numpy (1.12.1)

oauth2client (1.5.2)

oauthlib (2.0.2)

olefile (0.44)

onboard (1.2.0)

oslo.i18n (3.15.0)

oslo.serialization (2.18.0)

oslo.utils (3.25.0)

osmnx (0.5.1)

packaging (16.8)

padme (1.1.1)

pandas (0.20.1)

pandocfilters (1.4.1)

pathspec (0.5.0)

pbr (3.0.0)

pexpect (4.0.1)

pickleshare (0.7.4)

Pillow (4.1.1)

pip (9.0.1)

plainbox (0.25)

prettytable (0.7.2)

prompt-toolkit (1.0.14)

ptyprocess (0.5)

pyasn1 (0.2.3)

pyasn1-modules (0.0.8)

pycparser (2.17)

pycups (1.9.73)

pycurl (7.43.0)

Pygments (2.2.0)

pygobject (3.20.0)

PyJWT (1.5.0)

pyparsing (2.2.0)

pyproj (1.9.5.1)

PySocks (1.6.7)

python-apt (1.1.0b1)

python-dateutil (2.6.0)

python-debian (0.1.27)

python-nvd3 (0.14.2)

python-slugify (1.1.4)

python-systemd (231)

python3-openid (3.1.0)

pytz (2017.2)

pyxdg (0.25)

PyYAML (3.12)

pyzmq (16.0.2)

qtconsole (4.3.0)

redis (2.10.5)

reportlab (3.3.0)

requests (2.14.2)

requests-oauthlib (0.8.0)

rsa (3.4.2)

Rtree (0.8.3)

semantic-version (2.5.0)

sessioninstaller (0.0.0)

setuptools (35.0.2)

Shapely (1.5.17.post1)

simplegeneric (0.8.1)

six (1.10.0)

stevedore (1.21.0)

stripe (1.55.2)

suds-jurko (0.6)

system-service (0.3)

tabulate (0.7.5)

taskflow (2.10.0)

tenacity (4.1.0)

termcolor (1.1.0)

terminado (0.6)

testpath (0.3)

tornado (4.4.3)

traitlets (4.3.2)

twilio (6.1.0)

ubuntu-drivers-common (0.0.0)

ufw (0.35)

unattended-upgrades (0.1)

Unidecode (0.4.20)

unity-scope-calculator (0.1)

unity-scope-chromiumbookmarks (0.1)

unity-scope-colourlovers (0.1)

unity-scope-devhelp (0.1)

unity-scope-firefoxbookmarks (0.1)

unity-scope-gdrive (0.7)

unity-scope-manpages (0.1)

unity-scope-openclipart (0.1)

unity-scope-texdoc (0.1)

unity-scope-tomboy (0.1)

unity-scope-virtualbox (0.1)

unity-scope-yelp (0.1)

unity-scope-zotero (0.1)

uritemplate (3.0.0)

urllib3 (1.13.1)

usb-creator (0.3.0)

uszipcode (0.1.3)

uWSGI (2.0.15)

vine (1.1.3)

virtualenv (15.0.1)

wcwidth (0.1.7)

webencodings (0.5)

websocket-client (0.40.0)

wheel (0.29.0)

widgetsnbextension (2.0.0)

wrapt (1.10.10)

xdiagnose (3.8.4.1)

xkit (0.0.0)

XlsxWriter (0.7.3)

xmltodict (0.11.0)

</details>

#### Code that reproduces the issue
```python
import osmnx
```

# Issue says:

```
Failed `CDLL(libgeos_c.so.1)`
Failed `CDLL(libgeos_c.so)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/osmnx/__init__.py", line 8, in <module>
    from .buildings import *
  File "/usr/local/lib/python3.5/dist-packages/osmnx/buildings.py", line 9, in <module>
    import geopandas as gpd
  File "/usr/local/lib/python3.5/dist-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/usr/local/lib/python3.5/dist-packages/geopandas/geoseries.py", line 10, in <module>
    from shapely.geometry import box, shape, Polygon, Point
  File "/usr/local/lib/python3.5/dist-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/usr/local/lib/python3.5/dist-packages/shapely/geometry/base.py", line 9, in <module>
    from shapely.coords import CoordinateSequence
  File "/usr/local/lib/python3.5/dist-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/usr/local/lib/python3.5/dist-packages/shapely/geos.py", line 66, in <module>
    _lgeos = load_dll('geos_c', fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
  File "/usr/local/lib/python3.5/dist-packages/shapely/geos.py", line 61, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
```

Reading this [https://stackoverflow.com/questions/19742406/could-not-find-library-geos-c-or-load-any-of-its-variants](Stackoverflow article), I found the solution is by using the command
`sudo apt-get install libgeos-dev`

**Comment by gboeing** [comment]
Hmm. Did you install osmnx via pip or conda? Conda-forge should have installed GEOS automatically.

**Comment by blairg23** [comment]
I used pip. I was having a lot of difficulties, so I used conda and it works much better.

**Comment by gboeing** [comment]
Ok, so just to confirm, everything is working properly now?

**Comment by blairg23** [comment]
Yes but only through conda. Pip install requires a lot of dependencies.

**Comment by gboeing** [comment]
Yes indeed. That's how it goes with pip, and is the raison d'être for conda forge.
