### ISSUE TITLE
Documentation on road extraction

### ISSUE THREAD

**Issue by jesuslovesyiyi** [gboeing/osmnx#593]
Hi, I am wondering if more detailed documentation or link to external sites can be provided for the graph module's network extraction functions such as graph from place or graph from polygon. For example, "all" suggest all public roads yet this is still relatively hard to make out what is included.

**Comment by gboeing** [comment]
Thanks for your interest in OSMnx. The details of the built-in `network_type` filters can be seen [here](https://github.com/gboeing/osmnx/blob/v0.16.2/osmnx/downloader.py#L43-L92). Details about specific key/value tagging can be found on [OSM](https://wiki.openstreetmap.org/wiki/Key:highway). For "how to" usage questions, you can ask on StackOverflow.
