### ISSUE TITLE
Possible duplicate eges?

### ISSUE THREAD

**Issue by matiasitalia** [gboeing/osmnx#598]
Hello Geoof, how are you?

Im running this:
useful_tags_way = ['oneway', 'lanes', 'name', 'highway', 'maxspeed', 'width', 'est_width','surface']
ox.utils.config(useful_tags_way=useful_tags_way, timeout=1000, use_cache=True, log_console=True)
graph = ox.graph_from_place({'country': "Uruguay"}, retain_all = True, network_type='drive', simplify=False)
edges = ox.graph_to_gdfs(graph, nodes=False, edges=True)
df = pd.DataFrame(edges).apply(tuple)

And when I group the observations at the id level (u v key), I find observations that would seem to be duplicated.

For example, u=441826977, v=442300000, key=0 (LINESTRING (-55.9778512 -34.8441246, -55.978284 -34.8444826)), seems to be duplicated from: u=442348052, v=441800000, key=0 (LINESTRING (-55.978284 -34.8444826, -55.9778512 -34.8441246)), both with osmid=457934367. 

In case it is not understood, I paste an excel with three examples of possible repetitions.

Thank you!

Matias
[duplicated.xlsx](https://github.com/gboeing/osmnx/files/5576010/duplicated.xlsx)

**Comment by gboeing** [comment]
You didn't provide the complete code to reproduce how you identified duplicates. But here's a complete minimal code snippet... MultiDiGraph edges are uniquely identified by `u`, `v`, and `key` and I don't find any duplicates here:

```python
import osmnx as ox
useful_tags_way = ['oneway', 'lanes', 'name', 'highway', 'maxspeed', 'width', 'est_width','surface']
ox.config(useful_tags_way=useful_tags_way, timeout=1000, use_cache=True, log_console=True)
G = ox.graph_from_place({'country': "Uruguay"}, retain_all=True, network_type='drive', simplify=False)
edges = ox.graph_to_gdfs(G, nodes=False, fill_edge_geometry=False).set_index(['u', 'v', 'key'])
assert edges.index.is_unique #success
```

**Comment by gboeing** [comment]
Also note that #592 sets the index of the edges returned by `graph_to_gdfs` to explicitly index by u, v, and key. Will appear in the next release.

**Comment by matiasitalia** [comment]
Hi geoff, thanks for the reply.

I wanted to say that those observations have differents  u v key, but if you map them, they are the same edges. It seem an error, because i searched in osm, and there is only one of them.

Thanks

Matias

________________________________
De: Geoff Boeing <notifications@github.com>
Enviado: viernes, 20 de noviembre de 2020 21:04
Para: gboeing/osmnx <osmnx@noreply.github.com>
Cc: matiasitalia <matias_italia@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [gboeing/osmnx] Possible duplicate eges? (#598)


You didn't provide the complete code to reproduce how you identified duplicates. But here's a complete minimal code snippet... MultiDiGraph edges are uniquely identified by u, v, and key and I don't find any duplicates here:

import osmnx as ox
useful_tags_way = ['oneway', 'lanes', 'name', 'highway', 'maxspeed', 'width', 'est_width','surface']
ox.config(useful_tags_way=useful_tags_way, timeout=1000, use_cache=True, log_console=True)
G = ox.graph_from_place({'country': "Uruguay"}, retain_all=True, network_type='drive', simplify=False)
edges = ox.graph_to_gdfs(G, nodes=False, fill_edge_geometry=False).set_index(['u', 'v', 'key'])
assert edges.index.is_unique #success

**Comment by gboeing** [comment]
> observations have differents u v key, but if you map them, they are the same edges

If your graph is directed, you'd expect to see duplicated edges for any bidirectional streets, as one directed edge runs from `u` to `v` and the other runs from `v` to `u`. Their geometries would be the same.

**Comment by matiasitalia** [comment]
But in that case the variable oneway should be True in both cases? Because is false in both.

________________________________
De: Geoff Boeing <notifications@github.com>
Enviado: sábado, 21 de noviembre de 2020 00:38
Para: gboeing/osmnx <osmnx@noreply.github.com>
Cc: matiasitalia <matias_italia@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [gboeing/osmnx] Possible duplicate eges? (#598)


observations have differents u v key, but if you map them, they are the same edges

If your graph is directed, you'd expect to see duplicated edges for any bidirectional streets, as one directed edge runs from u to v and the other runs from v to u. Their geometries would be the same.

**Comment by gboeing** [comment]
> For example, u=441826977, v=442300000, key=0 (LINESTRING (-55.9778512 -34.8441246, -55.978284 -34.8444826)), seems to be duplicated from: u=442348052, v=441800000, key=0 (LINESTRING (-55.978284 -34.8444826, -55.9778512 -34.8441246)), both with osmid=457934367.

And looking further at this quote from your initial comment, I'm not clear on how you're identifying or defining duplicates here. Graph edges are uniquely identified by `u`, `v`, `key`... but the two edges you flag here as duplicates have different `u`, `v`, `key` values. They also have different geometries, as you can see from their coordinates.

Are you wondering why they both share the same `osmid` value? That's to be expected as you did not simplify your graph and there is not a 1:1 correspondence between graph edges and OSM ways. For example, if you look at [that way](https://www.openstreetmap.org/way/457934367) on OSM, you can see where it must be divided into two graph edges to accommodate [the node](https://www.openstreetmap.org/node/442348052) at the intersection of Calle Río de Janeiro.

**Comment by matiasitalia** [comment]
When i graph in qgis those two edges, they are one above the other. Thats why i think they could be duplicated. Althoug their coordinates are a little different. But in the data they have the same name, highway, oneway (=false), length, and almost coordinates...

________________________________
De: Geoff Boeing <notifications@github.com>
Enviado: sábado, 21 de noviembre de 2020 01:01
Para: gboeing/osmnx <osmnx@noreply.github.com>
Cc: matiasitalia <matias_italia@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [gboeing/osmnx] Possible duplicate eges? (#598)


For example, u=441826977, v=442300000, key=0 (LINESTRING (-55.9778512 -34.8441246, -55.978284 -34.8444826)), seems to be duplicated from: u=442348052, v=441800000, key=0 (LINESTRING (-55.978284 -34.8444826, -55.9778512 -34.8441246)), both with osmid=457934367.

And looking further at this quote from your initial comment, I'm not clear on how you're identifying or defining duplicates here. Graph edges are uniquely identified by u, v, key... but the two edges you flag here as duplicates have different u, v, key values. They also have different geometries, as you can see from their coordinates.

Are you wondering why they both share the same osmid value? That's to be expected as you did not simplify your graph and there is not a 1:1 correspondence between graph edges and OSM ways. For example, if you look at that way<https://www.openstreetmap.org/way/457934367> on OSM, you can see where it must be divided into two graph edges to accommodate the node<https://www.openstreetmap.org/node/442348052> at the intersection of Calle Río de Janeiro.

**Comment by gboeing** [comment]
Something is going wrong in your code. For example you mention the edge `u=442348052, v=441800000, key=0` but this [node 441800000](https://www.openstreetmap.org/node/441800000) is actually in France on OSM. You also mention [node 442300000](https://www.openstreetmap.org/node/442300000) but it is in El Salvador.

**Comment by matiasitalia** [comment]
Hi, Geoff thank you for you time, and sorry for the example used, when i pasted automatically round some numbers.

What I thaught ir could be duplicated observations, is what you said about bidirectional streets:
          "If your graph is directed, you'd expect to see duplicated edges for any bidirectional streets, as one directed edge runs from u to v and the other runs from v to u. Their geometries would be the same."

In this example is very clear: u1=442348057, v1=442348056, u2=442348056, v2=442348057 (same osmid=37717881)
Bu my question is why in those cases oneway if False? Shouldn't it be True?

The question comes because I am calculating the km of routes by lanes, and I understand that if I leave both observations I would be making a mistake. Should I remove the bidirectionality?

In this specific case, I'm doing a lane imputation exercise when you don't have information about it: imputing 2 lanes when oneway=False, and also recovering the information when in some section of the same route you DO have lane information, while in the rest you don't (in that case I impute that value to all the sections)

Thanks again for your time!

Matias


________________________________
De: Geoff Boeing <notifications@github.com>
Enviado: sábado, 21 de noviembre de 2020 01:23
Para: gboeing/osmnx <osmnx@noreply.github.com>
Cc: matiasitalia <matias_italia@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [gboeing/osmnx] Possible duplicate eges? (#598)


Something is going wrong in your code. For example you mention the edge u=442348052, v=441800000, key=0 but this node 441800000<https://www.openstreetmap.org/node/441800000> is actually in France on OSM. You also mention node 442300000<https://www.openstreetmap.org/node/442300000> but it is in El Salvador.

**Comment by gboeing** [comment]
> u1=442348057, v1=442348056, u2=442348056, v2=442348057 (same osmid=37717881)
Bu my question is why in those cases oneway if False? Shouldn't it be True?

The `oneway` attribute is just the value of the `oneway` tag of that OSM way. As you can see, that is not a one-way street in the real world or on OSM, so its `oneway` value is, correctly, `False`. To represent a bidirectional (i.e., not one-way) street such as this in a MultiDiGraph, we must use two reciprocal directed edges: one pointing from `442348057` to `442348056` and the other pointing from `442348057` to `442348056`, to represent both possible directions of flow.

> The question comes because I am calculating the km of routes by lanes, and I understand that if I leave both observations I would be making a mistake. Should I remove the bidirectionality?

You can simply use OSMnx's `get_undirected` function to calculate stats on an undirected representation of your graph with only one edge per physical street segment.

This does not appear to be about a bug in OSMnx but rather just a usage question, so I'm going to close this issue. Best to ask how-to usage questions on StackOverflow as per the contributing guidelines.
