### ISSUE TITLE
save and load graphml apparently changes the graph type/edges

### ISSUE THREAD

**Issue by matteoboh** [gboeing/osmnx#599]
**Problem description**

Hi @gboeing, first, thank you very much for your work. OSMnx is awesome, and actually really fun :)
So, I noticed that when loading networks that have previously been saved to .graphml, the type of graph changes as well as the number of edges. The sequence is:

1. load e.g. a graph_from_place, which is a MultiDiGraph having **x** edges;
2. get its undirected version, which has **y** edges and is a MultiGraph and I save_graphml it;
3. when load_graphml, the loaded graph has become again a MultiDiGraph, with a number **z** of edges that is different both from the number of edges of the original graph and from the one of its undirected version.

_Update_ : I noted that **z** is always about two times **y**, so apparently when loading/saving the MultiGraph is turned to a MultiDiGraph by adding for each edge its copy with inverse direction.. but why does this happen?

Am I missing something?
Could this be related to Issue #317 ?

Thank you very much!

**Environment information**

Ubuntu 18.04.5 LTS, Python 3.7.6, OSMnx 0.16.0

<details>
# packages in environment at /home/matteo/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py37_1  
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.7                    py37_0  
anaconda-project          0.8.4                      py_0  
asn1crypto                1.3.0                    py37_0    conda-forge
astroid                   2.3.3                    py37_1    conda-forge
astropy                   4.0              py37h516909a_1    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.os              0.1.1                 py37_1001    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1             py37_1000    conda-forge
beautifulsoup4            4.8.2                    py37_0    conda-forge
bitarray                  1.2.1            py37h516909a_0    conda-forge
bkcharts                  0.2                      py37_0  
blas                      2.14                   openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.17.1               he1b5a44_0    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.1            py37hc1659b7_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2020.4.5.2       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h2e261b9_0  
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                    pypi_0    pypi
cloudpickle               1.3.0                      py_0  
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
combo                     0.1.1                    pypi_0    pypi
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-build               3.18.11                  py37_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-package-handling    1.6.0            py37h516909a_1    conda-forge
conda-verify              3.4.2                      py_1  
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              2.8              py37h72c5cf5_1    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.15          py37he1b5a44_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.10.1                     py_0    conda-forge
dask-core                 2.10.1                     py_0    conda-forge
dbus                      1.13.12              h746ee38_0  
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.16                     py37_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
extratools                0.8.2.1                  pypi_0    pypi
fastcache                 1.1.0            py37h516909a_0    conda-forge
filelock                  3.0.12                     py_0  
fiona                     1.8.13                   pypi_0    pypi
flask                     1.1.1                      py_1    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
future                    0.18.2                   py37_0    conda-forge
georinex                  1.15.0                   pypi_0    pypi
geos                      3.8.0                he1b5a44_0    conda-forge
geotiff                   1.5.1                h38872f0_8    conda-forge
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.4.0            py37h516909a_0    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.63.1               h5a9c865_0  
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.0                he1b5a44_1    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
greenlet                  0.4.15           py37h516909a_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
h5py                      2.10.0          nompi_py37h513d04c_102    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
hypothesis                5.5.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
imbalanced-learn          0.6.2                      py_0    conda-forge
importlib_metadata        1.5.0                    py37_0    conda-forge
intel-openmp              2019.4                      243  
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.12.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isort                     4.3.21                   py37_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1               h14c3975_2001    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.16.0                   py37_0    conda-forge
jeepney                   0.4.2                      py_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.2                    py37_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
keyring                   21.1.0                   py37_0    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
lazy-object-proxy         1.4.3            py37h516909a_1    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libarchive                3.3.3             hc47fbbf_1007    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   2.4.4                h2b6fda6_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
liblapacke                3.8.0               14_openblas    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     12.1                 hd9ab2ff_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialite             4.3.0a            ha48a99a_1034    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
llvmlite                  0.31.0           py37h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.5.0            py37h7ec2d77_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.3                    py37_0    conda-forge
matplotlib-base           3.1.3            py37h250f245_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
mkl                       2019.4                      243  
mkl-service               2.3.0            py37h516909a_0    conda-forge
mkl_fft                   1.1.0            py37hc1659b7_1    conda-forge
mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
mock                      4.0.1                      py_0  
more-itertools            8.2.0                      py_0    conda-forge
mpc                       1.1.0             h04dde30_1006    conda-forge
mpfr                      4.0.2                he80fd80_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nltk                      3.4.5                    py37_0  
nose                      1.3.7                 py37_1003    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.48.0           py37hb3f55d8_0    conda-forge
numexpr                   2.7.1            py37hb3f55d8_0    conda-forge
numpy                     1.18.1           py37h95a1406_0    conda-forge
numpy-base                1.18.1           py37h2f8d375_1  
numpydoc                  0.9.2                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openpyxl                  3.0.3                      py_0    conda-forge
openssl                   1.1.1                h7b6447c_0    anaconda
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.1            py37hb3f55d8_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
parso                     0.6.1                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
path                      13.1.0                   py37_0    conda-forge
path.py                   12.4.0                        0    conda-forge
pathlib2                  2.3.5                    py37_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    7.0.0            py37hefe7db6_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
plotly                    4.5.3                      py_0    plotly
pluggy                    0.13.1                   py37_0  
ply                       3.11                       py_1    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.1                 hc63931a_0    conda-forge
prefixspan                0.5.2                    pypi_0    pypi
proj                      6.3.0                hc80f0dc_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.3                      py_0    conda-forge
psutil                    5.6.7            py37h516909a_0    conda-forge
psycopg2                  2.8.4            py37h72c5cf5_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3           py37h516909a_1002    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycrypto                  2.6.1           py37h516909a_1003    conda-forge
pycurl                    7.43.0.5         py37h16ce93b_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pylint                    2.4.4                    py37_0    conda-forge
pyod                      0.8.1                    pypi_0    pypi
pyodbc                    4.0.30           py37he6710b0_0  
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.4.2.post1              pypi_0    pypi
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyreadr                   0.2.6                    pypi_0    pypi
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pytables                  3.6.1            py37h9f153d1_1    conda-forge
pytest                    5.3.5                    py37_1    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.7.0                      py_0    conda-forge
pytest-astropy-header     0.1.2                      py_0    conda-forge
pytest-doctestplus        0.5.0                      py_0  
pytest-openfiles          0.4.0                      py_0    conda-forge
pytest-remotedata         0.3.2                    py37_0  
python                    3.7.6                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyyaml                    5.3              py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtawesome                 0.7.0                      py_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rasterio                  1.1.2            py37hdff7cfa_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
retrying                  1.3.3                      py_2    conda-forge
ripgrep                   11.0.2               h516909a_3    conda-forge
rise                      5.6.1                    py37_0    conda-forge
rope                      0.16.0                     py_0    conda-forge
ruamel_yaml               0.15.80         py37h516909a_1000    conda-forge
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scikit-learn              0.22.1           py37hcdab131_1    conda-forge
scipy                     1.4.1            py37h921218d_0    conda-forge
seaborn                   0.10.0                     py_1    conda-forge
secretstorage             3.1.2                    py37_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.2.0                   py37_0    conda-forge
shapely                   1.7.0                    pypi_0    pypi
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py37_1000    conda-forge
sip                       4.19.20          py37he1b5a44_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
snappy                    1.1.8                he1b5a44_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcollections         1.1.2                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.5                    py37_0  
sphinx                    2.4.1                      py_0    conda-forge
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sphinxcontrib-websupport  1.2.0                      py_0  
spyder                    3.3.6                    py37_0  
spyder-kernels            0.5.2                    py37_0    conda-forge
sqlalchemy                1.3.13           py37h516909a_0    conda-forge
sqlite                    3.31.1               h7b6447c_0  
statsmodels               0.11.0           py37h516909a_0    conda-forge
suod                      0.0.4                    pypi_0    pypi
sympy                     1.5.1                    py37_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_3    conda-forge
tqdm                      4.42.1                     py_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
tslearn                   0.3.1            py37h03ebfcd_0    conda-forge
typed-ast                 1.4.1            py37h516909a_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unixodbc                  2.3.7             h227dcee_1000    conda-forge
urllib3                   1.25.8                   py37_0  
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.0                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
wrapt                     1.11.2           py37h516909a_0    conda-forge
wurlitzer                 2.0.0                    py37_0    conda-forge
xarray                    0.15.1                   pypi_0    pypi
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.2.7                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      2.2.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge

</details>

**Complete minimal reproducible example**

```python
G = ox.graph_from_point((41.895947, 12.483000), dist=1000, network_type = 'drive_service')  # center of Rome
print(type(G), ', ', G.size())
# returns <class 'networkx.classes.multidigraph.MultiDiGraph'>, 1601
G_undirected = ox.get_undirected(G)
print(type(G_undirected), ', ', G_undirected.size())
# returns <class 'networkx.classes.multigraph.MultiGraph'> ,  1239
ox.save_graphml(G_undirected, 'test')
G_loaded = ox.load_graphml('test')
print(type(G_loaded), ', ', G_loaded.size())
# returns <class 'networkx.classes.multidigraph.MultiDiGraph'> ,  2474
```

**Comment by gboeing** [comment]
As you can see in the documentation, the [save_graphml](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.io.save_graphml) and [load_graphml](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.io.load_graphml) functions take/return graphs of type `MultiDiGraph`. OSMnx itself is designed around  the `MultiDiGraph` type but provides convenience functions to covert to `MultiGraph` or `DiGraph` for analytics that require one or the other.

The `save_graphml` function doesn't enforce strict graph type checks, but passing it an unexpected argument type will yield unexpected results, as you've seen.
