### ISSUE TITLE
Getting duplicate edges with origin and destination reversed

### ISSUE THREAD

**Issue by guibar** [gboeing/osmnx#601]
Hello,
 
I am new to this package and finding it very useful.
I am running version 0.16.2 of the package.

I have just realized something which looks to me like a bug. When I pull some data with the following code:

```python
import osmnx
road_graph = osmnx.graph.graph_from_bbox(49.35212, 49.32404, 2.11, 2.07,
                             network_type='drive', simplify=True, retain_all=False,
                             truncate_by_edge=True, clean_periphery=True)
```

I get the same edge twice with the origin and destination reversed as can be seen in the output of:

```python
print(road_graph.edges)
print(road_graph[2166017444][357131830])
print(road_graph[357131830][2166017444])
```

>[ ...,(357131830, 2166017444, 0),...,(2166017444, 357131830, 0),... ]
>{0: {'osmid': 282318499, 'name': 'Rue des Cyclamens', 'highway': 'residential', 'oneway': False, 'length': 211.79999999999998, 'geometry': <shapely.geometry.linestring.LineString object at 0x7feea05a5c40>}}
>{0: {'osmid': 282318499, 'name': 'Rue des Cyclamens', 'highway': 'residential', 'oneway': False, 'length': 211.8, 'geometry': <shapely.geometry.linestring.LineString object at 0x7feea034c940>}}

As you can see here:
https://www.openstreetmap.org/way/282318499

the street connecting these 2 nodes is just a banal residential street so I don't see why it would need repeating.

Is this behaviour intended? I can't see why it would be.

Thanks a lot,

Guillaume

**Comment by gboeing** [comment]
See [the docs](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.graph.graph_from_bbox). OSMnx models street networks as NetworkX `MultiDiGraph` objects. As the graph is directed, you'd expect to see two edges for any bidirectional streets, as one directed edge runs from node `u` to node `v` and the other runs from `v` to `u`. These are not duplicates, as Networkx MultiDiGraph edges are uniquely identified by ordered `u`, `v`, `key` tuples. If you need an undirected representation, you can use the `get_undirected` function: see [the docs](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils_graph.get_undirected).

See also https://github.com/gboeing/osmnx/issues/598#issuecomment-731770259

**Comment by guibar** [comment]
Hi Geoff,
I thought this could be the explanation but since the oneway tag was still attached to each of the edges, I discarded that explanation. Sorry to bother you, I should have looked better at the docs.
Thank you for your time.
