### ISSUE TITLE
Unclosed file ResourceWarning in geometries_from_polygon()

### ISSUE THREAD

**Issue by jnettels** [gboeing/osmnx#607]
**Problem description**
Hello there,
thanks for this awesome package. While everything is working without errors, I have encountered a warning message that seems to be related to ox.geometries_from_polygon(). After the script finishes, the following is displayed:
```
C:\Users\***\anaconda3\lib\site-packages\pyreadline\lineeditor\history.py:82: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Users\\***\\.python_history' mode='r' encoding='cp1252'>
  for line in open(filename, 'r'):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
Again, everything works as expected, but the warning is irritating and I hope it can be resolved.

**Environment information**
  - Windows 10
  - Python 3.7.8
  - osmnx 0.16.2
  - Provide a complete list of your environment's packages and their versions:

<details>
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py37_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
addict                    2.3.0            py37hc8dfbb8_1    conda-forge
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py37_1
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.10.0                   py37_0
anaconda-project          0.8.3                      py_0    conda-forge
apptools                  4.5.0                      py_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               20.1.0           py37h4ab8f01_2    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
assimulo                  3.2              py37h1d503c6_3    conda-forge
astroid                   2.4.2            py37hc8dfbb8_1    conda-forge
astropy                   4.0.3            py37h4ab8f01_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
bcrypt                    3.2.0            py37h4ab8f01_1    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
bitarray                  1.6.0            py37h4ab8f01_0    conda-forge
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blinker                   1.4                      pypi_0    pypi
blosc                     1.20.1               ha925a31_0    conda-forge
bokeh                     2.1.1            py37hc8dfbb8_0    conda-forge
boost-cpp                 1.74.0               hd4e6614_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.2            py37hbc2f12b_1    conda-forge
branca                    0.4.1                      py_0    conda-forge
brotli                    1.0.9                ha925a31_2    conda-forge
brotlipy                  0.7.0           py37h0013d47_1001    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.11.8            h5b45459_0    conda-forge
cartopy                   0.18.0           py37h8ae6022_2    conda-forge
certifi                   2020.11.8        py37h03978a9_0    conda-forge
cffi                      1.14.3           py37hd6b71e5_1    conda-forge
cfitsio                   3.470                hbbe6aef_7    conda-forge
chardet                   3.0.4           py37hf50a25e_1008    conda-forge
charls                    2.1.0                h33f27b4_2    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.6.0              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
comtypes                  1.1.7           py37hc8dfbb8_1002    conda-forge
conda                     4.9.2            py37h03978a9_0    conda-forge
conda-build               3.19.2           py37hc8dfbb8_2    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-package-handling    1.7.2            py37h6dbccfb_0    conda-forge
conda-verify              3.1.1           py37hc8dfbb8_1001    conda-forge
configobj                 5.0.6                      py_0    conda-forge
console_shortcut          0.1.1                         4
contextily                1.0.0                      py_0    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
convertdate               2.2.2              pyh9f0ad1d_0    conda-forge
cryptography              3.1.1            py37hd6b71e5_1    conda-forge
curl                      7.71.1               h4b64cdc_8    conda-forge
cx-logging                2.2                      pypi_0    pypi
cx_freeze                 6.3              py37hcc03f2d_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py37h8e8dfb5_1    conda-forge
cytoolz                   0.11.0           py37h4ab8f01_1    conda-forge
dask                      2.22.0                     py_0    conda-forge
dask-core                 2.22.0                     py_0    conda-forge
datashader                0.11.0             pyh9f0ad1d_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.2                    pypi_0    pypi
distributed               2.30.0           py37hc8dfbb8_1    conda-forge
docutils                  0.16             py37hf50a25e_2    conda-forge
entrypoints               0.3             py37hc8dfbb8_1002    conda-forge
envisage                  4.9.2                      py_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.9                h33f27b4_2    conda-forge
fastcache                 1.1.0            py37h4ab8f01_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
fiona                     1.8.17           py37h6e57952_0    conda-forge
flake8                    3.8.4                      py_0    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
fmilib                    2.2                  ha925a31_0    conda-forge
folium                    0.11.0                     py_0    conda-forge
freetype                  2.10.4               hd328e21_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
fsspec                    0.8.4                      py_0    conda-forge
future                    0.18.2           py37hc8dfbb8_2    conda-forge
gdal                      3.1.2            py37h6ddc196_2    conda-forge
geckodriver               0.27.0               h33f27b4_0    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.8.1                      py_0    conda-forge
geopy                     2.0.0              pyh9f0ad1d_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.6.0                h09e6dc1_1    conda-forge
get_terminal_size         1.0.0                h38e98db_0
gettext                   0.19.8.1          hfbb10ce_1004    conda-forge
gevent                    20.9.0           py37h4ab8f01_1    conda-forge
giflib                    5.2.1                h2fa13f4_2    conda-forge
glib                      2.66.1               ha925a31_1    conda-forge
glob2                     0.7                        py_0    conda-forge
gmpy2                     2.1.0b1          py37h2b2749b_1    conda-forge
greenlet                  0.4.17           py37h4ab8f01_1    conda-forge
grpcio                    1.31.0           py37h554427f_0    conda-forge
grpcio-tools              1.16.1           py37ha925a31_0
h5py                      2.10.0          nompi_py37h23cfb99_105    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_h89124ea_1110    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holidays                  0.10.3             pyh9f0ad1d_0    conda-forge
holoviews                 1.13.3             pyh9f0ad1d_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2020.5.30        py37hfde3dd5_4    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        2.0.0                      py_1    conda-forge
importlib_metadata        2.0.0                         1    conda-forge
iniconfig                 1.1.0              pyh9f0ad1d_0    conda-forge
intel-openmp              2019.4                      245
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.3.4            py37h7b7c402_1    conda-forge
ipython                   7.18.1           py37hc6149b9_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
isort                     5.6.4                      py_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.1           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsoncpp                   1.8.4             h1ad3211_1002    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_2    conda-forge
jupyterlab                2.2.8                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
jxrlib                    1.1                  hfa6e2cd_2    conda-forge
kealib                    1.4.13               h3b59ab9_1    conda-forge
keyring                   21.4.0           py37hc8dfbb8_2    conda-forge
kiwisolver                1.2.0            py37h1fb7aa8_1    conda-forge
korean_lunar_calendar     0.2.1              pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               hc04afaa_3    conda-forge
lazy-object-proxy         1.4.3            py37h4ab8f01_2    conda-forge
lcms2                     2.11                 he1115b7_0    conda-forge
lerc                      2.2                  ha925a31_0    conda-forge
libaec                    1.0.4                he025d50_1    conda-forge
libarchive                3.4.3                h793d221_0    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libgdal                   3.1.2                h132428b_2    conda-forge
libglib                   2.66.1               h31c07e1_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             he9e54da_1012    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
liblief                   0.10.1               ha925a31_2    conda-forge
libllvm9                  9.0.1                hde8ddfe_1    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_105    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libpq                     12.3                 hd9aa61d_2    conda-forge
libprotobuf               3.13.0.1             h200bbdf_0    conda-forge
libsodium                 1.0.18               h62dcd97_1    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            h9ed2f40_1039    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
libxslt                   1.1.33               h579f668_1    conda-forge
libzopfli                 1.0.3                ha925a31_0    conda-forge
llvmlite                  0.31.0           py37ha925a31_0
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.1            py37h8ba8a40_0    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-patch                  2.7.5                         2
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markdown                  3.3.2              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py37h0013d47_2    conda-forge
matplotlib                3.3.0                         1    conda-forge
matplotlib-base           3.3.0            py37h35e8a6e_1    conda-forge
mayavi                    4.7.1            py37hf36c280_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.16                   py37_0    conda-forge
mercantile                1.1.6              pyh9f0ad1d_0    conda-forge
mistune                   0.8.4           py37h4ab8f01_1002    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py37hfa6e2cd_0    conda-forge
mkl_fft                   1.1.0            py37hc8d92b1_1    conda-forge
mkl_random                1.1.0            py37h675688f_0
mock                      4.0.2            py37hc8dfbb8_1    conda-forge
more-itertools            8.5.0                      py_0    conda-forge
mpc                       1.1.0             h7edee0f_1009    conda-forge
mpfr                      4.0.2                h62dcd97_1    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            1.0.0            py37h1fb7aa8_2    conda-forge
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
navigator-updater         0.2.1                    py37_0
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
nest-asyncio              1.4.1                      py_0    conda-forge
networkx                  2.5                        py_0    conda-forge
nltk                      3.4.4                      py_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.1.4            py37hc8dfbb8_1    conda-forge
numba                     0.48.0           py37he350917_0    conda-forge
numexpr                   2.7.1            py37h414f9d2_3    conda-forge
numpy                     1.19.1           py37hae9e721_0    conda-forge
numpy-base                1.18.5           py37hc3f5095_0
numpydoc                  1.1.0                      py_1    conda-forge
oemof-network             0.4.0rc0                 pypi_0    pypi
oemof-solph               0.4.1                    pypi_0    pypi
oemof-tools               0.4.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openpyxl                  3.0.4                      py_0    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
osmnx                     0.16.2             pyhd3deb0d_0    conda-forge
owslib                    0.20.0                     py_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.0            py37h1834ac0_0    conda-forge
pandoc                    2.11.0.2             hf4a77e7_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
panel                     0.9.7                      py_0    conda-forge
param                     1.9.3                      py_0    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0    conda-forge
path                      15.0.0           py37hc8dfbb8_1    conda-forge
path.py                   12.5.0                        0    conda-forge
pathlib2                  2.3.5            py37hc8dfbb8_1    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
phantomjs                 2.1.1                         1    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.0            py37hb71ed58_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pkginfo                   1.6.0              pyh9f0ad1d_0    conda-forge
pluggy                    0.13.1           py37hc8dfbb8_3    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   0.89.0               h0cd1227_0    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.3                 he14cc48_2    conda-forge
powershell_shortcut       0.0.1                         3
proj                      7.1.0                h7d85306_1    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.8                      py_0    conda-forge
prompt_toolkit            3.0.8                         0    conda-forge
protobuf                  3.13.0.1         py37h1834ac0_1    conda-forge
psutil                    5.7.2            py37h0013d47_1    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
py-lief                   0.10.1           py37h8e8dfb5_2    conda-forge
pyaml                     20.4.0             pyh9f0ad1d_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py37h0013d47_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py37h0013d47_1005    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pycurl                    7.43.0.5         py37hb62a520_3    conda-forge
pydocstyle                5.1.1                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyface                    7.1.0              pyh9f0ad1d_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pyfmi                     2.7.4            py37h3a3b6f7_0    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pylint                    2.6.0            py37hc8dfbb8_1    conda-forge
pymeeus                   0.3.7              pyh9f0ad1d_0    conda-forge
pynacl                    1.4.0            py37h230ea1a_2    conda-forge
pyodbc                    4.0.30           py37h1834ac0_1    conda-forge
pyomo                     5.7.1                    pypi_0    pypi
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py37h37b0502_1    conda-forge
pyqt                      5.12.3           py37h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyreadline                2.1             py37hc8dfbb8_1002    conda-forge
pyrsistent                0.17.3           py37h4ab8f01_1    conda-forge
pyshp                     2.1.2              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py37hf50a25e_2    conda-forge
pytables                  3.6.1            py37h2d87964_2    conda-forge
pytest                    6.1.1            py37hc8dfbb8_1    conda-forge
python                    3.7.8           h60c2a47_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.35.1                     py_0    conda-forge
python-libarchive-c       2.9              py37hf50a25e_2    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyutilib                  6.0.0                    pypi_0    pypi
pyviz_comms               0.7.6              pyh9f0ad1d_0    conda-forge
pywavelets                1.1.1            py37h3a3b6f7_3    conda-forge
pywin32                   228              py37h4ab8f01_0    conda-forge
pywin32-ctypes            0.2.0           py37hc8dfbb8_1002    conda-forge
pywinpty                  0.5.7            py37hc8dfbb8_1    conda-forge
pyyaml                    5.3.1            py37h0013d47_1    conda-forge
pyzmq                     19.0.2           py37h453f00a_2    conda-forge
qdarkstyle                2.8.1              pyh9f0ad1d_1    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtawesome                 1.0.1              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rasterio                  1.1.7            py37hce843d0_0    conda-forge
regex                     2020.10.15       py37h4ab8f01_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h301d43c_1    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py37h804a536_1    conda-forge
ruamel_yaml               0.15.80         py37h0013d47_1003    conda-forge
scikit-image              0.17.2           py37h414f9d2_3    conda-forge
scikit-learn              0.23.2           py37h82ce443_1    conda-forge
scikit-optimize           0.7.4                      py_0    conda-forge
scipy                     1.5.2            py37h9439919_0
seaborn                   0.11.0                        0    conda-forge
seaborn-base              0.11.0                     py_0    conda-forge
selenium                  3.141.0         py37h8055547_1001    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37hf50a25e_2    conda-forge
setuptools-scm            4.1.2              pyh9f0ad1d_0    conda-forge
shapely                   1.7.1            py37h82f916b_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3         pyh9f0ad1d_1001    conda-forge
sip                       4.19.24          py37h1834ac0_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcollections         1.2.1              pyh9f0ad1d_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sphinx                    3.2.1                      py_0    conda-forge
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
spyder                    4.1.5            py37hc8dfbb8_0    conda-forge
spyder-kernels            1.9.4            py37hc8dfbb8_0    conda-forge
sqlalchemy                1.3.20           py37h4ab8f01_0    conda-forge
sqlite                    3.33.0               he774522_1    conda-forge
statsmodels               0.12.0           py37h3a3b6f7_1    conda-forge
sundials                  5.2.0                h33f27b4_1    conda-forge
sympy                     1.6.2            py37hc8dfbb8_1    conda-forge
tbb                       2020.1               he980bc4_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.1            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2020.10.1                  py_0    conda-forge
tiledb                    2.0.8                h71c485d_1    conda-forge
tk                        8.6.10               he774522_1    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.0.4            py37h4ab8f01_2    conda-forge
tqdm                      4.50.2             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
traits                    6.1.0            py37h4ab8f01_1    conda-forge
traitsui                  7.1.0              pyh9f0ad1d_0    conda-forge
typed-ast                 1.4.1            py37hfa6e2cd_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
ujson                     4.0.1            py37h1834ac0_1    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
vtk                       8.2.0           py37h359a0f6_218    conda-forge
watchdog                  0.10.3           py37hc8dfbb8_2    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py37hc8dfbb8_4    conda-forge
win_inet_pton             1.1.0            py37hc8dfbb8_1    conda-forge
win_unicode_console       0.5             py37hc8dfbb8_1001    conda-forge
wincertstore              0.2             py37hc8dfbb8_1005    conda-forge
windrose                  1.6.7                      py_1    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.11.2           py37h4ab8f01_1    conda-forge
xarray                    0.16.0                     py_0    conda-forge
xerces-c                  3.2.3                ha925a31_1    conda-forge
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xlsxwriter                1.3.7              pyh9f0ad1d_0    conda-forge
xlwings                   0.20.8           py37hc8dfbb8_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.2                ha925a31_4    conda-forge
zfp                       0.5.5                ha925a31_4    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.3.1                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zope                      1.0                      py37_1
zope.event                4.5.0              pyh9f0ad1d_0    conda-forge
zope.interface            5.1.2            py37h4ab8f01_1    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge
</details>

**Provide a complete minimal reproducible example**
```python
r"""Reproduce unclosed file warning.

ox.geometries_from_polygon() causes the following warning:

C:\Users\***\anaconda3\lib\site-packages\pyreadline\lineeditor\history.py:82:
    ResourceWarning:
        unclosed file <_io.TextIOWrapper
        name='C:\\Users\\***\\.python_history' mode='r' encoding='cp1252'>
  for line in open(filename, 'r'):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
"""

import shapely
import osmnx as ox

buildings = {'building': ['apartments', 'commercial', 'detached', 'house',
                          'industrial', 'residential', 'retail']}

# Define a bounding box polygon from a list of lat/lon coordinates
bbox = [(9.1008896, 54.1954005),
        (9.1048374, 54.1961024),
        (9.1090996, 54.1906397),
        (9.1027474, 54.1895923)]
polygon = shapely.geometry.Polygon(bbox)

gdf_poly_houses = ox.geometries_from_polygon(polygon, tags=buildings)
```

**Comment by gboeing** [comment]
How are you running your code? Terminal? Jupyter notebook?

**Comment by jnettels** [comment]
Sorry for not getting back to you earlier. I encountered this issue when running in a Windows cmd terminal. (And this is the first time I have ever seen this warning.) However, when using the iPython console built into Spyder, this issues does not appear. Anyway: If you cannot reproduce it, then I guess this is somehow an isolated problem of mine.
Thanks for looking into it, this is much appreciated.
