### ISSUE TITLE
Use `pathlib.Path` for directory and file operations

### ISSUE THREAD

**Issue by eumiro** [gboeing/osmnx#608]
Since `osmnx` is now a Python 3.6+ project, there are several features of the language that allow us to write better and more readable code. One of them is [pathlib](https://docs.python.org/3/library/pathlib.html) that can replace most `os.path/glob/fnmatch` calls.

I have started the PR #606 that changes only internal code and private methods. What do you think about it? And how about updating the public interface as well?

**Comment by gboeing** [comment]
Thanks @eumiro. Yes I think consolidating around `pathlib` would be a good idea at this point. #606 has some force-pushed commits so I'm going to close it. Could you open a new PR (make sure you're working off the current master branch)? I think updating the public functions to accept `string` or `Path` objects would make sense too. I'd like to get this in before v1.0 goes through its final tests (starting late next week) before release.

**Comment by eumiro** [comment]
Thank you, @gboeing . Please see #610 .

**Comment by gboeing** [comment]
Thank you. Closed by #610 and #614.
