### ISSUE TITLE
Adding a "via" to shortest_path

### ISSUE THREAD

**Issue by asongtoruin** [gboeing/osmnx#621]
**Is your feature proposal related to a problem?**
At present, the `shortest_path` function allows for the calculation of a shortest path between two nodes and two nodes only. In some circumstances, it would be useful to add in one or more "via" nodes to, for example, compare the length of OD journeys via different routes.

**Describe the solution you'd like to propose**
Pseudocode at present (though I'm happy to work up a PR if this is a feature you're open to):
- add a `via` parameter to `shortest_path` that takes the form of one of:
  - `int`
  - iterable of `int`s
  - `None` (default)
- if `None` is passed simply use existing code
- otherwise accumulate routes through calls to `shortest_path` with `via=None` for consecutive pairs (origin to first via node, first via node to second via node etc)

**Describe alternatives you've considered**
At present this can be done by having the user apply the logic themselves, e.g. for `a` to `c` via `b`

```python
route = ox.shortest_path(G, a, b)
route += ox.shortest_path(G, b, c)[1:]
```

But this could get a bit convoluted if many routes are being passed, or if there are many via nodes. What do you think?

**Comment by gboeing** [comment]
Thanks for the suggestion. The `shortest_path` function is really just a wrapper around networkx's equivalent function. It seems to me that this is simple enough to do oneself, so I'm not sure it adds value to put it into the package itself. As you demonstrated: the shortest path from `a` to `c` via `b` is simply the shortest paths from `a` to `b` and from `b` to `c`. That's just one line of code for the user either way:

```python
route = ox.shortest_path(G, a, b) + ox.shortest_path(G, b, c)[1:]
```
