### ISSUE TITLE
ERROR: No matching distribution found for pandas>=1.2 (from osmnx)

### ISSUE THREAD

**Issue by ppgiii** [gboeing/osmnx#636]
Hello,

Two weeks ago, everything was fine but not today.  I am using Google Colab to install osmnx and do some analysis.  I tried the following:
!apt install libspatialindex-dev
!pip install rtree

everything installed fine.   Then,
!pip install osmnx
I get the error:

Collecting osmnx
  Using cached https://files.pythonhosted.org/packages/6c/93/39e046e826cfa8e9936a81532fc389bfbc5e1c891ed5eea84766a3b242ed/osmnx-1.0.0-py2.py3-none-any.whl
Collecting matplotlib>=3.3
  Using cached https://files.pythonhosted.org/packages/d2/43/2bd63467490036697e7be71444fafc7b236923d614d4521979a200c6b559/matplotlib-3.3.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyproj>=2.6
  Using cached https://files.pythonhosted.org/packages/e4/ab/280e80a67cfc109d15428c0ec56391fc03a65857b7727cf4e6e6f99a4204/pyproj-3.0.0.post1-cp36-cp36m-manylinux2010_x86_64.whl
Requirement already satisfied: Shapely>=1.7 in /usr/local/lib/python3.6/dist-packages (from osmnx) (1.7.1)
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.6/dist-packages (from osmnx) (1.19.4)
Collecting geopandas>=0.8
  Using cached https://files.pythonhosted.org/packages/f7/a4/e66aafbefcbb717813bf3a355c8c4fc3ed04ea1dd7feb2920f2f4f868921/geopandas-0.8.1-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement pandas>=1.2 (from osmnx) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 0.25.0rc0, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0rc0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0rc0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
ERROR: No matching distribution found for pandas>=1.2 (from osmnx)

Thank you.

**Comment by gboeing** [comment]
Try to `pip` install each of OSMnx's [requirements](https://github.com/gboeing/osmnx/blob/master/requirements.txt) one at a time prior to installing OSMnx itself.

**Comment by ppgiii** [comment]
Hello,

The Colab notebook's default setting uses Python version is 3.6.9.  For Pandas 1.2.0, if I read it right requires Python 3.7.  I kept trying Colab to use Python 3.7 but I cannot.  I used another method but I prefer Colab.  I will try that solution when I have more time, in a rush at this time.  Thanks.

**Comment by gboeing** [comment]
I'm going to close this as it appears to just be a matter of meeting `pandas`'s minimum python version requirement.

**Comment by vaduraes** [comment]
Hi, try:   "!pip install osmnx==0.16.2" in the current Colab version. It will do the trick

**Comment by gboeing** [comment]
I'm going to bump the pandas requirement down to >=1.1 for the forthcoming release of OSMnx v1.0.1, so that'll fix it for now.

**Comment by ppgiii** [comment]
@vaduraes , yes, I tried that version and it worked.  With v1.0.1, I can just use it normally.  Thank you. @gboeing

**Comment by ppgiii** [comment]
@gboeing , I thought to let you know that Colab has moved to Python v3.7.10 so I tested OSMnx v1.0.0, the original problem I had, and it installed and ran fine.  It seems normal now for updated versions.  For Azure build I tested, it is still using Python 3.6.9 unfortunately.

**Comment by gboeing** [comment]
Thanks. I'm planning to maintain compatibility with Python 3.6.x for the next release (1.1.x) before dropping it.
