### ISSUE TITLE
Sample points uniformly at random from the road network

### ISSUE THREAD

**Issue by haossr** [gboeing/osmnx#639]
**Problem**
In urban computing/computational social science, a lot of statistical inference problem asks for uniformly random samples from the road network.  

For example, to estimate the number of utility poles or vehicles, researchers need to first get `n` point from the road network, evaluate them either manually or algorithmically, and then infer the total numbers by multiplying the length of the road network proportionally.

Noticing this is not equivalent to spatially uniformly random samples (which completely ignore the road network) or [equal length segmenting](https://gis.stackexchange.com/questions/17433/segment-road-network-line-shapefile-into-new-equal-length-segments-line-shapefil) (which does not guarantee the favorable statistical property). 

It would cost the user who needs this feature a significant amount of time to implement the sampling logic:
1. Unroll the network into LineStrings
2. Ensure the projection of the LineStrings and calculate the length `l_i`
3. Calculate the sum of the lengths `L` 
4. Draw 1-D uniformly random sample on `[0, L)`
5. Pick up the corresponding LineString
6. Calculate the point coordinates based on the distance from one end of the LineString

**Describe the solution you'd like to propose**

I am suggesting to introduce a module of `osmnx.random`, which for now include a sampling function:
```
osmnx.random.sample_point(G, size=None, replace=True, weights=None)
```
, which returns a list of shapely Points. Here `weights` stands for the edge attributes user could use sampling weights. 

Alternatively, we could return a geopandas DataFrame including all sampled points. 

Let me know how this sounds.
I am happy to give it a stab as this is part of my research anyway. Thank you so much!

**Comment by gboeing** [comment]
This sounds like a generally useful feature but I'm not totally sure of its fit and function. A couple questions:

  1. Is OSMnx the right location for this function? As it sounds more like a generic network-constrained spatial sampling problem, it may fit better elsewhere (though I'm not sure where... maybe shapely, pysal, etc). In particular, it's easy to dump an OSMnx graph to LineStrings for this kind of work. I'm not sure this is the right home for it.
  2. What is the sampling frame? All edges? Every edge has its own LineString geometry.
  3. I don't totally understand the bridge between steps four and five... but this partly goes back to the previous question. Perhaps some sample code would help to elucidate the proposed steps?

**Comment by haossr** [comment]
Thanks for your reply. Here is my response for 1&2:
1. I have been thinking of other packages such as `shapely`/`network`/`pysal` but it seems they are not dealing with this road network data structure (multigraph with edges associated with a LineString geometry). It is totally possible to dump the edges and do the work manually outside osmnx (that's what I am currently doing now). I agree it is not directly related to OSM but could be a nice util function that is easy to get wrong (in the sense of corrupting the uniformly at random statistical property) 
2&3. We try to come up with the sampling frame that each point on the road network is of equal probability being sampled (regardless of the density). So we first sample one LineString from all with a probability proportional to its length and then sample a random point on the LineString. Here is an example of the implementation:
```python
def sample_points(edges, n=100):
    m = len(edges)
    lengths = edges['length'].tolist()
    total_length = edges.sum()['length']
    lengths_normalized = [l/total_length for l in lengths] 
    
    indices = np.random.choice(range(m), 
                     size=n, 
                     p=lengths_normalized)
    points = []
    for index in indices:
        line = gdf.iloc[index]['geometry']
        offset = np.random.rand() * line.length
        point = line.interpolate(offset)
        points.append(point)
        
    return MultiPoint(points)
```

**Comment by gboeing** [comment]
I believe your function could be streamlined and vectorized:

```python
import numpy as np
import osmnx as ox

def sample_points(edges, n=100):
    p = edges['length'] / edges['length'].sum()
    idx = np.random.choice(edges.index, size=n, p=p)
    lines = edges.loc[idx, 'geometry']
    return lines.interpolate(lines.length * np.random.rand())

# test the sampler
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
points = sample_points(ox.graph_to_gdfs(ox.project_graph(G), nodes=False))
```

Something like this may be a useful addition to the `utils_graph` module.

**Comment by gboeing** [comment]
Here's a potentially better version, that takes a graph as the argument (keeping it more consistent with how the rest of the API works):

```python
import numpy as np
import osmnx as ox

def sample_points(G, n):
    gdf_edges = ox.graph_to_gdfs(G, nodes=False)[['geometry', 'length']]
    weights = gdf_edges['length'] / gdf_edges['length'].sum()
    idx = np.random.choice(gdf_edges.index, size=n, p=weights)
    lines = gdf_edges.loc[idx, 'geometry']
    return lines.interpolate(lines.length * np.random.rand())

# test the sampler (use a projected graph for most accurate results)
G = ox.project_graph(ox.graph_from_place('Piedmont, CA, USA', network_type='drive'))
points = sample_points(G, 100000)
```

**Comment by gboeing** [comment]
@haossr did the code snippet I provided above work for your use case? Would you like to contribute it as a PR?

**Comment by haossr** [comment]
> @haossr did the code snippet I provided above work for your use case? Would you like to contribute it as a PR?

That looks awesome! Thanks for vectorized it -- I can flesh out the details for a PR. : )

**Comment by gboeing** [comment]
@carlhiggs @shiqin-liu this graph-constrained random spatial sampling may be of particular interest to you.

**Comment by gboeing** [comment]
@haossr let me know if you'd like to contribute this as a PR. I'm planning to wrap up feature dev for v1.1 in the coming weeks before moving to testing in advance of release.

**Comment by gboeing** [comment]
I've added this feature in #687.

**Comment by haossr** [comment]
Sorry for not being able to work on it -- thanks for including this feature!

**Comment by gboeing** [comment]
@SujitPattanayak please reread the contributing guidelines regarding the appropriate use of this issue tracker and where to ask how-to usage questions instead.
