### ISSUE TITLE
Can I use Osmnx to visualize moving entities ?

### ISSUE THREAD

**Issue by Deejep** [gboeing/osmnx#65]
Hi,
I would like to know if Osmnx allows the visualization of moving entities like pedestrians , cars, etc...
If not, what tool would you recommend using instead?
Cheers,

**Comment by gboeing** [comment]
Yes. OSMnx produces a networkx multidigraph. Networkx can analyze and model network dynamics. For more, check out [their documentation](https://networkx.github.io/).

**Comment by Deejep** [comment]
Thank you!

**Comment by Deejep** [comment]
I have searched the networkx documentation, and it looks like the visualization features are not that advanced especially in space-time. 
The visualization I am trying to build is like this [one](https://mbtaviz.github.io/) in the header that uses d3.js.
I don't think of any other alternatives except loading the svg city file from d3, and continue working this it.
