### ISSUE TITLE
graph_from_place stucks

### ISSUE THREAD

**Issue by adhamenaya** [gboeing/osmnx#653]
I am using the following lines of code to download street network for relatively small city and it stuck. I left it for hours and it did not finish. Is there a way to see the log or progress of download?

- The NetworkX package is version 2.4
- The OSMNX package is version 0.14.1
- The Request package is version 2.23.0

```
import osmnx as ox
import networkx as nx
import requests

places = ["Amman","Jordan"]
G = ox.graph_from_place(places, network_type="all", simplify=True)
```

**Comment by gboeing** [comment]
> Is there a way to see the log or progress of download?

Yes. Use `ox.config(log_console=True)` as described in the [docs](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples). If this is a "how-to" usage question, better to ask on StackOverflow as per the contributing guidelines.

> The OSMNX package is version 0.14.1

This is a pretty old version of the package. Try upgrading to the current version, 1.0.1.

**Comment by adhamenaya** [comment]
> Yes. Use `ox.config(log_console=True)` as described in the [docs](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples). If this is a "how-to" usage question, better to ask on StackOverflow as per the contributing guidelines.
> 

Thank you for your reply, and pardon if I am not posting in the right place. But can you tell where I can see the log result., the docs is says it display in the terminal.
