### ISSUE TITLE
network_type "drive" leaves edges with highway=bus_guideway

### ISSUE THREAD

**Issue by guibar** [gboeing/osmnx#659]
After a call such as:

osmnx.graph.graph_from_bbox(bbox[0], bbox[1], bbox[2], bbox[3], network_type='drive', simplify=True, retain_all=False, truncate_by_edge=True, clean_periphery=True)

I end up with a graph which has some edges with tag "highway=bus_guideway" which is a valid tag but not for driving:

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_guideway

I think it is just a matter to exclude that tag in the drive filter. 
I have edited the filter to be:

filters["drive"] = (
        f'["highway"]["area"!~"yes"]{settings.default_access}'
        f'["highway"!~"abandoned|bridleway|construction|corridor|cycleway|elevator|'
        f"escalator|footway|path|pedestrian|planned|platform|proposed|raceway|service|"
        f'steps|track|bus_guideway"]'
        f'["motor_vehicle"!~"no"]["motorcar"!~"no"]'
        f'["service"!~"alley|driveway|emergency_access|parking|parking_aisle|private"]'
    )

and the edges are not there anymore.

**Comment by gboeing** [comment]
Thanks. Would you like to open a pull request for this?

**Comment by guibar** [comment]
Yes, I will do this tomorrow.
