### ISSUE TITLE
OSM did not return any polygonal geometries for query

### ISSUE THREAD

**Issue by fazaghifari** [gboeing/osmnx#663]
Hi Everyone!

I'm new to OSMnx. I was trying to use `geometries_from_place` with query = `Jakarta, Indonesia` but it returns `OSM did not return any polygonal geometries for query`. As far as I can remember, when I executed this code last Friday (February 26, 2021) it worked just fine. But when I execute the code this evening, OSMnx returns `ValueError: OSM did not return any polygonal geometries for query "Jakarta, Indonesia"`.  But strangely, it worked for other cities (e.g "Surabaya, Indonesia")

I'm using osmnx 1.0.1 both on my PC on windows and I also have tried executing the code using google colab.

Is there any change in the query? Where can I find the query references?

Here's the code:  
```python
import osmnx as ox
tags = {'amenity': 'cafe'}
cafe = ox.geometries_from_place("Jakarta, Indonesia", tags)
print(len(cafe))
```

Thanks in advance

**Comment by gboeing** [comment]
Thanks @fazaghifari. See resolution in #664. The `graph` module currently has clearer documentation in the `graph_from_place` docstring on how to change your place query when this happens. #664 adds this clearer documentation to the `geometries` module.
