### ISSUE TITLE
ValueError: OSM returned fewer than `which_result=2` results for query "{'state': 'Illinois', 'country': 'USA'}"

### ISSUE THREAD

**Issue by korasami96** [gboeing/osmnx#666]
**Problem description**
  - I am using the package OSMNX in python and trying to get the street network of the state of Illinois.  
  - But i got an error message (See in the details).
  <details> ValueError: OSM returned fewer than `which_result=2` results for query "{'state': 'Illinois', 'country': 'USA'}" </details>

**Environment information**
  - Operating system: Windows
  -Python version: Python 3.7.6 
  

```python
import osmnx as ox
place_query = {'state':'Illinois', 'country':'USA'}
G = ox.graph_from_place(place_query, network_type='drive',which_result=2)


```

**Comment by gboeing** [comment]
Cross-post of "how-to" usage question at https://stackoverflow.com/questions/66502325/package-osmnx-in-python
