### ISSUE TITLE
nodes visualization with betweenness centrality

### ISSUE THREAD

**Issue by shiqingzhangCSU** [gboeing/osmnx#667]
- What did you do?
  - the node with the highest betweenness centrality has ~30% of all shortest paths running through it. Highlighting it in the plot.
![image](https://user-images.githubusercontent.com/44834482/110206255-90e56600-7eb7-11eb-9f86-4690ae1094de.png)

  - And what actually happened instead?
  - The code in the document does not reflect 30% of the parameters。
```python code

G_projected = ox.project_graph(G)
max_node, max_bc = max(extended_stats['betweenness_centrality'].items(), key=lambda x: x[1])
max_node, max_bc 
nc = ['r' if node==max_node else 'w' for node in G_projected.nodes()]
ns = [80 if node==max_node else 15 for node in G_projected.nodes()]
fig, ax = ox.plot_graph(G_projected, node_size=ns, node_color=nc, node_zorder=2, bgcolor='k')
nx.set_node_attributes(G, extended_stats['betweenness_centrality'], 'bc')
nc = ox.plot.get_node_colors_by_attr(G, 'bc', cmap='plasma')
fig, ax = ox.plot_graph(G, node_color=nc, node_size=30, node_zorder=2,edge_linewidth=0.2, edge_color='w', bgcolor='k')
```

**Comment by gboeing** [comment]
If this is an issue with the code or markdown description in the usage example, please open an issue at the relevant repository: https://github.com/gboeing/osmnx-examples If you do, please make it clear what exactly the issue is and what fix is needed.
