### ISSUE TITLE
Drawing graphml vertices to images 

### ISSUE THREAD

**Issue by Deejep** [gboeing/osmnx#67]
The graphml vertices have only the longitude and latitude data. How to draw them on an image without using your save-to-svg option? 

Should I convert them to cartesian coordiantes (x,y) ?

**Comment by gboeing** [comment]
This isn't really an OSMnx issue. You'd plot these vertices the same way you'd plot any geographic data. You could either plot them as lat-long points or you could project them to another coordinate system and then plot them. It completely depends on what you're trying to do with the image.

This issue tracker is primarily for flagging bugs/problems or for suggesting specific new functionality. For general purpose questions about using OSMnx or general geospatial coding in Python, https://stackoverflow.com/ is your best friend.
