### ISSUE TITLE
get_nearest_edges(): More meaningfull error when passing in NaNs for X and Y

### ISSUE THREAD

**Issue by McToel** [gboeing/osmnx#676]
## Problem
When using `get_nearest_edges(method='kdtree')` with `NaNs` in `X` and `Y`, the function raises the following `KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported.`
It is expected that the function fails for `NaNs`, but there could be a more explicit error message.

## Possible solutions
I have 3 proposals on how to make the error more explicit:
- Check for `X` and `Y` `NaNs` and then raise an exception
- Catch the `KeyError` to raise another exception
- Add a description to the docstring that the `KeyError` is a result of `NaNs`

Of course, this is not a must-have, but I saw that for Version 1.1.0 the distance module is getting a redesign and this might be something to consider.

**Comment by gboeing** [comment]
Thanks for flagging this. Should be fixed in the `distance` module refactoring, in 099ebd9e6fa98652888a25a07fca42d2f1f09e0b.
