### ISSUE TITLE
Why preserve self loops?

### ISSUE THREAD

**Issue by kaseyklimes** [gboeing/osmnx#68]
Just a question about the `build_path` function in the simplify.py module.

You've written an if statement to identify and preserve the nodes in self loops, but (I'm pretty sure) the vast majority of self loops in the OSM road network represent cul-de-sacs. For most purposes I'd consider these to be the same as endpoints (at the very least don't represent real intersections).

Before I go tinkering with your script to change that for my purposes I was curious what your thinking was here and if perhaps there's something I'm missing. Thanks!

**Comment by gboeing** [comment]
There are a decent number of self-loops in a street network's graph, such [as here](https://www.openstreetmap.org/#map=19/33.29999/-111.83163). Some represent the intersection of 3 or 4 street segments. Some loops are very long (some suburban areas have 200m loops). Either way, if we break them, we get an inaccurate representation of the topology and can break accessibility to parcels along the loop.

**Comment by kaseyklimes** [comment]
I see, thanks for explaining!
