### ISSUE TITLE
Is it possible to filter by public transit?

### ISSUE THREAD

**Issue by JoshuaKissel** [gboeing/osmnx#680]
**Read these instructions carefully**

Please don't use the issue tracker to ask "how-to" or usage questions. If asked here, they will be closed automatically. Instead, ask "how-to" and usage questions on [StackOverflow](https://stackoverflow.com/).

Feature requests are for proposing an enhancement to OSMnx before opening a pull request to add your proposed functionality to the codebase. Your issue will be closed automatically if you don't provide the requested information that we need below. Before you proceed, review the contributing guidelines in this repo's CONTRIBUTING.md file.

**Is your feature proposal related to a problem?**

I was wondering if it is possible to filter just public transit (ie- Chicago el train, NYC subway)

**Describe the solution you'd like to propose**

Add filter to osmnx.graphy_from_place(network_type="")

**Describe alternatives you've considered**

None

**Additional context**

`import osmnx as ox

place = ["Chicago.Illinois.USA"]
G = ox.graph_from_place(place, retain_all=True, simplify = True, network_type='all')`

**Comment by gboeing** [comment]
> I was wondering if it is possible to filter just public transit

Yes this is possible. Per the contributing guidelines and new issue template, best to ask "how-to" and usage questions on StackOverflow.
