### ISSUE TITLE
Cannot Retrieve u, v nodes of edges geo data frame

### ISSUE THREAD

**Issue by anjulapaulus** [gboeing/osmnx#689]
@gboeing 
I need to get the u, v nodes from the edge dataframe.  I used the below code to check on the data present. I that I was able to see the u, v , key columns.

` import networkx as nx
g = nx.Graph()

G = ox.graph_from_place('New York, USA', network_type='drive')
nodes, edges = ox.graph_to_gdfs(G)

edges.head(10) `

![Head](https://user-images.githubusercontent.com/50554498/112751119-ea8a0d80-8fe9-11eb-9152-0491dde21821.png)

When I checked the columns in the edges dataframe. I cannot see the u, v node columns. 

![Columns](https://user-images.githubusercontent.com/50554498/112751192-3b016b00-8fea-11eb-8f8e-02e7be59a1c6.png)

Is there a way i could get the edge nodes? I need it to create a new graph in Networkx.

Thanks in Advance!

**Comment by gboeing** [comment]
Hi @anjulapaulus the node u, v, and key are in the GeoDataFrame index. Please reread the OSMnx documentation. And please reread the new issue template: you can ask usage questions on StackOverflow.

**Comment by anjulapaulus** [comment]
Hi @gboeing, Really sorry for the inconvenience caused. Ill look into it. Thanks for your response.
