### ISSUE TITLE
Can I load parts of the city according to their landuse ?

### ISSUE THREAD

**Issue by Deejep** [gboeing/osmnx#70]
Hi,
Can I use Osmnx to filter city areas according to whether or not they are residential / commercial ?

**Comment by gboeing** [comment]
OSMnx does not provide this functionality out of the box. This issue tracker is for flagging bugs/problems or for suggesting specific new functionality. For general purpose questions about using OSMnx, OpenStreetMap, NetworkX, or general geospatial coding in Python, https://stackoverflow.com/ is your best bet. For information about OSMnx's capabilities, they are fully documented in [the docs](https://osmnx.readthedocs.io/en/stable/) and demonstrated in [the examples](https://github.com/gboeing/osmnx/tree/master/examples).
