### ISSUE TITLE
get_nearest_node returning distant nodes

### ISSUE THREAD

**Issue by kaseyklimes** [gboeing/osmnx#71]
The `.get_nearest_node` method returns a node within the graph but nowhere near the original point. The [point below](http://www.openstreetmap.org/#map=18/42.9962/-78.9571) returns a [node here](http://www.openstreetmap.org/node/111511849#map=18/42.95945/-78.90726). May be a projection issue but projecting the graph differently didn't fix it.

Using OSMnx 0.5.2dev in python 2.7 on a Mac.

```python
import osmnx as ox, networkx as nx
ox.config(log_console=True, use_cache=True)
G = ox.graph_from_place('Buffalo, New York, USA', network_type='walk')

orig_point = (42.99618326, -78.957126)

orig_node = ox.get_nearest_node(G, orig_point)

print orig_node
```

**Comment by gboeing** [comment]
It looks like it's working properly... that point you specified is about 5.7km away from the city limits. First we construct the graph:

```python
import osmnx as ox
ox.config(log_console=True, use_cache=True)
G = ox.graph_from_place('Buffalo, New York, USA', network_type='walk')
```

Then we find the nearest node to a point in central Buffalo:

```python
point1 = (42.891310, -78.871355)
ox.get_nearest_node(G, point1, return_dist=True)
```

This returns the node and its distance from that point, which is 11 meters. Try it again, with your point:

```python
point2 = (42.99618326, -78.957126)
ox.get_nearest_node(G, point2, return_dist=True)
```

This returns the node and its distance from your point, which is 5698 meters. I'll update the docstring to specify that the distance units are in meters... but it looks like it's working properly.

**Comment by gboeing** [comment]
Clarified usage in 29005df and dd32fa2

**Comment by kaseyklimes** [comment]
Of course, dumb oversight on my end. The problem in the "production" version of my code then must be a projection issue – my point data is all in 2163, but when I project the graph (of the entire metro area, not just Buffalo) using `G = ox.project_graph(G, to_crs={'init': 'epsg:2163'})` I get random and distantly placed results as well. I can just project the data to 4326 but I'm curious why this isn't working.

**Comment by gboeing** [comment]
The nearest node calculator uses [great circle](https://en.wikipedia.org/wiki/Great-circle_distance) distances to find the nearest node. I updated the docstring in dd32fa2 to point out that the point and the network nodes' coordinates must be in decimal degrees, as planar projected geometries don't make sense in a great circle distance calculation.

However, it might be useful to add a euclidean distance calculator as well for finding nearest nodes in a projected graph.

**Comment by gboeing** [comment]
Ok, added the ability to get nearest node with projected graphs (that is, by euclidean distance) in 4f9cb926341c41977f1e58c4163e342f4fd32369

Check it out and let me know if it works properly for your use case.

**Comment by gboeing** [comment]
@kaseyklimes is that working for you?

**Comment by kaseyklimes** [comment]
@gboeing It doesn't appear to be. This point at Buffalo City Hall returns a node about 3.5 miles north at SUNY college.

`0.5.2dev (2721479675, 134460.9431565048)`
```python
import osmnx as ox, networkx as nx
ox.config(log_console=True, use_cache=True)
G = ox.graph_from_place('Buffalo, New York, USA', network_type='walk')
G = ox.project_graph(G, to_crs={'init': 'epsg:2163'})

center_node = ox.get_nearest_node(G, (1697219.79349577, -13324.947275372), return_dist=True)

print ox.__version__ , center_node```

**Comment by gboeing** [comment]
@kaseyklimes see [the documentation](https://osmnx.readthedocs.io/en/latest/osmnx.html#osmnx.utils.get_nearest_node) for this function: if the graph is projected, you should use the 'euclidean' `method` instead of the default 'greatcircle' method. Also, note that the `point` argument is passed as a tuple of (lat, lng) if in degrees or (y, x) if in projected planar units such as meters. This is kind of weird, but I think it's necessary: we consistently treat degree coordinates as (lat, lng) and there may be times when we want to calculate euclidean distances between them. In which case, both algorithms (euclidean and great circle) must accept a consistent point format... (lat, lng) is equivalent to (y, x).

So, if we specify a (y, x) point and use the euclidean method:

```python
import osmnx as ox, networkx as nx
ox.config(log_console=True, use_cache=True)
G = ox.graph_from_place('Buffalo, New York, USA', network_type='walk')
G = ox.project_graph(G, to_crs={'init': 'epsg:2163'})
center_point = (-13324.947275372, 1697219.79349577) #this tuple should be (y, x), like (lat, lng)
center_node, distance = ox.get_nearest_node(G, center_point, method='euclidean', return_dist=True)
print(distance)
```

Prints 0.454... so the nearest node is only half a meter from the point you specified.

**Comment by kaseyklimes** [comment]
RTFM Kasey, RTFM. Thanks Geoff 👍

**Comment by gboeing** [comment]
Regarding (lat, lng) and (y, x) coordinate tuples' order, see also [ISO 6709](https://en.wikipedia.org/wiki/ISO_6709)

**Comment by kuanb** [comment]
~3:20 in the morning and, reading through this, I follow the exact same series of errors eventually reach the same conclusion. 😛

**Comment by kuanb** [comment]
(To clarify the above and provide some useful feedback)

When you use `get_nearest_node` on a graph that has been reprojected, using the default `great_circle` method will return incorrect results. What need to be done is to ensure that one uses `euclidean` at this step.

**Comment by gboeing** [comment]
@kuanb that's right. [Great circle](https://en.wikipedia.org/wiki/Great-circle_distance) distance measures distances along the surface of a sphere while [euclidean](https://en.wikipedia.org/wiki/Euclidean_distance) distance measures it along a two dimensional plane. Lat-long data is in spherical units of degrees: it represents points on the surface of a sphere (or an approximate spheroid). If you project your lat-long data to two-dimensional planar units such as meters, great circle distance no longer makes sense: you need to use a planar metric such as Euclidean distance.

**Comment by kuanb** [comment]
Right - mostly an error of working on something at 3/4 in the morning instead of sleeping. 😛  Might be too much of magic but would checking `G.graph['crs']` and emitting a warning that the crs being used is in meter project but great-circle be too much? As I write it, it sounds overwrought. Maybe just having this observation here, in the issues, is sufficient.

**Comment by mbforr** [comment]
Having a similar issue here with a graph I created in NetworkX for custom routes and nodes from two GeoDataFrames. It is a `MutliDiGraph` and the issue I am seeing now is just an error with 'x':

```python
print(G.graph['crs'])

origin_point = (ARR_AND_DEP.iloc[0].lat, ARR_AND_DEP.iloc[0].lng)
destination_point = (ARR_AND_DEP.iloc[1].lng, ARR_AND_DEP.iloc[1].lat)

print(origin_point)

center_node, distance = osmnx.get_nearest_node(G, origin_point, method='euclidean', return_dist=True)
print(distance)
```

output:
```python
{'init': 'epsg:54032'}
(11377063.5861887, 5103089.8716958)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-194-aec8f795a237> in <module>
      6 print(origin_point)
      7 
----> 8 center_node, distance = osmnx.get_nearest_node(G, origin_point, method='euclidean', return_dist=True)
      9 print(distance)
     10 

/opt/conda/lib/python3.7/site-packages/osmnx/utils.py in get_nearest_node(G, point, method, return_dist)
    459     # dump graph node coordinates into a pandas dataframe indexed by node id
    460     # with x and y columns
--> 461     coords = [[node, data['x'], data['y']] for node, data in G.nodes(data=True)]
    462     df = pd.DataFrame(coords, columns=['node', 'x', 'y']).set_index('node')
    463 

/opt/conda/lib/python3.7/site-packages/osmnx/utils.py in <listcomp>(.0)
    459     # dump graph node coordinates into a pandas dataframe indexed by node id
    460     # with x and y columns
--> 461     coords = [[node, data['x'], data['y']] for node, data in G.nodes(data=True)]
    462     df = pd.DataFrame(coords, columns=['node', 'x', 'y']).set_index('node')
    463 

KeyError: 'x'
```

The function I used to create the graph is as follows:

```python
def gdf_to_nx(gdf_network):
    # generate graph from GeoDataFrame of LineStrings
    net = nx.MultiDiGraph()
    net.graph['crs'] = gdf_network.crs
    fields = list(gdf_network.columns)

    for index, row in gdf_network.iterrows():
        first = row.geometry.coords[0]
        last = row.geometry.coords[-1]

        data = [row[f] for f in fields]
        attributes = dict(zip(fields, data))
        net.add_edge(first, last, **attributes)

    return net

G = gdf_to_nx(ALL_ROUTES)
```

Any ideas would be great!

**Comment by gboeing** [comment]
Without a reproducible code snippet it's a bit hard to guess what's happening here, but my guess would be that you don't have an 'x' column in your geodataframe and therefore you don't end up having one in your graph.

**Comment by mbforr** [comment]
The complete code is listed here along with the file I am using to create the graph:

```python
ALL_ROUTES = gpd.read_file('data.geojson', crs={'init' :'epsg:54032'})

def gdf_to_nx(gdf_network):
    # generate graph from GeoDataFrame of LineStrings
    net = nx.MultiDiGraph()
    net.graph['crs'] = gdf_network.crs
    fields = list(gdf_network.columns)

    for index, row in gdf_network.iterrows():
        first = row.geometry.coords[0]
        last = row.geometry.coords[-1]

        data = [row[f] for f in fields]
        attributes = dict(zip(fields, data))
        net.add_edge(first, last, **attributes)

    return net

G = gdf_to_nx(ALL_ROUTES)
print(G.graph['crs'])

origin_point = (ARR_AND_DEP.iloc[0].lat, ARR_AND_DEP.iloc[0].lng)
destination_point = (ARR_AND_DEP.iloc[1].lng, ARR_AND_DEP.iloc[1].lat)

print(origin_point)

center_node, distance = osmnx.get_nearest_node(G, origin_point, method='euclidean', return_dist=True)
print(distance)
```

The goal here is to use the shortest route method and add some costing methods into the routes as well.

https://drive.google.com/file/d/1BoVQgLhQQAJ4sun1Ph3vbNh4wrILVXsi/view?usp=sharing

**Comment by gboeing** [comment]
Your code snippet isn't reproducible because it doesn't define all the variables being referenced in it. But in general, OSMnx constructs networkx graphs from OSM data and it expects all the attributes and metadata that it creates to exist in its graphs. If you manually create a graph yourself and then run OSMnx operations on it, you need to make sure all that machinery is in place in the graph object.  Like I mentioned in the previous comment, it appears that you do not have an "x" attribute in your geodataframe (from data.geojson), so you're not create this attribute in the graph. OSMnx expects it.
