### ISSUE TITLE
Points being returned instead of Isochrone Polygons

### ISSUE THREAD

**Issue by gabegm** [gboeing/osmnx#714]
Hi there, not sure if this is a bug or some wrong doing of mine, my apologies if it's the latter, although for other Points I am able to correctly get the desired Polygons however for this particular Point I am getting this weird behavior where Points are being returned.

**Problem description**
  - Get isochrone Polygons for particular Point
  - Expected result: Get 3 polygons; 1 for each trip time
  - Actual result: Points returned instead

**Environment information**
* osmnx: 1.1.0
* macOS
* Python 3.9.4

<details>
Package          Version
---------------- -------
appnope          0.1.2
awscli           1.19.27
backcall         0.2.0
boto3            1.17.27
botocore         1.20.27
colorama         0.4.3
decorator        4.4.2
docutils         0.15.2
humanfriendly    9.1
ipython          7.21.0
ipython-genutils 0.2.0
jedi             0.18.0
jmespath         0.10.0
numpy            1.20.1
pandas           1.2.3
parso            0.8.1
pexpect          4.8.0
pickleshare      0.7.5
pip              21.0.1
prompt-toolkit   3.0.17
ptyprocess       0.7.0
pyasn1           0.4.8
Pygments         2.8.1
python-dateutil  2.8.1
pytz             2021.1
PyYAML           5.4.1
rsa              4.7.2
s3transfer       0.3.4
setuptools       53.0.0
six              1.15.0
traitlets        5.0.5
urllib3          1.26.4
wcwidth          0.2.5
wheel            0.36.2
</details>

```python
import networkx as nx
import numpy as np
import osmnx as ox
import pyproj
from geopandas import GeoSeries
from shapely.geometry import Point

ox.config(log_console=True, use_cache=True)

def make_iso_polys(
    lat: float,
    lon: float,
    dist: int,
    network_type: str,
    meters_per_minute: float,
    trip_times: list,
    crs: pyproj.CRS
) -> list:
    """generates the isochrone polyhons for a particular point

    Args:
        lat (float): longitude
        lon (float): latitude
        dist (int): distance in metres from point
        network_type (str): walk/drive
        meters_per_minute (float): speed in KM
        trip_times (list): max travel time to centre

    Returns:
        list: polygons for each trip time
    """
    # download the street network
    G = ox.graph_from_point(
        center_point=(lat, lon),
        dist=dist,
        dist_type="bbox",
        network_type=network_type
    )

    # find the centermost node and then project the graph to UTM
    center_node = ox.get_nearest_node(G, (lat, lon))
    # center_point = Point(G.nodes[center_node]["x"], G.nodes[center_node]["y"])
    G = ox.project_graph(G)

    # store the graph crs
    utm = G.graph["crs"]

    # add an edge attribute for time in minutes required to traverse each edge
    for u, v, k, data in G.edges(data=True, keys=True):
        data['time'] = data['length'] / meters_per_minute

    # make the isochrone polygons
    isochrone_polys = np.array([])
    for trip_time in sorted(trip_times, reverse=True):
        subgraph = nx.ego_graph(
            G,
            center_node,
            radius=trip_time,
            distance='time'
        )

        node_points = [Point((data['x'], data['y']))
                       for node, data in subgraph.nodes(data=True)]

        bounding_poly = GeoSeries(
            node_points,
            crs=utm
        ).to_crs(crs).unary_union.convex_hull

        isochrone_polys = np.append(isochrone_polys, bounding_poly)

    return isochrone_polys.reshape(-1, 3)

if __name__ == "__main__":
    trip_times = [10, 20, 30]
    network_type = "drive"
    travel_speed = 40
    meters_per_minute = travel_speed * 1000 / 60  # km per hour to m per minute
    dist = 15000
    crs = pyproj.CRS("EPSG:4326")
    lat, lon = (47.323195, 5.027429)

    polys = make_iso_polys(
        lat=lat,
        lon=lon,
        dist=dist,
        trip_times=trip_times,
        meters_per_minute=meters_per_minute,
        network_type=network_type,
        crs=crs
    )
```

Array returned:
```python
array([[ 5.0279387, 47.3239937,  5.0279387],
       [47.3239937,  5.0279387, 47.3239937]])
```

**Comment by gboeing** [comment]
OSMnx doesn't natively make isochrones, so this isn't a bug in its codebase. Best to ask usage questions on StackOverflow.
