### ISSUE TITLE
distance.nearest_nodes returning wrong distant nodes

### ISSUE THREAD

**Issue by toglimm** [gboeing/osmnx#715]
Hi.
I'm trying to use the 'new' distance.nearest_nodes function, but it returns a node which is 12 km from the coordinates I put in, which is around the university of Magdeburg. When I use the old deprecated function get_nearest_node the resulting node is accurate. So, because the node is "just" 12 km off I thought it could have something to do with projection issues? 
I found a similar problem in issue#71, but it is in regard to the old function (https://github.com/gboeing/osmnx/issues/71).
But I'm not sure where to look. I didn't find any examples of this new function being used. Is there something I'm missing?

I'm using OSMnx 1.1.1 in Python 3.9

Here is an example:

```python
import osmnx as ox

H = ox.graph_from_place('Magdeburg, Germany', network_type='drive')


# use new function/not working
orig1 = ox.distance.nearest_nodes(H, 52.13891631423865, 11.646996097973076)

#use old deprecated function/working
orig2 = ox.get_nearest_node(H,(52.13891631423865, 11.646996097973076))

print("orig1",orig1)
print("orig2",orig2)

#%%

H.nodes[orig1]['y']
#%%
H.nodes[orig1]['x']

#%%

H.nodes[orig2]['y']
#%%
H.nodes[orig2]['x']

```

**Comment by gboeing** [comment]
See the `distance.nearest_nodes` function [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.distance.nearest_nodes). The coordinate arguments should be in the order `x, y` but you are passing them in the order `y, x`.
