### ISSUE TITLE
Finding polygons fails for some queries, even when Polygons exist

### ISSUE THREAD

**Issue by PeterMitrano** [gboeing/osmnx#716]
**Problem description**
  - What did you do?

Search for "Cape Town, South Africa", via `ox.graph_from_place("Cape Town, South Africa")`

  - What did you expect to happen?

Get the result withou an exception

  - And what actually happened instead?

It threw the following exception

```
    ox.graph_from_place("Cape Town, South Africa")
  File "/home/peter/miniconda3/envs/osmnx-examples/lib/python3.9/site-packages/osmnx/graph.py", line 327, in graph_from_place
    gdf_place = geocoder.geocode_to_gdf(
  File "/home/peter/miniconda3/envs/osmnx-examples/lib/python3.9/site-packages/osmnx/geocoder.py", line 110, in geocode_to_gdf
    gdf = gdf.append(_geocode_query_to_gdf(q, wr, by_osmid))
  File "/home/peter/miniconda3/envs/osmnx-examples/lib/python3.9/site-packages/osmnx/geocoder.py", line 166, in _geocode_query_to_gdf
    result = _get_first_polygon(results, query)
  File "/home/peter/miniconda3/envs/osmnx-examples/lib/python3.9/site-packages/osmnx/geocoder.py", line 226, in _get_first_polygon
    if result["geojson"]["type"] in polygon_types:
KeyError: 'geojson'

```

**Environment information**
  - Ubuntu 20
  - 3.9
  - 1.1.1
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
# packages in environment at /home/peter/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
brotlipy                  0.7.0           py38h27cfd23_1003  
ca-certificates           2020.10.14                    0  
certifi                   2020.6.20          pyhd3eb1b0_3  
cffi                      1.14.3           py38h261ae71_2  
chardet                   3.0.4           py38h06a4308_1003  
conda                     4.9.2            py38h06a4308_0  
conda-package-handling    1.7.2            py38h03888b9_0  
cryptography              3.2.1            py38h3c74f83_1  
idna                      2.10                       py_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1h               h7b6447c_0  
pip                       20.2.4           py38h06a4308_0  
pycosat                   0.6.3            py38h7b6447c_1  
pycparser                 2.20                       py_2  
pyopenssl                 19.1.0             pyhd3eb1b0_1  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.5                h7579374_1  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
ruamel_yaml               0.15.87          py38h7b6447c_1  
setuptools                50.3.1           py38h06a4308_1  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.51.0             pyhd3eb1b0_0  
urllib3                   1.25.11                    py_0  
wheel                     0.35.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
</details>

**Provide a complete minimal reproducible example**

```python
import osmnx as ox
ox.graph_from_place("Cape Town, South Africa")
```

This might not be a bug, perhaps not all values of `results` can be expected to have a `geojson`, but if I simply add a check `if 'geojson' in result` than it does what I want, which is keep iterating through the list until it finds a Polygen.

I tried dict and OSM ID version of query, and different little tweaks to the query string, they all get the same results.

**Comment by gboeing** [comment]
Interesting. Yes I would expect every value to have a `geojson` but apparently not. I'll add this check to fix that in #716.
