### ISSUE TITLE
Kernel crashes when building graph example from Modena, Italy

### ISSUE THREAD

**Issue by GregMorel** [gboeing/osmnx#720]
I am trying to execute the sample code from OSMnx main page:
```
import osmnx as ox
ox.plot_graph(ox.graph_from_place('Modena, Italy'))
```
but it always ends the same way: the kernel crashes. It is strange, since Modena is rather a small city compared to others for which I could get the graph (Lyon, France for example). I have started to investigate the problem, and it seems located in `_add_paths()`. I don't have time for the moment to go further.

**Comment by gboeing** [comment]
Can you provide the full traceback and your platform/environment info? Need it to troubleshoot.
