### ISSUE TITLE
Median instead of mean when guessing highway speeds

### ISSUE THREAD

**Issue by stalker314314** [gboeing/osmnx#722]
While analyzing highway speeds, I noticed that osmnx relies on existing values for speed to fill in missing speeds per highway type. But it is using `mean`, while I think `median` would be more beneficial, correct and round, as it will predict actual speed in a given country better.

### Impl:
I am thinking about changing this line only:
https://github.com/gboeing/osmnx/blob/9dbee4980fe7a43279b0bfa823b6b40317705c30/osmnx/speed.py#L87

(and accompanying comments). I tried running tests after changing this line and they are passing, but I still think this is behavioral change and can break some assumption on client code, not sure what are your thoughts (is it worth it). This is main reason I didn't submit PR, but opened issue first.

Another possible problem with this approach - few data points can lead to worse results (think of 2 speeds of 30kph and 50kph would produce 30, instead of maybe, more correct 40kph), but I think osmnx users generally work with larger amount of data than 2 or 3 rows and that this is not a problem.

### Example

I did this with streets from Belgrade, Serbia (funny fact - Belgrade is mentioned in @gboeing's page [here](https://geoffboeing.com/2016/11/osmnx-python-street-networks/))

This is with `mean`:

![slika](https://user-images.githubusercontent.com/188751/122096575-3e90db00-cdfe-11eb-9922-b8011c7702b7.png)

And with `median`:
![slika](https://user-images.githubusercontent.com/188751/122097762-90863080-cdff-11eb-967f-bfd31450cad9.png)

Here are raw values from these pictures for better searching and copy/pasting:

| type | speed (mean) |
| ---------------| ---------|
| living_street | 21.25 |
| motorway | 95.19767441860465 |
| motorway_link | 48.58974358974359 |
| primary | 52.78801843317972 |
| primary_link | 46.59574468085106 |
| residential | 37.29013539651837 |
| secondary | 44.09898305084746 |
| secondary_link | 42.916666666666664 |
| tertiary | 42.27095516569201 |
| tertiary_link | 49.25925925925926 |
| trunk | 65.625 |
| trunk_link | 50.0 |
| unclassified | 42.64705882352941 |

| type | speed (median) |
| ---------------| ---------|
| living_street | 10.0 |
| motorway | 91.0 |
| motorway_link | 50.0 |
| primary | 50.0 |
| primary_link | 50.0 |
| residential | 40.0 |
| secondary | 40.0 |
| secondary_link | 50.0 |
| tertiary | 40.0 |
| tertiary_link | 50.0 |
| trunk | 60.0 |
| trunk_link | 60.0 |
| unclassified | 45.0 |

**Comment by gboeing** [comment]
Note there is also some work going on right now with speeds in #717.

The mean seems like the better estimate of the "expected value" of the edge (at least in my opinion). That is, I'd typically be less interested in the "correct" or "round" value and more interested in which value will, on average, allow my shortest path solving to behave according to real-world constraints. Ideally the mean would be length-weighted as the expected value, though. However, it may be worth allowing the user to specify an aggregation function as an argument (defaulting to something like `agg=np.mean` to maintain current behavior) in case they want to customize it, as you do.

**Comment by stalker314314** [comment]
Huh, this is bigger level of engagement that I anticipated for:) If you also don't plan to address it, feel free to close this issue (I was just wanting to point out to low-hanging fruit, but seems that fruit was not that low:)

**Comment by gboeing** [comment]
@stalker314314 I have a proposed resolution in #725. Would you like to test it for your use case?
