### ISSUE TITLE
Issue with creating sub graphs from Los Angeles County graph.

### ISSUE THREAD

**Issue by xxC3llxx** [gboeing/osmnx#723]
I am trying to extract a subgraph using ```networkx``` ```ego_graph``` function from Los Angeles County graph.
When i plot this graph and compare it with graph generated from ```graph_from_point``` (which looks correct), they seem to be completely different.

### Here is my code : 

```
G = ox.graph_from_place('Los Angeles County, California, USA')
node = ox.get_nearest_node(G, (34.6806, -118.1435))
```

#### Subgraph from networkx
```
sub_graph = nx.ego_graph(G, node, radius=2500, distance='length')
ox.plot_graph(sub_graph)
```

![1](https://user-images.githubusercontent.com/22679937/122221823-49677080-cecf-11eb-933d-de7769cc464e.jpeg)

#### graph_from_point
```
g = ox.graph_from_point((34.6806, -118.1435), dist = 2500)
ox.plot_graph(g)
```

![2](https://user-images.githubusercontent.com/22679937/122221874-55533280-cecf-11eb-819a-6d1ca6285f31.jpeg)

Both ```sub_graph``` and ```g``` look completely different. 
Am i doing anything wrong here?

```
The environment's packages:
```

```
click==7.1.2
click-plugins==1.1.1
cligj==0.7.2
cycler==0.10.0 
decorator==5.0.9 
fiona==1.8.20
folium==0.12.0 
geopandas==0.9.0
geopandas-base==0.9.0
haversine==2.3.0
matplotlib-base==3.4.2
munch==2.5.0
networkx==2.5
osmnx==1.1.1
pandas==1.2.3  
pyparsing==2.4.7
pyproj==3.1.0
qt==5.12.9
regex==2021.4.4
requests==2.25.1
rope==0.19.0
rtree==0.9.7
shapely==1.7.1
six==1.16.0
```

**Comment by gboeing** [comment]
Per the usage instructions, please ask usage questions on StackOverflow. OpenStreetMap's nominatim geocoder is geocoding your county query to the city of LA instead of the county, so it's finding the nearest node within LA city limits in `G`. See the documentation and the usage examples for tips on getting nominatim to find the right result you're looking for.

**Comment by xxC3llxx** [comment]
thanks @gboeing
