### ISSUE TITLE
"No path to node" error

### ISSUE THREAD

**Issue by lilly-yang-th** [gboeing/osmnx#726]
I am using the latest OSMNX with python 3.9. When I try to find the shortest path between two nodes, I receive an error of "No path to 'No path to 204349928'. I am looping through points in Chittenden county, Vermont. I have nearly 65k points need to run, and this error has occurred multiple times

Is there a way to resolve this issue? Potentially skip the nodes and move on to the next on in the loop.

Thanks!!

**Comment by gboeing** [comment]
> Is there a way to resolve this issue? Potentially skip the nodes and move on to the next on in the loop.

If this is a "how-to" usage question (it appears to be), please ask it on StackOverflow, per the contributing guidelines. If this is a bug report for a bug you have discovered in the OSMnx codebase, please completely fill out the new issue template with the necessary details for troubleshooting (per the new issue instructions you saw when opening this issue), and we can re-open.
