### ISSUE TITLE
Why i can't obtain driving network of the United States with the package OSMNX in python?

### ISSUE THREAD

**Issue by korasami96** [gboeing/osmnx#728]
Hello @gboieng,
Please can you help me with this matter?
Iam using the function osmnx.graph_from_place of package osmnx in Python. I want to get the driving network of the entire United States. Here is a part of my code:

`import osmnx as ox`
`EU1=ox.graph_from_place('United States', network_type='drive')`

Here is the error message i got: 'ValueError: No Shapely geometry can be created from null value'.

So i tried this:
`EU1=ox.graph_from_place('United States', network_type='drive', which_result=2)`

I have got another error message : 'TypeError: Geometry must be a shapely Polygon or MultiPolygon. If you requested graph from place name, make sure your query resolves to a Polygon or MultiPolygon, and not some other geometry, like a Point. See OSMnx documentation for details.'

**Comment by gboeing** [comment]
Please ask usage questions on StackOverflow, per the contributing guidelines and the new issue template.

**Comment by korasami96** [comment]
I have already asked this question on StackOverflow. But i feel like with the package osmnx, it is not possible to obtain the driving network of the entire united states .It works  with smaller régions in United States I would like to know why ? Thank you Provenance : Courrier pour Windows 10 De : Geoff BoeingEnvoyé le :24 juin 2021 12:23À : gboeing/osmnxCc : korasami96; AuthorObjet :Re: [gboeing/osmnx] Why i can't obtain driving network of the United States with the package OSMNX in python? (#728) Please ask usage questions on StackOverflow, per the contributing guidelines and the new issue template.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
