### ISSUE TITLE
Error with UTM zone

### ISSUE THREAD

**Issue by theocharides** [gboeing/osmnx#73]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
I'm attempting to use a shapefile to get a road network. I read in the shapefile as a geodataframe, made it a shapely geometry, then tried to plot it. An error is generated when trying to plot it: 

#### What operating system, architecture, Python version, and OSMnx version are you using?
I'm using Windows, Python 3.5.2 with Anaconda 64-bit, and the latest version of OSMnx (installed three days ago). 

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>

_license                  1.1                      py35_1
_nb_ext_conf              0.3.0                    py35_0
alabaster                 0.7.9                    py35_0
anaconda                  custom                   py35_0
anaconda-clean            1.0.0                    py35_0
anaconda-client           1.5.1                    py35_0
anaconda-navigator        1.3.1                    py35_0
argcomplete               1.0.0                    py35_1
astroid                   1.4.7                    py35_0
astropy                   1.2.1               np111py35_0
babel                     2.3.4                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.5.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.2                   py35_0
boto                      2.42.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.7.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
click-plugins             1.0.3                     <pip>
cligj                     0.4.0                     <pip>
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.3.22                   py35_0
conda-build               2.0.2                    py35_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.5                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24.1                   py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.11.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
descartes                 1.0.2                     <pip>
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.6                    py35_0
Fiona                     1.7.1                     <pip>
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
GDAL                      2.1.2                     <pip>
geopandas                 0.2.1                     <pip>
geopy                     1.11.0                    <pip>
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.2                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
icu                       57.1                     vc14_0  [vc14]
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                5.2.2                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_2  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.0                    py35_0
lazy-object-proxy         1.2.1                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libspatialindex           1.8.5                    vc14_0  [vc14]  ioos
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.13.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.4                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.3               np111py35_0
matplotlib                2.0.2                     <pip>
menuinst                  1.4.1                    py35_0
mistune                   0.7.3                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
munch                     2.0.4                     <pip>
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.3                    py35_0
numba                     0.28.1              np111py35_0
numexpr                   2.6.1               np111py35_0
numpy                     1.11.1                   py35_1
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2j                   vc14_0  [vc14]
osmnx                     0.5                       <pip>
pandas                    0.20.1                    <pip>
pandas                    0.18.1              np111py35_0
partd                     0.3.6                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    3.3.1                    py35_0
pip                       8.1.2                    py35_0
pip                       9.0.1                     <pip>
pkginfo                   1.3.2                    py35_0
ply                       3.9                      py35_0
prompt_toolkit            1.0.3                    py35_0
psutil                    4.3.1                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.3.0                    py35_0
pygments                  2.1.3                    py35_0
pylint                    1.5.4                    py35_1
pyopenssl                 16.2.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyproj                    1.9.5.1                   <pip>
pyqt                      5.6.0                    py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.6.1                 py35_0
pywin32                   220                      py35_1
pyyaml                    3.12                     py35_0
pyzmq                     15.4.0                   py35_0
qt                        5.6.0                    vc14_0  [vc14]
qtawesome                 0.3.3                    py35_0
qtconsole                 4.2.1                    py35_2
qtpy                      1.1.2                    py35_0
requests                  2.12.4                   py35_0
rope                      0.9.4                    py35_1
Rtree                     0.8.3                     <pip>
rtree                     0.8.2                    py35_0    ioos
ruamel_yaml               0.11.14                  py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.18.1              np111py35_0
setuptools                27.2.0                   py35_1
Shapely                   1.5.17                    <pip>
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.6                    py35_0
spyder                    3.0.0                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.4.1                    py35_0
traitlets                 4.3.0                    py35_0
unicodecsv                0.14.1                   py35_0
vc                        14                            0
virtualenv                15.1.0                    <pip>
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.11.11                  py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        1.2.6                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.6                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.3                    py35_0
xlwings                   0.10.0                   py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]
</details>

#### Code that reproduces the issue

```python

import osmnx as ox, geopandas as gpd

Accra = gpd.read_file('Accra_studyArea.shp')

polygon = Accra['geometry'].iloc[0]

G = ox.graph_from_polygon(polygon, network_type='drive')
ox.plot_graph(G)

RuntimeError: b'invalid UTM zone number'


[Accra_studyArea.zip](https://github.com/gboeing/osmnx/files/1136519/Accra_studyArea.zip)
```

**Comment by gboeing** [comment]
@theocharides 

1. could you share the full error traceback so I can see what all's happening?
2. after the line where you read the shapefile, what do you see if you run `print(Accra.crs)`
3. can you reproduce this error without loading that shapefile (ie, getting the graph from address or place name), or could you share that shapefile online and post a link to download here so I can run your code snippet?

**Comment by theocharides** [comment]
No problem. 

1. Error:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-2abaf0cd0411> in <module>()
----> 1 G = ox.graph_from_polygon(polygon, network_type='drive')
      2 ox.plot_graph(G)
      3 
      4 #G = ox.graph_from_polygon(polygon, network_type='drive_service')
      5 #G_projected = ox.project_graph(G)

C:\Users\cheer\Anaconda3\lib\site-packages\osmnx\core.py in graph_from_polygon(polygon, network_type, simplify, retain_all, truncate_by_edge, name, timeout, memory, max_query_area_size, clean_periphery)
   1468         # create a new buffered polygon 0.5km around the desired one
   1469         buffer_dist = 500
-> 1470         polygon_utm, crs_utm = project_geometry(geometry=polygon)
   1471         polygon_proj_buff = polygon_utm.buffer(buffer_dist)
   1472         polygon_buffered, crs = project_geometry(geometry=polygon_proj_buff, crs=crs_utm, to_latlong=True)

C:\Users\cheer\Anaconda3\lib\site-packages\osmnx\projection.py in project_geometry(geometry, crs, to_crs, to_latlong)
     41     gdf['geometry'] = None
     42     gdf.loc[0, 'geometry'] = geometry
---> 43     gdf_proj = project_gdf(gdf, to_crs=to_crs, to_latlong=to_latlong)
     44     geometry_proj = gdf_proj['geometry'].iloc[0]
     45     return geometry_proj, gdf_proj.crs

C:\Users\cheer\Anaconda3\lib\site-packages\osmnx\projection.py in project_gdf(gdf, to_crs, to_latlong)
    102 
    103             # project the GeoDataFrame to the UTM CRS
--> 104             projected_gdf = gdf.to_crs(utm_crs)
    105             log('Projected the GeoDataFrame "{}" to UTM-{} in {:,.2f} seconds'.format(gdf.gdf_name, utm_zone, time.time()-start_time))
    106 

C:\Users\cheer\Anaconda3\lib\site-packages\geopandas\geodataframe.py in to_crs(self, crs, epsg, inplace)
    362         else:
    363             df = self.copy()
--> 364         geom = df.geometry.to_crs(crs=crs, epsg=epsg)
    365         df.geometry = geom
    366         df.crs = geom.crs

C:\Users\cheer\Anaconda3\lib\site-packages\geopandas\geoseries.py in to_crs(self, crs, epsg)
    274                 raise TypeError('Must set either crs or epsg for output.')
    275         proj_in = pyproj.Proj(self.crs, preserve_units=True)
--> 276         proj_out = pyproj.Proj(crs, preserve_units=True)
    277         project = partial(pyproj.transform, proj_in, proj_out)
    278         result = self.apply(lambda geom: transform(project, geom))

C:\Users\cheer\Anaconda3\lib\site-packages\pyproj\__init__.py in __new__(self, projparams, preserve_units, **kwargs)
    356         # on case-insensitive filesystems).
    357         projstring = projstring.replace('EPSG','epsg')
--> 358         return _proj.Proj.__new__(self, projstring)
    359 
    360     def __call__(self, *args, **kw):

_proj.pyx in _proj.Proj.__cinit__ (_proj.c:1578)()

RuntimeError: b'invalid UTM zone number'

2. "print(Accra.crs)" returns:
{'init': 'epsg:32630'} 

3. here is a google drive link to the shapefile:
https://drive.google.com/a/itdp.org/file/d/0B2gGuI4h0YeabzkyNDhHUm11bjg/view?usp=sharing

**Comment by gboeing** [comment]
OpenStreetMap stores its data as lat-long. Your shapefile comes projected, so your polygon is projected as well. You can't query OSM for data within a polygon that is in an arbitrary coordinate reference system -- you must use the geographic coordinate system that OSM uses: lat-long. So, the solution is to project your shapefile to lat-long and pass that polygon to OSMnx:

```python
import osmnx as ox, geopandas as gpd
Accra = gpd.read_file('Accra_studyArea.shp')
accra_latlng = Accra.to_crs({'init':'epsg:4326'})
polygon = accra_latlng['geometry'].iloc[0]
G = ox.graph_from_polygon(polygon, network_type='drive')
ox.plot_graph(G)
```

**Comment by theocharides** [comment]
Thanks Geoff. It looks like I was trying to change the crs too late in the process. 

Thanks again!
