### ISSUE TITLE
How to know the date of information obtained from OSMnx?

### ISSUE THREAD

**Issue by saorrego** [gboeing/osmnx#733]
I wonder how to know the date of the information obtained from OSMnx. Specifically, if i get street network info from a place, how to know the corresponding date of the street network. Is this type of information updated periodically? If so, it would be great because the info contains dynamics, which will be useful. I'm not sure if this is possible. Any comments are welcome.

**Comment by gboeing** [comment]
Per the contributing guidelines and new issue template, please ask "how-to" questions on StackOverflow as this issue tracker is reserved for tracking bugs and proposing pull requests.

**Comment by saorrego** [comment]
> Per the contributing guidelines and new issue template, please ask "how-to" questions on StackOverflow as this issue tracker is reserved for tracking bugs and proposing pull requests.

Thanks Geoff for providing me the right procedure to handle my question.
