### ISSUE TITLE
Out of scope response referenced in catch block

### ISSUE THREAD

**Issue by latkins** [gboeing/osmnx#734]
**Problem description**
When using a top level function like `ox.graph_from_point`, if there is e.g. a timeout error due to a poor network connection, the catch block in `_get_pause` raises an `UnboundLocalError` due to referencing `response`, which may be out of scope: https://github.com/gboeing/osmnx/blob/cd404ae2f153a5918a924b033e0e30700f156f99/osmnx/downloader.py#L327.

Traceback:

```
  File "/databricks/python/lib/python3.7/site-packages/osmnx/graph.py", line 166, in graph_from_point
    custom_filter=custom_filter,
  File "/databricks/python/lib/python3.7/site-packages/osmnx/graph.py", line 88, in graph_from_bbox
    custom_filter=custom_filter,
  File "/databricks/python/lib/python3.7/site-packages/osmnx/graph.py", line 420, in graph_from_polygon
    response_jsons = downloader._osm_network_download(poly_buff, network_type, custom_filter)
  File "/databricks/python/lib/python3.7/site-packages/osmnx/downloader.py", line 508, in _osm_network_download
    response_json = overpass_request(data={"data": query_str})
  File "/databricks/python/lib/python3.7/site-packages/osmnx/downloader.py", line 716, in overpass_request
    this_pause = _get_pause(base_endpoint)
  File "/databricks/python/lib/python3.7/site-packages/osmnx/downloader.py", line 327, in _get_pause
    sc = response.status_code
UnboundLocalError: local variable 'response' referenced before assignment
``` 

**Environment information**
  - OS: Linux
  - Python: 3.7.3
  - osmnx: 1.1.1 

<details>
appdirs                1.4.4     
attrs                  21.2.0    
black                  21.6b0    
certifi                2021.5.30 
chardet                3.0.4     
click                  8.0.1     
click-plugins          1.1.1     
cligj                  0.7.2     
cycler                 0.10.0    
databricks-cli         0.14.3    
databricks-connect     7.3.12    
decorator              4.4.2     
dnspython              1.16.0    
findspark              1.4.2     
Fiona                  1.8.20    
flake8                 3.9.2     
geographiclib          1.52      
geopandas              0.9.0     
geopy                  2.1.0     
idna                   2.10      
importlib-metadata     4.6.1     
iniconfig              1.1.1     
isort                  5.9.2     
kiwisolver             1.3.1     
linecache2             1.0.0     
matplotlib             3.4.2     
mccabe                 0.6.1     
munch                  2.5.0     
mypy-extensions        0.4.3     
networkx               2.5.1     
numpy                  1.21.0    
omegaconf              2.1.0     
osmnx                  1.1.1     
packaging              21.0      
pandas                 1.1.3     
pathspec               0.8.1     
Pillow                 8.3.1     
pip                    19.0.3    
pluggy                 0.13.1    
py                     1.10.0    
py4j                   0.10.9    
pyarrow                3.0.0     
pycodestyle            2.7.0     
pyflakes               2.3.1     
pykalman               0.9.5     
pymongo                3.11.0    
pyparsing              2.4.7     
pyproj                 3.1.0     
pytest                 6.2.4     
python-dateutil        2.8.1     
pytz                   2021.1    
PyYAML                 5.4.1     
regex                  2021.7.6  
requests               2.25.0    
Rtree                  0.9.7     
scipy                  1.6.3     
setuptools             40.8.0    
Shapely                1.7.1     
six                    1.16.0    
tabulate               0.8.9     
toml                   0.10.2    
traceback2             1.4.0     
typed-ast              1.4.3     
typing-extensions      3.10.0.0  
unittest2              1.1.0     
urllib3                1.25.11   
yapf                   0.31.0    
zipp                   3.5.0     

</details>

**Reproducible example**

Step 0: Have a terrible internet connection.

```python
impost osmnx as ox

center =(121.489747,31.238917)
G = ox.graph_from_point(center)
```

**Comment by gboeing** [comment]
Yep looks like a bug. Should be an easy fix... would you like to open a quick PR to fix it?
