### ISSUE TITLE
Bug?: osmnx.distance.nearest_nodes() and oxmnx.get_nearest_node() produce different locations for a given coordinate.

### ISSUE THREAD

**Issue by DavidP2045** [gboeing/osmnx#737]
- What did you do?
I'm graphing the drive route between two places in New York City using OSMnx on Python. I was told that osmnx.get_nearest_node() function is deprecated, and I should use osmnx.distance.nearest_nodes() instead.

  - What did you expect to happen?
I expect different node ids, since the locations are different.

  - And what actually happened instead?
osmnx.distance.nearest_nodes() relocated the start and endpoint of the route to a corner of the NYC road network plot.

**Environment information**
  - What operating system are you using? 
Windows 10

  - What Python version are you using? 
Python 3.9.5

  - What OSMnx version are you using?
1.1.1

  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py37_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py37_1
anaconda-client           1.7.2              pyhd8ed1ab_1    conda-forge
anaconda-navigator        2.0.4                    py37_0
anaconda-project          0.10.1             pyhd8ed1ab_0    conda-forge
anyio                     3.3.0            py37h03978a9_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               20.1.0           py37hcc03f2d_2    conda-forge
arrow                     1.1.1              pyhd8ed1ab_0    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
astroid                   2.6.5            py37h03978a9_0    conda-forge
astropy                   4.3.post1        py37hcc03f2d_1    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.5.5              pyh44b312d_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
bcrypt                    3.2.0            py37hcc03f2d_1    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
bitarray                  2.0.1            py37hcc03f2d_0    conda-forge
bkcharts                  0.2                      py37_0
black                     21.7b0             pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl
bleach                    3.3.1              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.3.3            py37h03978a9_0    conda-forge
boost-cpp                 1.74.0               h5b4e17d_4    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.2            py37hda49f71_3    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py37hcc03f2d_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
certifi                   2021.5.30        py37h03978a9_0    conda-forge
cffi                      1.14.6           py37hd8e9650_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
chardet                   4.0.0            py37h03978a9_1    conda-forge
charls                    2.2.0                h39d44d4_0    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
comtypes                  1.1.10           py37h03978a9_0    conda-forge
conda                     4.10.3           py37h03978a9_0    conda-forge
conda-build               3.21.4           py37h03978a9_0    conda-forge
conda-content-trust       0.1.3              pyhd8ed1ab_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-pack                0.6.0              pyhd3deb0d_0    conda-forge
conda-package-handling    1.7.3            py37ha54c9ec_0    conda-forge
conda-repo-cli            1.0.4              pyhd3eb1b0_0
conda-token               0.3.0              pyhd3eb1b0_0
conda-verify              3.1.1           py37h03978a9_1003    conda-forge
console_shortcut          0.1.1                         4
contextlib2               21.6.0             pyhd8ed1ab_0    conda-forge
cookiecutter              1.6.0                 py37_1000    conda-forge
cryptography              3.4.7            py37h20c650d_0    conda-forge
curl                      7.78.0               h789b8ee_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.24          py37hf2a7229_0    conda-forge
cytoolz                   0.11.0           py37hcc03f2d_3    conda-forge
dask                      2021.7.2           pyhd8ed1ab_0    conda-forge
dask-core                 2021.7.2           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
distributed               2021.7.2         py37h03978a9_0    conda-forge
docutils                  0.17.1           py37h03978a9_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
fastcache                 1.1.0            py37hcc03f2d_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
fiona                     1.8.20           py37h994f730_1    conda-forge
flake8                    3.8.4                      py_0    conda-forge
flask                     2.0.1              pyhd8ed1ab_0    conda-forge
folium                    0.12.0             pyhd8ed1ab_1    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py37h03978a9_3    conda-forge
gdal                      3.3.1            py37h3a36fe1_1    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_1    conda-forge
geopandas-base            0.9.0              pyhd8ed1ab_1    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                ha8a8a2d_6    conda-forge
get_terminal_size         1.0.0                h38e98db_0
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
gevent                    21.1.2           py37hcc03f2d_0    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
glob2                     0.7                        py_0    conda-forge
gmpy2                     2.1.0b5          py37hc3278d5_0    conda-forge
greenlet                  1.1.0            py37hf2a7229_0    conda-forge
h5py                      3.3.0           nompi_py37he280515_100    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       68.1                 h0e60522_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagecodecs               2021.7.30        py37h91eda04_0    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        4.6.2            py37h03978a9_0    conda-forge
importlib_metadata        4.6.2                hd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.5.5            py37h7813e69_0    conda-forge
ipython                   7.25.0           py37h7813e69_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
isort                     5.9.3              pyhd8ed1ab_0    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.2           py37h03978a9_1    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0            py37h03978a9_6    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py37h03978a9_0    conda-forge
jupyter_server            1.10.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.1.1              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.6.1              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kealib                    1.4.14               h96bfa42_2    conda-forge
keyring                   23.0.1           py37h03978a9_0    conda-forge
kiwisolver                1.3.1            py37h8c56517_1    conda-forge
krb5                      1.19.2               hbae68bd_0    conda-forge
lazy-object-proxy         1.6.0            py37hcc03f2d_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      2.2.1                h0e60522_0    conda-forge
libaec                    1.0.5                h39d44d4_0    conda-forge
libarchive                3.5.1                hb45042f_2    conda-forge
libblas                   3.9.0           1_h8933c1f_netlib    conda-forge
libbrotlicommon           1.0.9                h8ffe710_5    conda-forge
libbrotlidec              1.0.9                h8ffe710_5    conda-forge
libbrotlienc              1.0.9                h8ffe710_5    conda-forge
libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.78.0               h789b8ee_0    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.3.1                ha6cada3_1    conda-forge
libglib                   2.68.3               h1e62bf3_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
liblief                   0.11.5               h0e60522_0    conda-forge
libllvm9                  9.0.1                hab3b255_3    conda-forge
libnetcdf                 4.8.0           nompi_hf689e7d_103    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1                h762a7f4_5    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.3.0                h0c97f57_0    conda-forge
libwebp-base              1.2.0                h8ffe710_2    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
libzip                    1.8.0                hfed4ece_0    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
llvmlite                  0.36.0           py37habb0c8c_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.3            py37hd07aab1_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py37hcc03f2d_0    conda-forge
matplotlib                3.4.2            py37h03978a9_0    conda-forge
matplotlib-base           3.4.2            py37h0d1fb12_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.17           py37h03978a9_1    conda-forge
mistune                   0.8.4           py37hcc03f2d_1004    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py37h196d8e1_0
mkl_fft                   1.3.0            py37h46781fe_0
mkl_random                1.0.4            py37h343c172_0
mock                      4.0.3            py37h03978a9_1    conda-forge
more-itertools            8.8.0              pyhd8ed1ab_0    conda-forge
mpc                       1.1.0             h7edee0f_1009    conda-forge
mpfr                      4.0.2                h62dcd97_1    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.2            py37h8c56517_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
mypy_extensions           0.4.3            py37h03978a9_3    conda-forge
navigator-updater         0.2.1                    py37_0
nbclassic                 0.3.1              pyhd8ed1ab_1    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py37h03978a9_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.3                        py_0    conda-forge
nltk                      3.6.2              pyhd8ed1ab_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.4.0              pyha770c72_0    conda-forge
numba                     0.53.1           py37h9690626_1    conda-forge
numexpr                   2.7.3            py37h08fd248_0    conda-forge
numpy                     1.20.3           py37hcbcd69c_0    conda-forge
numpy-base                1.18.5           py37hc3f5095_0
numpydoc                  1.1.0                      py_1    conda-forge
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.7              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
osmnx                     1.1.1              pyhd8ed1ab_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.1            py37h90003fb_0    conda-forge
pandoc                    2.14.1               h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0                      py_0
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
path                      16.2.0           py37h03978a9_0    conda-forge
path.py                   12.5.0                        0    conda-forge
pathlib2                  2.3.6            py37h03978a9_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.1            py37hd7d9ad0_0    conda-forge
pip                       21.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pkginfo                   1.7.1              pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py37h03978a9_4    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.4.0              pyhd8ed1ab_0    conda-forge
poppler                   21.03.0              h9ff6ed8_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.3                 h1c22c4f_0    conda-forge
powershell_shortcut       0.0.1                         3
poyo                      0.5.0                      py_0    conda-forge
praw                      7.0.0                      py_0    conda-forge
prawcore                  1.3.0              pyh9f0ad1d_0    conda-forge
proj                      8.0.1                h1cfcee9_0    conda-forge
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
prompt_toolkit            3.0.19               hd8ed1ab_0    conda-forge
psutil                    5.8.0            py37hcc03f2d_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
py-lief                   0.11.5           py37hf2a7229_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py37hcc03f2d_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py37h0013d47_1005    conda-forge
pycurl                    7.43.0.6         py37h8b18dd5_1    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.0            py37hebb4d16_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyjwt                     2.1.0              pyhd8ed1ab_0    conda-forge
pylint                    2.9.6              pyhd8ed1ab_0    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.2              pyhd3eb1b0_0
pynacl                    1.4.0            py37ha54c9ec_2    conda-forge
pyodbc                    4.0.31           py37hf2a7229_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.1.0            py37h4b97110_3    conda-forge
pyqt                      5.12.3           py37h03978a9_7    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_7    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_7    conda-forge
pyqtchart                 5.12             py37hf2a7229_7    conda-forge
pyqtwebengine             5.12.1           py37hf2a7229_7    conda-forge
pyreadline                2.1             py37h03978a9_1003    conda-forge
pyrsistent                0.17.3           py37hcc03f2d_2    conda-forge
pysocks                   1.7.1            py37h03978a9_3    conda-forge
pytables                  3.6.1            py37hdc91d43_3    conda-forge
pytest                    6.2.4            py37h03978a9_0    conda-forge
python                    3.7.10          h7840368_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python-libarchive-c       3.1              py37h03978a9_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py37hda49f71_3    conda-forge
pywin32                   300              py37hcc03f2d_0    conda-forge
pywin32-ctypes            0.2.0           py37h03978a9_1003    conda-forge
pywinpty                  1.1.3            py37h7f67f24_0    conda-forge
pyyaml                    5.4.1            py37hcc03f2d_0    conda-forge
pyzmq                     22.1.0           py37hcce574b_0    conda-forge
qdarkstyle                3.0.2              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.0.3              pyhd8ed1ab_0    conda-forge
qtconsole                 5.1.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rasterio                  1.2.6            py37h8cf91df_2    conda-forge
regex                     2021.7.6         py37hcc03f2d_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
requests-unixsocket       0.2.0                      py_0    conda-forge
ripgrep                   13.0.0               h7f3b576_0    conda-forge
rope                      0.19.0             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py37h13cc57e_2    conda-forge
ruamel_yaml               0.15.80         py37hcc03f2d_1004    conda-forge
scikit-image              0.18.2           py37h90003fb_0    conda-forge
scikit-learn              0.24.2           py37h8ded0a9_0    conda-forge
scipy                     1.7.0            py37h924764e_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
send2trash                1.7.1              pyhd8ed1ab_0    conda-forge
setuptools                49.6.0           py37h03978a9_3    conda-forge
shapely                   1.7.1            py37heb7c565_5    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.6.1              pyh44b312d_0    conda-forge
sip                       4.19.25          py37hf2a7229_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
sniffio                   1.2.0            py37h03978a9_1    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcollections         2.1.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sphinx                    4.1.2              pyh6c4a22f_1    conda-forge
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_0    conda-forge
sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
spyder                    5.0.5            py37h03978a9_2    conda-forge
spyder-kernels            2.0.5            py37h03978a9_0    conda-forge
sqlalchemy                1.4.22           py37hcc03f2d_0    conda-forge
sqlite                    3.36.0               h8ffe710_0    conda-forge
statsmodels               0.12.2           py37hda49f71_0    conda-forge
sympy                     1.8              py37h03978a9_0    conda-forge
tbb                       2020.2               h2d74725_4    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.10.1           py37h03978a9_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
textdistance              4.2.1              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tifffile                  2021.7.30          pyhd8ed1ab_0    conda-forge
tiledb                    2.3.2                h78dabda_0    conda-forge
tinycss2                  1.1.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.2.0              pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py37hcc03f2d_1    conda-forge
tqdm                      4.62.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tweepy                    3.10.0             pyhd8ed1ab_0    conda-forge
typed-ast                 1.4.3            py37hcc03f2d_0    conda-forge
typing-extensions         3.10.0.0             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
ujson                     4.0.2            py37hf2a7229_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
update_checker            0.18.0             pyh9f0ad1d_0    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
watchdog                  2.1.3            py37h03978a9_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          0.57.0           py37h03978a9_4    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
widgetsnbextension        3.5.1            py37h03978a9_4    conda-forge
win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
win_unicode_console       0.5             py37hc8dfbb8_1001    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1           py37hcc03f2d_3    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                1.4.5              pyhd8ed1ab_0    conda-forge
xlwings                   0.24.5           py37h03978a9_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.31.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zfp                       0.5.5                h0e60522_5    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zope                      1.0                      py37_1
zope.event                4.5.0              pyh9f0ad1d_0    conda-forge
zope.interface            5.4.0            py37hcc03f2d_0    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge

<details>
# paste the output of your Python packages/versions here between these two "details" tags<br/>
The start point's id is 261367744<br/>
The end point's id is 261367744  
</details>

**Provide a complete minimal reproducible example**
```python
import osmnx as ox
ox.config(log_console=True, use_cache=True)
G = ox.graph_from_place("New York,New York,USA",
                        network_type='drive')  # Get New York City's car road network
orig_node = ox.distance.nearest_nodes(G, 40.76147508980302, -73.97752854954823, return_dist=False)
print("The start point's id is %d" % orig_node) # Google Maps Plus code: Q26C+HX New York
dest_node = ox.distance.nearest_nodes(G, 40.74396884115623, -73.84969161838018, return_dist=False)
print("The end point's id is %d" % dest_node) # Google Maps Plus code: P5V2+H8 New York
```

**Comment by gboeing** [comment]
It looks like you swapped your x and y coordinates.

**Comment by DavidP2045** [comment]
> 
> 
> It looks like you swapped your x and y coordinates.
If I swap the current orig_node and dest_node equation for:
```Python
orig_node = ox.get_nearest_node(G, (40.76147508980302, -73.97752854954823))
dest_node = ox.get_nearest_node(G, (40.74396884115623, -73.84969161838018))
# then add:
import networkx as nx # to the script's top
# and
route = nx.shortest_path(G, orig_node, dest_node, weight='length')  # route drawing
fig, ax = ox.plot_graph_route(G, route, node_size=0)
```
Then the output are:<\br>
The start point's id is 42430367<\br>
The end point's id is 276214329<\br>
and a figure showing the shortest path between two distinct places.<\br>
I didn't swap the coordinates by mistake.

**Comment by gboeing** [comment]
No, I mean in this line:
```
orig_node = ox.distance.nearest_nodes(G, 40.76147508980302, -73.97752854954823, return_dist=False)
```
the `X` and `Y` function arguments are swapped. You've provided `G, Y, X` instead of `G, X, Y`.
