### ISSUE TITLE
Edge geometry when simplifying the graph - Solution: unhashable type: 'LineString'

### ISSUE THREAD

**Issue by Hekmatdabbas** [gboeing/osmnx#744]
Dear Mr. Boeing, thank you alot for making our interaction with networkx much easier. Your package is really great. 
I noticed a strange behavior (or maybe I have a bug in my graph? not sure about that) when calling the function "osmnx.simplification.simplify_graph". The geometry of the resulted edge is destroyed if the deleted edges were forming curved edges, i.e. the 'geometry' is a long LineString. After going to your code I realized that you take just the first and the last node of the deleted edges. That explains the deformation. What is the reason for that?  I am suspecting that I am missing your point as the fix is really easy and I am wondering why you didn't consider this situation.
Here is the modified code to solve the problem:

```
def simplify_graph(G, strict=True, remove_rings=True):
      #.... some un modified code lines
      for path in _get_paths_to_simplify(G, strict=strict):
          path_attributes = dict()
          for u, v in zip(path[:-1], path[1:]):
              edge_count = G.number_of_edges(u, v)
              if edge_count != 1:
                  utils.log(f"Found {edge_count} edges between {u} and {v} when simplifying")
                  
              edge_data = G.edges[u, v, 0]
              edge_data['geometry'] = list(edge_data['geometry'].coords) #------------------------------> new code line
              for attr in edge_data:
                  if attr in path_attributes:
                      path_attributes[attr].append(edge_data[attr])
                  else:
                      path_attributes[attr] = [edge_data[attr]]
              path_attributes['geometry'] = sum(path_attributes['geometry'], []) #list of lists to one list #-> new line

          # consolidate the path's edge segments' attribute values
          for attr in path_attributes:
              if attr in attrs_to_sum:
                  path_attributes[attr] = sum(path_attributes[attr])
              elif attr == 'geometry': #-----------------------------------------------------------------> new code line
                  path_attributes[attr] = LineString([Point(node) for node in path_attributes[attr]]) #--> new code line
              elif len(set(path_attributes[attr])) == 1:
                  path_attributes[attr] = path_attributes[attr][0]
              else:
                  path_attributes[attr] = list(set(path_attributes[attr]))
  
          # construct the new consolidated edge's geometry for this path -----------------------> not required anymore 
          #path_attributes["geometry"] = LineString(
          #    [Point((G.nodes[node]["x"], G.nodes[node]["y"])) for node in path]
          #)
#... some unmodified code lines
```
That solves also the issue "unhashable type: LineString" which I saw raised online. The provided answer is to drop the geometry before calling the simplification function, which mutes the error but as I say it causes geometry deformation.
Please inlight me if I am missing your point of avoiding getting the complete geometry points.
Attached you can see photos for before and after.

![Capture2](https://user-images.githubusercontent.com/46673054/129215971-edd23958-0a83-4588-b6eb-6a9e90f002ce.JPG)

![Capture](https://user-images.githubusercontent.com/46673054/129215964-372229be-99d3-42e5-9117-09fbdce01c9f.JPG)

**Comment by gboeing** [comment]
> I noticed a strange behavior (or maybe I have a bug in my graph? not sure about that) when calling the function "osmnx.simplification.simplify_graph". The geometry of the resulted edge is destroyed if the deleted edges were forming curved edges, i.e. the 'geometry' is a long LineString.

This should not be the case, as OSMnx retains the complete geometry of the original edge(s) when it simplifies it down to a single edge (with that complete geometry stored in the edge's `geometry` attribute). Can you provide a complete but minimal standalone working example code snippet to demonstrate the bug you have found? Then I can test it.

**Comment by gboeing** [comment]
This doesn't appear to be an issue with OSMnx.

**Comment by gboeing** [comment]
As far as I can tell, you're trying to simplify the graph twice: that is, you're simplifying an already simplified graph. You said you created the graph like this:

```python
G = ox.graph_from_bbox(west=10.498215,south=52.241375,east=10.544735,north=52.277572, custom_filter='["highway"~"primary|secondary"]')
G.remove_edge(26153688, 27557091)
G.graph["simplified"] = False
G = ox.simplification.simplify_graph(G)
```

Then you saved to sqlite then ran your sqlite loading code to generate `nodes` and `edges` variables before turning them back into a graph like:

```python
G = ox.graph_from_gdfs(nodes, edges)
G = ox.simplification.simplify_graph(G)
```

Therein lies the second simplification. As you left OSMnx during your workflow (to/from sqlite) before returning to it, you sidestepped the usual error messages and warning messages that you cannot simplify a graph twice. Try a simpler reproducible example where you do not dump to sqlite. Just create the graph (and save to GraphML if necessary to serialize to disk) and perform your workflow. It should either work, or give you errors/warnings if you're doing something like double simplification.

**Comment by Hekmatdabbas** [comment]
Actually, I wrote down these four lines of code to demonstrate that it is also throwing an error even before going to SQLite. I believe it also makes sense to simplify the graph again once an edge (or more) is removed. That is why I sat the attribute to False and recalled the function.

**Comment by gboeing** [comment]
Thanks @Hekmatdabbas. If someone else has this same need as you, they'll be able to adopt your sample code above for their own custom solution.
