### ISSUE TITLE
Building Footprints

### ISSUE THREAD

**Issue by Marianapdiniz** [gboeing/osmnx#746]
Dear Mr. Boeing, 
I am currently using the OSMnx in my PhD research and, specifically for the street network, it has been working nicely. However, I noticed a strange behaviour when I tried to retrieve the building footprints, both using geometries_from_place and geometries_from_polygon methods. The outputs show just part of the buildings of the city of Porto, Portugal, with empty areas within the urban limit (i.e. green spots in the image below).

  
![image](https://user-images.githubusercontent.com/89023402/129629526-c37a9bca-2b0a-4416-9509-ba5d2e753501.png)

Also using geometries_from_polygon, these empty areas continue to appear: 

![image](https://user-images.githubusercontent.com/89023402/129629558-95dea31b-953c-4d02-bbd8-244120e80471.png)

 
Here are the steps I’ve followed:

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
%matplotlib inline

Lim_Port = gpd.read_file ("C:\Mariana\Data\Input_data\Lim_Porto2")
Lim_Port. head ()

 
![image](https://user-images.githubusercontent.com/89023402/129629685-018aebe8-d2cc-4949-8d65-e302866dcafc.png)

import osmnx as ox
Lim_Port = gpd.read_file ("C:\Mariana\Data\Input_data\Lim_Porto2")
polygon = Lim_Port["geometry"].iloc[0]
G = ox.graph_from_polygon(polygon, network_type='drive')
ox.plot_graph(G)

ox.save_graph_shapefile(G)

_(Until here, for the street network everything worked properly and I was able to save as a shapefile)._ 

gdf = ox.geometries_from_polygon (polygon, {"building": True})
 
gdf_proj = ox.project_gdf(gdf)

ox.plot.plot_footprints(gdf_proj)

gdf_save = gdf.applymap(lambda x: str(x) if isinstance(x, list) else x)
gdf_save.drop(labels="nodes", axis=1).to_file("buildings.gpkg", driver="GPKG")

Along with the issue of the empty areas, I’ve had problems to save the output as a shapefile. The GeoPackage file that was saved in my computer has only a few points (there should be polygons of the building footprints) when opened in ArcGIS 10.8.1. 

Environment info
Operating system Microsoft Windows 64
Python 2.7.18
OSMnx: 1.1.1

**Comment by gboeing** [comment]
I'm not sure this is a bug. Have you verified on OpenStreetMap that there are specific building footprints within your query boundary that OSMnx is not retrieving? If so, what are their OSM IDs?

**Comment by Marianapdiniz** [comment]
Thank you for your answer. In facts, the missing buildings within the query boundary are also not present in OpenStreetMap. Concerning how to save the building footrpints into shapefiles, I've used this code:


gdf_save = gdf.applymap(lambda x: str(x) if isinstance(x, list) else x)
gdf_save.drop(labels="nodes", axis=1).to_file("buildings.gpkg", driver="GPKG")

_Output:_

During handling of the above exception, another exception occurred:

CPLE_AppDefinedError                      Traceback (most recent call last)
fiona/_err.pyx in fiona._err.GDALErrCtxManager.__exit__()

CPLE_AppDefinedError: b'failed to prepare SQL: SELECT "fid", ST_MinX("geom"), ST_MaxX("geom"), ST_MinY("geom"), ST_MaxY("geom") FROM "buildings" WHERE "geom" NOT NULL AND NOT ST_IsEmpty("geom")'
Exception ignored in: 'fiona._shim.gdal_flush_cache'
Traceback (most recent call last):

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_10068/3214188614.py in <module>
      1 gdf_save = gdf.applymap(lambda x: str(x) if isinstance(x, list) else x)
----> 2 gdf_save.drop(labels="nodes", axis=1).to_file("buildings.gpkg", driver="GPKG")

~\anaconda3\envs\ox\lib\site-packages\geopandas\geodataframe.py in to_file(self, filename, driver, schema, index, **kwargs)
   1084         from geopandas.io.file import _to_file
   1085 
-> 1086         _to_file(self, filename, driver, schema, index, **kwargs)
   1087 
   1088     def set_crs(self, crs=None, epsg=None, inplace=False, allow_override=False):

~\anaconda3\envs\ox\lib\site-packages\geopandas\io\file.py in _to_file(df, filename, driver, schema, index, mode, crs, **kwargs)
    328             filename, mode=mode, driver=driver, crs_wkt=crs_wkt, schema=schema, **kwargs
    329         ) as colxn:
--> 330             colxn.writerecords(df.iterfeatures())
    331 
    332 

~\anaconda3\envs\ox\lib\site-packages\fiona\collection.py in writerecords(self, records)
    359         if self.mode not in ('a', 'w'):
    360             raise IOError("collection not open for writing")
--> 361         self.session.writerecs(records, self)
    362         self._len = self.session.get_length()
    363         self._bounds = None

fiona/ogrext.pyx in fiona.ogrext.WritingSession.writerecs()

**Comment by gboeing** [comment]
Regarding your shapefile saving code:

```python
gdf_save = gdf.applymap(lambda x: str(x) if isinstance(x, list) else x)
gdf_save.drop(labels="nodes", axis=1).to_file("buildings.gpkg", driver="GPKG")
```

You're not using OSMnx directly in this snippet. You're using GeoPandas, and the exception you're seeing is with Fiona. I'd recommend asking on StackOverflow for general troubleshooting or opening an issue at one of those relevant package repositories if you believe it is a bug in one of those packages.
