### ISSUE TITLE
Tcl_AsyncDelete: async handler deleted by the wrong thread

### ISSUE THREAD

**Issue by nafis042** [gboeing/osmnx#75]
Every time I close an image it says this error and stops my sever. How can I solve it? Here is the code I used:
`import osmnx as ox`
` G = ox.graph_from_bbox(23.807992, 23.691314, 90.460658, 90.343675, network_type='all_private')`
`G_projected = ox.project_graph(G)`
`ox.plot_graph(G_projected)`

when I run this code It plots the graph as expected but when I close the graph window then it shows the error 'Tcl_AsyncDelete: async handler deleted by the wrong thread' and automatically closes the server and also shows 'python.exe has stopped working'. please see the updated comment @gboeing

**Comment by gboeing** [comment]
Hi @nafis042, thanks for using OSMnx. We can provide some assistance, but first please fill out the complete "new issue" template so we have enough information to do so. Please see the [contributing guidelines](https://github.com/gboeing/osmnx/blob/master/CONTRIBUTING.md) for more info.

**Comment by gboeing** [comment]
@nafis042 this code snippet runs without error on my systems. Can you fill out the entire issue template so I have enough details to troubleshoot?

**Comment by gboeing** [comment]
@nafis042 a quick Google search suggests adding the line `matplotlib.use('agg')` at the top of your code.

**Comment by gboeing** [comment]
See also #33 and #55
