### ISSUE TITLE
Make `quadrat_width` tunable

### ISSUE THREAD

**Issue by nickodell** [gboeing/osmnx#754]
I am writing a program to fetch a list of fire stations, police stations, and hospitals in Flordia from open street maps. I'm using the osmnx.geometries_from_place() API to fetch them. Here's the full program:

```py
#!/usr/bin/env python3

import osmnx as ox
import osmnx.geometries
import time
import json
import os
import geopandas as gpd
import pandas as pd

ox.utils.config(
    log_console=True,
    # Use custom overpass endpoint. Replaced my server with a placeholder.
    overpass_endpoint='http://my-over-pass-server/api/',
    overpass_rate_limit=False,
)

def reprojecting(df):
    df = df.to_crs("+proj=cea")
    return df


def pull_osm(query):

    start_time = time.time()
    tags = {'amenity': ['hospital', 'fire_station', 'police']}
    gdf = ox.geometries_from_place(query, tags)
    total_seconds = time.time() - start_time
    print(round(total_seconds/60, 1))

    return gdf


def clean_osm(df):

    areas = df[df.geometry.type == "Polygon"].copy()
    # areas = areas.to_crs('+proj=cea').centroid.to_crs("EPSG:4326")
    areas["lon"] = areas.geometry.centroid.x
    areas["lat"] = areas.geometry.centroid.y

    areas = areas[['amenity', 'name', "lon", "lat"]]

    points = df[df.geometry.type == "Point"].copy()
    points['lon'] = points.geometry.x
    points['lat'] = points.geometry.y
    points = points[['amenity', 'name', "lon", "lat"]]

    full_set = areas.append(points)

    return full_set

def osm_summary(df):
    print(len(df))
    print(df["amenity"].value_counts())


def convert_json(df):
    df = df.to_json()
    df = json.loads(df)
    return df


def save_geojson(df, cwd, file_name):
    with open(os.path.join(cwd, f"{file_name}.json"), 'w') as outfile:
        json.dump(convert_json(df), outfile)


if __name__ == "__main__":

    # pull data from open street maps
    df = pull_osm(query="Florida")

    # save raw data as a geojson
    cwd = os.path.dirname(os.path.abspath(__file__))
    save_geojson(df=df, cwd=cwd, file_name="osm_emergencyservice")

    # re-project, simplify and summarize
    temp = df.copy()
    temp = reprojecting(temp)
    temp = clean_osm(temp)
    osm_summary(temp)
```

I noticed it seems to spend a huge amount of time filtering the response geometries by a polygon. Here's a flamegraph: 

![flame](https://user-images.githubusercontent.com/666402/135674930-ec4e0b49-8bd7-46e9-a683-711a720422b4.png)

It's spending 92% of its time doing this filtering step. (This is if the response is in cache.) However, if I go into osmnx/osmnx/utils_geo.py:_intersect_index_quadrats and change quadrat_width from 0.05 to 1, the script gets 25x times faster.

| quadrat_width | time taken |
| --- | --- |
| 0.05 | 50.35 s |
| 0.1 | 10.41s |
| 0.5 | 2.05s |
| 1 | **1.74s** |
| 5 | 2.44s |

For this reason, I think it would be useful for `quadrat_width` to be tunable without editing the library.

**Comment by gboeing** [comment]
Thanks! This is an interesting proposal. The timings make sense: the recursion of slicing up the geometry into smaller constituent geometries that won't exceed Overpass's query memory allocation could take time. This is necessary if you're querying the server. But as you note, it's not necessary for subsequent runs of your script as long as you cached your response. This makes it an edge use case: the best practice workflow would (usually) be to create the model/data set and save it to disk, then use a second script to load it and do any analysis. This is better than relying on the cache for serialization and prevents having to run an unnecessary modeling/downloading step every time you're doing anything with the data.

So I see three options:
  1. Leave it as is, and accept slower performance in this kind of rare edge case
  2. Improve the geometry-subdividing recursive logic
  3. Allow a configurable `quadrat_width` setting

**Comment by nickodell** [comment]
>The timings make sense: the recursion of slicing up the geometry into smaller constituent geometries that won't exceed Overpass's query memory allocation could take time. This is necessary if you're querying the server. But as you note, it's not necessary for subsequent runs of your script as long as you cached your response.

To clarify: I'm not talking about changing the `quadrat_width` of the [first](https://github.com/gboeing/osmnx/blob/ba16af37c6ca56b5c404189d8f582a1248ca0735/osmnx/utils_geo.py#L307) `_quadrat_cut_geometry()` call. That's controlled by [this setting](https://github.com/gboeing/osmnx/blob/main/osmnx/settings.py#L65), and is already configurable.

I'm talking about the [second call](https://github.com/gboeing/osmnx/blob/ba16af37c6ca56b5c404189d8f582a1248ca0735/osmnx/utils_geo.py#L422) to `_quadrat_cut_geometry()`: the one which is used to create an index to filter out the geometries received from overpass, to make sure that all of the geometries which were sent by the server are actually in the user's polygon. That second call is the killer one, because it's done with a much smaller `quadrat_width`. (~16km^2 vs ~2500km^2)

**Comment by gboeing** [comment]
Ah, right, so this is specific to the call originating [here](https://github.com/gboeing/osmnx/blob/main/osmnx/geometries.py#L969)? Yes `_quadrat_cut_geometry` gets called in two different ways:

  1. to subdivide a large geometry into smaller geometries (e.g., to make multiple queries to Overpass to not exhaust server memory)
  2. to subdivide a reference geometry when calculating spatial intersections, for r-tree index acceleration

I believe the first always uses the (configurable) 2500 km^2 as its quadrat size. The latter has a default argument of ~16 km^2 (but specified in degrees) as its quadrat size. It would be useful to think about this latter case. Is there a way to determine the ideal quadrat width given the size of the geometry? If so, this would be preferable to hard-coding it (like now) and probably preferable to leaving it to the user to configure.

**Comment by nickodell** [comment]
>Is there a way to determine the ideal quadrat width given the size of the geometry? If so, this would be preferable to hard-coding it (like now) and probably preferable to leaving it to the user to configure.

Agreed. That would be more user-friendly.

> So I see three options:
> 
>    1. ....
>    2. Improve the geometry-subdividing recursive logic
>    3. ....

So I've been thinking about how to make this faster, and experimenting with a few different approaches, and I found a pretty promising approach:

 * Avoid converting from GeometryCollection to MultiPolygon multiple times - keep the polygons in a list while processing them. This has a small effect, but enables optimization 2, which is:
 * Don't call split() on polygons which don't intersect the split line.

In my testing, this lead to reduction of cumulative time spent in _quadrat_cut_geometry of 6x.

I also experimented with using bounding boxes to optimize the intersection, but I found that didn't make it faster.

Here's the branch: https://github.com/gboeing/osmnx/compare/main...nickodell:njo-quadrat-bbox

**Comment by gboeing** [comment]
For what it's worth, I whipped up some code to time `utils_geo._intersect_index_quadrats` across a matrix of quadrat widths and number of points. Here are the (log) timings:

![timings](https://user-images.githubusercontent.com/4977197/136270312-4bc56539-c152-48fc-b3bb-8cb8be42da59.png)

This suggests that a simple rule-of-thumb fix that generalizes well to a variety of point sizes would be to change the function's [signature](https://github.com/gboeing/osmnx/blob/main/osmnx/utils_geo.py#L391) to `quadrat_width=0.5`. This parameterization seems to perform well across use cases and looks like it will provide >6x speed-ups for most.

**Comment by gboeing** [comment]
For reference, this is the code I used to generate that figure:
```python
import time
import geopandas as gpd
import numpy as np
import osmnx as ox
import pandas as pd
import seaborn as sns

# get a reference polygon
gdf = ox.geocode_to_gdf('Florida, USA')
polygon = gdf.unary_union

# generate random points
def generate_points(n):
    left, bottom, right, top = polygon.convex_hull.bounds
    x = np.random.uniform(left, right, n)
    y = np.random.uniform(bottom, top, n)
    return gpd.GeoSeries(gpd.points_from_xy(x, y))

# time different quadrat sizes for points-in-polygon intersection
points_n = np.linspace(start=100, stop=200000, num=20).astype(int)
widths = np.linspace(start=1, stop=0.05, num=20).round(2)
timings = dict()
for n in points_n:
    points = generate_points(n)
    timings[n] = dict()
    for width in widths:
        start_time = time.time()
        _ = ox.utils_geo._intersect_index_quadrats(points, polygon, width)
        end_time = time.time()
        timings[n][width] = end_time - start_time

# visualize log timings as heatmap
df = pd.DataFrame(timings).round(2).sort_index()
df.index = df.index.map(lambda x: f'{x:0.2f}')
ax = sns.heatmap(np.log(df), cmap='viridis', square=True, linewidths=0)
_ = ax.set_ylabel('quadrat width')
_ = ax.set_xlabel('number of points')
_ = ax.set_title('log of elapsed time in seconds')
ax.figure.savefig('timings.png', dpi=600, bbox_inches='tight')
```

**Comment by gboeing** [comment]
Here's the same thing (but not logarithmic) for a small town (Piedmont, California):

![timings-piedmont](https://user-images.githubusercontent.com/4977197/136278303-7dc7504b-88a1-496c-bc17-064749161628.png)
