### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by yuriniet** [gboeing/osmnx#756]
**Problem description:**

While trying to download graph using graph_from_address, the error "ConnectionRefusedError: [WinError 10061] No connection could be made because the destination machine actively refused to". 

Everything was working fine yesterday (6-11-2020).  The traceback error of the script is attached as pdf.

[TRACEBACK ERROR.pdf](https://github.com/gboeing/osmnx/files/7294831/TRACEBACK.ERROR.pdf)

**environment information**

Windows 10
Python 3.9
osmnx 1.1.1

<details>
affine                    2.3.0                      py_0    conda-forge
argon2-cffi               20.1.0                   pypi_0    pypi
arrow                     1.1.1                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
axelrod                   4.11.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
binaryornot               0.4.4                    pypi_0    pypi
bleach                    3.3.0                    pypi_0    pypi
boost-cpp                 1.74.0               h5b4e17d_4    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1001    conda-forge
bs4                       4.10.0               hd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
cchardet                  2.1.7                    pypi_0    pypi
certifi                   2021.5.30        py39hcbf5309_0    conda-forge
cffi                      1.14.6           py39h0878f49_1    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
chardet                   4.0.0            py39hcbf5309_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_0    conda-forge
cloudpickle               2.0.0                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cookiecutter              1.7.3                    pypi_0    pypi
cryptography              3.4.7            py39hd8d06c1_0    conda-forge
curl                      7.79.1               h789b8ee_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dask                      2021.9.0                 pypi_0    pypi
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
expat                     2.4.1                h39d44d4_0    conda-forge
fiona                     1.8.20           py39hea8b339_1    conda-forge
folium                    0.12.0             pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fsspec                    2021.8.1                 pypi_0    pypi
func-timeout              4.3.5                    pypi_0    pypi
gdal                      3.3.2            py39h7c9a9b1_4    conda-forge
geneticalgorithm          1.0.2                    pypi_0    pypi
geopandas                 0.10.0             pyhd8ed1ab_0    conda-forge
geopandas-base            0.10.0             pyha770c72_0    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.7.0                h350af67_3    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
gtfs-functions            1.0.1                    pypi_0    pypi
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_100    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
ipykernel                 5.5.5                    pypi_0    pypi
ipython                   7.23.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
isoweek                   1.3.3                    pypi_0    pypi
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0                    pypi_0    pypi
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
kealib                    1.4.14               h8995ca9_3    conda-forge
kiwisolver                1.3.2            py39h2e07f2f_0    conda-forge
krb5                      1.19.2               hbae68bd_2    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      2.2.1                h0e60522_0    conda-forge
libblas                   3.9.0              11_win64_mkl    conda-forge
libcblas                  3.9.0              11_win64_mkl    conda-forge
libcurl                   7.79.1               h789b8ee_1    conda-forge
libdeflate                1.7                  h8ffe710_5    conda-forge
libffi                    3.4.2                h0e60522_4    conda-forge
libgdal                   3.3.2                h08edb8f_4    conda-forge
libglib                   2.68.4               h3be07f2_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              11_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_0    conda-forge
libpysal                  4.5.1              pyhd8ed1ab_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1                h6a90f17_9    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                h0c97f57_1    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
locket                    0.2.1                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py39hb82d6ee_0    conda-forge
matplotlib-base           3.4.3            py39h581301d_1    conda-forge
matplotlib-inline         0.1.2                    pypi_0    pypi
mesa                      0.8.9                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.3.0           hb70f87d_564    conda-forge
momepy                    0.5.0              pyhd8ed1ab_1    conda-forge
mpmath                    1.2.1                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
nashpy                    0.0.25                   pypi_0    pypi
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.5                        py_0    conda-forge
notebook                  6.4.0                    pypi_0    pypi
numpy                     1.21.2           py39h6635163_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
osmnx                     1.1.1              pyhd8ed1ab_0    conda-forge
packaging                 20.9                     pypi_0    pypi
pandas                    1.3.3            py39h2e25243_0    conda-forge
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
partd                     1.2.0                    pypi_0    pypi
partridge                 1.1.1                    pypi_0    pypi
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
peartree                  0.6.4                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.3.2            py39h916092e_0    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   21.09.0              h24fffdf_3    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                13.3                 h1c22c4f_0    conda-forge
powerlaw                  1.5                      pypi_0    pypi
poyo                      0.5.0                    pypi_0    pypi
proj                      8.1.1                h1cfcee9_2    conda-forge
prometheus-client         0.10.1                   pypi_0    pypi
prompt-toolkit            3.0.18                   pypi_0    pypi
pycairo                   1.20.1                   pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygeos                    0.10.2           py39haadaec5_0    conda-forge
pygments                  2.9.0                    pypi_0    pypi
pyintergraph              1.3.2                    pypi_0    pypi
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypiwin32                 223                      pypi_0    pypi
pyproj                    3.2.1            py39h39b2389_2    conda-forge
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1            py39hcbf5309_3    conda-forge
python                    3.9.7           h7840368_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-igraph             0.9.6                    pypi_0    pypi
python-slugify            5.0.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywin32                   300                      pypi_0    pypi
pywinpty                  1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.1.0                   pypi_0    pypi
qtconsole                 5.1.0                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
rasterio                  1.2.9            py39h20dd13d_2    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py39h09fdee3_2    conda-forge
scikit-learn              1.0              py39h74df8f2_1    conda-forge
scipy                     1.7.1            py39hc0c34ad_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
send2trash                1.5.0                    pypi_0    pypi
setuptools                58.2.0           py39hcbf5309_0    conda-forge
shapely                   1.7.1            py39haadaec5_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
statsmodels               0.13.0           py39h5d4886f_0    conda-forge
tbb                       2021.3.0             h2d74725_0    conda-forge
terminado                 0.10.0                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
texttable                 1.6.3                    pypi_0    pypi
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tiledb                    2.3.4                h78dabda_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.1              py39hb82d6ee_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                    pypi_0    pypi
tzdata                    2021c                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
utm                       0.7.0                    pypi_0    pypi
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.1                    pypi_0    pypi
win_inet_pton             1.1.0            py39hcbf5309_2    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xyzservices               2021.9.1           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge

</details>

```python
import osmnx as ox
g = ox.graph_from_address('New York, US', network_type='drive')

**Comment by arthursou** [comment]
I got the same error. Yesterday, everything was working fine!
