### ISSUE TITLE
Openstreet map :Building plot?

### ISSUE THREAD

**Issue by seghier** [gboeing/osmnx#766]
Hello
Is there examples how to plot openstreet map (buildings, roads ...etc)

**Comment by gboeing** [comment]
The [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples) answer that question.

**Comment by seghier** [comment]
The example for notebook not python files

**Comment by gboeing** [comment]
I'm not clear what you are stating. Yes the example notebooks demonstrate Python code to plot OpenStreetMap buildings and roads.

**Comment by seghier** [comment]
People who used Pycharm for example or any other python editors can't open these examples.

**Comment by gboeing** [comment]
Pycharm certainly can open notebook files: https://www.jetbrains.com/help/pycharm/jupyter-notebook-support.html So can most other IDEs including Visual Studio: https://code.visualstudio.com/learn/educators/notebooks If you don't want to work with notebooks specifically, just open them in any IDE and export them to .py files or any other preferred format.
