### ISSUE TITLE
elevation test failed when the number of cpus is unusually huge

### ISSUE THREAD

**Issue by jgmbenoit** [gboeing/osmnx#768]
The elevation test currently failed on a server computer with 160 cores as reported and discussed in the Debian bugreport [#995021](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995021) .
A closer look to the code in [elevation.py](https://github.com/gboeing/osmnx/blob/main/osmnx/elevation.py) lets think that when the number of cores is larger the number of nodes something unexpected occurs. I am ready to give a chance on this 160 cores beast to any change.

**Comment by gboeing** [comment]
Thanks for contributing this issue to OSMnx. Per the contributing guidelines, please edit this to **fill out the complete new issue template**, including all details, and we can reopen this to take a look when we have that necessary info!
