### ISSUE TITLE
elevation test failed when the number of cpus is unusually huge

### ISSUE THREAD

**Issue by jgmbenoit** [gboeing/osmnx#769]
**Problem description**
  - What did you do?
  perform the tests on an armhf server with 160 nodes
  - What did you expect to happen?
  I expect the tests to succeed.
  - And what actually happened instead?
  One of the tests fails: the test_elevation test,

**Environment information**
  - What operating system are you using?
  Debian/GNU linux Sid (unstable)
  - What Python version are you using?
  Python 3.9.7
  - What OSMnx version are you using?
  1.1.1
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
# paste the output of your Python packages/versions here between these two "details" tags
dh-python	5.20211022.1
libpython3-stdlib:amd64	3.9.2-3
libpython3.5-minimal:amd64	3.5.4-4
libpython3.6-minimal:amd64	3.6.8-1
libpython3.7-minimal:amd64	3.7.7-1+b1
libpython3.8-minimal:amd64	3.8.6-1
libpython3.9:amd64	3.9.7-4
libpython3.9-minimal:amd64	3.9.7-4
libpython3.9-stdlib:amd64	3.9.7-4
python-babel-localedata	2.8.0+dfsg.1-7
python-matplotlib-data	3.3.4-2
python3	3.9.2-3
python3-affine	2.3.0-2
python3-alabaster	0.7.12-1
python3-appdirs	1.4.4-1
python3-attr	20.3.0-1
python3-babel	2.8.0+dfsg.1-7
python3-branca	0.4.2-1
python3-certifi	2020.6.20-1
python3-chardet	4.0.0-1
python3-click	8.0.2-1
python3-click-plugins	1.1.1-3
python3-cligj	0.7.2-1
python3-colorama	0.4.4-1
python3-coverage	5.1+dfsg.1-2+b2
python3-cycler	0.10.0-3
python3-dateutil	2.8.1-6
python3-debian	0.1.42
python3-decorator	4.4.2-2
python3-descartes	1.1.0-4
python3-distutils	3.9.7-1
python3-docutils	0.17.1+dfsg-2
python3-fiona	1.8.20-2+b2
python3-flake8	3.8.4-1
python3-folium	0.12.1+dfsg-1
python3-gdal	3.3.3+dfsg-1
python3-geopandas	0.10.2-1
python3-idna	2.10-1
python3-imagesize	1.2.0-2
python3-importlib-metadata	4.6.4-1
python3-iniconfig	1.1.1-1
python3-isort	5.6.4-1
python3-jinja2	3.0.1-2
python3-joblib	0.17.0-4
python3-kiwisolver	1.3.2-1
python3-lib2to3	3.9.7-1
python3-lxml:amd64	4.6.3+dfsg-1
python3-markupsafe	2.0.1-2
python3-matplotlib	3.3.4-2
python3-mccabe	0.6.1-3
python3-minimal	3.9.2-3
python3-more-itertools	4.2.0-3
python3-munch	2.3.2-2
python3-mypy-extensions	0.4.3-2
python3-networkx	2.5+ds-2
python3-numpy	1:1.19.5-1
python3-packaging	21.0-1
python3-pandas	1.1.5+dfsg-2
python3-pandas-lib:amd64	1.1.5+dfsg-2
python3-pathspec	0.9.0-1
python3-pil:amd64	8.3.2-1
python3-pkg-resources	58.2.0-1
python3-pluggy	0.13.0-7.1
python3-py	1.10.0-1
python3-pycodestyle	2.6.0-1
python3-pydocstyle	6.1.1-1
python3-pyflakes	2.2.0-3
python3-pygments	2.7.1+dfsg-2.1
python3-pyparsing	2.4.7-1
python3-pyproj	3.2.1-1+b1
python3-pytest	6.2.5-1
python3-rasterio	1.2.10-1
python3-regex	0.1.20211008-1
python3-requests	2.25.1+dfsg-2
python3-roman	3.3-1
python3-rtree	0.9.7-1
python3-scipy	1.7.1-1
python3-setuptools	58.2.0-1
python3-shapely	1.8.0-1
python3-six	1.16.0-2
python3-sklearn	0.23.2-5
python3-sklearn-lib:amd64	0.23.2-5
python3-snowballstemmer	2.1.0-2
python3-snuggs	1.4.7-2
python3-sphinx	4.2.0-5
python3-threadpoolctl	2.1.0-1
python3-toml	0.10.2-1
python3-tz	2021.3-1
python3-urllib3	1.26.5-1~exp1
python3-zipp	1.0.0-3
python3.9	3.9.7-4
python3.9-minimal	3.9.7-4
</details>

**Provide a complete minimal reproducible example**

Your example code snippet here must be *minimal* so it doesn't contain extraneous code unrelated to your specific problem and it must be *complete* so we can independently run it from top to bottom by copying/pasting it into a Python interpreter. That means all imports and all variables must be defined. If you're unsure how to create a good reproducible example, read [this guide](https://stackoverflow.com/help/minimal-reproducible-example). Do not post a screenshot of your code or error message: provide it as text.

```python
#  code of the failing test:
def test_elevation():

    G = ox.graph_from_address(address=address, dist=500, dist_type="bbox", network_type="bike")
    rasters = list(Path("tests/input_data").glob("elevation*.tif"))

    # add node elevations from a single raster file (some nodes will be null)
    G = ox.elevation.add_node_elevations_raster(G, rasters[0], cpus=1)

    # add node elevations from multiple raster files # the code fails here
    G = ox.elevation.add_node_elevations_raster(G, rasters)
```

The very details of the test failure is available [here](https://ci.debian.net/data/autopkgtest/testing/armhf/o/osmnx/16373891/log.gz).
This issue is discussed in the Debian reportbug [#995021](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995021).

**Comment by gboeing** [comment]
I'm not clear what the nature of this error is. It looks like it's a problem in the multiprocessing of the elevations. However, I'm not able to reproduce this on any machine and I don't see any reason why have 160 cores should inherently cause this problem. Are you able to reproduce this anywhere else?

**Comment by jgmbenoit** [comment]
The tests succeed the architectures  amd64, arm64, armhf (4 cores), i386, and  ppc64el .
But the issue currently occurs on this beast of 160 cores. There is no inherent reason indeed.
However the number of cores is so unusual that still undetected bugs can emerge.

**Comment by jgmbenoit** [comment]
I run extra elevation tests with explicit different values for the cpus parameter.
The follow code with cpus=389 on my amd64 laptop (six cores) failed the same way.
```
def test_elevation_extra_huge():

    G = ox.graph_from_address(address=address, dist=500, dist_type="bbox", network_type="bike")
    rasters = list(Path("tests/input_data").glob("elevation*.tif"))

    # add node elevations from multiple raster files with 389 cpus
    G = ox.elevation.add_node_elevations_raster(G, rasters, cpus=389)
    assert pd.notnull(pd.Series(dict(G.nodes(data="elevation")))).all()

    # add edge grades and their absolute values
    G = ox.add_edge_grades(G, add_absolute=True)
```
The log file reports the following:
```
=================================== FAILURES ===================================
__________________________ test_elevation_extra_huge ___________________________
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/lib/python3/dist-packages/osmnx/elevation.py", line 49, in _query_raster
    return zip(nodes.index, values)
TypeError: iteration over a 0-d array
"""

The above exception was the direct cause of the following exception:

    def test_elevation_extra_huge():
    
        G = ox.graph_from_address(address=address, dist=500, dist_type="bbox", network_type="bike")
        rasters = list(Path("tests/input_data").glob("elevation*.tif"))
    
        # add node elevations from multiple raster files with 389 cpus
>       G = ox.elevation.add_node_elevations_raster(G, rasters, cpus=389)

tests/test_osmnx.py:253: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3/dist-packages/osmnx/elevation.py:98: in add_node_elevations_raster
    results = sma.get()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.MapResult object at 0x7f48512b5af0>, timeout = None

    def get(self, timeout=None):
        self.wait(timeout)
        if not self.ready():
            raise TimeoutError
        if self._success:
            return self._value
        else:
>           raise self._value
E           TypeError: iteration over a 0-d array

/usr/lib/python3.9/multiprocessing/pool.py:771: TypeError
```
Can you reproduce the issue on your side ?

**Comment by gboeing** [comment]
How many CPUs do you actually have available on your big computer? Try to run `import multiprocessing as mp; print(mp.cpu_count())` to ascertain this.

**Comment by gboeing** [comment]
> Can you reproduce the issue on your side?

No I'm not able to reproduce this on any of my machines, even when using `cpus=1000` to drastically exceed my true number of available cores. However, I've created #771 to limit the CPUs in multiprocessing to the number available on the machine, even if the user requested more.

**Comment by jgmbenoit** [comment]
> How many CPUs do you actually have available on your big computer? Try to run `import multiprocessing as mp; print(mp.cpu_count())` to ascertain this.
I have no direct access to the machine. The tests are managed by `robots'.
I asked to the person who is in charge.

**Comment by jgmbenoit** [comment]
> No I'm not able to reproduce this on any of my machines, even when using `cpus=1000` to drastically exceed my true number of available cores.

Good to know.

>However, I've created #771 to limit the CPUs in multiprocessing to the number available on the machine, even if the user requested more.
I am not familiar with Python microsystem, but I would bet that multiprocessing module  should manage this situations.

I will dig furhther on my side.

**Comment by jgmbenoit** [comment]
> How many CPUs do you actually have available on your big computer? Try to run `import multiprocessing as mp; print(mp.cpu_count())` to ascertain this.

160

**Comment by gboeing** [comment]
As far as I can tell, this isn't an issue with OSMnx itself. I'm unable to reproduce it and I haven't had anyone else report anything similar. If you can reproduce it on a computer you have full control over (such as your own personal computer) we can try to diagnose and explore further. But it seems to have something to do with how Python's multiprocessing module is working with the machines in your environment.

**Comment by jgmbenoit** [comment]
I agree even so I think it is a bit premature to close the issue.

**Comment by gboeing** [comment]
Happy to reopen later if there ends up being something we should fix on the OSMnx side to help out.

**Comment by jgmbenoit** [comment]
Imposing a lowerbound of 3 for size in  `add_node_elevations_raster` solves the issue for all architectures used for CI in Debian.
```
size = max(3, int(np.ceil(len(nodes) / cpus)))
```
I tried this because the issue shows up when size equals 2 (on my amd64 box).
This lowerbound might be relevant only for the data of the test. I do not really know the computation underway to set a better one.

Otherwise, have you tried to reproduce the issue on a Linux box (e.g., Ubuntu) or just on Windows or Mac boxes ?

**Comment by gboeing** [comment]
Yes I have tested on my own Linux machines. And the OSMnx CI tests runs on Ubuntu.

**Comment by gboeing** [comment]
How many CPUs does Python's `multiprocessing` module say you have?

**Comment by jgmbenoit** [comment]
160 on the big computer.

**Comment by gboeing** [comment]
That's what the `multiprocessing` module specifically says?

**Comment by jgmbenoit** [comment]
This is the out ouput given by
```
mp.cpu_count()
``` 
on the big computer.

**Comment by gboeing** [comment]
For reference, you can see the Linux logs from the test suite running in CI [here](https://github.com/gboeing/osmnx/commit/47126e79e5c4f0e8a8eb2a2bba35326aa9ecfe12/checks/4098765558/logs).
