### ISSUE TITLE
Suming travel_time properties when simplifying graph

### ISSUE THREAD

**Issue by hehlinge42** [gboeing/osmnx#770]
Hello osmnx team! Thank you for this awesome package that spares me a lot of troubles working with osm files.

I noticed that the version of the package available on pypi (either pip install osmnx --upgrade or directly downloadable on https://pypi.org/project/osmnx/) is not the one we can see on Github, despite being on the main branch. 

Especially, simplifying a graph in which "travel_time" properties have been assigned seems possible on the latest version from Github (see file simplification.py line 230): 
```attrs_to_sum = {"length", "travel_time"}```: it seems that "travel_time" properties should be sumed during simplification.

Nevertheless, on the pypi version, this feature is not implemented and "travel_time" properties are appended to a list, which makes any method of shortest path detection raising Exceptions.

Is there any plan to make the Github version installable via Pypi ? I can see that the commit was 5 months ago.

Best,

hehlinge42

**Comment by gboeing** [comment]
Thanks for using OSMnx. This enhancement happened in #721. See the [change log](https://github.com/gboeing/osmnx/blob/main/CHANGELOG.md) for release details. The `main` branch of the code repository does not necessarily match the latest release, as development work is constantly being merged into this branch. I am aiming for the next minor release in hopefully the next month, pending closing out a couple of open issues first.

**Comment by gboeing** [comment]
Specifically I want to have fixes for #727 #751 #764 in the minor release.

**Comment by gboeing** [comment]
@hehlinge42 see forthcoming release in #783

**Comment by gboeing** [comment]
@hehlinge42 OSMnx v1.1.2 has been released
