### ISSUE TITLE
Add APIs for loading/saving graphml from/to IO-like objects

### ISSUE THREAD

**Issue by xSAVIKx** [gboeing/osmnx#776]
**Is your feature proposal related to a problem?**

Loading graphs in serverless environments doubles the amount of RAM required to load a graph.

The reason for that is that with the current APIs one is forced to store the graphml file in the file system prior to loading it with e.g. `load_graphml`. And in serverless environments file system is usually mounted directly into the memory.
It may be even worse if you first need to store it in some IO stream cause it's not possible to write directly into a file for some reason (you end up with 3x more memory needed)

**Describe the solution you'd like to propose**

The `networkx` already provides an API to parse a graph from a string (`parse_graphml`), so going to use it and have a similar one in the `osmnx.io` package that does the `load_graphml` logic but for a graph from a string.

**Describe alternatives you've considered**

Re-implement the `load_graphml` logic but outside of the library. Use `parse_graphml` directly and then use copy-pasted logic from the library.

**Additional context**

```python

graph = b"my-graph-data"
with open("/tmp/my-graph", "wb") as graph_file:
    graph_file.write(graph)

G = ox.io.load_graphml("/tmp/my-graph")
os.remove("/tmp/my-graph")

# Do stuff with `G`
```

**Comment by xSAVIKx** [comment]
It's hard to say, but this should be the case for any serverless environment while you don't have a normal file system there. And even if you do have a file system, why one may want to write the content to disk first and then read it again? I mean, if I am downloading the file from a remote location it just doesn't make a lot of sense to do the job twice.

**Comment by gboeing** [comment]
Thanks. If you'd like to open a PR I can take a look.

**Comment by gboeing** [comment]
Let me know if you'd like to contribute this as a PR.

**Comment by xSAVIKx** [comment]
I'd love to as soon as the war in Ukraine is gonna be won. I'm from Kharkiv (very close to the Russian border) and had to leave my hometown due to massive shelling and airstrikes.

**Comment by benafischer94** [comment]
I think the use case for this will continue grow.  I was working through a similar use case of needing the data but trying to reduce number of copies across containers/functions consuming it, as well as the issue of downloading, writing, then reading again.
I'll take a look and see if I can work through the PR for this one. 

@xSAVIKx , hope you can return home safe soon.

**Comment by Vermouth1103** [comment]
Is it possible to load shp/geojson format graph with osmnx? As I can see, there isn't any supporting methods in the docs.

**Comment by gboeing** [comment]
@Vermouth1103 yes this is demonstrated in the usage examples and in the documentation: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils_graph.graph_from_gdfs

**Comment by gboeing** [comment]
Closed by #815

**Comment by Vermouth1103** [comment]
你好，你的邮件已经收到。祝你一切顺利。

**Comment by Vermouth1103** [comment]
你好，你的邮件已经收到。祝你一切顺利。
