### ISSUE TITLE
How to extract city graphml from offline OSM area ?

### ISSUE THREAD

**Issue by unvaiso** [gboeing/osmnx#78]
Hi,
Is there a way to extract a given city graphml from an offline OSM area ?
For example, extracting Paris `.graphml `file from an offline european continental `.osm` file.
I had this idea because the online requests from Osmnx to osm have important overhead.
Thank you.

**Comment by gboeing** [comment]
There isn't a way to do this out-of-the-box. However, you potentially could, but it would take some hacking of OSMnx. If you're up for it, the key function would be [`ox.create_graph`](https://github.com/gboeing/osmnx/blob/0f41bd480b50d6e7b9b1b2d2ac32cc9d7fcc31a2/osmnx/core.py#L1252).

This function takes a list of JSON responses from the Overpass API and turns them into a networkx graph. You could load your existing downloaded data (it would have to be in the correct format, as returned by the Overpass API), and pass it into `create_graph`. Or write a translator function to go from your `.osm` file to the expected format for `create_graph`.

If you do go down this route, a pull request to add a `graph_from_osm_file` function might be a nice addition to OSMnx!

**Comment by gboeing** [comment]
@unvaiso Alternatively, if you load your .osm file into node and edge geopandas GeoDataFrames, you can convert these into a graph with `ox.gdfs_to_graph`: https://osmnx.readthedocs.io/en/latest/osmnx.html#osmnx.save_load.gdfs_to_graph

**Comment by unvaiso** [comment]
That's a good start. Thanks !

**Comment by gboeing** [comment]
@unvaiso the functionality to use OSMnx to load a .osm file and then save it as a .graphml file now exists in the latest software release.

**Comment by NaniBird** [comment]
@gboeing is it possible to extract  cities and towns contained in one big osm file (hundreds of Gigs) and then save them later on as osm files. I've tried using osmosis, but doesn't offer this functionality, and OSMNX cannot load such big files.

**Comment by gboeing** [comment]
@NaniBird OSMnx can load arbitrarily large files, with the constraint being available system memory. That is, if you have enough RAM, OSMnx can load your big .osm file.

**Comment by NaniBird** [comment]
@gboeing Since I only got 16gis of ram, i strongly doubt it would load a 200 gb osm file.

**Comment by gboeing** [comment]
@NaniBird yeah, not much OSMnx can do about that, though there is an open issue for a forthcoming PR to help make graph construction more memory efficient: #149

**Comment by matthew-rococo** [comment]
> 
> 
> @unvaiso the functionality to use OSMnx to load a .osm file and then save it as a .graphml file now exists in the latest software release.

i want to use this function to read osm file  and save it as graph file , but i can only find the overpass_json_from_file function,  can not figuer out how to save it .

**Comment by Aryahagh** [comment]
> @unvaiso the functionality to use OSMnx to load a .osm file and then save it as a .graphml file now exists in the latest software release.

I downloaded "us-midwest-latest.osm.bz2" and I want to save it as a graphml file so I can reload it every time easily. Would you please share a link on how I can do that?

Thanks in advance

**Comment by gboeing** [comment]
If folks are landing here looking to create a graph from a .osm formatted XML file and then save it as a GraphML file, see the [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.graph.graph_from_xml). If you have a usage questions, per the contributing guidelines, please ask it on StackOverflow.
