### ISSUE TITLE
Handle attributes that are based on OSM way direction

### ISSUE THREAD

**Issue by teddyort** [gboeing/osmnx#784]
**Is your feature proposal related to a problem?**

Some OSM attributes are based implicitly on the knowledge of the direction of the underlying OSM way. For example, [lanes:forward](https://wiki.openstreetmap.org/wiki/Key:lanes#Lanes_in_different_directions) and lanes:backward both are described with respect to the order of the nodes in the way.

Problem: When osmnx generates a graph, it adds edges in both directions and copies the attributes to both edges. Therefore, if direction specific attributes are present, it becomes ambiguous as to which direction is "forward" and which is "backward".

**Describe the solution you'd like to propose**

I think a clean solution would be to add a tag to every edge _reversed={True, False}_ as a boolean indicating whether the edge is in the original direction or reversed.

I would be happy to provide a PR for this, if it would be helpful.

**Describe alternatives you've considered**

Another option would be to make a comprehensive list of direction dependent tags and handle them during graph creation. For example, the "forward" direction in attributes can be assigned to the forward edge, and the backward direction attributes to the backward edge. However, while this could be useful for some cases, I would worry that we couldn't forsee all the possible tags and usecases and so would prefer the proposed solution which provides the necessary information (that an edge was reversed) and leaves the processing to the end-user.

**Additional context**
As an example of the problem see https://www.openstreetmap.org/way/426604957. There the _lanes=3_, and _lanes:forward=2_ and _lanes:backward=1_. These attributes are copied "as is" to both the forward and backward directed edges in the MultiDiGraph which makes it impossible to detect which of the edges has 2 lanes, and which as 1. Additionally, this edge also has an attribute _turn:lanes:forward=left|through;right_ which describes the turning lanes of the edge approaching the intersection. Again, there would be know way to identify from the graph which of these edges the property applies to.

**Comment by gboeing** [comment]
Let me know if you'd like to contribute this as a PR.

**Comment by teddyort** [comment]
Yes, I'll be happy to. I should be able to submit it shortly.

**Comment by gboeing** [comment]
Closed by #814
