### ISSUE TITLE
Railway data field loss problem

### ISSUE THREAD

**Issue by lalalachidouzi** [gboeing/osmnx#787]
I have A problem with railway data. I can't get the railway network by setting network_type, so I download the railway data by setting custom_filter='["railway"~"rail|subway|light_rail|tram|narrow_gauge"]'.  However, there is no railway field in the data after downloading, so I can no longer distinguish rail or TRAM in the network.  How can we solve this problem?
thanks a lot !

**Comment by lalalachidouzi** [comment]
And this is my code:
import osmnx as ox
city=ox.graph_from_place('Taiwan',which_result=2,simplify=False,custom_filter='["railway"~"rail|light_rail|narrow_gauge|subway"]')
ox.save_graph_shapefile(city,'T_rail')

**Comment by gboeing** [comment]
See https://osmnx.readthedocs.io/en/latest/osmnx.html#osmnx.utils.config and https://stackoverflow.com/a/62106557/7321942

**Comment by lalalachidouzi** [comment]
> See https://osmnx.readthedocs.io/en/latest/osmnx.html#osmnx.utils.config and https://stackoverflow.com/a/62106557/7321942

That seems to solve my problem. I'll give it a try. Thank you very much!
