### ISSUE TITLE
No JSON object could be decoded 

### ISSUE THREAD

**Issue by LennyFan** [gboeing/osmnx#79]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

Thanks for sharing this library. I have been used this library for three months. 
It works so well until this week. Sometime when I call the functions from OSMNX, it will return the error that "No JSON object could be decoded". I thought maybe because I reach some limitation of calling the library, but even when I used the example you provided, it still returns this error sometimes.

```python
G = ox.graph_from_address('350 5th Ave, New York, NY', network_type='drive')
ox.plot_graph(G)
```

---------------------------------------------------------------------------

```python
ValueError                                Traceback (most recent call last)
<ipython-input-12-a49e37d104f7> in <module>()
----> 1 G = ox.graph_from_address('350 5th Ave, New York, NY', network_type='drive')
      2 ox.plot_graph(G)

/anaconda/envs/OSMNX/lib/python2.7/site-packages/osmnx/core.pyc in graph_from_address(address, distance, distance_type, network_type, simplify, retain_all, truncate_by_edge, return_coords, name, timeout, memory, max_query_area_size, clean_periphery, infrastructure)
   1427 
   1428     # geocode the address string to a (lat, lon) point
-> 1429     point = geocode(query=address)
   1430 
   1431     # then create a graph from this point

/anaconda/envs/OSMNX/lib/python2.7/site-packages/osmnx/utils.pyc in geocode(query)
    418     url = url_template.format(query)
    419     response = requests.get(url, timeout=60)
--> 420     results = response.json()
    421 
    422     # if results were returned, parse lat and long out of the result

/anaconda/envs/OSMNX/lib/python2.7/site-packages/requests/models.pyc in json(self, **kwargs)
    892                     # used.
    893                     pass
--> 894         return complexjson.loads(self.text, **kwargs)
    895 
    896     @property

/anaconda/envs/OSMNX/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    337             parse_int is None and parse_float is None and
    338             parse_constant is None and object_pairs_hook is None and not kw):
--> 339         return _default_decoder.decode(s)
    340     if cls is None:
    341         cls = JSONDecoder

/anaconda/envs/OSMNX/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    362 
    363         """
--> 364         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    365         end = _w(s, end).end()
    366         if end != len(s):

/anaconda/envs/OSMNX/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    380             obj, end = self.scan_once(s, idx)
    381         except StopIteration:
--> 382             raise ValueError("No JSON object could be decoded")
    383         return obj, end

ValueError: No JSON object could be decoded
```

#### What operating system, architecture, Python version, and OSMnx version are you using?

ANACONDA Jupyter Notebook4.3.1
Python 2.7
OSMNX 0.5.3

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)
<details>
appnope                   0.1.0                    py27_0  
asn1crypto                0.22.0                   py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0    conda-forge
bleach                    1.5.0                    py27_0  
branca                    0.2.0                    py27_0    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
certifi                   2017.4.17                py27_0    conda-forge
cffi                      1.10.0                   py27_0    conda-forge
chardet                   3.0.2                    py27_1    conda-forge
chardet                   3.0.4                     <pip>
click                     6.7                      py27_0    conda-forge
click-plugins             1.0.3                    py27_0    conda-forge
cligj                     0.4.0                    py27_0    conda-forge
configparser              3.5.0                    py27_0  
cryptography              1.8.1                    py27_0  
curl                      7.52.1                        0    conda-forge
cycler                    0.10.0                   py27_0    conda-forge
decorator                 4.0.11                   py27_0    conda-forge
descartes                 1.1.0                    py27_0    conda-forge
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_1    conda-forge
expat                     2.1.0                         2    conda-forge
fiona                     1.7.7               np112py27_0    conda-forge
folium                    0.3.0                    py27_0    conda-forge
freetype                  2.7                           1    conda-forge
freexl                    1.0.2                         1    conda-forge
functools32               3.2.3.2                  py27_1    conda-forge
gdal                      2.2.0               np112py27_2    conda-forge
geopandas                 0.2.1                    py27_4    conda-forge
geopy                     1.11.0                   py27_0    conda-forge
geos                      3.5.1                         1    conda-forge
get_terminal_size         1.0.0                    py27_0  
giflib                    5.1.4                         0    conda-forge
googlemaps                2.5.1                     <pip>
gurobi                    7.0.2                    py27_0    gurobi
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.18                        0    conda-forge
html5lib                  0.999                    py27_0  
icu                       58.1                          1    conda-forge
idna                      2.5                      py27_0    conda-forge
ipaddress                 1.0.18                   py27_0    conda-forge
ipykernel                 4.6.1                    py27_0  
ipython                   5.3.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
jinja2                    2.9.5                    py27_0    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
jsonschema                2.6.0                    py27_0  
jupyter_client            5.0.1                    py27_0  
jupyter_core              4.3.0                    py27_0  
kealib                    1.4.7                         2    conda-forge
krb5                      1.14.2                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.14                          4    conda-forge
libnetcdf                 4.4.1.1                       5    conda-forge
libpng                    1.6.28                        0    conda-forge
libpq                     9.5.4                         4    conda-forge
libspatialindex           1.8.5                         1    conda-forge
libspatialite             4.3.0a                       15    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.4                         4    conda-forge
markupsafe                1.0                      py27_0    conda-forge
matplotlib                2.0.2               np112py27_0    conda-forge
mistune                   0.7.4                    py27_0  
mkl                       2017.0.1                      0  
munch                     2.1.1                    py27_0    conda-forge
nbconvert                 5.2.1                    py27_0  
nbformat                  4.3.0                    py27_0  
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py27_0    conda-forge
notebook                  5.0.0                    py27_0  
numpy                     1.12.1                   py27_0  
openjpeg                  2.1.2                         2    conda-forge
openssl                   1.0.2k                        0    conda-forge
osmnx                     0.5.3                    py27_0    conda-forge
packaging                 16.8                     py27_0    conda-forge
pandas                    0.20.2              np112py27_0    conda-forge
pandocfilters             1.4.1                    py27_0  
path.py                   10.3.1                   py27_0  
pathlib2                  2.2.1                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pip                       9.0.1                    py27_0    conda-forge
proj4                     4.9.3                         3    conda-forge
prompt_toolkit            1.0.14                   py27_0  
psycopg2                  2.7.1                    py27_0    conda-forge
ptyprocess                0.5.1                    py27_0  
pycparser                 2.17                     py27_0    conda-forge
pygments                  2.2.0                    py27_0  
pyopenssl                 16.2.0                   py27_0    conda-forge
pyparsing                 2.2.0                    py27_0    conda-forge
pyproj                    1.9.5.1                  py27_0    conda-forge
pysal                     1.13.0                   py27_0    conda-forge
pysocks                   1.6.7                    py27_0    conda-forge
python                    2.7.13                        1    conda-forge
python-dateutil           2.6.0                    py27_0    conda-forge
pytz                      2017.2                   py27_0    conda-forge
pyzmq                     16.0.2                   py27_0  
readline                  6.2                           0    conda-forge
requests                  2.17.3                   py27_0    conda-forge
requests                  2.18.1                    <pip>
rtree                     0.8.3                    py27_0    conda-forge
scandir                   1.5                      py27_0  
scipy                     0.19.0              np112py27_0  
setuptools                33.1.1                   py27_0    conda-forge
shapely                   1.5.17              np112py27_3    conda-forge
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0    conda-forge
six                       1.10.0                   py27_1    conda-forge
sqlalchemy                1.1.5                    py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
ssl_match_hostname        3.5.0.1                  py27_1    conda-forge
subprocess32              3.2.7                    py27_0    conda-forge
terminado                 0.6                      py27_0  
testpath                  0.3.1                    py27_0  
tk                        8.5.19                        1    conda-forge
tornado                   4.5.1                    py27_0    conda-forge
traitlets                 4.3.2                    py27_0  
urllib3                   1.21.1                   py27_1    conda-forge
vincent                   0.4.4                    py27_0    conda-forge
wcwidth                   0.1.7                    py27_0  
wheel                     0.29.0                   py27_0    conda-forge
xerces-c                  3.1.4                         3    conda-forge
xz                        5.2.2                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
</details>

**Comment by gboeing** [comment]
The OSM nominatim API was sporadically down the past couple days. I was experiencing connecting problems too. When it was down, it would return an HTML error message. When OSMnx tries to parse the expected JSON, it hits HTML instead and throws this error.

If you see this error, try visiting the API [directly](https://nominatim.openstreetmap.org/?format=json&q=350%205th%20Ave,%20New%20York,%20NY) to verify that it's temporarily down.

**Comment by gboeing** [comment]
Just checking back -- any ongoing issue still?

**Comment by gboeing** [comment]
@LennyFan Just checking back -- any ongoing issue still?

**Comment by LennyFan** [comment]
@gboeing 
Hi, I haven't tried it the past few days. 
But if it's not the issue of OSMNX, I think we can close it, right?

I guess most of time it works. However, when I run the mathematical model, once it's down then my model will return the error instead of any solution. Hope it will get better soon.

Thanks for sharing this and answering my question!

**Comment by gboeing** [comment]
@LennyFan yeah, it's not an OSMnx specific issue. But: it would be a good idea in your script to handle this exception with try/except. You could attempt the API call (`ox.graph_from_address`) inside a try block, and if it fails, pause 5 minutes (like `time.sleep(300)`) then re-try. If the API is experiencing sporadic downtime or overload, this should allow your script to succeed eventually. It will work well if you are running a bulk automated process for many places that may take a long time to cycle through -- you don't want that breaking in the middle. Also good to configure `ox.config(use_cache=True)` so that if you complete your API call once, you can run the script again multiple times, using the cached response without having to call the API again.
