### ISSUE TITLE
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version.

### ISSUE THREAD

**Issue by johnziebro** [gboeing/osmnx#796]
**Problem description**
  - What did you do?
      - la_county = ox.geocode_to_gdf("Los Angeles County, USA")
  - What did you expect to happen?
      - Geocoding response without FutureWarning 
  - And what actually happened instead?
      - Correct geodataframe response with FutureWarning. 
      >osmnx/geocoder.py:110 FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead. gdf = gdf.append(_geocode_query_to_gdf(q, wr, by_osmid)) 

**Environment information**
  - What operating system are you using?
      - Ubuntu 21 
  - What Python version are you using?
      - Python 3.8 
  - What OSMnx version are you using?
      - 1.1.2 
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
osmnx = "1.1.2"
jupyterlab = "3.2.5"
</details>

**Minimal reproducible example**
```python
import osmnx as ox
la_county = ox.geocode_to_gdf("Los Angeles County, USA")
```

**Comment by gboeing** [comment]
We should be able to fix this with a `.concat()` call, a la: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append
