### ISSUE TITLE
graph_from_place giving networkx NetworkXPointlessConcept Exception

### ISSUE THREAD

**Issue by manugarri** [gboeing/osmnx#8]
I am trying to follow the article on the link [here](http://geoffboeing.com/2016/11/osmnx-python-street-networks/) (awesome blog btw).

However, every time I try to get a graph from a place using `graph_from_place` I get the following error:

```
  File "/home/manuel/miniconda3/envs/test/lib/python3.5/site-packages/osmnx/osmnx.py", line 1815, in graph_from_place
    truncate_by_edge=truncate_by_edge, name=name, timeout=timeout, memory=memory, max_query_area_size=max_query_area_size, clean_periphery=clean_periphery)
  File "/home/manuel/miniconda3/envs/test/lib/python3.5/site-packages/osmnx/osmnx.py", line 1749, in graph_from_polygon
    G = truncate_graph_polygon(G_buffered, polygon, retain_all=retain_all, truncate_by_edge=truncate_by_edge)
  File "/home/manuel/miniconda3/envs/test/lib/python3.5/site-packages/osmnx/osmnx.py", line 1320, in truncate_graph_polygon
    G = get_largest_component(G)
  File "/home/manuel/miniconda3/envs/test/lib/python3.5/site-packages/osmnx/osmnx.py", line 1099, in get_largest_component
    if not nx.is_weakly_connected(G):
  File "<decorator-gen-62>", line 2, in is_weakly_connected
  File "/home/manuel/miniconda3/envs/test/lib/python3.5/site-packages/networkx/utils/decorators.py", line 68, in _not_implemented_for
    return f(*args,**kwargs)
  File "/home/manuel/miniconda3/envs/test/lib/python3.5/site-packages/networkx/algorithms/components/weakly_connected.py", line 178, in is_weakly_connected
    """Connectivity is undefined for the null graph.""")
networkx.exception.NetworkXPointlessConcept: Connectivity i
```
`gdf_from_place` works, as well as `graph_from_point` .

I am  using spatialindex=1.8.5  

The environment's packages:

```
click==6.6
click-plugins==1.0.3
cligj==0.4.0
cycler==0.10.0
decorator==4.0.10
descartes==1.0.2
Fiona==1.7.1
geopandas==0.2.1
geopy==1.11.0
matplotlib==1.5.3
munch==2.0.4
networkx==1.11
numpy==1.11.2
OSMnx==0.1a1
pandas==0.19.1
pyparsing==2.1.10
pyproj==1.9.5.1
python-dateutil==2.6.0
pyttsx==1.1
pytz==2016.7
requests==2.12.1
Rtree==0.8.2
Shapely==1.5.17
six==1.10.0
```

My machine's watermark:
```
2016-11-28T15:33:21+01:00

CPython 3.5.1
IPython 4.2.0

compiler   : GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
system     : Linux
release    : 4.4.0-47-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 8
interpreter: 64bit
```

**Comment by gboeing** [comment]
It looks like the graph you're downloading has no nodes or edges -- hence the null graph in the error trace. The NetworkXPointlessConcept exception is one in which you are operating on a null graph. What is the full code you are running, and does your query definitely cover a spatial extent for which OSM has street network data?

**Comment by manugarri** [comment]
The code that fails is simply:

```
import osmnx as ox
G = ox.graph_from_place('Modena, Italy')
ox.plot_graph(G)
```

That is, the function `graph_from_place`

**Comment by gboeing** [comment]
I'm still struggling to reproduce this error. It's so basic that it's odd for it to happen at all. I'm wondering if there was a one-off fluke of some kind. 

Would you try upgrading OSMnx to its latest beta version: 0.1b2:

`pip install osmnx --upgrade`

**Comment by manugarri** [comment]
Yeah, thats what I thought. Im gonna update and see if that fixes it.

**Comment by raphadasilva** [comment]
Got the same error with version 0.1b2. Damned :-/...

**Comment by manugarri** [comment]
Same error with 0.1b2 :/  

Its weird because ` ox.graph_from_point((37.79, -122.41))` works

**Comment by lizhili** [comment]
this error not so weird because graph_from_point actually down osm data by bbox, it works well.
graph_from_place use osm_net_download query by str formed polygon, the query str ox.graph_from_place('Modena, Italy') cant download data even in browser.

**Comment by lizhili** [comment]
graph_from_place form request url by poly, the request headers is 28kb of ox.graph_from_place('Modena, Italy'), so error will happen in overpass api server,  return Request-URI Too Long. Maybe server's tomcat conf changed ?

**Comment by gboeing** [comment]
@lizhili graph_from_place does query Overpass by polygon, however it does so via HTTP POST. Thus the request URI is not too long and it isn't a server rejection issue. I just tested again across my environments (Windows, Mac, Python 2.7, 3.4, 3.5) and am unable to re-create this error...

**Comment by lizhili** [comment]
CentOS Linux release 7.2.1511 (Core)
Python 2.7.5
as i see in your code, when graph_from_palce called, gdf_from_place first called and it works well. Then use graph_from_polygon which download jsondata use osm_net_download, its query str is form by the polygon, this query is too large.

**Comment by manugarri** [comment]
I have linux as well, maybe its a linux issue?

**Comment by raphadasilva** [comment]
I use a Linux distribution too !

**Comment by gboeing** [comment]
It's seeming that way. If anyone is able to track down the specific issue (e.g., specific line of code, or problematic dependency, etc) on Linux, I'd be very grateful. I'm currently struggling to reproduce it, which makes fixing it difficult at the moment...

**Comment by lizhili** [comment]
Call ox.graph_from_place('Manhattan, New York, USA', network_type='drive'):
In truncate_graph_polygon, print('points within', points_within_geometry) get
`('points within',                          geometry      node
0  POINT (-73.9603796 40.7755735)  42459137)`
so after G.remove_nodes_from(nodes_outside_polygon['node'], the length of G is 0, so the "Connectivity is undefined for the null graph" error got.
@manugarri , i'm not familiar with all type and package used here,cant fix this, but you can just remove this line to use this function with some useless point, just bad solution, worded on my centos

**Comment by manugarri** [comment]
Just found the issue, sort of.

on line: 1267    `possible_matches_index = list(sindex.intersection(poly.bounds))`
Returns a list of indexes of points that intersect the gdf with the polygon
However,  it seems to either return an empy list or an array of zeroes. 
Unfortunately I am not a geopandas power user so I got a bit lost once I got into the intersects method of geopandas. I believe geopandas uses rtree to perform the intersection, so the issue might be with rtree itself.

I fixed by by, changing, in line 1307 : instead of using 

`points_within_geometry = intersect_index_quadrats(gdf_nodes, polygon) # (there is a typo btw)`

, to compute a multipoly and iteratively do an sindex.intersection, 

I just let geopandas calculate the whole intersection as:

`points_within_geometry = gdf_nodes[gdf_nodes.intersects(polygon)]`

Which seems to do the trick (as far as I can tell, intersect_index_quadrats is performing an intersection of the gdf nodes with the polygon boundary).

P.S. I noticed you import from rtree.index but don't use it, I would suggest removing the import.

**Comment by gboeing** [comment]
@manugarri that workaround might work for limited use cases with small networks, but the reason OSMnx uses a spatial index and this quadrat-based intersection algorithm is that without a spatial index, large queries (such as for a big city like New York with many street intersections and many vertices in its boundary polygon) will take hours to run.

The spatial index and algorithm work fine on Windows and Mac... we just need to figure out what's different in these Linux installations. It seems to have something to do with rtree or its dependencies.

**Comment by gboeing** [comment]
Ok I got a Debian-based Linux machine up and running (actually a Raspberry Pi 3, running Raspbian), and *OSMnx works successfully on this Linux machine*.

I first did a fresh install of Raspbian 1.1, kernel version 4.4, which includes Python 2.7.9 x64. Then I installed:

```
sudo apt-get install build-essential python-dev python-distlib python-setuptools python-pip python-wheel libzmq-dev libgdal-dev
```

to get some useful building and packaging tools, GDAL, etc. Then I installed some pandas optional dependencies:

```
sudo apt-get install xsel xclip libxml2-dev libxslt-dev python-lxml python-h5py python-numexpr python-dateutil python-six python-tz python-bs4 python-html5lib python-openpyxl python-tables python-xlrd python-xlwt cython python-sqlalchemy python-xlsxwriter python-jinja2 python-boto python-gflags python-googleapi python-httplib2 python-zmq
```

Then I installed libspatialindex, bottleneck, and rtree:

```
sudo apt-get libspatialindex-dev
sudo pip install bottleneck rtree
```

Next I installed the scientific Python stack:

```
sudo apt-get install python-numpy python-matplotlib python-scipy python-pandas python-requests python-geopy python-shapely python-pyproj
```

Some packages' versions in the apt repo were a bit stale, so I updated them with pip then installed geopandas and OSMnx:

```
sudo pip install numpy pandas shapely --upgrade
sudo pip install geopandas osmnx
```

Finally I opened a Python interpreter and ran:

```
import osmnx as ox
G = ox.graph_from_place('Modena, Italy')
ox.plot_graph(G)
```

**The code ran without error and displayed the plot of the Modena street network.**

The key components would presumably be libspatialindex-dev (I have 1.8.1-3 installed), libgdal-dev (I have 1.10.1+dfsg-8+b2 installed), rtree 0.8.2, and geopandas 0.2.1.

For reference I'm attaching the full list of Debian packages installed on this machine, plus the full list of Python packages in this environment. 
[packages-final.txt](https://github.com/gboeing/osmnx/files/644812/packages-final.txt)
[pip-freeze-final.txt](https://github.com/gboeing/osmnx/files/644813/pip-freeze-final.txt)

@manugarri @lizhili @raphadasilva hopefully this identifies some missing package or different version between your machines and this test machine I just set up fresh from scratch? Thanks for all your help so far in debugging this issue.

**Comment by gboeing** [comment]
Ok managed to re-create the problem and got it solved for Ubuntu desktop now as well.

It appears to be an rtree bug that affects the combination of rtree 0.8.2 + libspatialindex 1.8.5 + Linux. This bug was not reproducible for me on Mac or Windows. The bug is documented in [an issue](https://github.com/Toblerity/rtree/issues/68) in rtree's GitHub repo, and it was recently [fixed](https://github.com/Toblerity/rtree/pull/77) but hasn't been released yet. But you can fix it in the meantime by installing the GitHub version of rtree:

```
pip install --upgrade https://github.com/Toblerity/rtree/tarball/master
```

That got it working for me. 

*For reference*, here are the full steps I took starting with a fresh installation of Ubuntu 16.10. First I installed Miniconda and pip, then ran:

```
conda config --add channels conda-forge
conda install requests networkx geopy geopandas
sudo apt-get install libspatialindex-dev
pip install --upgrade https://github.com/Toblerity/rtree/tarball/master
pip install osmnx
```

This adds the conda-forge channel, installs the required packages and libspatialindex, upgrades rtree to the GitHub development version, then installs OSMnx. It's using spatialindex 1.8.5, 64-bit Python 3.5.1 on Ubuntu 16.10 with kernel 4.8.0-22-generic. Here's the complete list of Python packages installed in the environment (but *note* that rtree is in fact the upgraded GitHub dev version):

```
click==6.6
click-plugins==1.0.3
cligj==0.4.0
conda==4.2.13
cycler==0.10.0
decorator==4.0.10
descartes==1.0.2
Fiona==1.7.1
GDAL==2.1.2
geopandas==0.2.1
geopy==1.11.0
matplotlib==1.5.3
munch==2.0.4
networkx==1.11
numpy==1.11.2
osmnx==0.1b2
pandas==0.19.1
psycopg2==2.6.2
pycosat==0.6.1
pycrypto==2.6.1
pyparsing==2.1.10
pyproj==1.9.5.1
PySAL==1.13.0
python-dateutil==2.6.0
pytz==2016.7
requests==2.12.1
Rtree==0.8.2
ruamel-yaml===-VERSION
scipy==0.18.1
Shapely==1.5.17
six==1.10.0
SQLAlchemy==1.1.4
```

**Comment by gboeing** [comment]
Just confirmed the solution above is working for Python 2.7.12 on the same system, as well.

**Comment by raphadasilva** [comment]
Just tested that, and... it worked !!

I just uninstalled previous rtree version with : 

`sudo pip3 uninstall rtree` (just used pip if you're using Python 2.7)

Then : 

`sudo pip3 install --upgrade https://github.com/Toblerity/rtree/tarball/master`

And the beautiful Modena finally appears !

![modena](https://cloud.githubusercontent.com/assets/2005117/21090815/9ae5484c-c042-11e6-9839-12a2c4da1c82.png)

**Comment by manugarri** [comment]
Yup, works here as well. I think I will close this now :)

**Comment by gboeing** [comment]
FYI, rtree 0.8.3 (which fixes this issue) is now released and available via pip: https://github.com/Toblerity/rtree/issues/79#issuecomment-267150896

**Comment by manugarri** [comment]
Awesome! Good to know :)

**Comment by luthieisilra** [comment]
I've already try all of the above and still get this: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-uvhyrjci/

**Comment by gboeing** [comment]
@luthieisilra please open as a new issue, filling out the complete new issue template

**Comment by mejl** [comment]
I used before **graph_from_place** now I changed to **graph_from_xml**, and I get the error:

> NetworkXPointlessConcept at /
> Connectivity is undefined for the null graph.

This is how I used **graph_from_xml**:
`G = ox.graph_from_xml(XMLFile)`
