### ISSUE TITLE
gdf_from_place returns a point instead of a polygon

### ISSUE THREAD

**Issue by fzenoni** [gboeing/osmnx#80]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
The tutorial reports examples to get the boundaries of a place as a polygon, using Berkley CA, Bolivia, etc. I succeeded in executing similar requests, for instance with Milan, Italy.
However, when it comes to other specific cities, such as Copenhagen, Denmark or Brussels, Belgium, no polygon is actually returned, but just a single point.

#### What operating system, architecture, Python version, and OSMnx version are you using?
Ubuntu 16.04.3 LTS x86_64
Python 3.6.2
osmnx 0.5.3
 
#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>
asn1crypto                0.22.0                   py36_0    conda-forge
bleach                    1.5.0                    py36_0    conda-forge
boost                     1.64.0                   py36_3    conda-forge
boost-cpp                 1.64.0                        1    conda-forge
branca                    0.2.0                    py36_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.2                    py36_1    conda-forge
click                     6.7                      py36_0    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cryptography              1.9                      py36_0    conda-forge
curl                      7.54.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.10.10                       3    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
descartes                 1.1.0                    py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.1.0                         3    conda-forge
fiona                     1.7.8                    py36_1    conda-forge
folium                    0.3.0                    py36_0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
freexl                    1.0.2                         2    conda-forge
geopandas                 0.2.1                    py36_4    conda-forge
geopy                     1.11.0                   py36_0    conda-forge
geos                      3.5.1                         1    conda-forge
gettext                   0.19.7                        1    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.18                        1    conda-forge
html5lib                  0.9999999                py36_0    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.5                      py36_0    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.5                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12.1                        0    conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
kealib                    1.4.7                         2    conda-forge
krb5                      1.14.2                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.1.4                         2    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libkml                    1.3.0                         1    conda-forge
libnetcdf                 4.4.1.1                       6    conda-forge
libpng                    1.6.28                        1    conda-forge
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libspatialindex           1.8.5                         1    conda-forge
libspatialite             4.3.0a                       15    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2                    py36_2    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
mkl                       2017.0.3                      0  
munch                     2.2.0                    py36_0    conda-forge
nb_conda                  2.2.1                    py36_0    conda-forge
nb_conda_kernels          2.1.0                    py36_0    conda-forge
nbconvert                 5.2.1                    py36_1    conda-forge
nbformat                  4.3.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py36_0    conda-forge
notebook                  5.0.0                    py36_0    conda-forge
numpy                     1.13.1                   py36_0  
openjpeg                  2.1.2                         3    conda-forge
openssl                   1.0.2l                        0    conda-forge
osmnx                     0.5.3                    py36_0    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.3                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
poppler                   0.52.0                        2    conda-forge
poppler-data              0.4.7                         0    conda-forge
proj4                     4.9.3                         4    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psycopg2                  2.7.1                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyopenssl                 16.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysal                     1.13.0                   py36_0    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
python                    3.6.2                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                         3    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.3                   py36_0    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
scipy                     0.19.1              np113py36_0  
setuptools                36.2.2                   py36_0    conda-forge
shapely                   1.5.17                   py36_4    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlalchemy                1.1.11                   py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3                      py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.21.1                   py36_1    conda-forge
util-linux                2.21                          0  
vincent                   0.4.4                    py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xerces-c                  3.1.4                         3    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.2                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.8                         3    conda-forge
</details>

#### Code that reproduces the issue

```python
import osmnx as ox
G = ox.gdf_from_place('Brussels, Belgium')
ox.plot_shape(ox.project_gdf(G))
G
```

**Comment by fzenoni** [comment]
I have just found this page: https://github.com/gboeing/osmnx-examples/blob/master/notebooks/02-example-osm-to-shapefile.ipynb, that documents my issue.
I will make other trials and reformulate my query, but of course any help is welcome.

**Comment by fzenoni** [comment]
'Brussels, Belgium' -> 'Ville de Bruxelles, Belgium' did the trick

**Comment by gboeing** [comment]
See also #16 for an in-depth explanation.
