### ISSUE TITLE
Multilingual (English) names

### ISSUE THREAD

**Issue by EwoutH** [gboeing/osmnx#806]
Sometimes it would be useful to get street or structure names into a certain language, for example the local on or English. Especially in the [graph module](https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.graph) specifying the preferred language would be very nice.

See [Multilingual names](https://wiki.openstreetmap.org/wiki/Multilingual_names) on the OpenStreetMap wiki.

**Comment by gboeing** [comment]
Can you provide some use cases for this? What are some specific examples that you cannot do right now?

**Comment by EwoutH** [comment]
Thanks for getting back! For example, I want to study the road network of Bangladesh. By default, most names are in the native language, while for much roads an English name is available. Recognizing and filtering those roads (in a dataframe for example) is easier with the English names.

Some example code:
```python
import osmnx as ox

road_types = '["highway"~"motorway|trunk|motorway_link|trunk_link"]'
G = ox.graph_from_place("Bangladesh", custom_filter=road_types, clean_periphery=True)

nodes, edges = ox.graph_to_gdfs(G, nodes=True, edges=True, node_geometry=True, fill_edge_geometry=True)
edges = edges.to_crs(epsg=3857)

edges["name"].values.tolist()
```
Which gives:
```
[nan,
 'শেখ মুজিব সড়ক',
 nan,
 'বাদামতলী গোলচক্কর',
 'A K Khan Circle',
 'বন্দর সংযোগ সড়ক',
 'অলংকার মোড়',
 'মুরিং সড়ক',
 'মুরিং সড়ক',
 'বন্দর সংযোগ সড়ক',
 nan,
 nan,
 'মুরিং সড়ক',
 nan,
 'অলংকার মোড়',
 'বাদামতলী গোলচক্কর',
 ['শেখ মুজিব সড়ক', 'দেওয়ানহাট ওভারপাস'],
 nan,
 'Dewanhat Overpass',
 nan,
 nan,
 nan,
 ['ঢাকা-চট্টগ্রাম মহাসড়ক', 'ঢাকা - চট্টগ্রাম মহাসড়ক'],
 'A K Khan Circle',
```

**Comment by gboeing** [comment]
What would have to change in the query to specify which language we want names back in?

**Comment by gboeing** [comment]
@EwoutH checking back on this ^

**Comment by gboeing** [comment]
Closed for lack of activity during issue cleanup. Can reopen at a later data if/as needed.
