### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by Faarabi** [gboeing/osmnx#812]
Hi, 

I have installed OSMnx and then removed it but it seems that the directory is not removed completely, cause as I trying to reinstall it again by writing this command in conda prompt 

conda create -n ox --strict-channel-priority osmnx

I got this error:

A directory already exists at the target location 'C:\Users\username\Anaconda3\envs\ox'
but it is not a conda environment.

**Comment by gboeing** [comment]
This is not an OSMnx bug so I'm afraid we cannot assist. Please see the conda docs or ask on StackOverflow for conda help.
