### ISSUE TITLE
graph_from_polygon can't create graphs because nodes don’t have ‘x’ values

### ISSUE THREAD

**Issue by WolodjaZ** [gboeing/osmnx#817]
I need to take a graph from a defined polygon based on my custom overpass and nominatim. In some cases, my code produces networkx graphs, but there are some cases when function:
```python
osmnx.graph.graph_from_polygon
```
shows an error because some nodes don’t have ‘x’ values. When debugging I find out that in this line https://github.com/gboeing/osmnx/blob/e9e81baec2cc875999b669c48351176ce1642735/osmnx/graph.py#L577
There are new nodes added that have no data. I removed the nodes that do not have those parameters, but I don't know if this is the right way to do it. I also think that I know why this is happening. When we receive a json from an overpass, it has two types of tags, ‘way’ and ‘node’, on which a graph is constructed. From ‘node’ a graph is created, and then ways are added based on the ‘way’ tag. The ‘way’ tag has some parameters, for example nodes it goes through, and I think that there are some nodes that are not in the ‘node’ tag because in the 577 line, there are additional nodes added, but they have no data which would indicate that my assumption is correct. My question is whether the removal of those nodes that do not have the ‘x’ parameter after line 577 is the right way to do it.

**Comment by gboeing** [comment]
> My question is whether the removal of those nodes that do not have the ‘x’ parameter after line 577 is the right way to do it.

Thanks for using OSMnx. If this is a "how-to" question, please ask on StackOverflow, per the contributing guidelines. If this is a bug report, please fill out the complete new issue template including a reproducible demonstration, per the contributing guidelines, to reopen this issue.
