### ISSUE TITLE
_add_paths adds new nodes without 'x' or 'y' parameters.

### ISSUE THREAD

**Issue by WolodjaZ** [gboeing/osmnx#818]
https://github.com/gboeing/osmnx/blob/e9e81baec2cc875999b669c48351176ce1642735/osmnx/graph.py#L577
This function adds paths to a graph with already added nodes, but I encountered in my case that this function also creates new nodes that then leads to an error. In my environment where I used dockers of nominatim and overpass (I needed overpass and nominatim to run on my custom maps) 
```python
ox.utils.config(
            nominatim_endpoint='http://localhost:8080', 
            overpass_endpoint='http://localhost:12345/api/', 
            overpass_rate_limit=False
)
```
I encountered an error where this function adds not only paths but also nodes that are not already present in the graph but are mentioned in paths data. Those nodes do not have any inner data such as 'x' and 'y'  due to that such function as
```python
osmnx.graph.graph_from_polygon
```
can't be executed. My idea that I used is to filter out all the nodes that don’t have  'x' or 'y' params:
```python
empty_nodes = [node for node, data in G.nodes.items() if 'x' not in data.keys() or 'y' not in data.keys() ]
for node_id in empty_nodes:
      G.remove_node(node_id)
```

But I also don’t know if this strange behavior is only because something is wrong with my nominatim or overpass dockers.

**Comment by gboeing** [comment]
> But I also don’t know if this strange behavior is only because something is wrong with my nominatim or overpass dockers.

Impossible for me to say either off the top of my head. Please provide a complete, minimal, reproducible code snippet to test this independently. If this error is unique your own hosted instance, this wouldn't appear to be a bug with OSMnx which is designed to work with the public, reference Overpass/Nominatim instances.

**Comment by gboeing** [comment]
Closed for lack of activity. Can reopen at a later date as needed.
