### ISSUE TITLE
Bike network GraphML contains driveway labelled edges

### ISSUE THREAD

**Issue by unvaiso** [gboeing/osmnx#82]
Hi,
I have saved the biking network of a city on a graphml, and noticed the presence of a few driveways. Is this okay or should I discard them ?
Thank you.

**Comment by unvaiso** [comment]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
I have saved the biking network of a city on a graphml, and noticed the presence of a few driveways. I expected only cycleways.

#### What operating system, architecture, Python version, and OSMnx version are you using?
Ubuntu 16.04 LTS, 64-bits, python 2.7, OSMNX 0.5.3

#### Packages
<details>
adium-theme-ubuntu (0.3.4)
appdirs (1.4.3)
arrow (0.10.0)
astroid (1.5.3)
backports.functools-lru-cache (1.4)
beautifulsoup4 (4.4.1)
brewer2mpl (1.4.1)
ccsm (0.9.12.2)
certifi (2017.7.27.1)
chardet (2.3.0)
click (6.7)
click-plugins (1.0.3)
cligj (0.4.0)
colorlover (0.2.1)
compizconfig-python (0.9.12.2)
configparser (3.5.0)
cycler (0.10.0)
Cython (0.23.4)
dash (0.17.4)
dash-core-components (0.5.1)
dash-html-components (0.6.0)
dash-renderer (0.7.3)
dash.ly (0.17.3)
decorator (4.0.6)
descartes (1.1.0)
digits (5.1.dev0, /home/djeb/digits)
dnspython (1.12.0)
dominate (2.2.1)
duplicity (0.7.6)
easydict (1.6)
enum34 (1.1.6)
Fiona (1.7.9)
Flask (0.12.2)
Flask-Compress (1.4.0)
Flask-SeaSurf (0.2.2)
Flask-SocketIO (2.6)
Flask-WTF (0.11)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
future (0.16.0)
futures (3.1.1)
GDAL (2.2.1)
geog (0.0.2)
geopandas (0.2.1)
gevent (1.0.2)
gevent-socketio (0.3.6)
gevent-websocket (0.9.3)
ggplot (0.11.5)
greenlet (0.4.9)
gunicorn (19.7.1)
gyp (0.1)
h5py (2.6.0)
html5lib (0.999)
idna (2.6)
imageio (1.6)
imposm.parser (1.0.7)
ipython (2.4.1)
ipython-genutils (0.2.0)
isort (4.2.15)
itsdangerous (0.24)
Jinja2 (2.8)
joblib (0.11)
jsonschema (2.6.0)
jupyter-core (4.3.0)
lazy-object-proxy (1.3.1)
leveldb (0.1)
lmdb (0.87)
lockfile (0.12.2)
lxml (3.5.0)
mapbox-vector-tile (1.2.0)
markerlib (0.6.0)
MarkupSafe (0.23)
matplotlib (2.0.2)
mccabe (0.6.1)
mercurial (3.7.3)
mock (2.0.0)
moviepy (0.2.2.11)
munch (2.2.0)
mwparserfromhell (0.5)
nbformat (4.4.0)
networkx (1.11)
nltk (3.2.4)
nose (1.3.7)
numpy (1.13.1)
osmgraph (0.0.1)
osmnx (0.5.3)
osmqa-parser (0.0.1)
packaging (16.8)
pandas (0.20.3)
pandas-datareader (0.4.0)
patsy (0.4.1)
pbr (3.0.0)
pexpect (4.0.1)
Pillow (3.1.2)
pip (8.1.1)
plotly (2.0.11)
prettytensor (0.7.4)
progressbar (2.3)
protobuf (3.0.0)
psutil (5.2.2)
ptyprocess (0.5)
pyclipper (1.0.6)
pycrypto (2.6.1)
pycurl (7.43.0)
pydot (1.0.28)
pygobject (3.20.0)
pylint (1.7.1)
PyOpenGL (3.0.2)
pyparsing (2.0.3)
pyproj (1.9.5.1)
Pyste (0.9.10)
python-apt (1.1.0b1)
python-dateutil (2.6.1)
python-dotenv (0.6.4)
python-engineio (1.0.1)
python-gflags (1.5.1)
python-louvain (0.8)
python-snappy (0.5)
python-socketio (1.5.0)
pytz (2017.2)
PyYAML (3.11)
QDarkStyle (2.2.1)
redis (2.10.5)
requests (2.18.4)
requests-file (1.4.2)
requests-ftp (0.3.1)
rq (0.8.0)
Rtree (0.8.3)
scikit-fmm (0.0.9)
scikit-image (0.10.1)
scikit-learn (0.18.2)
scipy (0.19.1)
setuptools (36.2.2)
Shapely (1.6b4)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
skdata (0.0.4)
statsmodels (0.8.0)
subprocess32 (3.2.7)
tensorflow (0.11.0)
tensorflow-gpu (1.1.0)
Theano (0.9.0.dev3)
torchfile (0.1.0)
tqdm (4.10.0)
traitlets (4.3.2)
tsne (0.1.7)
unity-lens-photos (1.0)
urllib3 (1.22)
Werkzeug (0.12.2)
wheel (0.29.0)
wikipedia (1.4.0)
wrapt (1.10.10)
WTForms (2.1)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
youtube-dl (2017.5.29)
</details>

#### Code that reproduces the issue

```python
G = ox.graph_from_place('Strasbourg, France', network_type='bike')
ox.save_graphml(G, 'file.graphml')

```

**Comment by gboeing** [comment]
@unvaiso ok, I see what you mean. Yes, when network_type='bike', OSMnx downloads the bikable network. This means all the routes that bikes *can* travel along, not just the routes designed only for bikes. Once you've downloaded the bikable network, you can always filter it to remove any edges that are not tagged as cycleways.

**Comment by NaniBird** [comment]
Thanks. So, how does osmnx consider a driveway bikable or not ?

**Comment by unvaiso** [comment]
Thanks. So, how does osmnx consider a driveway bikable or not ?

**Comment by gboeing** [comment]
@unvaiso you can see the specific filter [here](https://github.com/gboeing/osmnx/blob/f9177d3b1fca41545fe3ccb59fc087a4fc4c8991/osmnx/core.py#L532-533). The basic logic is that we filter out everything that is explicitly not bikable, and keep what remains.

**Comment by unvaiso** [comment]
Thanks!
