### ISSUE TITLE
Overpass endpoint can't be served on /interpreter

### ISSUE THREAD

**Issue by jeremyk6** [gboeing/osmnx#829]
Hello,

The GIS service of my city serve an Overpass endpoint. However, the address they propose probably use a reverse proxy that redirects to /interpreter. Thus, their endpoint can't be used on OSMnx as /interpreter seems to be always added to the Overpass url (downloader.py:755).

Maybe I missed something, or it's not a common way to serve an Overpass endpoint, but I thought it would be interesting to let you know 🙂 .

**Comment by gboeing** [comment]
How does it handle the `status` endpoint/ See: https://github.com/gboeing/osmnx/blob/main/osmnx/downloader.py#L359

We use the base URL ("https://overpass-api.de/api") defined in the `settings` module then append "/status" or "/interpreter" on it to make our queries.

**Comment by gboeing** [comment]
In line with the comment at https://github.com/gboeing/osmnx/issues/832#issuecomment-1146419342, we are going to keep OSMnx consistent and compatible with the reference Overpass API instance's current release. In that sense, OSMnx can work with any Overpass server as long as its essential functionality matches the current reference version. We cannot support older or nonconforming instances as there will be too much ad hoc code to maintain.
