### ISSUE TITLE
Migrating networkx from 1.x to 2.0

### ISSUE THREAD

**Issue by mhsekhavat** [gboeing/osmnx#83]
Is there any branch or progress on adapting new networkx api?
There is a guide that might help: https://networkx.github.io/documentation/development/reference/migration_guide_from_1.x_to_2.0.html?highlight=migration

**Comment by gboeing** [comment]
See also #23

**Comment by gboeing** [comment]
Branch for updating OSMnx to work with the networkx 2.x API: https://github.com/gboeing/osmnx/tree/nx2

**Comment by mhsekhavat** [comment]
Thanks

**Comment by gboeing** [comment]
See also PR #84
