### ISSUE TITLE
use_cache not working

### ISSUE THREAD

**Issue by Harshpanday** [gboeing/osmnx#834]
Hey everyone,
I just discovered this amazing library.
I am trying to calculate the distance between 2 longitude and latitude points in **Columbus, Ohio**.
It takes the code 1 minute to return the distance, is that normal? I have made ```ox.settings.use_cache=True``` as well, the cache folder is the default ```./cache```.
I read the example notebook and I am calculating the distance as follows
```
import osmnx as ox
ox.settings.use_cache=True
G = ox.graph_from_place("Columbus, Ohio, USA", network_type="drive")
#fig, ax = ox.plot_graph(G)
G = ox.speed.add_edge_speeds(G)
G = ox.speed.add_edge_travel_times(G)
orig = ox.distance.nearest_nodes(G, X=-83.034785, Y=39.945993)
dest = ox.distance.nearest_nodes(G, X=-82.99194508, Y=40.04649963)
route = ox.shortest_path(G, orig, dest, weight="")
edge_lengths = ox.utils_graph.get_route_edge_attributes(G, route, "length")
print(round(sum(edge_lengths)*0.000621371))  //I am converting the distance into miles
```
Am I doing something wrong, or is it normal to take 1 whole minute to get the distance? In my final code I will be calculating distances b/w 150-200K longitudes and latitude pairs, so if there is a faster approach to calculate the distance I will be very grateful if someone could let me know.

**Comment by Harshpanday** [comment]
Saving and loading makes it way faster.
I am currently saving it as a Graphml file. I just want to calculate the distances, so is Graphml the best way to save the file or is there another way, which can make loading and calculating distance even faster?

**Comment by gboeing** [comment]
Thanks for using OSMnx! Per the contributing guidelines, please ask usage questions on StackOverflow.
