### ISSUE TITLE
geometries_from_point() function returns Error 1027 (Invalid value for an argument): utm: Invalid value for zone)

### ISSUE THREAD

**Issue by Gustacro** [gboeing/osmnx#843]
**Problem description**
Created a function that will iterate over a geodataframe retrieving a lat and lon values to feed the function  `omsnx.geometries_from_point()`, then save them into a list.

tried it with different CRS: 4326, 3395, and 3857, same Error.

 `omsnx.geometries_from_point()` should return geodataframe containing building geometries from defined lat & lon with specific tag and distance params.
Returning : `CRSError: Invalid projection: +proj=utm +zone=1913565 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs: (Internal Proj Error: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone)`.

**Environment information**
MacOS Monterey 12.4, Python 3.9, OSMnx 1.2.1, JupyterLab 8.0.1

<details>
# Name                    Version                   Build  Channel
affine                    2.3.0                    pypi_0    pypi
anyio                     3.5.0           py310h2ec42d9_0    conda-forge
appnope                   0.1.2           py310h2ec42d9_2    conda-forge
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0          py310he24745e_1    conda-forge
asttokens                 2.0.5                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports                 1.0                        py_2    conda-forge
backports-functools-lru-cache 1.6.4                    pypi_0    pypi
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.1.0                    pypi_0    pypi
blosc                     1.21.0               he49afe7_0    conda-forge
boost-cpp                 1.74.0               hdbf7018_7    conda-forge
branca                    0.4.2                    pypi_0    pypi
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
brotlipy                  0.7.0           py310he24745e_1003    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
cairo                     1.16.0            he01c77b_1009    conda-forge
certifi                   2022.6.15       py310h2ec42d9_0    conda-forge
cffi                      1.15.0          py310hcc37b68_0    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.3           py310h2ec42d9_1    conda-forge
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.2                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
cryptography              36.0.1          py310ha82f1d4_0    conda-forge
curl                      7.81.0               hf45b732_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1           py310hba3363e_0    conda-forge
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 0.8.2                    pypi_0    pypi
expat                     2.4.4                he49afe7_0    conda-forge
fiona                     1.8.21          py310h56b70e1_0    conda-forge
flit-core                 3.6.0                    pypi_0    pypi
folium                    0.12.1.post1             pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.94              h10f422b_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.29.1          py310he24745e_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.6                h0d85af4_0    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
gdal                      3.4.1                    pypi_0    pypi
geopandas                 0.10.2                   pypi_0    pypi
geopandas-base            0.10.2             pyha770c72_1    conda-forge
geos                      3.10.2               he49afe7_0    conda-forge
geotiff                   1.7.0                h0ca5f94_6    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
greenlet                  1.1.1           py310he9d5cce_0  
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.12.1          nompi_h2f0ef1a_103    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.1          py310h2ec42d9_0    conda-forge
importlib-resources       5.4.0                    pypi_0    pypi
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.9.1           py310ha188af9_0    conda-forge
ipython                   8.0.1           py310h2ec42d9_1    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1          py310h2ec42d9_0    conda-forge
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h0d85af4_0    conda-forge
json-c                    0.15                 hcb556a6_0    conda-forge
json5                     0.9.5                    pypi_0    pypi
jsonschema                4.4.0                    pypi_0    pypi
jupyter-client            7.1.2                    pypi_0    pypi
jupyter-server            1.13.5                   pypi_0    pypi
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2           py310h2ec42d9_0    conda-forge
jupyter_server            1.13.5             pyhd8ed1ab_1    conda-forge
jupyterlab                3.2.9                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.10.3                   pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.10.3             pyhd8ed1ab_0    conda-forge
kealib                    1.4.14               ha22a8b1_3    conda-forge
kiwisolver                1.3.2           py310h2fea185_1    conda-forge
krb5                      1.19.2               hcfbf3a7_3    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcurl                   7.81.0               hf45b732_0    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libdap4                   3.20.6               h3e144a0_2    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgdal                   3.4.1                h23c56e6_3    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_4    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libimagequant             2.17.0               h9bde063_1    conda-forge
libkml                    1.3.0             h8fd9edb_1014    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h6609ca0_101    conda-forge
libnghttp2                1.46.0               h6f36284_0    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     14.2                 hea3049e_0    conda-forge
librttopo                 1.1.0                hec60dd8_9    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libspatialindex           1.9.3                he49afe7_4    conda-forge
libspatialite             5.0.1               h88e7940_14    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libzip                    1.8.0                h8b0c345_1    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               13.0.1               hda6cdc1_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
mapclassify               2.4.3                    pypi_0    pypi
markupsafe                2.0.1           py310he24745e_1    conda-forge
matplotlib-base           3.5.1           py310hfc59cd6_0    conda-forge
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4           py310he24745e_1005    conda-forge
mplleaflet                0.0.5                    pypi_0    pypi
munch                     2.5.0                    pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
nbclassic                 0.3.5                    pypi_0    pypi
nbclient                  0.5.11                   pypi_0    pypi
nbconvert                 6.4.2           py310h2ec42d9_0    conda-forge
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.3                  he49afe7_0    conda-forge
nest-asyncio              1.5.4                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
notebook                  6.4.8                    pypi_0    pypi
nspr                      4.32                 hcd9eead_1    conda-forge
nss                       3.74                 h31e2bf1_0    conda-forge
numpy                     1.22.2          py310hfbbbacf_0    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1p               hfe4f2af_0    conda-forge
osmnx                     1.2.1                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.1           py310hdd25497_0    conda-forge
pandoc                    2.17.1.1             h694c41f_0    conda-forge
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1           py310h9351100_1    conda-forge
pip                       22.0.3                   pypi_0    pypi
pixman                    0.40.0               hbcb3906_0    conda-forge
poppler                   22.01.0              h9573804_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 he8fe76e_0    conda-forge
proj                      8.2.1                h1512c50_0    conda-forge
prometheus-client         0.13.1                   pypi_0    pypi
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27                   pypi_0    pypi
psycopg2                  2.9.3                    pypi_0    pypi
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21                     pypi_0    pypi
pygments                  2.11.2                   pypi_0    pypi
pyopenssl                 22.0.0                   pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
pyproj                    3.3.0           py310h4ed7dbf_1    conda-forge
pyrsistent                0.18.1          py310he24745e_0    conda-forge
pysocks                   1.7.1           py310h2ec42d9_4    conda-forge
python                    3.10.2          h1dd9edd_3_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3                   pypi_0    pypi
pyzmq                     22.3.0          py310hcce64c8_1    conda-forge
rasterio                  1.2.10          py310h4193d74_4    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
rtree                     0.9.7           py310had9ce37_3    conda-forge
scikit-learn              1.0.2           py310h598de7d_0    conda-forge
scipy                     1.8.0           py310h47774c9_1    conda-forge
send2trash                1.8.0                    pypi_0    pypi
setuptools                60.9.2          py310h2ec42d9_0    conda-forge
shapely                   1.8.0           py310hbb63119_5    conda-forge
six                       1.16.0                   pypi_0    pypi
sniffio                   1.2.0           py310h2ec42d9_2    conda-forge
snuggs                    1.4.7                    pypi_0    pypi
spyder-kernels            0.2.6                    pypi_0    pypi
sqlalchemy                1.4.32          py310hca72f7f_0  
sqlite                    3.37.0               h23a322b_0    conda-forge
stack-data                0.2.0                    pypi_0    pypi
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
terminado                 0.13.1          py310h2ec42d9_0    conda-forge
testpath                  0.5.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tiledb                    2.6.2                hca4410a_1    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.1             py310he24745e_2    conda-forge
traitlets                 5.1.1                    pypi_0    pypi
tzcode                    2021e                h0d85af4_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unicodedata2              14.0.0          py310he24745e_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.2.3                    pypi_0    pypi
wheel                     0.37.1                   pypi_0    pypi
xerces-c                  3.2.3                h6564042_4    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xyzservices               2022.2.0                 pypi_0    pypi
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
</details>

**Provide a complete minimal reproducible example**

Your example code snippet here must be *minimal* so it doesn't contain extraneous code unrelated to your specific problem and it must be *complete* so we can independently run it from top to bottom by copying/pasting it into a Python interpreter. That means all imports and all variables must be defined. If you're unsure how to create a good reproducible example, read [this guide](https://stackoverflow.com/help/minimal-reproducible-example). Do not post a screenshot of your code or error message: provide it as text.

```python
import osmnx as ox
import os

print(to_get_footprint.crs)
#  3857

def bldn_footprint(to_get_footprint, df_list, noneGeom_bldn_list):
    # iterate over the geodataframe 
    for idx, r in to_get_footprint.iterrows():
        name = r['name'] 
        df_temp = ox.geometries_from_point((r['latitude'], r['longitude']), tags={'building': True} , dist=50)
        if len(df_temp) >0:
            df_temp['name'] = name
            df_list.append(df_temp)
    else:
        noneGeom_bldn_list.append(name)
        
    return df_list, noneGeom_bldn_list

# define dataframe empty list
df_list = []
# list of None geometries
noneGeom_bldn_list = []

# call function 
df_list_return, noneGeom_list_return = bldn_footprint(ilas_to_get_footprint, df_list, noneGeom_bldn_list)
```

**Comment by nickodell** [comment]
I'm currently trying to reproduce your bug. Could you add two things to your example?

1. I get `NameError: name 'to_get_footprint' is not defined` when I run your example on line 4. Can you edit your example and define this variable?
2. I get `NameError: name 'ilas_to_get_footprint' is not defined` when I run your example on line 26. Can you define this variable?

Thanks.

**Comment by Gustacro** [comment]
Thank you for the fast check on my post.
I found what was causing the error. The lat and lon created that were fed to the function `omsnx.geometries_from_point()` were created using an incorrect crs, because of this, the function was not able to process the (lat ,lon) tuple.
The crs that I used to create the (lat, lon) was 3395 WGS 84 / World Mercator.

Thank you again.
