### ISSUE TITLE
osmnx.geometries_from_point() Error : JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Gustacro** [gboeing/osmnx#844]
- What did you do?
  I used a (lat, lon) tuple and passed to the function `ox.geometries_from_point((lat, lon), tags={'building': True}, dist=100)` to retrieve buildings but is returning a series of Exception Errors.
  - What did you expect to happen?
  Expected to return one or multiple geodataframes per building found.
  - And what actually happened instead?
  the following Exception Errors were printed:  

JSONDecodeError Traceback (most recent call last) File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/site-packages/requests/models.py:910, in Response.json(self, **kwargs) 909 try: --> 910 return complexjson.loads(self.text, **kwargs) 911 except JSONDecodeError as e: 912 # Catch JSON-related errors and raise as requests.JSONDecodeError 913 # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/json/init.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw) 343 if (cls is None and object_hook is None and 344 parse_int is None and parse_float is None and 345 parse_constant is None and object_pairs_hook is None and not kw): --> 346 return _default_decoder.decode(s) 347 if cls is None:

File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/json/decoder.py:337, in JSONDecoder.decode(self, s, _w) 333 """Return the Python representation of s (a str instance 334 containing a JSON document). 335 336 """ --> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 338 end = _w(s, end).end()

File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx) 354 except StopIteration as err: --> 355 raise JSONDecodeError("Expecting value", s, err.value) from None 356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError Traceback (most recent call last) File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/site-packages/osmnx/downloader.py:784, in overpass_request(data, pause, error_pause) 783 try: --> 784 response_json = response.json() 785 if "remark" in response_json:

File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/site-packages/requests/models.py:917, in Response.json(self, **kwargs) 916 else: --> 917 raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: [Errno Expecting value]

OSM3S Response
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" an even number of float values must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" at least 3 lat/lon float value pairs must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" an even number of float values must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" at least 3 lat/lon float value pairs must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" an even number of float values must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" at least 3 lat/lon float value pairs must be provided.

: 0
During handling of the above exception, another exception occurred:

Exception Traceback (most recent call last) Input In [79], in ----> 1 ox.geometries_from_point((-121.986000, 37.372300), tags={'building': True} , dist=100)

File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/site-packages/osmnx/geometries.py:118, in geometries_from_point(center_point, tags, dist) 115 polygon = utils_geo.bbox_to_poly(north, south, east, west) 117 # create GeoDataFrame of geometries within this polygon --> 118 gdf = geometries_from_polygon(polygon, tags) 120 return gdf

File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/site-packages/osmnx/geometries.py:278, in geometries_from_polygon(polygon, tags) 270 raise TypeError( 271 "Boundaries must be a shapely Polygon or MultiPolygon. If you requested " 272 "geometries from place name, make sure your query resolves to a Polygon or " 273 "MultiPolygon, and not some other geometry, like a Point. See OSMnx " 274 "documentation for details." 275 ) 277 # download the geometry data from OSM --> 278 response_jsons = downloader._osm_geometries_download(polygon, tags) 280 # create GeoDataFrame from the downloaded data 281 gdf = _create_gdf(response_jsons, polygon, tags)

File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/site-packages/osmnx/downloader.py:584, in _osm_geometries_download(polygon, tags) 582 for polygon_coord_str in polygon_coord_strs: 583 query_str = _create_overpass_query(polygon_coord_str, tags) --> 584 response_json = overpass_request(data={"data": query_str}) 585 response_jsons.append(response_json) 587 utils.log( 588 f"Got all geometries data within polygon from API in {len(polygon_coord_strs)} request(s)" 589 )

File ~/opt/anaconda3/envs/geo_spatial/lib/python3.10/site-packages/osmnx/downloader.py:801, in overpass_request(data, pause, error_pause) 798 else: 799 # else, this was an unhandled status code, throw an exception 800 utils.log(f"{domain} returned {sc}", level=lg.ERROR) --> 801 raise Exception(f"Server returned\n{response} {response.reason}\n{response.text}") 803 _save_to_cache(prepared_url, response_json, sc) 804 return response_json

Exception: Server returned <Response [400]> Bad Request

OSM3S Response
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" an even number of float values must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" at least 3 lat/lon float value pairs must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" an even number of float values must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" at least 3 lat/lon float value pairs must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" an even number of float values must be provided.

Error: line 1: static error: For the attribute "bounds" of the element "polygon-query" at least 3 lat/lon float value pairs must be provided.

**Environment information**
MAcOS Monterey version : 12.4
Python version : 3.10.2
OSMnx version : 1.2.1
Jupyter-lab version : 3.2.9 

<details>
# Name                    Version                   Build  Channel
affine                    2.3.0                    pypi_0    pypi
anyio                     3.5.0           py310h2ec42d9_0    conda-forge
appnope                   0.1.2           py310h2ec42d9_2    conda-forge
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0          py310he24745e_1    conda-forge
asttokens                 2.0.5                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports                 1.0                        py_2    conda-forge
backports-functools-lru-cache 1.6.4                    pypi_0    pypi
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.1.0                    pypi_0    pypi
blosc                     1.21.0               he49afe7_0    conda-forge
boost-cpp                 1.74.0               hdbf7018_7    conda-forge
branca                    0.4.2                    pypi_0    pypi
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
brotlipy                  0.7.0           py310he24745e_1003    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
cairo                     1.16.0            he01c77b_1009    conda-forge
certifi                   2022.6.15       py310h2ec42d9_0    conda-forge
cffi                      1.15.0          py310hcc37b68_0    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.3           py310h2ec42d9_1    conda-forge
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.2                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
cryptography              36.0.1          py310ha82f1d4_0    conda-forge
curl                      7.81.0               hf45b732_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1           py310hba3363e_0    conda-forge
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 0.8.2                    pypi_0    pypi
expat                     2.4.4                he49afe7_0    conda-forge
fiona                     1.8.21          py310h56b70e1_0    conda-forge
flit-core                 3.6.0                    pypi_0    pypi
folium                    0.12.1.post1             pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.94              h10f422b_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.29.1          py310he24745e_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.6                h0d85af4_0    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
gdal                      3.4.1                    pypi_0    pypi
geopandas                 0.10.2                   pypi_0    pypi
geopandas-base            0.10.2             pyha770c72_1    conda-forge
geos                      3.10.2               he49afe7_0    conda-forge
geotiff                   1.7.0                h0ca5f94_6    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
greenlet                  1.1.1           py310he9d5cce_0  
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.12.1          nompi_h2f0ef1a_103    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.1          py310h2ec42d9_0    conda-forge
importlib-resources       5.4.0                    pypi_0    pypi
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.9.1           py310ha188af9_0    conda-forge
ipython                   8.0.1           py310h2ec42d9_1    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1          py310h2ec42d9_0    conda-forge
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h0d85af4_0    conda-forge
json-c                    0.15                 hcb556a6_0    conda-forge
json5                     0.9.5                    pypi_0    pypi
jsonschema                4.4.0                    pypi_0    pypi
jupyter-client            7.1.2                    pypi_0    pypi
jupyter-server            1.13.5                   pypi_0    pypi
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2           py310h2ec42d9_0    conda-forge
jupyter_server            1.13.5             pyhd8ed1ab_1    conda-forge
jupyterlab                3.2.9                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.10.3                   pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.10.3             pyhd8ed1ab_0    conda-forge
kealib                    1.4.14               ha22a8b1_3    conda-forge
kiwisolver                1.3.2           py310h2fea185_1    conda-forge
krb5                      1.19.2               hcfbf3a7_3    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcurl                   7.81.0               hf45b732_0    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libdap4                   3.20.6               h3e144a0_2    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgdal                   3.4.1                h23c56e6_3    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_4    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libimagequant             2.17.0               h9bde063_1    conda-forge
libkml                    1.3.0             h8fd9edb_1014    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h6609ca0_101    conda-forge
libnghttp2                1.46.0               h6f36284_0    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     14.2                 hea3049e_0    conda-forge
librttopo                 1.1.0                hec60dd8_9    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libspatialindex           1.9.3                he49afe7_4    conda-forge
libspatialite             5.0.1               h88e7940_14    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libzip                    1.8.0                h8b0c345_1    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               13.0.1               hda6cdc1_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
mapclassify               2.4.3                    pypi_0    pypi
markupsafe                2.0.1           py310he24745e_1    conda-forge
matplotlib-base           3.5.1           py310hfc59cd6_0    conda-forge
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4           py310he24745e_1005    conda-forge
mplleaflet                0.0.5                    pypi_0    pypi
munch                     2.5.0                    pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
nbclassic                 0.3.5                    pypi_0    pypi
nbclient                  0.5.11                   pypi_0    pypi
nbconvert                 6.4.2           py310h2ec42d9_0    conda-forge
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.3                  he49afe7_0    conda-forge
nest-asyncio              1.5.4                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
notebook                  6.4.8                    pypi_0    pypi
nspr                      4.32                 hcd9eead_1    conda-forge
nss                       3.74                 h31e2bf1_0    conda-forge
numpy                     1.22.2          py310hfbbbacf_0    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1p               hfe4f2af_0    conda-forge
osmnx                     1.2.1                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.1           py310hdd25497_0    conda-forge
pandoc                    2.17.1.1             h694c41f_0    conda-forge
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1           py310h9351100_1    conda-forge
pip                       22.0.3                   pypi_0    pypi
pixman                    0.40.0               hbcb3906_0    conda-forge
poppler                   22.01.0              h9573804_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 he8fe76e_0    conda-forge
proj                      8.2.1                h1512c50_0    conda-forge
prometheus-client         0.13.1                   pypi_0    pypi
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27                   pypi_0    pypi
psycopg2                  2.9.3                    pypi_0    pypi
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21                     pypi_0    pypi
pygments                  2.11.2                   pypi_0    pypi
pyopenssl                 22.0.0                   pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
pyproj                    3.3.0           py310h4ed7dbf_1    conda-forge
pyrsistent                0.18.1          py310he24745e_0    conda-forge
pysocks                   1.7.1           py310h2ec42d9_4    conda-forge
python                    3.10.2          h1dd9edd_3_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3                   pypi_0    pypi
pyzmq                     22.3.0          py310hcce64c8_1    conda-forge
rasterio                  1.2.10          py310h4193d74_4    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
rtree                     0.9.7           py310had9ce37_3    conda-forge
scikit-learn              1.0.2           py310h598de7d_0    conda-forge
scipy                     1.8.0           py310h47774c9_1    conda-forge
send2trash                1.8.0                    pypi_0    pypi
setuptools                60.9.2          py310h2ec42d9_0    conda-forge
shapely                   1.8.0           py310hbb63119_5    conda-forge
six                       1.16.0                   pypi_0    pypi
sniffio                   1.2.0           py310h2ec42d9_2    conda-forge
snuggs                    1.4.7                    pypi_0    pypi
spyder-kernels            0.2.6                    pypi_0    pypi
sqlalchemy                1.4.32          py310hca72f7f_0  
sqlite                    3.37.0               h23a322b_0    conda-forge
stack-data                0.2.0                    pypi_0    pypi
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
terminado                 0.13.1          py310h2ec42d9_0    conda-forge
testpath                  0.5.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tiledb                    2.6.2                hca4410a_1    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.1             py310he24745e_2    conda-forge
traitlets                 5.1.1                    pypi_0    pypi
tzcode                    2021e                h0d85af4_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unicodedata2              14.0.0          py310he24745e_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.2.3                    pypi_0    pypi
wheel                     0.37.1                   pypi_0    pypi
xerces-c                  3.2.3                h6564042_4    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xyzservices               2022.2.0                 pypi_0    pypi
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
</details>

```python
import osmnx as ox

ox.geometries_from_point((-121.986000, 37.372300), tags={'building': True} , dist=100)

```

**Comment by gboeing** [comment]
You provided a `lng, lat` point instead of a `lat, lng` point.
