### ISSUE TITLE
networkx graph get_edge_data might return by default None; causes problems in get_route_edge_attributes

### ISSUE THREAD

**Issue by msurkovsky** [gboeing/osmnx#845]
The method `get_route_edge_attributes` calls networkx.graph.`get_edge_data` and expects a dict with attributes. However, the method might return None by default which causes problems.

**Comment by gboeing** [comment]
Thanks for flagging this. Do you have a minimal working example to demonstrate this causing an error?

**Comment by gboeing** [comment]
@msurkovsky checking back on this. Can you provide a minimal working example to reproduce this bug?

**Comment by msurkovsky** [comment]
Yes. sorry for delay, I'll prepare it by the end of the week.

**Comment by msurkovsky** [comment]
After investigating my app. I finally found the problem, it is my mistake as the program wrongly loaded a different map from cache. Then I was accessing edges that were not actually present in graph.
