### ISSUE TITLE
Keep node attributes when consolidating intersections

### ISSUE THREAD

**Issue by christophsteinacker** [gboeing/osmnx#846]
First, I want to thank you for developing this great tool.

**Is your feature proposal related to a problem?**

No, not a real problem more an enhancement for more convenience. When intersections are consolidated with `consolidate_intersections`, all the attributes of the original nodes are lost during the consolidation process, unless a node is not merged with other nodes at all, in which case it retains all its attributes, right?

**Describe the solution you'd like to propose**

I think it would be nice if a new node representing a cluster of merged nodes could "inherit" the attributes of all merged nodes. This could be handled analogously to how edges and their attributes are handled when simplifying a graph with `simplify_graph`. This would be particularly handy if more node attributes are to be downloaded with a customized `useful_tags_node`. Since you probably downloaded them for some reason, and you might want to keep them even when editing the graph. Some attributes maybe should not be carried over, like `street_count`, as they are inherently different for the new node.

**Describe alternatives you've considered**

I currently copy the attributes over to the consolidated graph via the `osmid_original` attribute from the old graph. But I find it more simple if it would be handled in osmnx directly.

**Additional context**

My idea would be adding some lines to Step 5 of `_consolidate_intersections_rebuild_graph`:
```python
# STEP 5
# create a new node for each cluster of merged nodes
# regroup now that we potentially have new cluster labels from step 3
groups = gdf.groupby("cluster")
for cluster_label, nodes_subset in groups:

    osmids = nodes_subset.index.to_list()
    if len(osmids) == 1:
        # if cluster is a single node, add that node to new graph
        osmid = osmids[0]
        H.add_node(cluster_label, osmid_original=osmid, **G.nodes[osmid])
    else:
        # if cluster is multiple merged nodes, create one new node to
        # represent them
        node_attributes = dict()
        for osmid in osmids:
            node_data = G.nodes[osmid]
            for attr in node_data:
                if attr in node_attributes:
                    # if this key already exists in the dict, append it to the
                    # value list
                    node_attributes[attr].append(node_data[attr])
                else:
                    # if this key doesn't already exist, set the value to a list
                    # containing the one value
                    if attr not in ["street_count", "x", "y"]:
                            node_attributes[attr] = [node_data[attr]]
        for attr in node_attributes:
            if len(set(node_attributes[attr])) == 1:
                # if there's only 1 unique value in this attribute list,
                # consolidate it to the single value (the zero-th):
                node_attributes[attr] = node_attributes[attr][0]
            else:
                # otherwise, if there are multiple values, keep one of each
                node_attributes[attr] = list(set(node_attributes[attr]))
        H.add_node(
                cluster_label,
                osmid_original=str(osmids),
                x=nodes_subset["x"].iloc[0],
                y=nodes_subset["y"].iloc[0],
        )
```

Thanks

**Comment by gboeing** [comment]
@christophsteinacker thanks for suggesting this. I do understand the value of this feature. However, it was deliberately left out of the consolidation function: the reasoning is that there are multiple ways someone might want this to behave, and it creates a lot of complexity. However, I'll leave some sample code here others can adapt if they want to copy attributes over to their newly consolidated nodes.

```python
import ast
import networkx as nx
import osmnx as ox

# create, project, and consolidate a graph
ox.settings.useful_tags_node += ["crossing"]
G = ox.graph_from_place("Piedmont, CA, USA", network_type="drive")
Gpc = ox.consolidate_intersections(ox.project_graph(G))

# copy attribute values over from old nodes to newly merged nodes
for tag in ox.settings.useful_tags_node:
    values = []
    for new_node, new_data in Gpc.nodes(data=True):
        if not type(new_data["osmid_original"]) == int:
            for osmid in ast.literal_eval(new_data["osmid_original"]):
                if tag in G.nodes[osmid]:
                    values.append(G.nodes[osmid][tag])
    if len(values) > 0:
        if len(set(values)) == 1:
            values = values[0]
        nx.set_node_attributes(Gpc, values={new_node: values}, name=tag)
```

**Comment by christophsteinacker** [comment]
@gboeing thanks for the explanation and the sample code.
