### ISSUE TITLE
Update `oneway` attribute for reversed edges

### ISSUE THREAD

**Issue by the-matt-morris** [gboeing/osmnx#848]
**Is your feature proposal related to a problem?**

#814 introduced the `reversed` attribute.  [All attributes from the forward edge except `geometry` and `reversed` are inherited](https://github.com/gboeing/osmnx/blob/e650b3ab5b2ce1cf14aae83596645a54617d3a7e/osmnx/graph.py#L784-L786).  The `oneway` field remains `False` on these reversed edges.  I can understand the motivation to keep it this way, but it seems misleading to have both forward and reversed edges included and both labeled as twoway.

**Describe the solution you'd like to propose**

For any edges that have both forward and reversed edges returned, label these with `oneway == True`.  I recognize doing this will likely result in all edges returned being oneway, and it could be argued that the `oneway` field could be removed altogether.

**Describe alternatives you've considered**

Remove the `reversed` field and just return these as single edges with `oneway == False` (i.e. revert)

**Additional context**

I had a project that relied on the `oneway` field and generated edges when `oneway` was False.  The introduction of `reversed` edges has done the work I was doing previously.  The network ended up with many duplicate edges when it relied on the `oneway` field, since these `reversed` edges inherited `oneway == False`.

Thanks!  If accepted, I can submit a PR.

**Comment by gboeing** [comment]
This is as intended. *All* edges in a directed graph are "one-way." The attribute value identifies whether or not the OSM way this edge represents is tagged as a one-way street or not.

**Comment by the-matt-morris** [comment]
Ok thanks for the explanation.  Makes sense that these attributes are OSM metadata.
