### ISSUE TITLE
"Module 'osmnx' has no attribute 'get_nearest_node'"

### ISSUE THREAD

**Issue by vic131** [gboeing/osmnx#850]
I'm executing an old tutorial and several functions are deprecated now. But i'm having trouble replacing  one of them, wich i didnt found an alternativa anywere : 

```# Deine origin and desination locations 
origin_point = (33.787201, -84.405076) 
destination_point = (33.764135, -84.394980)# get the nearest nodes to the locations 
origin_node = ox.get_nearest_node(G, origin_point) 
destination_node = ox.get_nearest_node(G, destination_point)
```

https://towardsdatascience.com/find-and-plot-your-optimal-path-using-plotly-and-networkx-in-python-17e75387b873

**Comment by gboeing** [comment]
Per the contributing guidelines, please ask usage questions on StackOverflow to reserve the issue tracker for bug reporting and feature development. Have you read the package [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.distance.nearest_nodes) and usage [examples](https://github.com/gboeing/osmnx-examples), which explain how to do what you are trying? The function you are using was deprecated and removed/replaced a while back in #675.
