### ISSUE TITLE
OSMnx-exported XML file failing on load with Osmium

### ISSUE THREAD

**Issue by bfmat** [gboeing/osmnx#852]
I am trying to export a graph to XML using OSMnx and then use Osmium to convert it to PBF. However, Osmium refuses to read it:

```
> osmium fileinfo -e out.osm

File:
  Name: out.osm
  Format: XML
  Compression: none
  Size: 7619
Can not read file with version 1
```

I don't know if this is a bug in OSMnx or Osmium. I have attached the OSM XML in the hopes that someone will know whether the problem is with OSMnx or Osmium. I am new to OSM; thanks for your patience, and please point me elsewhere if I'm asking in the wrong place.

I have also included a 5-line Python repro below to generate the faulty (?) OSM XML file.

**Environment information**
  - macOS 12.4
  - Python 3.10.5
  - OSMnx 1.2.1

**Python reproduction**

```python
import osmnx as ox
ox.settings.all_oneway = True
ox.settings.log_console = True
G = ox.graph_from_point((46.4735, -81.0338), dist=50, network_type='walk')
ox.save_graph_xml(G, filepath='out.osm')
```

**Resulting XML**

```<osm version="1" generator="OSMnx"><node id="2017401835" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1" lat="46.4738411" lon="-81.0333296" /><node id="2017401836" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1" lat="46.4739373" lon="-81.0331847" /><node id="2017401837" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1" lat="46.4739472" lon="-81.0334705" /><node id="2017401843" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1" lat="46.4735566" lon="-81.0337641" /><node id="2017401857" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1" lat="46.4733848" lon="-81.0335871" /><way id="0" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1"><nd ref="2017401835" /><nd ref="2017401836" /><tag k="highway" v="footway" /></way><way id="1" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1"><nd ref="2017401835" /><nd ref="2017401843" /><tag k="highway" v="footway" /></way><way id="2" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1"><nd ref="2017401835" /><nd ref="2017401857" /><tag k="highway" v="footway" /></way><way id="3" timestamp="2017-01-01T00:00:00Z" uid="1" user="osmnx" version="1" changeset="1"><nd ref="2017401837" /><nd ref="2017401835" /><tag k="highway" v="footway" /></way></osm>```

**Comment by bfmat** [comment]
My bad. OSMConvert does the trick. I'll open a bug report with Osmium instead.

**Comment by bfmat** [comment]
OSMConvert will open the file; however, when I increase `dist` from 50 to 3000, it outputs the following warnings:

```osmconvert Warning: wrong sequence at way 1009
osmconvert Warning: next object is way 101
osmconvert Warning: wrong sequence at way 1019
osmconvert Warning: next object is way 102
osmconvert Warning: wrong sequence at way 1029
osmconvert Warning: next object is way 103```

**Comment by gboeing** [comment]
Thanks @bfmat. I'm not sure what changed but I believe the problem is here:
```
<osm version="1" generator="OSMnx">
```
The current OSM [API](https://wiki.openstreetmap.org/wiki/API) is 0.6. If you manually edit your XML file to change the version to 0.6, it should work. Please confirm and we can work to resolve this bug.

**Comment by gboeing** [comment]
Proposed fix in #853.

**Comment by gboeing** [comment]
Using the codebase in #853 and this snippet:
```python
import osmnx as ox
ox.settings.all_oneway = True
ox.settings.log_console = True
G = ox.graph_from_point((46.4735, -81.0338), dist=3000)
ox.save_graph_xml(G, filepath='out.osm')
```
Then running:
```
osmium fileinfo -e out.osm
```
I am successfully getting:
```
File:
  Name: out.osm
  Format: XML
  Compression: none
  Size: 2219600
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=OSMnx
    version=0.6
[======================================================================] 100% 
Data:
  Bounding box: (-81.0729071,46.4467116,-80.9946254,46.5004606)
  Timestamps:
    First: 2017-01-01T00:00:00Z
    Last: 2017-01-01T00:00:00Z
  Objects ordered (by type and id): no
  Multiple versions of same object: unknown (because objects in file are unordered)
  CRC32: not calculated (use --crc/-c to enable)
  Number of changesets: 0
  Number of nodes: 3762
  Number of ways: 5530
  Number of relations: 0
  Smallest changeset ID: 0
  Smallest node ID: 282081367
  Smallest way ID: 0
  Smallest relation ID: 0
  Largest changeset ID: 0
  Largest node ID: 9926847554
  Largest way ID: 5529
  Largest relation ID: 0
  Number of buffers: 2 (avg 4646 objects per buffer)
  Sum of buffer sizes: 1135200 (0.001 GB)
  Sum of buffer capacities: 2097152 (0.002 GB, 54% full)
Metadata:
  All objects have following metadata attributes: all
  Some objects have following metadata attributes: all
```

**Comment by bfmat** [comment]
Sorry for slow reply. Yep, seems to work. Thanks so much for the quick fix!
