### ISSUE TITLE
simplify_graph removes node of a road between a continous driveway that creates nodes/intersection on either side of it

### ISSUE THREAD

**Issue by jaguardo** [gboeing/osmnx#859]
Background:
I didn't see this problem with native osmnx only (if the osm graph is attained through the osmnx library only), but when I pulled a graph from another library (pyrosm).  I'm not sure the difference between the "simplification" that occurs when osmnx pulls the map directly (overpass API?) versus osmnx.simplify_graph.  But I'll show the difference I'm seeing.

Only osmnx:

```
import osmnx as ox
point =  39.61, -84.073
G = ox.graph_from_point(point, network_type="all_private", dist=2000)
fig, ax = ox.plot_graph(G, node_color="r", figsize=(25, 25))
```

![image](https://user-images.githubusercontent.com/28798269/186428105-3602eee8-2d26-4848-ae13-f1bb0b6a193f.png)

please note the connected "driveway" at the middle of the resulting figure:

![image](https://user-images.githubusercontent.com/28798269/186428343-782cf6ad-b4db-4902-9d9d-8be168163e24.png)

Now if I pull the data via pyrosm, I obviously get a lot more nodes as nothing has been simplified yet.

pyrosm -> osmnx
```
from pyrosm import OSM, get_data
from shapely import geometry

fp = get_data("ohio")
osm = OSM(fp)

ll_lat = 39.6
ur_lat = 39.62
ll_lon = -84.083
ur_lon = -84.063

p1 = geometry.Point(ll_lon,ll_lat)
p2 = geometry.Point(ll_lon,ur_lat)
p3 = geometry.Point(ur_lon,ur_lat)
p4 = geometry.Point(ur_lon,ll_lat)

pointList = [p1, p2, p3, p4, p1]
poly = geometry.Polygon([[p.x, p.y] for p in pointList])

osm = OSM(fp, bounding_box=poly)
drive_net = osm.get_network(network_type="all")

import osmnx as ox

nodes, edges = osm.get_network(network_type="driving", nodes=True)
G = osm.to_graph(nodes, edges, graph_type="networkx")
fig, ax = ox.plot_graph(G, node_color="r",figsize=(25, 25))
```

![image](https://user-images.githubusercontent.com/28798269/186429593-11aad56a-96aa-40d9-895d-fd07363c4f24.png)

now if I attempt to simplify it

```
G2 = ox.simplify_graph(G, strict=False)
fig, ax = ox.plot_graph(G2, node_color="r",figsize=(25, 25))
```

Admittedly, I received a `TypeError: unhashable type: 'LineString'` when I do this, so added:
```
att_list = ['geometry']
for n1, n2, d in G.edges(data=True):
    for att in att_list:
        d.pop(att, None)
```

Regardless the resulting plot:
![image](https://user-images.githubusercontent.com/28798269/186431158-193edd05-76a4-475b-be2b-b92a493cf294.png)

See how the main road has been subdivided between the 2 driveway intersections with the road?  I've since gone into open street map and removed that point, so it shouldn't cause an issue (however it will take awhile for the change to take effect and be downloadable).

this can obviously be just an issue with pyrosm and the way it transfers to osmnx, but thought it was worth noting.

**Environment information**
  - What operating system are you using?
Win10, conda, jupyter
  - What Python version are you using?
Python 3.10.5
  - What OSMnx version are you using?
1.2.2
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
# Name                    Version                   Build  Channel                                                                                                               affine                    2.3.1              pyhd8ed1ab_0    conda-forge                                                                                                         anyio                     3.6.1           py310h5588dad_0    conda-forge                                                                                                         aom                       3.4.0                h0e60522_1    conda-forge                                                                                                         argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge                                                                                                         argon2-cffi-bindings      21.2.0          py310he2412df_2    conda-forge                                                                                                         asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge                                                                                                         attrs                     21.4.0                   pypi_0    pypi                                                                                                                babel                     2.10.3             pyhd8ed1ab_0    conda-forge                                                                                                         backcall                  0.2.0              pyh9f0ad1d_0    conda-forge                                                                                                         backports                 1.0                        py_2    conda-forge                                                                                                         backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge                                                                                                     beautifulsoup4            4.11.1             pyha770c72_0    conda-forge                                                                                                         blas                      1.0                         mkl    anaconda                                                                                                            bleach                    5.0.1              pyhd8ed1ab_0    conda-forge                                                                                                         blosc                     1.21.1               h74325e0_3    conda-forge                                                                                                         boost-cpp                 1.74.0               h9f4b32c_8    conda-forge                                                                                                         branca                    0.5.0              pyhd8ed1ab_0    conda-forge                                                                                                         brotli                    1.0.9                h8ffe710_7    conda-forge                                                                                                         brotli-bin                1.0.9                h8ffe710_7    conda-forge                                                                                                         brotlipy                  0.7.0           py310he2412df_1004    conda-forge                                                                                                      bzip2                     1.0.8                h8ffe710_4    conda-forge                                                                                                         c-compiler                1.4.2                h8ffe710_0    conda-forge                                                                                                         ca-certificates           2022.6.15            h5b45459_0    conda-forge                                                                                                         cairo                     1.16.0            h0ac17fb_1012    conda-forge                                                                                                         certifi                   2022.6.15                pypi_0    pypi                                                                                                                cffi                      1.15.1          py310hcbf9ad4_0    conda-forge                                                                                                         cfitsio                   4.1.0                h5a969a9_0    conda-forge                                                                                                         charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge                                                                                                         clangdev                  5.0.0                   flang_3    conda-forge                                                                                                         click                     8.1.3           py310h5588dad_0    conda-forge                                                                                                         click-plugins             1.1.1                      py_0    conda-forge                                                                                                         cligj                     0.7.2              pyhd8ed1ab_1    conda-forge                                                                                                         cmake                     3.23.2               h39d44d4_0    conda-forge                                                                                                         colorama                  0.4.5              pyhd8ed1ab_0    conda-forge                                                                                                         compilers                 1.4.2                h57928b3_0    conda-forge                                                                                                         cryptography              37.0.1          py310h21b164f_0                                                                                                                        curl                      7.83.1               h789b8ee_0    conda-forge                                                                                                         cxx-compiler              1.4.2                h2d74725_0    conda-forge                                                                                                         cycler                    0.11.0             pyhd8ed1ab_0    conda-forge                                                                                                         cykhash                   2.0.0           py310h8a704f9_1    conda-forge                                                                                                         cython                    0.29.32         py310h8a704f9_0    conda-forge                                                                                                         debugpy                   1.6.0           py310h8a704f9_0    conda-forge                                                                                                         decorator                 5.1.1              pyhd8ed1ab_0    conda-forge                                                                                                         defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge                                                                                                         entrypoints               0.4                pyhd8ed1ab_0    conda-forge                                                                                                         executing                 0.9.1              pyhd8ed1ab_0    conda-forge                                                                                                         expat                     2.4.8                h39d44d4_0    conda-forge                                                                                                         fastkml                   0.12                     pypi_0    pypi                                                                                                                ffmpeg                    5.1.0           gpl_ha0349d7_100    conda-forge                                                                                                        ffmpeg-python             0.2.0                    pypi_0    pypi                                                                                                                fiona                     1.8.21          py310hfed10a5_2    conda-forge                                                                                                         flang                     5.0.0           he025d50_20180525    conda-forge                                                                                                       flang_win-64              5.0.0           h13ae965_20180526    conda-forge                                                                                                       flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge                                                                                                         folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge                                                                                                         font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge                                                                                                         font-ttf-inconsolata      3.000                h77eed37_0    conda-forge                                                                                                         font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge                                                                                                         font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge                                                                                                         fontconfig                2.14.0               hce3cb01_0    conda-forge                                                                                                         fonts-conda-ecosystem     1                             0    conda-forge                                                                                                         fonts-conda-forge         1                             0    conda-forge                                                                                                         fonttools                 4.34.4          py310he2412df_0    conda-forge                                                                                                         fortran-compiler          1.4.2                h9655429_0    conda-forge                                                                                                         freetype                  2.10.4               h546665d_1    conda-forge                                                                                                         freexl                    1.0.6                ha8e266a_0    conda-forge                                                                                                         future                    0.18.2                   pypi_0    pypi                                                                                                                gdal                      3.5.1           py310hbcd9b36_2    conda-forge                                                                                                         geomag                    0.9.2015                 pypi_0    pypi                                                                                                                geopandas                 0.11.1             pyhd8ed1ab_0    conda-forge                                                                                                         geopandas-base            0.11.1             pyha770c72_0    conda-forge                                                                                                         geos                      3.11.0               h39d44d4_0    conda-forge                                                                                                         geotiff                   1.7.1                h714bc5f_3    conda-forge                                                                                                         gettext                   0.19.8.1          ha2e2712_1008    conda-forge                                                                                                         glib                      2.72.1               h7755175_0    conda-forge                                                                                                         glib-tools                2.72.1               h7755175_0    conda-forge                                                                                                         glpk                      4.65              h8ffe710_1004    conda-forge                                                                                                         gst-plugins-base          1.20.3               he07aa86_0    conda-forge                                                                                                         gstreamer                 1.20.3               hdff456e_0    conda-forge                                                                                                         hdf4                      4.2.15               h0e5069d_4    conda-forge                                                                                                         hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge                                                                                                      icu                       70.1                 h0e60522_0    conda-forge                                                                                                         idna                      3.3                pyhd8ed1ab_0    conda-forge                                                                                                         igraph                    0.9.9                h89236e6_0    conda-forge                                                                                                         importlib-metadata        4.11.4          py310h5588dad_0    conda-forge                                                                                                         importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge                                                                                                         importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge                                                                                                         intel-openmp              2021.4.0          haa95532_3556    anaconda                                                                                                            ipykernel                 6.15.1             pyh025b116_0    conda-forge                                                                                                         ipython                   8.4.0           py310h5588dad_0    conda-forge                                                                                                         ipython_genutils          0.2.0                      py_1    conda-forge                                                                                                         ipywidgets                7.7.1              pyhd8ed1ab_0    conda-forge                                                                                                         jedi                      0.18.1             pyhd8ed1ab_2    conda-forge                                                                                                         jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge                                                                                                         joblib                    1.1.0              pyhd8ed1ab_0    conda-forge                                                                                                         jpeg                      9e                   h8ffe710_2    conda-forge                                                                                                         json5                     0.9.5              pyh9f0ad1d_0    conda-forge                                                                                                         jsonschema                4.9.1              pyhd8ed1ab_0    conda-forge                                                                                                         jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge                                                                                                         jupyter_core              4.11.1          py310h5588dad_0    conda-forge                                                                                                         jupyter_server            1.18.1             pyhd8ed1ab_0    conda-forge                                                                                                         jupyterlab                3.4.4              pyhd8ed1ab_0    conda-forge                                                                                                         jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge                                                                                                         jupyterlab_server         2.15.0             pyhd8ed1ab_0    conda-forge                                                                                                         jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge                                                                                                         kealib                    1.4.15               hdf81f3a_1    conda-forge                                                                                                         kiwisolver                1.4.4           py310h476a331_0    conda-forge                                                                                                         krb5                      1.19.3               h1176d77_0    conda-forge                                                                                                         lcms2                     2.12                 h2a16943_0    conda-forge                                                                                                         lerc                      4.0.0                h63175ca_0    conda-forge                                                                                                         libblas                   3.9.0           1_h8933c1f_netlib    conda-forge                                                                                                       libbrotlicommon           1.0.9                h8ffe710_7    conda-forge                                                                                                         libbrotlidec              1.0.9                h8ffe710_7    conda-forge                                                                                                         libbrotlienc              1.0.9                h8ffe710_7    conda-forge                                                                                                         libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge                                                                                                       libclang                  14.0.6          default_h77d9078_0    conda-forge                                                                                                      libclang13                14.0.6          default_h77d9078_0    conda-forge                                                                                                      libcurl                   7.83.1               h789b8ee_0    conda-forge                                                                                                         libdeflate                1.13                 h8ffe710_0    conda-forge                                                                                                         libffi                    3.4.2                h8ffe710_5    conda-forge                                                                                                         libflang                  5.0.0           h6538335_20180525    conda-forge                                                                                                       libgdal                   3.5.1                h472ea22_2    conda-forge                                                                                                         libglib                   2.72.1               h3be07f2_0    conda-forge                                                                                                         libiconv                  1.16                 he774522_0    conda-forge                                                                                                         libkml                    1.3.0             h9859afa_1014    conda-forge                                                                                                         liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge                                                                                                       liblapacke                3.9.0           5_hd5c7e75_netlib    conda-forge                                                                                                       libnetcdf                 4.8.1           nompi_h85765be_104    conda-forge                                                                                                      libogg                    1.3.4                h8ffe710_1    conda-forge                                                                                                         libpng                    1.6.37               h1d00b33_3    conda-forge                                                                                                         libpq                     14.5                 hfcc5ef8_0    conda-forge                                                                                                         librttopo                 1.1.0               h2842628_11    conda-forge                                                                                                         libsodium                 1.0.18               h8d14728_1    conda-forge                                                                                                         libspatialindex           1.9.3                h39d44d4_4    conda-forge                                                                                                         libspatialite             5.0.1               ha17912d_18    conda-forge                                                                                                         libsqlite                 3.39.2               h8ffe710_1    conda-forge                                                                                                         libssh2                   1.10.0               h680486a_3    conda-forge                                                                                                         libtiff                   4.4.0                h92677e6_3    conda-forge                                                                                                         libvorbis                 1.3.7                h0e60522_0    conda-forge                                                                                                         libwebp                   1.2.3                h8ffe710_1    conda-forge                                                                                                         libwebp-base              1.2.3                h8ffe710_2    conda-forge                                                                                                         libxcb                    1.13              hcd874cb_1004    conda-forge                                                                                                         libxml2                   2.9.14               hf5bbc77_3    conda-forge                                                                                                         libzip                    1.9.2                hfed4ece_1    conda-forge                                                                                                         libzlib                   1.2.12               h8ffe710_2    conda-forge                                                                                                         llvm-meta                 5.0.0                         0    conda-forge                                                                                                         llvmlite                  0.38.1                   pypi_0    pypi                                                                                                                lz4-c                     1.9.3                h8ffe710_1    conda-forge                                                                                                         m2w64-gcc-libgfortran     5.3.0                         6    conda-forge                                                                                                         m2w64-gcc-libs            5.3.0                         7    conda-forge                                                                                                         m2w64-gcc-libs-core       5.3.0                         7    conda-forge                                                                                                         m2w64-gmp                 6.1.0                         2    conda-forge                                                                                                         m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge                                                                                                      mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge                                                                                                         markupsafe                2.1.1           py310he2412df_1    conda-forge                                                                                                         matplotlib                3.5.2           py310h5588dad_1    conda-forge                                                                                                         matplotlib-base           3.5.2           py310h79a7439_1    conda-forge                                                                                                         matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge                                                                                                         meson                     0.63.0                   pypi_0    pypi                                                                                                                mistune                   0.8.4           py310he2412df_1005    conda-forge                                                                                                      mkl                       2021.4.0           haa95532_640    anaconda                                                                                                            mkl-service               2.4.0           py310hcf6e17e_0    conda-forge                                                                                                         mkl_fft                   1.3.1           py310h94c019f_1    conda-forge                                                                                                         mkl_random                1.2.2           py310h4ed8f06_0                                                                                                                        mpir                      3.0.0             he025d50_1002    conda-forge                                                                                                         msys2-conda-epoch         20160418                      1    conda-forge                                                                                                         munch                     2.5.0                      py_0    conda-forge                                                                                                         munkres                   1.1.4              pyh9f0ad1d_0    conda-forge                                                                                                         nbclassic                 0.4.3              pyhd8ed1ab_0    conda-forge                                                                                                         nbclient                  0.6.6              pyhd8ed1ab_0    conda-forge                                                                                                         nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge                                                                                                         nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge                                                                                                         nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge                                                                                                         nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge                                                                                                         nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge                                                                                                         networkx                  2.8.5              pyhd8ed1ab_0    conda-forge                                                                                                         ninja                     1.11.0               h2d74725_0    conda-forge                                                                                                         notebook                  6.4.12             pyha770c72_0    conda-forge                                                                                                         notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge                                                                                                         numba                     0.55.2                   pypi_0    pypi                                                                                                                numexpr                   2.8.3                    pypi_0    pypi                                                                                                                numpy                     1.22.4                   pypi_0    pypi                                                                                                                numpy-base                1.22.3          py310h206c741_0                                                                                                                        openh264                  2.2.0                h0e60522_2    conda-forge                                                                                                         openjpeg                  2.4.0                hb211442_1    conda-forge                                                                                                         openmp                    5.0.0                    vc14_1    conda-forge                                                                                                         openssl                   1.1.1q               h8ffe710_0    conda-forge                                                                                                         osmnx                     1.2.2              pyhd8ed1ab_0    conda-forge                                                                                                         packaging                 21.3               pyhd8ed1ab_0    conda-forge                                                                                                         pandas                    1.4.3           py310hf5e1058_0    conda-forge                                                                                                         pandoc                    2.19                 h57928b3_0    conda-forge                                                                                                         pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge                                                                                                         panther                   0.1                       dev_0    <develop>                                                                                                           parso                     0.8.3              pyhd8ed1ab_0    conda-forge                                                                                                         pcre                      8.45                 h0e60522_0    conda-forge                                                                                                         pickleshare               0.7.5                   py_1003    conda-forge                                                                                                         pillow                    9.2.0           py310h767b3fd_0    conda-forge                                                                                                         pip                       22.1.2             pyhd8ed1ab_0    conda-forge                                                                                                         pixman                    0.40.0               h8ffe710_0    conda-forge                                                                                                         pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge                                                                                                         poppler                   22.04.0              h24fffdf_1    conda-forge                                                                                                         poppler-data              0.4.11               hd8ed1ab_0    conda-forge                                                                                                         postgresql                14.5                 h1c22c4f_0    conda-forge                                                                                                         powershell_shortcut       0.0.1                         3                                                                                                                        progress                  1.6                      pypi_0    pypi                                                                                                                proj                      9.0.1                h1cfcee9_1    conda-forge                                                                                                         prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge                                                                                                         prompt-toolkit            3.0.30             pyha770c72_0    conda-forge                                                                                                         psutil                    5.9.1           py310he2412df_0    conda-forge                                                                                                         pthread-stubs             0.4               hcd874cb_1001    conda-forge                                                                                                         pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge                                                                                                         pycparser                 2.21               pyhd8ed1ab_0    conda-forge                                                                                                         pygeoif                   0.7                      pypi_0    pypi                                                                                                                pygeos                    0.12.0          py310h523c7d9_4    conda-forge                                                                                                         pygments                  2.12.0             pyhd8ed1ab_0    conda-forge                                                                                                         pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge                                                                                                         pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge                                                                                                         pyproj                    3.3.1           py310h843b76b_1    conda-forge                                                                                                         pyqt                      5.15.4          py310h8a704f9_0    conda-forge                                                                                                         pyqt5-sip                 12.9.0          py310h8a704f9_0    conda-forge                                                                                                         pyrobuf                   0.9.3           py310h8a704f9_4    conda-forge                                                                                                         pyrosm                    0.6.1           py310h8a704f9_1    conda-forge                                                                                                         pyrsistent                0.18.1          py310he2412df_1    conda-forge                                                                                                         pysocks                   1.7.1           py310h5588dad_5    conda-forge                                                                                                         python                    3.10.5          h9a09f29_0_cpython    conda-forge                                                                                                      python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge                                                                                                         python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge                                                                                                         python-igraph             0.9.11          py310he40ff86_0    conda-forge                                                                                                         python-rapidjson          1.6             py310h8a704f9_0    conda-forge                                                                                                         python_abi                3.10                    2_cp310    conda-forge                                                                                                         pytz                      2022.1             pyhd8ed1ab_0    conda-forge                                                                                                         pywin32                   303             py310he2412df_0    conda-forge                                                                                                         pywinpty                  2.0.7           py310h00ffb61_0    conda-forge                                                                                                         pyzmq                     23.2.0          py310h73ada01_0    conda-forge                                                                                                         qt-main                   5.15.4               h467ea89_2    conda-forge                                                                                                         rasterio                  1.3.0                    pypi_0    pypi                                                                                                                requests                  2.28.1             pyhd8ed1ab_0    conda-forge                                                                                                         rtree                     1.0.0           py310h1cbd46b_1    conda-forge                                                                                                         sciencebasepy             2.0.3                    pypi_0    pypi                                                                                                                sciencedates              1.5.0                    pypi_0    pypi                                                                                                                scikit-learn              1.1.2           py310h3a564e9_0    conda-forge                                                                                                         scipy                     1.8.1           py310h33db832_0    conda-forge                                                                                                         send2trash                1.8.0              pyhd8ed1ab_0    conda-forge                                                                                                         setuptools                63.2.0          py310h5588dad_0    conda-forge                                                                                                         shapely                   1.8.4           py310h523c7d9_0    conda-forge                                                                                                         simplekml                 1.3.6                    pypi_0    pypi                                                                                                                sip                       6.5.1           py310h8a704f9_2    conda-forge                                                                                                         six                       1.16.0             pyhd3eb1b0_1                                                                                                                        snappy                    1.1.9                h82413e6_1    conda-forge                                                                                                         sniffio                   1.2.0           py310h5588dad_3    conda-forge                                                                                                         snuggs                    1.4.7                      py_0    conda-forge                                                                                                         soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge                                                                                                         sqlite                    3.39.2               h8ffe710_1    conda-forge                                                                                                         stack_data                0.3.0              pyhd8ed1ab_0    conda-forge                                                                                                         suitesparse               5.4.0                h5d0cbe0_1    conda-forge                                                                                                         svt-av1                   1.1.0                h0e60522_1    conda-forge                                                                                                         tables                    3.7.0                    pypi_0    pypi                                                                                                                terminado                 0.15.0          py310h5588dad_0    conda-forge                                                                                                         texttable                 1.6.4              pyhd8ed1ab_0    conda-forge                                                                                                         threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge                                                                                                         tiledb                    2.9.5                h5689973_0    conda-forge                                                                                                         tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge                                                                                                         tk                        8.6.12               h8ffe710_0    conda-forge                                                                                                         toml                      0.10.2             pyhd8ed1ab_0    conda-forge                                                                                                         tornado                   6.2             py310he2412df_0    conda-forge                                                                                                         tqdm                      4.64.0                   pypi_0    pypi                                                                                                                traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge                                                                                                         tzdata                    2022a                h191b570_0    conda-forge                                                                                                         ucrt                      10.0.20348.0         h57928b3_0    conda-forge                                                                                                         unicodedata2              14.0.0          py310he2412df_1    conda-forge                                                                                                         urllib3                   1.26.10                  pypi_0    pypi                                                                                                                vc                        14.2                 hb210afc_6    conda-forge                                                                                                         vs2015_runtime            14.29.30037          h902a5da_6    conda-forge                                                                                                         vs2017_win-64             19.16.27033          hb90652a_6    conda-forge                                                                                                         vswhere                   3.0.3                h57928b3_0    conda-forge                                                                                                         wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge                                                                                                         webencodings              0.5.1                      py_1    conda-forge                                                                                                         websocket-client          1.3.3              pyhd8ed1ab_0    conda-forge                                                                                                         wheel                     0.37.1             pyhd8ed1ab_0    conda-forge                                                                                                         widgetsnbextension        3.6.1              pyha770c72_0    conda-forge                                                                                                         win_inet_pton             1.1.0           py310h5588dad_4    conda-forge                                                                                                         winpty                    0.4.3                         4    conda-forge                                                                                                         wmm2015                   1.0.1                    pypi_0    pypi                                                                                                                x264                      1!161.3030           h8ffe710_1    conda-forge                                                                                                         x265                      3.5                  h2d74725_3    conda-forge                                                                                                         xarray                    2022.3.0                 pypi_0    pypi                                                                                                                xerces-c                  3.2.3                h0e60522_5    conda-forge                                                                                                         xorg-libxau               1.0.9                hcd874cb_0    conda-forge                                                                                                         xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge                                                                                                         xyzservices               2022.6.0           pyhd8ed1ab_0    conda-forge                                                                                                         xz                        5.2.5                h62dcd97_1    conda-forge                                                                                                         zeromq                    4.3.4                h0e60522_1    conda-forge                                                                                                         zipp                      3.8.1              pyhd8ed1ab_0    conda-forge                                                                                                         zlib                      1.2.12               h8ffe710_2    conda-forge                                                                                                         zstd                      1.5.2                h6255e5f_3    conda-forge 
</details>

**Provide a complete minimal reproducible example**

```python

from pyrosm import OSM, get_data
from shapely import geometry
import osmnx as ox

fp = get_data("ohio")
osm = OSM(fp)

ll_lat = 39.6
ur_lat = 39.62
ll_lon = -84.083
ur_lon = -84.063
p1 = geometry.Point(ll_lon,ll_lat)
p2 = geometry.Point(ll_lon,ur_lat)
p3 = geometry.Point(ur_lon,ur_lat)
p4 = geometry.Point(ur_lon,ll_lat)
pointList = [p1, p2, p3, p4, p1]
poly = geometry.Polygon([[p.x, p.y] for p in pointList])

osm = OSM(fp, bounding_box=poly)
drive_net = osm.get_network(network_type="all")
nodes, edges = osm.get_network(network_type="driving", nodes=True)
G = osm.to_graph(nodes, edges, graph_type="networkx")

att_list = ['geometry']
for n1, n2, d in G.edges(data=True):
    for att in att_list:
        d.pop(att, None)

G2 = ox.simplify_graph(G, strict=False)
fig, ax = ox.plot_graph(G2, node_color="r",figsize=(25, 25))
```

**Comment by gboeing** [comment]
Thanks for using OSMnx. Unfortunately, I cannot provide tech support for generating graphs with other packages then using OSMnx functions on them. OSMnx is tested and supported on OSMnx-generated graphs. You may want to ask on StackOverflow if the community has any usage suggestions.
