### ISSUE TITLE
coordinate problems

### ISSUE THREAD

**Issue by tongjiyiming** [gboeing/osmnx#86]
I run the "get_nearest_node" method and always get result different from result I get by using geopandas` spatial index. I doubt if the coordinate axis of x, y are rotated in your library.
Please check!

**Comment by gboeing** [comment]
Hi @tongjiyiming thanks for using OSMnx! To give us enough information to help you, could you fill out all the information in the new issue template? It's hard to guess at the answer without knowing exactly what you did, how you did it, and what versions of packages are in play.

**Comment by kuanb** [comment]
If it helps... I wonder if @tongjiyiming is somehow getting Euclidean distance with Geopandas, just finding the closest point to another, as the crow flies, while OSMnx evaluates the network graph and identifies the closes point _along the network_ and *not* as the crow flies.

**Comment by gboeing** [comment]
Thanks @kuanb. @tongjiyiming also, make sure you are passing in the point as a tuple of (lat, lng) or its projected/geometric equivalent of (y, x) as this is the standard for geographic coordinates (see [ISO 6709](https://en.wikipedia.org/wiki/ISO_6709)). The tuple coordinates order is explicitly mentioned in [the documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils.get_nearest_node).

But, again, this is guesswork... if you fill out the full issue template we'll have enough info to know what you did and how you did it, so we can troubleshoot.

**Comment by gboeing** [comment]
See also #71
