### ISSUE TITLE
Connect OSMNX to a local OSM databasae

### ISSUE THREAD

**Issue by icemagno** [gboeing/osmnx#861]
**Is your feature proposal related to a problem?**
Maybe. 

**A clear and concise description of what the problem is.**
I need to connect OSMNX to my local OpenStreetMap server installed by ```overv/openstreetmap-tile-server``` Docker.
I have a closed network running secret stuff and need to cut off any contact to external world.
So I have my own OSM server and data, updated daily.

**Describe the solution you'd like to propose**
I'd like to use OSMNX in this closed environment, so I need to know if there is any configurations or additional tools I must use.

**A clear and concise description of what you want to change in OSMnx and how you plan to implement it.**
I don't know what to change.

**Describe alternatives you've considered**
There are no alternatives.

**A clear and concise description of any alternative solutions or features you've considered.**

I'm planning to:

1) Install a local Overpass API ( https://hub.docker.com/r/wiktorn/overpass-api )
2) Somehow (plase tell me how) edit https://github.com/gboeing/osmnx/blob/main/osmnx/settings.py to point to my local API in ```overpass_endpoint``` parameter.

I don't know how to do the step 2 because I'm using an already cooked OSMNX Docker container ( exposing this file, maybe? ).

**Additional context**

Seems doing that I'll have another copy of same data. Unfortunatly Overpass don't use PBF or PostGIS... ( AFAIK )

**Comment by gboeing** [comment]
> Somehow (plase tell me how) edit https://github.com/gboeing/osmnx/blob/main/osmnx/settings.py to point to my local API in overpass_endpoint parameter.

Hi. Thanks for using OSMnx. Please ask this usage question on StackOverflow. We reserve this issue tracker for bugs and feature development. Also, see the documentation for details on using the settings module and configuring the endpoint.
