### ISSUE TITLE
Streamline _create_overpass_query method

### ISSUE THREAD

**Issue by derinwalters** [gboeing/osmnx#862]
Hello, first time contributor here

**Is your feature proposal related to a problem?**

Yes. The _create_overpass_query method creates a larger than necessary query string. In it are three main issues that cause a significant amount of redundancy: 1) each tag-value pair is explicitly called one by one, 2) each tag-value is called three times (node, way, relation), and 3) the polygon coordinate string is replicated for every tag-value pair.

**Describe the solution you'd like to propose**

The following changes address the above three deficiencies:
1) multiple values for the same tag should be combined together into a single component, as per Overpass documentation https://dev.overpass-api.de/overpass-doc/en/criteria/per_tag.html
Example: 
way[highway~"^(trunk|primary|secondary|tertiary)$"]

2) The node, way, and relation trifecta can be replaced with the single query statement nwr as per Overpass issue https://github.com/drolbr/Overpass-API/issues/453#issuecomment-378718323

3) The polygon can be globalized and referenced multiple times, rather than explicitly sending the same coordinate sequence for each query component, as per Overpass documentation https://dev.overpass-api.de/overpass-doc/en/criteria/union.html
Example: 
nwr({{bbox}})->.all;
(
  nwr.all[amenity=atm];
  nwr.all[atm=yes];
);

**A clear and concise description of what you want to change in OSMnx and how you plan to implement it.**

Replace the guts of the _create_overpass_query method to take advantage of the above. On an example query of mine the query size shrank from 20,625 bytes to 770 bytes (see attached files pre.txt and post.txt). osmnx lint and unit tests all pass in my forked copy of the repo.

[pre.txt](https://github.com/gboeing/osmnx/files/9437640/pre.txt)
[post.txt](https://github.com/gboeing/osmnx/files/9437641/post.txt)

**Provide a complete minimal working example of code to demonstrate your use case. Add any additional code snippets, context, or screenshots about the feature proposal to demonstrate its importance and feasibility.**

```python
def _create_overpass_query(polygon_coord_str, tags):
    """
    Create an overpass query string based on passed tags.

    Parameters
    ----------
    polygon_coord_str : list
        list of lat lng coordinates
    tags : dict
        dict of tags used for finding elements in the selected area

    Returns
    -------
    query : string
    """
    # create overpass settings string
    overpass_settings = _make_overpass_settings()

    # make sure every value in dict is bool, str, or list of str
    error_msg = "tags must be a dict with values of bool, str, or list of str"
    if not isinstance(tags, dict):  # pragma: no cover
        raise TypeError(error_msg)

    # make sure every value in dict is bool, str, or list of str
    error_msg = "tags must be a dict with values of bool, str, or list of str"
    if not isinstance(tags, dict):  # pragma: no cover
        raise TypeError(error_msg)

    # add node/way/relation query components one at a time
    components = []
    for key, value in tags.items():

        if isinstance(value, bool) and value:
            # if bool (ie, True) just pass the key, no value
            tag_str = f"[{key}]"

        elif isinstance(value, str):
            tag_str = f"[{key}='{value}']"

        elif isinstance(value, list):
            if not all(isinstance(s, str) for s in value):  # pragma: no cover
                raise TypeError(error_msg)

            if len(value) == 1:
                tag_str = f"[{key}='{value[0]}']"
            else:
                tag_str = "[{0}~'^({1})$']".format(key, "|".join(value))

        else:  # pragma: no cover
            raise TypeError(error_msg)

        components.append(f"nwr.all{tag_str};")

    # finalize query and return
    components = "".join(components)
    query = f"{overpass_settings};nwr(poly:'{polygon_coord_str}')->.all;({components});(._;>;);out;"

    return query
```

**Comment by anditi-lidar** [comment]
Hello, for this function, is there any way to request all OSM data in the given poly?

I am looking for a way to just ask for all OSM data in a given polygon in the current release version, but the `tags` seems mandatory, and if an empty dict then there is no error, but no data is returned.

**Comment by nickodell** [comment]
I wrote a similar patch, in issue https://github.com/gboeing/osmnx/issues/755, but unfortunately I didn't have time to fully test it. The OSMnx author was concerned that the query might not be a 1-to-1 match:

> I'd be open to reviewing a PR from you for this. Should also demonstrate that you're getting a perfect match between the results from the current method vs the new one you're proposing, across several test queries.

He's likely going to have a similar concern about this one. Could you provide some testing that you get the same results across old and new queries?

**Comment by derinwalters** [comment]
@anditi-lidar I don't see why it wouldn't be possible to allow an empty tags dictionary to indicate all OSM data be retrieved. I'll take a look.

@nickodell Ah, I didn't see that as I only looked at open issues prior to opening this one. I thought your brief analysis was well done. I would be willing to do a side-by-side comparison of the revised query in the context of my own validation dataset of about 30k POI in USA and Japan. IMO, using 'nwr' instead of the three separate node/way/relation query is a no-brainer and shouldn't require as much validation as the area and tag-value compression.

**Comment by nickodell** [comment]
@derinwalters

That would be great.

**Comment by gboeing** [comment]
@derinwalters thanks for suggesting this. And thanks @nickodell for your comments. Yes I'm open to a reviewing a PR. The key thing, as Nick mentioned, will be comprehensively demonstrating there is no change in query results from the old way to the new way. For the end user we must guarantee consistent deterministic results between versions. Let me know if you're willing to take this enhancement on. I'm grateful for your proposal.

**Comment by gboeing** [comment]
Also, please note that I'm on international travel with limited connectivity, so please forgive sporadically long response times.

**Comment by derinwalters** [comment]
@gboeing yessir, I'll take a crack at it

**Comment by gboeing** [comment]
One thought that occurred to me and is worth documenting here: this change will cause cache invalidation upon release. This seems acceptable but worth noting.

**Comment by derinwalters** [comment]
Alrighty, I ran two sets of queries covering 4500 km^2 around Tokyo and San Francisco with 1) osmnx 1.2.2 and 2) the proposed change to _create_overpass_query above. Each returned 463488 elements (45MB) and the diff between the raw json responses was clean. 

Query string byte size down from 1MB to 41KB
Query-to-response time delta of downloader.py{overpass_request} down from 5711 seconds to 4450 seconds. Yes, I know this also includes delay due to waiting on Overpass slot availability, but seems like a reasonable enough proxy.

Raw queries and json responses, along with a diff of the responses, attached as Archive.zip
[Archive.zip](https://github.com/gboeing/osmnx/files/9533299/Archive.zip)

Many of the queries looked like this:
`out:json][timeout:1800];nwr(poly:'36.856085 -118.345039 36.947997 -118.345039 36.947997 -118.459417 36.856085 -118.459417 36.856085 -118.345039')->.all;(nwr.all[aerialway~'^(cable_car|chair_lift|gondola|mixed_lift|station)$'];nwr.all[amenity~'^(cafe|community_centre|drinking_water|place_of_worship|public_bath|ranger_station|restaurant|shelter|shower|toilets|vending_machine|water_point|watering_place)$'];nwr.all[ford='yes'];nwr.all[geological~'^(volcanic_caldera_rim|volcanic_vent)$'];nwr.all[highway~'^(bus_stop|rest_area|services|trailhead)$'];nwr.all[leisure='park'];nwr.all[mountain_pass='yes'];nwr.all[natural~'^(beach|cave_entrance|fumarole|geyser|hot_spring|peak|saddle|spring|volcano|water|wetland)$'];nwr.all[public_transport='station'];nwr.all[shop='convenience'];nwr.all[tourism~'^(alpine_hut|camp_site|guest_house|hostel|hotel|information|viewpoint|wilderness_hut)$'];nwr.all[water~'^(lagoon|lake|pond|reservoir|river)$'];nwr.all[waterway~'^(dam|river|stream|waterfall)$'];);(._;>;);out;`

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/derinw/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/derinw/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



  | OSMNX 1.2.2 |   |   |   | PROPOSED |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
MGRS | Qbytes | Qseconds | Relems | Rbytes | Qbytes | Qseconds | Relems | Rbytes
10SEG94 | 27026 | 29 | 20546 | 2005616 | 1003 | 23 | 20546 | 2005616
10SEG95 | 27026 | 17 | 10986 | 1099060 | 1003 | 137 | 10986 | 1099060
10SFG04 | 27026 | 122 | 10947 | 989915 | 1003 | 125 | 10947 | 989915
10SFG05 | 27026 | 100 | 10448 | 934994 | 1003 | 8 | 10448 | 934994
10SFG15 | 27026 | 11 | 12719 | 1137548 | 1003 | 8 | 12719 | 1137548
10SFG16 | 27026 | 14 | 12150 | 1087687 | 1003 | 13 | 12150 | 1087687
11SLA57 | 27026 | 10 | 6999 | 640677 | 1003 | 5 | 6999 | 640677
11SLA66 | 27026 | 238 | 6144 | 571585 | 1003 | 97 | 6144 | 571585
11SLA67 | 27026 | 110 | 8175 | 758551 | 1003 | 7 | 8175 | 758551
11SLA68 | 27026 | 9 | 9995 | 937554 | 1003 | 20 | 9995 | 937554
11SLA76 | 27026 | 10 | 15541 | 1500183 | 1003 | 25 | 15541 | 1500183
11SLA77 | 27026 | 108 | 10547 | 976668 | 1003 | 6 | 10547 | 976668
11SLA78 | 27026 | 110 | 7993 | 754440 | 1003 | 20 | 7993 | 754440
54SUD78 | 26171 | 121 | 857 | 93288 | 998 | 86 | 857 | 93288
54SUD79 | 26171 | 259 | 4784 | 508375 | 998 | 8 | 4784 | 508375
54SUD89 | 26171 | 124 | 2385 | 244924 | 998 | 87 | 2385 | 244924
54SUE10 | 26171 | 352 | 12292 | 1207789 | 998 | 14 | 12292 | 1207789
54SUE11 | 26171 | 213 | 11617 | 1097582 | 998 | 242 | 11617 | 1097582
54SUE20 | 26171 | 134 | 7456 | 776832 | 998 | 19 | 7456 | 776832
54SUE21 | 26171 | 353 | 6540 | 648404 | 998 | 124 | 6540 | 648404
54SUE22 | 26171 | 421 | 8416 | 812698 | 998 | 5 | 8416 | 812698
54SUE26 | 26171 | 211 | 9734 | 914688 | 998 | 128 | 9734 | 914688
54SUE27 | 26171 | 14 | 5503 | 510248 | 998 | 5 | 5503 | 510248
54SUE28 | 26171 | 17 | 14684 | 1425217 | 998 | 9 | 14684 | 1425217
54SUE32 | 26171 | 152 | 10402 | 1017586 | 998 | 132 | 10402 | 1017586
54SUE33 | 26171 | 17 | 15669 | 1559011 | 998 | 8 | 15669 | 1559011
54SUE34 | 26171 | 23 | 24422 | 2431862 | 998 | 8 | 24422 | 2431862
54SUE35 | 26171 | 131 | 9365 | 880887 | 998 | 236 | 9365 | 880887
54SUE36 | 26171 | 214 | 16388 | 1519745 | 998 | 12 | 16388 | 1519745
54SUE37 | 26171 | 15 | 7928 | 852064 | 998 | 123 | 7928 | 852064
54SUE38 | 26171 | 421 | 7491 | 721721 | 998 | 73 | 7491 | 721721
54SUE47 | 26171 | 45 | 11690 | 1133578 | 998 | 53 | 11690 | 1133578
54SUE60 | 26171 | 268 | 8732 | 938020 | 998 | 153 | 8732 | 938020
54SUE61 | 10121 | 13 | 6271 | 568879 | 556 | 101 | 6271 | 568879
54SUE70 | 26171 | 131 | 13544 | 1417304 | 998 | 15 | 13544 | 1417304
54SUE71 | 26171 | 20 | 15831 | 1708717 | 998 | 217 | 15831 | 1708717
54SUE72 | 10121 | 82 | 5815 | 552424 | 556 | 145 | 5815 | 552424
54SUE73 | 10121 | 42 | 5537 | 509953 | 556 | 447 | 5537 | 509953
54SUE80 | 26171 | 16 | 2789 | 296418 | 998 | 9 | 2789 | 296418
54SUE83 | 10121 | 148 | 9561 | 890540 | 556 | 284 | 9561 | 890540
54SUE84 | 10121 | 288 | 11356 | 1110164 | 556 | 290 | 11356 | 1110164
54SUE85 | 10121 | 156 | 9591 | 956823 | 556 | 152 | 9591 | 956823
54SUE94 | 26171 | 264 | 26821 | 2984093 | 998 | 274 | 26821 | 2984093
54SUE95 | 10121 | 148 | 10323 | 983241 | 556 | 17 | 10323 | 983241
54SUE96 | 10121 | 12 | 6504 | 603358 | 556 | 480 | 6504 | 603358
TOTAL | 1060410 | 5711 | 463488 | 45270911 | 41439 | 4450 | 463488 | 45270911



</body>

</html>

**Comment by derinwalters** [comment]
@anditi-lidar I'm going to pass on making the change you mentioned for "tagless" queries, because it would create some potentially confusing behavior with the geometries.py{_create_gdf} method that removes elements without any associated tags.

```python
                # add elements that are not nodes and that are without tags or
                # with empty tags to the untagged_element_ids set (untagged
                # nodes are not added to the geometries dict at all)
                if (element["type"] != "node") and (
                    ("tags" not in element) or (not element["tags"])
                ):
                    untagged_element_ids.add(unique_id)
```

**Comment by anditi-lidar** [comment]
> @anditi-lidar I'm going to pass on making the change you mentioned for "tagless" queries, because it would create some potentially confusing behavior with the geometries.py{_create_gdf} method that removes elements without any associated tags.

Yeah no worries. I was pushing my luck anyway trying to piggyback a feature request onto this issue. ;-)

**Comment by gboeing** [comment]
Thanks @derinwalters this is looking good. Would you like to open a PR? We can discuss a couple more tests for thoroughness there.

**Comment by derinwalters** [comment]
@gboeing PR submitted
