### ISSUE TITLE
Rasterio fixed the sampling bug, patch can be reverted

### ISSUE THREAD

**Issue by nickodell** [gboeing/osmnx#863]
In PR #842, while fixing CI, I ran into an issue with rasterio 1.3.0: it checks the truthiness of each value you pass to raster.sample(), meaning you cannot use numpy arrays anymore. I added commit 4ba2b1dbb3e15ab12f7eb5a807e481844948542f to fix this.

Rasterio fixed this. In PR https://github.com/rasterio/rasterio/pull/2547, which was included in rasterio 1.3.1, rasterio can once again use numpy arrays in raster.sample().

I've tested the fix, and it does work. The workaround is no longer required.

**Comment by gboeing** [comment]
Thank you @nickodell. Would you be interested in opening a PR for this?

**Comment by nickodell** [comment]
Sure. I've opened PR #866.
