### ISSUE TITLE
project_graph creates and adds unsimplified edge geometries if already simplified

### ISSUE THREAD

**Issue by pmlpm1986** [gboeing/osmnx#864]
**Is your feature proposal related to a problem?**

Yes. The method project_graph creates a projected graph with edge geometries if the original graph has already been simplified. In this case, the geometries added/converted include those for simplified edges as well as those for unsimplified edges, i.e., those that did not require simplification and do not have a geometry object. As a result, geometries that did not previously exist in the original graph are created and added to the projected graph, arguably even if they are not needed.

**Describe the solution you'd like to propose**

In order to make this method more flexible, there should be an input parameter (e.g., create_unsimplified_edge_geometries) specifying if all edges should have projected geometry objects or only simplified ones. As it stands, only the former is possible, which could be left as the default:

```
def project_graph(G, to_crs=None, create_unsimplified_edge_geometries=True):

    (...)

    # STEP 2: PROJECT THE EDGES
    if "simplified" in G.graph and G.graph["simplified"]:
        # if graph has previously been simplified, project the edge geometries
        gdf_edges = utils_graph.graph_to_gdfs(G, nodes=False, fill_edge_geometry=create_unsimplified_edge_geometries)
        gdf_edges_proj = project_gdf(gdf_edges, to_crs=to_crs)
    else:
        # if not, you don't have to project these edges because the nodes
        # contain all the spatial data in the graph (unsimplified edges have
        # no geometry attributes)
        gdf_edges_proj = utils_graph.graph_to_gdfs(G, nodes=False, fill_edge_geometry=False).drop(
            columns=["geometry"]
        )
   
    (...)

    return G_proj
```

**Describe alternatives you've considered**

I have considered deleting the new geometries but that is not an elegant solution.

**Additional context**

The aforementioned issue can be reproduced using the code below:

```
import networkx as nx
from osmnx.projection import project_graph

mygraph = nx.MultiDiGraph()

mygraph.graph['crs'] = 'epsg:4326'

mygraph.graph['simplified'] = True

# define the nodes

list_nodes = [
	(0, {'x':0,'y':0}),
	(1, {'x':1,'y':0})
	]

mygraph.add_nodes_from(list_nodes)

mygraph.add_edge(
	u_for_edge=0,
	v_for_edge=1,
	key=0,
	length=1,
	geometry=LineString(
	    [(0, 0), 
	     (1, 0)]
	    )
	)

mygraph.add_edge(
	u_for_edge=1,
	v_for_edge=0,
	key=0,
	length=1,
	)
	
assert 'geometry' in mygraph.edges[(0,1,0)]
assert 'geometry' not in mygraph.edges[(1,0,0)]

my_projected_graph = project_graph(mygraph)

assert 'geometry' in my_projected_graph.edges[(0,1,0)]
assert 'geometry' in my_projected_graph.edges[(1,0,0)] # geometry exists in (1,0,0) too
```

**Comment by gboeing** [comment]
Thanks for this suggestion. The "principle of least astonishment" here suggests to me that OSMnx should not generate/add edge geometry attributes unless the user tells it to. And projecting the graph does not constitute the user telling it to. I cannot remember the design decision years ago that resulted in `fill_edge_geometry=True` in the `project_graph` function's code. But I'm inclined to set it `False` without adding another parameter to `project_graph`. As it is, the user already has the ability to fill in missing edge geometries whenever they want to.

**Comment by gboeing** [comment]
See #865 for proposal.

**Comment by pmlpm1986** [comment]
I have. That should do it.
