### ISSUE TITLE
Discrepancy in the unit of edges in the graph

### ISSUE THREAD

**Issue by JaishreeJanu** [gboeing/osmnx#867]
**Problem description**
  - I used ```basic_stats()``` function to get the properties of the graph.
  - I expected values, specially ```edge_density_km``` values to look sane/practical
  - This is how the values look like:
  
![image](https://user-images.githubusercontent.com/21203830/189890306-fc71cc0d-fa8a-4e65-93b7-4a6ec51b2e3b.png)

**Problem description**:
There is a discrepancy in the unit of ```edge_density_km```. While calculation of ```edge_density_km```, osmnx uses ```edge_length_total``` which is just the sum of edges in the graph (Note the edges in the graph from osmnx are in meters) and expects area of the graph in m^2 (It converts area to km^2). It then divides ```edge_length_total``` (in ```meters```) by area in km^2. Hence, the values of ```edge_density_km``` are not correct or there is discrepancy in units of edges. 
To remove the discrepancy, I dividing ```edge_density_km``` received from ```basic_stats``` by 1000 and then the values look practical. 

**Environment information**
  - OS: Linux
  - Python 3.10
  - osmnx 1.2.2
  - Attaching the requirements.tx file. 
[requirements.txt](https://github.com/gboeing/osmnx/files/9556643/requirements.txt)

**A complete minimal reproducible example**

```python
import osmnx as ox
import pandas as pd
from countryinfo import CountryInfo
ox.config(use_cache=True, log_console=True)

test_list = ['CZECH REPUBLIC', 'UK']

hi_tr_country_stats = []
unit_convert = 1e+6

for country in test_list:
    ## Load the graphml from directory
    ## The graphml of the countries have been saved to this directory
    path = 'EU/HIGHWAY/'
    graph = ox.load_graphml(path+country+"/highway_graph.graphml")
    if graph.graph['simplified'] == False:
        graph = ox.simplify_graph(graph)
     
    country_area = CountryInfo(country).area() * unit_convert
    
    ## Find the network stats
    hi_tr_country_stats.append(ox.stats.basic_stats(graph, country_area))

## Creating dataframe and rearranging columns

hi_tr_country_stats_df = pd.DataFrame(hi_tr_country_stats)

hi_tr_country_stats_df['country'] = test_list

column_names = list(hi_tr_country_stats_df.columns)
column_names.insert(0, column_names.pop())
hi_tr_country_stats_df = hi_tr_country_stats_df.reindex(columns=column_names)

## Select required features
features = ['country', 'edge_length_total', 'intersection_density_km', 'edge_density_km']
hi_tr_country_stats_df = hi_tr_country_stats_df[features]

hi_tr_country_stats_df.head()
## This dataframe looks like the snapshot shared above.

```
**Attaching graphs** for UK and Czech
[highway_graph_czech_uk.zip](https://github.com/gboeing/osmnx/files/9557030/highway_graph_czech_uk.zip)

**Comment by gboeing** [comment]
There's a lot going on in your snippet, and I don't see where you originally created your graphs, but here's a minimal reproducible example and it appears that the numbers are all fine:

```python
import osmnx as ox
G = ox.graph_from_place("Piedmont, CA, USA", network_type="drive")

area_km = 4.4  # the city's area is approx 4.4 km^2
area_m = area_km * 1000 * 1000  # convert km^2 to m^2

stats = ox.basic_stats(G, area=area_m)
stats["edge_density_km"]  # returns 25702
```

**Comment by JaishreeJanu** [comment]
Yes exactly. Now, my question is how do you interpret this value of ```"edge_density_km"``` ? It is (```25,702 meters``` of ```edge_length``` per ```sq km```), right? My suggestion is that it would be nice to convert unit of ```edge_length``` from ```meters``` to ```kms``` such that we have final ```"edge_density_km"``` in total ```edge_length``` in ```kms``` per ```sq km```.

**Comment by gboeing** [comment]
> my question is how do you interpret this value of "edge_density_km"? 

The [docs](https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.stats) explain how to interpret it: the graph's `edge_length_total` (by default, [in meters](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.stats.edge_length_total)) per square kilometer.

> My suggestion is that it would be nice to convert unit of edge_length from meters to kms

You may convert these units, and any others returned by `basic_stats` to any other units you prefer with simple division or multiplication. OSMnx returns these results in the same consistent units it uses elsewhere (e.g., graph edge lengths are by default meters throughout the package).
