### ISSUE TITLE
dead kernel on ox.project_graph

### ISSUE THREAD

**Issue by temporalista** [gboeing/osmnx#87]
If you're having trouble with OSMnx, first search the previously opened issues to see if the problem has already been noted. If not, fill in the template below. You can delete any sections that don't apply.

#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Every time I run ox.project_graph I get a dead kernel. For example, following the jupyter notebook from the examples (01-overview-osmnx.ipynb) the kernel fails at cell 4: 
`G1 = ox.project_graph(G1)`
  
#### What operating system, architecture, Python version, and OSMnx version are you using?
Mac OSX Sierra
Python 3.6.2
OSMnx 0.5.3

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>
#
appnope                   0.1.0                    py36_0    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
branca                    0.2.0                    py36_0    conda-forge
certifi                   2016.2.28                py36_0  
click                     6.7                      py36_0    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
curl                      7.54.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
descartes                 1.1.0                    py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.1                         0    conda-forge
fiona                     1.7.7               np112py36_0    conda-forge
folium                    0.3.0                    py36_0    conda-forge
freetype                  2.7                           1    conda-forge
freexl                    1.0.2                         2    conda-forge
gdal                      2.2.1               np112py36_0    conda-forge
geopandas                 0.3.0                    py36_0    conda-forge
geopy                     1.11.0                   py36_0    conda-forge
geos                      3.5.1                         1    conda-forge
giflib                    5.1.4                         0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.18                        0    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
icu                       58.1                          1    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12.1                        0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
kealib                    1.4.7                         2    conda-forge
krb5                      1.14.2                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libgdal                   2.2.1                         0    conda-forge
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.14                          4    conda-forge
libnetcdf                 4.4.1.1                       5    conda-forge
libpng                    1.6.28                        0    conda-forge
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libspatialindex           1.8.5                         1    conda-forge
libspatialite             4.3.0a                       15    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.4                         4    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2                    py36_2    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
mkl                       2017.0.3                      0  
munch                     2.2.0                    py36_0    conda-forge
nbconvert                 5.2.1                    py36_1    conda-forge
nbformat                  4.3.0                    py36_0    conda-forge
networkx                  1.11                     py36_0    conda-forge
notebook                  5.0.0                    py36_0    conda-forge
numpy                     1.12.1                   py36_0  
openjpeg                  2.1.2                         2    conda-forge
openssl                   1.0.2l                        0  
osmnx                     0.5.3                    py36_0    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1                    py36_1  
proj4                     4.9.3                         4    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psycopg2                  2.7.3                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysal                     1.13.0                   py36_0    conda-forge
python                    3.6.2                         0  
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                h9e3eb04_4    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
readline                  6.2                           2  
requests                  2.13.0                   py36_0    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
scipy                     0.19.1              np112py36_0  
setuptools                36.4.0                   py36_0  
shapely                   1.6.1                    py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.13.0                        0  
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.5.18                        0  
tornado                   4.5.1                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
vincent                   0.4.4                    py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.29.0                   py36_0  
xerces-c                  3.1.4                         3    conda-forge
xz                        5.2.3                         0  
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0  

</details>

#### Code that reproduces the issue

```python
# define a bounding box in San Francisco
north, south, east, west = 37.79, 37.78, -122.41, -122.43

# create network from that bounding box
G1 = ox.graph_from_bbox(north, south, east, west, network_type='drive_service')
G1 = ox.project_graph(G1)
fig, ax = ox.plot_graph(G1)
```
console out:
graph_from_bbox() returning graph with 259 nodes and 514 edges
Created a GeoDataFrame from graph in 0.04 seconds
Projected the GeoDataFrame "unnamed_nodes" to UTM-10 in 0.02 seconds
[I 09:41:44.878 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel ee4dfe44-2313-4e79-b9bf-dff26ca9ea05 restarted

**Comment by gboeing** [comment]
Strange. I don't own a Mac to test this on, but I'm not able to reproduce it on my Linux or Windows machines. I just created a new virtual environment, then installed Jupyter, OSMnx and all dependencies up to their latest versions. Ran your snippet no problem. Can you try this in a new virtual environment?

Lastly, have you seen https://github.com/jupyter/notebook/issues/990

**Comment by kuanb** [comment]
FWIW, Just ran the query and re-projection methods locally (not in a Jupyter notebook) on macOS Sierra 10.12.5, with Py 3.6 and it ran smoothly. Looking at the console logs, I wonder if it failed during the plot operation. I did not run that step from the command line prompt, but am aware that there's some issues with Matplotlib (generally, but also specifically with playing well with macOS).
