### ISSUE TITLE
Why does osmnx.distance.nearest_nodes return same nodes?

### ISSUE THREAD

**Issue by Dr-AlaaKhamis** [gboeing/osmnx#873]
**Read these instructions carefully**

Please don't use the issue tracker to ask "how-to" or usage questions. If asked here, they will be closed automatically. Instead, ask "how-to" and usage questions on [StackOverflow](https://stackoverflow.com/).

Bug reports are for reporting a bug you have found in OSMnx's codebase. Your issue will be closed automatically if you don't provide the requested information that we need in order to help you. Before you proceed, review the contributing guidelines in this repo's CONTRIBUTING.md file. If you installed OSMnx via conda and are experiencing installation problems, please open an issue at its [feedstock](https://github.com/conda-forge/osmnx-feedstock/issues). If you've found a problem in OSMnx itself, first search the open/closed issues and StackOverflow to see if the problem has already been noted. If it hasn't, fill in the bug reporting template below. We need this information to assist you:

**Problem description**
  - What did you do?
  - What did you expect to happen?
  - And what actually happened instead?

**Environment information**
  - What operating system are you using?
  - What Python version are you using?
  - What OSMnx version are you using?
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
# paste the output of your Python packages/versions here between these two "details" tags

</details>

**Provide a complete minimal reproducible example**

Your example code snippet here must be *minimal* so it doesn't contain extraneous code unrelated to your specific problem and it must be *complete* so we can independently run it from top to bottom by copying/pasting it into a Python interpreter. That means all imports and all variables must be defined. If you're unsure how to create a good reproducible example, read [this guide](https://stackoverflow.com/help/minimal-reproducible-example). Do not post a screenshot of your code or error message: provide it as text.

```python
# your code goes here

```

**Comment by Dr-AlaaKhamis** [comment]
In the following code, why does "nearest_nodes" returns same nodes: 1422659162 1422659162 1422659162 ? The previous deprecated "get_nearest_node" was returning different values.

origin = (43.8387129,-79.31549783)
dist_1 = (43.8559083,-79.3040332)
dist_2 = (43.8319896,-79.4621784)

bbox = [43.81, 43.87, -79.29, -79.48]
G = osmnx.graph_from_bbox(*bbox, network_type='drive_service')

originId = osmnx.distance.nearest_nodes(G, origin[0], origin[1])
distId1 = osmnx.distance.nearest_nodes(G, dist_1[0], dist_1[1])
distId2 = osmnx.distance.nearest_nodes(G, dist_2[0], dist_2[1])
print(originId,distId1,distId2)

**Comment by gboeing** [comment]
Cross posted and answered at https://stackoverflow.com/a/74033343/7321942
