### ISSUE TITLE
Request way to create a graph from one or more OSM route relation IDs

### ISSUE THREAD

**Issue by kevinp2** [gboeing/osmnx#874]
**Is your feature proposal related to a problem?**

I have a project to identify rural trunk roads and highways in OSM that are missing key pieces of information such as speed limits that are useful for route planning.  Once the ways with missing information are identified, they are usually fixed by a volunteer road trip to determine the speed limits by recording with Mapillary or simply manual editing.

**Describe the solution you'd like to propose**

I found this StackOverflow thread on how to download the trunk highway graph for an entire state or country:
https://stackoverflow.com/questions/64672001/filtering-on-relation

But this is slow and we only need a fraction of the information for the volunteer road trip.

If OSMnx can implement a filter to create a graph from one or more route relations, that would be very helpful.  Here is an example of US Hwy 6 in Utah which has member ways that lack speed limits: Relation: US 6 (UT) (2308411)
https://www.openstreetmap.org/relation/2308411 

And here is a member way that at the current moment lacks a speed limit: Way: US 6 (117054955)
https://www.openstreetmap.org/way/117054955

Upon obtaining this information, I can programmatically identify the ways that need speed limits and construct a GPX file to guide the road trip to each waypoint.  Prior to the trip, I could also add the fixme tag to the ways so that other volunteers passing through might fix it.

**Describe alternatives you've considered**

A brute force approach to download every trunk highway in the entire state and then attempt to identify the ways of US Highway 6.

**Additional context**

I found osmnx only yesterday and so have no code to offer :-)

**Comment by gboeing** [comment]
OSMnx filters on way tags, not on relations. This won't change (at least as far as I can foresee).

However, you can filter with way tags. For example, the way you linked to above has a `ref` tag with value "US 6". If that is consistent, you could use it in a [custom_filter](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.graph.graph_from_place) argument.
