### ISSUE TITLE
Simplification.simplify_graph method

### ISSUE THREAD

**Issue by reporkey** [gboeing/osmnx#875]
Thanks gboeing for the distribution on osmnx, it's really handy to preprocess road network. During my usage, I found an issue but not sure if this is common.

#### Simplification.simplify_graph Line.268-284

I read node and edge shapefile using Geopandas, and then convert them from GeoDataFrames to MultiDiGraph by `osmnx.utils_graph.graph_from_gdfs`. In my code, geometry is one of the keys in `path_attributes`, so when it gets to Line.279, it raise `TypeError: unhashable type: 'LineString'`. This also happens for some other unhashable type attributes, like `list`.

Here's my solution.
```python
if attr == 'geometry':
    continue
elif len(path_attributes[attr]) > 0 and isinstance(path_attributes[attr][0], list):
    # flat thhe list of list, then consolidate them to unique values
    path_attributes[attr] = [item for sublist in path_attributes[attr] for item in sublist]
    path_attributes[attr] = list(set(path_attributes[attr]))
```

#### Here is some other suggestions.
- Creating geometry from its path may loss some geo info as show in images below. Giving an option to concat existing geometry would be aweson. This may related to double simplify, I'm not sure.
  ```python
  if attr == 'geometry':
      multi_line = geometry.MultiLineString(path_attributes[attr])
      path_attributes[attr] = ops.linemerge(multi_line)
  ```
  <img width="121" alt="image" src="https://user-images.githubusercontent.com/26684461/195807389-027e996f-1c87-447b-88d6-3ca4118a0c94.png">
  <img width="128" alt="image" src="https://user-images.githubusercontent.com/26684461/195807439-e35b9e98-30df-4b9d-90de-9145b959488f.png">

**Comment by gboeing** [comment]
Thanks for using OSMnx. Please provide a complete minimal reproducible code snippet for us to reproduce and troubleshoot your issue. Per the contributing guidelines, issues without this must be closed as we're unable to troubleshoot them.
