### ISSUE TITLE
Error: Attempt to write non-point (POLYGON) geometry to point shapefile

### ISSUE THREAD

**Issue by DerrickJuda** [gboeing/osmnx#877]
**Problem description**
After downloading geometries using geometries_from_place, I tried exporting building footprints to shapefile but failed due to non-point (POLYGON) geometries, but manged to plot the footprints. Please see the code and error messages below. Would be grateful if there's a solution for this.

I'm using Win 10 21H2 64-bit, Python 3.10.7 64-bit, OSMnx 1.2.2
Below are all the installed packages.

<details>
Package            Version
------------------ -----------
asttokens          2.0.8
attrs              22.1.0
backcall           0.2.0
basemap            1.3.4
basemap-data       1.3.2
beautifulsoup4     4.11.1
certifi            2022.9.24
charset-normalizer 2.1.1
click              8.1.3
click-plugins      1.1.1
cligj              0.7.2
colorama           0.4.5
ConfigArgParse     1.5.3
contourpy          1.0.5
cycler             0.11.0
debugpy            1.6.3
decorator          5.1.1
entrypoints        0.4
executing          1.1.1
Fiona              1.8.21
fonttools          4.37.4
GDAL               3.4.3
geographiclib      1.52
geopandas          0.11.1
geopy              2.2.0
idna               3.4
ipykernel          6.16.0
ipython            8.5.0
jedi               0.18.1
joblib             1.2.0
JPype1             1.4.0
jupyter_client     7.4.2
jupyter-core       4.11.1
kiwisolver         1.4.4
matplotlib         3.5.3
matplotlib-inline  0.1.6
munch              2.5.0
nest-asyncio       1.5.6
networkx           2.8.7
numpy              1.23.3
osmnx              1.2.2
packaging          21.3
pandas             1.5.0
parso              0.8.3
pickleshare        0.7.5
Pillow             9.2.0
pip                22.2.2
plotly             5.10.0
prompt-toolkit     3.0.31
psutil             5.9.2
pure-eval          0.2.2
Pygments           2.13.0
pyogrio            0.4.2
pyparsing          3.0.9
pyproj             3.3.1
pyshp              2.3.1
python-dateutil    2.8.2
pytz               2022.4
pywin32            304
pyzmq              24.0.1
r5py               0.0.4
requests           2.28.1
Rtree              1.0.1
scikit-learn       1.1.2
scipy              1.9.2
setuptools         63.2.0
Shapely            1.8.4
six                1.16.0
soupsieve          2.3.2.post1
stack-data         0.5.1
tenacity           8.1.0
threadpoolctl      3.1.0
tornado            6.2
traitlets          5.4.0
urllib3            1.26.12
wcwidth            0.2.5

</details>

```python
place1= 'Piedmont, California, USA'
gdf = ox.geometries_from_place(place1, tags={'building':True})
gdf_proj = ox.project_gdf(gdf)
gdf.head()

gdf.drop(labels='nodes', axis=1).to_file('/Users/derri/Downloads/Planetizen Courses/Python Programming for Data Visualization and Analysis/Ch4/input_data/footprints')

fig, ax = ox.plot_footprints(gdf_proj)

```

Here is the error code

```python
C:\Users\derri\AppData\Local\Temp\ipykernel_12912\1222792032.py:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  gdf_proj.drop(labels='nodes', axis=1).to_file('/Users/derri/Downloads/Planetizen Courses/Python Programming for Data Visualization and Analysis/Ch4/input_data/footprints')
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?119bdac4-4ef4-4eb0-a477-ccb961e87efd)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [104], line 2
      1 # save as a shapefile
----> 2 gdf_proj.drop(labels='nodes', axis=1).to_file('/Users/derri/Downloads/Planetizen Courses/Python Programming for Data Visualization and Analysis/Ch4/input_data/footprints')

File ~\AppData\Roaming\Python\Python310\site-packages\geopandas\geodataframe.py:1216, in GeoDataFrame.to_file(self, filename, driver, schema, index, **kwargs)
   1133 """Write the ``GeoDataFrame`` to a file.
   1134 
   1135 By default, an ESRI shapefile is written, but any OGR data source
   (...)
   1212 >>> gdf.to_file('dataframe.shp', mode="a")  # doctest: +SKIP
   1213 """
   1214 from geopandas.io.file import _to_file
-> 1216 _to_file(self, filename, driver, schema, index, **kwargs)

File ~\AppData\Roaming\Python\Python310\site-packages\geopandas\io\file.py:525, in _to_file(df, filename, driver, schema, index, mode, crs, engine, **kwargs)
    518     warnings.warn(
    519         "Column names longer than 10 characters will be truncated when saved to "
    520         "ESRI Shapefile.",
    521         stacklevel=3,
    522     )
    524 if engine == "fiona":
--> 525     _to_file_fiona(df, filename, driver, schema, crs, mode, **kwargs)
    526 elif engine == "pyogrio":
...
File fiona\ogrext.pyx:1295, in fiona.ogrext.WritingSession.writerecs()

RuntimeError: GDAL Error: Attempt to write non-point (POLYGON) geometry to point shapefile. 
 
 Failed to write record: {'id': '1', 'type': 'Feature', 'properties': {'element_type': 'way', 'osmid': 28861558, 'ele': None, 'gnis:county_id': None, 'gnis:created': None, 'gnis:feature_id': None, 'gnis:state_id': None, 'name': None, 'wikidata': None, 'addr:city': 'Piedmont', 'addr:housenumber': '740', 'addr:postcode': '94611', 'addr:street': 'Magnolia Avenue', 'building': 'yes', 'area': None, 'historic': None, 'opening_hours': None, 'phone': None, 'shop': None, 'website': None, 'amenity': None, 'atm': None, 'brand': None, 'brand:wikidata': None, 'brand:wikipedia': None, 'building:levels': None, 'man_made': None, 'operator': None, 'addr:state': None, 'opening_hours:covid19': None, 'second_hand': None, 'house': None, 'religion': None, 'tourism': None, 'denomination': None, 'gnis:county_name': None, 'gnis:import_uuid': None, 'gnis:reviewed': None, 'source': None, 'ways': None, 'type': None}, 'geometry': {'type': 'Polygon', 'coordinates': (((567339.4173500717, 4186423.4307648363), (567364.3392875884, 4186448.6560805556), (567380.0749203343, 4186432.7403903687), (567360.7044486271, 4186413.1750119254), (567362.2654284141, 4186411.723145667), (567375.2745379251, 4186411.6854848997), (567375.307598546, 4186415.169857603), (567410.2754557601, 4186415.29001871), (567410.3435983768, 4186393.021173295), (567370.915875713, 4186392.5759790074), (567339.4173500717, 4186423.4307648363)),)}}

```

**Comment by gboeing** [comment]
Thanks for using OSMnx. This isn't an OSMnx bug, as your problem line of code is using GeoPandas to write a GeoDataFrame to disk as a ShapeFile via GDAL. You could ask the GeoPandas maintainers why this is happening, but in general ShapeFile is an outdated and limited format. Consider writing to a GeoPackage instead. The relevant documentation is here: https://geopandas.org/en/stable/docs/user_guide/io.html

The OSMnx [usage examples](https://github.com/gboeing/osmnx-examples/blob/main/notebooks/05-save-load-networks.ipynb) contain more demonstrations of writing to disk (including geometries, like in your case). For further usage questions, per the contributing guidelines, please ask on StackOverflow to reserve this issue tracker for bug reporting and feature development.
