### ISSUE TITLE
ox.consolidate_intersections Error when saving and reloading

### ISSUE THREAD

**Issue by Spockkk0225** [gboeing/osmnx#878]
I want to save a graph as .xml file after `ox.consolidate_intersections`.

However, when I load the graph from .xml file, it seems not work.

>Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

So can I get a graph after `ox.consolidate_intersections` and can operate on it the same as the original graph?

test code:
```
import osmnx as ox
ox.settings.all_oneway = True

place = 'Berkeley'

G1 = ox.graph_from_place(place)
G2 = ox.project_graph(G1)
G3 = ox.consolidate_intersections(G2)

ox.save_graph_xml(G3, place+".xml")
print(place, G3.number_of_nodes(), G3.number_of_edges())

Gx = ox.graph_from_xml(place+'.xml')
print(place, Gx.number_of_nodes(), Gx.number_of_edges())
ox.plot_graph(Gx)
```

**Comment by gboeing** [comment]
Please fill out the complete new issue details so I have enough info for debugging. Then I can take a look.

**Comment by Spockkk0225** [comment]
Thanks for your concern!

It seems that the first `print` sentence printed the correct result.

The full standard output: (I removed some personal information)
```
Berkeley 504 956
Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "*******.py", line 13, in <module>
    Gx = ox.graph_from_xml(place+'.xml')
  File "*******/python3.9/site-packages/osmnx/graph.py", line 522, in graph_from_xml
    G = simplification.simplify_graph(G)
  File "*******/python3.9/site-packages/osmnx/simplification.py", line 282, in simplify_graph
    path_attributes["geometry"] = LineString(
  File "*******/python3.9/site-packages/shapely/geometry/linestring.py", line 47, in __init__
    ret = geos_linestring_from_py(coordinates)
  File "shapely/speedups/_speedups.pyx", line 188, in shapely.speedups._speedups.geos_linestring_from_py
  File "shapely/speedups/_speedups.pyx", line 165, in shapely.speedups._speedups.geos_linestring_from_py._coords
  File "*******/python3.9/site-packages/shapely/coords.py", line 85, in __getitem__
    raise IndexError("index out of range")
IndexError: index out of range
```

**Comment by gboeing** [comment]
Your specific error is happening because you simplified the graph in the line `
G1 = ox.graph_from_place(place)`, but you are trying to simplify it again in the line `Gx = ox.graph_from_xml(place+'.xml')`. For one of those two, you must set the `simplify=False` parameter because you cannot simplify an already simplified graph.

More broadly, however, note the [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.osm_xml) for the `save_graph_xml` function:

> This function exists only to allow serialization to the .osm file format for applications that require it, and has constraints to conform to that. To save/load full-featured OSMnx graphs to/from disk for later use, use the io.save_graphml and io.load_graphml functions instead.

As the docs state, if you want to reload your graph again with OSMnx, use the `save_graphml` function. The `save_graph_xml` has a limited use case, and it does not include saving/loading for subsequent OSMnx analysis.

**Comment by gboeing** [comment]
Documentation further clarified in a936451.

**Comment by Spockkk0225** [comment]
I'll check the document and my code again. Thanks a lot for your careful answering!
