### ISSUE TITLE
Issue: TypeError: loop of ufunc does not support argument 0 of type float which has no callable deg2rad method

### ISSUE THREAD

**Issue by veager** [gboeing/osmnx#883]
**Do not delete the following template. Fill it out completely.**

  - [x] I have read the OSMnx [contributing guidelines](../blob/main/CONTRIBUTING.md)
  - [x] I have read the OSMnx [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples)
  - [x] I have searched the open/closed issues and [StackOverflow](https://stackoverflow.com/search?q=osmnx) for problems similar to mine

**Problem description**

When I use the function `ox.graph.graph_from_xml()` to parse a large osm file ([google drive](https://drive.google.com/file/d/1GYcWe_wJP6dro502Fs2-7NW9z2N8cYVP/view?usp=share_link), 38MB), I get the following errors:

```
AttributeError: 'float' object has no attribute 'deg2rad'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\osmnx_test\main.py", line 9, in <module>
    net = ox.graph.graph_from_xml(osm_file, retain_all=False)
  File "C:\Py39Geo\lib\site-packages\osmnx\graph.py", line 518, in graph_from_xml
    G = _create_graph(response_jsons, bidirectional=bidirectional, retain_all=retain_all)
  File "C:\Py39Geo\lib\site-packages\osmnx\graph.py", line 587, in _create_graph
    G = distance.add_edge_lengths(G)
  File "C:\Py39Geo\lib\site-packages\osmnx\distance.py", line 159, in add_edge_lengths
    dists = great_circle_vec(c[:, 0], c[:, 1], c[:, 2], c[:, 3]).round(precision)
  File "C:\Py39Geo\lib\site-packages\osmnx\distance.py", line 65, in great_circle_vec
    y1 = np.deg2rad(lat1)
TypeError: loop of ufunc does not support argument 0 of type float which has no callable deg2rad method
```

**Environment information**:
- Windows 10
- Python 3.9
- osmnx  1.2.2
```
Package            Version
------------------ -----------
attrs              22.1.0     
certifi            2022.9.24  
charset-normalizer 2.1.1      
click              8.1.3      
click-plugins      1.1.1      
cligj              0.7.2      
colorama           0.4.6      
contourpy          1.0.6      
cycler             0.11.0     
Fiona              1.8.22     
fonttools          4.38.0     
geopandas          0.12.1     
idna               3.4        
kiwisolver         1.4.4      
matplotlib         3.6.2
munch              2.5.0
networkx           2.8.8
numpy              1.23.4
osmnx              1.2.2
packaging          21.3
pandas             1.5.1
Pillow             9.3.0
pip                21.1.2
pyparsing          3.0.9
pyproj             3.4.0
python-dateutil    2.8.2
pytz               2022.6
requests           2.28.1
Rtree              1.0.1
setuptools         57.0.0
Shapely            1.8.5.post1
six                1.16.0
urllib3            1.26.12
wheel              0.36.2
```

Thank you so much.

**Comment by gboeing** [comment]
Your error is occurring here:
```
osmnx\distance.py", line 65, in great_circle_vec
```
Can you please run this line:
```python
G = ox.graph_from_place("Piedmont, California, USA", network_type="drive")
```
Does it succeed without error? This line will also call the `great_circle_vec` function. What I'm wondering is: what is the origin of your XML file? Is there anything non-standard in it that would cause your error? Something  may be wrong with your coordinates?

**Comment by veager** [comment]
Hi, @gboeing Thank you so much for your reply.

I have found it is my XML file error. I found that some elements of latitude and longitude parameters passing to `great_circle_vec` were `None`. I checked my file and found some points were dropped when I clipped the original osm file.
I re-clip the osm file and it can work now.

Thank you very much!
