### ISSUE TITLE
Length of street edges

### ISSUE THREAD

**Issue by ayesharshahid** [gboeing/osmnx#89]
Hi, 

I am new to OSMnx so might be missing something obvious. I downloaded shapefiles of street edges using ox.graph_from_place for Almaty, Kazakhstan, saved it as a shapefile and then imported it into QGIS. I was doing a sanity check measuring by ruler distance of each edge segment and found that each one was measured to roughly 50m more than the length written in the attribute table of the shapefile. I thought maybe this is a projection issue. The project projection is EPSG: 3857, same as OSM's default one. Changing it to WSG84 didn't quite solve it. Am I missing something obvious? 

#### What operating system, architecture, Python version, and OSMnx version are you using?
Windows 8, python 3.4.4, OSMnx 0.5.3. 

####Python code: 
````
G = ox.graph_from_place('Almaty, Kazakhstan', network_type='bike')
fig, ax = ox.plot_graph(G)
ox.save_graph_shapefile(G, filename='Almaty_Bike_Network')
`````

**Comment by gboeing** [comment]
@ayesharshahid I just checked and all looks to be working properly to my eye. Try to use a meter projection then check the length again. For example, in QGIS click Project > Project Properties > then click on enable on-the-fly CRS transformation. Choose an appropriate meter projection for Almaty (UTM zone 43N looks like a [good candidate](http://spatialreference.org/ref/epsg/wgs-84-utm-zone-43n/)). Then try using the Measure Line tool. It should work properly.

**Comment by ayesharshahid** [comment]
That did it! Projections will be the bane of me. Thank you! OSMnx is great for GIS amateurs like me!
