### ISSUE TITLE
Enhancement: Get elevation data from opentopodata.org

### ISSUE THREAD

**Issue by aburgr** [gboeing/osmnx#893]
Hi!

It would be great to add the possiblity to get elevantion data from opentopodata.org.

The API is identical to the maps.googleapis.com/maps API.
`https://api.opentopodata.org/v1/eudem25m?locations={}&key={}`

The advantage is that no user or api-key is necessary. The maximum locations per batch is still 100.

Best regards,
Andreas

**Comment by gboeing** [comment]
Resolved by #901
