### ISSUE TITLE
Best practice - custom query parameters

### ISSUE THREAD

**Issue by kuanb** [gboeing/osmnx#90]
Question: 2 parts:
1. Confirm `infrastructure` kwarg is appropriate way to pass custom OSM queries.
2. Propose conversion of `get_osm_filter` to a class method to allow for customization.

OSM Filter defaults are set as a dictionary assembled every time `get_osm_filter` is called.

1. In my workflow, I'd like to introduce a modification/new filter parameters (drive excluding highways). [This example](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/16-work-with-other-infrastructures.ipynb) suggests that the best way to do this would be to use network type `'none'` and to then pass the custom query through the `infrastructure` kwarg. Is this correct?

2. If the above is correct, I'd like to suggest that, perhaps, a class `OSMSearchFilter` be created with a method `.get_filter(filter_name)`. When initialized, it has some defaults, but also the ability to `.edit_filter(filter_name, modification)` and `.add_filter(filter_name, filter_string)`. 

The 2 makes sense, I'd be happy to sketch it out and submit it.

Update: Upon further review I see that `infrastructure` actually subselects a particular way type from the network values so, in order to do a custom network (in my case prune out `highway=motorway`), I'd need to introduce a new network default into OSM. (Let me know if this is wrong, of course.)

**Comment by gboeing** [comment]
A couple thoughts. 

The original use case for OSMnx was to make things dead simple: get a street network that corresponds to a "type" that a planner would understand and find valid. Like drive, or walk. As time has gone on, this feature seems increasingly limiting. It would be nice to be able to request specific highway types, or exclude certain others in a more customized way. I'm not sure of the best way to do this though.

When I was first creating OSMnx it was just a script I was running to do dissertation data collection. As it expanded, I realized I should have made it object-oriented, but in the end I couldn't afford the time to refactor it all into classes. Maybe someday. 

If you want to sketch out some ideas for more powerful OSM querying/filtering, I'd be curious to see it and have a think.

**Comment by kuanb** [comment]
Sounds good, thanks for the reply. Totally understand re why it wasn't present. I see your point re making it oo. Itd prob be a rabbit hole to make just that component part of a class... That would likely push or make it feel like the rest should be in classes as well. I could just have an alternative parameter that it could be fed. I'll whip it up this week.

**Comment by gboeing** [comment]
@kuanb just checking back if you still want to keep this issue open?

**Comment by kuanb** [comment]
Wow! I totally dropped the ball on this. Can I have a ~week to dig back into this? I still think it would be helpful. Sorry for leaving this hanging for so long.

**Comment by gboeing** [comment]
No prob at all! Was just checking if you were still thinking about this.

**Comment by kuanb** [comment]
In the interest of starting with a very minimal entry, here's a proposal: 

Diff: https://github.com/gboeing/osmnx/compare/master...kuanb:kuanb-custom-query

Basically, there's just one more param in `osm_net_download`. This would have to be threaded through the `graph_from_...` methods, as well, of course. But, basically, you could just write your own string filter and pass it in lieu of using one of the preset ones.

**Comment by gboeing** [comment]
@kuanb see #139

**Comment by kuanb** [comment]
As mentioned above, merging https://github.com/gboeing/osmnx/pull/139 will/should close this issue.
