### ISSUE TITLE
Bug with graph_from_gdfs

### ISSUE THREAD

**Issue by FGE85** [gboeing/osmnx#913]
Hi. I'm facing a bug while using graph_from_gdfs. I'm trying to add a node in order to calculate some distances but I get "TypeError: cannot unpack non-iterable int object"

  - [x] I have read the OSMnx [contributing guidelines](../blob/main/CONTRIBUTING.md)
  - [x] I have read the OSMnx [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples)
  - [x] I have searched the open/closed issues and [StackOverflow](https://stackoverflow.com/search?q=osmnx) for problems similar to mine

I'm using windows 11, python 3.10 and OSMnx 1.23 

<details>
My packages: 
affine                    2.3.1
anyio                     3.6.2
argon2-cffi               21.3.0
argon2-cffi-bindings      21.2.0
arrow                     1.2.3
association-metrics       0.0.1
asttokens                 2.0.7
attrs                     22.1.0
autopage                  0.5.1
Babel                     2.11.0
backcall                  0.2.0
beautifulsoup4            4.11.1
bleach                    5.0.1
branca                    0.5.0
Brotli                    1.0.9
cachelib                  0.9.0
certifi                   2022.6.15
cffi                      1.15.1
charset-normalizer        2.1.0
chart-studio              1.1.0
classify                  0.5.0
click                     8.1.3
click-plugins             1.1.1
cligj                     0.7.2
cmaes                     0.8.2
cmd2                      2.4.2
colorama                  0.4.5
colorlog                  6.7.0
colormap                  1.0.4
contextily                1.2.0
contourpy                 1.0.5
cspy                      1.0.2
cycler                    0.11.0
Cython                    0.29.32
dash                      2.6.1
dash-auth                 1.3.2
dash-bootstrap-components 1.2.1
dash-bootstrap-templates  1.0.7
dash-core-components      2.0.0
dash-extensions           0.0.65
dash-html-components      2.0.0
dash-leaflet              0.1.23
dash-table                5.0.0
debugpy                   1.6.2
decorator                 5.1.1
defusedxml                0.7.1
docopt                    0.6.2
EditorConfig              0.12.3
entrypoints               0.4
et-xmlfile                1.1.0
executing                 0.9.1
fastjsonschema            2.16.1
Fiona                     1.8.21
Flask                     2.2.1
Flask-Caching             2.0.1
Flask-Compress            1.12
Flask-SeaSurf             1.1.1
folium                    0.12.1.post1
fonttools                 4.34.4
fqdn                      1.5.1
GDAL                      3.4.3
geobuf                    1.1.1
geographiclib             1.52
geopandas                 0.12.2
geoplotlib                0.3.2
geopy                     2.2.0
geos                      0.2.3
goto-statement            1.2
greenlet                  1.1.3
hygese                    0.0.0.8
idna                      3.3
ipykernel                 6.15.1
ipylab                    0.5.2
ipython                   8.4.0
ipython-genutils          0.2.0
ipywidgets                7.0.0
isoduration               20.11.0
itsdangerous              2.1.2
jedi                      0.18.1
Jinja2                    3.1.2
joblib                    1.1.0
Js2Py                     0.71
jsbeautifier              1.14.6
json5                     0.9.10
jsonpointer               2.3
jsonschema                4.9.1
jupyter_client            7.4.8
jupyter_core              5.1.0
jupyter-events            0.5.0
jupyter_server            2.0.1
jupyter_server_terminals  0.4.2
jupyterlab                3.5.1
jupyterlab-pygments       0.2.2
jupyterlab_server         2.16.5
jupyterlab-widgets        1.1.1
kepler                    0.0.1
keplergl                  0.3.2
kiwisolver                1.4.4
lxml                      4.9.1
Mako                      1.2.3
mapclassify               2.4.3
MarkupSafe                2.1.1
matplotlib                3.6.1
matplotlib-inline         0.1.3
mercantile                1.2.1
mistune                   0.8.4
more-itertools            8.14.0
munch                     2.5.0
nbclassic                 0.4.8
nbclient                  0.6.6
nbconvert                 6.5.1
nbformat                  5.4.0
nest-asyncio              1.5.5
networkx                  2.8.5
notebook                  6.4.12
notebook_shim             0.2.2
numpy                     1.24.1
openpyxl                  3.0.10
osmnx                     1.2.3
packaging                 21.3
pandas                    1.5.1
pandocfilters             1.5.0
parso                     0.8.3
patsy                     0.5.2
pbr                       5.11.0
pickleshare               0.7.5
Pillow                    9.2.0
pip                       22.2.1
pipwin                    0.5.2
platformdirs              2.6.0
plotly                    5.10.0
plotly-express            0.4.1
prettytable               3.5.0
prometheus-client         0.14.1
prompt-toolkit            3.0.30
protobuf                  3.20.1
psutil                    5.9.1
PuLP                      2.6.0
pure-eval                 0.2.2
pyaml                     21.10.1
pycparser                 2.21
pygeos                    0.12.0
pyglet                    1.5.26
Pygments                  2.12.0
pyjsparser                2.7.1
pyparsing                 3.0.9
pyperclip                 1.8.2
PyPrind                   2.11.3
pyproj                    3.4.1
pyreadline3               3.4.1
pyrsistent                0.18.1
pySmartDL                 1.3.4
python-dateutil           2.8.2
python-json-logger        2.0.4
pytz                      2022.1
pytz-deprecation-shim     0.1.0.post0
pywin32                   304
pywinpty                  2.0.7
PyYAML                    6.0
pyzmq                     24.0.1
rasterio                  1.3.0
requests                  2.28.1
retrying                  1.3.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
Rtree                     1.0.0
scikit-learn              1.1.0
scipy                     1.9.0
scoop                     0.7.2.0
seaborn                   0.11.2
Send2Trash                1.8.0
setuptools                65.3.0
setuptools-scm            7.0.5
Shapely                   1.8.2
six                       1.16.0
sniffio                   1.3.0
snuggs                    1.4.7
soupsieve                 2.3.2.post1
SQLAlchemy                1.4.42
stack-data                0.3.0
statsmodels               0.13.2
stevedore                 4.1.0
tenacity                  8.0.1
terminado                 0.15.0
threadpoolctl             3.1.0
tinycss2                  1.1.1
tomli                     2.0.1
tornado                   6.2
tqdm                      4.64.0
traitlets                 5.7.1
traittypes                0.2.1
typing_extensions         4.4.0
tzdata                    2022.1
tzlocal                   4.2
ua-parser                 0.16.1
uri-template              1.2.0
urllib3                   1.26.11
vrpy                      0.5.1
wcwidth                   0.2.5
webcolors                 1.12
webencodings              0.5.1
websocket-client          1.4.2
Werkzeug                  2.2.1
wheel                     0.37.1
widgetsnbextension        3.0.8
xyzservices               2022.6.0
zipp                      3.10.0

</details>

```python
import networkx as nx
import osmnx as ox
from IPython.display import IFrame
import geopandas as gpd
from shapely.geometry import  Point

my_dict = {
  '001': {
    'y': -31.640224888841907,
    'x': -60.672566478771884,
    'street_count': 1
  }
}

tmp_list = []
for item_key, item_value in my_dict.items() :
  tmp_list.append({
    'geometry' : Point(item_value['x'], item_value['y']),
    'osmid': item_key,
    'y' : item_value['y'],
      'x' : item_value['x'],
    'street_count': item_value ['street_count']
   })
my_nodes = gpd.GeoDataFrame(tmp_list)

G = ox.graph_from_place("Santa Fe, Santa Fe, Argentina", network_type="drive", buffer_dist=5000)
nodes= ox.graph_to_gdfs(G, nodes=True, edges=False).reset_index()
edges= ox.graph_to_gdfs(G, edges=True, nodes=False).reset_index()

nodes = nodes.append(my_nodes, ignore_index = True)
G2 = ox.graph_from_gdfs(nodes, edges) 

```

**Comment by gboeing** [comment]
This is not a bug with OSMnx. You are using the function incorrectly. Please read the OSMnx [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils_graph.graph_from_gdfs) for the `graph_from_gdfs` function:

> However, you can convert arbitrary node and edge GeoDataFrames as long as 1) gdf_nodes is uniquely indexed by osmid, 2) gdf_nodes contains x and y coordinate columns representing node geometries, 3) gdf_edges is uniquely multi-indexed by u, v, key (following normal MultiDiGraph structure). This allows you to load any node/edge shapefiles or GeoPackage layers as GeoDataFrames then convert them to a MultiDiGraph for graph analysis. Note that any geometry attribute on gdf_nodes is discarded since x and y provide the necessary node geometry information instead.

Neither your nodes nor edges GeoDataFrames are indexed as the documentation states they must be, because you called `reset_index` on them.

**Comment by gboeing** [comment]
See #1317 for a validator.
