### ISSUE TITLE
`graph_from_place()` Hang: Towns Named After Countries

### ISSUE THREAD

**Issue by MetzgerSK** [gboeing/osmnx#927]
## Preliminaries
  - [x] I have read the OSMnx [contributing guidelines](../blob/main/CONTRIBUTING.md)<br/>_Found this potential issue on a lark.  Python's not one of my languages, so my ability to troubleshoot's limited.  The problem seems to stem from one of OSMnx's functions.  If it stems from one of OSMnx's dependencies, though, disregard this report._ 
  - [x] I have read the OSMnx [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples) <br/>_Searched for mentions of "country", then read through results._
  - [x] I have searched the open/closed issues and [StackOverflow](https://stackoverflow.com/search?q=osmnx) for problems similar to mine <br/>_Searched for mentions of "country", then read through results._

## Problem Description
When querying town names that are the same as country names, `graph_from_place()` seems to stall out.

  - _Did what_: Added element to `places` object containing town name in the US.  The town happens to be named after a country.
  - _Expected_: Code to run successfully + graphs for all elements in `places` to be generated.
  - _Actually occurred_: Code does not run successfully.  `geocode_to_gdf()` runs fine (first "Details" chunk), but the `graph_from_place()` query either (a) does not advance past the country-as-town name (second "Details" chunk) or (b) throws error and generates graphs only for elements corresponding to non-country-as-towns (error in third "Details" chunk).

## Environment Information
Tested locally, but reproduced the issue in OSMnx's Binder (see MWE).  All copy/pasted output comes from the Binder run.

<details>
<summary><code>geocode_to_gdf()</code> Query Output (successful)</summary>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>geometry</th>
      <th>bbox_north</th>
      <th>bbox_south</th>
      <th>bbox_east</th>
      <th>bbox_west</th>
      <th>place_id</th>
      <th>osm_type</th>
      <th>osm_id</th>
      <th>lat</th>
      <th>lon</th>
      <th>display_name</th>
      <th>class</th>
      <th>type</th>
      <th>importance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>MULTIPOLYGON (((-106.69272 35.08326, -106.6928...</td>
      <td>35.218203</td>
      <td>34.947087</td>
      <td>-106.471376</td>
      <td>-106.882150</td>
      <td>298030767</td>
      <td>relation</td>
      <td>171262</td>
      <td>35.084103</td>
      <td>-106.650985</td>
      <td>Albuquerque, Bernalillo County, New Mexico, Un...</td>
      <td>boundary</td>
      <td>administrative</td>
      <td>0.702740</td>
    </tr>
    <tr>
      <th>1</th>
      <td>POLYGON ((-79.03948 42.62794, -79.01978 42.628...</td>
      <td>42.647761</td>
      <td>42.627935</td>
      <td>-79.019784</td>
      <td>-79.039477</td>
      <td>298029982</td>
      <td>relation</td>
      <td>176039</td>
      <td>42.638393</td>
      <td>-79.027816</td>
      <td>Village of Angola, Town of Evans, Erie County,...</td>
      <td>boundary</td>
      <td>administrative</td>
      <td>0.521335</td>
    </tr>
  </tbody>
</table>

</details>

<details>
<summary><code>graph_from_place()</code> Query Output (unsuccessful)</summary>
<pre>
2023-01-27 16:03:07 Albuquerque
2023-01-27 16:04:54 Angola
</pre>

The possible error output in the next "Details" chunk was finally thrown at `2023-01-27 16:28:16`, for reference.
</details>

<details>
<summary>Possible Error Output</summary>
<i>Might have accidentally killed the kernel with an errant keystroke.  But, in case useful:</i>
<pre class="highlight">
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In [7], line 13
     10 print(ox.utils.ts(), place)
     12 # get undirected graphs with edge bearing attributes
---> 13 G = ox.graph_from_place(place, network_type="drive")
     14 Gu = ox.add_edge_bearings(ox.get_undirected(G))
     15 fig, ax = ox.bearing.plot_orientation(Gu, ax=ax, title=place, area=True)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/osmnx/graph.py:351, in graph_from_place(query, network_type, simplify, retain_all, truncate_by_edge, which_result, buffer_dist, clean_periphery, custom_filter)
    348 utils.log("Constructed place geometry polygon(s) to query API")
    350 # create graph using this polygon(s) geometry
--> 351 G = graph_from_polygon(
    352     polygon,
    353     network_type=network_type,
    354     simplify=simplify,
    355     retain_all=retain_all,
    356     truncate_by_edge=truncate_by_edge,
    357     clean_periphery=clean_periphery,
    358     custom_filter=custom_filter,
    359 )
    361 utils.log(f"graph_from_place returned graph with {len(G)} nodes and {len(G.edges)} edges")
    362 return G

File /srv/conda/envs/notebook/lib/python3.10/site-packages/osmnx/graph.py:432, in graph_from_polygon(polygon, network_type, simplify, retain_all, truncate_by_edge, clean_periphery, custom_filter)
    429 poly_buff, _ = projection.project_geometry(poly_proj_buff, crs=crs_utm, to_latlong=True)
    431 # download the network data from OSM within buffered polygon
--> 432 response_jsons = downloader._osm_network_download(poly_buff, network_type, custom_filter)
    434 # create buffered graph from the downloaded data
    435 bidirectional = network_type in settings.bidirectional_network_types

File /srv/conda/envs/notebook/lib/python3.10/site-packages/osmnx/downloader.py:548, in _osm_network_download(polygon, network_type, custom_filter)
    546 for polygon_coord_str in polygon_coord_strs:
    547     query_str = f"{overpass_settings};(way{osm_filter}(poly:'{polygon_coord_str}');>;);out;"
--> 548     response_json = overpass_request(data={"data": query_str})
    549     response_jsons.append(response_json)
    550 utils.log(
    551     f"Got all network data within polygon from API in {len(polygon_coord_strs)} request(s)"
    552 )

File /srv/conda/envs/notebook/lib/python3.10/site-packages/osmnx/downloader.py:768, in overpass_request(data, pause, error_pause)
    766     this_pause = _get_pause(base_endpoint)
    767 utils.log(f"Pausing {this_pause} seconds before making HTTP POST request")
--> 768 time.sleep(this_pause)
    770 # transmit the HTTP POST request
    771 utils.log(f"Post {prepared_url} with timeout={settings.timeout}")

KeyboardInterrupt: 
</pre>
</details>

## MWE
Launch [Binder](https://mybinder.org/v2/gh/gboeing/osmnx-examples/main?urlpath=lab), open `17-street-network-orientations.ipynb`, and change the `places` object's contents to be:
```python
places = {
    "Albuquerque": "Albuquerque, NM, USA",  # to ensure a query's successful
    "Angola"     : "Angola, NY, USA",       # example of problem
}
```
Then, run the code.

I also tried a few other countries-as-towns, arbitrarily picked from [this](https://en.wikipedia.org/wiki/List_of_U.S._places_named_after_non-U.S._places) list + some local knowledge:
 * Brazil, IN
 * Greece, NY
 * Mexico, MS

Ran these on my local machine (and let one or two of them run for a few hours), but ran into the same problem.  Had to kill the kernel manually every time.

**Comment by gboeing** [comment]
Thanks for using OSMnx! Not a bug. You can turn on OSMnx logging to see what it's doing and why this is happening. If you have further questions about this usage, please ask on StackOverflow.x

**Comment by MetzgerSK** [comment]
Huh, interesting.  I found it curious that the query about Albuquerque took 17 seconds to run on my local machine, but that Mexico, MS (pop: ~11.5k) ran for 2 hours and took up ~29GB of RAM, but still hadn't finished running.  However, if you say no bug, then no bug.  Thanks for looking into this, and if I dive into it any deeper and have follow-up questions, I'll post them on SO.
