### ISSUE TITLE
Add the option of providing a z-order for edges when plotting a graph

### ISSUE THREAD

**Issue by george-willcox** [gboeing/osmnx#928]
**Do not delete the following template. Fill it out completely.**

  - [x] I have read the OSMnx [contributing guidelines](../blob/main/CONTRIBUTING.md)
  - [x] I have read the OSMnx [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples)
  - [x] I have searched the open/closed issues and pull requests for others similar to mine

**Is your feature proposal related to a problem?**

Currently, there is no way to specify a z-ordering of edges when calling `osmnx.plot_graph()`. This can result in undesirable-looking plots, where edges with data that is significant can be covered over. And, especially in areas with many nodes close together, can result in a messy plot.

**Describe the solution you'd like to propose**

Add an argument to the `plot_graph` method to take a list which gives the relative z-ordering of the edges in the graph, which can be used to sort the dataframe before calling `gdf_edges.plot()`.

**Describe alternatives you've considered**

It's possible to do this without using the `plot_graph` method, but it essentially involves rewriting the same code as in the method, but with the mentioned change. And, having this as an argument here would be much more convenient.

**Additional context**

The following code will produce [this image](https://i.imgur.com/2YU48fW.png) (when zoomed in).

```python
import networkx as nx
import osmnx as ox

place = "Hornsea"
G = ox.graph_from_place(place, network_type="drive")

line_graph = nx.line_graph(G)
betweenness_centrality = nx.betweenness_centrality(line_graph, weight="travel_time")
nx.set_edge_attributes(G, betweenness_centrality, "betweenness_centrality")

edge_colours = ox.plot.get_edge_colors_by_attr(
    G, "betweenness_centrality", cmap="plasma"
)
edge_linewidth = [
    G.get_edge_data(*edge).get("betweenness_centrality", 0) * 10 + 0.25
    for edge in G.edges
]
fig, ax = ox.plot_graph(
    G,
    edge_color=edge_colours,
    edge_linewidth=edge_linewidth,
    node_size=0,
    save=True,
    filepath=f"images/{place}.png",
    dpi=1000,
)
```

And with this proposal, the change shown below would produce [this image](https://i.imgur.com/TISRMGy.png).

```python
edge_zorder = [
    G.get_edge_data(*edge).get("betweenness_centrality", 0) for edge in G.edges
]
fig, ax = ox.plot_graph(
    G,
    edge_color=edge_colours,
    edge_linewidth=edge_linewidth,
    edge_zorder=edge_zorder,
    node_size=0,
    save=True,
    filepath=f"images/{place}.png",
    dpi=1000,
)
```

**Comment by gboeing** [comment]
Thanks for using OSMnx and suggesting this. We're unlikely to add this as a new feature: the OSMnx project maintains a basic plotting module to cover most use cases. We recommend that users with other use cases employ a custom solution. This allows us to keep the codebase general-purpose and mantainable. For your use case, it should be pretty simple by just adapting a couple lines of code from the `plot` module, along the lines of what you suggested in the PR.
