### ISSUE TITLE
Graph from file?

### ISSUE THREAD

**Issue by migurski** [gboeing/osmnx#93]
I’m looking at OSMnx and needing to create a graph from a local OSM file, such as the ones generated by [Metro Extracts](https://mapzen.com/metro-extracts). I would expect to see this in the group of `graph_from_*` functions (e.g. graph_from_address, graph_from_bbox, etc.). Does this exist someplace? If it doesn't, would it be a welcome addition to OSMnx?

**Comment by kuanb** [comment]
I don't believe there exists, currently, the ability to do a graph from a local file.

All the `graph_from_*` (I believe) wrap just over `graph_from_bbox`, which feeds `osm_net_download` output into `create_graph`.

If it (a `from_local` were to be generated, I think there could be the option to read from a file instead of run `osm_net_download` and pass that to `create_graph`. Would just need to resolve the fact that the response is current a JSON and the extracts would be XML, PBF, etc...

**Comment by migurski** [comment]
Thanks Kuan! The way I'm thinking of using this data, I need to have a known version of OSM data to coordinate between a few different pieces of software. I’ll root around in the code to see if any obvious implementations jump out at me.

**Comment by migurski** [comment]
Yeah! What’s nice about starting from OSM files is that you can [run Osmosis on them](http://wiki.openstreetmap.org/wiki/Osmosis) to do your filtering. I don't specifically have an issue with the OO vs. functions thing, just looking for another way to get vetted data in.

**Comment by gboeing** [comment]
@migurski @kuanb correct, this functionality does not currently exist. However it would be a very welcome addition. I know there has been interest in this previously from other quarters... I just haven't had the time or personal need to develop it myself. But a graph_from_osm_file() function would be really useful if you have any interest in looking into it. It wouldn't take much processing to pass the read data off to the create_graph() function.

**Comment by gboeing** [comment]
Resolved by #95

**Comment by zifeo** [comment]
@gboeing Is there any way of saving a graph as osm (or pbf)? Is this reasonable a feature?

**Comment by gboeing** [comment]
@zifeo no, OSMnx saves graphs as GraphML, ESRI shapefile, or regular old node/edge lists. Converting data back to .osm format would be a specialized task and probably best to consult https://wiki.openstreetmap.org/wiki/Converting_map_data_between_formats or similar.

**Comment by zifeo** [comment]
Thanks!
