### ISSUE TITLE
setting.default_crs UTM issue

### ISSUE THREAD

**Issue by aw-west-defra** [gboeing/osmnx#931]
- [x] I have read the OSMnx [contributing guidelines](../blob/main/CONTRIBUTING.md)
  - [x] I have read the OSMnx [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples)
  - [x] I have searched the open/closed issues and [StackOverflow](https://stackoverflow.com/search?q=osmnx) for problems similar to mine

**Problem description**
  - What did you do?
Change default CRS to BNG=epsg:27700
  - What did you expect to happen?
Download the data I wanted.
  - And what actually happened instead?
`ValueError: Geometry must be unprojected to calculate UTM zone`

**Environment information**
  - What operating system are you using?
`import platform; platform.platform()` > `Linux-5.4.0-1100-azure-x86_64-with-glibc2.29`
  - What Python version are you using?
`import sys; sys.version` > `3.8.10 (default, Nov 14 2022, 12:59:47) \n[GCC 9.4.0]`
  - What OSMnx version are you using?
`import osmnx; osmnx.__version__` > `1.2.2`
  - Provide a complete list of your environment's packages and their versions (`pip list`)

<details>

Package              Version
-------------------- --------------------
affine               2.4.0
apache-sedona        1.2.1
appdirs              1.4.4
argon2-cffi          20.1.0
async-generator      1.10
attrs                20.3.0
backcall             0.2.0
bidict               0.21.4
bleach               3.3.0
boto3                1.16.7
botocore             1.19.7
branca               0.6.0
cachetools           5.3.0
certifi              2020.12.5
cffi                 1.14.5
chardet              4.0.0
charset-normalizer   3.0.1
click                8.1.3
click-plugins        1.1.1
cligj                0.7.2
contourpy            1.0.7
cycler               0.10.0
Cython               0.29.23
databricks-mosaic    0.3.7
dbus-python          1.2.16
decorator            5.0.6
defusedxml           0.7.1
distlib              0.3.4
distro               1.4.0
distro-info          0.23ubuntu1
entrypoints          0.3
et-xmlfile           1.1.0
facets-overview      1.0.0
filelock             3.6.0
Fiona                1.9.0
folium               0.14.0
fonttools            4.38.0
GDAL                 3.4.3
geocube              0.3.3
geopandas            0.12.2
h3                   3.7.0
idna                 2.10
ipykernel            5.3.4
ipython              7.22.0
ipython-genutils     0.2.0
ipywidgets           7.6.3
jedi                 0.17.2
Jinja2               2.11.3
jmespath             0.10.0
joblib               1.0.1
jsonschema           3.2.0
jupyter-client       6.1.12
jupyter-core         4.7.1
jupyterlab-pygments  0.1.2
jupyterlab-widgets   1.0.0
kaleido              0.2.1
keplergl             0.3.2
kiwisolver           1.3.1
koalas               1.8.2
lxml                 4.9.2
mapclassify          2.5.0
MarkupSafe           2.0.1
matplotlib           3.6.3
matplotlib-scalebar  0.8.1
mistune              0.8.4
more-itertools       8.14.0
munch                2.5.0
nbclient             0.5.3
nbconvert            6.0.7
nbformat             5.1.3
nest-asyncio         1.5.1
networkx             3.0
notebook             6.3.0
numpy                1.22.4
odc-geo              0.3.3
openpyxl             3.1.0
osmnx                1.2.2
packaging            23.0
pandas               1.5.3
pandocfilters        1.4.3
parso                0.7.0
patsy                0.5.1
pexpect              4.8.0
pickleshare          0.7.5
Pillow               8.2.0
pip                  21.0.1
plotly               5.5.0
prometheus-client    0.10.1
prompt-toolkit       3.0.17
protobuf             3.17.2
psycopg2             2.8.5
ptyprocess           0.7.0
py4j                 0.10.9.3
pyarrow              4.0.0
pycparser            2.20
Pygments             2.8.1
PyGObject            3.36.0
pyogrio              0.5.1
pyparsing            2.4.7
pyproj               3.4.1
pyrsistent           0.17.3
pyspark              3.2.1
pyspark-vector-files 0.2.5
python-apt           2.0.0+ubuntu0.20.4.8
python-dateutil      2.8.1
python-engineio      4.3.0
python-pptx          0.6.21
python-socketio      5.4.1
pytz                 2020.5
pyzmq                20.0.0
rasterio             1.3.5.post1
requests             2.28.2
requests-unixsocket  0.2.0
rioxarray            0.13.3
Rtree                1.0.1
s3transfer           0.3.7
scikit-learn         0.24.1
scipy                1.6.2
seaborn              0.11.1
Send2Trash           1.5.0
setuptools           52.0.0
Shapely              1.8.5.post1
six                  1.15.0
snuggs               1.4.7
spatialite           0.0.3
ssh-import-id        5.10
statsmodels          0.12.2
tenacity             8.0.1
terminado            0.9.4
testpath             0.4.4
threadpoolctl        2.1.0
tornado              6.1
traitlets            5.0.5
traittypes           0.2.1
unattended-upgrades  0.1
urllib3              1.25.11
virtualenv           20.4.1
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.36.2
widgetsnbextension   3.5.1
xarray               2023.1.0
XlsxWriter           3.0.8
</details>

**Minimal Reproducible Example**

Fails
```python
import osmnx as ox
ox.settings.default_crs = 'epsg:27700'
df = ox.geometries_from_place('Gwynedd', {'water': True})

>>> ValueError: Geometry must be unprojected to calculate UTM zone
```

Success, using the default (lat,lon) which is UTM coordinates for downloading, then converting.
```python
import osmnx as ox
df = ox.geometries_from_place('Gwynedd', {'water': True}).to_crs('epsg')
```

**Comment by gboeing** [comment]
When you change the value of `ox.settings.default_crs` you are *setting* the CRS value, not reprojecting your coordinates. You are simply telling OSMnx: "this is the coordinate reference system that these data are already in." This is the same as in other GIS tools where you can either 1) tell the system the current CRS the data are already in, or 2) reproject the data to a new CRS. See GeoPandas, for example.

If your data are not actually in the CRS that you told it they would be in, you'll run into problems. You see that here: you told it the coordinates would be in `epsg:27700`, but you downloaded the geometries from OpenStreetMap, which uses `epsg:4326`. If you want to change your data's CRS, reproject it as described in the OSMnx documentation and usage examples.

**Comment by aw-west-defra** [comment]
Apologies for misunderstanding.
Should this be made more clear in the documentation then?
[default_crs doc](https://osmnx.readthedocs.io/en/stable/internals.html?highlight=default_crs#osmnx-settings-module)

From:
Default coordinate reference system to set when creating graphs. Default is “epsg:4326”.
Perhaps:
Backup coordinate reference system if none is provided from the upstream source, used when creating graphs. Default is “epsg:4326”.

**Comment by gboeing** [comment]
> Backup coordinate reference system if none is provided from the source, used when creating graphs. Default is “epsg:4326”.

It doesn't really work like that: the source does not provide a CRS. You alone have to tell OSMnx what the CRS is. This parameter in the `settings` module is where you set it.
