### ISSUE TITLE
maxspeed with | misinterpreted

### ISSUE THREAD

**Issue by crosspolar** [gboeing/osmnx#934]
- [x] I have read the OSMnx [contributing guidelines](../blob/main/CONTRIBUTING.md)
  - [x] I have read the OSMnx [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples)
  - [x] I have searched the open/closed issues and [StackOverflow](https://stackoverflow.com/search?q=osmnx) for problems similar to mine

**Problem description**
  - What did you do? I assigned the speed to all motorways and primary-highways in germany with `ox.add_edge_speeds()`. One edge had a maxspeed of "70|100". Either this is a complete user error or it is meant to be for different lanes (but also wrong).
  - What did you expect to happen? The actual speed on that edge is above 10000 km/h.
  - And what actually happened instead? I would prefer the slower maxspeed to be selected, but whatever suits you.

**Environment information**
  - What operating system are you using? Windows 11
  - What Python version are you using? 3.11
  - What OSMnx version are you using? 1.3.0
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
attrs              22.2.0   
bcrypt             4.0.1    
black              22.12.0  
certifi            2022.12.7
cffi               1.15.1   
cfgv               3.3.1    
charset-normalizer 2.1.1    
click              8.1.3    
click-plugins      1.1.1    
cligj              0.7.2
colorama           0.4.6
contourpy          1.0.7
cryptography       39.0.0
cycler             0.11.0
distlib            0.3.6
filelock           3.9.0
Fiona              1.8.22
fonttools          4.38.0
GeoAlchemy2        0.13.1
geopandas          0.12.2
greenlet           2.0.1
identify           2.5.11
idna               3.4
iniconfig          1.1.1
joblib             1.2.0
kiwisolver         1.4.4
matplotlib         3.6.3
munch              2.5.0
mypy-extensions    0.4.3
networkx           3.0
nodeenv            1.7.0
numpy              1.24.1
osmnx              1.3.0
packaging          22.0
pandas             1.5.3
paramiko           2.12.0
pathspec           0.10.3
Pillow             9.4.0
pip                22.3.1
platformdirs       2.6.2
pluggy             1.0.0
pre-commit         2.21.0
psycopg            3.1.7
psycopg-binary     3.1.6
psycopg2           2.9.5
psycopg2-binary    2.9.5
pycparser          2.21
PyNaCl             1.5.0
pyparsing          3.0.9
pyproj             3.4.1
pytest             7.2.1
python-dateutil    2.8.2
python-dotenv      0.21.1
pytz               2022.7
PyYAML             6.0
requests           2.28.2
scikit-learn       1.2.1
scipy              1.10.0
setuptools         65.6.3
shapely            2.0.0
six                1.16.0
SQLAlchemy         1.4.46
sshtunnel          0.4.0
threadpoolctl      3.1.0
tqdm               4.64.1
typing_extensions  4.4.0
tzdata             2022.7
urllib3            1.26.13
virtualenv         20.17.1
wheel              0.38.4

</details>

**Provide a complete minimal reproducible example**

```python
import osmnx as ox
import networkx as nx

location_point = (37.791427, -122.410018)
G = ox.graph_from_point(location_point, dist=750, dist_type="bbox", network_type="drive")
random_edge = list(G.edges)[5]
nx.set_edge_attributes(G, "70|100", "maxspeed")
G = ox.add_edge_speeds(G)
node, edge = ox.graph_to_gdfs(G)
print(edge.head()["speed_kph"])
```
returns
```
u         v         key
65295287  65295289  0      70100.0
          65305817  0      70100.0
65295289  65307363  0      70100.0
          65295293  0      70100.0
          65295287  0      70100.0
Name: speed_kph, dtype: float64

```

**Comment by crosspolar** [comment]
I assume the `_clean_maxspeed` could be adapted to split at `| ` and select the smallest value or calculate the average value. If this is fine for you, I can prepare a PR the next days.

**Comment by gboeing** [comment]
Where did the "70|100" value come from? Is it directly from OpenStreetMap? If so, can you provide the OSM way ID?

**Comment by crosspolar** [comment]
It is directly from OpenStreetMap. You can find it here: https://www.openstreetmap.org/way/118245446#map=19/51.30424/14.32723. The road has two lanes, but the tagging person wasn't using the `lanes` key.

And while searching for other unexpected values in Openstreetmap tags, I found these:

- maxspeed of 0 km/h, e.g. https://www.openstreetmap.org/way/71130861
- maxspeed ="DE:rural" (instead of maxspeed:type), e.g. https://www.openstreetmap.org/way/352062105
- maxspeed="signals", see [here](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Maxspeed#Proposals)

**Comment by gboeing** [comment]
Thanks, yes, would you like to propose a PR to split on | and calculate the average?

**Comment by gboeing** [comment]
Let us know if you're still interested in proposing a PR.

**Comment by cbueth** [comment]
Agreed, averaging is a sensible solution, over splitting the edge with two different speeds. Having the average is useful for when calculating shortest paths where the speed limit (travel time) is used as weight.

**Comment by gboeing** [comment]
A couple of thoughts. First, the purpose of the `add_edge_speeds` [function ](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.speed.add_edge_speeds) is to offer a quick-and-dirty imputation of missing maxspeed values to be overridden by the user with precise values whenever needed. Second (and as such), it's not designed to handle all edge cases or unorthodox values. We should handle [numeric speed limits](https://wiki.openstreetmap.org/wiki/Key:maxspeed#Values), but variable limits, implicit limits, zones, and extended tagging are outside the scope because there are hundreds of cases and other tools out there designed for this purpose.

I think splitting on | and calculating the average is a reasonable enhancement because it's both relatively common and relatively simple logic. But, we shouldn't handle invalid values (such as ";" separated lanes) or all the implicit values and zones (see [docs](https://wiki.openstreetmap.org/wiki/Key:maxspeed)). The user has full control via the `add_edge_speeds` function's `hwy_speeds` parameter and should exercise it to handle edge cases, implicit values, incorrect data, etc.

OSM recommends a couple of regex parsers here: https://wiki.openstreetmap.org/wiki/Key:maxspeed#Developers
