### ISSUE TITLE
ox.projection.project_graph raises an AttributeError: 'DataFrame' object has no attribute 'crs'

### ISSUE THREAD

**Issue by GeorgeKontsevik** [gboeing/osmnx#939]
I need to reproject my graph to the utm coordinate system. (The graph was calculated using `ox.graph_from_polygon`). When I run:
`network_utm = ox.projection.project_graph(G)`
It gives me an Error:
![image](https://user-images.githubusercontent.com/98597244/225437715-d4ff3163-3c12-439e-8d64-cba491ab58a9.png)

I thought it could be a possible duplicate to [this question](https://github.com/gboeing/osmnx/issues/387), but it's not.
What do you think I should do in this case?
Thanks in advance, George.

Python: 3.8.10, System: Ubuntu 20.04
Libraries versions:
osmnx                    1.2.2 
pyproj                   3.4.0 
geopandas                0.12.2 

P.s. I resolved  such a problem when I got GeoDataFrame from the graph and then I specified geometry to the GeoDataFrame using the following command:
`gdf_G['geometry'].apply(wkt.loads)`. Unfortunately, I can't do this when I want to reproject graph to the utm system.

P.s.2: It also has an open issue on StackOverflow [here](https://stackoverflow.com/questions/74501770/dataframe-object-has-no-attribute-crs). But there the update is fixing the problem. In my case, I've already updated the library.

P.s.3: I actually discovered that it is caused because `gdf_edge_proj` lost it's `crs` when the geometry column is dropped.
I've cached the crs, reused it later and it worked!

The screen with the fix is below:
As you can see I've marked it on lines 155 and 180
![image](https://user-images.githubusercontent.com/98597244/225447377-81e29be2-0b8d-4a0c-8ad6-62c43d0a6a27.png)

If it is really a bug, should I do a PR with this small fix (but re-do it better ofc)?

**Comment by gboeing** [comment]
Please provide a standalone, minimal, reproducible example to generate the problem.

**Comment by GeorgeKontsevik** [comment]
Sorry, that was my local issue with VSCode. Somehow it showed that I have 1.2.2. version, but ran the code with 1.1.1. version.
Thank you for your time, closing this issue. With 1.2.2. everything works just fine.

btw code was like this:
`G = ox.graph_from_place('Saint-Petersburg', network_type='drive', simplify=False)`
`network_utm = ox.projection.project_graph(G)`
