### ISSUE TITLE
Are geometry coordinates necessarily in the same direction as the edge?

### ISSUE THREAD

**Issue by migurski** [gboeing/osmnx#94]
In sample data, I’ve observed that edge geometry coordinates always seem to be in the same direction as the edge itself. The first coordinate matches the position of the first edge node. 

Is this strictly true, and can I trust it?

**Comment by kuanb** [comment]
That is true. The `add_edge_lengths` method relies on the way NetworkX holds edges (dictionary with keys sorted by "node from" to "node to").

For an example of OSMnx itself relying on this structure, see line: https://github.com/gboeing/osmnx/blob/fe5289c334369c2d453a54da7fceda01e1819506/osmnx/core.py#L1161

**Comment by migurski** [comment]
It is, thanks!
