### ISSUE TITLE
Missing weights in ox.shortest_path() cause it to minimize graph distance

### ISSUE THREAD

**Issue by nickodell** [gboeing/osmnx#954]
**Do not delete the following template. Fill it out completely.**

  - [x] I have read the OSMnx [contributing guidelines](../blob/main/CONTRIBUTING.md)
  - [x] I have read the OSMnx [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples)
  - [x] I have searched the open/closed issues and pull requests for others similar to mine

**Is your feature proposal related to a problem?**

If you ask OSMnx to minimize distance according to some metric, and that metric is not defined, OSMnx will find the minimum distance, but it finds the minimum *graph distance*. It's a really insidious problem, because for a lot of inputs, minimizing graph distance and minimizing length or travel time will do exactly the same thing. This is something that's easy to get wrong by making a typo or misunderstanding the docs.

Here are two StackOverflow users who ran into this:

* https://stackoverflow.com/questions/76267280/how-is-the-shortest-path-computed-with-osmnx-and-networkx  
* https://stackoverflow.com/questions/74944181/osmnx-not-choosing-shorter-route

**Describe the solution you'd like to propose**

For any of the functions in `osmnx/distance.py`, if they take a weight argument, and that weight is None on the entire network, then raise an exception. The exception message would also contain the name of the valid weights that the user could have used.

**Describe alternatives you've considered**

Some ways to detect the "missing weight" case:

* Look at every edge. If every edge is missing the weight, raise an error.
* Look at every edge. If any edge is missing the weight, raise an error.
* Look at the first edge. If that one is missing the weight, raise an error.

I have no strong opinion about which approach to take.

**Additional context**

Here's an example of how a real user ran into this problem:

```python
import osmnx as ox
import networkx as nx


Cities = ['Annecy, France','Epagny Metz-Tessy, France']
graph_city = ox.graph_from_place(Cities, network_type='drive', simplify=True, truncate_by_edge=False, clean_periphery =True)
graph_city = ox.project_graph(graph_city)
graph_city = ox.consolidate_intersections(graph_city, rebuild_graph=True, tolerance=15, dead_ends=True)


graph_city = ox.add_edge_speeds(graph_city)
graph_city = ox.add_edge_travel_times(graph_city)


DEP_node = 530
ARR_node  = 549


path_NX = nx.dijkstra_path(graph_city, DEP_node, ARR_node)
path_OX_L = ox.shortest_path(graph_city, DEP_node, ARR_node, weight='length')
path_OX_T = ox.shortest_path(graph_city, DEP_node, ARR_node, weight='time')  # Incorrect code!!! Should be weight='travel_time'

def get_travel_time(path):
    return int(sum(ox.utils_graph.get_route_edge_attributes(graph_city,path, 'travel_time')))

# The travel time for a path optimized for travel time should be equal to or better than a path optimized for length
assert get_travel_time(path_OX_T) <= get_travel_time(path_OX_L)
```

**Comment by gboeing** [comment]
I agree that this mistake can be hard for the user to notice, but I'm a bit on the fence about what to do about it. Essentially `osmnx.shortest_path` just wraps `networkx.shortest_path`, and this behavior (missing weight attributes minimizing topological distance) comes from networkx itself. If it should be fixed, it should probably be fixed upstream at networkx. That said, it would be easy enough for us to fix it in OSMnx itself... I'd just prefer to keep its functionality as similar to networkx as possible if this function is meant to be a thin wrapper.

**Comment by gboeing** [comment]
@nickodell perhaps a good "compromise" strategy would be to explicitly state in the docstring that this phenomenon can occur if weight attributes are nonexistent, in accordance with networkx functionality?

**Comment by nickodell** [comment]
@gboeing I was reading through the source code of networkx to figure out how this weight replacement is done. It appears I was wrong about how the replacement is done. It's not that it treats a network with None everywhere as a unit-weight graph, it replaces each weight which is None with 1. So if you have a network with some None weights, and some non-None weights, the None weights still affect the search.

Here's the code which does the replacement: https://github.com/networkx/networkx/blob/5d1b0e5c6053f677ce37e022068731b28a34a9ef/networkx/algorithms/shortest_paths/weighted.py#L41

Reading this code gave me an idea, though, which is that all of the networkx functions which accept a string as a weight also accept a function, so I can pass a function to it which looks up the weight and errors if it's not present.

I experimented with adding a _weight_function() and passing it to shortest_simplest_paths. I haven't gotten it to pass tests though, because one of the tests runs routing with missing weights. I'm planning to dig into that further, but haven't gotten around to it yet.

Links:

* PR: https://github.com/nickodell/osmnx/pull/3
* Failing test: https://github.com/nickodell/osmnx/actions/runs/5007381764/jobs/8973925820#step:7:48

**Comment by gboeing** [comment]
I feel like the weight function may over complicate this issue, or at least diverge from standard networkx behavior. In other words, there may be a use case in which a user explicitly wants to have some edge attributes missing/null... which would work in networkx directly but break here. If you feel a docstring edit is too subtle, what about an explicit warning if the weight is either missing or null on at least some edges? Something like:

```python
import numpy as np
import osmnx as ox
from warnings import warn
weight = 'distance'
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')

# this check would go in the distance module where needed
weights = np.array(tuple(G.edges(data=weight)))[:, 2]
if np.isnan(weights.astype(float)).any():
    warn(f'The attribute {weight!r} is missing or null on some edges.')
```

This would leave the behavior the same as networkx's, but it would warn the user as this is usually just a mistake rather than intentional. It would also ensure the weight is numeric (ie, convertible to float).

**Comment by gboeing** [comment]
@nickodell any thoughts on the sufficiency of that warning?

**Comment by nickodell** [comment]
@gboeing I think that's a great solution.
