### ISSUE TITLE
Use mock requests in tests?

### ISSUE THREAD

**Issue by migurski** [gboeing/osmnx#96]
I noticed the recent test failures due to imprecise geocoding, which seem to be a product of changing responses from the live Nominatim server. Would you be interested in a change to the test suite that mocks responses from remote servers, so that tests are no longer dependent on 3rd party services or an internet connection? We use these all over the place in `openaddresses/machine`, [to implement responses from observed ArcGIS and other servers](https://github.com/openaddresses/machine/blob/master/openaddr/tests/__init__.py#L88).

**Comment by gboeing** [comment]
@migurski yes that's a good idea. Relying on API responses in the tests isn't very efficient.

**Comment by migurski** [comment]
I may take a stab at this sometime. I see that you are already using `requests`, so supporting mocked responses in the tests should be pretty easy.
