### ISSUE TITLE
Example in README doesn't appear to work

### ISSUE THREAD

**Issue by bkj** [gboeing/osmnx#98]
Hi -- I'm trying to run the example given in the README and get the following error:

```
>>> import osmnx as ox
>>> G = ox.graph_from_place('Manhattan, New York, USA', network_type='drive')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bkj/.anaconda/lib/python2.7/site-packages/osmnx/core.py", line 1800, in graph_from_place
    clean_periphery=clean_periphery, infrastructure=infrastructure)
  File "/home/bkj/.anaconda/lib/python2.7/site-packages/osmnx/core.py", line 1664, in graph_from_polygon
    raise ValueError('Geometry must be a shapely Polygon or MultiPolygon')
ValueError: Geometry must be a shapely Polygon or MultiPolygon
```

Anyone have any ideas?

**Comment by bkj** [comment]
Turning on logging reveals that that query string returns a single point.  Changing to
```
G = ox.graph_from_place('Manhattan Island, New York City, New York, USA', network_type='drive')
```
appears to get the network, but then fails like:
```
Got all network data within polygon from API in 1 request(s) and 0.23 seconds
Creating networkx graph from downloaded OSM data...
Created graph with 20,681 nodes and 29,511 edges in 1.25 seconds
Added edge lengths to graph in 0.76 seconds
Identifying all nodes that lie outside the polygon...
Created r-tree spatial index for 20,681 points in 0.00 seconds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "osmnx/core.py", line 1800, in graph_from_place
    clean_periphery=clean_periphery, infrastructure=infrastructure)
  File "osmnx/core.py", line 1680, in graph_from_polygon
    G_buffered = truncate_graph_polygon(G_buffered, polygon_buffered, retain_all=True, truncate_by_edge=truncate_by_edge)
  File "osmnx/core.py", line 1125, in truncate_graph_polygon
    points_within_geometry = intersect_index_quadrats(gdf_nodes, polygon, quadrat_width=quadrat_width, min_num=min_num, buffer_amount=buffer_amount)
  File "osmnx/core.py", line 1064, in intersect_index_quadrats
    possible_matches_index = list(sindex.intersection(poly.bounds))
AttributeError: 'NoneType' object has no attribute 'intersection'
```

**Comment by kuanb** [comment]
The error is being thrown on this line:

`possible_matches_index = list(sindex.intersection(poly.bounds))`
https://github.com/gboeing/osmnx/blob/master/osmnx/core.py#L1064

The spatial index (`sindex`) is acquired a few lines up:
`sindex = gdf['geometry'].sindex`

In order for tree to work, you’ll need a few dependencies.
First, you’ll need libspatial index, before you can install rare:
Link: http://libspatialindex.github.io/

Once you have that, you should be able to install rtree.

If you happen to be on a Windows OS, Geoff has outlined how to get this all set up on Windows, here:
http://geoffboeing.com/2014/09/using-geopandas-windows/

**Comment by bkj** [comment]
OK thanks.  I was able to get it working w/ `'Manhattan Island, New York City, New York, USA'` as the query string, but still getting errors w/ `'Manhattan, New York City, New York, USA'`, so the README should probably be updated.

**Comment by kuanb** [comment]
Gotcha. 

In the future, if you want to check quickly if something is a point or not, Nominatim is the API being called to access the Polygons and you can just visually check by searching yourself on nominatim.openstreetmap.org and making sure that your query string does indeed point to a Polygon.

OSMnx could also add a check to ensure that the returned geometry is not a Point.

**Comment by gboeing** [comment]
> OSMnx could also add a check to ensure that the returned geometry is not a Point.

@kuanb I think this would be useful to reduce confusion. I looked into it at one point but wasn't sure of a neat way to do it due to how certain functions rely on each other. Open to suggestions.

@bkj I think Nominatim updated their engine recently as a couple of old geocoding examples were experiencing this. If you've got a query that works, would you mind creating a PR to update the example?

**Comment by bkj** [comment]
PR: #99
